import { cefrSource, coffeePack, coffeeQuestions } from './authoring'

// Explicit editorial attestation after reading every listed row and both variants.
const reviewed = {
  state: 'model-reviewed' as const,
  record:
    'src/content/dialogues/graded/coffee-order/coffee-pilot-review.md#a1 — Codex implementation agent, model-assisted reading, 2026-09-09; teacher reads 0',
}

export const a1 = coffeePack(
  'A1',
  {
    canDoZh: '在明确的二选一问题和中文提示帮助下，说出咖啡点单的基本需要。',
    complexityZh:
      '每轮一个具体决定；已说明可选项目，不要求解释理由或推断隐含条件。',
    scaffoldingZh: '简短问题、完整可选短句；可以请求重说，未识别时保留原话。',
    registerZh: '柜台礼貌用语，以 please 和简单否定表达选择或拒绝。',
    sourceBasis: [cefrSource],
  },
  coffeeQuestions('A1', [
    [
      'drink',
      'order',
      'Hello! An Americano or a filter coffee?',
      '选择美式或滴滤咖啡。默认热饮，不加奶和糖。',
      'americano',
      'An Americano, please.',
      'filter',
      'A filter coffee, please.',
      reviewed,
    ],
    [
      'size',
      'quantity',
      'Small or large?',
      '选择小杯或大杯。',
      'small',
      'Small, please.',
      'large',
      'Large, please.',
      reviewed,
    ],
    [
      'service',
      'serving',
      'For here or to go?',
      '说堂食或外带。',
      'here',
      'For here, please.',
      'takeaway',
      'To go, please.',
      reviewed,
    ],
    [
      'milk',
      'customize',
      'Would you like oat milk, or no milk?',
      '两种咖啡都可加燕麦奶，也可不加奶。',
      'none',
      'No milk, please.',
      'oat',
      'Oat milk, please.',
      reviewed,
    ],
    [
      'sweetener',
      'preference',
      'One sugar, or no sugar?',
      '选一份糖或不加糖。',
      'none',
      'No sugar, please.',
      'one',
      'One sugar, please.',
      reviewed,
    ],
    [
      'payment',
      'payment',
      'Cash or card?',
      '说明支付方式；练习不会扣款。',
      'cash',
      'Cash, please.',
      'card',
      'Card, please.',
      reviewed,
    ],
    [
      'receipt',
      'record',
      'Would you like a receipt?',
      '接受或拒绝收据。',
      'yes',
      'Yes, please.',
      'no',
      'No, thank you.',
      reviewed,
    ],
    [
      'name',
      'identify',
      'What name shall I call for your drink?',
      '给出模拟取餐名，或要求叫订单号码。',
      'sam',
      'Sam, please.',
      'number',
      'The order number, please.',
      reviewed,
    ],
    [
      'cooling',
      'temperature',
      'Your drink will be hot. Shall I add a little cold water?',
      '选择加少量冷水降温，或保持原样。',
      'water',
      'Yes, a little cold water, please.',
      'unchanged',
      'No, leave it hot, please.',
      reviewed,
    ],
    [
      'food',
      'upsell',
      'Would you like a cookie with your drink?',
      '接受饼干或明确只要饮品。',
      'cookie',
      'Yes, one cookie, please.',
      'none',
      'No, just the drink, please.',
      reviewed,
    ],
    [
      'timing',
      'schedule',
      'Shall I make it now or in ten minutes?',
      '选择现在制作或十分钟后制作。',
      'now',
      'Now, please.',
      'later',
      'In ten minutes, please.',
      reviewed,
    ],
    [
      'cup',
      'sustainability',
      'Shall I use your cup or one of ours?',
      '可用自带杯；若没有则用店里的杯具，杯型按之前选择。',
      'own',
      'My cup, please. Here it is.',
      'shop',
      'One of yours, please.',
      reviewed,
    ],
  ]),
  {
    clarify: 'I can repeat that.',
    struggle: 'Take your time. You can use either example.',
    offTopic: 'Let us return to your drink.',
    unknown: 'I have kept your words, but I cannot confirm that choice.',
    changed: 'I have updated that choice.',
    refusedClosing:
      'No problem. We will stop here. This practice has ended without a confirmed order.',
  },
  reviewed,
)
