import { cefrSource, coffeePack, coffeeQuestions } from './authoring'

// Explicit editorial attestation after reading every listed row and both variants.
const reviewed = {
  state: 'model-reviewed' as const,
  record:
    'src/content/dialogues/graded/coffee-order/coffee-pilot-review.md#a2 — Codex implementation agent, model-assisted reading, 2026-09-09; teacher reads 0',
}

export const a2 = coffeePack(
  'A2',
  {
    canDoZh: '处理常见柜台交换，在点单中表达简单偏好及下一步安排。',
    complexityZh: '连接选择与一个日常原因，区分制作时间、取餐方式及实际付款。',
    scaffoldingZh:
      '问题给出可用选项；参考回答提供 because 或简单补充句，不要求即兴论证。',
    registerZh: '友好、直接且礼貌，可婉拒推销或提出个人安排。',
    sourceBasis: [cefrSource],
  },
  coffeeQuestions('A2', [
    [
      'drink',
      'order',
      'We have Americanos and filter coffee. What would you like today?',
      '选一种在售咖啡，可补充简单原因。',
      'americano',
      'An Americano, please. I like a strong coffee.',
      'filter',
      'I would like a filter coffee today, please.',
      reviewed,
    ],
    [
      'size',
      'quantity',
      'Would you prefer a small drink or a large one?',
      '按需要选择杯型，不改变饮品种类。',
      'small',
      'A small one, please. I do not have much time.',
      'large',
      'A large one, please. I have a long morning ahead.',
      reviewed,
    ],
    [
      'service',
      'serving',
      'Are you staying here, or taking your drink away?',
      '交代堂食或外带以及简单行程。',
      'here',
      'I am staying here. I would like to sit by the window.',
      'takeaway',
      'I am taking it away. I need to catch a bus.',
      reviewed,
    ],
    [
      'milk',
      'customize',
      'Would you like to keep it black, or add some oat milk?',
      'black 在这里是不加奶；不要按颜色泛解。',
      'none',
      'Black, please. I do not usually have milk in coffee.',
      'oat',
      'Some oat milk, please. I like a milder taste.',
      reviewed,
    ],
    [
      'sweetener',
      'preference',
      'Would you like one sugar, or would you prefer it without sugar?',
      '有意识地选择甜度；不暗示店员已加糖。',
      'none',
      'Without sugar, please. I do not like sweet coffee.',
      'one',
      'One sugar, please. That is enough for me.',
      reviewed,
    ],
    [
      'payment',
      'payment',
      'You can pay by cash or card. Which would you like to use?',
      '选择支付方式；不要把模拟回答当成支付完成。',
      'cash',
      'I will pay in cash. I have some change.',
      'card',
      'By card, please. I do not have any cash today.',
      reviewed,
    ],
    [
      'receipt',
      'record',
      'Do you need a paper receipt for this order?',
      '说明是否需要纸质收据。',
      'yes',
      'Yes, please. I need to keep a record of what I spend.',
      'no',
      'No, thank you. I do not need a paper receipt.',
      reviewed,
    ],
    [
      'name',
      'identify',
      'May I have a name to call when your drink is ready?',
      '使用模拟名字，或选择订单号码保护隐私。',
      'sam',
      'You can call Sam. That is easy to remember.',
      'number',
      'Could you call my order number instead, please?',
      reviewed,
    ],
    [
      'cooling',
      'temperature',
      'The drink will be hot. Would a little cold water help?',
      '不更换为冰咖啡，只决定是否略微降温。',
      'water',
      'Yes, please add a little. I want to drink it soon.',
      'unchanged',
      'No, thank you. I can wait for it to cool.',
      reviewed,
    ],
    [
      'food',
      'upsell',
      'Would you like to add a cookie, or is the drink enough?',
      '接受加购，或礼貌拒绝并给出简单理由。',
      'cookie',
      'A cookie would be nice. I have not had a snack today.',
      'none',
      'Just the drink, thanks. I have already eaten.',
      reviewed,
    ],
    [
      'timing',
      'schedule',
      'Would you like your drink made now or in ten minutes?',
      '决定制作时点，而不是声称已经制作完。',
      'now',
      'Please make it now. I am ready to collect it.',
      'later',
      'In ten minutes, please. I need to make a quick phone call.',
      reviewed,
    ],
    [
      'cup',
      'sustainability',
      'Do you have your own cup, or shall we provide one?',
      '自带杯或店内杯具均不改变之前的堂食/外带选择。',
      'own',
      'I have my own cup. Here it is, and it is clean.',
      'shop',
      'Please provide one. I left my cup at home.',
      reviewed,
    ],
  ]),
  {
    clarify: 'Of course. Here are the choices again.',
    struggle: 'Take your time. Start with one of the example answers.',
    offTopic:
      'We can come back to that later. Let us finish this drink choice.',
    unknown:
      'Your words are saved for this practice, but this local lesson cannot confirm their meaning.',
    changed: 'That earlier choice has been updated.',
    refusedClosing:
      'That is fine. We will stop this practice without completing the order.',
  },
  reviewed,
)
