import { cefrSource, coffeePack, coffeeQuestions } from './authoring'

// Explicit editorial attestation after reading every listed row and both variants.
const reviewed = {
  state: 'model-reviewed' as const,
  record:
    'src/content/dialogues/graded/coffee-order/coffee-pilot-review.md#b1 — Codex implementation agent, model-assisted reading, 2026-09-09; teacher reads 0',
}

export const b1 = coffeePack(
  'B1',
  {
    canDoZh: '在熟悉的点单情境中核对信息，说明需要并应对行程或资源限制。',
    complexityZh:
      '用理由连接选择和后果，主动提出可行替代，不依靠统一的句尾扩写。',
    scaffoldingZh: '提供事实明确的情境和两种不同策略；允许停顿、重说或改选。',
    registerZh: '自然柜台语域，礼貌提出请求并解释限制，不使用书面投诉口吻。',
    sourceBasis: [cefrSource],
  },
  coffeeQuestions('B1', [
    [
      'drink',
      'order',
      'The Americano is stronger than our filter coffee today. Which would suit you?',
      '根据当天明确口味差异选饮品并解释。',
      'americano',
      'I will have the Americano because I would prefer a stronger flavour.',
      'filter',
      'The filter coffee sounds better. I am looking for something a little gentler.',
      reviewed,
    ],
    [
      'size',
      'quantity',
      'Our large size costs a little more. Would you like small or large?',
      '在容量和花费之间作日常选择。',
      'small',
      'A small one will do. I am trying to keep my spending down.',
      'large',
      'I will take a large one, since I will be working for a while.',
      reviewed,
    ],
    [
      'service',
      'serving',
      'There are seats available, but takeaway is also an option. What works for you?',
      '两个选项都有条件支持，不假定用户的行程。',
      'here',
      'I will stay here because I have time before my next appointment.',
      'takeaway',
      'Takeaway would be better. My meeting has been brought forward.',
      reviewed,
    ],
    [
      'milk',
      'customize',
      'We can serve either coffee black or with oat milk. Which would you prefer?',
      '只在已说明的配料范围内提出需求。',
      'none',
      'Please keep it black. I would like to taste the coffee on its own.',
      'oat',
      'Could you add oat milk? I enjoy coffee more when it tastes less bitter.',
      reviewed,
    ],
    [
      'sweetener',
      'preference',
      'Shall I leave out the sugar, or add one portion?',
      '用 leave out 表达省略；一份糖与无糖不同。',
      'none',
      'Please leave it out. I have been getting used to coffee without sugar.',
      'one',
      'One portion, please. I would rather start with a little than add too much.',
      reviewed,
    ],
    [
      'payment',
      'payment',
      'Cash and card are both working today. How would you prefer to pay?',
      '支付可用性已明确，不虚构机器故障。',
      'cash',
      'I will use cash this time because I am keeping to a daily budget.',
      'card',
      'I would prefer to use my card so I can check the payment later.',
      reviewed,
    ],
    [
      'receipt',
      'record',
      'Would a printed receipt be useful, or would you rather skip it?',
      '是否保留消费凭证，不声称报销必定成功。',
      'yes',
      'Please print one. I need to check whether I can claim this expense.',
      'no',
      'I would rather skip it. I already keep my own spending notes.',
      reviewed,
    ],
    [
      'name',
      'identify',
      'We can call your name or your order number. Which is easier for collection?',
      '协商取餐识别方式，不提供真实个人资料。',
      'sam',
      'Please call Sam. I will listen out for that name.',
      'number',
      'The order number would be easier, as I might miss my name in the noise.',
      reviewed,
    ],
    [
      'cooling',
      'temperature',
      'We can cool it slightly with a little water, although that will weaken the flavour. Shall we?',
      '在尽快饮用与口味浓度之间说明取舍。',
      'water',
      'Yes, a little water is fine. Being able to drink it soon matters more to me.',
      'unchanged',
      'No, please leave it as it is. I would rather wait and keep the flavour.',
      reviewed,
    ],
    [
      'food',
      'upsell',
      'We have cookies available as an extra. Would you like one with your drink?',
      '接受或拒绝加购都能推进点单。',
      'cookie',
      'Yes, I will add one because lunch will be later than usual today.',
      'none',
      'No, thanks. I brought a snack, so the drink is all I need.',
      reviewed,
    ],
    [
      'timing',
      'schedule',
      'We can prepare it now or start in ten minutes. Which fits your plans?',
      'start in ten minutes 指开始制作，不保证届时已拿到。',
      'now',
      'Please start now. I will wait nearby until it is ready.',
      'later',
      'Start in ten minutes, please. That should fit better with my break.',
      reviewed,
    ],
    [
      'cup',
      'sustainability',
      'You can use a clean cup of your own, or we can provide one. What would you prefer?',
      '不假定用户已经携带杯子。',
      'own',
      'I brought a clean cup, so I would like to use that and avoid another one.',
      'shop',
      'Please provide one today. I meant to bring mine, but I forgot it.',
      reviewed,
    ],
  ]),
  {
    clarify: 'Certainly. I will repeat the unresolved choice.',
    struggle:
      'There is no hurry. The examples show two possible ways to answer.',
    offTopic:
      'Let us set that aside and return to the order detail we have not settled.',
    unknown:
      'I have kept your original wording. This local lesson has no reviewed match for it, so the detail is still unconfirmed.',
    changed:
      'The earlier preference has been replaced; unrelated choices remain unchanged.',
    refusedClosing:
      'Understood. We will stop rather than complete the order. Any unfinished details remain unconfirmed.',
  },
  reviewed,
)
