import { cefrSource, coffeePack, coffeeQuestions } from './authoring'

// Explicit editorial attestation after reading every listed row and both variants.
const reviewed = {
  state: 'model-reviewed' as const,
  record:
    'src/content/dialogues/graded/coffee-order/coffee-pilot-review.md#b2 — Codex implementation agent, model-assisted reading, 2026-09-09; teacher reads 0',
}

export const b2 = coffeePack(
  'B2',
  {
    canDoZh:
      '在服务交际中说明并支持偏好，权衡实际后果，礼貌协商不完全理想的选项。',
    complexityZh:
      '处理预算、口味、时间及记录需求之间的取舍，使用让步、条件与比较。',
    scaffoldingZh: '给出必要事实但不规定唯一正确立场；示例展示不同的合理权衡。',
    registerZh: '流畅、合作的日常服务语域；不同意提议时避免生硬或过度道歉。',
    sourceBasis: [cefrSource],
  },
  coffeeQuestions('B2', [
    [
      'drink',
      'order',
      'Our Americano has a bolder flavour, while the filter coffee is more delicate. Which would you go for?',
      '对比口味并支撑选择，不把口味当成咖啡因含量。',
      'americano',
      'I would go for the Americano; a bolder flavour is what I am after this morning.',
      'filter',
      'The filter coffee appeals to me more. I would rather notice the subtler flavours than have something intense.',
      reviewed,
    ],
    [
      'size',
      'quantity',
      'The large size costs less per millilitre, but it is still more to drink. Which size makes sense for you?',
      '可以质疑性价比是否符合自身需要。',
      'small',
      'Small makes more sense for me. Even if the large is better value, I would probably leave some.',
      'large',
      'I will choose large. I have time to finish it, so the extra quantity will not go to waste.',
      reviewed,
    ],
    [
      'service',
      'serving',
      'You are welcome to stay, though the café may get busier soon. Would you prefer to sit in or take it away?',
      '面对可能的噪声与方便程度作选择。',
      'here',
      'I will sit in. A little background noise does not bother me, and it is convenient to stay here.',
      'takeaway',
      'I would prefer takeaway. I need somewhere quiet, so I will find a spot outside the café.',
      reviewed,
    ],
    [
      'milk',
      'customize',
      'Oat milk softens the flavour, but leaving it black keeps the coffee more distinct. What would you prefer?',
      '承认另一种选择的优点后说明立场。',
      'none',
      'I can see why oat milk is popular, but I would prefer to keep the coffee black and taste it on its own.',
      'oat',
      'Please add oat milk. I do not mind losing a little intensity in exchange for a smoother taste.',
      reviewed,
    ],
    [
      'sweetener',
      'preference',
      'We can add one portion of sugar or leave it out entirely. How would you like to balance the taste?',
      '不把无糖描述为健康保证；只讨论偏好。',
      'none',
      'Leave it out entirely, please. I would like to judge the coffee before adding anything sweet.',
      'one',
      'One portion would suit me. I want to soften the bitterness without making it particularly sweet.',
      reviewed,
    ],
    [
      'payment',
      'payment',
      'We accept both cash and card without an extra charge. Which would you prefer?',
      '已知无手续费，理由可来自记账或预算。',
      'cash',
      'I will pay cash. Using a fixed amount helps me keep track of small purchases.',
      'card',
      'Card would be more convenient, since I want this purchase to appear in my spending record.',
      reviewed,
    ],
    [
      'receipt',
      'record',
      'We can print an itemised receipt, or skip the paper. Which option would be more useful?',
      '区分明细凭证与一般支付记录。',
      'yes',
      'An itemised receipt, please. A payment record alone will not show what I bought.',
      'no',
      'Let us skip the paper. I only need to track the total, not keep an item-by-item record.',
      reviewed,
    ],
    [
      'name',
      'identify',
      'To avoid confusion at collection, would you rather we called a name or an order number?',
      '主动选择更合适的识别方式。',
      'sam',
      'Please use Sam. I will stay close enough to hear it, so that should work well.',
      'number',
      'An order number would be clearer. It avoids confusion if someone else has the same name.',
      reviewed,
    ],
    [
      'cooling',
      'temperature',
      'A little cold water would make it easier to drink immediately, but dilute it slightly. Would you like that adjustment?',
      '明确接受代价或提出等待这一替代策略。',
      'water',
      'Yes, please. I am happy to trade a little strength for being able to drink it straight away.',
      'unchanged',
      'I would rather leave it unchanged. Waiting a few minutes seems a better compromise than diluting it.',
      reviewed,
    ],
    [
      'food',
      'upsell',
      'A cookie is available separately, but there is no pressure to add one. Would you like to?',
      '接受附加消费或说明已满足需要。',
      'cookie',
      'Yes, I will add one. I had not planned on a snack, but it will save me another stop later.',
      'none',
      'Thanks for offering, but I will stick to the drink. That is all I had budgeted for.',
      reviewed,
    ],
    [
      'timing',
      'schedule',
      'We can start preparing it now or wait ten minutes. Which arrangement would suit your schedule better?',
      '讨论安排，不把预计开始时间误说成取餐保证。',
      'now',
      'Please start now. I would rather allow a little extra time than risk rushing later.',
      'later',
      'Waiting ten minutes would suit me better. My break starts then, and I would prefer it freshly made.',
      reviewed,
    ],
    [
      'cup',
      'sustainability',
      'We can use a clean cup you have brought or provide one suitable for your order. Which would you choose?',
      '与堂食或外带都相容，不突然限定为陶瓷杯。',
      'own',
      'I have brought a clean reusable cup. Please use that; it is a small way to cut down on waste.',
      'shop',
      'Please provide one this time. I support reusable cups, but I do not have mine with me.',
      reviewed,
    ],
  ]),
  {
    clarify: 'Certainly. Let us clarify the choice that is still open.',
    struggle:
      'Take a moment. You can use an example or keep your own wording unconfirmed.',
    offTopic:
      'That falls outside this coffee lesson. Let us return to the unresolved order detail.',
    unknown:
      'Your wording is retained, but this bounded local lesson cannot confirm its meaning or offer a reliable correction.',
    changed:
      'The supported change is recorded. Only choices that depend on the old detail need reconsideration.',
    refusedClosing:
      'Understood. We will leave the order incomplete and end this practice here.',
  },
  reviewed,
)
