import { diningPack, type Scene } from './authoring'

// Applied only after the postdraft item reading documented at this scene anchor.
const reviewed = {
  state: 'model-reviewed' as const,
  record:
    'src/content/dialogues/graded/dining/dining-review.md#food-allergy — Codex implementation agent; model-assisted postdraft reading 2026-09-09; teacher0',
}

const variantReview = {
  state: 'model-reviewed' as const,
  record:
    'src/content/dialogues/graded/dining/dining-review.md#self-review — food-allergy self-contained situations reread 2026-09-09; Codex implementation agent; teacher0',
}

const scene: Scene = {
  sceneId: 'dining-03',
  slug: 'food-allergy',
  situations: [
    '仅训练过敏沟通：你是询问餐厅的顾客，可模拟说明花生或芝麻过敏；询问汤或面包，尚未点餐。两者的配料及制作过程均待核实，店员不能保证安全，也未查到任何结果。所有检查都是请求，不是已完成检查；短练只说明过敏、食品和核实方式。拓展谈沟通辅助、记录及下一步，不提供医疗建议。',
    '仅训练沟通：你是为未来用餐准备信息的顾客，向餐厅店员询问汤或面包，可模拟说明花生或芝麻过敏。两种食品配料及制作过程都未知，所有检查均待进行，没有已确认的安全食品，默认不下单。拓展询问未来联系渠道和配料记录版本。练习不联系真实人员、不提供医疗建议、不保证食品安全。',
  ],
  closing:
    'Your information requests have been noted in this practice. Food suitability has not been verified, and no order has been placed.',
  partial:
    'Some information requests remain unconfirmed. This practice has ended without verifying food suitability or placing an order.',
  repairs: {
    clarify:
      'I can repeat the information question without guessing an answer about the food.',
    struggle: 'You can use a short example to state what you need checked.',
    offTopic: 'Let us return to the food information you want to request.',
    unknown:
      'I have kept your words, but I cannot confirm the request from that wording.',
    changed: 'Your stated information request has been updated.',
    refusedClosing:
      'We will stop the practice here. No food has been verified as suitable, and no order has been placed.',
  },
}

export const allergyPacks = {
  A1: diningPack(
    scene,
    'A1',
    {
      canDoZh: '借助明确选项说出过敏项目并请求配料信息。',
      complexityZh: '只表达和核实信息，不判断食物安全；逐轮一个具体请求。',
      scaffoldingZh: '短问句、中文释义和完整简短回应；允许重复或书写。',
      registerZh: '直接、礼貌地说明过敏不是喜好，能拒绝在不清楚时点餐。',
    },
    [
      [
        'allergen',
        'disclose',
        'Do you have a peanut allergy or a sesame allergy?',
        '模拟说明花生或芝麻过敏。',
        'peanut',
        'I have a peanut allergy.',
        'sesame',
        'I have a sesame allergy.',
        reviewed,
      ],
      [
        'food',
        'identify',
        'Are you asking about the soup or the bread?',
        '选择需要核实的食品，不表示点餐。',
        'soup',
        'The soup, please.',
        'bread',
        'The bread, please.',
        reviewed,
      ],
      [
        'check',
        'request',
        'Would you like the ingredient list, or should I ask the chef?',
        '请求配料表或请厨师核实。',
        'list',
        'The ingredient list, please.',
        'chef',
        'Please ask the chef.',
        reviewed,
      ],
      [
        'extras',
        'scope',
        'Should we also check sauces or toppings?',
        '选择额外检查的项目。',
        'sauce',
        'Please check the sauces too.',
        'topping',
        'Please check the toppings too.',
        reviewed,
      ],
      [
        'preparation',
        'process',
        'Would you like to ask about shared tools or work surfaces?',
        '请求制作过程信息，不保证风险已排除。',
        'tools',
        'Please ask about shared tools.',
        'surfaces',
        'Please ask about the work surfaces.',
        reviewed,
      ],
      [
        'uncertainty',
        'boundary',
        'If we cannot confirm the information, will you wait or avoid ordering?',
        '条件是假设，不是已经查明。',
        'wait',
        'I will wait for more information.',
        'noorder',
        'I will not order.',
        reviewed,
      ],
      [
        'format',
        'clarify',
        'Would you like me to speak slowly or write the question down?',
        '选择沟通帮助。',
        'slow',
        'Please speak slowly.',
        'write',
        'Please write it down.',
        reviewed,
      ],
      [
        'card',
        'support',
        'Would you like to show an allergy card?',
        '可用模拟卡，也可口头表达。',
        'card',
        'Yes, here is my allergy card.',
        'speak',
        'No, I will explain it.',
        reviewed,
      ],
      [
        'record',
        'record',
        'Would you like a copy of the questions we have listed?',
        '仅复制问题，不是安全证明。',
        'copy',
        'Yes, a paper copy, please.',
        'none',
        'No copy, thank you.',
        reviewed,
      ],
      [
        'next',
        'next-step',
        'For now, would you like to speak to the manager or leave the enquiry here?',
        '结束前决定是否提出进一步询问。',
        'manager',
        'I would like to speak to the manager.',
        'leave',
        'I will leave it here, thank you.',
        reviewed,
      ],
      [
        'contact',
        'follow-up',
        'For a later enquiry, would you prefer to call or visit?',
        '只练习未来联系意向。',
        'call',
        'I would prefer to call.',
        'visit',
        'I would prefer to visit.',
        reviewed,
      ],
      [
        'version',
        'verify-record',
        'Would you like us to check the current label or the current recipe?',
        '请求当前资料，不假定已有结果。',
        'label',
        'Please check the current label.',
        'recipe',
        'Please check the current recipe.',
        reviewed,
      ],
    ],
    variantReview,
  ),
  A2: diningPack(
    scene,
    'A2',
    {
      canDoZh: '在熟悉的餐厅交换中补充过敏信息并明确核实范围。',
      complexityZh: '连接配料、附加物和制作方式，保留未核实状态。',
      scaffoldingZh: '选项清楚，参考句加入简单原因及条件；支持口头或书写修复。',
      registerZh: '表达认真但不指责店员，礼貌拒绝凭猜测点单。',
    },
    [
      [
        'allergen',
        'disclose',
        'Which allergy do you need us to know about today?',
        '选择模拟过敏项目。',
        'peanut',
        'I am allergic to peanuts, so I need to check the food.',
        'sesame',
        'I have a sesame allergy and need some information first.',
        reviewed,
      ],
      [
        'food',
        'identify',
        'Which item would you like information about before ordering?',
        '汤或面包；只是询问。',
        'soup',
        'I want to ask about the soup before I order.',
        'bread',
        'Could we check the bread before I decide?',
        reviewed,
      ],
      [
        'check',
        'request',
        'Would reading the ingredients help, or would you prefer me to ask the chef?',
        '明确核实方式。',
        'list',
        'I would like to read the ingredient list first.',
        'chef',
        'Please ask the chef because I have a question about the recipe.',
        reviewed,
      ],
      [
        'extras',
        'scope',
        'Which extras should we include in the enquiry: sauces or toppings?',
        '不要从主食名称推断配料。',
        'sauce',
        'Please include sauces; they may have different ingredients.',
        'topping',
        'Please include toppings as well as the main item.',
        reviewed,
      ],
      [
        'preparation',
        'process',
        'Do you want to ask about shared utensils or the preparation area?',
        '提问而非确认已分开制作。',
        'utensils',
        'I want to know whether the utensils are shared.',
        'area',
        'Please ask how the preparation area is used.',
        reviewed,
      ],
      [
        'uncertainty',
        'boundary',
        'What would you do if the kitchen could not give you the information?',
        '说明不确定时的沟通决定。',
        'wait',
        'I would wait until someone could check it.',
        'noorder',
        'I would not order without that information.',
        reviewed,
      ],
      [
        'format',
        'clarify',
        'Would it be easier to hear the question slowly or see it in writing?',
        '请求交流辅助。',
        'slow',
        'Please say it slowly so I can follow.',
        'write',
        'It would be easier to read it, please.',
        reviewed,
      ],
      [
        'card',
        'support',
        'Do you have an allergy card to show, or would you rather explain in words?',
        '模拟资料或口头说明。',
        'card',
        'I have a card. Could you read it, please?',
        'words',
        'I would rather explain it in my own words.',
        reviewed,
      ],
      [
        'record',
        'record',
        'Would you like to keep the written list of our questions?',
        '这是问题清单，不是食品核实报告。',
        'paper',
        'Yes, a paper copy would help me remember.',
        'none',
        'No, thanks. I do not need a copy of the questions.',
        reviewed,
      ],
      [
        'next',
        'next-step',
        'Would speaking to the manager help, or would you like to finish the enquiry now?',
        '可提出升级或停止询问。',
        'manager',
        'I would like to ask the manager about the information process.',
        'finish',
        'I would like to finish here without placing an order.',
        reviewed,
      ],
      [
        'contact',
        'follow-up',
        'Would you rather phone before a future visit or ask in person?',
        '描述将来的联系偏好，不假定选择过展示卡片。',
        'phone',
        'I would rather phone before coming in.',
        'person',
        'I prefer to ask in person so I can ask more questions.',
        reviewed,
      ],
      [
        'version',
        'verify-record',
        'Should we look for the latest package label or the latest recipe record?',
        '只请求最新资料。',
        'label',
        'Please look for the latest label on the package.',
        'recipe',
        'The latest recipe record would be useful, please.',
        reviewed,
      ],
    ],
    variantReview,
  ),
  B1: diningPack(
    scene,
    'B1',
    {
      canDoZh: '说明过敏询问的原因、信息缺口和不确定时的边界。',
      complexityZh: '区分配料与制作过程，提出后续核实而不把查询当结果。',
      scaffoldingZh: '已知食品提供背景，示例连接请求与理由，允许请求改述。',
      registerZh: '明确而合作，能说明“过敏”而不是一般喜好。',
    },
    [
      [
        'allergen',
        'disclose',
        'What allergy should I mention when I ask the kitchen?',
        '使店员知道应核实的项目。',
        'peanut',
        'Please mention my peanut allergy; I am not just asking because of a taste preference.',
        'sesame',
        'Please tell them I have a sesame allergy, rather than simply disliking sesame.',
        reviewed,
      ],
      [
        'food',
        'identify',
        'Which menu item is your enquiry about, and why that one?',
        '确定汤或面包及询问原因。',
        'soup',
        'It is about the soup because I cannot tell all its ingredients from the name.',
        'bread',
        'It is about the bread because I would like to know what goes into it.',
        reviewed,
      ],
      [
        'check',
        'request',
        'Would an ingredient list be your starting point, or would you rather ask the chef directly?',
        '说明初步核实策略。',
        'list',
        'The list would be a useful starting point, although I may still have questions.',
        'chef',
        'I would rather ask the chef directly because I need to discuss how the item is made.',
        reviewed,
      ],
      [
        'extras',
        'scope',
        'What else should the enquiry cover beyond the main item?',
        '扩展到酱汁或装饰配料。',
        'sauce',
        'Please include any sauces, since a plain menu description may not mention them.',
        'topping',
        'Please include toppings, even if they are added only just before serving.',
        reviewed,
      ],
      [
        'preparation',
        'process',
        'Which part of preparation would you like the kitchen to explain?',
        '选择工具或区域信息。',
        'utensils',
        'I would like to know whether the same utensils are used for different foods.',
        'surfaces',
        'Could they explain whether the work surfaces are shared with other preparation?',
        reviewed,
      ],
      [
        'uncertainty',
        'boundary',
        'If the information remains uncertain, how would you want to proceed?',
        '不凭未查明信息点单。',
        'wait',
        'I would keep the order on hold while we seek clearer information.',
        'noorder',
        'I would decide not to order rather than rely on a guess.',
        reviewed,
      ],
      [
        'format',
        'clarify',
        'What would help you check that you have understood the questions we are sending to the kitchen?',
        '核对问句本身，不假装收到答复。',
        'repeat',
        'Please repeat them slowly so I can check that nothing is missing.',
        'written',
        'A written list would help me check each point before it goes to the kitchen.',
        reviewed,
      ],
      [
        'card',
        'support',
        'Would a written allergy card support the enquiry, or would you prefer to explain yourself?',
        '表达辅助资料选择。',
        'card',
        'I can show a card so the kitchen has the allergy written clearly.',
        'explain',
        'I would prefer to explain myself and check that the key word is understood.',
        reviewed,
      ],
      [
        'record',
        'record',
        'Would you find it useful to keep a copy of the questions, even though they are not answers?',
        '明确记录边界。',
        'copy',
        'Yes, it would help me remember what still needs checking.',
        'none',
        'No, I understand the questions and do not need a separate copy.',
        reviewed,
      ],
      [
        'next',
        'next-step',
        'Would you like the manager involved at this stage, or is this enough discussion for now?',
        '提出进一步沟通或停止。',
        'manager',
        'Please involve the manager; they may be able to explain who can check the details.',
        'finish',
        'This is enough for now. I will end the enquiry without ordering.',
        reviewed,
      ],
      [
        'contact',
        'follow-up',
        'How would you prefer to make a future enquiry when the kitchen has more time?',
        '联系意向不产生真实联系。',
        'phone',
        'I would phone ahead so staff could tell me when to speak to the right person.',
        'visit',
        'I would visit at a quieter time so we could discuss the questions face to face.',
        reviewed,
      ],
      [
        'version',
        'verify-record',
        'Which current record would you like checked first?',
        '区分包装标签与厨房配方。',
        'label',
        'Please start with the current package label, since suppliers can change.',
        'recipe',
        'Please start with the current kitchen recipe, rather than an older menu description.',
        reviewed,
      ],
    ],
    variantReview,
  ),
  B2: diningPack(
    scene,
    'B2',
    {
      canDoZh: '区分证据来源与保证，协商核实过程并表达信息边界。',
      complexityZh: '权衡书面资料和人员说明，限定可接受的信息质量。',
      scaffoldingZh:
        '情境明确未知事项；示例展示让步与反问式核实，不输出医学结论。',
      registerZh: '坚持准确但不指责，拒绝把友善安慰当证据。',
    },
    [
      [
        'allergen',
        'disclose',
        'What exactly should I record, so this is not mistaken for a general dietary preference?',
        '明确记录过敏项目，不评估严重程度。',
        'peanut',
        'Please record a peanut allergy, not simply a preference to avoid peanuts.',
        'sesame',
        'A sesame allergy is the relevant information; a general note saying dietary preference would be too vague.',
        reviewed,
      ],
      [
        'food',
        'identify',
        'Which item needs closer examination before you could consider ordering it?',
        '食品仍未获确认。',
        'soup',
        'The soup needs closer examination because its description does not reveal the full recipe.',
        'bread',
        'The bread does; its appearance alone does not tell me enough about its ingredients.',
        reviewed,
      ],
      [
        'check',
        'request',
        'Would you prioritise the written ingredients or a conversation with the chef, given that neither is yet available?',
        '选择查询入口，不声称已得到信息。',
        'list',
        'I would start with the written ingredients, while recognising that preparation needs a separate discussion.',
        'chef',
        'I would prioritise speaking to the chef so we can distinguish the recipe from the way it is prepared.',
        reviewed,
      ],
      [
        'extras',
        'scope',
        'Where might the scope of our ingredient enquiry be too narrow?',
        '指出附加项目可能未被询问。',
        'sauce',
        'It would be too narrow if we left out sauces just because they are served separately.',
        'topping',
        'We should include final toppings rather than assume the base recipe covers everything served.',
        reviewed,
      ],
      [
        'preparation',
        'process',
        'What preparation question would add information that an ingredient list cannot provide?',
        '询问过程，不推断安全结论。',
        'tools',
        'Whether utensils are shared would tell us something the ingredient list cannot establish.',
        'area',
        'I would ask how the preparation area is shared, rather than treating the ingredient list as the whole picture.',
        reviewed,
      ],
      [
        'uncertainty',
        'boundary',
        'How would you respond to reassurance that was not backed by a completed check?',
        '礼貌拒绝无依据安慰。',
        'pause',
        'I would appreciate the intention but keep the order paused until the information could be checked.',
        'decline',
        'I would politely decline to order; reassurance alone would not answer my questions.',
        reviewed,
      ],
      [
        'format',
        'clarify',
        'How can we make sure the wording of the enquiry reflects what you mean?',
        '核对问题，非提供检查结果。',
        'readback',
        'Please read the questions back slowly so I can correct any ambiguity before they are passed on.',
        'written',
        'Let me see the questions in writing; that would help me spot any missing qualification.',
        reviewed,
      ],
      [
        'card',
        'support',
        'Would showing a card improve clarity, or would you prefer to retain control of the explanation?',
        '不强迫披露额外私人资料。',
        'card',
        'A card would improve clarity, provided it is used to support the enquiry rather than replace checking.',
        'explain',
        'I would prefer to explain verbally, so I can clarify the exact information I am asking for.',
        reviewed,
      ],
      [
        'record',
        'record',
        'Would a copy of the enquiry be useful, despite not being a record of verified findings?',
        '记录范围诚实。',
        'copy',
        'Yes, it would give me a checklist of outstanding questions, not evidence that the food is suitable.',
        'none',
        'I do not need a copy; the important point is that the answers are still outstanding.',
        reviewed,
      ],
      [
        'next',
        'next-step',
        'Would involving a manager help coordinate the checks, or would you rather close the enquiry?',
        '不承诺经理能提供结论。',
        'manager',
        'Please ask the manager to coordinate the enquiry, without assuming they can immediately resolve it.',
        'close',
        'I would rather close it here; that is a decision not to order, not a complaint about your efforts.',
        reviewed,
      ],
      [
        'contact',
        'follow-up',
        'For a later visit, would advance contact or an in-person discussion give you a better opportunity to ask questions?',
        '权衡交流方式。',
        'advance',
        'Advance contact would give staff time to identify who can answer, although it would not itself settle the questions.',
        'person',
        'An in-person discussion would let me clarify follow-up questions immediately, even if it meant visiting at a quieter time.',
        reviewed,
      ],
      [
        'version',
        'verify-record',
        'Which document would help establish that we are discussing current information rather than an old assumption?',
        '只请求核实资料时效。',
        'label',
        'The label on the current supply would be relevant; an older label might no longer describe it.',
        'recipe',
        'The current recipe record would help, especially if the kitchen has changed how the dish is made.',
        reviewed,
      ],
    ],
    variantReview,
  ),
  C1: diningPack(
    scene,
    'C1',
    {
      canDoZh: '以准确限定和自然修复表达过敏沟通的证据要求。',
      complexityZh:
        '处理记录失真、范围遗漏与信息时效，区分协作意图和未经验证的结论。',
      scaffoldingZh:
        '较少句型支架，示例展示如何澄清潜在误解；不作风险判断或处置建议。',
      registerZh: '坚定但体谅服务限制，避免承诺、归责或迫使店员保证安全。',
    },
    [
      [
        'allergen',
        'disclose',
        'How should I phrase the note so that the nature of your enquiry is unambiguous?',
        '明确过敏而非偏好。',
        'peanut',
        'Please specify a peanut allergy. Describing it merely as an aversion would change the nature of what I am asking you to check.',
        'sesame',
        'Please use sesame allergy rather than a broad dietary restriction; precision matters more here than a softer label.',
        reviewed,
      ],
      [
        'food',
        'identify',
        'Which item should we focus on without allowing its name to stand in for a full description?',
        '指明待核实食品和信息差。',
        'soup',
        'The soup. Its name gives an impression of the dish, but I would not treat that as an account of everything in it.',
        'bread',
        'The bread, please. What looks like a simple item may still need a fuller ingredient description.',
        reviewed,
      ],
      [
        'check',
        'request',
        'What would be the most useful starting point, bearing in mind that a document and a conversation serve different purposes?',
        '区分证据来源的功能。',
        'document',
        'I would start with the ingredient record for a concrete reference, then leave room to ask about matters it does not cover.',
        'conversation',
        'A conversation with the chef would help frame the enquiry, provided any uncertainty is identified rather than smoothed over.',
        reviewed,
      ],
      [
        'extras',
        'scope',
        'What could inadvertently fall outside the enquiry if we described it only as a recipe check?',
        '指出查核范围的隐含遗漏。',
        'sauces',
        'Sauces served alongside could be overlooked; I would like the enquiry to cover those as well as what is cooked into the dish.',
        'toppings',
        'Finishing toppings could fall through that gap, so I would explicitly include what is added at the point of serving.',
        reviewed,
      ],
      [
        'preparation',
        'process',
        'Which distinction about preparation would you most want the kitchen to address?',
        '选择过程维度而非推断可食用。',
        'utensils',
        'I would distinguish ingredients from utensil use; knowing the recipe does not tell us whether equipment is shared.',
        'surfaces',
        'I would distinguish the recipe from the use of work surfaces, rather than assume one description settles both issues.',
        reviewed,
      ],
      [
        'uncertainty',
        'boundary',
        'If a colleague offered well-meant reassurance without checking, how would you keep the boundary clear?',
        '尊重对方但不接受未经证实结论。',
        'pause',
        'I would acknowledge the reassurance but explain that I am keeping the order on hold pending checked information.',
        'decline',
        'I would thank them for trying to help and decline to order, making clear that I am not asking them to improvise a guarantee.',
        reviewed,
      ],
      [
        'format',
        'clarify',
        'How would you like to check the wording before the enquiry is passed on?',
        '不把复述问题变成复述已确认答案。',
        'spoken',
        'A careful read-back would let me catch any loss of meaning between what I said and what is recorded.',
        'written',
        'I would prefer to review the written questions; it is easier to notice an omitted qualification when I can see the wording.',
        reviewed,
      ],
      [
        'card',
        'support',
        'Would an allergy card make the exchange more precise, or would you rather clarify the details yourself?',
        '辅助卡不代替检查；无多余个人资料要求。',
        'card',
        'The card would be a useful reference, though I would not want it treated as a substitute for this particular enquiry.',
        'myself',
        'I would rather clarify the details myself, so the conversation stays focused on what needs checking rather than on a general summary.',
        reviewed,
      ],
      [
        'record',
        'record',
        'Would retaining this list help, as long as its status as unanswered questions remains explicit?',
        '保留记录的意义和限制。',
        'retain',
        'Yes. It would preserve the scope of the enquiry, not establish that any answer has been obtained or verified.',
        'none',
        'I would not retain it; a written list might look more conclusive than it is if separated from this conversation.',
        reviewed,
      ],
      [
        'next',
        'next-step',
        'Would management involvement be useful for coordination, or would you prefer to draw the enquiry to a close?',
        '不施压要求安全保证。',
        'manager',
        'Coordination would be useful, provided the manager is asked to organise the checks rather than endorse an answer they cannot substantiate.',
        'close',
        'I would prefer to draw it to a close without ordering. That respects the limits of the information available.',
        reviewed,
      ],
      [
        'contact',
        'follow-up',
        'How would you arrange a future enquiry while allowing staff a realistic opportunity to respond?',
        '计划下一次沟通，不实际发送。',
        'advance',
        'I would contact the restaurant in advance to ask when the relevant person is available, not to demand an immediate assurance.',
        'visit',
        'I would arrange to visit at a quieter time, when follow-up questions are less likely to be lost in the rush.',
        reviewed,
      ],
      [
        'version',
        'verify-record',
        'What would help prevent a previously accurate record from being treated as automatically current?',
        '限定资料时效，不作食品安全结论。',
        'label',
        'Checking the label on the current supply would address that gap; a familiar brand name would not establish that nothing has changed.',
        'recipe',
        'I would ask for the currently used recipe record and its revision date, rather than rely on a description retained from an earlier visit.',
        reviewed,
      ],
    ],
    variantReview,
  ),
}
