import { diningPack, type Scene } from './authoring'

// Applied only after the postdraft item reading documented at this scene anchor.
const reviewed = {
  state: 'model-reviewed' as const,
  record:
    'src/content/dialogues/graded/dining/dining-review.md#price-discount — Codex implementation agent; model-assisted postdraft reading 2026-09-09; teacher0',
}

const variantReview = {
  state: 'model-reviewed' as const,
  record:
    'src/content/dialogues/graded/dining/dining-review.md#self-review — price-discount self-contained situations reread 2026-09-09; Codex implementation agent; teacher0',
}

const scene: Scene = {
  sceneId: 'dining-06',
  slug: 'price-discount',
  situations: [
    '虚构商店议价，顾客与店员交谈：新手提袋£20，轻微擦痕展示手提袋£16且仅一只；这两项标价不再降价。另有小收纳包£12，两只新手提袋的组合价£36，不叠加折扣。礼品包装另加£2，现金/卡同价。默认不加包装、未购买未付款；可询问但店员可拒绝额外折扣。短练只确定比较对象、预算和想核实的信息；拓展可决定继续核对总额或不买。',
    '虚构商店，顾客先询价再考虑：新手提袋£20，轻微擦痕的展示袋£16且一只有货，两标价不再降低；小收纳包£12，两只新袋组合£36，不叠加折扣，礼品包装另加£2，现金/卡同价。默认不加包装、未购买。可申请免费保留所选单只手提袋30分钟，不能延长，待店员办理。拓展谈保留请求和检查表面/缝线；比较小包或组合不自动换购。无真实预订、购买或支付。',
  ],
  closing:
    'Your price enquiry and the choices discussed are noted. This was a fictional negotiation; nothing has been bought, charged or reserved.',
  partial:
    'Some choices in the price enquiry remain unconfirmed. The practice has ended without a purchase, charge or reservation.',
  repairs: {
    clarify: 'I can restate the listed prices and the question.',
    struggle: 'You can make a short request or politely decline.',
    offTopic: 'Let us return to the price enquiry.',
    unknown:
      'Your words are saved, but I cannot confirm a price choice from them.',
    changed: 'That preference in the price enquiry has been updated.',
    refusedClosing:
      'We can stop without a deal. This practice is closed and no money has changed hands.',
  },
}

export const pricePacks = {
  A1: diningPack(
    scene,
    'A1',
    {
      canDoZh: '询问价格、说预算并接受或拒绝明确报价。',
      complexityZh: '具体商品与固定价格，能提出一次简单降价请求并尊重拒绝。',
      scaffoldingZh: '价格背景明确，简短二选一配中文提示，默认无附加消费。',
      registerZh: '礼貌买卖交流，不用威胁或虚假理由议价。',
    },
    [
      [
        'item',
        'identify',
        'The new tote is twenty pounds; the display tote is sixteen. Which interests you?',
        '新袋£20或展示袋£16。',
        'new',
        'The new tote, please.',
        'display',
        'The display tote, please.',
        reviewed,
      ],
      [
        'budget',
        'budget',
        'Is your budget eighteen pounds or twenty pounds?',
        '预算不是承诺购买。',
        'eighteen',
        'Eighteen pounds.',
        'twenty',
        'Twenty pounds.',
        reviewed,
      ],
      [
        'check',
        'clarify',
        'Would you like to check the price or the condition of the tote?',
        '选择先核实的信息。',
        'price',
        'The price, please.',
        'condition',
        'The condition, please.',
        reviewed,
      ],
      [
        'request',
        'negotiate',
        'Would you like to ask about a lower price, or leave the listed price as it is?',
        '可以问一次，不保证降价。',
        'ask',
        'Could you lower the price?',
        'leave',
        'The listed price is clear, thank you.',
        reviewed,
      ],
      [
        'boundary',
        'respect-refusal',
        'We cannot lower either listed price. Would you like to compare options or stop discussing discounts?',
        '接受拒绝；后续仍可查询信息。',
        'compare',
        'I would like to compare the options.',
        'stop',
        'I will stop asking for a discount.',
        reviewed,
      ],
      [
        'alternative',
        'alternative',
        'The small pouch is twelve pounds. Would you like to see it?',
        '只看替代品，不自动改选。',
        'look',
        'Yes, please show me the pouch.',
        'no',
        'No, thank you. I want to look at totes.',
        reviewed,
      ],
      [
        'bundle',
        'compare',
        'Two new totes are thirty-six pounds. Would you like the price explained?',
        '组合只提供信息，不强迫买两个。',
        'explain',
        'Yes, please explain the price.',
        'no',
        'No, I only need information about one tote.',
        reviewed,
      ],
      [
        'wrap',
        'extras',
        'Gift wrapping is two pounds extra. Would you want it if you bought a bag?',
        '假设购买，另收费不改变已知预算。',
        'yes',
        'Yes, I would want gift wrapping.',
        'no',
        'No gift wrapping, thanks.',
        reviewed,
      ],
      [
        'payment',
        'payment',
        'If you buy later, would you use cash or a card?',
        '不发生支付。',
        'cash',
        'I would use cash.',
        'card',
        'I would use a card.',
        reviewed,
      ],
      [
        'decision',
        'decision',
        'Would you like to check an option against your budget, or leave without buying?',
        '不保证预算足够，保留最终核对。',
        'check',
        'I would like to check an option against my budget.',
        'leave',
        'I will leave without buying.',
        reviewed,
      ],
      [
        'hold',
        'reservation',
        'We can hold a tote for thirty minutes. Would you like to request that?',
        '只是请求模拟保留，尚未办理。',
        'request',
        'Yes, please hold it for thirty minutes.',
        'no',
        'No, do not hold it.',
        reviewed,
      ],
      [
        'inspect',
        'inspect',
        'Would you like to check the surface or the stitching?',
        '所有候选袋都可检查，不保证无缺陷。',
        'surface',
        'The surface, please.',
        'stitching',
        'The stitching, please.',
        reviewed,
      ],
    ],
    variantReview,
  ),
  A2: diningPack(
    scene,
    'A2',
    {
      canDoZh: '用简单理由比较标价与预算，了解额外费用并礼貌拒绝。',
      complexityZh: '区分商品标价、组合价及包装费，不将询问当作成交。',
      scaffoldingZh: '所有数字明示，回答可用简单条件句表达购买意向。',
      registerZh: '允许一次请求和无交易结束，拒绝后不继续施压。',
    },
    [
      [
        'item',
        'identify',
        'Would you like to look at the twenty-pound new tote or the sixteen-pound display one?',
        '展示袋有轻微擦痕。',
        'new',
        'I would like to look at the new tote.',
        'display',
        'Could I see the display tote with the lower price?',
        reviewed,
      ],
      [
        'budget',
        'budget',
        'How much have you planned to spend: eighteen pounds or twenty?',
        '说明上限，不表示任意组合都买得起。',
        'eighteen',
        'I have planned to spend up to eighteen pounds.',
        'twenty',
        'My limit is twenty pounds today.',
        reviewed,
      ],
      [
        'check',
        'clarify',
        'What would you like to check first about the tote?',
        '价格或状态尚可询问。',
        'price',
        'I would like to check the listed price first.',
        'condition',
        'I want to check its condition before I decide.',
        reviewed,
      ],
      [
        'request',
        'negotiate',
        'Do you want to ask whether there is any further discount?',
        '询问并不承诺一定有。',
        'ask',
        'Yes, is there any further discount on this tote?',
        'no',
        'No, I understand the listed price.',
        reviewed,
      ],
      [
        'boundary',
        'respect-refusal',
        'There is no further discount on either tote. Would you like to compare them or leave the discount question there?',
        '尊重标价不可再降。',
        'compare',
        'That is fine. I would like to compare the options.',
        'leave',
        'I understand. I will leave the discount question there.',
        reviewed,
      ],
      [
        'alternative',
        'alternative',
        'Would you like to see the twelve-pound pouch as a different option?',
        '可看看或拒绝小包。',
        'see',
        'Yes, I would like to see what the pouch is like.',
        'no',
        'No, I need the shape of a tote, not a pouch.',
        reviewed,
      ],
      [
        'bundle',
        'compare',
        'Would you like me to explain the thirty-six-pound offer for two new totes?',
        '不推断顾客要买两个。',
        'explain',
        'Yes, please explain how much each tote would cost.',
        'no',
        'No, thank you. I am only looking for one tote.',
        reviewed,
      ],
      [
        'wrap',
        'extras',
        'If you bought a bag, would you add gift wrapping for two pounds?',
        '包装另加，最终仍要核对总额。',
        'yes',
        'I would like gift wrapping if I bought one.',
        'no',
        'I would not need wrapping because the bag is for me.',
        reviewed,
      ],
      [
        'payment',
        'payment',
        'Cash and card have the same prices. Which would you use for a later purchase?',
        '无现金折扣，不执行付款。',
        'cash',
        'I would pay in cash if I bought something.',
        'card',
        'I would use my card for a purchase.',
        reviewed,
      ],
      [
        'decision',
        'decision',
        'Would you like to check the total for an option, or decide not to buy today?',
        '总额尚未核算，不承诺成交。',
        'total',
        'Please help me check an option against my spending limit.',
        'no',
        'I have decided not to buy anything today.',
        reviewed,
      ],
      [
        'hold',
        'reservation',
        'Would a free thirty-minute hold help while you think about one of the totes?',
        '请求而非真实保留。',
        'hold',
        'Yes, I would like to request the thirty-minute hold.',
        'none',
        'No, please leave the tote available for other customers.',
        reviewed,
      ],
      [
        'inspect',
        'inspect',
        'Which would you like to look at more closely: the surface or the stitching?',
        '新袋/展示袋均可检查。',
        'surface',
        'I would like to look closely at the surface.',
        'stitching',
        'Please let me check the stitching first.',
        reviewed,
      ],
    ],
    variantReview,
  ),
  B1: diningPack(
    scene,
    'B1',
    {
      canDoZh: '说明预算与用途，并在降价被拒绝后比较真实替代。',
      complexityZh:
        '连接价差、状态、数量和额外费用，保留核对总额或不买的选择。',
      scaffoldingZh: '固定数值和条件支持理由表达，答案不假定算过未选组合。',
      registerZh: '坦率说明限制，礼貌接受拒绝，不编造竞争报价。',
    },
    [
      [
        'item',
        'identify',
        'Which tote would you start with: new at twenty pounds, or the marked display one at sixteen?',
        '展示品折价对应擦痕。',
        'new',
        'I would start with the new tote because I want to see an unmarked option.',
        'display',
        'I would start with the display tote because a small mark may not bother me.',
        reviewed,
      ],
      [
        'budget',
        'budget',
        'What spending limit should guide your comparison?',
        '可选18或20英镑总预算。',
        'eighteen',
        'Eighteen pounds is my limit, so I need to keep the full cost within that.',
        'twenty',
        'I have set aside twenty pounds, including any extras I might choose.',
        reviewed,
      ],
      [
        'check',
        'clarify',
        'What information do you need first to judge the tote properly?',
        '选择价格依据或物品状态。',
        'price',
        'I want to confirm the price so I know which figure I am comparing with my budget.',
        'condition',
        'I need to look at the condition because the price alone does not tell me whether it suits me.',
        reviewed,
      ],
      [
        'request',
        'negotiate',
        'Would you make a further price request, or are you content to work from the listed figures?',
        '合法诚实地问一次。',
        'request',
        'Could you offer any further reduction, or are the listed figures final?',
        'listed',
        'I am content to compare the listed figures without asking for a further reduction.',
        reviewed,
      ],
      [
        'boundary',
        'respect-refusal',
        'Both listed prices are final. How would you like to handle that limit?',
        '接受拒绝但可继续询问。',
        'compare',
        'I understand the limit and would like to compare what is available within it.',
        'stop',
        'I will not pursue another discount; thank you for making the limit clear.',
        reviewed,
      ],
      [
        'alternative',
        'alternative',
        'Would seeing the twelve-pound pouch help, even though it serves a different purpose from a tote?',
        '较便宜不等于可替代。',
        'see',
        'It might help me judge the difference, so I would like to see it before ruling it out.',
        'decline',
        'I would rather not; I need a tote’s carrying space, so the lower price would not solve my problem.',
        reviewed,
      ],
      [
        'bundle',
        'compare',
        'Would a breakdown of the thirty-six-pound two-tote offer be useful, even if you only need one?',
        '信息比较不增加购买数量。',
        'breakdown',
        'Yes, I would like to understand the eighteen-pound price per tote without committing to two.',
        'no',
        'No, the total for two is not relevant to what I need today.',
        reviewed,
      ],
      [
        'wrap',
        'extras',
        'Would you consider the two-pound wrapping charge worthwhile if you made a purchase?',
        '支出意向不自动认定预算可行。',
        'worth',
        'I would consider it worthwhile for a gift, but I would still need to include it in the total.',
        'skip',
        'I would skip the wrapping because I can pack a gift myself if necessary.',
        reviewed,
      ],
      [
        'payment',
        'payment',
        'With no price difference between cash and card, which would be easier for you?',
        '明确无支付方式折扣。',
        'cash',
        'Cash would be easier because I have brought money for this shopping trip.',
        'card',
        'Card would be easier because I prefer to keep a transaction record.',
        reviewed,
      ],
      [
        'decision',
        'decision',
        'Are you ready to compare a final total with your limit, or would you rather walk away today?',
        '不因选择产品而自动买下。',
        'compare',
        'I would like to compare a complete total with my limit before committing to anything.',
        'leave',
        'I would rather walk away today; the enquiry has helped me decide not to buy.',
        reviewed,
      ],
      [
        'hold',
        'reservation',
        'Would you like to request the free thirty-minute hold while you consider a tote?',
        '不已完成预留，不保证延时。',
        'request',
        'Yes, I would like to request it, and I understand it would last only thirty minutes.',
        'decline',
        'No, I do not want the shop to set one aside while I remain undecided.',
        reviewed,
      ],
      [
        'inspect',
        'inspect',
        'Which physical detail would you want to examine before making a decision?',
        '检查表面或针脚。',
        'surface',
        'I would examine the surface to decide whether any visible marks matter to me.',
        'stitching',
        'I would look at the stitching because the construction matters more to me than appearance.',
        reviewed,
      ],
    ],
    variantReview,
  ),
  B2: diningPack(
    scene,
    'B2',
    {
      canDoZh: '区分折扣、单位节省与总支出，提出并收回有边界的议价请求。',
      complexityZh:
        '权衡展示品状态和价格，避免为折扣增加不需要的数量；尊重最终报价。',
      scaffoldingZh: '明确虚构价目不叠加优惠，示例给理由、条件和让步。',
      registerZh: '协商坚定但尊重拒绝，认可无交易也可结束沟通。',
    },
    [
      [
        'item',
        'identify',
        'How would you weigh a new tote at twenty pounds against the lightly marked display tote at sixteen?',
        '状态和价格作权衡。',
        'new',
        'I would examine the new tote first; an unmarked finish may justify the difference for my purpose.',
        'display',
        'I would examine the display tote first, since a minor surface mark may be an acceptable trade-off for the lower price.',
        reviewed,
      ],
      [
        'budget',
        'budget',
        'What firm limit should the overall cost respect, rather than just the base price?',
        '全额预算18或20。',
        'eighteen',
        'The overall cost must stay within eighteen pounds, even if an extra seems inexpensive on its own.',
        'twenty',
        'Twenty pounds is the ceiling for the whole purchase, not just the item before extras.',
        reviewed,
      ],
      [
        'check',
        'clarify',
        'Would confirming the exact price or examining the condition contribute more to your initial comparison?',
        '信息优先级而非已检查结果。',
        'price',
        'Confirming the exact price would give me a reliable basis for comparing the options.',
        'condition',
        'Examining the condition would help more, because a lower price is only useful if the item is acceptable.',
        reviewed,
      ],
      [
        'request',
        'negotiate',
        'Would you ask whether there is room below the listed price, or avoid reopening that question?',
        '只问余地，不假定应得。',
        'ask',
        'I would ask once whether there is any room below the listed price, without treating a reduction as an entitlement.',
        'avoid',
        'I would avoid reopening it and judge the options on the prices already stated.',
        reviewed,
      ],
      [
        'boundary',
        'respect-refusal',
        'There is no room for a further reduction on either tote. What is your response?',
        '拒绝后的合法不同策略。',
        'compare',
        'I accept that constraint and would compare the available options rather than continue bargaining.',
        'close',
        'Thank you for being clear. I will close the discount discussion and consider the remaining information.',
        reviewed,
      ],
      [
        'alternative',
        'alternative',
        'Would the twelve-pound pouch be worth considering, given that a cheaper product may not meet the same need?',
        '比较目的适配，不一定选择便宜品。',
        'consider',
        'It is worth looking at, provided I compare what it can carry rather than focus only on the saving.',
        'reject',
        'I would reject it as a substitute because its smaller format would not meet the purpose of a tote.',
        reviewed,
      ],
      [
        'bundle',
        'compare',
        'Would you like to unpack the difference between saving per tote and spending thirty-six pounds on two?',
        '18每只不等于总价18。',
        'explain',
        'Yes, the unit saving is worth understanding, even though the total for two exceeds what I intend to spend.',
        'no',
        'No, I do not need a breakdown; buying two would add an unnecessary item regardless of the unit saving.',
        reviewed,
      ],
      [
        'wrap',
        'extras',
        'Does two-pound gift wrapping add enough value to be considered in a possible final total?',
        '这里只表达价值判断，预算仍待核对。',
        'yes',
        'It could add enough value for a present, as long as the final total still respects my limit.',
        'no',
        'It does not add enough value for me; I would prefer to handle the presentation myself.',
        reviewed,
      ],
      [
        'payment',
        'payment',
        'Since neither cash nor card changes the price, what would determine your payment preference?',
        '支付渠道理由不虚构交易。',
        'cash',
        'Keeping to cash would help me separate this spending from other expenses.',
        'card',
        'A card record would make it easier to track the purchase afterwards, if I decide to proceed.',
        reviewed,
      ],
      [
        'decision',
        'decision',
        'Would you want a final cost check before proceeding, or has the comparison led you to decline a purchase?',
        '最后仍可无交易。',
        'check',
        'I would want the item and any extras checked against my limit before I agree to a purchase.',
        'decline',
        'The comparison has led me to decline a purchase; I do not need to reach a deal merely because we have discussed one.',
        reviewed,
      ],
      [
        'hold',
        'reservation',
        'Would a thirty-minute hold be useful, knowing that the example policy does not allow an extension?',
        '真实限制，不强求延长。',
        'hold',
        'It would be useful, so I would request the hold without assuming I could extend it later.',
        'no',
        'I would not request it, because I cannot make a decision within that time and would rather leave the stock available.',
        reviewed,
      ],
      [
        'inspect',
        'inspect',
        'Would surface appearance or the quality of the stitching deserve closer examination for your intended use?',
        '不将检查偏好当质量结论。',
        'surface',
        'Surface appearance deserves a closer look because I want to judge whether any marks would be noticeable in use.',
        'stitching',
        'The stitching deserves closer examination because construction matters more to me than a cosmetic difference.',
        reviewed,
      ],
    ],
    variantReview,
  ),
  C1: diningPack(
    scene,
    'C1',
    {
      canDoZh: '以精确限定处理价格、价值和总预算的复杂区别，尊重协商边界。',
      complexityZh:
        '识别折扣叙述中的数量陷阱及目的偏移，作不失分寸的请求和退出。',
      scaffoldingZh:
        '保留明确数值和政策背景，参考回答组织立场和限定，不暗示成交。',
      registerZh: '自然买卖交流，避免对抗、虚构报价或把让步当义务。',
    },
    [
      [
        'item',
        'identify',
        'Which would you want to examine first, once the difference in condition is weighed against the four-pound gap?',
        '£20新袋与£16展示袋相差£4。',
        'new',
        'The new tote first. I want to see whether the unmarked finish is worth the extra four pounds to me, rather than assuming it must be.',
        'display',
        'The display tote first. A modest cosmetic compromise may be reasonable, but I would want to judge the mark rather than buy the discount.',
        reviewed,
      ],
      [
        'budget',
        'budget',
        'Where is your actual ceiling once incidental charges are included?',
        '18或20为全额上限。',
        'eighteen',
        'Eighteen pounds is the ceiling for everything; splitting the price into small charges would not change that limit.',
        'twenty',
        'Twenty pounds in total. I am leaving no separate allowance outside that figure for extras that might sound negligible.',
        reviewed,
      ],
      [
        'check',
        'clarify',
        'What needs establishing first so that the comparison is about the offer itself, not an impression of a bargain?',
        '选择核实内容，不声称已核实。',
        'price',
        'I would establish the exact quoted price first, so the comparison has a concrete basis rather than a vague sense of saving.',
        'condition',
        'I would establish the condition first; otherwise I would be comparing prices without knowing whether the goods serve the same purpose for me.',
        reviewed,
      ],
      [
        'request',
        'negotiate',
        'Would you raise the possibility of a further concession, or regard the stated prices as the basis for deciding?',
        '问一次而非施压。',
        'raise',
        'I would ask whether a further concession is possible, while making it clear that a refusal is an answer I can accept.',
        'basis',
        'I would take the stated prices as the basis for deciding. Repeated bargaining would add little to understanding the offer.',
        reviewed,
      ],
      [
        'boundary',
        'respect-refusal',
        'Neither price can be reduced further. How would you keep the conversation constructive from here?',
        '拒绝后不坚持要求让步。',
        'compare',
        'I would accept that boundary and turn to the merits of the available options, rather than repackage the same request.',
        'close',
        'I would explicitly close the discount question. That leaves room for a useful enquiry without implying that persistence should change your answer.',
        reviewed,
      ],
      [
        'alternative',
        'alternative',
        'Would looking at the twelve-pound pouch broaden your options, or distract from what you came to find?',
        '目的不同也可拒绝廉价替代。',
        'broaden',
        'It could broaden the options if I assess it against the actual need, rather than let the lower figure make the decision for me.',
        'distract',
        'It would distract from the purpose. A pouch that cannot do the job is not an economical alternative simply because it costs less.',
        reviewed,
      ],
      [
        'bundle',
        'compare',
        'Would discussing the two-for-thirty-six offer help distinguish a unit saving from a sensible purchase?',
        '总额36，不把每只18说成可单买18。',
        'discuss',
        'Yes. Eighteen per tote is a unit figure conditional on buying two, not an offer to sell a single new tote for eighteen.',
        'decline',
        'No further discussion is needed; a lower unit figure would not justify buying a second tote I have no use for.',
        reviewed,
      ],
      [
        'wrap',
        'extras',
        'Would the two-pound wrapping charge earn its place in a possible total, or be an avoidable addition?',
        '包装意向不扩张预算。',
        'value',
        'It could earn its place for a gift, but only within the overall ceiling; its small size would not exempt it from the budget.',
        'avoid',
        'It would be avoidable for me. I can arrange the presentation myself without letting an extra service drive the purchase.',
        reviewed,
      ],
      [
        'payment',
        'payment',
        'With price held constant, what practical consideration would govern your choice of cash or card?',
        '两种支付方式价格相同。',
        'cash',
        'I would use cash to keep this expense ring-fenced; that is a budgeting preference, not an expectation of a cash discount.',
        'card',
        'I would use a card for the transaction record, assuming I proceed; the method itself does not make the offer better value.',
        reviewed,
      ],
      [
        'decision',
        'decision',
        'Would a final total check help you reach a decision, or is walking away the better conclusion?',
        '无交易亦为有效沟通结果。',
        'check',
        'A final check would help, provided it covers the full amount and does not treat my interest as consent to buy.',
        'leave',
        'Walking away is the better conclusion. I have learned what I needed without acquiring an obligation to make the discussion end in a sale.',
        reviewed,
      ],
      [
        'hold',
        'reservation',
        'Would the thirty-minute hold genuinely help, given that the time limit is firm?',
        '不承诺现实库存或预留。',
        'hold',
        'It would give me enough time to think, so I would request it on those terms rather than plan to renegotiate the deadline.',
        'no',
        'It would not help within that limit. I would rather decline the hold than tie up stock on an assumption of extra time.',
        reviewed,
      ],
      [
        'inspect',
        'inspect',
        'Which aspect warrants a closer look, rather than being inferred from the price tag?',
        '检查请求不是质量保证。',
        'surface',
        'The surface condition warrants a closer look; neither a higher price nor a reduction tells me how noticeable a mark will be.',
        'stitching',
        'The stitching warrants examination. I would rather inspect how it is put together than let the price stand in for evidence of construction quality.',
        reviewed,
      ],
    ],
    variantReview,
  ),
}
