import { diningPack, type Scene } from './authoring'

// Applied only after the postdraft item reading documented at this scene anchor.
const reviewed = {
  state: 'model-reviewed' as const,
  record:
    'src/content/dialogues/graded/dining/dining-review.md#restaurant-order — Codex implementation agent; model-assisted postdraft reading 2026-09-09; teacher0',
}

const breadReview = {
  state: 'model-reviewed' as const,
  record:
    'src/content/dialogues/graded/dining/dining-review.md#fix-round-1 — A2/B1 bread question and owned pair reread with both timing choices and extended paths; Codex implementation agent, 2026-09-09; teacher0',
}

const variantReview = {
  state: 'model-reviewed' as const,
  record:
    'src/content/dialogues/graded/dining/dining-review.md#self-review — restaurant-order self-contained situations reread 2026-09-09; Codex implementation agent; teacher0',
}

const scene: Scene = {
  sceneId: 'dining-02',
  slug: 'restaurant-order',
  situations: [
    '虚构餐厅，你与同行者用餐，分别选择自己的主食。顾客与服务员面谈：番茄意面和蘑菇意面均有货，均可选小份/普通份、辣椒、配菜和面包；默认不加辣椒、无配菜。无气水/气泡水免费，餐食约20分钟，吧台可安排较安静座位。短练仅选自己的主食、份量和饮品，标准再谈定制，拓展加现场服务细节；只是练习，不下单或扣款。',
    '虚构餐厅，你与同行者安排稍后的用餐，分别选择自己的主食。番茄意面和蘑菇意面均有货，都可选小份/普通份、辣椒另放或加入、配菜、面包；默认不加辣椒、无配菜。无气水/气泡水免费，餐食约20分钟；可申请安静吧台座或普通桌。拓展讨论座位与用餐目的而非现场账单和支付。只是练习，不产生预约、订单或扣款。',
  ],
  closing:
    'We have noted the choices discussed in this restaurant practice. No real order, booking or payment has been made.',
  partial:
    'Some restaurant choices remain unconfirmed. This practice has ended without a real order or payment.',
  repairs: {
    clarify: 'I can explain that menu choice again.',
    struggle: 'Take your time; the two examples show possible replies.',
    offTopic: 'Let us return to the meal arrangements.',
    unknown: 'Your words are saved, but that meal choice is not confirmed.',
    changed: 'That meal preference has been updated in the practice.',
    refusedClosing:
      'We can stop here. No order has been placed, and the practice is closed.',
  },
}

export const restaurantPacks = {
  A1: diningPack(
    scene,
    'A1',
    {
      canDoZh: '在服务员给出具体选项后，表达一餐的基本需要。',
      complexityZh: '一次决定一个项目，前三轮只选择主食、份量和饮品。',
      scaffoldingZh: '明确二选一及中文提示；拓展增加简单服务请求，不要求解释。',
      registerZh: '简短礼貌柜台表达，能用简单否定拒绝额外项目。',
    },
    [
      [
        'meal',
        'order',
        'Tomato pasta or mushroom pasta?',
        '选番茄意面或蘑菇意面。',
        'tomato',
        'Tomato pasta, please.',
        'mushroom',
        'Mushroom pasta, please.',
        reviewed,
      ],
      [
        'portion',
        'quantity',
        'A small portion or a regular portion?',
        '选择份量。',
        'small',
        'A small portion, please.',
        'regular',
        'A regular portion, please.',
        reviewed,
      ],
      [
        'drink',
        'drink',
        'Still water or sparkling water?',
        '选择无气水或气泡水。',
        'still',
        'Still water, please.',
        'sparkling',
        'Sparkling water, please.',
        reviewed,
      ],
      [
        'chilli',
        'customize',
        'Would you like chilli on your pasta?',
        '两种意面都可加辣椒。',
        'yes',
        'Yes, a little chilli, please.',
        'no',
        'No chilli, please.',
        reviewed,
      ],
      [
        'side',
        'accompaniment',
        'Would you like a side salad?',
        '接受或拒绝配菜。',
        'salad',
        'Yes, a side salad, please.',
        'none',
        'No salad, thank you.',
        reviewed,
      ],
      [
        'timing',
        'schedule',
        'The food takes twenty minutes. Can you wait?',
        '能等20分钟，或请求更快的选择；不保证一定加速。',
        'wait',
        'Yes, I can wait.',
        'ask',
        'That is too long. Is there a quicker option?',
        reviewed,
      ],
      [
        'bread',
        'extra',
        'While we discuss the timing, would you like bread?',
        '正在安排时间，接受面包或拒绝，不表示已接受20分钟等待。',
        'yes',
        'Yes, some bread, please.',
        'no',
        'No bread, thanks.',
        reviewed,
      ],
      [
        'cutlery',
        'equipment',
        'A fork only, or a fork and spoon?',
        '选餐具。',
        'fork',
        'Just a fork, please.',
        'both',
        'A fork and spoon, please.',
        reviewed,
      ],
      [
        'bill',
        'billing',
        'One bill for the table, or separate bills?',
        '选择合并或分开账单。',
        'one',
        'One bill, please.',
        'separate',
        'Separate bills, please.',
        reviewed,
      ],
      [
        'payment',
        'payment',
        'How would you like to pay when you finish?',
        '说明稍后支付方式，不执行付款。',
        'card',
        'By card, please.',
        'cash',
        'In cash, please.',
        reviewed,
      ],
      [
        'seat',
        'access',
        'A quiet seat at the counter, or a table?',
        '选择安静吧台或普通桌。',
        'quiet',
        'A quiet seat, please.',
        'table',
        'A table, please.',
        reviewed,
      ],
      [
        'purpose',
        'occasion',
        'Is this a quick meal or a celebration?',
        '说明用餐目的。',
        'quick',
        'A quick meal.',
        'celebrate',
        'A birthday meal.',
        reviewed,
      ],
    ],
    variantReview,
  ),
  A2: diningPack(
    scene,
    'A2',
    {
      canDoZh: '按菜单完成熟悉的点餐交换，并说明简单服务偏好。',
      complexityZh: '连接份量与食量、时间与安排；拓展加入账单或座位需求。',
      scaffoldingZh: '问题提供已知选项，回答使用简单原因和时间短语。',
      registerZh: '日常服务语域，以 could I 和明确请求表达需要。',
    },
    [
      [
        'meal',
        'order',
        'Which pasta would you like from our two choices?',
        '番茄或蘑菇意面均有货。',
        'tomato',
        'I would like the tomato pasta today.',
        'mushroom',
        'Could I have the mushroom pasta?',
        reviewed,
      ],
      [
        'portion',
        'quantity',
        'How hungry are you: would a small or regular portion suit you?',
        '用食量说明份量选择。',
        'small',
        'A small portion is enough; I am not very hungry.',
        'regular',
        'I am quite hungry, so a regular portion, please.',
        reviewed,
      ],
      [
        'drink',
        'drink',
        'We have still and sparkling water. Which would you prefer?',
        '选择水的种类。',
        'still',
        'I prefer still water with my meal.',
        'sparkling',
        'I would like sparkling water for a change.',
        reviewed,
      ],
      [
        'chilli',
        'customize',
        'Shall we add chilli, or leave your pasta mild?',
        '说加辣或不加辣。',
        'yes',
        'Please add a little chilli. I like spicy food.',
        'no',
        'Please keep it mild; I do not like chilli.',
        reviewed,
      ],
      [
        'side',
        'accompaniment',
        'Would you like a salad as an extra side?',
        '配菜是另加项目。',
        'salad',
        'Yes, I would like some salad with the pasta.',
        'none',
        'No, the pasta will be enough for me.',
        reviewed,
      ],
      [
        'timing',
        'schedule',
        'Preparation takes about twenty minutes. Does that fit your plans?',
        '接受等待或请求了解更快选项。',
        'wait',
        'Yes, I have enough time to wait.',
        'ask',
        'I need to leave soon. Could you suggest something quicker?',
        reviewed,
      ],
      [
        'bread',
        'extra',
        'While we discuss the timing, would you like some bread?',
        '正在讨论出餐时间；这里只选择面包，不确认愿意等意面。',
        'yes',
        'Yes, I would like some bread, please.',
        'no',
        'No, thanks. I do not need any bread.',
        breadReview,
      ],
      [
        'cutlery',
        'equipment',
        'Would a fork be enough, or would you like a spoon as well?',
        '选择是否加勺。',
        'fork',
        'A fork is enough for me, thanks.',
        'both',
        'Could I have a spoon as well as a fork?',
        reviewed,
      ],
      [
        'bill',
        'billing',
        'Should we put the table on one bill or make separate bills?',
        '说明账单安排。',
        'one',
        'Please put everything on one bill.',
        'separate',
        'We would like separate bills, please.',
        reviewed,
      ],
      [
        'payment',
        'payment',
        'Will you use cash or a card at the end of the meal?',
        '仅确认支付意向。',
        'cash',
        'I will use cash when we finish.',
        'card',
        'I would like to pay by card later.',
        reviewed,
      ],
      [
        'seat',
        'access',
        'For your visit, would you prefer the quiet counter or a normal table?',
        '规划座位。',
        'quiet',
        'The quiet counter sounds good; I want to read.',
        'table',
        'A normal table, please. I am meeting a friend.',
        reviewed,
      ],
      [
        'purpose',
        'occasion',
        'What kind of visit are you planning: an everyday meal or a special occasion?',
        '说明日常用餐或庆祝。',
        'everyday',
        'It is just an everyday lunch.',
        'special',
        'It is a small birthday celebration.',
        reviewed,
      ],
    ],
    variantReview,
  ),
  B1: diningPack(
    scene,
    'B1',
    {
      canDoZh: '解释选择理由并处理用餐时间等小障碍。',
      complexityZh: '联系个人目的与菜单和服务条件，提出尚未获保证的替代请求。',
      scaffoldingZh: '保留明确情境和参考回答，减少逐词提示；每轮可给简短理由。',
      registerZh: '合作、清晰地说明不便，不把请求当作服务员承诺。',
    },
    [
      [
        'meal',
        'order',
        'What appeals to you about either the tomato or the mushroom pasta?',
        '选主食并说简短理由。',
        'tomato',
        'I will choose the tomato pasta because I fancy a familiar flavour.',
        'mushroom',
        'The mushroom pasta appeals to me because I rarely make it at home.',
        reviewed,
      ],
      [
        'portion',
        'quantity',
        'Would you prefer a small portion, or do you need a full regular serving?',
        '结合后续计划选择。',
        'small',
        'A small portion would suit me because I am eating again later.',
        'regular',
        'I need a regular portion; I missed lunch.',
        reviewed,
      ],
      [
        'drink',
        'drink',
        'Which water would work better for you, still or sparkling?',
        '选择饮水并解释。',
        'still',
        'Still water would be better because I do not enjoy fizzy drinks.',
        'sparkling',
        'I will have sparkling water; I like the bubbles with a meal.',
        reviewed,
      ],
      [
        'chilli',
        'customize',
        'How would you like us to handle the optional chilli?',
        '明确加辣椒或另放。',
        'mixed',
        'Please mix in a little chilli so the flavour is spread through the pasta.',
        'separate',
        'Could you serve the chilli separately so I can add it myself?',
        reviewed,
      ],
      [
        'side',
        'accompaniment',
        'Would adding a side salad improve the meal for you?',
        '接受或说明不需要配菜。',
        'salad',
        'Yes, I would like something fresh alongside the pasta.',
        'none',
        'No, I would rather keep the meal simple and skip the salad.',
        reviewed,
      ],
      [
        'timing',
        'schedule',
        'The kitchen needs around twenty minutes; how does that affect your plans?',
        '面对等待说明决定。',
        'wait',
        'That still gives me enough time, so I am happy to wait.',
        'ask',
        'That leaves me very little time to eat. Could we discuss a quicker option?',
        reviewed,
      ],
      [
        'bread',
        'extra',
        'While we look at the timing options, would some bread be welcome?',
        '仍在商量出餐时间；接受或拒绝面包不改变之前的时间需要。',
        'bread',
        'Some bread would help because I have not eaten for hours.',
        'none',
        'I would prefer not to add bread; I want to save my appetite for the meal.',
        breadReview,
      ],
      [
        'cutlery',
        'equipment',
        'Do you manage pasta with a fork alone, or would a spoon help?',
        '表达餐具使用偏好。',
        'fork',
        'A fork is fine; that is what I normally use.',
        'both',
        'A spoon would help me, so could you bring both?',
        reviewed,
      ],
      [
        'bill',
        'billing',
        'How should we organise the bill for your table?',
        '说明合账或分账策略。',
        'one',
        'One bill is easiest; we can settle up between ourselves.',
        'separate',
        'Separate bills would help us keep track of our own meals.',
        reviewed,
      ],
      [
        'payment',
        'payment',
        'Which payment method are you planning to use?',
        '说明现金或卡的原因。',
        'card',
        'I plan to use my card because I do not have much cash with me.',
        'cash',
        'I will pay in cash because I have set some aside for this meal.',
        reviewed,
      ],
      [
        'seat',
        'access',
        'Would the quiet counter or a standard table better suit your visit?',
        '按用餐任务权衡座位。',
        'quiet',
        'The quiet counter would suit me because I need to read before eating.',
        'table',
        'A standard table would be better because I need space for my bag.',
        reviewed,
      ],
      [
        'purpose',
        'occasion',
        'Is there anything about the occasion that would help us plan the service?',
        '提供普通用餐或庆祝需求。',
        'ordinary',
        'It is an ordinary meal, so there is no special occasion to plan around.',
        'birthday',
        'It is a birthday, but we would like a relaxed meal without a public announcement.',
        reviewed,
      ],
    ],
    variantReview,
  ),
  B2: diningPack(
    scene,
    'B2',
    {
      canDoZh: '权衡餐食与服务安排，协商可接受的调整而不预设成功。',
      complexityZh: '区分偏好和必要条件，说明取舍与对他人的影响。',
      scaffoldingZh:
        '已知菜单支持推理，参考答案展示理由与让步，允许自行措辞但只确认收录形式。',
      registerZh: '礼貌且有主张，拒绝额外服务时避免贬低对方。',
    },
    [
      [
        'meal',
        'order',
        'How would you choose between the two pasta dishes if familiarity and variety both matter?',
        '权衡熟悉感和变化。',
        'tomato',
        'I would favour the tomato pasta; familiarity matters more to me tonight than trying something different.',
        'mushroom',
        'I would choose the mushroom pasta because a change is worth stepping outside my usual order.',
        reviewed,
      ],
      [
        'portion',
        'quantity',
        'Would a smaller serving meet your needs, or would it leave you wanting more?',
        '说明份量与避免浪费的取舍。',
        'small',
        'A small serving should be enough, and I would rather avoid ordering more than I can finish.',
        'regular',
        'A regular serving makes more sense; a smaller one would probably leave me hungry.',
        reviewed,
      ],
      [
        'drink',
        'drink',
        'Do you see any advantage in sparkling water, or would you rather keep to still?',
        '清楚表达偏好而不作健康断言。',
        'sparkling',
        'Sparkling water feels more like a treat, even though still water would be perfectly adequate.',
        'still',
        'I would keep to still water; I find bubbles distracting when I am eating.',
        reviewed,
      ],
      [
        'chilli',
        'customize',
        'Would you trust the kitchen to add a little chilli, or prefer to control it at the table?',
        '选择加辣方式。',
        'kitchen',
        'A little added by the kitchen is fine; I do not need exact control over the heat.',
        'table',
        'I would prefer it on the side so I can adjust the heat without changing the whole dish.',
        reviewed,
      ],
      [
        'side',
        'accompaniment',
        'Is a side salad worth adding, given that you already have a main course?',
        '权衡配菜价值。',
        'salad',
        'Yes, the contrast in texture would make it worthwhile for me.',
        'none',
        'I do not think so; I would rather enjoy the main course without another plate.',
        reviewed,
      ],
      [
        'timing',
        'schedule',
        'With a twenty-minute kitchen wait, would you accept the delay or explore another option?',
        '协商时间，不保证提供替代。',
        'wait',
        'I can accommodate that delay, provided the estimate is reasonably reliable.',
        'explore',
        'I would like to explore another option; twenty minutes would make the rest of my evening rather tight.',
        reviewed,
      ],
      [
        'bread',
        'extra',
        'While the timing is being discussed, would bread be welcome or would you prefer not to add anything?',
        '接受面包不表示已接受原来的等待时间。',
        'bread',
        'Some bread would be welcome, although I would only want a little.',
        'none',
        'I would prefer not to add anything; I do not need bread as well.',
        reviewed,
      ],
      [
        'cutlery',
        'equipment',
        'Would you prefer the usual fork, or an additional spoon to make eating easier?',
        '提出具体工具需要。',
        'fork',
        'The usual fork is all I need; there is no need to bring extra cutlery.',
        'both',
        'An additional spoon would be useful, especially for gathering the last of the sauce.',
        reviewed,
      ],
      [
        'bill',
        'billing',
        'Would one bill simplify things, or do you need separate records for the table?',
        '权衡处理便利与个人记录。',
        'one',
        'One bill would simplify the service, and we can divide the cost ourselves.',
        'separate',
        'Separate bills would be preferable because each person needs a record of their own order.',
        reviewed,
      ],
      [
        'payment',
        'payment',
        'Would paying by card or in cash fit your arrangements better?',
        '仅说明支付计划。',
        'card',
        'Card would be more convenient, as I prefer to keep a digital record of spending.',
        'cash',
        'Cash would suit me better; I am keeping this meal within a fixed cash budget.',
        reviewed,
      ],
      [
        'seat',
        'access',
        'Would you trade the space of a table for a quieter seat at the counter?',
        '两个座位各有收益。',
        'quiet',
        'Yes, I would give up some space for a quieter place to read.',
        'table',
        'No, I would prioritise table space, even if the room is a little livelier.',
        reviewed,
      ],
      [
        'purpose',
        'occasion',
        'How much attention would you want the staff to give the occasion?',
        '不要从之前回答推断一定庆祝。',
        'routine',
        'It is just a routine meal, so ordinary service would be ideal.',
        'discreet',
        'It is a celebration, but discreet service would suit us better than anything theatrical.',
        reviewed,
      ],
    ],
    variantReview,
  ),
  C1: diningPack(
    scene,
    'C1',
    {
      canDoZh: '细致限定餐饮服务需求，处理偏好、条件和社交分寸。',
      complexityZh:
        '区别真正约束与次要偏好，修正可能的隐含理解，作有条件的协商。',
      scaffoldingZh:
        '问题给出情境而非逐词模板，回答示范自然让步和限定；十轮推进不同安排。',
      registerZh: '自然服务口语中的委婉异议和精确表达，不以生硬长句堆高等级。',
    },
    [
      [
        'meal',
        'order',
        'Are you drawn to the tomato pasta for its familiarity, or would the mushroom dish be a welcome change?',
        '区分本次选择与长期偏好。',
        'tomato',
        'The tomato pasta, I think. I am after something familiar tonight, rather than ruling out the mushroom dish altogether.',
        'mushroom',
        'I would welcome the mushroom dish for a change; there is nothing wrong with the tomato option, but it is my usual choice.',
        reviewed,
      ],
      [
        'portion',
        'quantity',
        'How would you balance having enough to eat against the possibility of leaving food?',
        '不作营养建议，只表达份量策略。',
        'small',
        'I would err on the side of a small portion. Having a little less is preferable to ordering food I am unlikely to finish.',
        'regular',
        'A regular portion is the more realistic choice; under-ordering would only leave me looking for something else afterwards.',
        reviewed,
      ],
      [
        'drink',
        'drink',
        'Is sparkling water part of the experience for you, or merely an alternative to still?',
        '限定偏好强度。',
        'sparkling',
        'It does add to the occasion for me, so I would choose sparkling, though it is hardly essential.',
        'still',
        'It is only an alternative as far as I am concerned. Still water would actually be my preference.',
        reviewed,
      ],
      [
        'chilli',
        'customize',
        'Would a little chilli added in the kitchen be acceptable, or is keeping control of the heat important?',
        '区别宽泛偏好与精确控制。',
        'kitchen',
        'A little in the kitchen would be fine. I have a preference for mild heat, not a requirement for a precise amount.',
        'table',
        'I would rather have it separately. That is about adjusting the flavour, not a request for a different pasta dish.',
        reviewed,
      ],
      [
        'side',
        'accompaniment',
        'Would the salad add something worthwhile, or is the main course enough on its own?',
        '说明是否值得加配菜。',
        'salad',
        'I would add it for the freshness; the point is contrast, rather than simply making the meal larger.',
        'none',
        'The main course stands on its own for me. I will pass on the salad, though I appreciate the suggestion.',
        reviewed,
      ],
      [
        'timing',
        'schedule',
        'The twenty-minute wait is an estimate, not a promise. How much flexibility do you have?',
        '回应估计而非承诺，避免确认不存在的快速服务。',
        'flexible',
        'There is some room in my schedule, so I can accept that uncertainty rather than needing a guaranteed serving time.',
        'limited',
        'Very little, unfortunately. Could we look at what might be quicker without assuming the kitchen can rush this dish?',
        reviewed,
      ],
      [
        'bread',
        'extra',
        'While we work out the timing, would bringing bread be helpful or an unnecessary extra?',
        '温和接受或拒绝，不把拒绝面包等同于接受等待。',
        'bread',
        'It would be helpful, as I am hungry now; a modest amount would tide me over.',
        'none',
        'It would be an unnecessary extra for me, so there is no need to bring bread on my account.',
        reviewed,
      ],
      [
        'cutlery',
        'equipment',
        'Some guests prefer a spoon with their fork. Would that be useful, or unnecessary for you?',
        '表达具体而不评判他人的餐具偏好。',
        'both',
        'A spoon would be useful, thank you. It is simply how I find this kind of meal easiest to manage.',
        'fork',
        'A fork alone would suit me, thank you. I find it easier to manage the pasta that way, although I know some people prefer a spoon as well.',
        {
          state: 'model-reviewed',
          record:
            'dining-review.md#task-3i-polish — affected question and both answers reread with selected context by Codex implementation agent, 2026-09-11; teacher0',
        },
      ],
      [
        'bill',
        'billing',
        'Would a single bill suit the group, or would separate bills prevent awkwardness later?',
        '说明社交及记账边界。',
        'one',
        'A single bill is fine; we have already agreed to sort out individual shares among ourselves.',
        'separate',
        'Separate bills would avoid ambiguity about who owes what, without anyone needing to discuss their budget at the table.',
        reviewed,
      ],
      [
        'payment',
        'payment',
        'Do you have a firm payment preference, or is convenience the deciding factor?',
        '本轮选择支付意向，不真实付款。',
        'card',
        'Convenience is the deciding factor, so I would use a card rather than count out cash.',
        'cash',
        'I have a firm preference for cash on this occasion; it keeps this expense separate from my card spending.',
        reviewed,
      ],
      [
        'seat',
        'access',
        'If quiet and table space cannot both be maximised, which would you prioritise?',
        '接受现实座位取舍。',
        'quiet',
        'Quiet would take priority. I can manage with the counter space, but a noisy setting would defeat the purpose of the visit.',
        'table',
        'I would prioritise a proper table; some background conversation would be an acceptable trade-off.',
        reviewed,
      ],
      [
        'purpose',
        'occasion',
        'Is there a particular tone you would like us to set for the visit?',
        '用意图而非消费能力定义服务。',
        'ordinary',
        'Nothing ceremonial; this is an ordinary meal, and I would be most comfortable with unobtrusive service.',
        'celebrate',
        'It is a celebration, but we would rather mark it privately than become the centre of the room.',
        reviewed,
      ],
    ],
    variantReview,
  ),
}
