import { diningPack, type Scene } from './authoring'

// Applied only after the postdraft item reading documented at this scene anchor.
const reviewed = {
  state: 'model-reviewed' as const,
  record:
    'src/content/dialogues/graded/dining/dining-review.md#return-item — Codex implementation agent; model-assisted postdraft reading 2026-09-09; teacher0',
}

const variantReview = {
  state: 'model-reviewed' as const,
  record:
    'src/content/dialogues/graded/dining/dining-review.md#self-review — return-item self-contained situations reread 2026-09-09; Codex implementation agent; teacher0',
}

const scene: Scene = {
  sceneId: 'dining-04',
  slug: 'return-item',
  situations: [
    '虚构家用品店退换杯子，仍保留旧餐饮分类。模拟店规：购买14天内、未使用的杯子，包装拆开也可接受；出示纸质或电子收据，可申请退回原支付卡£12或换在售同价杯，均须柜台检查；不是法律权利说明。模拟购买在7或10天前，未使用，纸质/电子收据可选。现场可能排队10分钟；短练只说明诉求、原因和凭证，不实际退款或换货。',
    '虚构家用品店，顾客咨询退换一只自己7或10天前购买、未使用的£12杯子，收据可选纸质/电子。店规仅为练习：购买14天内、未使用，即使包装拆开也可申请退回原支付卡£12或换现货同价杯，均须柜台检查；不是普遍法律权利。办理可能排队10分钟，有低柜台和安静咨询桌。顾客先咨询再安排办理时间；拓展谈搬运帮助及柜台安排。未提交、批准或处理真实退换。',
  ],
  closing:
    'Your return enquiry has been recorded for this fictional shop. No inspection, refund or exchange has actually been carried out.',
  partial:
    'Some details of the return enquiry remain unconfirmed. No refund or exchange has been carried out in this practice.',
  repairs: {
    clarify: 'I can explain the fictional shop process again.',
    struggle: 'Start with one detail; either example is a possible reply.',
    offTopic: 'Let us return to the mug and the return enquiry.',
    unknown:
      'Your wording has been kept, but that return detail is not confirmed.',
    changed: 'That detail of the simulated return has been updated.',
    refusedClosing:
      'We will stop this enquiry here. No return has been processed or payment changed.',
  },
}

export const returnPacks = {
  A1: diningPack(
    scene,
    'A1',
    {
      canDoZh: '说明退换诉求、简单原因及收据形式。',
      complexityZh: '按明确虚构店规逐项表达，前三轮不假装已获退款。',
      scaffoldingZh: '具体词汇配二选一，中文说明未使用和14天条件。',
      registerZh: '简短礼貌请求；能够选择暂缓办理。',
    },
    [
      [
        'request',
        'remedy',
        'Would you like a refund or an exchange for the mug?',
        '只申请，不执行。',
        'refund',
        'A refund, please.',
        'exchange',
        'An exchange, please.',
        reviewed,
      ],
      [
        'reason',
        'explain',
        'Is it the wrong colour, or an extra gift?',
        '两种原因均符合虚构未使用店规。',
        'colour',
        'It is the wrong colour.',
        'gift',
        'It is an extra gift.',
        reviewed,
      ],
      [
        'receipt',
        'evidence',
        'Do you have a paper receipt or a digital receipt?',
        '两种凭证均在模拟店规中可用。',
        'paper',
        'I have a paper receipt.',
        'digital',
        'I have a digital receipt.',
        reviewed,
      ],
      [
        'date',
        'time',
        'Did you buy it seven days ago or ten days ago?',
        '两者均在14天内。',
        'seven',
        'Seven days ago.',
        'ten',
        'Ten days ago.',
        reviewed,
      ],
      [
        'condition',
        'condition',
        'The mug is unused. Is the box open or still closed?',
        '未使用已知，只确认包装状态。',
        'open',
        'The box is open.',
        'closed',
        'The box is still closed.',
        reviewed,
      ],
      [
        'inspection',
        'permission',
        'May we inspect the mug, or would you like the process explained first?',
        '申请检查或先听说明。',
        'inspect',
        'You may inspect it.',
        'explain',
        'Please explain first.',
        reviewed,
      ],
      [
        'queue',
        'schedule',
        'There is a ten-minute queue. Can you wait or will you come back?',
        '决定等待或改天，不表示已处理。',
        'wait',
        'I can wait.',
        'return',
        'I will come back later.',
        reviewed,
      ],
      [
        'record',
        'record',
        'Would you want a paper record of the enquiry or no copy?',
        '仅询问记录，不是退款收据。',
        'paper',
        'A paper record, please.',
        'none',
        'No copy, thanks.',
        reviewed,
      ],
      [
        'policy',
        'clarify',
        'Shall I explain the refund rule or the exchange rule?',
        '可了解任一政策，不变更先前申请。',
        'refund',
        'The refund rule, please.',
        'exchange',
        'The exchange rule, please.',
        reviewed,
      ],
      [
        'next',
        'next-step',
        'Would you like to continue the enquiry today or stop for now?',
        '选择本次交流下一步。',
        'continue',
        'I would like to continue.',
        'stop',
        'I will stop for now.',
        reviewed,
      ],
      [
        'carry',
        'assistance',
        'Can you carry the box, or would you like help?',
        '表达搬运帮助需求。',
        'self',
        'I can carry it.',
        'help',
        'I would like help, please.',
        reviewed,
      ],
      [
        'desk',
        'access',
        'A lower counter or a quieter desk?',
        '表达咨询位置需要。',
        'lower',
        'A lower counter, please.',
        'quiet',
        'A quieter desk, please.',
        reviewed,
      ],
    ],
    variantReview,
  ),
  A2: diningPack(
    scene,
    'A2',
    {
      canDoZh: '用简单过去时描述购买并配合退换查询。',
      complexityZh: '串联诉求、凭证、日期与包装，理解检查前后不同状态。',
      scaffoldingZh: '明确店规及问题选项，参考句带简单原因和时间短语。',
      registerZh: '合作式请求，不把店内模拟条款说成普遍权利。',
    },
    [
      [
        'request',
        'remedy',
        'Which option would you like to request under our example policy?',
        '退款到原卡或换同价杯。',
        'refund',
        'I would like to request a refund to the card I used.',
        'exchange',
        'Could I exchange the mug for another one at the same price?',
        reviewed,
      ],
      [
        'reason',
        'explain',
        'What is your reason for bringing the unused mug back?',
        '选颜色或重复款式，两者均可申请退款或换另一款。',
        'colour',
        'I chose the wrong colour for my kitchen.',
        'gift',
        'I received the same design as a gift, so I have two like this.',
        reviewed,
      ],
      [
        'receipt',
        'evidence',
        'How would you like to show us the purchase receipt?',
        '展示纸质或电子凭证。',
        'paper',
        'I brought the paper receipt with me.',
        'digital',
        'I can show the digital receipt on my phone.',
        reviewed,
      ],
      [
        'date',
        'time',
        'How long ago did you buy this mug?',
        '模拟7或10天前购买，均满足14天。',
        'seven',
        'I bought it seven days ago.',
        'ten',
        'I bought it ten days ago.',
        reviewed,
      ],
      [
        'condition',
        'condition',
        'Has the box been opened, even though the mug has not been used?',
        '不重复询问已知未使用。',
        'open',
        'Yes, I opened the box, but I have not used the mug.',
        'closed',
        'No, the box is still closed.',
        reviewed,
      ],
      [
        'inspection',
        'permission',
        'Are you ready for an inspection, or would you like to hear what it involves?',
        '可同意检查或先问流程。',
        'ready',
        'I am ready for you to inspect the mug.',
        'explain',
        'Please tell me what the inspection involves first.',
        reviewed,
      ],
      [
        'queue',
        'schedule',
        'The queue is about ten minutes. Would you like to wait or return later?',
        '安排审核时间，不结束当前简短咨询。',
        'wait',
        'I can wait because I have some time.',
        'later',
        'I will return later; I do not have ten minutes today.',
        reviewed,
      ],
      [
        'record',
        'record',
        'Would a printed record of this enquiry be useful to you?',
        '仅记录本次咨询。',
        'print',
        'Yes, I would like a printed record to keep.',
        'none',
        'No, thank you. I do not need a record.',
        reviewed,
      ],
      [
        'policy',
        'clarify',
        'Which part of the example policy would you like explained in more detail?',
        '澄清不自动改动申请。',
        'refund',
        'Please explain how the refund goes back to the original card.',
        'exchange',
        'Please explain how the same-price exchange works.',
        reviewed,
      ],
      [
        'next',
        'next-step',
        'Would you like to keep discussing this now, or leave it for another time?',
        '与排队选择不同：此处决定是否继续咨询。',
        'talk',
        'I would like to ask a little more now.',
        'later',
        'I would like to leave the discussion for another time.',
        reviewed,
      ],
      [
        'carry',
        'assistance',
        'Will you manage the box yourself when you visit the counter?',
        '可请求帮助。',
        'self',
        'Yes, I can carry the box myself.',
        'help',
        'Could someone help me carry the box, please?',
        reviewed,
      ],
      [
        'desk',
        'access',
        'Would the lower counter or the quiet enquiry desk suit you better?',
        '两个沟通位置均可安排。',
        'lower',
        'The lower counter would be easier for me.',
        'quiet',
        'I would prefer the quiet desk so I can hear clearly.',
        reviewed,
      ],
    ],
    variantReview,
  ),
  B1: diningPack(
    scene,
    'B1',
    {
      canDoZh: '说明购买经过并在检查和等待等限制下安排退换查询。',
      complexityZh: '区分申请与批准、商品状态与包装状态，解释更改安排的原因。',
      scaffoldingZh: '明确虚构条款；回答示范理由连接和流程澄清。',
      registerZh: '清晰表达期望并尊重店员核实步骤，不宣称法律权利。',
    },
    [
      [
        'request',
        'remedy',
        'What outcome are you hoping for within the two options in our example policy?',
        '说明想要的处理，不冒充已获批准。',
        'refund',
        'I am hoping for a refund to the original card because I no longer need a mug.',
        'exchange',
        'I would prefer a same-price exchange because I still need a mug, just not this one.',
        reviewed,
      ],
      [
        'reason',
        'explain',
        'Could you explain why this unused mug is not suitable?',
        '理由不涉及虚构质量故障；不同款式仍可能有用。',
        'colour',
        'The colour does not match what I had in mind when I bought it.',
        'duplicate',
        'It duplicates a gift I received, so I would rather not keep two in the same design.',
        reviewed,
      ],
      [
        'receipt',
        'evidence',
        'What proof of purchase have you brought for us to check?',
        '原收据不同呈现形式。',
        'paper',
        'I have the original paper receipt, which shows the mug and the price.',
        'digital',
        'I have the digital receipt on my phone and can show the relevant purchase.',
        reviewed,
      ],
      [
        'date',
        'time',
        'Can you place the purchase within our fictional fourteen-day window?',
        '明确模拟购买时间。',
        'seven',
        'Yes, I bought it seven days ago, so it falls within that window.',
        'ten',
        'It was ten days ago, which is still within the fourteen days in your example policy.',
        reviewed,
      ],
      [
        'condition',
        'condition',
        'How would you describe the packaging, separately from the fact that the mug is unused?',
        '包装拆封不等于使用过。',
        'open',
        'I opened the box to look at the colour, but the mug itself remains unused.',
        'closed',
        'The packaging is still closed; I have not taken the mug out.',
        reviewed,
      ],
      [
        'inspection',
        'permission',
        'Would you like us to inspect it next, or explain the inspection before you agree?',
        '许可和核实结果分开。',
        'inspect',
        'You can inspect it next; I understand that the request still needs checking.',
        'explain',
        'Please explain the inspection first so I know what you need to examine.',
        reviewed,
      ],
      [
        'queue',
        'schedule',
        'How would a ten-minute wait affect your plans for having the request checked?',
        '安排现场审核时间。',
        'wait',
        'It would not disrupt my plans, so I can stay in the queue.',
        'return',
        'It would make me late for an appointment, so I would return another time.',
        reviewed,
      ],
      [
        'record',
        'record',
        'Would you like a printed enquiry record to distinguish this discussion from a completed return?',
        '不将咨询记录当退款证明。',
        'copy',
        'Yes, that would help me remember what has been discussed and what is still pending.',
        'none',
        'No, thanks. I understand that the return has not been completed.',
        reviewed,
      ],
      [
        'policy',
        'clarify',
        'What part of the policy is still unclear, regardless of which option you requested?',
        '允许了解未选方案而不变更申请。',
        'refund',
        'I would like to understand why the refund must go to the original payment card in this example.',
        'exchange',
        'I would like to know how choosing an in-stock mug at the same price would work.',
        reviewed,
      ],
      [
        'next',
        'next-step',
        'Do you want to continue asking questions now, or pause the discussion?',
        '咨询与排队办理区别。',
        'continue',
        'I would like to continue the discussion, even if the inspection has to wait.',
        'pause',
        'I would prefer to pause now and come back to the questions later.',
        reviewed,
      ],
      [
        'carry',
        'assistance',
        'Would carrying the boxed mug to the service point be manageable for you?',
        '主动说明可获得的帮助需求。',
        'self',
        'Yes, I can manage it without help; the box is easy for me to carry.',
        'help',
        'I would appreciate help because I am already carrying several bags.',
        reviewed,
      ],
      [
        'desk',
        'access',
        'Which service point would make the discussion easier: a lower counter or a quieter desk?',
        '说明位置对交流的作用。',
        'lower',
        'The lower counter would help me put the box down comfortably.',
        'quiet',
        'The quieter desk would make it easier to follow the explanation.',
        reviewed,
      ],
    ],
    variantReview,
  ),
  B2: diningPack(
    scene,
    'B2',
    {
      canDoZh: '在店规约束下权衡处理方案并澄清批准与查询的区别。',
      complexityZh:
        '处理记录范围、程序许可和日程冲突，提出有依据且不过度的请求。',
      scaffoldingZh: '固定虚构价格与条件，示例引入让步及分步骤理解。',
      registerZh: '有主张但不对抗，不以模拟政策推导现实法律权益。',
    },
    [
      [
        'request',
        'remedy',
        'Would reversing the purchase or replacing the mug better address your situation?',
        '两种方案均待店员核实。',
        'refund',
        'A refund to the original card would address it better; replacing the mug would leave me with something I do not need.',
        'exchange',
        'Replacing it with an in-stock mug at the same price would be more useful than reversing the purchase.',
        reviewed,
      ],
      [
        'reason',
        'explain',
        'How would you explain the reason for the return without suggesting there is a fault?',
        '明确不是质量问题。',
        'colour',
        'It is a colour mismatch rather than a defect; the mug is simply not what I wanted for the room.',
        'duplicate',
        'It is an unwanted duplicate of a gift, not an item I consider faulty.',
        reviewed,
      ],
      [
        'receipt',
        'evidence',
        'Which receipt format can you provide for checking the transaction?',
        '证明格式不同但不虚构检查完成。',
        'paper',
        'I can provide the paper receipt, so you can compare the item with the transaction details.',
        'digital',
        'I can display the digital receipt and the relevant transaction, without handing over unrelated information on my phone.',
        reviewed,
      ],
      [
        'date',
        'time',
        'How does the purchase date relate to the fourteen-day limit in this fictional policy?',
        '明确数字与资格关系。',
        'seven',
        'The purchase was seven days ago, comfortably within the stated fourteen-day limit.',
        'ten',
        'It was ten days ago, so there are still four days before that example window closes.',
        reviewed,
      ],
      [
        'condition',
        'condition',
        'Can you separate the condition of the packaging from the unused status of the product?',
        '不误称打开包装即不符合条款。',
        'open',
        'The box has been opened for a look at the mug, but opening the packaging is not the same as using the product.',
        'closed',
        'Both the closed packaging and the unused mug are unchanged since purchase.',
        reviewed,
      ],
      [
        'inspection',
        'permission',
        'Would you consent to an inspection now, or prefer an explanation of its scope first?',
        '许可不等于已通过。',
        'consent',
        'I consent to the inspection, while recognising that it does not automatically approve the request.',
        'scope',
        'I would like its scope explained first, so I understand what the assessment will and will not establish.',
        reviewed,
      ],
      [
        'queue',
        'schedule',
        'Would staying in a ten-minute queue be worthwhile, or would another visit be more practical?',
        '两种合法时间安排。',
        'wait',
        'Staying would be worthwhile; I would rather allow the time now than make another journey.',
        'return',
        'Another visit would be more practical because waiting now would interfere with a fixed appointment.',
        reviewed,
      ],
      [
        'record',
        'record',
        'Would a printed summary help you keep the enquiry separate from any later approval?',
        '避免查询单冒充处理凭证。',
        'print',
        'Yes, provided it clearly records a pending enquiry rather than a completed refund or exchange.',
        'none',
        'I do not need one; I am clear that no approval or transfer has occurred.',
        reviewed,
      ],
      [
        'policy',
        'clarify',
        'Which policy detail would you want clarified before making any further decision?',
        '可了解两方案不同约束。',
        'refund',
        'I would clarify the original-card requirement, rather than assume a refund could be paid in cash.',
        'exchange',
        'I would clarify the in-stock, same-price condition, rather than assume every replacement is covered.',
        reviewed,
      ],
      [
        'next',
        'next-step',
        'Would further discussion now be useful, or would a pause give you time to consider the information?',
        '不把此决定当批准处理。',
        'discuss',
        'Further discussion would be useful; I still want to understand the process before anything is carried out.',
        'pause',
        'A pause would be useful, as I would rather consider the information than rush a decision.',
        reviewed,
      ],
      [
        'carry',
        'assistance',
        'Would assistance moving the box remove a practical difficulty, or can you manage comfortably?',
        '不假定身体能力。',
        'help',
        'Assistance would remove a practical difficulty because I have other bags to manage.',
        'self',
        'I can manage comfortably, so there is no need to arrange assistance on my behalf.',
        reviewed,
      ],
      [
        'desk',
        'access',
        'Would physical access at a lower counter or reduced noise at a quieter desk matter more?',
        '权衡两种交流条件。',
        'lower',
        'The lower counter matters more because I need somewhere accessible to put the box.',
        'quiet',
        'Reduced noise matters more; being able to follow the explanation is my priority.',
        reviewed,
      ],
    ],
    variantReview,
  ),
  C1: diningPack(
    scene,
    'C1',
    {
      canDoZh: '精确表达补救偏好并管理证据、程序和预期之间的边界。',
      complexityZh:
        '澄清隐含的质量指控、许可范围和模拟店规适用性，协商而非施压。',
      scaffoldingZh:
        '保留事实背景，问题要求限定和话语组织，答案不机械延长礼貌句。',
      registerZh: '自然、克制的服务协商，承认店内审核限制但保留个人选择。',
    },
    [
      [
        'request',
        'remedy',
        'Which of the two stated remedies would actually resolve the issue, rather than merely move it elsewhere?',
        '申请在模拟政策范围内。',
        'refund',
        'A refund to the original card would resolve it. An exchange would merely leave me finding a use for another mug.',
        'exchange',
        'A same-price exchange from current stock would resolve it; I still need the item in principle, just not this particular one.',
        reviewed,
      ],
      [
        'reason',
        'explain',
        'How would you frame the reason so it is not recorded as a product fault?',
        '精确说明个人不适合而非故障。',
        'colour',
        'Please record a change of mind about the colour, not a defect. The distinction matters because I am not alleging a quality problem.',
        'duplicate',
        'It is a duplicate gift that I do not need. I would not want that compressed into a misleading claim that the mug is faulty.',
        reviewed,
      ],
      [
        'receipt',
        'evidence',
        'What evidence can you make available while keeping the check confined to this purchase?',
        '仅相关凭证，不暴露无关私人资料。',
        'paper',
        'I can provide the paper receipt for this purchase; that should keep the evidence focused on the item being discussed.',
        'digital',
        'I can display the relevant digital receipt, but I would prefer not to give access to unrelated material on my phone.',
        reviewed,
      ],
      [
        'date',
        'time',
        'Can you establish where this purchase falls within the example policy, without assuming anything about other shops?',
        '明确虚构14天，不泛化法律。',
        'seven',
        'It was seven days ago, so it falls within this shop example’s fourteen-day window; I am not treating that as a universal rule.',
        'ten',
        'It was ten days ago, which puts it inside the stated window, leaving the other checks to be addressed separately.',
        reviewed,
      ],
      [
        'condition',
        'condition',
        'What qualification is needed when describing the item as unused?',
        '准确限定包装打开与否。',
        'opened',
        'Unused does not mean unopened in this case: I opened the box to inspect the colour but did not use the mug.',
        'sealed',
        'No qualification about opening is needed; the box remains closed and the mug has not been used.',
        reviewed,
      ],
      [
        'inspection',
        'permission',
        'Are you comfortable authorising the inspection, or would you like its boundaries made explicit first?',
        '许可与结果清楚分离。',
        'authorise',
        'I am comfortable authorising it, on the understanding that we are permitting a check rather than recording an approved return.',
        'boundaries',
        'I would like the boundaries explained first, so agreement to an inspection is not mistaken for agreement to something beyond it.',
        reviewed,
      ],
      [
        'queue',
        'schedule',
        'How would you weigh a ten-minute queue against the inconvenience of returning?',
        '合理权衡时间，不要求插队。',
        'wait',
        'The queue is the smaller inconvenience, so I would allow the ten minutes rather than ask for an exception.',
        'return',
        'Returning would be preferable; a fixed commitment makes the delay more costly to me than a second visit.',
        reviewed,
      ],
      [
        'record',
        'record',
        'Would a written summary be helpful, provided it makes no stronger claim than the discussion warrants?',
        '记录已谈事项，不杜撰处理结果。',
        'summary',
        'Yes, if it distinguishes what I requested from what has actually been approved, which at this stage is nothing.',
        'none',
        'I would leave it at the discussion for now; a summary is unnecessary as long as we are clear that no remedy has been processed.',
        reviewed,
      ],
      [
        'policy',
        'clarify',
        'Which limitation would you want brought into the open before relying on the policy?',
        '澄清原卡和同价现货条件，不扩张。',
        'card',
        'The original-card limitation; I would not want an expectation of cash repayment to develop when the example does not offer it.',
        'stock',
        'The current-stock limitation on exchanges; same price does not imply that a particular replacement can be promised.',
        reviewed,
      ],
      [
        'next',
        'next-step',
        'Would you prefer to pursue the remaining questions now or leave the decision open for the moment?',
        '继续咨询不是已完成退换。',
        'pursue',
        'I would pursue the questions now, while keeping any actual processing separate from this discussion.',
        'open',
        'I would leave the decision open for the moment. That is a pause, not a request to treat the enquiry as approved.',
        reviewed,
      ],
      [
        'carry',
        'assistance',
        'Would you appreciate a hand with the box, or would you prefer to carry it yourself?',
        '接受或拒绝帮助有自然理由。',
        'help',
        'A hand with the box would be welcome, as my hands are full. I can manage the rest once we get to the counter.',
        'self',
        'I can manage the box myself, thank you. It is light enough for me to carry, so there is no need to trouble you.',
        {
          state: 'model-reviewed',
          record:
            'dining-review.md#task-3i-polish — affected question and both answers reread with selected context by Codex implementation agent, 2026-09-11; teacher0',
        },
      ],
      [
        'desk',
        'access',
        'Which adjustment would best support our discussion: a lower counter or somewhere quieter?',
        '此处指交流位置，不自动将退款改为换货。',
        'lower',
        'A lower counter would be the useful adjustment; I need a manageable working height rather than a change in the procedure.',
        'quiet',
        'Somewhere quieter would help most, so I can follow the explanation without repeatedly interrupting to ask for it again.',
        reviewed,
      ],
    ],
    variantReview,
  ),
}
