import { diningPack, type Scene } from './authoring'

// Applied only after the postdraft item reading documented at this scene anchor.
const reviewed = {
  state: 'model-reviewed' as const,
  record:
    'src/content/dialogues/graded/dining/dining-review.md#supermarket-help — Codex implementation agent; model-assisted postdraft reading 2026-09-09; teacher0',
}

const variantReview = {
  state: 'model-reviewed' as const,
  record:
    'src/content/dialogues/graded/dining/dining-review.md#self-review — supermarket-help self-contained situations reread 2026-09-09; Codex implementation agent; teacher0',
}

const scene: Scene = {
  sceneId: 'dining-05',
  slug: 'supermarket-help',
  situations: [
    '虚构超市，顾客向店员找干货：米和意面均在3号通道，有500克和1千克袋装，均有自有品牌和其他品牌。小包装和大包装都可比较单价；本轮不提供未知价格。默认只咨询未购买。有人值守收银台及自助台均开放，可提供店内路线图、取高处货品帮助。短练找产品、帮助方式、包装大小，拓展谈替代方案及标签核对。',
    '虚构超市，顾客为计划购物向店员咨询米或意面；两者均在3号通道，有500克/1千克袋装，自有品牌和其他品牌都有货。有人值守收银台与自助台都开放，可提供店内地图和取高处货品帮助；可比较每千克或整袋价格，但本轮没有给出具体单价。默认只咨询未买。拓展安排购物篮/推车及购物目的，而非假设缺货和标签检查；不产生订单、付款或检查结果。',
  ],
  closing:
    'Your shopping preferences and requests discussed here are noted. This supermarket practice has not bought or reserved any goods.',
  partial:
    'Some shopping requests remain unconfirmed. The practice has ended without buying or reserving goods.',
  repairs: {
    clarify: 'I can explain that shelf or shopping question again.',
    struggle: 'Use either example, or take a moment to write your own words.',
    offTopic: 'Let us return to finding the groceries.',
    unknown:
      'Your words are kept, but that shopping request is still unconfirmed.',
    changed: 'That shopping preference has been updated in this practice.',
    refusedClosing:
      'That is fine; we will stop here. Nothing has been bought or reserved.',
  },
}

export const supermarketPacks = {
  A1: diningPack(
    scene,
    'A1',
    {
      canDoZh: '在店员帮助下找商品并说明包装与服务需要。',
      complexityZh: '单步具体交换；前三轮确定产品、导航帮助及数量单位。',
      scaffoldingZh: '明确货架事实和二选一短句，中文提示公斤与克。',
      registerZh: '礼貌求助，允许拒绝购物袋或其他额外帮助。',
    },
    [
      [
        'product',
        'find',
        'Are you looking for rice or pasta?',
        '选择米或意面。',
        'rice',
        'Rice, please.',
        'pasta',
        'Pasta, please.',
        reviewed,
      ],
      [
        'navigation',
        'navigate',
        'Both are in aisle three. Would you like a map or shall I show you?',
        '不因商品选择而错报通道。',
        'map',
        'A map, please.',
        'show',
        'Please show me.',
        reviewed,
      ],
      [
        'size',
        'quantity',
        'A five-hundred-gram bag or a one-kilo bag?',
        '选择500克或1千克。',
        'small',
        'A five-hundred-gram bag, please.',
        'large',
        'A one-kilo bag, please.',
        reviewed,
      ],
      [
        'brand',
        'preference',
        'Our own brand or another brand?',
        '两类都有货。',
        'own',
        'Your own brand, please.',
        'other',
        'Another brand, please.',
        reviewed,
      ],
      [
        'compare',
        'compare',
        'Would you like to compare the price per kilo or the bag price?',
        '选择比较单位，不声称哪个便宜。',
        'unit',
        'The price per kilo, please.',
        'bag',
        'The bag price, please.',
        reviewed,
      ],
      [
        'checkout',
        'service',
        'A staffed checkout or self-checkout?',
        '选择结账渠道，尚未付款。',
        'staff',
        'A staffed checkout, please.',
        'self',
        'Self-checkout, please.',
        reviewed,
      ],
      [
        'reach',
        'assistance',
        'Would you like help reaching a high shelf?',
        '接受或拒绝取货帮助。',
        'help',
        'Yes, please help me.',
        'no',
        'No, I can reach it.',
        reviewed,
      ],
      [
        'bag',
        'packing',
        'Do you have a shopping bag, or do you need one?',
        '购物袋与商品包装不同。',
        'own',
        'I have a shopping bag.',
        'need',
        'I need a shopping bag.',
        reviewed,
      ],
      [
        'fallback',
        'alternative',
        'If your chosen food pack is unavailable next time, would you choose another pack or wait?',
        '明确是假设下次食品缺货，不是刚提到的购物袋。',
        'other',
        'I would choose another food pack.',
        'wait',
        'I would wait.',
        reviewed,
      ],
      [
        'label',
        'verify',
        'Shall we check the weight label or the date label?',
        '请求看标签，不作食品安全保证。',
        'weight',
        'The weight label, please.',
        'date',
        'The date label, please.',
        reviewed,
      ],
      [
        'carrier',
        'equipment',
        'Would you like a basket or a trolley?',
        '店内携带工具。',
        'basket',
        'A basket, please.',
        'trolley',
        'A trolley, please.',
        reviewed,
      ],
      [
        'purpose',
        'purpose',
        'Is this for dinner today or for your cupboard?',
        '说明购物用途。',
        'dinner',
        'For dinner today.',
        'cupboard',
        'For my cupboard.',
        reviewed,
      ],
    ],
    variantReview,
  ),
  A2: diningPack(
    scene,
    'A2',
    {
      canDoZh: '完成找货、比较包装和选择服务的简短日常交换。',
      complexityZh: '结合携带方便和使用计划给简单理由，处理假设缺货。',
      scaffoldingZh: '明示两种商品位置相同，提供简单时间和原因结构。',
      registerZh: '友好直接的店内求助，不把询价当作支付。',
    },
    [
      [
        'product',
        'find',
        'Which dry food do you need help finding today?',
        '情境提供米与意面。',
        'rice',
        'I need some rice for my shopping list.',
        'pasta',
        'I am looking for pasta, please.',
        reviewed,
      ],
      [
        'navigation',
        'navigate',
        'Rice and pasta are in aisle three. Would a map help, or should I take you there?',
        '选导航方式。',
        'map',
        'A map would help me find it myself.',
        'escort',
        'Could you take me there, please?',
        reviewed,
      ],
      [
        'size',
        'quantity',
        'Would five hundred grams be enough, or would you like a kilo?',
        '决定袋装大小。',
        'small',
        'Five hundred grams would be enough for me.',
        'large',
        'I would like a kilo so I have some left for later.',
        reviewed,
      ],
      [
        'brand',
        'preference',
        'Would you like to try our own brand or choose another brand?',
        '品牌不决定未给出的价格。',
        'own',
        'I would like to try your own brand this time.',
        'other',
        'I would prefer another brand that I know.',
        reviewed,
      ],
      [
        'compare',
        'compare',
        'Which price would you like to look at first: per kilo or per bag?',
        '不同包装比较方式。',
        'unit',
        'Let us look at the price per kilo first.',
        'bag',
        'I want to check what one bag costs first.',
        reviewed,
      ],
      [
        'checkout',
        'service',
        'Would you rather use self-checkout or speak to a cashier?',
        '选择支付渠道但不付款。',
        'self',
        'I would rather use self-checkout today.',
        'cashier',
        'I would like to use a checkout with a cashier.',
        reviewed,
      ],
      [
        'reach',
        'assistance',
        'Can you reach the upper shelf, or do you need some help?',
        '不要求攀爬。',
        'self',
        'I can reach it from here, thanks.',
        'help',
        'Could you get a bag down for me, please?',
        reviewed,
      ],
      [
        'bag',
        'packing',
        'Have you brought your own shopping bag today?',
        '决定是否另需购物袋。',
        'own',
        'Yes, I brought a bag with me.',
        'need',
        'No, I will need a shopping bag.',
        reviewed,
      ],
      [
        'fallback',
        'alternative',
        'If that pack is out of stock on a future visit, what would you prefer to do?',
        '未来备选策略，不否定当前有货。',
        'alternative',
        'I would look at another pack instead.',
        'wait',
        'I would wait until the pack I want is back.',
        reviewed,
      ],
      [
        'label',
        'verify',
        'Would you like help reading the weight or finding the printed date?',
        '只找标签信息。',
        'weight',
        'Please help me read the weight on the bag.',
        'date',
        'Could you show me where the date is printed?',
        reviewed,
      ],
      [
        'carrier',
        'equipment',
        'Would a basket be enough, or would a trolley be easier?',
        '店内运输不是结账购物袋。',
        'basket',
        'A basket is enough because I am buying only a few things.',
        'trolley',
        'A trolley would be easier for carrying everything.',
        reviewed,
      ],
      [
        'purpose',
        'purpose',
        'Are these groceries for a meal soon or to keep at home?',
        '给出用途。',
        'meal',
        'They are for a meal I am making today.',
        'store',
        'I want to keep them at home for later meals.',
        reviewed,
      ],
    ],
    variantReview,
  ),
  B1: diningPack(
    scene,
    'B1',
    {
      canDoZh: '说明购物目的并比较方案，在缺货等非例行情境提出替代。',
      complexityZh: '连接单价、包装、携带与后续计划，不推断未标价格。',
      scaffoldingZh: '已知店内事实支持理由表达，允许解释看不懂的标签。',
      registerZh: '合作地请求实际帮助，保留自己选择和拒绝的权利。',
    },
    [
      [
        'product',
        'find',
        'What item from your list are you having trouble locating?',
        '原位置未知，选米或意面。',
        'rice',
        'I cannot find the rice, and I would appreciate some directions.',
        'pasta',
        'I have been looking for pasta but seem to have missed the right section.',
        reviewed,
      ],
      [
        'navigation',
        'navigate',
        'Both items are in aisle three. Would directions on a map be enough, or would you prefer to be shown?',
        '固定位置避免商品分支冲突。',
        'map',
        'A map should be enough; I would like to learn the layout myself.',
        'shown',
        'I would prefer to be shown because I have already gone past the section once.',
        reviewed,
      ],
      [
        'size',
        'quantity',
        'How would you choose between the half-kilo and one-kilo bags?',
        '尺寸选择与使用频率结合。',
        'half',
        'I would take half a kilo because I do not use a large amount at a time.',
        'kilo',
        'A kilo makes sense because I use this regularly and have space to keep it.',
        reviewed,
      ],
      [
        'brand',
        'preference',
        'Would you be comfortable trying the own-brand option, or do you want a familiar alternative?',
        '品牌选择不默认价差。',
        'own',
        'I would try the own-brand option; I do not need a particular name on the bag.',
        'familiar',
        'I would choose a familiar brand because I know how it works in my usual recipes.',
        reviewed,
      ],
      [
        'compare',
        'compare',
        'Would comparing the unit price or the total bag price help you decide?',
        '同一重量单位与总支出不同。',
        'unit',
        'The price per kilo would help me compare different bag sizes fairly.',
        'total',
        'The bag price matters first because I need to know what I would spend today.',
        reviewed,
      ],
      [
        'checkout',
        'service',
        'Which checkout would be more convenient for you, and why?',
        '只计划结账途径。',
        'staffed',
        'A staffed checkout would be more convenient because I may need help with a price question.',
        'self',
        'Self-checkout would suit me because I am comfortable using the machine.',
        reviewed,
      ],
      [
        'reach',
        'assistance',
        'Would you like someone to take a bag down from the upper shelf?',
        '不建议危险攀爬。',
        'help',
        'Yes, please. It is higher than I can comfortably reach.',
        'self',
        'No, I can reach a bag without stretching, so I do not need help.',
        reviewed,
      ],
      [
        'bag',
        'packing',
        'Will you need a shopping bag after checkout, or have you brought one?',
        '不混淆商品袋和店内工具。',
        'own',
        'I have brought a reusable bag, so I will not need another one.',
        'need',
        'I will need a shopping bag because I left mine at home.',
        reviewed,
      ],
      [
        'fallback',
        'alternative',
        'If your preferred pack were unavailable next time, would you change packs or postpone the purchase?',
        '未来假设，不重复当前选择。',
        'change',
        'I would compare another pack rather than make a separate trip just for this one.',
        'postpone',
        'I would postpone the purchase because I still have enough at home for now.',
        reviewed,
      ],
      [
        'label',
        'verify',
        'What would you like clarified on the label: the amount in the bag or the printed date?',
        '确认所需信息，不推断可食用期限。',
        'amount',
        'I would like the amount clarified because the print is difficult to read.',
        'date',
        'Please show me the printed date; I cannot tell where to look for it.',
        reviewed,
      ],
      [
        'carrier',
        'equipment',
        'Would carrying a basket work for the rest of your shop, or would you rather use a trolley?',
        '按携带需求选择工具。',
        'basket',
        'A basket would work because I can carry the few things on my list.',
        'trolley',
        'I would rather use a trolley so I do not have to carry the weight around the shop.',
        reviewed,
      ],
      [
        'purpose',
        'purpose',
        'Are you buying for an immediate meal or building up supplies at home?',
        '用途不推断已完成购买。',
        'meal',
        'I am buying for a meal this evening, so it is part of a specific plan.',
        'supplies',
        'I am building up supplies so I can put a meal together without another trip.',
        reviewed,
      ],
    ],
    variantReview,
  ),
  B2: diningPack(
    scene,
    'B2',
    {
      canDoZh: '权衡单位成本、当次支出和便利，解释合理替代策略。',
      complexityZh: '区分品牌偏好与实际功能，处理包装和帮助的取舍。',
      scaffoldingZh: '有限货架事实不提供虚构比价结论；回答示范比较依据与让步。',
      registerZh: '清楚提出需求，不要求店员猜测用途或承诺库存。',
    },
    [
      [
        'product',
        'find',
        'Which product would you like help locating before you compare the options?',
        '先确定米或意面，不用关键词假推断。',
        'rice',
        'Rice is what I need to locate; I can consider the different packs once I find the section.',
        'pasta',
        'I am looking for pasta, but I have not committed to a particular pack yet.',
        reviewed,
      ],
      [
        'navigation',
        'navigate',
        'They are both in aisle three. Would a map give you enough independence, or would being shown save time?',
        '比较导航帮助的价值。',
        'map',
        'A map would give me enough information, and learning the layout would help on future visits.',
        'shown',
        'Being shown would save time; I would rather accept help than keep circling the same shelves.',
        reviewed,
      ],
      [
        'size',
        'quantity',
        'Would you prioritise the lighter half-kilo bag or the extra supply in a one-kilo bag?',
        '明确包装取舍。',
        'half',
        'I would prioritise the lighter bag because carrying less matters more than having extra supplies.',
        'kilo',
        'The one-kilo bag would be more practical; I have storage space and would use the extra amount.',
        reviewed,
      ],
      [
        'brand',
        'preference',
        'Is familiarity with a brand important, or would you consider the own-brand product on its merits?',
        '品牌不自动等于价格或质量。',
        'own',
        'I would consider the own-brand product on its merits rather than assume the name determines its quality.',
        'familiar',
        'Familiarity matters to me here because I want a result I already know in a recipe.',
        reviewed,
      ],
      [
        'compare',
        'compare',
        'Would the price per kilo or the immediate price of a bag be the more useful comparison?',
        '单位价与预算不同。',
        'unit',
        'Price per kilo would be more useful for comparing value across sizes, without assuming the larger bag is cheaper.',
        'bag',
        'The immediate bag price would be more useful because today’s spending limit matters more than a possible unit saving.',
        reviewed,
      ],
      [
        'checkout',
        'service',
        'Would you favour staff support at checkout or the control of using the self-service machine?',
        '不是已付款状态。',
        'staff',
        'I would favour staff support so I can raise a query before completing a purchase.',
        'self',
        'I would choose self-checkout because I prefer to scan and review the items at my own pace.',
        reviewed,
      ],
      [
        'reach',
        'assistance',
        'Would help from a colleague solve the shelf-height issue, or is the item within comfortable reach?',
        '真实帮助请求，不评价身体能力。',
        'help',
        'Help would solve it; I would rather ask than stretch for something beyond a comfortable reach.',
        'self',
        'The bag I want is within comfortable reach, so additional help is unnecessary.',
        reviewed,
      ],
      [
        'bag',
        'packing',
        'Have you planned how to carry the shopping home, or will you need a bag from us?',
        '店内篮/车与带回家包装不同。',
        'own',
        'I have a reusable bag with me, so I have already covered the packing need.',
        'shop',
        'I will need a bag from the shop; I forgot to bring one when I left home.',
        reviewed,
      ],
      [
        'fallback',
        'alternative',
        'On a future visit, would you accept a different pack if your preference was unavailable, or wait for it?',
        '假设条件明确。',
        'different',
        'I would consider a different pack, provided I could compare its contents and price before deciding.',
        'wait',
        'I would wait for the preferred pack rather than buy a substitute merely to finish the shopping list.',
        reviewed,
      ],
      [
        'label',
        'verify',
        'Which label detail needs a closer look before you decide what to buy?',
        '看标签不是安全认证。',
        'weight',
        'The stated weight needs a closer look so I do not confuse the pack size with the unit-price basis.',
        'date',
        'The printed date needs a closer look; I would like to identify it accurately rather than guess from the packaging.',
        reviewed,
      ],
      [
        'carrier',
        'equipment',
        'Would you rather carry a basket for easier movement, or use a trolley to support the weight?',
        '自然明确地比较篮与推车。',
        'basket',
        'I would choose a basket; it would be easier to move through the aisles, and the weight would be manageable.',
        'trolley',
        'I would prefer a trolley so the weight is supported while I finish shopping.',
        reviewed,
      ],
      [
        'purpose',
        'purpose',
        'Is the purchase driven by a particular meal or by keeping the cupboard stocked?',
        '目的不重复包装选择。',
        'meal',
        'A particular meal is driving it; I would rather shop to that plan than add things without a purpose.',
        'stock',
        'Keeping the cupboard stocked is the aim, so flexibility for several future meals matters more than one recipe.',
        reviewed,
      ],
    ],
    variantReview,
  ),
  C1: diningPack(
    scene,
    'C1',
    {
      canDoZh: '精确区分购物决策依据，管理帮助与自主选择的边界。',
      complexityZh:
        '揭示单位比较、品牌推断和替代选择中的隐含假设，以限定和让步说明策略。',
      scaffoldingZh:
        '菜单式支架减少，保留明确货架事实；不依赖未提供的价格或库存预测。',
      registerZh:
        '自然服务交流中的精确说明，不把店员当顾客预算或健康的判断者。',
    },
    [
      [
        'product',
        'find',
        'What should we locate first, before narrowing the choice down to a particular pack?',
        '先确定产品类别。',
        'rice',
        'Rice, please. I would like to find the section first, then compare the brands and pack sizes before deciding.',
        'pasta',
        'Pasta, please. Once I can see the range, I can make a more informed choice about the pack.',
        {
          state: 'model-reviewed',
          record:
            'dining-review.md#task-3i-polish — affected question and both answers reread with selected context by Codex implementation agent, 2026-09-11; teacher0',
        },
      ],
      [
        'navigation',
        'navigate',
        'Both are in aisle three. Would a map be the right amount of help, or would you rather be taken there?',
        '帮助程度由用户选择。',
        'map',
        'A map would be just enough; I would like to find my own way without taking up more of your time.',
        'escort',
        'I would appreciate being taken there. At this point, a quick demonstration would be more useful than another attempt to interpret directions.',
        reviewed,
      ],
      [
        'size',
        'quantity',
        'Which consideration should carry more weight: a lighter half-kilo pack or having a kilo available at home?',
        '具体数量与抽象取舍结合。',
        'half',
        'The lighter half-kilo pack wins for me. Extra supplies are less useful if bringing them home becomes inconvenient.',
        'kilo',
        'Having a kilo available is the more practical choice; storage is not an issue, and I expect to use the quantity.',
        reviewed,
      ],
      [
        'brand',
        'preference',
        'Is the brand a genuine requirement, or a useful shortcut for something else you value?',
        '区分真正要求与代理依据。',
        'own',
        'It is not a requirement. I would consider the own-brand option rather than let the label stand in for a judgement about the product.',
        'familiar',
        'It is a shortcut for consistency in a recipe, so I would stay with a familiar brand on this occasion.',
        reviewed,
      ],
      [
        'compare',
        'compare',
        'Which comparison would answer your actual question, rather than simply highlight a larger number or a smaller pack?',
        '明确单位比较和现金支出问题。',
        'unit',
        'The price per kilo would answer the value question, as long as both figures use the same unit and the quantity is useful to me.',
        'bag',
        'The bag price would answer what I can spend today; a lower unit price would not help if the upfront cost exceeded that amount.',
        reviewed,
      ],
      [
        'checkout',
        'service',
        'Would access to a cashier or control over the scanning process better suit how you want to finish shopping?',
        '服务渠道选择无支付执行。',
        'cashier',
        'Access to a cashier would suit me, particularly if a shelf-price query needs resolving before I commit to the purchase.',
        'self',
        'I would prefer control over scanning at self-checkout, while still asking for assistance if something needs clarification.',
        reviewed,
      ],
      [
        'reach',
        'assistance',
        'Would assistance with the upper shelf be welcome, or would offering more help be unnecessary?',
        '接受帮助不要求解释健康状况。',
        'help',
        'It would be welcome. I can manage the rest of the shopping, but this particular bag is beyond comfortable reach.',
        'self',
        'I can reach the bag comfortably, thank you. There is no need to arrange assistance simply because it is on an upper shelf.',
        reviewed,
      ],
      [
        'bag',
        'packing',
        'Is taking the shopping home already accounted for, or is a shop bag still needed?',
        '携带包装不依赖是否用篮/车。',
        'own',
        'It is accounted for: I have a reusable bag, so another bag would be redundant.',
        'shop',
        'A shop bag is still needed. I overlooked that part of the trip and have nothing suitable to carry the shopping home.',
        reviewed,
      ],
      [
        'fallback',
        'alternative',
        'If the preferred pack were missing on another visit, where would you draw the line on substitution?',
        '表达替代边界，不预测库存。',
        'compare',
        'I would consider a substitute after checking its contents and price, but I would not treat availability alone as a reason to buy it.',
        'wait',
        'I would postpone the purchase. Finishing the list is less important than avoiding a substitute that does not serve the same purpose.',
        reviewed,
      ],
      [
        'label',
        'verify',
        'What would you like established from the label, without reading more into it than it actually says?',
        '不把标签当通用质量或安全结论。',
        'weight',
        'The net weight, so I can distinguish the amount inside from the unit used for the price comparison.',
        'date',
        'The location and wording of the printed date; I would rather identify that precisely than infer it from the pack’s appearance.',
        reviewed,
      ],
      [
        'carrier',
        'equipment',
        'Would a basket’s flexibility justify carrying the load, or would a trolley be the more sensible tool?',
        '不用生硬隐喻推高等级。',
        'basket',
        'A basket would be sufficient; moving easily around the aisles matters more here than having the load supported.',
        'trolley',
        'A trolley would be more sensible. I can steer it around the shop without having to carry the accumulated weight.',
        reviewed,
      ],
      [
        'purpose',
        'purpose',
        'Are you shopping with a specific meal in mind, or trying to keep your options open for later?',
        '目的与已有产品和份量都兼容。',
        'meal',
        'I have a specific meal in mind. I would rather buy for that need than find a purpose for extra groceries afterwards.',
        'options',
        'Keeping my options open is the aim; I want a supply in the cupboard rather than ingredients for one fixed recipe.',
        reviewed,
      ],
    ],
    variantReview,
  ),
}
