import { topic, type DialoguePack } from './types'

export const dailyDialogues: Record<string, DialoguePack> = {
  'ask-directions': [
    topic(
      'Where would you like to go?',
      'Are you looking for the train station?',
      'There are two stations nearby with similar names. Which line or destination are you trying to reach?',
      'Where is the station?',
      'I am looking for the central station. Is it nearby?',
      'I need the central railway station rather than the metro stop; could you point me towards the correct entrance?',
    ),
    topic(
      'Would you prefer to walk there?',
      'Do you know where to turn left?',
      'The shorter route has several steps, while the main road is easier to follow. Which would suit you better?',
      'How far is the walk?',
      'Should I go straight and then turn left?',
      'I would prefer the easier route even if it takes longer; could you describe the turns and approximate walking time?',
    ),
    topic(
      'Can you see the building opposite?',
      'Would a nearby landmark help you?',
      'The entrance is partly hidden by roadworks. Which landmark can you see so I can explain the final turn?',
      'Is it opposite the bank?',
      'Is the entrance on the corner beside the bank?',
      'I can see the bank but not the entrance; should I continue to the next corner or cross the road here?',
    ),
  ],
  'taxi-ride': [
    topic(
      'What address are you going to?',
      'Is that the hotel near the station?',
      'There are two branches of that hotel. Could you confirm the address before we set off?',
      'Please go to this address.',
      'I am heading to the Riverside Hotel on King Street.',
      'Please take me to the King Street branch of the Riverside Hotel; I have the address here to avoid confusion.',
    ),
    topic(
      'Do you need to arrive soon?',
      'Would you prefer the highway today?',
      'The highway is faster but includes a toll. Would saving time justify the extra cost for you?',
      'I need to arrive by two.',
      'How is the traffic? I need to arrive before two.',
      'Arriving before two is my priority, so I would consider the highway if the time saving is significant; please confirm the toll first.',
    ),
    topic(
      'Where would you like to get out?',
      'Would you like a receipt today?',
      'Stopping directly outside is not allowed here. Would the side entrance work, or should we continue to the next safe stop?',
      'Please stop here. Can I pay by card?',
      'Could you drop me off at the side entrance and give me a receipt?',
      'The side entrance would be fine as long as stopping is permitted; I would also appreciate an itemised receipt when I pay.',
    ),
  ],
  'bank-card-problem': [
    topic(
      'What happened when you used your card?',
      'Was your payment declined in the shop?',
      'The card appears active, but you reported a declined payment. Could you describe the transaction without sharing your card number?',
      'My card was declined.',
      'My card was declined twice in a shop this morning.',
      'The card was declined for two ordinary purchases this morning, although it worked yesterday; I would like to understand the cause.',
    ),
    topic(
      'Are you using the official bank service?',
      'Do you need the verification process explained?',
      'We will use the secure bank channel for identity checks. What would you like clarified before continuing there?',
      'How can I verify my identity?',
      'Could you explain how to verify my identity through the official channel?',
      'I am happy to complete identity verification through the secure bank channel, but I would like the procedure explained before proceeding.',
    ),
    topic(
      'Would you like to discuss a replacement?',
      'Do you need to report a charge?',
      'If the card needs replacing, you may be without it temporarily. Which access or timing concerns should we discuss?',
      'Can I request a replacement?',
      'Could you explain the replacement process and whether I should freeze the card?',
      'Please explain the available options for blocking or replacing the card, including how I can access my account while waiting.',
    ),
  ],
  'collect-parcel': [
    topic(
      'Do you have your collection code?',
      'What name is on the parcel?',
      'The code does not match our collection record. Could you check the notification and confirm the collection point?',
      'Here is my collection code.',
      'The parcel is under Chen. I have the tracking number here.',
      'The notification lists this collection point, but the code may refer to another parcel; could we compare the tracking details?',
    ),
    topic(
      'Is this the parcel you expected?',
      'How many boxes are you collecting?',
      'Two parcels have similar names on the labels. Which delivery details can help us identify yours?',
      'I am collecting one parcel.',
      'The notification says there should be two boxes.',
      'The collection notification refers to two boxes from the same order; could you check whether the second arrived separately?',
    ),
    topic(
      'Is the box damaged on this side?',
      'Would you like the damage recorded?',
      'The outer packaging is damaged but the contents have not been checked. How would you like that condition documented?',
      'The box looks damaged.',
      'Could you document the damage before I collect the parcel?',
      'Before I accept the parcel, could we record the visible damage and clarify how to report any missing or affected contents?',
    ),
  ],
  'haircut-request': [
    topic(
      'How much length should I take off?',
      'Would you like just a small trim?',
      'You want a shorter cut but still need to tie it back. Where would you like the length to finish?',
      'Just a small trim, please.',
      'Please take about two centimetres off the length.',
      'I would like it shorter while retaining enough length to tie it back; could you show me the proposed length before cutting?',
    ),
    topic(
      'Would you like layers in your hair?',
      'Do you want to change your fringe?',
      'This style needs daily styling to hold its shape. Would you prefer that look or something easier to maintain?',
      'I would like a few layers.',
      'Could you add soft layers without changing my fringe?',
      'I like the shape in this photo, but I would prefer softer layers that work without extensive daily styling.',
    ),
    topic(
      'What would you like me to keep?',
      'Is there anything I should avoid?',
      'The reference photo has much shorter sides than yours. Which details are essential and which can be adapted?',
      'Please keep the fringe long.',
      'Please avoid cutting the sides too short.',
      'Please keep some weight at the sides and preserve the longer fringe; the overall shape matters more than copying every detail of the photo.',
    ),
  ],
  'phone-repair': [
    topic(
      'What is wrong with your phone?',
      'When does the screen stop responding?',
      'The fault is not constant. Does it happen while charging, using a particular app, or after the phone warms up?',
      'The screen is not working.',
      'The screen stops responding when the phone gets warm.',
      'The touch screen becomes unresponsive after prolonged use, particularly while charging, but starts working again after the phone cools down.',
    ),
    topic(
      'Have you tried restarting the phone?',
      'Did the update change the problem?',
      'You have already tried several fixes. Which changed the behaviour, even temporarily, and which made no difference?',
      'I tried a restart.',
      'I restarted it and installed the latest update.',
      'A restart briefly resolves the issue, whereas the software update made no noticeable difference; I have not attempted any hardware repairs.',
    ),
    topic(
      'Have you backed up your data?',
      'When do you need your phone back?',
      'The repair may involve replacing a component and could affect stored data. What would you like confirmed before authorising any work?',
      'Is my data backed up?',
      'Could you explain the repair time and whether my data will be kept?',
      'Before any work begins, please explain the data implications, estimated turnaround and warranty coverage so I can decide how to proceed.',
    ),
  ],
}
