import { topic, type DialoguePack } from './types'

export const diningDialogues: Record<string, DialoguePack> = {
  'coffee-order': [
    topic(
      'What size coffee would you like?',
      'Would you prefer hot or iced coffee?',
      'Our seasonal blend is fruity rather than chocolatey. How would you like to balance flavour and strength?',
      'A small latte, please.',
      'Could I try a medium iced latte with an extra shot?',
      'I usually prefer a fuller body, but I would try the seasonal blend if an extra shot keeps the flavour balanced.',
    ),
    topic(
      'Which milk would you like today?',
      'How much sugar should I add?',
      'Oat milk adds natural sweetness. Would you keep the syrup, reduce it, or leave it out altogether?',
      'Oat milk, no sugar, please.',
      'Could you use oat milk and half the usual syrup?',
      'Please leave out the syrup; I would rather keep the natural sweetness of the oat milk without masking the espresso.',
    ),
    topic(
      'Is your order for here or takeaway?',
      'Would you like a receipt as well?',
      'There is a short wait for takeaway orders. Would you prefer to wait here or collect your drink later?',
      'To go, please. How much is it?',
      'Takeaway, please. Could you confirm the total and where I should collect it?',
      'I can wait by the counter. Before I pay, could you confirm whether the milk substitution changes the total?',
    ),
  ],
  'restaurant-order': [
    topic(
      'Which dish on the menu interests you?',
      'Would you like to hear the specials?',
      'The special changes daily and contains a rich sauce. What would you like to know before choosing?',
      'What is in this dish?',
      'What does the daily special come with?',
      'Could you describe the main ingredients and how the special differs from the regular grilled option?',
    ),
    topic(
      'What would you like to order today?',
      'Which drink would you like with that?',
      'The kitchen can serve one course first while the main takes longer. How would you like the meal timed?',
      'Chicken and water, please.',
      'I would like the grilled chicken and sparkling water.',
      'Could we start with a salad while the chicken is being prepared, and have the drinks brought out first?',
    ),
    topic(
      'How would you like your steak cooked?',
      'Would you prefer rice or vegetables?',
      'We can change the side dish but not the marinade. Which adjustment would make this meal work for you?',
      'Medium, please, with vegetables.',
      'Could I have vegetables instead of rice, with the sauce on the side?',
      'The marinade is fine; I would appreciate a lighter side dish and the sauce served separately so I can adjust the amount.',
    ),
  ],
  'food-allergy': [
    topic(
      'Which food are you allergic to?',
      'Are there other ingredients you must avoid?',
      'I need to check the ingredients with our kitchen. Which allergens or dietary restrictions should I explain to the chef?',
      'I am allergic to nuts.',
      'I have a nut allergy, so I need to check the ingredients.',
      'I have a nut allergy, rather than a preference, and I need the kitchen to verify the ingredients before I order.',
    ),
    topic(
      'What should I ask the kitchen staff?',
      'Do you need separate cooking equipment?',
      'We cannot confirm how the equipment was used earlier. What information would help you decide whether to order?',
      'Is the food cooked separately?',
      'Could you check the risk of cross-contact in the kitchen?',
      'Please ask whether separate utensils and preparation surfaces are available; if that cannot be confirmed, I would prefer not to order.',
    ),
    topic(
      'Would you like to discuss another dish?',
      'Shall I ask about a different option?',
      'The chef cannot guarantee that dish is suitable. Would you like ingredient information for an alternative before making a decision?',
      'Is there an alternative?',
      'Could you check whether a simpler alternative would be suitable?',
      'I appreciate the clarification. Please provide the ingredient information for the alternative, and I will decide whether to proceed.',
    ),
  ],
  'return-item': [
    topic(
      'When did you buy this item?',
      'Do you have the receipt with you?',
      'The purchase is not showing on this receipt. What other purchase details could help us locate it?',
      'I bought it yesterday.',
      'I bought this last week, and here is the receipt.',
      'I purchased it online last Thursday; if the receipt is unclear, I can show the order confirmation instead.',
    ),
    topic(
      'What problem does the item have?',
      'When did it stop working properly?',
      'It works during this brief check but you reported an intermittent fault. Could you describe when the problem usually occurs?',
      'It is broken.',
      'It stopped working after ten minutes of normal use.',
      'The fault appears after it has been running for a while; restarting temporarily helps, but the problem then returns.',
    ),
    topic(
      'Would you prefer a refund or exchange?',
      'Would another model work for you?',
      'An identical replacement is unavailable today. Would you prefer a refund or to wait for an exchange?',
      'A refund, please.',
      'I would prefer a refund to the original payment method.',
      'Since I need a reliable replacement soon, a refund would work better than store credit; could you explain the next step?',
    ),
  ],
  'supermarket-help': [
    topic(
      'Which item are you looking for?',
      'Which aisle have you checked already?',
      'That product is stocked in two sections. Are you looking for the fresh version or the longer-life one?',
      'Where is the milk?',
      'I am looking for oat milk. Which aisle is it in?',
      'I checked the chilled section but could not find unsweetened oat milk; is there a shelf-stable version elsewhere?',
    ),
    topic(
      'What size or type do you need?',
      'Would you like to check the label?',
      'These packages look similar but their ingredients differ. Which label information matters most for your choice?',
      'I need dairy-free milk.',
      'I would like a dairy-free option without added sugar.',
      'Could you help me compare the ingredient labels? I am looking for an unsweetened dairy-free option rather than a flavoured drink.',
    ),
    topic(
      'Would a similar product be suitable?',
      'Do you need the same brand?',
      'The usual brand is out of stock until tomorrow. Would a different brand meet your needs today?',
      'Is there a similar one?',
      'Is a similar unsweetened product in stock?',
      'I am flexible about the brand provided the ingredients are comparable; otherwise, I would prefer to come back tomorrow.',
    ),
  ],
  'price-discount': [
    topic(
      'Which price would you like to check?',
      'Did you see a sale sign?',
      'The shelf label and the till show different prices. Could you point out the offer you were expecting?',
      'Is this on sale?',
      'The shelf price looks lower. Does the discount apply to this item?',
      'I noticed the promotional label beside this model; could you clarify whether it applies to this exact size and colour?',
    ),
    topic(
      'Do you have a coupon with you?',
      'Are you a member of the store?',
      'The coupon may not combine with the member offer. Would you like to compare the two before choosing?',
      'Is this coupon valid?',
      'Can I use the coupon without being a member?',
      'Could you explain the conditions and compare the coupon with the member offer, including any minimum spend?',
    ),
    topic(
      'Shall we check the total together?',
      'Would you like an itemised receipt?',
      'The total includes an item outside the promotion. Shall we review the price breakdown before you pay?',
      'What is the final price?',
      'Could you confirm the total after the discount?',
      'Before I pay, could we review the final amount and identify which item was excluded from the promotion?',
    ),
  ],
}
