import { topic, type DialoguePack } from './types'

// Fictional language practice only: no diagnosis, dosage, live location or private identifiers.
export const emergencyDialogues: Record<string, DialoguePack> = {
  'pharmacy-medicine': [
    topic(
      'What symptoms would you like to describe?',
      'How long have you felt this way?',
      'Before discussing products, could you describe the symptoms and their duration so I know what information you need?',
      'I have had a cough since yesterday.',
      'I have a sore throat and a cough that started yesterday.',
      'I would like to describe a sore throat and persistent cough that started yesterday, and ask whether I should speak to a clinician.',
    ),
    topic(
      'Do you have any known medicine allergies?',
      'Are you taking any other medicine?',
      'Interactions and allergies need a qualified check. What information would you like to discuss with the pharmacist?',
      'I have a medicine allergy.',
      'I take another medicine and need to check possible interactions.',
      'Before choosing any product, I would like the pharmacist to check my current medication and known allergies rather than assume it is suitable.',
    ),
    topic(
      'Which label instruction would you like explained?',
      'Would you like to speak to a pharmacist?',
      'The label is unclear to you. How would you ask a qualified pharmacist to explain it and when further help is appropriate?',
      'Could you explain the instructions?',
      'Could the pharmacist explain the directions and when I should seek medical help?',
      'I want to confirm that I have understood the label correctly and ask a qualified pharmacist when symptoms should prompt further professional advice.',
    ),
  ],
  'describe-symptoms': [
    topic(
      'Where does it hurt at the moment?',
      'How would you describe the discomfort?',
      'Different descriptions can mean different things. Could you explain the sensation and where you feel it, using your own words?',
      'My stomach hurts.',
      'I have a dull pain in my stomach.',
      'I am experiencing a persistent dull pain in my stomach, with occasional sharper discomfort; I would like to describe it accurately to the clinician.',
    ),
    topic(
      'When did the discomfort first start?',
      'Has it changed since yesterday?',
      'You mentioned that the symptoms vary. Could you explain the sequence and what has changed since they began?',
      'It started yesterday.',
      'It started yesterday evening and has become worse today.',
      'The discomfort began yesterday evening, eased briefly overnight and became more noticeable this morning; that change is what concerned me.',
    ),
    topic(
      'How strong is the pain now?',
      'Does the pain stay in one place?',
      'To help the clinician understand your description, how is the discomfort affecting your normal activities?',
      'The pain is in one place.',
      'The pain feels moderate, but it is affecting my sleep.',
      'I would describe the severity as moderate rather than mild, because it interrupts my sleep and makes normal movement uncomfortable.',
    ),
  ],
  'doctor-appointment': [
    topic(
      'Why would you like an appointment?',
      'Is this a routine appointment request?',
      'We need a brief reason to arrange the appropriate appointment. How would you describe the request without going into unnecessary detail?',
      'I would like a routine appointment.',
      'I need a non-emergency appointment to discuss recurring symptoms.',
      'I would like a non-emergency appointment to discuss symptoms that have been recurring; I can provide the clinician with the full history at the visit.',
    ),
    topic(
      'What day are you available?',
      'Would a morning appointment suit you?',
      'The first available appointment conflicts with your work. Would another day or a different time be more practical?',
      'I am available on Monday.',
      'Do you have an appointment on Monday afternoon?',
      'Monday afternoon would be most practical, but I can consider a morning appointment later in the week if nothing is available then.',
    ),
    topic(
      'Do you know where the clinic is?',
      'Which documents would you like to confirm?',
      'This will be your first visit to this clinic. Which arrangements should we confirm so you can arrive prepared?',
      'What documents should I bring?',
      'Could you confirm the clinic address and the documents I need?',
      'Could you confirm the location, arrival time and any documents or referral information needed for a first appointment?',
    ),
  ],
  'emergency-call': [
    topic(
      'What address are you calling from?',
      'Can you name a nearby landmark?',
      'For this fictional call, the street name is unclear. How would you clarify the location without guessing?',
      'In this practice, I am at Green Street.',
      'The practice address is ten Green Street, opposite the library.',
      'For this fictional scenario, the location is ten Green Street; the library opposite is the clearest landmark if the address is difficult to identify.',
    ),
    topic(
      'What happened at that location?',
      'Is anyone injured in this scenario?',
      'You did not witness the entire event. How would you distinguish what you observed from what you do not know?',
      'There was an accident in this scenario.',
      'In this practice scenario, someone fell, but I do not know the extent of the injury.',
      'In this fictional scenario, I saw someone fall but did not witness what caused it; I can describe what I observed without speculating.',
    ),
    topic(
      'Which question would you like repeated?',
      'Can you repeat what I just asked?',
      'Clear communication matters during the call. How would you check an instruction you did not fully understand?',
      'Please repeat the question.',
      'Could you repeat that slowly so I can confirm I understand?',
      'I did not fully understand the last question; could you repeat it slowly so I can confirm exactly what information you need?',
    ),
  ],
  'lost-property': [
    topic(
      'What item have you lost today?',
      'What colour and size is it?',
      'We have several similar items. Which distinctive feature would help identify yours without revealing sensitive contents?',
      'I lost a black bag.',
      'I lost a small black bag with a red zip.',
      'It is a small black shoulder bag with a distinctive red zip and a fabric label on the strap, which should help distinguish it.',
    ),
    topic(
      'Where did you last see it?',
      'What time did you leave that place?',
      'You visited several places this morning. Which location are you certain about, and which are only possibilities?',
      'I last saw it at the station.',
      'I last saw the bag on a bench at the station around ten.',
      'I am certain I had it on the station bench at about ten; the café is another possibility, but I cannot confirm that it was there.',
    ),
    topic(
      'How would you like us to contact you?',
      'Would you like the reference number?',
      'The item has not been found yet. What would you like confirmed about the report and how to follow up?',
      'Can I have a reference number?',
      'Please give me a report number so I can follow up.',
      'Could you confirm the report reference and the official follow-up process? I would also like to know what proof is required if the item is found.',
    ),
  ],
  'rental-repair': [
    topic(
      'What is broken in the flat?',
      'Where is the leak coming from?',
      'The fault has several visible effects. Which details would help the maintenance team understand the problem before attending?',
      'There is a leak in the kitchen.',
      'Water is leaking from the pipe under the kitchen sink.',
      'There is a recurring leak beneath the kitchen sink, and the cupboard becomes wet even when the tap has not been used recently.',
    ),
    topic(
      'How is the problem affecting you?',
      'Has the problem become worse today?',
      'We need to understand the impact to assess priority. What has changed, and what have you already reported?',
      'It is affecting the kitchen.',
      'The leak is getting worse and affecting the cupboard.',
      'The leak has become more frequent and is affecting the cupboard and nearby floor; I reported it yesterday and would appreciate an update on priority.',
    ),
    topic(
      'When could someone visit for the repair?',
      'How should we arrange access to the flat?',
      'The repair team has a limited visiting window. How can we agree on access while respecting your availability?',
      'I am home tomorrow morning.',
      'Could you arrange the repair tomorrow morning and call before arriving?',
      'Tomorrow morning would work if the arrival window is confirmed in advance; please contact me before anyone enters so we can agree on access.',
    ),
  ],
}
