import { topic, type DialoguePack } from './types'

export const socialDialogues: Record<string, DialoguePack> = {
  'first-small-talk': [
    topic(
      'What is your name, by the way?',
      'Is this your first visit here?',
      'We have not met before, but we seem to know the same host. How did you come to know them?',
      'Hi, my name is Lin.',
      'Hi, I am Lin. I know the host through a language class.',
      'I am Lin; the host and I met through a language exchange, so I thought this would be a good chance to meet a few people.',
    ),
    topic(
      'What do you enjoy doing after work?',
      'What brought you to this event?',
      'You mentioned trying something new recently. What drew you to it, and has it turned out as you expected?',
      'What do you like to do?',
      'What do you enjoy most about living here?',
      'You mentioned moving here fairly recently; what has surprised you most, and what have you found easiest to settle into?',
    ),
    topic(
      'Would you like to keep in touch?',
      'Do you need to leave soon?',
      'It has been lovely talking, but we both need to circulate. How would you like to stay in touch?',
      'Nice to meet you. See you soon.',
      'It was nice meeting you. Could we keep in touch?',
      'I have enjoyed our conversation; I should let you catch up with the others, but I would be glad to continue it another time.',
    ),
  ],
  'networking-event': [
    topic(
      'What kind of work do you do?',
      'Which field are you interested in?',
      'You work across several areas. How would you describe the connecting thread without relying on a job title?',
      'I work in product design.',
      'I specialise in designing learning tools for adults.',
      'My work sits between learning design and product research, with a focus on turning difficult concepts into practical experiences.',
    ),
    topic(
      'What project are you working on?',
      'Do we share any professional interests?',
      'Our projects seem related but serve different audiences. Where do you see a useful overlap?',
      'I am interested in language learning.',
      'We both seem interested in helping adults learn new skills.',
      'Although our audiences differ, we share the challenge of helping learners sustain practice; I would be interested in comparing our approaches.',
    ),
    topic(
      'Shall we arrange a short follow-up?',
      'Would you like to exchange contact details?',
      'A broad collaboration may be premature. What small, specific follow-up would make this conversation useful?',
      'Could we keep in touch?',
      'Would you be open to a short call next week?',
      'Rather than proposing a full collaboration now, could we arrange a short call to compare one relevant project and see whether there is a fit?',
    ),
  ],
  'make-invitation': [
    topic(
      'What would you like us to do?',
      'Why does that activity interest you?',
      'You mentioned an event that might suit both of us. What makes you think it would be a good choice?',
      'Would you like to have lunch?',
      'Would you like to visit the new exhibition with me?',
      'There is a small exhibition I think you would enjoy, especially given your interest in photography; would you like to go together?',
    ),
    topic(
      'When and where should we meet?',
      'Would Saturday afternoon work for you?',
      'We are coming from different parts of town. What time and meeting point would be convenient for both of us?',
      'Saturday at two, at the station.',
      'Shall we meet outside the station at two on Saturday?',
      'Would two on Saturday work, with the station as a meeting point? It should be straightforward for both of us to get there.',
    ),
    topic(
      'Would another time work better for you?',
      'Shall we confirm the plan tomorrow?',
      'I am interested but cannot commit yet. How could we keep the plan flexible without leaving everything uncertain?',
      'We could go another time.',
      'No problem. Could you let me know by tomorrow?',
      'That is absolutely fine; perhaps we could keep Saturday as a possibility and confirm tomorrow, with Sunday as an alternative.',
    ),
  ],
  'polite-refusal': [
    topic(
      'Would you like to join our event?',
      'Did you get my invitation yesterday?',
      'I hoped you could join because your perspective would help. How would you respond while acknowledging the invitation?',
      'Thank you for inviting me.',
      'I appreciate the invitation and you thinking of me.',
      'Thank you for thinking of me; I appreciate the invitation, particularly knowing how much effort you have put into organising this.',
    ),
    topic(
      'Are you able to come that day?',
      'Would changing the time help you?',
      'We could adjust the timing if that helps. Is this mainly a scheduling problem, or should we plan without you?',
      'I cannot come this time.',
      'I am afraid I cannot make it because I already have a commitment.',
      'I appreciate the flexibility, but I will need to decline this time rather than ask you to change the plans around me.',
    ),
    topic(
      'Could we arrange something another time?',
      'Is there another way you could help?',
      'I understand you cannot attend. Is there a realistic alternative you would like to offer, without taking on too much?',
      'Maybe we can meet next week.',
      'Could we catch up another time, perhaps next week?',
      'I cannot attend, but I could review the short outline beforehand if that would help; otherwise, I would be happy to catch up next week.',
    ),
  ],
  'discuss-opinions': [
    topic(
      'What do you think about remote work?',
      'Which part of the idea interests you?',
      'Remote work offers flexibility but can weaken informal learning. How do you weigh those competing effects?',
      'I think remote work is useful.',
      'I think a mixed approach works better than one fixed rule.',
      'My view is that flexibility has real value, but the arrangement should account for the kind of collaboration and support each role needs.',
    ),
    topic(
      'Why do you see it that way?',
      'Which reason matters most to you?',
      'You have explained your position. What would you ask to understand why someone might reasonably disagree?',
      'Why do you prefer the office?',
      'Could you explain the main reason for your preference?',
      'If I understand your perspective correctly, you are concerned about learning from colleagues; is that your main reason for preferring office time?',
    ),
    topic(
      'Is there anything we agree on?',
      'Where do our views still differ?',
      'We agree on the aim but differ on the method. Can you identify common ground without pretending the disagreement has disappeared?',
      'We agree that teamwork matters.',
      'I agree about teamwork; however, I still value flexibility.',
      'We share the goal of effective collaboration, even though we differ on how much office time it requires; a trial could help test our assumptions.',
    ),
  ],
  'apology-repair': [
    topic(
      'What happened with our meeting yesterday?',
      'What would you like to say first?',
      'The missed meeting affected other people as well. How would you acknowledge your specific responsibility without making excuses?',
      'I am sorry I was late.',
      'I am sorry I missed the meeting without letting you know.',
      'I should have told you as soon as I realised I could not attend; leaving you waiting was my responsibility, and I am sorry.',
    ),
    topic(
      'Do you understand why I was upset?',
      'How did that affect our plans?',
      'An apology helps, but I want to know you understand the impact. What do you think made this particularly frustrating?',
      'I understand that you were upset.',
      'I understand it was frustrating to wait and change your plans.',
      'I understand that the lack of notice wasted your time and left you to explain my absence, which made the impact greater than a simple delay.',
    ),
    topic(
      'How could you make this right?',
      'What will you change next time?',
      'You have promised to do better before. What specific change would make that promise more credible this time?',
      'I will call next time.',
      'I will confirm the meeting beforehand and call if anything changes.',
      'To make this right, I will handle the rescheduling and confirm future commitments in advance; if plans change, I will tell you immediately.',
    ),
  ],
}
