import { topic, type DialoguePack } from './types'

export const studyDialogues: Record<string, DialoguePack> = {
  'class-introduction': [
    topic(
      'Could you introduce yourself to the class?',
      'Where have you studied before?',
      'Your classmates have varied backgrounds. Which part of your background would help them understand your perspective?',
      'My name is Lin. I am from Shanghai.',
      'I am Lin, and my background is in design.',
      'I am Lin, with a background in design rather than formal language teaching, so I am interested in how different learning approaches translate into practice.',
    ),
    topic(
      'What do you enjoy learning about?',
      'Which topic interests you the most?',
      'The course covers several approaches. Which topic connects most closely with an experience or question you already have?',
      'I enjoy learning languages.',
      'I am interested in how people practise speaking with confidence.',
      'My main interest is how repeated practice changes confidence, especially when learners understand the language but hesitate to use it.',
    ),
    topic(
      'What is your goal for this course?',
      'Which skill would you like to improve?',
      'A broad goal can be difficult to evaluate. What specific outcome would tell you this course had been useful?',
      'I want to speak more clearly.',
      'My goal is to explain my ideas clearly in a short discussion.',
      'By the end of the course, I would like to sustain a discussion, respond to questions and clarify my position without relying on a prepared script.',
    ),
  ],
  'ask-teacher': [
    topic(
      'Which part are you finding difficult?',
      'Where did you get stuck exactly?',
      'You followed the first steps but reached a different result. Where did your reasoning start to diverge?',
      'I am stuck on this step.',
      'I understand the example, but I am confused by the second step.',
      'I can follow the initial assumption, but I lose the connection between the second step and the conclusion; could we look at that transition?',
    ),
    topic(
      'What would you like me to explain?',
      'Would another example help you understand?',
      'Would a definition, a worked example or a comparison address your question most directly?',
      'Could you explain this again?',
      'Could you show another example of how this rule works?',
      'Could you compare a case where the rule applies with one where it does not, so I can understand the boundary rather than memorise the example?',
    ),
    topic(
      'Can you explain it in your words?',
      'What would you try in this example?',
      'You can repeat the rule, but applying it is the next step. How would you use it in a slightly different case?',
      'So I should check the first step.',
      'So, if I understand correctly, I should identify the subject first.',
      'Let me check my understanding: the choice depends on the context rather than a fixed pattern, so I should identify that context before applying the rule.',
    ),
  ],
  'group-project': [
    topic(
      'Which part would you like to handle?',
      'Who could work on the research?',
      'Everyone wants the same task, while another task is unassigned. How could we divide the work fairly?',
      'I can do the research.',
      'I could handle the research while someone else prepares the slides.',
      'Could we divide the work by both workload and relevant strengths, with a shared review so no one is left carrying an overlooked task?',
    ),
    topic(
      'When should we finish the first draft?',
      'What do you need from the team?',
      'The slides depend on the research, but both are due together. How should we sequence the work?',
      'The draft is due on Friday.',
      'I need the research by Wednesday to finish the slides on Friday.',
      'Since the slides depend on the research, I suggest an internal deadline on Wednesday and a joint review before the final submission on Friday.',
    ),
    topic(
      'Does anyone have too much work?',
      'Would you like to exchange one task?',
      'One member has fallen behind and others feel the workload is uneven. What adjustment would be fair and practical?',
      'Can we share this task?',
      'The workload seems uneven. Could we redistribute the remaining tasks?',
      'Could we review the remaining workload openly and redistribute specific tasks, while agreeing how everyone will contribute to the final review?',
    ),
  ],
  'presentation-qa': [
    topic(
      'Did you understand the audience question?',
      'Which part would you like clarified?',
      'The question touches both your method and your conclusion. How would you check which part the audience wants addressed first?',
      'Could you repeat the question?',
      'Are you asking about the method or the result?',
      'Just to clarify, are you questioning the choice of method, or asking how far the conclusion can be applied beyond this example?',
    ),
    topic(
      'What is your main answer to that?',
      'Can you give a short example?',
      'You have limited time to answer. How would you organise a clear response while still giving supporting evidence?',
      'The main reason is the cost.',
      'There are two reasons: the cost and the time required.',
      'I would distinguish the practical reason from the evidence: the approach was feasible within our constraints, and the comparison showed a consistent improvement.',
    ),
    topic(
      'Is there anything you cannot confirm?',
      'Would you need to check more evidence?',
      'The audience asks about a case you did not study. How can you acknowledge the limitation without dismissing the question?',
      'I do not know that yet.',
      'That is outside our data, but I can check and follow up.',
      'Our evidence does not cover that case, so I would not want to speculate; I can explain the limitation and identify what further work would be needed.',
    ),
  ],
  'seminar-discussion': [
    topic(
      'What is the author’s main point?',
      'How would you summarise that argument?',
      'Several interpretations have been offered. How would you summarise the central argument before giving your own view?',
      'The author says practice is important.',
      'The author argues that regular practice matters more than long sessions.',
      'As I understand it, the author’s central claim concerns consistency rather than intensity, although the examples do not establish that this holds in every context.',
    ),
    topic(
      'What evidence supports your own view?',
      'Can you point to an example?',
      'Your interpretation challenges the previous speaker’s. Which evidence supports it, and what alternative explanation should we consider?',
      'The example supports this idea.',
      'I agree partly, because the example shows a clear improvement.',
      'The example supports a narrower conclusion than the one proposed; it shows improvement in that setting, but an alternative explanation could be the additional feedback.',
    ),
    topic(
      'What question should we discuss next?',
      'How could we test that idea?',
      'The discussion has reached agreement too quickly. What question could expose a useful assumption or unresolved tension?',
      'Would this work in another class?',
      'What would happen if the learners had less time to practise?',
      'Would the same result hold without individual feedback, and how could we separate the effect of practice from the support learners received?',
    ),
  ],
  'office-hours': [
    topic(
      'What would you like help with today?',
      'What have you prepared for our meeting?',
      'We have limited time together. Could you outline what you have tried and the main reason for coming?',
      'I need help with my essay.',
      'I brought an outline and two questions about my essay.',
      'I have revised the outline in response to the feedback, but I would value your help with one remaining issue before developing the next draft.',
    ),
    topic(
      'Which question is most important to you?',
      'Where would feedback be most useful?',
      'Your outline raises several issues. Which one would make the biggest difference if we resolved it today?',
      'Is my main argument clear?',
      'Could you help me make the main argument more focused?',
      'The most useful feedback would be on whether my central claim is sufficiently focused, since the choice of evidence depends on getting that right.',
    ),
    topic(
      'What will you do after this meeting?',
      'When will you bring the next draft?',
      'We have identified a direction rather than a complete solution. What will you do next, and how will you check your progress?',
      'I will revise the introduction.',
      'My next step is to revise the argument and send a draft on Friday.',
      'I will narrow the claim, select evidence that directly supports it and bring a revised outline on Friday to check that the structure now follows logically.',
    ),
  ],
}
