import { topic, type DialoguePack } from './types'

export const travelDialogues: Record<string, DialoguePack> = {
  'airport-check-in': [
    topic(
      'Where are you flying to today?',
      'May I see your passport, please?',
      'Your itinerary includes a connection. Which destination is your final stop, and are both flights on the same booking?',
      'I am flying to London.',
      'Here is my passport. My final destination is London.',
      'My final destination is London via Singapore, and both flights should be on the same booking; could you confirm that?',
    ),
    topic(
      'How many bags are you checking in?',
      'Do you have any hand luggage?',
      'This suitcase may exceed the allowance. Would you like to redistribute the contents before we check the baggage?',
      'I have one suitcase.',
      'I have one bag to check and a small carry-on.',
      'I would like to check one suitcase; if it exceeds the allowance, please explain my options before adding any charges.',
    ),
    topic(
      'Would you like an aisle seat?',
      'Do you need help finding the gate?',
      'The only aisle seat available is near the back. Would you prefer that or a window seat nearer the exit?',
      'An aisle seat, please.',
      'An aisle seat would be great. Which gate should I go to?',
      'I would prefer the aisle even towards the back; could you also confirm the boarding time and whether the gate might change?',
    ),
  ],
  'security-screening': [
    topic(
      'Can you put your laptop here?',
      'Do you need another tray today?',
      'You have several electronic devices. Which instructions would you like me to clarify before you unpack them?',
      'Should I remove my laptop?',
      'Do I need to take out all my electronics?',
      'Could you clarify whether the tablet also needs a separate tray, or whether only the laptop should be removed?',
    ),
    topic(
      'What is inside this small bottle?',
      'Is this liquid or solid medicine?',
      'This bottle needs a closer check. Could you explain what it contains and why you are carrying it?',
      'This is my medicine.',
      'The bottle contains medicine. Would you like me to show the label?',
      'It contains my medication in its original packaging; please let me know what information you need for the check.',
    ),
    topic(
      'Can you wait beside this table?',
      'Would you like me to repeat that?',
      'An additional inspection is needed and your gate is some distance away. What would you like to clarify about the process?',
      'Could you repeat that, please?',
      'Should I wait here for the additional inspection?',
      'I understand an additional inspection is required; could you explain where I should wait and when I can collect my belongings?',
    ),
  ],
  'flight-connection': [
    topic(
      'What is your next flight number?',
      'When does your connecting flight leave?',
      'Your arrival was delayed and boarding is already under way. Can you give me the onward flight details?',
      'My next flight is AB123.',
      'I am connecting to flight AB123, which leaves at three.',
      'My onward flight is AB123 at three, and the inbound delay has left very little connection time; what should I do first?',
    ),
    topic(
      'Do you know your next gate?',
      'Can you follow the transfer signs?',
      'The transfer desk and the departure gate are in different directions. Which information do you still need before heading over?',
      'Which way is the gate?',
      'What is the quickest route to the departure gate?',
      'Could you confirm the quickest transfer route and whether I need another security check before reaching the gate?',
    ),
    topic(
      'Would you like to check another flight?',
      'Can you travel later this evening?',
      'If the connection is no longer possible, would arriving later today or taking a different route be preferable?',
      'Is there another flight?',
      'If I miss it, could you help me with rebooking?',
      'My priority is arriving today; I would consider a different route if you can confirm the onward connection and baggage arrangements.',
    ),
  ],
  'immigration-interview': [
    topic(
      'What is the purpose of your visit?',
      'Are you visiting for work or leisure?',
      'Your itinerary includes a conference and several free days. Could you explain the main purpose of this visit?',
      'I am here on holiday.',
      'I am visiting for tourism and meeting a friend.',
      'The main purpose is attending a conference, followed by a few days of sightseeing before my return flight.',
    ),
    topic(
      'How long will you stay here?',
      'What date will you leave?',
      'Your booking covers part of the visit. How does the rest of your stay fit into your travel plan?',
      'I will stay for ten days.',
      'I plan to stay for ten days and leave next Friday.',
      'I will stay for ten days in total; the conference takes four days and the remaining time is for personal travel.',
    ),
    topic(
      'Where will you stay during your visit?',
      'Do you have your return ticket?',
      'You plan to stay at more than one address. Could you explain the accommodation and onward travel arrangements?',
      'I will stay at a hotel.',
      'Here are my hotel booking and return ticket.',
      'I have a hotel booking for the conference and another for sightseeing; my return ticket is confirmed for the final day.',
    ),
  ],
  'hotel-check-in': [
    topic(
      'What name is the reservation under?',
      'Do you have your booking confirmation?',
      'I cannot see the reservation under that spelling. Could it have been booked through another name or platform?',
      'My reservation is under Chen.',
      'I have a reservation under Chen. Here is the confirmation.',
      'The reservation is under Chen, although the booking platform may have reversed my first and last names; here is the confirmation number.',
    ),
    topic(
      'How many nights will you stay?',
      'Would you prefer a quiet room?',
      'Your booked room faces the street, while a quieter room is available later. Which arrangement would suit your stay?',
      'Two nights, in a quiet room.',
      'I booked a double room for two nights. Could it be away from the lift?',
      'I am staying for two nights and would prioritise a quiet room over immediate access, provided I can leave my luggage here.',
    ),
    topic(
      'Would you like breakfast during your stay?',
      'Do you need the check-out time?',
      'Your departure is later than the usual check-out time. Would luggage storage or a late check-out suit your plans better?',
      'What time is breakfast?',
      'Is breakfast included, and what time should I check out?',
      'Could you confirm the breakfast arrangements and whether late check-out is possible? Luggage storage would be a useful alternative.',
    ),
  ],
  'hotel-room-problem': [
    topic(
      'What is wrong with your room?',
      'When did you notice the problem?',
      'The issue has not appeared during our check. Could you describe when it happens and which part of the room is affected?',
      'The air conditioning is broken.',
      'The air conditioning keeps switching off in my room.',
      'The air conditioning stops intermittently, particularly at night; it may seem normal during a brief check but the problem keeps returning.',
    ),
    topic(
      'Is the noise keeping you awake?',
      'Has this affected your sleep tonight?',
      'I understand this has disrupted your stay. Which impact should we prioritise while arranging a solution?',
      'I cannot sleep.',
      'The noise has kept me awake, and I have an early meeting.',
      'The repeated noise is affecting my sleep before an early meeting; a reliable solution tonight matters more than a temporary adjustment.',
    ),
    topic(
      'Would you prefer a different room?',
      'When can we arrange the repair?',
      'A repair could take time, but another room is available on a different floor. Which would you prefer?',
      'Could I change rooms?',
      'I would prefer a room change if the repair will take a while.',
      'A room change would be preferable provided the replacement is quiet; could someone help with the move so I can settle in quickly?',
    ),
  ],
}
