import { topic, type DialoguePack } from './types'

export const workDialogues: Record<string, DialoguePack> = {
  'work-introduction': [
    topic(
      'What is your role on the team?',
      'Which tasks are you responsible for?',
      'Your role overlaps with another team. How would you describe your responsibility and where collaboration is needed?',
      'I work on the design team.',
      'I am responsible for researching customer needs.',
      'My role focuses on customer research and translating findings into product decisions, working closely with both design and engineering.',
    ),
    topic(
      'What work have you done before?',
      'Which project did you enjoy most?',
      'Which part of your previous experience is most relevant to the challenges this team is facing?',
      'I have two years of experience.',
      'I previously worked on a mobile learning product.',
      'My background in mobile learning is especially relevant because it involved balancing learner engagement with the constraints of a small development team.',
    ),
    topic(
      'How can we help you get started?',
      'Who would you like to work with?',
      'Several colleagues could help, but their time is limited. What would be the most useful first conversation?',
      'I look forward to working with you.',
      'Could we arrange a short introduction to the project team?',
      'A brief conversation with the project owner would help me understand the current priorities before I propose how best to contribute.',
    ),
  ],
  'daily-standup': [
    topic(
      'What did you finish yesterday?',
      'Which task is ready for review?',
      'The task is marked complete but the review is pending. What is finished, and what still needs confirmation?',
      'I finished the report yesterday.',
      'Yesterday I completed the draft and sent it for review.',
      'The implementation is complete and the tests pass; the remaining review is a dependency rather than unfinished development work.',
    ),
    topic(
      'What will you work on today?',
      'Which task is your first priority?',
      'Two items are competing for today’s time. Which will you prioritise, and what will you defer?',
      'Today I will test the feature.',
      'My priority today is testing the new flow before fixing minor issues.',
      'I will prioritise the customer-facing failure today and defer the cosmetic changes, because the failure blocks the team’s next milestone.',
    ),
    topic(
      'Is anything blocking your work today?',
      'What help do you need from us?',
      'The dependency has slipped again. What specific help would unblock you, and what can continue in parallel?',
      'I am blocked by the missing file.',
      'I need the API details before I can finish the integration.',
      'The integration is blocked by the missing API contract; an owner and delivery time would help, while I continue testing against the agreed mock.',
    ),
  ],
  'progress-update': [
    topic(
      'What is the current project status?',
      'Which milestone have you reached?',
      'The headline status sounds positive, but we need a decision today. Which milestone is actually complete and verifiable?',
      'The first milestone is complete.',
      'We have completed the first milestone and started testing.',
      'The core workflow is complete and has passed internal checks; the remaining milestone is external validation before we can call it release-ready.',
    ),
    topic(
      'Is there a risk to the schedule?',
      'What caused the delay this week?',
      'Your latest estimate differs from last week’s. What evidence explains the change, and what uncertainty remains?',
      'There is a delay in testing.',
      'Testing found a risk that may delay the release by two days.',
      'The revised estimate reflects a reproducible integration issue rather than a general slowdown; the main uncertainty is the partner’s response time.',
    ),
    topic(
      'What should our next step be?',
      'Which decision do you need today?',
      'We can reduce scope or move the date, but not both without justification. Which option do you recommend?',
      'We need a decision on the date.',
      'The next step is to agree on a smaller release scope.',
      'I recommend keeping the date and deferring the optional feature; I need approval of that scope change so the team can finish validation.',
    ),
  ],
  'deadline-negotiation': [
    topic(
      'Why do you need more time?',
      'What is causing the current delay?',
      'The deadline is tied to a public commitment. Which constraint makes the current date unworkable despite that commitment?',
      'We need more time for testing.',
      'The delay is caused by an integration issue we found in testing.',
      'The integration failure affects the core workflow, so meeting the current deadline would require accepting a reliability risk that I cannot recommend.',
    ),
    topic(
      'What new date can you offer?',
      'Could we reduce the scope instead?',
      'A later date solves the testing constraint but affects the launch. Could a phased delivery protect the most important outcome?',
      'We can deliver on Friday.',
      'We could deliver the core scope on Friday and the rest next week.',
      'A phased delivery would preserve the launch’s essential scope this Friday while giving us until Tuesday to validate the remaining integration.',
    ),
    topic(
      'What can you commit to now?',
      'When will you send the next update?',
      'If we accept the revised plan, what evidence and update schedule will let us know it is still on track?',
      'I will send an update tomorrow.',
      'I can commit to a tested version on Friday and daily updates.',
      'I will provide a verified build on Friday and flag any material risk in the daily update, with clear ownership of each remaining dependency.',
    ),
  ],
  'meeting-disagreement': [
    topic(
      'What outcome do we both want?',
      'Which part of the plan do you support?',
      'Before challenging the proposal, could you identify the shared outcome you want to protect?',
      'We have the same goal.',
      'I support the goal of making the process faster.',
      'I agree that reducing turnaround time is the right objective, and my concern is about whether this approach achieves it reliably.',
    ),
    topic(
      'What is your concern about the plan?',
      'Which risk should we discuss first?',
      'The team believes this risk is unlikely. What concrete evidence makes you think we should address it now?',
      'I am concerned about the cost.',
      'My concern is that the proposed shortcut could increase errors.',
      'The pilot showed errors when the review step was removed, so I am concerned that a faster process could create more rework downstream.',
    ),
    topic(
      'What alternative would you suggest?',
      'Could we test your idea first?',
      'Your alternative adds a step to the process. How would you test whether the extra effort is justified?',
      'We could run a small pilot.',
      'Could we test both options with a small pilot before deciding?',
      'I suggest a limited comparison using turnaround time and rework as measures, so we can decide on evidence rather than preference.',
    ),
  ],
  'job-interview': [
    topic(
      'Why are you interested in this role?',
      'What do you like about our team?',
      'You could pursue a similar role elsewhere. What makes this particular opportunity a good fit for your next step?',
      'I am interested in your product.',
      'I applied because the role combines research with practical product work.',
      'This role interests me because it connects customer research with implementation, which is the direction I want to develop after several research-led projects.',
    ),
    topic(
      'Can you describe a work challenge?',
      'What was the result of your action?',
      'The result sounds strong, but several people were involved. What did you personally do, and how did you assess its impact?',
      'I helped my team finish a project.',
      'I simplified the review process, which helped the team finish on time.',
      'When reviews became a bottleneck, I introduced a shared checklist and clearer ownership; the next delivery completed on time with fewer repeated corrections.',
    ),
    topic(
      'What would you like to ask us?',
      'Do you have questions about the team?',
      'What information about the role would help you judge whether you could succeed here, beyond the job description?',
      'What is the team working on?',
      'How would you measure success in this role during the first three months?',
      'Could you explain the main challenge the person in this role will inherit and how priorities are negotiated across the teams involved?',
    ),
  ],
}
