// Metadata only: importing scene cards must not import authored dialogue prose.
export const gradedSceneManifest = [
  {
    sceneId: 'work-01',
    category: 'work',
    titleZh: '职场自我介绍',
    contentVersion: 1,
    levels: ['A1', 'A2', 'B1', 'B2', 'C1'],
  },
  {
    sceneId: 'work-02',
    category: 'work',
    titleZh: '每日站会',
    contentVersion: 1,
    levels: ['A1', 'A2', 'B1', 'B2', 'C1'],
  },
  {
    sceneId: 'work-03',
    category: 'work',
    titleZh: '进度汇报',
    contentVersion: 1,
    levels: ['A1', 'A2', 'B1', 'B2', 'C1'],
  },
  {
    sceneId: 'work-04',
    category: 'work',
    titleZh: '截止日期协商',
    contentVersion: 1,
    levels: ['A1', 'A2', 'B1', 'B2', 'C1'],
  },
  {
    sceneId: 'work-05',
    category: 'work',
    titleZh: '会议异议',
    contentVersion: 1,
    levels: ['A1', 'A2', 'B1', 'B2', 'C1'],
  },
  {
    sceneId: 'work-06',
    category: 'work',
    titleZh: '工作面试',
    contentVersion: 1,
    levels: ['A1', 'A2', 'B1', 'B2', 'C1'],
  },
  {
    sceneId: 'daily-01',
    category: 'daily',
    titleZh: '问路',
    contentVersion: 1,
    levels: ['A1', 'A2', 'B1', 'B2', 'C1'],
  },
  {
    sceneId: 'daily-02',
    category: 'daily',
    titleZh: '乘出租车',
    contentVersion: 1,
    levels: ['A1', 'A2', 'B1', 'B2', 'C1'],
  },
  {
    sceneId: 'daily-03',
    category: 'daily',
    titleZh: '银行卡问题',
    contentVersion: 1,
    levels: ['A1', 'A2', 'B1', 'B2', 'C1'],
  },
  {
    sceneId: 'daily-04',
    category: 'daily',
    titleZh: '领取包裹',
    contentVersion: 1,
    levels: ['A1', 'A2', 'B1', 'B2', 'C1'],
  },
  {
    sceneId: 'daily-05',
    category: 'daily',
    titleZh: '理发要求',
    contentVersion: 1,
    levels: ['A1', 'A2', 'B1', 'B2', 'C1'],
  },
  {
    sceneId: 'daily-06',
    category: 'daily',
    titleZh: '手机维修',
    contentVersion: 1,
    levels: ['A1', 'A2', 'B1', 'B2', 'C1'],
  },
  {
    sceneId: 'travel-01',
    category: 'travel',
    titleZh: '机场值机',
    contentVersion: 1,
    levels: ['A1', 'A2', 'B1', 'B2', 'C1'],
  },
  {
    sceneId: 'travel-02',
    category: 'travel',
    titleZh: '安检沟通',
    contentVersion: 1,
    levels: ['A1', 'A2', 'B1', 'B2', 'C1'],
  },
  {
    sceneId: 'travel-03',
    category: 'travel',
    titleZh: '航班转机',
    contentVersion: 1,
    levels: ['A1', 'A2', 'B1', 'B2', 'C1'],
  },
  {
    sceneId: 'travel-04',
    category: 'travel',
    titleZh: '入境问答',
    contentVersion: 1,
    levels: ['A1', 'A2', 'B1', 'B2', 'C1'],
  },
  {
    sceneId: 'travel-05',
    category: 'travel',
    titleZh: '酒店入住',
    contentVersion: 1,
    levels: ['A1', 'A2', 'B1', 'B2', 'C1'],
  },
  {
    sceneId: 'travel-06',
    category: 'travel',
    titleZh: '酒店房间问题',
    contentVersion: 1,
    levels: ['A1', 'A2', 'B1', 'B2', 'C1'],
  },
  {
    sceneId: 'dining-01',
    category: 'dining',
    titleZh: '咖啡点单',
    contentVersion: 1,
    levels: ['A1', 'A2', 'B1', 'B2', 'C1'],
  },
  {
    sceneId: 'dining-02',
    category: 'dining',
    titleZh: '餐厅点餐',
    contentVersion: 1,
    levels: ['A1', 'A2', 'B1', 'B2', 'C1'],
  },
  {
    sceneId: 'dining-03',
    category: 'dining',
    titleZh: '食物过敏',
    contentVersion: 1,
    levels: ['A1', 'A2', 'B1', 'B2', 'C1'],
  },
  {
    sceneId: 'dining-04',
    category: 'dining',
    titleZh: '退换商品',
    contentVersion: 1,
    levels: ['A1', 'A2', 'B1', 'B2', 'C1'],
  },
  {
    sceneId: 'dining-05',
    category: 'dining',
    titleZh: '超市求助',
    contentVersion: 1,
    levels: ['A1', 'A2', 'B1', 'B2', 'C1'],
  },
  {
    sceneId: 'dining-06',
    category: 'dining',
    titleZh: '价格与折扣',
    contentVersion: 1,
    levels: ['A1', 'A2', 'B1', 'B2', 'C1'],
  },
] as const
