import { socialPack, type SocialScene, type Review } from './authoring'
const read = {
  A1: {
    state: 'model-reviewed',
    record: 'social-review.md: fix1 discuss-opinions.A1 complete-unit reread 2026-09-10',
  },
  A2: {
    state: 'model-reviewed',
    record: 'social-review.md: discuss-opinions.A2',
  },
  B1: {
    state: 'model-reviewed',
    record: 'social-review.md: discuss-opinions.B1',
  },
  B2: {
    state: 'model-reviewed',
    record: 'social-review.md: discuss-opinions.B2',
  },
  C1: {
    state: 'model-reviewed',
    record: 'social-review.md: discuss-opinions.C1',
  },
} satisfies Record<string, Review>
const scene: SocialScene = {
  sceneId: 'social-05',
  slug: 'discuss-opinions',
  situations: [
    '虚构朋友聊天：你与 Rowan 讨论社区周末活动是否应留出安静时段。Rowan 开场已说：“I like lively events, but people should have a choice.” 这不是投票或正式决策，双方可以保持不同看法。例子可用虚构体验，未发生任何调查或政策改变；学习成功指表达清楚，不是同意 Rowan。',
    '同一虚构周末活动话题，Rowan 的原话是：“I like lively events, but people should have a choice.” 你们时间有限，重点澄清 lively 的含义、比较观点、辨别假设并尊重分歧。只讨论可能方案，不声称已咨询居民、投票或达成共识。',
  ],
  paths: [
    {
      short: ['position', 'reason', 'close'],
      standard: ['position', 'reason', 'example', 'priority', 'other', 'close'],
      extended: [
        'position',
        'reason',
        'example',
        'priority',
        'other',
        'proposal',
        'tradeoff',
        'evidence',
        'limit',
        'close',
      ],
    },
    {
      short: ['position', 'meaning', 'close'],
      standard: ['position', 'meaning', 'other', 'tone', 'limit', 'close'],
      extended: [
        'position',
        'meaning',
        'reason',
        'example',
        'other',
        'tone',
        'proposal',
        'tradeoff',
        'limit',
        'close',
      ],
    },
  ],
  closing:
    'That completes the opinion practice. Clear communication counts here, whether or not our views match. No community decision has been made.',
  partial:
    'We will pause with some points still unexplored. Different views can remain, and no agreement or community decision is assumed.',
  repairs: {
    clarify:
      'We can clarify the current point without asking you to change your view.',
    struggle:
      'You can state one simple preference or ask for help with the question.',
    offTopic:
      'We can return to weekend events and quiet time if you want to continue.',
    unknown:
      'I have not matched that wording in this local set; I am not judging the opinion or confirming a new point.',
    changed: 'Your revised view replaces the earlier answer in this practice.',
    refusedClosing:
      'We will end the discussion here. You do not have to defend a view or agree with mine.',
  },
}
export const discussOpinions = {
  A1: socialPack(
    scene,
    'A1',
    {
      canDoZh: '用简单句说活动喜好、声音感受，问时间地点并礼貌结束聊天。',
      complexityZh:
        '围绕音乐、游戏、画画和安静角落做具体选择；不要求比较抽象方案或论证证据。',
      scaffoldingZh:
        '对方原话已给出；每题只问一件事，提供短句，可要求举例或放慢。',
      registerZh: '朋友间平实口语，不同喜好同样有效；建议不是已决定的活动。',
    },
    [
      [
        'position',
        'state-position',
        'Do you want some quiet time at the event?',
        '说是否想有安静时段。',
        'yes',
        'Yes, I want some quiet time.',
        'no',
        'No, I like lots of music.',
        read.A1,
      ],
      [
        'reason',
        'share-enjoyment',
        'What do you enjoy at an event?',
        '说活动中喜欢做的事，不要求证明立场。',
        'talk',
        'I like talking to people.',
        'music',
        'I like listening to music.',
        read.A1,
      ],
      [
        'example',
        'recall-sound',
        'Was the last event you went to quiet or loud?',
        '用 quiet 或 loud 说一次虚构经历的声音。',
        'quiet',
        'It was quiet.',
        'loud',
        'It was loud.',
        read.A1,
      ],
      [
        'priority',
        'choose-activity',
        'Do you like games or drawing at events?',
        '选游戏或画画，与音乐偏好分开。',
        'games',
        'I like games.',
        'drawing',
        'I like drawing.',
        read.A1,
      ],
      [
        'other',
        'acknowledge-other',
        'Do you understand my idea, or do you need an example?',
        '可以说听懂，或请对方举例；不表示同意。',
        'yes',
        'Yes, I understand your idea.',
        'help',
        'Please give me an example.',
        read.A1,
      ],
      [
        'proposal',
        'suggest-object',
        'What can we put in a quiet corner?',
        '为假设的安静角落提议一种物品，没有决定设置角落。',
        'chairs',
        'We can put some chairs there.',
        'books',
        'We can put some books there.',
        read.A1,
      ],
      [
        'tradeoff',
        'describe-difficulty',
        'What is difficult for you in a noisy room?',
        '说具体困难：听朋友说话或思考。',
        'hear',
        'I cannot hear my friends.',
        'think',
        'I cannot think well.',
        read.A1,
      ],
      [
        'evidence',
        'ask-event-info',
        'What do you want to ask about the event?',
        '用 What time 或 Where 询问时间地点；还没有得到答案。',
        'time',
        'What time does it start?',
        'place',
        'Where is it?',
        read.A1,
      ],
      [
        'limit',
        'state-openness',
        'Do you like trying new activities?',
        '选择愿意尝新或喜欢熟悉活动，不用评价证据。',
        'new',
        'Yes, I like trying new things.',
        'familiar',
        'No, I like my usual activities.',
        read.A1,
      ],
      [
        'close',
        'close-discussion',
        'How can you end our chat?',
        '可以说要离开或想再想想，不假装达成一致。',
        'go',
        'Thanks for the chat. I must go.',
        'think',
        'Thanks. I want to think about it.',
        read.A1,
      ],
      [
        'meaning',
        'clarify-meaning',
        'What does lively mean here?',
        'lively 已在对方原话中出现；可用 busy and fun 或请解释。',
        'active',
        'It means busy and fun.',
        'ask',
        'I do not know. Please explain.',
        read.A1,
      ],
      [
        'tone',
        'request-pace',
        'Am I speaking too fast for you?',
        '可请求放慢，也可说速度合适。',
        'slow',
        'Yes, please slow down.',
        'fine',
        'No, this speed is OK.',
        read.A1,
      ],
    ],
    read.A1,
  ),
  A2: socialPack(
    scene,
    'A2',
    {
      canDoZh: '比较活动偏好，用经历和简单理由展开观点并请求澄清。',
      complexityZh: '分开个人喜好、别人需要和拟议方案，不把理解当成一致。',
      scaffoldingZh: '明确主题与已说原话，简单条件与比较句支撑互动。',
      registerZh: '礼貌闲聊，观点不同无需道歉。',
    },
    [
      [
        'position',
        'state-position',
        'Would quiet periods improve a weekend event for you?',
        '表达赞成或另一偏好。',
        'yes',
        'Yes, quiet periods would make the event more comfortable for me.',
        'no',
        'No, I would rather have music throughout the event.',
        read.A2,
      ],
      [
        'reason',
        'give-reason',
        'What is important to you when you choose the sound level?',
        '给独立需求，不暗示前面必选安静。',
        'talk',
        'It is important that I can talk to friends easily.',
        'energy',
        'I enjoy the energy that music brings.',
        read.A2,
      ],
      [
        'example',
        'give-example',
        'Can you describe the atmosphere at a past event?',
        '用具体虚构经历支撑讨论。',
        'quiet',
        'At one event, the quiet area made it easy to meet people.',
        'music',
        'At another event, the music made the whole place feel cheerful.',
        read.A2,
      ],
      [
        'priority',
        'name-priority',
        'Would you put more value on different options or a clear, simple schedule?',
        '选择组织重点。',
        'options',
        'Different options would help more people enjoy the event.',
        'simple',
        'A simple schedule would be easier for everyone to follow.',
        read.A2,
      ],
      [
        'other',
        'acknowledge-other',
        'Is it easy to see why other visitors might choose differently?',
        '理解他人或请求帮助理解。',
        'yes',
        'Yes, their idea of a good day may be different from mine.',
        'example',
        'I can see part of it, but an example would help.',
        read.A2,
      ],
      [
        'proposal',
        'offer-proposal',
        'If the organisers wanted to compare options, what could they try?',
        '假设试验不代表支持方案或改变立场。',
        'area',
        'They could consider a separate quiet area.',
        'schedule',
        'They could put quieter and louder activities at different times.',
        read.A2,
      ],
      [
        'tradeoff',
        'identify-tradeoff',
        'What difficulty might come with offering both quiet and lively activities?',
        '讨论成本而非否认多种需求。',
        'space',
        'There might not be enough room for separate areas.',
        'staff',
        'The organisers might need more people to help.',
        read.A2,
      ],
      [
        'evidence',
        'request-evidence',
        'What information would help you judge the options?',
        '先查需求或场地，不捏造答案。',
        'visitors',
        'Knowing what visitors prefer would help me.',
        'layout',
        'A plan of the space would help me judge what is possible.',
        read.A2,
      ],
      [
        'limit',
        'state-limit',
        'Could your view change after hearing more about the event?',
        '不同开放程度都可以诚实表达。',
        'stay',
        'I would probably keep my view for now.',
        'change',
        'Yes, more information about the space could change my view.',
        read.A2,
      ],
      [
        'close',
        'close-discussion',
        'What would you say to end without pretending we agree?',
        '差异可有可无，不强造一致或分歧。',
        'different',
        'We may have different preferences, and that is fine. Thanks for the chat.',
        'think',
        'I would like to think about it more. Thanks for sharing your view.',
        read.A2,
      ],
      [
        'meaning',
        'clarify-meaning',
        'Does lively mean the same thing to you as it does to me?',
        '针对已听到的词澄清。',
        'active',
        'I take it to mean active and cheerful, not always loud.',
        'ask',
        'I am not sure what you mean by it; could you explain?',
        read.A2,
      ],
      [
        'tone',
        'manage-tone',
        'Would you prefer a brief answer or a fuller explanation of my view?',
        '请求交流深度，不改变自己观点。',
        'brief',
        'A brief answer would be easier for me to follow.',
        'full',
        'A fuller explanation would help me understand you better.',
        read.A2,
      ],
    ],
    read.A2,
  ),
  B1: socialPack(
    scene,
    'B1',
    {
      canDoZh: '用理由和具体例子支撑观点，理解相反偏好并提出可试方案。',
      complexityZh:
        '区分经验、推测和待获取信息，讨论实施困难但不要求达成共识。',
      scaffoldingZh: '具体开放问题和连贯策略示例支持持续对话。',
      registerZh: '朋友间有理由的讨论，理解与赞成分开。',
    },
    [
      [
        'position',
        'state-position',
        'Where do you stand on including quiet periods in weekend events?',
        '表达支持或反对并限定个人偏好。',
        'support',
        'I support the idea because not everyone enjoys constant noise.',
        'oppose',
        'I would prefer a lively programme throughout, although I know that will not suit everyone.',
        read.B1,
      ],
      [
        'reason',
        'give-reason',
        'Which need carries the most weight for you when thinking about event sound?',
        '重点可独立于最初立场。',
        'conversation',
        'Being able to hold a conversation matters most to me.',
        'atmosphere',
        'A shared, energetic atmosphere matters most to me.',
        read.B1,
      ],
      [
        'example',
        'give-example',
        'What experience helps explain your view of event atmosphere?',
        '陈述一个具体经历，不伪造普遍事实。',
        'quiet',
        'I once went to a crowded event where a quiet corner gave me space to talk.',
        'music',
        'I remember an event where the music helped people relax and join in.',
        read.B1,
      ],
      [
        'priority',
        'name-priority',
        'Would you prioritise variety for visitors or simplicity for organisers?',
        '清楚说明权衡重点。',
        'variety',
        'I would prioritise variety so people could choose what suited them.',
        'simple',
        'I would prioritise a simple programme that the organisers could run well.',
        read.B1,
      ],
      [
        'other',
        'acknowledge-other',
        'How far can you understand a preference that is different from yours?',
        '可承认理解有限而不装作同意。',
        'understand',
        'I can understand it; people come to events with different needs and expectations.',
        'partial',
        'I understand part of it, but I would like an example of how it works for someone else.',
        read.B1,
      ],
      [
        'proposal',
        'offer-proposal',
        'What practical option would be worth trying, without deciding everything now?',
        '建议是试验而非执行。',
        'zone',
        'A clearly marked quiet area would be worth trying if space allowed.',
        'times',
        'Separating quieter activities from music in the timetable would be worth considering.',
        read.B1,
      ],
      [
        'tradeoff',
        'identify-tradeoff',
        'What might the organisers have to give up to offer more options?',
        '识别取舍而不保证可实施。',
        'room',
        'They might have less room for the main activity if they created another area.',
        'time',
        'They might need more volunteer time to run a more varied programme.',
        read.B1,
      ],
      [
        'evidence',
        'request-evidence',
        'What would you check before treating your preferred plan as practical?',
        '计划不等于已经核查。',
        'needs',
        'I would ask visitors about their needs rather than assume everyone felt as I do.',
        'space',
        'I would check the layout and available space before recommending a change.',
        read.B1,
      ],
      [
        'limit',
        'state-limit',
        'How settled is your view at this point?',
        '允许暂留或待信息改变。',
        'settled',
        'I am fairly settled for now, though I do not expect everyone to share my view.',
        'open',
        'My view is still open because I do not know enough about the venue.',
        read.B1,
      ],
      [
        'close',
        'close-discussion',
        'How would you bring this discussion to an honest end?',
        '学习目标是表达，不假定请求的解释已给出。',
        'differ',
        'We may still prefer different things, and that is fine. Thanks for talking.',
        'reflect',
        'You have given me something to think about. I will leave the question open for now.',
        read.B1,
      ],
      [
        'meaning',
        'clarify-meaning',
        'What do you understand by lively in the point I made at the start?',
        '有明确已说原话作为依据。',
        'active',
        'I understand it as active and sociable, rather than simply noisy.',
        'clarify',
        'I am not sure whether you mean busy or loud; could you make that distinction clearer?',
        read.B1,
      ],
      [
        'tone',
        'manage-tone',
        'Would it help if I summarised my reasoning or worked through an example?',
        '选择解释方式，不推定听不懂。',
        'summary',
        'A summary would help me follow the main reason without too much detail.',
        'example',
        'An example would help me see how your idea might work in practice.',
        read.B1,
      ],
    ],
    read.B1,
  ),
  B2: socialPack(
    scene,
    'B2',
    {
      canDoZh: '有依据地解释立场，比较方案代价并澄清对方关键词。',
      complexityZh: '处理个人经验的证据局限、不同优先事项及暂时性结论。',
      scaffoldingZh: '双策略支撑权衡和条件表达，但不把同意写成路径目标。',
      registerZh: '有分寸的朋友讨论，不用辩论赛式压制。',
    },
    [
      [
        'position',
        'state-position',
        'Would you build quiet periods into the programme, or keep the event lively throughout?',
        '清楚立场并承认并非唯一选择。',
        'quiet',
        'I would build in quiet periods so visitors did not have to leave simply to get a break.',
        'lively',
        'I would keep the programme lively, while recognising that this would not be everyone’s preferred event.',
        read.B2,
      ],
      [
        'reason',
        'give-reason',
        'What underlying need shapes your judgement about sound at these events?',
        '展开最重视的需要。',
        'conversation',
        'I put weight on being able to talk without strain, because conversation is a main reason I attend.',
        'energy',
        'I value a shared sense of energy, because an event can offer something different from an ordinary afternoon.',
        read.B2,
      ],
      [
        'example',
        'give-example',
        'What does a specific experience suggest, without proving what everyone would prefer?',
        '个人经历只支持有限观察。',
        'quiet',
        'A quiet corner helped me at a busy fair, though I cannot assume that experience represents every visitor.',
        'music',
        'Music made a neighbourhood gathering welcoming for me, but others may have experienced the same sound differently.',
        read.B2,
      ],
      [
        'priority',
        'name-priority',
        'Which would you protect if variety and ease of running the event came into conflict?',
        '说明权衡标准。',
        'variety',
        'I would protect variety where possible, even if that meant reducing the size of individual activities.',
        'simple',
        'I would protect a manageable programme, since offering choices badly may help less than doing a few things well.',
        read.B2,
      ],
      [
        'other',
        'acknowledge-other',
        'What can you recognise in the opposing preference without adopting it yourself?',
        '理解不要求立场转换。',
        'value',
        'I can recognise that it meets a genuine need, even if it is not the need I would put first.',
        'ask',
        'I can recognise the preference, but I need a more concrete example before I understand the reasoning behind it.',
        read.B2,
      ],
      [
        'proposal',
        'offer-proposal',
        'What limited trial could give the organisers something useful to learn from?',
        '试验仅为建议，未实施。',
        'area',
        'They could try a small quiet area and invite feedback without treating it as a permanent solution.',
        'times',
        'They could trial a timetable with clearly separated sound levels and see where visitors actually spend time.',
        read.B2,
      ],
      [
        'tradeoff',
        'identify-tradeoff',
        'Which cost of a more varied programme would you want made explicit?',
        '说明场地或志愿者投入的取舍。',
        'space',
        'I would want to know which activities would lose space if another area were introduced.',
        'volunteers',
        'I would want the extra volunteer workload made clear rather than assume variety came without a cost.',
        read.B2,
      ],
      [
        'evidence',
        'request-evidence',
        'What evidence would you seek before recommending a change beyond this conversation?',
        '未来查询，不谎称已调查。',
        'users',
        'I would seek views from a range of visitors, especially people whose preferences are less visible.',
        'venue',
        'I would examine the venue layout and sound separation before assuming that the plan could work.',
        read.B2,
      ],
      [
        'limit',
        'state-limit',
        'How would you qualify your conclusion given what we still do not know?',
        '可持稳立场但承认范围。',
        'view',
        'I would keep my preference but avoid presenting it as the best answer for every event.',
        'open',
        'I would hold my conclusion open until we knew more about the people and the space involved.',
        read.B2,
      ],
      [
        'close',
        'close-discussion',
        'How can we finish while being accurate about any remaining difference?',
        '不用虚假共识收尾。',
        'difference',
        'Our priorities may still differ, and I am comfortable leaving that difference in place. Thanks for the discussion.',
        'open',
        'I have not reached a final view, but the conversation has helped me see the trade-offs more clearly.',
        read.B2,
      ],
      [
        'meaning',
        'clarify-meaning',
        'Is my use of lively clear enough to discuss, or does it need narrowing down?',
        '澄清已说词语而非凭空假定听觉错误。',
        'clear',
        'I take you to mean socially active, not necessarily loud, and that is clear enough for me.',
        'narrow',
        'It needs narrowing down; a busy event and a loud event are not always the same thing.',
        read.B2,
      ],
      [
        'tone',
        'manage-tone',
        'Would you rather hear the main principle behind my view or test it against a concrete example?',
        '选择讨论方式。',
        'principle',
        'The main principle would help me understand what you are trying to protect.',
        'example',
        'A concrete example would let me test where our preferences actually diverge.',
        read.B2,
      ],
    ],
    read.B2,
  ),
  C1: socialPack(
    scene,
    'C1',
    {
      canDoZh: '细致界定立场、词义与证据适用范围，在不达共识时仍能顺畅结束。',
      complexityZh:
        '识别优先事项差异，比较有条件的试验与资源代价，不从个人经历推出普遍结论。',
      scaffoldingZh: '以具体社区话题支撑较复杂论述，要求限定、回应和自然收束。',
      registerZh: '思路细致但仍是朋友聊天，避免学术或企业腔。',
    },
    [
      [
        'position',
        'state-position',
        'Where would you place the balance between a lively programme and deliberately quiet periods?',
        '精确表达倾向而非绝对化。',
        'quiet',
        'I would make quiet periods part of the programme, so taking a break did not depend on knowing a hidden corner.',
        'lively',
        'I would keep a lively programme rather than interrupt its flow, while being honest about the kind of event we were offering.',
        read.C1,
      ],
      [
        'reason',
        'give-reason',
        'Which aspect of the experience are you least willing to lose when thinking about sound?',
        '突出核心价值。',
        'conversation',
        'The chance to have an unforced conversation matters most to me; noise can make that tiring long before it becomes intolerable.',
        'energy',
        'I would be reluctant to lose the sense of a shared occasion that music and activity can create.',
        read.C1,
      ],
      [
        'example',
        'give-example',
        'How far can a personal example take us before we start reading too much into it?',
        '说明经历和推论边界。',
        'quiet',
        'A quiet space let me stay longer at one fair, which illustrates a need without showing how common that need is.',
        'music',
        'Music helped me feel part of a gathering, but that tells us about my experience rather than everyone else’s comfort.',
        read.C1,
      ],
      [
        'priority',
        'name-priority',
        'If the organisers could not maximise both choice and simplicity, what would you protect first?',
        '现实约束下作优先排序。',
        'choice',
        'I would protect meaningful choice, even if that meant a smaller event with fewer activities in each area.',
        'simple',
        'I would protect a programme the volunteers could run reliably; nominal choices are not much use if the event becomes unmanageable.',
        read.C1,
      ],
      [
        'other',
        'acknowledge-other',
        'What is the strongest point in a preference unlike your own, without overstating your agreement?',
        '可承认价值或保留理解。',
        'recognise',
        'Its strongest point is that it protects a real part of the experience that my own preference might squeeze out.',
        'clarify',
        'I can see what it values, but I would need a more concrete account before saying I fully understand its strongest case.',
        read.C1,
      ],
      [
        'proposal',
        'offer-proposal',
        'What small experiment might clarify the issue without pretending to settle it for every event?',
        '探索性建议不构成实施。',
        'zone',
        'A clearly signposted quiet area could show whether people use it, provided feedback also came from those who still felt excluded.',
        'schedule',
        'A trial with distinct quieter and livelier periods could reveal practical tensions that a general discussion leaves hidden.',
        read.C1,
      ],
      [
        'tradeoff',
        'identify-tradeoff',
        'Which consequence would you want kept visible when a more varied programme sounds like an easy compromise?',
        '识别表面折中的隐藏代价。',
        'space',
        'I would keep the space trade-off visible: adding an area may shrink or displace something people already value.',
        'workload',
        'I would keep the volunteer workload visible, rather than let a generous-sounding plan depend on effort nobody has agreed to provide.',
        read.C1,
      ],
      [
        'evidence',
        'request-evidence',
        'What would you need to investigate before carrying this view into a recommendation?',
        '尚未调查或获授权。',
        'people',
        'I would want to hear from a broader range of visitors, including those who avoid the event and are missing from casual feedback.',
        'practical',
        'I would investigate the layout and how sound travels there, because a plausible idea can fail in a particular space.',
        read.C1,
      ],
      [
        'limit',
        'state-limit',
        'What qualification belongs with your view at this stage?',
        '保留判断或延后结论均有明确范围。',
        'bounded',
        'It remains my preference, not a claim that one arrangement suits every community or every venue.',
        'provisional',
        'I would treat the view as provisional until the practical constraints and less-heard perspectives were clearer.',
        read.C1,
      ],
      [
        'close',
        'close-discussion',
        'How would you close without smoothing over a difference that may still matter?',
        '允许真实分歧存在。',
        'difference',
        'We may be protecting different things, and I am happy to leave that difference honestly on the table. Thanks for talking it through.',
        'reflect',
        'I am not ready to settle on an answer, but I have a clearer sense of what I need to think about. I will leave it there for now.',
        read.C1,
      ],
      [
        'meaning',
        'clarify-meaning',
        'Does lively carry a clear enough meaning in my opening comment, or are we putting different things under the same word?',
        '仅引用情境明确给出的原话。',
        'clear',
        'I understand it as an atmosphere of shared activity rather than a particular volume, so the distinction is clear to me.',
        'unclear',
        'We may be mixing activity with volume; I would like to separate those before drawing conclusions from the word.',
        read.C1,
      ],
      [
        'tone',
        'manage-tone',
        'Would it be more useful to unpack my underlying assumption or examine a case where it might fail?',
        '推进论证深度而非求同。',
        'assumption',
        'Unpacking the assumption would help me see whether our difference is about aims or about how to achieve them.',
        'case',
        'A case where it might fail would be more useful; that would show the limits of the view rather than just its appeal.',
        read.C1,
      ],
    ],
    read.C1,
  ),
}
