import { socialPack, type SocialScene, type Review } from './authoring'
const read = {
  A1: {
    state: 'model-reviewed',
    record: 'social-review.md: first-small-talk.A1',
  },
  A2: {
    state: 'model-reviewed',
    record: 'social-review.md: first-small-talk.A2',
  },
  B1: {
    state: 'model-reviewed',
    record: 'social-review.md: first-small-talk.B1',
  },
  B2: {
    state: 'model-reviewed',
    record: 'social-review.md: first-small-talk.B2',
  },
  C1: {
    state: 'model-reviewed',
    record: 'social-review.md: first-small-talk.C1',
  },
} satisfies Record<string, Review>
const scene: SocialScene = {
  sceneId: 'social-01',
  slug: 'first-small-talk',
  situations: [
    '虚构社区花园开放日。你与邻居 Alex 初次见面，旁边有座椅和植物标签；姓名牌可按回答设为 Lina 或 Samuel。Alex 说：“Hello, I’m Alex. Welcome to the garden.” 只练习自然认识、话题选择和告别；姓名与生活细节可采用参考答案的虚构设定，不要求真实隐私。短练不代表同意交换联系方式。',
    '同一虚构社区花园开放日，音乐区稍吵，Alex 下一个活动快开始了，想先简短认识、说明听说需要并留出离开空间。Alex 已说：“Hello, I’m Alex. Welcome to the garden.” 座椅和植物标签就在旁边，姓名牌可按回答设为 Lina 或 Samuel。可以不解释个人原因、不交换联系方式；没有真实社交安排。',
  ],
  paths: [
    {
      short: ['name', 'topic', 'leave'],
      standard: ['name', 'connection', 'topic', 'interest', 'comfort', 'leave'],
      extended: [
        'name',
        'connection',
        'topic',
        'interest',
        'weekend',
        'local',
        'comfort',
        'privacy',
        'contact',
        'leave',
      ],
    },
    {
      short: ['name', 'pace', 'leave'],
      standard: ['name', 'connection', 'pace', 'detail', 'privacy', 'leave'],
      extended: [
        'name',
        'connection',
        'topic',
        'interest',
        'pace',
        'detail',
        'comfort',
        'privacy',
        'contact',
        'leave',
      ],
    },
  ],
  closing:
    'Thanks for the conversation practice. Your stated preferences stand; no contact details have been exchanged or future meeting arranged.',
  partial:
    'We will stop here. Some conversation choices remain unconfirmed, and no future contact is assumed.',
  repairs: {
    clarify: 'Take your time; you can ask about the current question.',
    struggle: 'A short answer is fine. You can use either example or stop.',
    offTopic: 'We can return to this introduction if you want to continue.',
    unknown:
      'That wording is not in this local practice set, so I have not confirmed a choice.',
    changed: 'Your new answer replaces that earlier choice.',
    refusedClosing:
      'We will end the introduction here. No explanation is needed.',
  },
}
export const firstSmallTalk = {
  A1: socialPack(
    scene,
    'A1',
    {
      canDoZh: '借助双选句介绍称呼，选择熟悉话题并结束初次交谈。',
      complexityZh: '一次确认一个具体生活信息；不要求披露住址。',
      scaffoldingZh: '短问句、已介绍的花园情境和可直接使用的句型。',
      registerZh: '友好日常口语，简单拒绝与告别同样有效。',
    },
    [
      [
        'name',
        'introduce-name',
        'What should I call you?',
        '说希望别人怎样称呼你。',
        'lin',
        'Please call me Lin.',
        'sam',
        'My name is Sam.',
        read.A1,
      ],
      [
        'connection',
        'describe-connection',
        'Do you live near this garden?',
        '可以用虚构居住情况回答，不给地址。',
        'near',
        'Yes, I live nearby.',
        'visit',
        'No, I am visiting a friend.',
        read.A1,
      ],
      [
        'topic',
        'choose-topic',
        'Shall we talk about the garden or music?',
        '选择一个轻松话题。',
        'garden',
        'The garden, please.',
        'music',
        'Let’s talk about music.',
        read.A1,
      ],
      [
        'interest',
        'share-interest',
        'What do you like doing?',
        '说一种爱好。',
        'walk',
        'I like walking.',
        'cook',
        'I like cooking.',
        read.A1,
      ],
      [
        'weekend',
        'describe-routine',
        'What do you usually do on Sundays?',
        '说周日习惯，不是答应一起活动。',
        'rest',
        'I usually rest at home.',
        'market',
        'I usually go to the market.',
        read.A1,
      ],
      [
        'local',
        'share-local-knowledge',
        'Do you know the café by the gate?',
        '说明是否知道那家咖啡馆。',
        'know',
        'Yes, I know that café.',
        'new',
        'No, it is new to me.',
        read.A1,
      ],
      [
        'comfort',
        'express-comfort',
        'Would you like to sit on that bench?',
        '可以接受或拒绝座位。',
        'sit',
        'Yes, I would like to sit.',
        'stand',
        'No, I prefer to stand.',
        read.A1,
      ],
      [
        'privacy',
        'set-privacy',
        'Is talking about work OK, or shall we skip it?',
        '可以直接跳过工作话题。',
        'ok',
        'Work is OK.',
        'skip',
        'Let’s skip work.',
        read.A1,
      ],
      [
        'contact',
        'choose-contact',
        'Would you like to exchange numbers, or leave it here?',
        '没有必须交换号码的义务。',
        'offer',
        'I would like to exchange numbers.',
        'no',
        'Let’s leave it here.',
        read.A1,
      ],
      [
        'leave',
        'close-conversation',
        'How would you like to say goodbye now?',
        '选择符合你安排的告别。',
        'go',
        'Nice to meet you. I must go now.',
        'stay',
        'Nice to meet you. I will look around here.',
        read.A1,
      ],
      [
        'pace',
        'request-pace',
        'Am I speaking too fast?',
        '说明说话速度是否合适。',
        'slow',
        'Yes, please speak slowly.',
        'fine',
        'No, this speed is fine.',
        read.A1,
      ],
      [
        'detail',
        'request-detail',
        'Would you like me to explain the plant labels?',
        '可请求解释或自己阅读。',
        'explain',
        'Yes, please explain them.',
        'read',
        'No, I can read them.',
        read.A1,
      ],
    ],
    read.A1,
  ),
  A2: socialPack(
    scene,
    'A2',
    {
      canDoZh: '在社区活动中维持简短认识交谈，并说明兴趣与简单偏好。',
      complexityZh: '连接来访背景和日常习惯，区分认识与未来联络。',
      scaffoldingZh: '明确二选支架，允许请求放慢和跳过话题。',
      registerZh: '轻松礼貌，不以私事解释换取拒绝权。',
    },
    [
      [
        'name',
        'introduce-name',
        'Do you use your full name or a shorter name?',
        '说明称呼习惯。',
        'full',
        'Please use my full name, Lina.',
        'short',
        'Sam is short for Samuel; please use Sam.',
        read.A2,
      ],
      [
        'connection',
        'describe-connection',
        'What brings you to the garden today?',
        '解释这次来访缘由。',
        'invite',
        'A neighbour invited me to look around.',
        'poster',
        'I saw a poster and wanted to visit.',
        read.A2,
      ],
      [
        'topic',
        'choose-topic',
        'Would you prefer to chat about hobbies or this event?',
        '选择接下来聊什么。',
        'hobbies',
        'Hobbies would be nice.',
        'event',
        'I would rather hear about this event.',
        read.A2,
      ],
      [
        'interest',
        'share-interest',
        'Do you prefer indoor or outdoor activities?',
        '给偏好加一个简单例子。',
        'inside',
        'I prefer indoor activities, like drawing.',
        'outside',
        'I prefer being outdoors, especially walking.',
        read.A2,
      ],
      [
        'weekend',
        'describe-routine',
        'Are your weekends usually busy or quiet?',
        '说明一般周末节奏。',
        'busy',
        'They are usually busy with family visits.',
        'quiet',
        'They are quite quiet; I often read.',
        read.A2,
      ],
      [
        'local',
        'share-local-knowledge',
        'Have you tried the café beside the garden gate?',
        '区分体验过与尚未体验。',
        'tried',
        'Yes, I had tea there last week.',
        'notyet',
        'Not yet, but I have seen it.',
        read.A2,
      ],
      [
        'comfort',
        'express-comfort',
        'Are you comfortable standing, or would a seat help?',
        '表达身体舒适需要。',
        'stand',
        'I am comfortable standing, thanks.',
        'seat',
        'A seat would be nice; my feet are tired.',
        read.A2,
      ],
      [
        'privacy',
        'set-privacy',
        'Would you rather leave family out of our chat?',
        '是否聊家庭完全自愿。',
        'skip',
        'Yes, I would rather talk about something else.',
        'ok',
        'No, I am happy to talk about family.',
        read.A2,
      ],
      [
        'contact',
        'choose-contact',
        'Shall we exchange email addresses, or just say hello when we meet?',
        '选择联络方式或不交换资料。',
        'email',
        'I would like to exchange email addresses.',
        'hello',
        'Let’s just say hello when we meet.',
        read.A2,
      ],
      [
        'leave',
        'close-conversation',
        'What would you say to finish our chat politely?',
        '说明现在结束谈话的方式。',
        'next',
        'It was nice talking to you. I need to get to my next activity.',
        'browse',
        'Thanks for the chat. I am going to look at the plants now.',
        read.A2,
      ],
      [
        'pace',
        'request-pace',
        'Would a slower pace make this chat easier?',
        '可以请求放慢而不道歉。',
        'slower',
        'Yes, a little slower would help me.',
        'normal',
        'No, I can follow you at this pace.',
        read.A2,
      ],
      [
        'detail',
        'request-detail',
        'Would a quick explanation of those plant labels be useful?',
        '区别请求说明与不需要说明。',
        'help',
        'Yes, I do not know those plant names.',
        'alone',
        'No, thanks. I would like to read them myself.',
        read.A2,
      ],
    ],
    read.A2,
  ),
  B1: socialPack(
    scene,
    'B1',
    {
      canDoZh: '把来访经历与兴趣连起来，维持有简短理由的初识交谈。',
      complexityZh: '处理生疏环境、听说难点和适度自我披露，十轮各推进一事。',
      scaffoldingZh: '具体问题和两种策略示例帮助连接句子，保留明确退出。',
      registerZh: '自然邻里口语，解释是选项而非义务。',
    },
    [
      [
        'name',
        'introduce-name',
        'How would you like me to introduce you to other people here?',
        '选择希望使用的称呼。',
        'first',
        'Just use Lina; I prefer my first name.',
        'short',
        'Introduce me as Sam, although my name tag says Samuel.',
        read.B1,
      ],
      [
        'connection',
        'describe-connection',
        'How did you hear about this open day?',
        '交代得知活动的经过。',
        'friend',
        'A friend mentioned it because I am interested in gardening.',
        'walk',
        'I passed the gate yesterday and noticed the sign.',
        read.B1,
      ],
      [
        'topic',
        'choose-topic',
        'What would be a good starting point for our conversation?',
        '提出适合初识的话题。',
        'plants',
        'The plants would be a good start; I am trying to grow herbs.',
        'events',
        'Perhaps local events, since I do not know what happens around here.',
        read.B1,
      ],
      [
        'interest',
        'share-interest',
        'Is there a hobby you have started or returned to recently?',
        '说明新爱好或重新开始的兴趣。',
        'new',
        'I have started sketching, and I am still learning the basics.',
        'return',
        'I have gone back to cycling after a long break.',
        read.B1,
      ],
      [
        'weekend',
        'describe-routine',
        'How do you make time to relax at weekends?',
        '描述自己的休闲安排。',
        'early',
        'I keep Sunday mornings free so I can go for a walk.',
        'flexible',
        'I do not plan much; I rest whenever I have a quiet hour.',
        read.B1,
      ],
      [
        'local',
        'share-local-knowledge',
        'Could you recommend the café by the gate from experience?',
        '不能把见过咖啡馆当成体验。',
        'yes',
        'Yes, I have eaten there twice and enjoyed the soup.',
        'no',
        'I have not been inside, so I cannot recommend it myself.',
        read.B1,
      ],
      [
        'comfort',
        'express-comfort',
        'Would sitting down make it easier for you to carry on chatting?',
        '明确座位偏好，不涉及未来活动同意。',
        'sit',
        'Yes, I would be more comfortable on that bench.',
        'stand',
        'Standing is fine for me; I have been sitting all morning.',
        read.B1,
      ],
      [
        'privacy',
        'set-privacy',
        'Are there any everyday topics you would prefer not to get into?',
        '可以设边界也可以表示暂无。',
        'work',
        'I would rather not get into work today.',
        'none',
        'Nothing in particular; everyday topics are fine.',
        read.B1,
      ],
      [
        'contact',
        'choose-contact',
        'Would keeping in touch appeal to you, or is a chat today enough?',
        '未来联系不是本次聊天的必然结果。',
        'contact',
        'I would enjoy keeping in touch by email.',
        'enough',
        'A chat today is enough for me, but I have enjoyed it.',
        read.B1,
      ],
      [
        'leave',
        'close-conversation',
        'How can you bring this first conversation to a friendly close?',
        '选择离开或转向自己的活动。',
        'leave',
        'I have enjoyed meeting you, but I need to head off now.',
        'look',
        'It has been lovely chatting. I am going to explore the garden on my own.',
        read.B1,
      ],
      [
        'pace',
        'request-pace',
        'Is there anything about my speaking that makes me hard to follow?',
        '只依据已发生的问候说明需求。',
        'speed',
        'You speak quite quickly; a slower pace would help.',
        'clear',
        'I can follow you clearly, so there is no need to change.',
        read.B1,
      ],
      [
        'detail',
        'request-detail',
        'Would you like help with the information on the plant labels?',
        '请求具体解释或选择自行查看。',
        'names',
        'Yes, could you explain which names are the common names?',
        'read',
        'I would rather read them first and ask if I get stuck.',
        read.B1,
      ],
    ],
    read.B1,
  ),
  B2: socialPack(
    scene,
    'B2',
    {
      canDoZh: '在初识时有分寸地展开经历，协商话题、舒适度和联络边界。',
      complexityZh: '区分有限经验与推荐依据，处理兴趣变化和不确定社交意图。',
      scaffoldingZh: '示例支撑理由与限定，但学习者无需同意任何联络提议。',
      registerZh: '亲切克制的日常语气，不用商务套话包装普通闲聊。',
    },
    [
      [
        'name',
        'introduce-name',
        'Is there a name you prefer socially that differs from your name tag?',
        '可纠正称呼，也可沿用标签。',
        'short',
        'The tag says Samuel, but I go by Sam outside work.',
        'same',
        'Lina, as it says on the tag, is what I use everywhere.',
        read.B2,
      ],
      [
        'connection',
        'describe-connection',
        'Was coming here a planned visit or a spur-of-the-moment decision?',
        '解释来访的决定过程。',
        'planned',
        'I planned it after hearing how the volunteers revived the garden.',
        'spontaneous',
        'It was spontaneous; the open gate caught my attention on a walk.',
        read.B2,
      ],
      [
        'topic',
        'choose-topic',
        'Would you rather compare local discoveries or talk about interests beyond the neighbourhood?',
        '选择谈话范围而非默认共享背景。',
        'local',
        'Local discoveries would be useful; I still have a lot to explore.',
        'beyond',
        'I would enjoy talking about interests beyond the neighbourhood for a change.',
        read.B2,
      ],
      [
        'interest',
        'share-interest',
        'Has the way you spend your free time changed much recently?',
        '说明变化或稳定，并简述原因。',
        'changed',
        'Quite a bit; I have replaced competitive sport with walks that fit around my schedule.',
        'steady',
        'Not really; reading has remained my main way of switching off.',
        read.B2,
      ],
      [
        'weekend',
        'describe-routine',
        'How do you balance social plans with having a quiet weekend?',
        '描述权衡，不承诺参加任何活动。',
        'limit',
        'I usually arrange one social activity and leave the rest of the weekend open.',
        'flex',
        'I decide as the weekend approaches rather than filling it in advance.',
        read.B2,
      ],
      [
        'local',
        'share-local-knowledge',
        'How much weight would you put on your own impression of the café by the gate?',
        '明确推荐依据是否充足。',
        'limited',
        'I liked it on one visit, though that is a fairly limited impression.',
        'none',
        'I have only seen it from outside, so I would not judge the service.',
        read.B2,
      ],
      [
        'comfort',
        'express-comfort',
        'Would you be more at ease on the bench, or is standing working for you?',
        '表达当下交谈舒适度。',
        'bench',
        'The bench would suit me better; I would rather take the weight off my feet.',
        'standing',
        'Standing works for me, although please sit if you would be more comfortable.',
        read.B2,
      ],
      [
        'privacy',
        'set-privacy',
        'Would you like to set any limits on what we talk about?',
        '可以保留私人界限而不提供理由。',
        'private',
        'I would prefer to keep my personal circumstances out of the conversation.',
        'open',
        'I am comfortable with general personal topics, and I will say if anything feels too private.',
        read.B2,
      ],
      [
        'contact',
        'choose-contact',
        'Would exchanging contact details feel useful, or would you rather keep this informal?',
        '同意仅为此处表述的联络选择。',
        'email',
        'I would be happy to exchange email addresses for an occasional message.',
        'informal',
        'I would rather keep it to friendly chats if we happen to meet.',
        read.B2,
      ],
      [
        'leave',
        'close-conversation',
        'How would you close warmly without suggesting plans you have not agreed to?',
        '真诚告别不等于承诺再见。',
        'go',
        'I have really enjoyed our conversation. I need to leave now, so take care.',
        'space',
        'Thanks for such a pleasant chat. I am going to have a little time to myself in the garden.',
        read.B2,
      ],
      [
        'pace',
        'request-pace',
        'Would changing my pace or pausing between ideas help you follow me?',
        '可提出具体听说调整。',
        'pause',
        'A pause between ideas would help me take in what you are saying.',
        'fine',
        'Your pace is comfortable for me; I will let you know if I miss anything.',
        read.B2,
      ],
      [
        'detail',
        'request-detail',
        'Would you prefer an overview of the plant labels or time to work them out yourself?',
        '区别口头概览与独立阅读。',
        'overview',
        'An overview would help me understand how the labels are organised.',
        'time',
        'I would appreciate a moment to work them out myself before asking for help.',
        read.B2,
      ],
    ],
    read.B2,
  ),
  C1: socialPack(
    scene,
    'C1',
    {
      canDoZh: '自然管理初次交谈的亲疏程度，精确限定经历、推荐和未来联系。',
      complexityZh: '处理称呼语境、兴趣转变及含蓄社交预期，不把友善当承诺。',
      scaffoldingZh: '给出两种有分寸的策略，需持续组织限定和转接；可明确修复。',
      registerZh: '成熟但轻松的日常口语，避免夸张正式。',
    },
    [
      [
        'name',
        'introduce-name',
        'For our chat, is the name on your tag the one you actually go by?',
        '避免把正式标签当成社交偏好，不默认向别人介绍。',
        'different',
        'Samuel is my full name, but Sam feels more natural in a setting like this.',
        'same',
        'Lina is right; there is no need to shorten it or add a title.',
        read.C1,
      ],
      [
        'connection',
        'describe-connection',
        'What tipped the balance towards visiting the garden today?',
        '说明促成来访的具体因素。',
        'project',
        'I had been curious for a while, and hearing about the volunteer project finally drew me in.',
        'chance',
        'Nothing quite so deliberate; I happened to pass while I had some time to spare.',
        read.C1,
      ],
      [
        'topic',
        'choose-topic',
        'Shall we start with what is happening here, or find some common ground beyond gardening?',
        '可以谈眼前活动或转向更宽泛兴趣。',
        'here',
        'Let’s start here; I would be interested in how the garden became a shared space.',
        'beyond',
        'Perhaps beyond gardening; I enjoy it, but I would not want to pretend I know much about it.',
        read.C1,
      ],
      [
        'interest',
        'share-interest',
        'Is there an interest that has taken on a different place in your life lately?',
        '谈兴趣意义的变化或保持。',
        'changed',
        'Photography used to be about getting a good result; lately I value the excuse to notice things.',
        'same',
        'Music has kept much the same place in my life: something I enjoy without needing to improve at it.',
        read.C1,
      ],
      [
        'weekend',
        'describe-routine',
        'How do you stop an enjoyable weekend from becoming another list of obligations?',
        '讨论社交与休息的取舍。',
        'space',
        'I leave part of it deliberately unplanned, even when the invitations sound appealing.',
        'select',
        'I choose a few things I genuinely want to do rather than agreeing out of habit.',
        read.C1,
      ],
      [
        'local',
        'share-local-knowledge',
        'Would you trust your impression of the gate-side café enough to recommend it?',
        '推荐须忠实于实际体验范围。',
        'cautious',
        'I would recommend it for a quiet cup of tea, which is all I have actually tried there.',
        'withhold',
        'I have not been in, so I would rather leave recommendations to someone with firsthand experience.',
        read.C1,
      ],
      [
        'comfort',
        'express-comfort',
        'Would moving to the bench make this more comfortable, or would you rather stay on your feet?',
        '说明座位需要并保留对方选择。',
        'bench',
        'The bench would be welcome; I can concentrate on the conversation better if I am comfortable.',
        'feet',
        'I would rather stay on my feet for now, but please do not let that stop you sitting down.',
        read.C1,
      ],
      [
        'privacy',
        'set-privacy',
        'Is there anything you would rather keep outside a first conversation like this?',
        '界限本身足够，无须交代隐私。',
        'limit',
        'I tend to keep family circumstances private until I know someone a little better.',
        'flexible',
        'I do not have a fixed list; I am comfortable saying so if we reach something I would rather not discuss.',
        read.C1,
      ],
      [
        'contact',
        'choose-contact',
        'Would you welcome occasional contact, or prefer this to remain a pleasant chance meeting?',
        '友善和持续联系是不同选择。',
        'welcome',
        'I would welcome an occasional email, without either of us feeling obliged to keep a conversation going.',
        'chance',
        'I would prefer to leave it as a pleasant chance meeting; I have still very much enjoyed talking.',
        read.C1,
      ],
      [
        'leave',
        'close-conversation',
        'How would you round this off without making a vague promise to meet again?',
        '自然告别，不制造未商定的计划。',
        'time',
        'I am glad we had the chance to talk. I should get going now; enjoy the rest of your day.',
        'alone',
        'This has been a lovely conversation. I am going to wander on my own for a while, so I will leave you to your afternoon.',
        read.C1,
      ],
      [
        'pace',
        'request-pace',
        'Would a little more space between ideas help, or is the rhythm of the conversation comfortable?',
        '可用具体反馈调整节奏。',
        'space',
        'A little more space would help; I am following the ideas but need a moment to put my reply together.',
        'comfortable',
        'The rhythm feels comfortable. If I lose the thread, I will ask rather than let you carry on guessing.',
        read.C1,
      ],
      [
        'detail',
        'request-detail',
        'Would a quick guide to the labels add something, or would you enjoy figuring them out independently?',
        '自己阅读不等于已读懂。',
        'guide',
        'A quick guide would be useful, especially to the distinction between common and botanical names.',
        'independent',
        'I would enjoy figuring them out first; I will ask about any details that remain unclear.',
        read.C1,
      ],
    ],
    read.C1,
  ),
}
