import { socialPack, type SocialScene, type Review } from './authoring'
const read = {
  A1: {
    state: 'model-reviewed',
    record: 'social-review.md: make-invitation.A1',
  },
  A2: {
    state: 'model-reviewed',
    record: 'social-review.md: make-invitation.A2',
  },
  B1: {
    state: 'model-reviewed',
    record: 'social-review.md: make-invitation.B1',
  },
  B2: {
    state: 'model-reviewed',
    record: 'social-review.md: make-invitation.B2',
  },
  C1: {
    state: 'model-reviewed',
    record: 'social-review.md: make-invitation.C1',
  },
} satisfies Record<string, Review>
const scene: SocialScene = {
  sceneId: 'social-03',
  slug: 'make-invitation',
  situations: [
    '虚构情境：你与朋友 Lee 商量怎样邀请不在场的 Jo 参加周六的小聚，尚未发出邀请，也没有人答应。可提议下午散步或傍晚在你家玩桌游，两项都不需买票。问题中的时间、地点和配套细节均为拟议内容；不必真实举办。讨论被拒绝时应尊重对方，不索要私人理由。',
    '同样是在和 Lee 拟写给 Jo 的邀请，但你们知道 Jo 最近安排较多，重点是清楚、低压力地邀请。散步与在你家桌游只是备选，未发出邀请或得到同意；还需考虑无回复、照片许可和人数边界。短练只练三个邀请要素，不代表活动已确定。',
  ],
  paths: [
    {
      short: ['activity', 'invite', 'response'],
      standard: ['activity', 'invite', 'time', 'details', 'access', 'response'],
      extended: [
        'activity',
        'invite',
        'time',
        'details',
        'access',
        'cost',
        'company',
        'response',
        'alternative',
        'send',
      ],
    },
    {
      short: ['activity', 'invite', 'response'],
      standard: ['activity', 'invite', 'response', 'silence', 'photos', 'send'],
      extended: [
        'activity',
        'invite',
        'time',
        'details',
        'response',
        'alternative',
        'silence',
        'photos',
        'company',
        'send',
      ],
    },
  ],
  closing:
    'The invitation wording practice is complete. Nothing has been sent or accepted, and any refusal or silence still leaves Jo free not to join.',
  partial:
    'We will leave the invitation draft here. Some details are still unconfirmed; no invitation has been sent and nobody has agreed to attend.',
  repairs: {
    clarify: 'We can clarify this part of the proposed invitation.',
    struggle:
      'Keep the invitation simple; either example can help you express one point.',
    offTopic:
      'We can return to the invitation draft without assuming that anyone has accepted.',
    unknown:
      'That wording is outside this local set, so the invitation detail remains unconfirmed.',
    changed: 'Your revised wording replaces the earlier invitation choice.',
    refusedClosing: 'We will stop drafting here. No invitation has been sent.',
  },
}
export const makeInvitation = {
  A1: socialPack(
    scene,
    'A1',
    {
      canDoZh: '向朋友说明拟议活动，用简单邀请句并尊重拒绝。',
      complexityZh: '分开确认活动、信息需求及回应方式；没有对方已接受的前提。',
      scaffoldingZh: '明确两个免票活动、短句和逐项问题。',
      registerZh: '轻松友好，邀请不带命令或催促。',
    },
    [
      [
        'activity',
        'propose-activity',
        'What shall we suggest doing with Jo on Saturday?',
        '活动只是提议。',
        'walk',
        'Let’s suggest a walk.',
        'games',
        'Let’s suggest board games at my home.',
        read.A1,
      ],
      [
        'invite',
        'word-invitation',
        'How would you invite Jo?',
        '用邀请而非命令。',
        'question',
        'Would you like to join us on Saturday?',
        'welcome',
        'You are welcome to join us on Saturday.',
        read.A1,
      ],
      [
        'time',
        'set-time-detail',
        'Should we give Jo a time or ask what time works?',
        '时间还待商量。',
        'give',
        'Let’s give Jo a proposed time.',
        'ask',
        'Let’s ask what time works for Jo.',
        read.A1,
      ],
      [
        'details',
        'offer-details',
        'How can Jo get the meeting details?',
        '细节可写在消息里或另问。',
        'message',
        'We can put them in the message.',
        'ask',
        'Jo can ask us for the details.',
        read.A1,
      ],
      [
        'access',
        'check-needs',
        'Shall we ask if Jo needs anything to join comfortably?',
        '自愿说明需要，不要求隐私。',
        'ask',
        'Yes, let’s ask.',
        'open',
        'Let’s say Jo can tell us any needs.',
        read.A1,
      ],
      [
        'cost',
        'explain-cost',
        'Shall we mention tickets in the first message?',
        '已知无需买票；选择主动说明或暂不提。',
        'mention',
        'Yes, let’s say no ticket is needed.',
        'omit',
        'No, let’s leave tickets out of the first message.',
        read.A1,
      ],
      [
        'company',
        'set-company',
        'Can Jo bring a friend to this proposed get-together?',
        '说明拟议人数边界。',
        'yes',
        'Yes, Jo can bring one friend.',
        'no',
        'No, let’s keep it to our small group.',
        read.A1,
      ],
      [
        'response',
        'respect-response',
        'What will you say if Jo says no?',
        '拒绝后不追问理由。',
        'thanks',
        'Thanks for letting me know.',
        'fine',
        'That’s fine. No problem.',
        read.A1,
      ],
      [
        'alternative',
        'handle-alternative',
        'After a no, should we mention another day?',
        '不把拒绝理解为要求另约。',
        'leave',
        'No, let’s leave it there.',
        'open',
        'Only if Jo asks about another day.',
        read.A1,
      ],
      [
        'send',
        'choose-next-step',
        'Is the draft ready to send, or do you want more time?',
        '表达准备状态，不是已发送。',
        'ready',
        'I think the draft is ready to send.',
        'wait',
        'I want more time to read it.',
        read.A1,
      ],
      [
        'silence',
        'handle-silence',
        'What if Jo does not reply?',
        '沉默不是同意。',
        'wait',
        'Let’s wait and not count Jo in.',
        'stop',
        'Let’s leave it and not count Jo in.',
        read.A1,
      ],
      [
        'photos',
        'set-photo-boundary',
        'Should we ask before taking a photo of Jo?',
        '照片需要独立许可。',
        'ask',
        'Yes, we should ask first.',
        'none',
        'Let’s not take photos of Jo.',
        read.A1,
      ],
    ],
    read.A1,
  ),
  A2: socialPack(
    scene,
    'A2',
    {
      canDoZh: '拟写包含基本细节的邀请，说明可选参加和后续处理。',
      complexityZh: '分开拟议时间、人数、回复和照片边界，不因友好而默认同意。',
      scaffoldingZh: '可预测朋友间商量，简单连接词和条件句。',
      registerZh: '日常朋友语气，不附加必须解释的要求。',
    },
    [
      [
        'activity',
        'propose-activity',
        'Which Saturday activity would you like to suggest to Jo?',
        '选择一项可行提议。',
        'walk',
        'I would like to suggest an afternoon walk.',
        'games',
        'I would like to suggest board games at my place in the evening.',
        read.A2,
      ],
      [
        'invite',
        'word-invitation',
        'Would you open with a direct question or a friendly offer?',
        '两种邀请策略都允许不参加。',
        'question',
        'Would you like to join us for a small get-together on Saturday?',
        'offer',
        'We would be happy to have you with us on Saturday if you feel like it.',
        read.A2,
      ],
      [
        'time',
        'set-time-detail',
        'How should we deal with the starting time in the invitation?',
        '给拟议时间或先询问。',
        'suggest',
        'We can suggest a starting time and ask if it suits Jo.',
        'ask',
        'We can ask what time Jo is free before choosing one.',
        read.A2,
      ],
      [
        'details',
        'offer-details',
        'Should the first message include directions or offer them later?',
        '说明信息提供方式。',
        'include',
        'Let’s include the meeting details and directions in the first message.',
        'later',
        'Let’s offer the directions if Jo wants more information.',
        read.A2,
      ],
      [
        'access',
        'check-needs',
        'How could we make it easy for Jo to mention any needs?',
        '不要求说明个人原因。',
        'question',
        'We can ask if anything would make joining easier.',
        'offer',
        'We can say Jo is welcome to tell us about any needs.',
        read.A2,
      ],
      [
        'cost',
        'explain-cost',
        'Would you include the no-ticket detail now or answer if Jo asks?',
        '区分主动说明和按需解释。',
        'mention',
        'I would say in the first message that no ticket is needed.',
        'onrequest',
        'I would leave it out for now and explain if Jo asks.',
        read.A2,
      ],
      [
        'company',
        'set-company',
        'How would you answer if Jo wanted to bring someone?',
        '拟议人数限制仍可明确。',
        'one',
        'Jo is welcome to bring one friend.',
        'small',
        'We would rather keep it to the people we plan to invite this time.',
        read.A2,
      ],
      [
        'response',
        'respect-response',
        'How could you reply kindly if Jo cannot come?',
        '不加再次劝说或理由要求。',
        'thanks',
        'Thanks for telling us. I hope you have a good weekend.',
        'understand',
        'That is completely fine; thanks for replying.',
        read.A2,
      ],
      [
        'alternative',
        'handle-alternative',
        'Would you offer another date after a refusal?',
        '另约必须由对方意愿支持。',
        'no',
        'No, I would leave the invitation there.',
        'jo',
        'I would only discuss another date if Jo said they wanted to.',
        read.A2,
      ],
      [
        'send',
        'choose-next-step',
        'Would you send this draft next, or review it first?',
        '下一步尚未执行。',
        'ready',
        'I would send it next because the main points are clear.',
        'review',
        'I would review it once more before sending anything.',
        read.A2,
      ],
      [
        'silence',
        'handle-silence',
        'How should we plan if there is no reply from Jo?',
        '没有答复不预留为确认出席。',
        'wait',
        'We can wait without treating Jo as confirmed.',
        'plan',
        'We can make our own plans without including Jo as a confirmed guest.',
        read.A2,
      ],
      [
        'photos',
        'set-photo-boundary',
        'What should our plan be for photos involving Jo?',
        '参加与拍照不是同一项许可。',
        'ask',
        'We should ask Jo before taking any photos of them.',
        'avoid',
        'We can avoid taking photos of Jo altogether.',
        read.A2,
      ],
    ],
    read.A2,
  ),
  B1: socialPack(
    scene,
    'B1',
    {
      canDoZh: '围绕朋友邀请说明信息取舍，处理拒绝、无回复和可选替代。',
      complexityZh:
        '从单句邀请推进到带原因的拟稿决定，所有安排保持未执行状态。',
      scaffoldingZh: '具体情境、两种策略与条件句支撑六到十轮协作。',
      registerZh: '亲切清楚，不用内疚感促成接受。',
    },
    [
      [
        'activity',
        'propose-activity',
        'Which plan would you put forward, and what makes it appealing?',
        '为提议给简短理由。',
        'walk',
        'I would suggest an afternoon walk because it is easy to keep it short.',
        'games',
        'I would suggest evening board games at my place because we can sit and talk.',
        read.B1,
      ],
      [
        'invite',
        'word-invitation',
        'How would you word the invitation so it sounds welcoming rather than demanding?',
        '可邀请参加或把决定留给对方。',
        'join',
        'Would you like to join us on Saturday? It would be lovely to see you.',
        'option',
        'We are thinking of a small get-together on Saturday; you are welcome if it appeals to you.',
        read.B1,
      ],
      [
        'time',
        'set-time-detail',
        'Would you suggest a time now or find out Jo’s availability first?',
        '未确认时间不能写成共同决定。',
        'proposal',
        'I would suggest a provisional time so Jo has something concrete to consider.',
        'availability',
        'I would ask about Jo’s availability before proposing a time.',
        read.B1,
      ],
      [
        'details',
        'offer-details',
        'How much practical information belongs in the first invitation?',
        '在完整性和简短之间选择。',
        'full',
        'I would include the meeting point and directions so Jo does not need to ask.',
        'brief',
        'I would keep the first message brief and offer practical details on request.',
        read.B1,
      ],
      [
        'access',
        'check-needs',
        'How could Jo raise a practical need without having to explain private circumstances?',
        '只询问所需调整，不探原因。',
        'ask',
        'We could ask what would make joining comfortable, without asking why.',
        'open',
        'We could leave an open invitation to tell us about any practical needs.',
        read.B1,
      ],
      [
        'cost',
        'explain-cost',
        'Would you explain the ticket situation in the invitation or keep it for a follow-up question?',
        '选择说明时机，不把无需票扩大为全部免费。',
        'mention',
        'I would include a short line saying that no ticket needs to be bought.',
        'onrequest',
        'I would keep that detail for a question from Jo rather than put it in the first message.',
        read.B1,
      ],
      [
        'company',
        'set-company',
        'What boundary would you set if Jo asked to bring a friend?',
        '提供人数许可或清晰限制。',
        'one',
        'One friend would be welcome, but I would like to keep the group small.',
        'invited',
        'I would explain that we plan to keep this get-together to the people on our invitation list.',
        read.B1,
      ],
      [
        'response',
        'respect-response',
        'What would a respectful reply to Jo’s refusal sound like?',
        '承认拒绝，不把其变成谈判。',
        'accept',
        'Thanks for letting us know; there is no need to explain.',
        'warm',
        'No problem at all. I appreciate you getting back to us, and I hope your weekend goes well.',
        read.B1,
      ],
      [
        'alternative',
        'handle-alternative',
        'What would need to happen before you suggested an alternative date?',
        '替代日期需要对方主动表达兴趣。',
        'initiative',
        'I would wait for Jo to bring up another date.',
        'none',
        'I would not suggest an alternative after this invitation; I would leave it there.',
        read.B1,
      ],
      [
        'send',
        'choose-next-step',
        'What is your next step with the invitation draft?',
        '拟稿不等于已发消息。',
        'ready',
        'I am ready to send the draft after this conversation.',
        'reread',
        'I want to read the draft again before deciding whether to send it.',
        read.B1,
      ],
      [
        'silence',
        'handle-silence',
        'How would you avoid treating no reply as an acceptance?',
        '说清规划上不计为确认。',
        'wait',
        'I would wait for an explicit answer and not count Jo as attending.',
        'own',
        'I would continue with our own plans and leave Jo off the confirmed guest list.',
        read.B1,
      ],
      [
        'photos',
        'set-photo-boundary',
        'How would you separate joining the activity from agreeing to photos?',
        '出席不包含照片许可。',
        'ask',
        'I would ask separately before photographing Jo, even if they joined us.',
        'none',
        'I would plan not to photograph Jo, so joining would not involve a photo request.',
        read.B1,
      ],
    ],
    read.B1,
  ),
  B2: socialPack(
    scene,
    'B2',
    {
      canDoZh: '协商清楚且低压力的邀请，解释信息安排并维护拒绝及隐私边界。',
      complexityZh: '区分拟议细节与已确认答案，处理沉默、替代和额外许可。',
      scaffoldingZh: '原始情境固定，答案需给出权衡和条件限定。',
      registerZh: '朋友间自然礼貌，不把拒绝写成需要解决的问题。',
    },
    [
      [
        'activity',
        'propose-activity',
        'Which option would you lead with, given that this is meant to be a low-key invitation?',
        '给出与低压力目标一致的理由。',
        'walk',
        'I would lead with the afternoon walk, since people can leave when they need to.',
        'games',
        'I would lead with board games at my place, since sitting together leaves room for conversation.',
        read.B2,
      ],
      [
        'invite',
        'word-invitation',
        'How would you show genuine interest in seeing Jo while leaving the decision open?',
        '热情不等于强迫。',
        'question',
        'Would you be interested in joining us on Saturday? We would enjoy your company, but there is no pressure.',
        'offer',
        'We have a small get-together in mind for Saturday, and you would be very welcome if it suits you.',
        read.B2,
      ],
      [
        'time',
        'set-time-detail',
        'Would a provisional time or an availability question make the invitation easier to consider?',
        '选择降低不确定性的方式。',
        'provisional',
        'A provisional time would make it concrete, as long as we made clear that it was a suggestion.',
        'ask',
        'An availability question would be better; I would rather not imply that the timing was settled.',
        read.B2,
      ],
      [
        'details',
        'offer-details',
        'Would you prioritise a complete first message or a lighter invitation with details available?',
        '两种信息策略各有用途。',
        'complete',
        'I would include the practical details so Jo could decide without an extra exchange.',
        'light',
        'I would keep it light and offer details, especially as we do not yet know whether Jo is interested.',
        read.B2,
      ],
      [
        'access',
        'check-needs',
        'How could you invite requests for adjustments without putting Jo on the spot?',
        '可以只说需要，不解释私人原因。',
        'question',
        'I would ask whether any practical adjustment would help and make clear that no personal explanation was needed.',
        'open',
        'I would say practical requests were welcome, leaving Jo to decide whether to raise anything.',
        read.B2,
      ],
      [
        'cost',
        'explain-cost',
        'Is the no-ticket detail worth including up front, or would you leave it for a question from Jo?',
        '比较主动透明与消息简短，不捏造费用。',
        'mention',
        'I would include it up front so Jo knew there was no ticket to buy, without promising to cover other expenses.',
        'onrequest',
        'I would leave ticket information out of the first message and explain the arrangement if Jo asked.',
        read.B2,
      ],
      [
        'company',
        'set-company',
        'How would you respond to a request for an extra guest while protecting the scale of the gathering?',
        '清楚人数边界。',
        'one',
        'One extra guest would be fine, but I would explain that we could not expand beyond that.',
        'limit',
        'I would keep to the invited group and explain that we wanted a small gathering this time.',
        read.B2,
      ],
      [
        'response',
        'respect-response',
        'How would you acknowledge a refusal without turning it into a request for justification?',
        '不要求原因，不继续施压。',
        'brief',
        'Thanks for letting me know. That is absolutely fine, and there is no need to give a reason.',
        'warm',
        'I appreciate the reply. I will leave it there and wish you a good weekend.',
        read.B2,
      ],
      [
        'alternative',
        'handle-alternative',
        'Would you leave a declined invitation alone or discuss alternatives under a particular condition?',
        '只有明确另约兴趣才谈替代。',
        'leave',
        'I would leave it alone; declining this invitation does not ask me to find another date.',
        'condition',
        'I would discuss alternatives only if Jo explicitly said they wanted to meet another time.',
        read.B2,
      ],
      [
        'send',
        'choose-next-step',
        'Are you ready to use this draft, or does it need another look?',
        '只确认准备和下一步。',
        'ready',
        'I am ready to use it as the invitation, though it has not been sent yet.',
        'look',
        'I would like another look, particularly to check that the wording leaves room for a no.',
        read.B2,
      ],
      [
        'silence',
        'handle-silence',
        'How would silence affect your planning without becoming a reason to chase Jo?',
        '沉默不授权参加或催问。',
        'wait',
        'I would keep Jo unconfirmed and wait without sending repeated reminders.',
        'proceed',
        'I would make plans that do not depend on Jo attending and leave the message alone.',
        read.B2,
      ],
      [
        'photos',
        'set-photo-boundary',
        'What approach to photographs would avoid bundling consent into attendance?',
        '把照片许可与参加分开。',
        'ask',
        'I would ask separately before taking photos of Jo and accept a no without discussion.',
        'none',
        'I would avoid photographing Jo, so attendance would not bring an extra consent decision.',
        read.B2,
      ],
    ],
    read.B2,
  ),
  C1: socialPack(
    scene,
    'C1',
    {
      canDoZh: '用自然有分寸的语言形成邀请，处理隐含义务、未定信息和多重同意。',
      complexityZh:
        '论证信息与自由选择的权衡，避免从拒绝或沉默推导动机、替代需求。',
      scaffoldingZh:
        '问题仅给决策焦点，答案综合条件、理由和语气；保留短练的明确边界。',
      registerZh: '朋友协作中的成熟口语，不采用公文腔。',
    },
    [
      [
        'activity',
        'propose-activity',
        'Which plan would feel easiest to say yes or no to, rather than hardest to turn down?',
        '邀请应易于选择而非难以拒绝。',
        'walk',
        'The afternoon walk would be easy to consider because it need not take up the whole day.',
        'games',
        'Board games at my place would be clear enough to picture, without suggesting a big occasion Jo ought to attend.',
        read.C1,
      ],
      [
        'invite',
        'word-invitation',
        'How would you convey warmth without making Jo responsible for your feelings about the answer?',
        '热情但不借失望施压。',
        'direct',
        'Would you fancy joining us on Saturday? It would be lovely to see you, and equally fine if it is not for you.',
        'open',
        'We are thinking of getting together on Saturday; you would be very welcome, with no expectation that you rearrange anything.',
        read.C1,
      ],
      [
        'time',
        'set-time-detail',
        'Would pinning down a provisional time help, or would it close the conversation too soon?',
        '时间可以明确建议，也可以先问。',
        'propose',
        'A provisional time would help Jo judge the invitation, provided we labelled it as a suggestion rather than a decision.',
        'ask',
        'I would start by asking about availability; there is little point refining a time before knowing whether Jo wants to consider it.',
        read.C1,
      ],
      [
        'details',
        'offer-details',
        'Where would you draw the line between a useful invitation and too much advance detail?',
        '完整与简短之间作实际取舍。',
        'complete',
        'I would include the details needed to make a decision, so Jo would not have to signal interest just to obtain them.',
        'brief',
        'I would give a brief outline and make the details available, rather than bury the invitation in arrangements that are still only proposals.',
        read.C1,
      ],
      [
        'access',
        'check-needs',
        'How would you make practical adjustments discussable without inviting personal disclosure?',
        '询问需要与索取隐私不同。',
        'direct',
        'I would ask what might make participation easier, keeping the focus on adjustments rather than the reasons behind them.',
        'open',
        'I would simply make it clear that practical requests were welcome and leave Jo in control of whether to raise any.',
        read.C1,
      ],
      [
        'cost',
        'explain-cost',
        'Would spelling out the no-ticket arrangement help Jo decide, or is it a detail you would hold back unless asked?',
        '选择信息提供时机，两种选项均不承诺全包。',
        'mention',
        'I would spell it out briefly, since knowing there is no ticket to buy removes one possible uncertainty.',
        'onrequest',
        'I would hold that detail back unless Jo asked, keeping the first message focused on the activity and leaving space for questions.',
        read.C1,
      ],
      [
        'company',
        'set-company',
        'How would you handle an extra-guest request without making the size limit sound personal?',
        '边界针对活动规模而非个人。',
        'one',
        'I could welcome one extra guest while making clear that this was the limit for a small get-together.',
        'fixed',
        'I would explain that we were keeping to the invited group this time, without passing judgement on the person Jo wanted to bring.',
        read.C1,
      ],
      [
        'response',
        'respect-response',
        'What reply would let a refusal stand without reading a hidden message into it?',
        '不猜测拒绝背后的原因。',
        'simple',
        'Thanks for letting me know. I will leave it there; no explanation is needed.',
        'warm',
        'Of course, and thank you for replying. I hope you have a good weekend, whatever your plans are.',
        read.C1,
      ],
      [
        'alternative',
        'handle-alternative',
        'What would justify opening a discussion of alternatives after Jo declined?',
        '替代不是拒绝后的自动步骤。',
        'explicit',
        'Only an explicit wish from Jo to find another time; I would not infer that from a polite refusal.',
        'none',
        'I would not open that discussion from this invitation at all; Jo can raise it if they want to.',
        read.C1,
      ],
      [
        'send',
        'choose-next-step',
        'Does the draft now reflect what you want to offer, or would you hold it back?',
        '区别对草稿满意和实际发送。',
        'ready',
        'It reflects what I want to offer, so I would be ready to send it after we finish talking.',
        'hold',
        'I would hold it back for another read, especially to remove anything that might make declining feel awkward.',
        read.C1,
      ],
      [
        'silence',
        'handle-silence',
        'How would you leave a non-response genuinely open without quietly counting it as agreement?',
        '沉默保持未确认，不追加压力。',
        'wait',
        'I would keep Jo off the confirmed list and allow the message to sit without repeated follow-ups.',
        'independent',
        'I would make arrangements that stand on their own without Jo, rather than let an unanswered message become an obligation.',
        read.C1,
      ],
      [
        'photos',
        'set-photo-boundary',
        'How would you avoid treating an invitation accepted in one sense as permission in another?',
        '参加和照片各需独立决定。',
        'separate',
        'I would ask separately before photographing Jo; agreeing to spend time together would not answer that question.',
        'avoid',
        'I would keep Jo out of photographs altogether, rather than make participation carry an unspoken expectation about pictures.',
        read.C1,
      ],
    ],
    read.C1,
  ),
}
