import { socialPack, type SocialScene, type Review } from './authoring'
const read = {
  A1: {
    state: 'model-reviewed',
    record: 'social-review.md: networking-event.A1',
  },
  A2: {
    state: 'model-reviewed',
    record: 'social-review.md: networking-event.A2',
  },
  B1: {
    state: 'model-reviewed',
    record: 'social-review.md: networking-event.B1',
  },
  B2: {
    state: 'model-reviewed',
    record: 'social-review.md: networking-event.B2',
  },
  C1: {
    state: 'model-reviewed',
    record: 'social-review.md: networking-event.C1',
  },
} satisfies Record<string, Review>
const scene: SocialScene = {
  sceneId: 'social-02',
  slug: 'networking-event',
  situations: [
    '虚构社区创意交流会。对方 Morgan 是本地艺术活动志愿者，不是招聘人；你戴着自选虚构姓名的名牌。现场有作品和制作过程展示、印刷活动单和公开群组链接，十分钟后的分享介绍如何加入及组织群组。你们只是在认识和交换信息，任何建议都不是工作机会或资源保证；可以不留联系方式。',
    '同一虚构社区创意交流会，你戴着自选虚构姓名的名牌，Morgan 还要帮忙布置十分钟后关于加入及组织群组的分享。适合先说明交流目标与时间界限，再决定是否接受介绍或公开资料。作品和制作过程展示、活动单和公开群组链接均可讨论，尚未发生转介、发送或加入群组。',
  ],
  paths: [
    {
      short: ['purpose', 'area', 'exit'],
      standard: ['purpose', 'area', 'project', 'resource', 'contact', 'exit'],
      extended: [
        'purpose',
        'area',
        'project',
        'experience',
        'interest',
        'resource',
        'offer',
        'contact',
        'permission',
        'exit',
      ],
    },
    {
      short: ['purpose', 'time', 'exit'],
      standard: [
        'purpose',
        'area',
        'time',
        'introduction',
        'permission',
        'exit',
      ],
      extended: [
        'purpose',
        'area',
        'project',
        'time',
        'interest',
        'introduction',
        'offer',
        'contact',
        'permission',
        'exit',
      ],
    },
  ],
  closing:
    'That completes this networking practice. Offers and contact preferences are only what you stated; no introduction, message or opportunity has been arranged.',
  partial:
    'We will pause the practice here. Unanswered preferences stay open, and no contact or introduction is assumed.',
  repairs: {
    clarify: 'We can clarify the current networking question.',
    struggle: 'A simple description of what you want is enough.',
    offTopic: 'We can return to getting to know each other at this event.',
    unknown:
      'This local set does not recognise that response, so no preference has been confirmed.',
    changed: 'That earlier preference has been replaced by your new answer.',
    refusedClosing:
      'We will stop here without exchanging any further information.',
  },
}
export const networkingEvent = {
  A1: socialPack(
    scene,
    'A1',
    {
      canDoZh: '说出来参加交流会的目的、兴趣领域和联络偏好。',
      complexityZh: '熟悉活动中逐一交换具体信息，不承诺转介或工作。',
      scaffoldingZh: '简单词汇和直接双选回答，明确告别句。',
      registerZh: '友好社交，不套用正式求职语气。',
    },
    [
      [
        'purpose',
        'state-purpose',
        'Why are you here today?',
        '说参加交流会的简单目的。',
        'people',
        'I want to meet people.',
        'ideas',
        'I want some new ideas.',
        read.A1,
      ],
      [
        'area',
        'describe-area',
        'What kind of creative work interests you?',
        '说感兴趣的领域。',
        'photos',
        'I like photography.',
        'craft',
        'I like making things by hand.',
        read.A1,
      ],
      [
        'project',
        'describe-project',
        'Do you have a project at the moment?',
        '有项目与没有项目都合适。',
        'poster',
        'Yes, I am making a poster.',
        'none',
        'No, I do not have a project now.',
        read.A1,
      ],
      [
        'experience',
        'describe-experience',
        'Is this your first event like this?',
        '说明参与经验。',
        'first',
        'Yes, this is my first one.',
        'again',
        'No, I came last month.',
        read.A1,
      ],
      [
        'interest',
        'choose-interest',
        'Would you like to look at the displays or hear a talk?',
        '选择当前活动兴趣。',
        'displays',
        'I would like to see the displays.',
        'talk',
        'I would like to hear a talk.',
        read.A1,
      ],
      [
        'resource',
        'request-resource',
        'Would you like an event leaflet?',
        '可以不要活动单。',
        'yes',
        'Yes, a leaflet would help.',
        'no',
        'No, thank you. I do not need one.',
        read.A1,
      ],
      [
        'offer',
        'offer-contribution',
        'Can you offer help at a future event?',
        '只是意愿，不是已报名。',
        'help',
        'I can offer help with signs.',
        'no',
        'I cannot offer help now.',
        read.A1,
      ],
      [
        'contact',
        'choose-contact',
        'Would you like to keep in touch?',
        '自由选择是否保持联系。',
        'yes',
        'Yes, by email, please.',
        'no',
        'No, I would rather not.',
        read.A1,
      ],
      [
        'permission',
        'set-sharing-permission',
        'May I share your name with the event organiser?',
        '联系偏好不自动允许转发姓名。',
        'yes',
        'Yes, you may share my name.',
        'no',
        'No, please do not share my name.',
        read.A1,
      ],
      [
        'exit',
        'close-networking',
        'How would you finish this meeting?',
        '给出告别，不承诺后续。',
        'talk',
        'Thanks for talking. I will go to the talk now.',
        'browse',
        'Nice to meet you. I will look around now.',
        read.A1,
      ],
      [
        'time',
        'set-time',
        'Do you have five minutes to chat?',
        '可直接限制时间。',
        'five',
        'Yes, I have five minutes.',
        'two',
        'I only have two minutes.',
        read.A1,
      ],
      [
        'introduction',
        'choose-introduction',
        'Would you like to meet another volunteer?',
        '可以拒绝介绍。',
        'yes',
        'Yes, I would like an introduction.',
        'no',
        'No, I prefer to look around alone.',
        read.A1,
      ],
    ],
    read.A1,
  ),
  A2: socialPack(
    scene,
    'A2',
    {
      canDoZh: '简述项目与活动经验，提出资料请求并管理后续联络。',
      complexityZh: '在可预测社交活动中连接目的和简单理由，区分许可类型。',
      scaffoldingZh: '场景已给资源和角色，问题明确、答案提供原因支架。',
      registerZh: '礼貌但非推销式闲谈，可不给理由地拒绝。',
    },
    [
      [
        'purpose',
        'state-purpose',
        'What are you hoping to get from this event?',
        '说明今天希望得到什么。',
        'learn',
        'I hope to learn about local creative groups.',
        'meet',
        'I hope to meet people with similar interests.',
        read.A2,
      ],
      [
        'area',
        'describe-area',
        'Which creative activity do you spend most time on?',
        '用具体活动说明领域。',
        'drawing',
        'I spend most of my free time drawing.',
        'sewing',
        'I usually make simple bags and other things with fabric.',
        read.A2,
      ],
      [
        'project',
        'describe-project',
        'Are you working on anything you can tell me about?',
        '没有项目也可以回答。',
        'cards',
        'I am designing some birthday cards for friends.',
        'none',
        'I am not working on anything at the moment.',
        read.A2,
      ],
      [
        'experience',
        'describe-experience',
        'Have you been to this kind of gathering before?',
        '描述有或没有经验。',
        'new',
        'No, so I am still learning how it works.',
        'before',
        'Yes, I went to a similar gathering last spring.',
        read.A2,
      ],
      [
        'interest',
        'choose-interest',
        'Which part of the programme sounds most useful to you?',
        '区分展示与讲座用途。',
        'display',
        'The displays sound useful because I can see people’s work.',
        'talk',
        'The next talk sounds useful because it explains how to join a group.',
        read.A2,
      ],
      [
        'resource',
        'request-resource',
        'Would you prefer the printed leaflet or the public group link?',
        '只表达选择，还未领取或加入。',
        'paper',
        'I would prefer the leaflet so I can read it later.',
        'link',
        'The public link would be useful; I can look at it at home.',
        read.A2,
      ],
      [
        'offer',
        'offer-contribution',
        'Is there a small way you could help at a later event?',
        '有能力不等于活动已安排。',
        'signs',
        'I could help make signs if the organiser needs them.',
        'none',
        'I cannot offer help at the moment, but thank you for asking.',
        read.A2,
      ],
      [
        'contact',
        'choose-contact',
        'Would an occasional email be welcome?',
        '不需要为了礼貌接受联系。',
        'yes',
        'Yes, I would be happy to get an occasional email.',
        'no',
        'No, I prefer to keep this to a chat today.',
        read.A2,
      ],
      [
        'permission',
        'set-sharing-permission',
        'Are you happy for me to mention your name to the organiser?',
        '单独确认转述姓名的许可。',
        'yes',
        'Yes, you can mention my name to the organiser.',
        'no',
        'Please keep my name between us for now.',
        read.A2,
      ],
      [
        'exit',
        'close-networking',
        'What could you say when it is time to move on?',
        '选择自己接下来的行动。',
        'talk',
        'It was good to meet you. I am going to the next talk.',
        'break',
        'Thanks for the conversation. I am going to take a short break.',
        read.A2,
      ],
      [
        'time',
        'set-time',
        'How long can you stay in this conversation?',
        '明确自己可用时间。',
        'few',
        'I can stay for a few more minutes.',
        'brief',
        'I need to keep it brief because I have another activity.',
        read.A2,
      ],
      [
        'introduction',
        'choose-introduction',
        'Would you welcome an introduction to someone who helps run the displays?',
        '可以接受或不要介绍。',
        'yes',
        'Yes, I would like to hear about the displays.',
        'no',
        'No, thanks. I would prefer to explore them myself.',
        read.A2,
      ],
    ],
    read.A2,
  ),
  B1: socialPack(
    scene,
    'B1',
    {
      canDoZh: '说明交流目标、项目状态和贡献范围，带简短理由接受或拒绝后续。',
      complexityZh: '非例行初识中区分探索兴趣、具体承诺及资料分享许可。',
      scaffoldingZh: '两种完整响应帮助组织事实与理由，可中止或改选。',
      registerZh: '社区同行式交流，不把对话包装成面试。',
    },
    [
      [
        'purpose',
        'state-purpose',
        'What would make today’s event worthwhile for you?',
        '具体说明成功目标。',
        'group',
        'Finding a group where beginners are welcome would make it worthwhile.',
        'ideas',
        'I would be pleased to leave with a few ideas to try on my own.',
        read.B1,
      ],
      [
        'area',
        'describe-area',
        'How would you describe your creative interests to someone outside your field?',
        '用容易理解的语言说明兴趣。',
        'repair',
        'I enjoy repairing old clothes and turning them into useful things.',
        'photo',
        'I take photographs of ordinary streets to show details people often miss.',
        read.B1,
      ],
      [
        'project',
        'describe-project',
        'Is there something current you would like to share, or are you between projects?',
        '允许没有当前项目。',
        'current',
        'I am planning a small photo collection about the local market.',
        'between',
        'I am between projects and using today to explore what I might try next.',
        read.B1,
      ],
      [
        'experience',
        'describe-experience',
        'What experience of creative meetups are you bringing with you?',
        '不需要夸大资历。',
        'online',
        'I have joined online meetups, but this is my first local one.',
        'local',
        'I have been to a few local meetups and found informal chats most helpful.',
        read.B1,
      ],
      [
        'interest',
        'choose-interest',
        'Would you rather see practical examples or hear how a group organises its activities?',
        '选择具体信息类型。',
        'examples',
        'Practical examples would help because I learn by seeing how things are made.',
        'organise',
        'I would rather hear about organisation, since starting a small group interests me.',
        read.B1,
      ],
      [
        'resource',
        'request-resource',
        'Which resource would be easier for you to use after the event?',
        '选择活动单或公开链接。',
        'leaflet',
        'The leaflet would be easier because I can add notes while I read.',
        'link',
        'The public link would suit me better because I can check for updates.',
        read.B1,
      ],
      [
        'offer',
        'offer-contribution',
        'Could you offer a skill without committing to a regular role?',
        '限定帮助范围，也可以不提供。',
        'limited',
        'I could design a one-off sign, but I cannot take on a regular role.',
        'none',
        'I am not able to offer a skill at present; I am here mainly to learn.',
        read.B1,
      ],
      [
        'contact',
        'choose-contact',
        'Would you like a way to continue the conversation after today?',
        '后续交流需要明确自愿。',
        'email',
        'An email exchange would be welcome, especially about local workshops.',
        'no',
        'I would rather leave the conversation here, although I have found it useful.',
        read.B1,
      ],
      [
        'permission',
        'set-sharing-permission',
        'What can I pass on to the organiser about meeting you?',
        '转述范围是独立许可。',
        'name',
        'You can pass on my name, but not any contact details.',
        'nothing',
        'Please do not pass on any information about me for now.',
        read.B1,
      ],
      [
        'exit',
        'close-networking',
        'How would you end our chat while leaving the next step genuinely open?',
        '告别不等于承诺联络。',
        'talk',
        'Thanks for sharing your experience. I am going to catch the talk now.',
        'pause',
        'I have enjoyed meeting you. I need a break, so I will leave it there for today.',
        read.B1,
      ],
      [
        'time',
        'set-time',
        'How much time would you like to give this chat before moving on?',
        '为双方时间设界限。',
        'five',
        'About five minutes would be comfortable before I join the next activity.',
        'two',
        'I only have a couple of minutes, so let’s keep to the main points.',
        read.B1,
      ],
      [
        'introduction',
        'choose-introduction',
        'Would meeting the display volunteer help, or would you prefer to make your own way around?',
        '拒绝介绍不影响交流成功。',
        'meet',
        'Meeting the volunteer would help me understand how the displays were selected.',
        'alone',
        'I would prefer to make my own way around and approach people myself.',
        read.B1,
      ],
    ],
    read.B1,
  ),
  B2: socialPack(
    scene,
    'B2',
    {
      canDoZh: '在陌生社交活动中清楚呈现兴趣、权衡贡献与时间，限定信息转述。',
      complexityZh: '区分探索、经验和可兑现承诺，协商交流深度而非寻求录用。',
      scaffoldingZh: '问题引出说明和限定，示例提供两种有效边界策略。',
      registerZh: '自然同行交流，表达能力但不自夸或强迫联络。',
    },
    [
      [
        'purpose',
        'state-purpose',
        'Are you here to explore possibilities or to find help with something specific?',
        '区分探索与具体求助。',
        'explore',
        'I am exploring possibilities rather than looking for a particular collaborator yet.',
        'help',
        'I would like advice on making a small exhibition accessible to more people.',
        read.B2,
      ],
      [
        'area',
        'describe-area',
        'What connects the different creative things you are interested in?',
        '给领域一个清楚但不抽象的介绍。',
        'reuse',
        'Reusing materials is the common thread, whether I am sewing or making objects.',
        'stories',
        'I am drawn to everyday stories, which is why both photography and writing appeal to me.',
        read.B2,
      ],
      [
        'project',
        'describe-project',
        'How concrete is your current project, if you have one?',
        '区分明确计划与暂无项目。',
        'early',
        'It is at an early stage: I have a theme for a photo series but no exhibition date.',
        'none',
        'I do not have a current project; I am taking time to explore what I might want to make next.',
        read.B2,
      ],
      [
        'experience',
        'describe-experience',
        'What have earlier gatherings taught you, or is this new territory?',
        '有经历才陈述所得。',
        'learned',
        'Earlier gatherings taught me to ask concrete questions instead of trying to meet everyone.',
        'new',
        'This is new territory; I am curious to see which conversations develop naturally.',
        read.B2,
      ],
      [
        'interest',
        'choose-interest',
        'Would practical demonstrations or the discussion of group organisation be more relevant?',
        '按实际需求选内容。',
        'practical',
        'Practical demonstrations would be more relevant because I want to improve how I explain a process.',
        'group',
        'The discussion of group organisation would help me weigh up whether I could sustain a local meetup.',
        read.B2,
      ],
      [
        'resource',
        'request-resource',
        'Would you use a brief printed overview or an online resource that may be updated?',
        '比较稳定概览和后续更新。',
        'print',
        'A printed overview would be enough for me; I do not need ongoing updates.',
        'online',
        'I would use the public online resource because changes to the programme matter to me.',
        read.B2,
      ],
      [
        'offer',
        'offer-contribution',
        'What, if anything, could you offer without taking on more than you can manage?',
        '不让礼貌变成过度承诺。',
        'oneoff',
        'I could help with a single poster, provided we agreed a manageable deadline.',
        'none',
        'I cannot offer help responsibly at the moment, so I would rather not make a vague promise.',
        read.B2,
      ],
      [
        'contact',
        'choose-contact',
        'Would staying in contact have a clear purpose for you?',
        '有目的才接受，也可结束于今天。',
        'yes',
        'Yes, I would welcome occasional emails about accessible community exhibitions.',
        'no',
        'Not at present; I am happy for this to remain a useful conversation at the event.',
        read.B2,
      ],
      [
        'permission',
        'set-sharing-permission',
        'How would you like me to handle any mention of you to the organiser?',
        '许可转述和接受联络分别确认。',
        'name',
        'You can mention that we met and give my name, but please leave my contact details out.',
        'private',
        'I would prefer you not to mention me; I can introduce myself if I decide to.',
        read.B2,
      ],
      [
        'exit',
        'close-networking',
        'How would you close without turning a friendly chat into an obligation?',
        '礼貌结束但不模糊承诺。',
        'move',
        'I appreciate the conversation. I am going to move on to the next part of the event now.',
        'break',
        'This has given me plenty to think about. I will take a break and leave it there for today.',
        read.B2,
      ],
      [
        'time',
        'set-time',
        'Would a quick exchange suit you better than a longer conversation right now?',
        '说明当下交流长度。',
        'brief',
        'A quick exchange would suit me; I want to leave you time to prepare for the talk.',
        'longer',
        'I have time for a little more detail, as long as it fits around your preparation.',
        read.B2,
      ],
      [
        'introduction',
        'choose-introduction',
        'Would an introduction to the display volunteer be useful, or would that interrupt your plans?',
        '考虑转介价值而非默认需要。',
        'useful',
        'It would be useful if the volunteer has time; I would not want to pull them away from something.',
        'skip',
        'I would rather skip the introduction and spend some time looking at the work first.',
        read.B2,
      ],
    ],
    read.B2,
  ),
  C1: socialPack(
    scene,
    'C1',
    {
      canDoZh:
        '在非正式交流中精确呈现方向、经验与能力范围，处理转介含义和未来联络。',
      complexityZh: '澄清尚未成形的目标、资源取舍与承诺边界，保持不确定性。',
      scaffoldingZh: '问题提供情境焦点，答案需自然组织限定、理由和礼貌收束。',
      registerZh: '成熟而平实，不将社区创意会写成企业战略会议。',
    },
    [
      [
        'purpose',
        'state-purpose',
        'What would you like to take away from today, without putting too much pressure on the event?',
        '明确期望而不过度索取结果。',
        'perspective',
        'A fresh perspective would be enough; I am not expecting to find a ready-made partnership.',
        'specific',
        'I would value one useful conversation about making small exhibitions more welcoming.',
        read.C1,
      ],
      [
        'area',
        'describe-area',
        'How do you explain what draws you to creative work without relying on specialist labels?',
        '用具体动机代替行业标签。',
        'materials',
        'I like giving overlooked materials a second life, whether that ends up as clothing or a simple object.',
        'stories',
        'I am interested in the stories a place tells through ordinary details, and I use images and words to explore them.',
        read.C1,
      ],
      [
        'project',
        'describe-project',
        'Is there a project taking shape, or are you deliberately leaving things open?',
        '有雏形不等于确定计划。',
        'shape',
        'A photo series is taking shape, though I am still working out whose perspective it should foreground.',
        'open',
        'I am deliberately leaving things open; I would rather notice a worthwhile question than rush into a project.',
        read.C1,
      ],
      [
        'experience',
        'describe-experience',
        'Has experience changed how you approach events like this, or are you finding your feet?',
        '区分经验反思和新手探索。',
        'changed',
        'Experience has made me less concerned with collecting contacts and more interested in a few substantial conversations.',
        'new',
        'I am still finding my feet, so I am listening for where my interests might fit rather than presenting myself as an expert.',
        read.C1,
      ],
      [
        'interest',
        'choose-interest',
        'Would seeing how people make things or hearing how they keep a group going be more revealing?',
        '选择希望深入理解的一面。',
        'making',
        'Seeing the making process would be more revealing; finished work can hide the decisions and compromises behind it.',
        'group',
        'I would learn more from how a group keeps going, especially when enthusiasm meets limited time.',
        read.C1,
      ],
      [
        'resource',
        'request-resource',
        'Would a self-contained leaflet meet your needs, or would you benefit from following the public updates?',
        '资源用途不等于订阅同意。',
        'leaflet',
        'A self-contained leaflet would meet my needs; I can decide what is relevant without following every update.',
        'updates',
        'The public updates would be useful, particularly if workshop details are still being settled.',
        read.C1,
      ],
      [
        'offer',
        'offer-contribution',
        'Is there a contribution you could realistically offer, with its limits made clear?',
        '可以谨慎限定或不承诺。',
        'bounded',
        'I could help shape a one-off poster, but I would need to agree the scope before committing.',
        'none',
        'Not realistically at the moment; I would rather be clear about that than leave you counting on an uncertain offer.',
        read.C1,
      ],
      [
        'contact',
        'choose-contact',
        'Would you see a reason to stay in touch, or has the conversation served its purpose here?',
        '不把有用交谈当成持续关系。',
        'purpose',
        'I would welcome occasional contact about community exhibitions, while keeping expectations of a reply flexible.',
        'complete',
        'It has served its purpose here for me, and I would be happy to leave it as a good conversation.',
        read.C1,
      ],
      [
        'permission',
        'set-sharing-permission',
        'If you come up in my conversation with the organiser, what are you comfortable with me passing on?',
        '这是前瞻许可，不是假称转述已发生。',
        'name',
        'You may mention my name and that we met; anything beyond that should come from me.',
        'none',
        'I would prefer not to be brought into that conversation at all; I can approach the organiser in my own time.',
        read.C1,
      ],
      [
        'exit',
        'close-networking',
        'How would you end on a warm note without implying an agreement to work together?',
        '友好收束，不虚构合作。',
        'session',
        'I have enjoyed hearing your perspective. I will let you get on and head to the next session.',
        'reflect',
        'Thank you for such a thoughtful exchange. I am going to take a little time to reflect on what I have heard.',
        read.C1,
      ],
      [
        'time',
        'set-time',
        'Would you rather keep this focused now, or make room for a little more detail?',
        '以当下时间和对方安排为准。',
        'focused',
        'Let’s keep it focused; I would rather have a useful brief exchange than make you late for the setup.',
        'detail',
        'I can make room for more detail, provided you are not being held up by the conversation.',
        read.C1,
      ],
      [
        'introduction',
        'choose-introduction',
        'Would a personal introduction add anything for you, or would you rather approach the displays on your own terms?',
        '介绍应当自愿且不保证发生。',
        'intro',
        'An introduction could help, as long as the volunteer is free and knows I am only exploring.',
        'own',
        'I would rather approach them on my own terms; I do not need an introduction to feel comfortable looking around.',
        read.C1,
      ],
    ],
    read.C1,
  ),
}
