import { socialPack, type SocialScene, type Review } from './authoring'
const read = {
  A1: {
    state: 'model-reviewed',
    record: 'social-review.md: fix1 polite-refusal.A1 complete-unit reread 2026-09-10',
  },
  A2: {
    state: 'model-reviewed',
    record: 'social-review.md: fix1 polite-refusal.A2 complete-unit reread 2026-09-10',
  },
  B1: {
    state: 'model-reviewed',
    record: 'social-review.md: polite-refusal.B1',
  },
  B2: {
    state: 'model-reviewed',
    record: 'social-review.md: polite-refusal.B2',
  },
  C1: {
    state: 'model-reviewed',
    record: 'social-review.md: fix1 polite-refusal.C1 complete-unit reread 2026-09-10',
  },
} satisfies Record<string, Review>
const scene: SocialScene = {
  sceneId: 'social-04',
  slug: 'polite-refusal',
  situations: [
    '虚构拒绝表达练习：朋友 Casey 邀你周六参加家中晚餐，你决定不参加。对话中的另一位朋友 Dana 帮你拟回复，不扮演纠缠邀请者。你可以选用虚构理由，也可以完全不说原因。后续问题是审阅边界和消息内容，不是再次劝你参加；尚未发送回复或约定替代计划。',
    '同一虚构晚餐拒绝，Dana 帮你写一段适合群消息的回复。重点是避免“也许”被误认成同意、保护私人理由和控制后续联系。Casey 未被设定为已接受你的拒绝；只练如何表达，不要求你证明拒绝合理，也不需要真实隐私。',
  ],
  paths: [
    {
      short: ['decline', 'reason', 'close'],
      standard: [
        'decline',
        'thanks',
        'reason',
        'alternative',
        'contact',
        'close',
      ],
      extended: [
        'decline',
        'thanks',
        'reason',
        'clarity',
        'alternative',
        'contact',
        'boundary',
        'channel',
        'check',
        'close',
      ],
    },
    {
      short: ['decline', 'clarity', 'close'],
      standard: ['decline', 'reason', 'privacy', 'silence', 'check', 'close'],
      extended: [
        'decline',
        'thanks',
        'reason',
        'clarity',
        'privacy',
        'alternative',
        'silence',
        'boundary',
        'check',
        'close',
      ],
    },
  ],
  closing:
    'The refusal practice is complete. A no needs no private explanation, and no alternative plan or future contact has been agreed with Casey.',
  partial:
    'We will stop this draft here. Some wording choices remain open; your decision not to attend is not an agreement to an alternative.',
  repairs: {
    clarify:
      'We can clarify the wording question; your refusal is not being challenged.',
    struggle: 'A short no is enough. You do not need to give a private reason.',
    offTopic:
      'We can return to writing the refusal, if you still want to practise.',
    unknown:
      'I have not matched that wording locally, so no draft choice is confirmed.',
    changed:
      'The revised wording replaces the earlier choice in this practice.',
    refusedClosing:
      'We will stop practising. You do not owe an explanation for stopping.',
  },
}
export const politeRefusal = {
  A1: socialPack(
    scene,
    'A1',
    {
      canDoZh: '用简单句明确不参加，选择是否给理由，并结束拒绝消息。',
      complexityZh: '已决定拒绝，只处理表达选择，不要求反复证明理由。',
      scaffoldingZh: '由朋友协助拟稿，短问句和直接可用的句子。',
      registerZh: '友好而明确；不说原因也是完整回答。',
    },
    [
      [
        'decline',
        'state-refusal',
        'How will you say no to Saturday dinner?',
        '明确不参加，不用含糊的也许。',
        'cannot',
        'I cannot come to dinner on Saturday.',
        'decline',
        'Thank you, but I will not join you on Saturday.',
        read.A1,
      ],
      [
        'thanks',
        'express-appreciation',
        'What would you like to thank Casey for?',
        '感谢邀请或想到你，不等于答应。',
        'invite',
        'Thank you for inviting me.',
        'think',
        'Thank you for thinking of me.',
        read.A1,
      ],
      [
        'reason',
        'choose-disclosure',
        'Do you want to give a reason or keep it private?',
        '原因完全自愿。',
        'busy',
        'I have other plans.',
        'private',
        "I'd rather not say.",
        read.A1,
      ],
      [
        'clarity',
        'clarify-example-date',
        "A different example says, 'I cannot come this weekend.' Can you name one day?",
        '单独例句：把 this weekend 换成具体星期，不修改你先前对周六的明确拒绝。',
        'saturday',
        'I cannot come on Saturday.',
        'sunday',
        'I cannot come on Sunday.',
        read.A1,
      ],
      [
        'alternative',
        'choose-alternative',
        'Would you like to suggest another plan?',
        '提出替代只是提议，可以不提。',
        'none',
        'No, I do not want to suggest another plan.',
        'tea',
        'I would like to suggest tea another day.',
        read.A1,
      ],
      [
        'contact',
        'set-contact',
        'May Casey contact you about future dinners?',
        '本次拒绝不自动答应未来联系。',
        'yes',
        'Yes, future invitations are welcome.',
        'no',
        'No, please do not send me more dinner invitations.',
        read.A1,
      ],
      [
        'boundary',
        'state-boundary',
        'If someone keeps asking, what could you say?',
        '假设有人追问，不要求实际已发生。',
        'firm',
        'My answer is still no.',
        'stop',
        'Please stop asking me.',
        read.A1,
      ],
      [
        'channel',
        'choose-channel',
        'Would you send your reply privately or in the group?',
        '选择拟发送渠道。',
        'private',
        'I would send a private message.',
        'group',
        'I would reply in the group.',
        read.A1,
      ],
      [
        'check',
        'review-draft',
        'Do you want to read the draft yourself or hear it aloud?',
        '审阅尚未发送的回复。',
        'read',
        'I want to read it myself.',
        'hear',
        'Please read it aloud to me.',
        read.A1,
      ],
      [
        'close',
        'close-refusal',
        'How would you end the dinner reply?',
        '可祝福或请对方按不出席安排，不假定理解已发生。',
        'enjoy',
        'Enjoy your dinner.',
        'plan',
        'Please make your dinner plans without me.',
        read.A1,
      ],
      [
        'privacy',
        'protect-reason',
        'Should a group reply include personal details?',
        '可不写私事或另外决定。',
        'none',
        'No, leave personal details out.',
        'separate',
        'I will decide about personal details in a private message.',
        read.A1,
      ],
      [
        'silence',
        'avoid-reassurance-demand',
        'After sending a clear no, would you need another reply?',
        '前瞻发送之后，不假设已发出。',
        'no',
        'No, I would not need another reply.',
        'receipt',
        'I would only need to know the message arrived.',
        read.A1,
      ],
    ],
    read.A1,
  ),
  A2: socialPack(
    scene,
    'A2',
    {
      canDoZh: '礼貌拒绝熟悉邀请，选择简单理由、消息渠道和未来邀请边界。',
      complexityZh: '把当前拒绝、替代提议和后续联系作为分开的选择。',
      scaffoldingZh: '朋友拟稿情境提供明确支架，条件问法不虚构已发生追问。',
      registerZh: '清楚温和，不用过度道歉换取接受。',
    },
    [
      [
        'decline',
        'state-refusal',
        'What clear reply could you give about the dinner invitation?',
        '直接拒绝本次周六晚餐。',
        'cannot',
        'Thank you for the invitation, but I cannot make it on Saturday.',
        'notjoin',
        'I appreciate the invitation, but I will not be joining the dinner.',
        read.A2,
      ],
      [
        'thanks',
        'express-appreciation',
        'Would you thank Casey for the invitation or for including you?',
        '具体感谢不改变拒绝。',
        'invite',
        'Thank you for inviting me to your dinner.',
        'include',
        'It was kind of you to include me in your plans.',
        read.A2,
      ],
      [
        'reason',
        'choose-disclosure',
        'Would a short reason feel comfortable, or would you prefer none?',
        '给一个虚构理由或不披露。',
        'plans',
        'I already have plans for Saturday.',
        'none',
        'I would prefer not to give a reason.',
        read.A2,
      ],
      [
        'clarity',
        'clarify-example-date',
        "Here is a separate example: 'I cannot come next week.' How could you make the day clear?",
        '另一个例句需要明确日期；用 next Tuesday 或 next Thursday，不改变当前晚餐拒绝。',
        'tuesday',
        'I cannot come next Tuesday.',
        'thursday',
        'I cannot come next Thursday.',
        read.A2,
      ],
      [
        'alternative',
        'choose-alternative',
        'Do you want to leave it there or suggest something different?',
        '没有义务补偿另约。',
        'leave',
        'I would like to leave it there without another plan.',
        'coffee',
        'I would like to suggest a short coffee another week.',
        read.A2,
      ],
      [
        'contact',
        'set-contact',
        'Would you welcome more dinner invitations in the future?',
        '允许未来邀请与本次出席分开。',
        'welcome',
        'Yes, Casey is welcome to invite me another time.',
        'pause',
        'No, I would rather not get more dinner invitations for now.',
        read.A2,
      ],
      [
        'boundary',
        'state-boundary',
        'If the invitation were repeated, how could you keep your answer clear?',
        '不把 hypothetical 追问写成真实历史。',
        'same',
        'Thank you, but my answer has not changed.',
        'stop',
        'I have said no, and I would like to leave it there.',
        read.A2,
      ],
      [
        'channel',
        'choose-channel',
        'Which reply channel would you choose for this refusal?',
        '根据偏好选择，不要求解释隐私。',
        'private',
        'I would choose a private message to Casey.',
        'group',
        'I would send a brief reply to the group.',
        read.A2,
      ],
      [
        'check',
        'review-draft',
        'Would you rather check the reply silently or hear how it sounds?',
        '稿件尚未发送。',
        'silent',
        'I would rather read it silently first.',
        'aloud',
        'I would like to hear it aloud before using it.',
        read.A2,
      ],
      [
        'close',
        'close-refusal',
        'What friendly ending could you use without offering another meeting?',
        '收尾不要暗示替代已确定。',
        'enjoy',
        'I hope you all have a lovely dinner.',
        'plan',
        'Please go ahead with your dinner plans without me.',
        read.A2,
      ],
      [
        'privacy',
        'protect-reason',
        'How would you handle personal information in a group reply?',
        '已选给原因也不代表可公开。',
        'omit',
        'I would leave personal information out of the group reply.',
        'private',
        'I would keep any personal information for a separate private message, if I chose to share it.',
        read.A2,
      ],
      [
        'silence',
        'avoid-reassurance-demand',
        'Once the refusal is sent, what response would you need from Casey?',
        '前瞻需求，不索求对方安慰。',
        'none',
        'I would not need a response after sending a clear answer.',
        'delivery',
        'I would only want to know it had arrived, not ask Casey to make me feel better.',
        read.A2,
      ],
    ],
    read.A2,
  ),
  B1: socialPack(
    scene,
    'B1',
    {
      canDoZh: '维持清晰拒绝，解释披露和回复策略，区分替代建议与既定安排。',
      complexityZh: '处理群消息、可能追问和回执需求，但不虚构对方施压。',
      scaffoldingZh: '两种策略帮助展开简短理由与条件表达。',
      registerZh: '诚恳但不自责，私人原因可以保留。',
    },
    [
      [
        'decline',
        'state-refusal',
        'How would you make your decision about Saturday clear from the start?',
        '拒绝不应藏在解释中。',
        'direct',
        'Thank you for inviting me, but I will not be able to join the dinner on Saturday.',
        'decision',
        'I have decided not to come to dinner this Saturday, though I appreciate the invitation.',
        read.B1,
      ],
      [
        'thanks',
        'express-appreciation',
        'Which part of the invitation would you acknowledge warmly?',
        '分别感谢邀请行为或被想到。',
        'invite',
        'I would thank Casey for taking the time to invite me.',
        'thought',
        'I would say it was kind of Casey to think of including me.',
        read.B1,
      ],
      [
        'reason',
        'choose-disclosure',
        'Would you include a brief explanation, or does a clear answer feel sufficient?',
        '解释不是拒绝有效性的前提。',
        'rest',
        'I would explain that I need a quiet evening to myself.',
        'enough',
        'A clear answer feels sufficient; I would rather keep my reasons private.',
        read.B1,
      ],
      [
        'clarity',
        'avoid-ambiguity',
        'What would you do with wording that could be mistaken for uncertainty?',
        '用肯定拒绝或删掉暧昧字句。',
        'replace',
        'I would replace it with a clear statement that I am not attending.',
        'delete',
        'I would delete phrases such as perhaps or we will see from the reply.',
        read.B1,
      ],
      [
        'alternative',
        'choose-alternative',
        'Is a different get-together something you genuinely want to propose?',
        '无替代也是完整拒绝。',
        'none',
        'No, I do not want to propose another get-together just to soften the refusal.',
        'walk',
        'Yes, I would like to suggest a short walk another week, without assuming Casey will agree.',
        read.B1,
      ],
      [
        'contact',
        'set-contact',
        'What would you like Casey to understand about future dinner invitations?',
        '独立表达未来邀请偏好。',
        'open',
        'I would still welcome future invitations, even though this one does not work for me.',
        'stop',
        'I would prefer not to receive dinner invitations for a while, and I do not need to explain why.',
        read.B1,
      ],
      [
        'boundary',
        'state-boundary',
        'If someone tried to persuade you after this, how would you respond?',
        '以条件句排练坚定边界。',
        'repeat',
        'I appreciate the thought, but I am not changing my decision.',
        'end',
        'I have given my answer, so I would like us to stop discussing the invitation.',
        read.B1,
      ],
      [
        'channel',
        'choose-channel',
        'Would a private reply or a short group message suit you better?',
        '选择发送方式，不代表已发送。',
        'private',
        'A private reply would suit me because I prefer to handle invitations directly.',
        'group',
        'A short group message would suit me, provided it did not include personal details.',
        read.B1,
      ],
      [
        'check',
        'review-draft',
        'How would you like to check the draft before sending it?',
        '审阅意图而非已完成检查。',
        'self',
        'I would read it myself to check that it says what I mean.',
        'aloud',
        'I would like you to read it aloud so I can judge the tone.',
        read.B1,
      ],
      [
        'close',
        'close-refusal',
        'How can the closing stay friendly without adding a promise?',
        '不为了礼貌虚构下一次见面。',
        'wish',
        'I hope you have a great evening together.',
        'appreciate',
        'Thanks again for thinking of me; please make your plans without me.',
        read.B1,
      ],
      [
        'privacy',
        'protect-reason',
        'How would you keep personal reasons from becoming part of a group discussion?',
        '即使给理由也可选择私下渠道。',
        'exclude',
        'I would leave reasons out of the group message altogether.',
        'separate',
        'If I chose to share a reason, I would send it privately rather than invite a group discussion.',
        read.B1,
      ],
      [
        'silence',
        'avoid-reassurance-demand',
        'What, if anything, would you want after the message had been delivered?',
        '把确认收到与情感安慰分开。',
        'nothing',
        'Nothing further; I would not need Casey to reassure me about saying no.',
        'receipt',
        'A simple acknowledgement would help me know it had been seen, without any discussion of my reasons.',
        read.B1,
      ],
    ],
    read.B1,
  ),
  B2: socialPack(
    scene,
    'B2',
    {
      canDoZh: '平衡感谢与坚定拒绝，维护隐私并防止含糊承诺。',
      complexityZh: '解释拒绝措辞、群消息披露和未来邀请的不同边界。',
      scaffoldingZh: '通过有理由的两种策略支持协商，但不让拒绝依赖合理化。',
      registerZh: '自然清楚，避免防御性长篇解释和道德评判。',
    },
    [
      [
        'decline',
        'state-refusal',
        'How would you decline in a way that leaves little room for negotiation?',
        '态度坚定，不敌对。',
        'unable',
        'Thank you for inviting me, but I will not be able to join you on Saturday.',
        'decision',
        'I appreciate being included, but I have decided to sit this dinner out.',
        read.B2,
      ],
      [
        'thanks',
        'express-appreciation',
        'Would you acknowledge the effort of inviting you or the thought behind it?',
        '感谢对象不同，均不撤回拒绝。',
        'effort',
        'I would thank Casey for making the effort to include me in the invitation.',
        'thought',
        'I would acknowledge how thoughtful it was to remember me.',
        read.B2,
      ],
      [
        'reason',
        'choose-disclosure',
        'How much explanation, if any, would you be comfortable including?',
        '可以简短说明或不说明。',
        'brief',
        'I would mention that I need some time to myself, without going into personal details.',
        'none',
        'I would not include an explanation; a clear and polite refusal is enough.',
        read.B2,
      ],
      [
        'clarity',
        'avoid-ambiguity',
        'How would you deal with a softening phrase that makes the refusal sound undecided?',
        '温和不等于不确定。',
        'replace',
        'I would replace it with a warmer but definite sentence saying I will not attend.',
        'remove',
        'I would remove the softening phrase rather than let politeness create a false expectation.',
        read.B2,
      ],
      [
        'alternative',
        'choose-alternative',
        'Would an alternative be a genuine offer or something you felt obliged to add?',
        '只提出真实想要的替代。',
        'none',
        'It would feel like an obligation, so I would not offer an alternative.',
        'genuine',
        'I genuinely want to suggest coffee another week, while leaving Casey free to decline it.',
        read.B2,
      ],
      [
        'contact',
        'set-contact',
        'What boundary would you set around similar invitations in future?',
        '未来联系与替代计划不互相推导。',
        'welcome',
        'I would welcome future dinner invitations, with the understanding that I may still say no.',
        'pause',
        'I would ask for a pause in dinner invitations and leave it to me to reopen that conversation.',
        read.B2,
      ],
      [
        'boundary',
        'state-boundary',
        'If a clear refusal were met with more persuasion, how would you hold the boundary?',
        '仅为条件排练，没有实际追问史。',
        'decision',
        'I hear that you would like me there, but my decision is not changing.',
        'end',
        'I have answered the invitation, and I do not want to keep discussing whether I should come.',
        read.B2,
      ],
      [
        'channel',
        'choose-channel',
        'Which channel would let you keep the reply proportionate and comfortable?',
        '按实际沟通偏好选择。',
        'direct',
        'A direct message would let me be clear without turning the refusal into a group topic.',
        'group',
        'A brief group reply would be proportionate, as long as I kept personal explanations out of it.',
        read.B2,
      ],
      [
        'check',
        'review-draft',
        'What kind of final check would help you feel ready to use the reply?',
        '检查仍是下一步，不宣称已做。',
        'meaning',
        'I would read it quietly to check that warmth had not blurred the decision.',
        'tone',
        'I would listen to it aloud to check that firmness had not become unnecessarily sharp.',
        read.B2,
      ],
      [
        'close',
        'close-refusal',
        'How would you end without taking responsibility for how Casey feels about the refusal?',
        '可以祝福或感谢，不求安慰。',
        'wish',
        'I hope everyone has a lovely evening together.',
        'thanks',
        'Thank you again for including me; I will leave my answer there.',
        read.B2,
      ],
      [
        'privacy',
        'protect-reason',
        'How would you stop a group reply from inviting discussion of your private circumstances?',
        '理由是否披露与渠道分开。',
        'omit',
        'I would omit the circumstances entirely and keep the group reply to the decision.',
        'private',
        'Any explanation I chose to give would go privately, not into a group conversation where others might pursue it.',
        read.B2,
      ],
      [
        'silence',
        'avoid-reassurance-demand',
        'Once the message had reached Casey, what sort of response would actually be useful?',
        '不要向对方索要情感批准。',
        'none',
        'No response would be necessary; I would not ask Casey to approve my right to decline.',
        'seen',
        'A brief acknowledgement would be useful, but not reassurance or a discussion of whether my reason was good enough.',
        read.B2,
      ],
    ],
    read.B2,
  ),
  C1: socialPack(
    scene,
    'C1',
    {
      canDoZh: '细致区分感激、决定、披露及关系维护，在潜在异议中自然坚守边界。',
      complexityZh:
        '识别缓和语造成的错误期待，处理替代邀约真实性与私人信息受众。',
      scaffoldingZh: '以具体拟稿问题组织限定和解释，保留不解释的直接策略。',
      registerZh: '成熟朋友口语，坚定不等于冷漠或正式训斥。',
    },
    [
      [
        'decline',
        'state-refusal',
        'How would you make the no unmistakable without making the invitation itself sound unwelcome?',
        '区别感谢对方与接受邀请。',
        'clear',
        'Thank you for asking me; I will not be joining the dinner on Saturday, but I appreciate the invitation.',
        'decision',
        'It was thoughtful of you to include me. I have decided not to come this time, and I wanted to give you a clear answer.',
        read.C1,
      ],
      [
        'thanks',
        'express-appreciation',
        'What would you acknowledge so that the appreciation feels specific rather than automatic?',
        '感谢具体邀请行为或被记挂。',
        'effort',
        'I would acknowledge the effort Casey made to include me rather than add a string of apologies.',
        'thought',
        'I would thank Casey for thinking of me; that is what I genuinely appreciate about the invitation.',
        read.C1,
      ],
      [
        'reason',
        'choose-disclosure',
        'Would sharing a little context serve you, or would it invite a discussion you do not want?',
        '理由是自主决定，不是证据要求。',
        'context',
        'A little context would suit me: I need an evening to myself, and I would leave the explanation at that.',
        'private',
        'I would keep the context private; I do not want a personal decision to become something others assess.',
        read.C1,
      ],
      [
        'clarity',
        'avoid-ambiguity',
        'How would you preserve kindness if the draft’s softening language left the door unintentionally open?',
        '删暧昧或另写明确而温和的句子。',
        'rewrite',
        'I would rewrite the sentence warmly but definitively, so kindness did not sound like an invitation to negotiate.',
        'cut',
        'I would cut the uncertain wording and let the genuine thanks carry the warmth instead.',
        read.C1,
      ],
      [
        'alternative',
        'choose-alternative',
        'Would suggesting another meeting reflect what you want, or merely make the no easier to deliver?',
        '替代只能来自真实意愿。',
        'nooffer',
        'It would only make the no easier to deliver, so I would not create an offer I did not mean.',
        'offer',
        'It reflects what I want: I would like to propose coffee another week, while treating that as a new invitation Casey can decline.',
        read.C1,
      ],
      [
        'contact',
        'set-contact',
        'How would you describe your preference about future dinner invitations without rewriting today’s decision?',
        '不因未来开放就撤回现在拒绝。',
        'open',
        'I would be glad to receive future invitations, without that placing any expectation on my answer to them.',
        'pause',
        'I would ask Casey not to send me any more dinner invitations for now; I will bring it up again if that changes.',
        read.C1,
      ],
      [
        'boundary',
        'state-boundary',
        'If someone treated your refusal as the start of a negotiation, what would you say?',
        '条件场景排练坚定表达。',
        'settled',
        'I understand you would like a different answer, but this is a decision I have made, not a problem I am asking you to solve.',
        'end',
        'I have been clear about not coming, and I would like the discussion of my attendance to end here.',
        read.C1,
      ],
      [
        'channel',
        'choose-channel',
        'Would a private reply give you useful control, or would a restrained group answer be enough?',
        '按受众和舒适度选渠道。',
        'private',
        'A private reply would give me the control I want over who sees the conversation.',
        'group',
        'A restrained group answer would be enough; the decision does not need a private exchange if I keep the details out.',
        read.C1,
      ],
      [
        'check',
        'review-draft',
        'How would you check that the draft is both faithful to your decision and fair in tone?',
        '安排检查，不谎称已经审过。',
        'self',
        'I would read it myself, looking especially for any unintended promise or hint that the no was provisional.',
        'aloud',
        'I would have it read aloud so I could hear whether the tone sounded firm rather than irritated.',
        read.C1,
      ],
      [
        'close',
        'close-refusal',
        'What closing would leave the relationship warm without asking Casey to comfort you?',
        '祝福或感谢即可，不索要原谅。',
        'wish',
        'I hope it is a lovely evening for everyone; thank you for thinking of me.',
        'thanks',
        'I appreciate the invitation, and I will leave you with that clear answer so you can make your plans.',
        read.C1,
      ],
      [
        'privacy',
        'protect-reason',
        'How would you keep the choice to disclose a reason separate from the choice of audience?',
        '私下说原因不代表同意公开。',
        'none',
        'I would leave reasons out of the group message, regardless of whether I chose to discuss them elsewhere.',
        'private',
        'If I decided to share context, I would choose a private recipient rather than let a group reply disclose it by default.',
        read.C1,
      ],
      [
        'silence',
        'avoid-reassurance-demand',
        'After delivery, would you need acknowledgement, or could you let the refusal stand without a response?',
        '不把对方回应当成拒绝生效条件。',
        'stand',
        'I could let it stand; I do not need Casey to reassure me that declining was acceptable.',
        'ack',
        'A simple acknowledgement would help with practical certainty, but it would not be permission for my refusal to count.',
        read.C1,
      ],
    ],
    read.C1,
  ),
}
