import { studyPack, type StudyScene, type Review } from './authoring'
const variantRead = {
  A1: {
    state: 'model-reviewed',
    record: 'study-review.md: ask-teacher.A1 variants',
  },
  A2: {
    state: 'model-reviewed',
    record: 'study-review.md: ask-teacher.A2 variants',
  },
  B1: {
    state: 'model-reviewed',
    record: 'study-review.md: ask-teacher.B1 variants',
  },
  B2: {
    state: 'model-reviewed',
    record: 'study-review.md: ask-teacher.B2 variants',
  },
  C1: {
    state: 'model-reviewed',
    record: 'study-review.md: ask-teacher.C1 variants',
  },
} satisfies Record<string, Review>
const scene: StudyScene = {
  sceneId: 'study-02',
  slug: 'ask-teacher',
  situations: [
    '虚构课堂，老师 Lee 与你看一张小练习纸，内容全部在题目中给出。桌上有铅笔、蓝笔和写着 apple / book 的图卡。Lee 已说：“Circle one word, then write a sentence.” 这是真正可请求重说的已给指令；尚未解释答案、批改或答应课后帮助。每道题引入自己的小例子，不要求外部课程知识。',
    '虚构课堂的图卡练习角，老师 Lee 想先确认你需要怎样的示范。桌上有铅笔、蓝笔和 apple / book 图卡。Lee 已说：“Circle one word, then write a sentence.” 可以请求说明，也可以尝试自己做；没有默认你做错了，也没有假设老师已回答你的请求。题内的小例子均为原创练习材料。',
  ],
  paths: [
    {
      short: ['focus', 'example', 'next'],
      standard: [
        'focus',
        'instruction',
        'example',
        'meaning',
        'attempt',
        'next',
      ],
      extended: [
        'focus',
        'instruction',
        'example',
        'meaning',
        'attempt',
        'check',
        'contrast',
        'apply',
        'scope',
        'next',
      ],
    },
    {
      short: ['focus', 'repeat', 'next'],
      standard: ['focus', 'repeat', 'format', 'meaning', 'attempt', 'next'],
      extended: [
        'focus',
        'repeat',
        'format',
        'meaning',
        'attempt',
        'check',
        'contrast',
        'apply',
        'scope',
        'next',
      ],
    },
  ],
  closing:
    'This question practice is complete. Requests for explanation remain requests; no marking or extra help has been promised.',
  partial:
    'We will stop here with some learning choices unconfirmed. You can keep your question for later practice.',
  repairs: {
    clarify: 'You can ask about the current example or instruction.',
    struggle: 'You can use a short question or either example answer.',
    offTopic: 'We can return to the small exercise on this sheet.',
    unknown:
      'I have not matched that wording to a covered answer or confirmed understanding.',
    changed: 'Your new response replaces your earlier choice.',
    refusedClosing: 'We will stop this exercise. Asking for help is optional.',
  },
}
export const askTeacher = {
  A1: studyPack(
    scene,
    'A1',
    {
      canDoZh: '借助具体图卡和短指令向老师说明不懂哪里。',
      complexityZh: '只处理一个单词、动作或书写选择；不要求解释语法规则。',
      scaffoldingZh: '已给英文指令、apple/book 图卡和两条短答案。',
      registerZh: '简单礼貌的提问；求助不被当作失败。',
    },
    [
      [
        'focus',
        'identify-gap',
        'Which part is hard: reading or writing?',
        '说具体困难。',
        'read',
        'Reading is hard for me.',
        'write',
        'Writing is hard for me.',
        {
          state: 'model-reviewed',
          record: 'study-review.md: ask-teacher.A1.focus',
        },
      ],
      [
        'instruction',
        'check-instruction',
        'Do you understand “circle one word”?',
        '可以理解，也可以请求演示。',
        'yes',
        'Yes. I draw a circle around one word.',
        'show',
        'No. Please show me.',
        {
          state: 'model-reviewed',
          record: 'study-review.md: ask-teacher.A1.instruction',
        },
      ],
      [
        'example',
        'request-example',
        'Do you want an example?',
        '说明是否需要例子。',
        'yes',
        'Yes, an example, please.',
        'try',
        'No, I want to try.',
        {
          state: 'model-reviewed',
          record: 'study-review.md: ask-teacher.A1.example',
        },
      ],
      [
        'meaning',
        'check-word-meaning',
        'What does “book” mean on this card?',
        '回应已给的单词。',
        'object',
        'It is something I read.',
        'ask',
        'I do not know. Please tell me.',
        {
          state: 'model-reviewed',
          record: 'study-review.md: ask-teacher.A1.meaning',
        },
      ],
      [
        'attempt',
        'choose-word',
        'Which word will you write: apple or book?',
        '选择实际要写的词。',
        'apple',
        'I will write apple.',
        'book',
        'I will write book.',
        {
          state: 'model-reviewed',
          record: 'study-review.md: ask-teacher.A1.attempt',
        },
      ],
      [
        'check',
        'request-check',
        'What do you want me to look at on your page?',
        '请求查看指定部分，不假设已批改。',
        'word',
        'Please look at this word.',
        'sentence',
        'Please look at this sentence.',
        {
          state: 'model-reviewed',
          record: 'study-review.md: ask-teacher.A1.check',
        },
      ],
      [
        'contrast',
        'compare-concrete-items',
        'This card has one apple; that card has two. Which card do you want?',
        '数量差异已给出，只需选卡。',
        'one',
        'The card with one apple, please.',
        'two',
        'The card with two apples, please.',
        {
          state: 'model-reviewed',
          record: 'study-review.md: ask-teacher.A1.contrast',
        },
      ],
      [
        'apply',
        'choose-tool',
        'Will you use a pencil or the blue pen?',
        '选择桌上的书写工具。',
        'pencil',
        'I will use a pencil.',
        'pen',
        'I will use the blue pen.',
        {
          state: 'model-reviewed',
          record: 'study-review.md: ask-teacher.A1.apply',
        },
      ],
      [
        'scope',
        'check-amount',
        'The sheet says “one sentence”. Is that clear?',
        '确认具体数量或请指给你看。',
        'one',
        'Yes, just one sentence.',
        'point',
        'Please show me that line.',
        {
          state: 'model-reviewed',
          record: 'study-review.md: ask-teacher.A1.scope',
        },
      ],
      [
        'next',
        'choose-next-step',
        'Will you try now or read the card first?',
        '选择尚未做的下一步。',
        'try',
        'I will try now.',
        'read',
        'I will read the card first.',
        {
          state: 'model-reviewed',
          record: 'study-review.md: ask-teacher.A1.next',
        },
      ],
      [
        'repeat',
        'request-repeat',
        'Do you want me to say the instruction again?',
        '前文确实已给过指令。',
        'again',
        'Yes, please say it again.',
        'no',
        'No, I heard it.',
        {
          state: 'model-reviewed',
          record: 'study-review.md: ask-teacher.A1.repeat',
        },
      ],
      [
        'format',
        'choose-demonstration',
        'Shall I point to a card or write an example?',
        '选择示范形式，不表示已示范。',
        'point',
        'Please point to a card.',
        'write',
        'Please write an example.',
        {
          state: 'model-reviewed',
          record: 'study-review.md: ask-teacher.A1.format',
        },
      ],
    ],
    variantRead.A1,
  ),
  A2: studyPack(
    scene,
    'A2',
    {
      canDoZh: '核查两步指令，选择示范并说明需要查看的部分。',
      complexityZh: '熟悉词句的小任务，允许说明一个具体信息缺口。',
      scaffoldingZh: '题目直接给出例句和数量，不依赖未提供的讲义。',
      registerZh: '简短直接的师生求助与确认。',
    },
    [
      [
        'focus',
        'identify-gap',
        'What would you like help with on this sheet?',
        '指出一个需要帮助的环节。',
        'words',
        'I need help reading the new words.',
        'sentence',
        'I can read the words, but making a sentence is hard.',
        {
          state: 'model-reviewed',
          record: 'study-review.md: ask-teacher.A2.focus',
        },
      ],
      [
        'instruction',
        'check-instruction',
        'What comes first in the instruction I gave?',
        '核查已给的两步顺序，也可坦承不确定。',
        'circle',
        'First, we circle one word.',
        'uncertain',
        'I am not sure which step comes first.',
        {
          state: 'model-reviewed',
          record: 'study-review.md: ask-teacher.A2.instruction',
        },
      ],
      [
        'example',
        'request-example',
        'Would a complete example or just a starting phrase help you?',
        '选择支架程度。',
        'complete',
        'A complete example would help me understand the task.',
        'start',
        'Just a starting phrase, please. I want to finish it myself.',
        {
          state: 'model-reviewed',
          record: 'study-review.md: ask-teacher.A2.example',
        },
      ],
      [
        'meaning',
        'check-word-meaning',
        'On this sheet, “circle” is an action. Is its meaning clear?',
        '指令中的用法已明确。',
        'clear',
        'Yes, it means drawing a circle around a word.',
        'show',
        'Not yet. Could you show me on the card?',
        {
          state: 'model-reviewed',
          record: 'study-review.md: ask-teacher.A2.meaning',
        },
      ],
      [
        'attempt',
        'choose-word',
        'Which sentence would you like to try writing?',
        '两句均为可尝试的目标。',
        'apple',
        'I would like to write “I have an apple.”',
        'book',
        'I would like to write “This is my book.”',
        {
          state: 'model-reviewed',
          record: 'study-review.md: ask-teacher.A2.attempt',
        },
      ],
      [
        'check',
        'request-check',
        'Which part of your writing would you like me to check first?',
        '选择反馈焦点。',
        'spelling',
        'Could you check the spelling first?',
        'order',
        'Please check the order of the words.',
        {
          state: 'model-reviewed',
          record: 'study-review.md: ask-teacher.A2.check',
        },
      ],
      [
        'contrast',
        'compare-examples',
        'Look at “a book” and “two books”. What do you notice?',
        '例子就在题中，可观察也可求助。',
        's',
        'The second example has an s at the end.',
        'help',
        'I see a difference, but I need help explaining it.',
        {
          state: 'model-reviewed',
          record: 'study-review.md: ask-teacher.A2.contrast',
        },
      ],
      [
        'apply',
        'apply-example',
        'Could you make a new example using “apple”?',
        '将已给数量例子用于熟悉词。',
        'one',
        'Yes: “one apple”.',
        'two',
        'Yes: “two apples”.',
        {
          state: 'model-reviewed',
          record: 'study-review.md: ask-teacher.A2.apply',
        },
      ],
      [
        'scope',
        'check-amount',
        'Would you like to check how much writing this exercise needs?',
        '可询问数量，也可引用已知指令。',
        'ask',
        'Yes. Do we need more than one sentence?',
        'one',
        'No, I understand that it is one sentence.',
        {
          state: 'model-reviewed',
          record: 'study-review.md: ask-teacher.A2.scope',
        },
      ],
      [
        'next',
        'choose-next-step',
        'How would you like to begin your own attempt?',
        '不假设帮助请求已经得到回应。',
        'card',
        'I will read the card and try a sentence.',
        'wait',
        'I would like to wait for a demonstration.',
        {
          state: 'model-reviewed',
          record: 'study-review.md: ask-teacher.A2.next',
        },
      ],
      [
        'repeat',
        'request-repeat',
        'Which part of my spoken instruction would you like to hear again?',
        '请求重说真实给过的部分或表示无需重说。',
        'second',
        'Please repeat the part after circling a word.',
        'none',
        'I do not need it repeated; I heard both steps.',
        {
          state: 'model-reviewed',
          record: 'study-review.md: ask-teacher.A2.repeat',
        },
      ],
      [
        'format',
        'choose-demonstration',
        'Would it be easier to follow a written example or a slow demonstration?',
        '选择形式。',
        'written',
        'A written example would be easier for me.',
        'demo',
        'A slow demonstration would help more.',
        {
          state: 'model-reviewed',
          record: 'study-review.md: ask-teacher.A2.format',
        },
      ],
    ],
    variantRead.A2,
  ),
  B1: studyPack(
    scene,
    'B1',
    {
      canDoZh: '定位理解缺口、核查指令并迁移一个小语法例子。',
      complexityZh: '说明困难原因，区分观察与不确定，不要求完整语法术语。',
      scaffoldingZh: '自足例句与明确反馈选项，老师请求尚未答复也能连贯推进。',
      registerZh: '主动求证而不过度道歉的课堂口语。',
    },
    [
      [
        'focus',
        'identify-gap',
        'Where does this exercise become difficult for you?',
        '把困难定位到任务环节。',
        'instruction',
        'I know the words, but I am unsure what kind of sentence the instruction expects.',
        'forming',
        'I understand the task, but putting my idea into a sentence is difficult.',
        {
          state: 'model-reviewed',
          record: 'study-review.md: ask-teacher.B1.focus',
        },
      ],
      [
        'instruction',
        'check-instruction',
        'How would you check whether choosing a word and writing a sentence are linked?',
        '核查尚未明确的关联。',
        'use',
        'Does the sentence have to include the word we circle?',
        'free',
        'Can we circle one word and write about a different one?',
        {
          state: 'model-reviewed',
          record: 'study-review.md: ask-teacher.B1.instruction',
        },
      ],
      [
        'example',
        'request-example',
        'What sort of example would help without doing the whole exercise for you?',
        '让求助有具体边界。',
        'start',
        'Could you show the beginning and let me finish it?',
        'different',
        'Could you use a different word so I can make my own sentence?',
        {
          state: 'model-reviewed',
          record: 'study-review.md: ask-teacher.B1.example',
        },
      ],
      [
        'meaning',
        'check-word-meaning',
        'In “a short sentence”, what would you like to clarify about “short”?',
        '针对给出的模糊要求。',
        'words',
        'Is there a limit on the number of words?',
        'idea',
        'Do you mean we should express only one simple idea?',
        {
          state: 'model-reviewed',
          record: 'study-review.md: ask-teacher.B1.meaning',
        },
      ],
      [
        'attempt',
        'choose-attempt',
        'How would you approach a sentence when you are unsure of one word?',
        '提出尝试策略而非声称已经写过。',
        'simple',
        'I would use a simpler word that I know and check the other word later.',
        'gap',
        'I would leave a gap for the word and finish the rest of the sentence.',
        {
          state: 'model-reviewed',
          record: 'study-review.md: ask-teacher.B1.attempt',
        },
      ],
      [
        'check',
        'request-check',
        'How would you ask for feedback that tells you more than whether the sentence is right?',
        '选择实质反馈需求。',
        'reason',
        'Could you explain why that word order works or does not work?',
        'meaning',
        'Could you tell me what meaning you get from my sentence?',
        {
          state: 'model-reviewed',
          record: 'study-review.md: ask-teacher.B1.check',
        },
      ],
      [
        'contrast',
        'compare-examples',
        'Compare “I read every day” with “I am reading now”. What difference can you explain?',
        '例句已完整给出。',
        'time',
        'The first is a habit, while the second describes what is happening now.',
        'help',
        'I can see the verb changes, but I need help connecting that change to the time.',
        {
          state: 'model-reviewed',
          record: 'study-review.md: ask-teacher.B1.contrast',
        },
      ],
      [
        'apply',
        'apply-example',
        'How could you describe a regular activity of your own?',
        '迁移到规律活动，可用虚构设定。',
        'walk',
        'I walk to class every morning.',
        'cook',
        'I cook dinner on Fridays.',
        {
          state: 'model-reviewed',
          record: 'study-review.md: ask-teacher.B1.apply',
        },
      ],
      [
        'scope',
        'check-rule-scope',
        'Would these two examples be enough for you to explain every use of the present tense?',
        '允许说明当前理解的范围。',
        'limited',
        'No, I could explain these examples, but I would need more to describe all the uses.',
        'question',
        'Not yet. I would want to ask about verbs such as “know” first.',
        {
          state: 'model-reviewed',
          record: 'study-review.md: ask-teacher.B1.scope',
        },
      ],
      [
        'next',
        'choose-next-step',
        'For a pattern such as “I read every day”, how could you check your understanding?',
        '完整引入例子，短练也能据此制定下一步。',
        'new',
        'I could write a new example without looking at the model.',
        'sort',
        'I could sort a few sentences into habits and things happening now.',
        {
          state: 'model-reviewed',
          record: 'study-review.md: ask-teacher.B1.next',
        },
      ],
      [
        'repeat',
        'request-repeat',
        'How would you ask me to repeat only the part of the original instruction you need?',
        '前文指令真实存在，针对部分请求。',
        'after',
        'Could you repeat what we do after circling a word?',
        'first',
        'Could you say the first step again? I missed the action word.',
        {
          state: 'model-reviewed',
          record: 'study-review.md: ask-teacher.B1.repeat',
        },
      ],
      [
        'format',
        'choose-demonstration',
        'How should an explanation be presented so you can follow the steps?',
        '选择具体呈现方式。',
        'board',
        'Please put the steps on the board so I can refer back to them.',
        'demo',
        'Please demonstrate one step at a time and pause between them.',
        {
          state: 'model-reviewed',
          record: 'study-review.md: ask-teacher.B1.format',
        },
      ],
    ],
    variantRead.B1,
  ),
  B2: studyPack(
    scene,
    'B2',
    {
      canDoZh: '精确提问，比较例句并检验规则的适用范围。',
      complexityZh: '区分任务要求、形式与含义，提出有限验证而非背诵答案。',
      scaffoldingZh: '所有小例子当场给出，可解释未知而不假装理解。',
      registerZh: '礼貌但有主见地要求可用反馈。',
    },
    [
      [
        'focus',
        'identify-gap',
        'Which uncertainty would be most useful to resolve before you begin?',
        '优先说明一个关键缺口。',
        'criterion',
        'I need to know whether the aim is grammatical accuracy or communicating an idea clearly.',
        'choice',
        'I am unsure whether we may choose our own sentence structure or should follow a particular model.',
        {
          state: 'model-reviewed',
          record: 'study-review.md: ask-teacher.B2.focus',
        },
      ],
      [
        'instruction',
        'check-instruction',
        'What would you ask about the relationship between the two steps in the original instruction?',
        '不重复已清楚的动作，而核查关联。',
        'purpose',
        'Is circling a word meant to identify the topic for the sentence or simply practise recognition?',
        'constraint',
        'Must the circled word appear exactly as printed, or may we change its form in the sentence?',
        {
          state: 'model-reviewed',
          record: 'study-review.md: ask-teacher.B2.instruction',
        },
      ],
      [
        'example',
        'request-example',
        'How could an example make the decision process visible rather than just display a finished answer?',
        '请求展示过程。',
        'think',
        'Could you talk through why you choose one structure rather than another?',
        'revise',
        'Could you show an initial attempt and explain one useful revision?',
        {
          state: 'model-reviewed',
          record: 'study-review.md: ask-teacher.B2.example',
        },
      ],
      [
        'meaning',
        'check-word-meaning',
        'The comment “make it clearer” appears on a separate sample. What would you ask the teacher?',
        '独立样例避免虚构对自己已给过的反馈。',
        'unclear',
        'Which part is unclear: the reference, the order of ideas, or the choice of words?',
        'reader',
        'What would a reader be likely to misunderstand in this version?',
        {
          state: 'model-reviewed',
          record: 'study-review.md: ask-teacher.B2.meaning',
        },
      ],
      [
        'attempt',
        'choose-attempt',
        'How would you balance checking every detail with getting an initial version down?',
        '解释写作尝试策略。',
        'draft',
        'I would draft the main idea first, then check the details that could alter its meaning.',
        'anchor',
        'I would check the key phrase before drafting, since the rest of the sentence depends on it.',
        {
          state: 'model-reviewed',
          record: 'study-review.md: ask-teacher.B2.attempt',
        },
      ],
      [
        'check',
        'request-check',
        'What feedback would help you revise independently next time?',
        '让反馈产生可迁移的信息。',
        'pattern',
        'Please identify the pattern behind the problem rather than correcting every instance for me.',
        'compare',
        'Could you compare my version with an alternative and explain what changes for the reader?',
        {
          state: 'model-reviewed',
          record: 'study-review.md: ask-teacher.B2.check',
        },
      ],
      [
        'contrast',
        'compare-examples',
        'Compare “Some students preferred the picture” and “The students preferred the picture”. What changes?',
        '在具体对比中讨论指称范围。',
        'scope',
        'The first limits the claim to part of the group; the second sounds like a claim about the group as a whole.',
        'context',
        'The second may refer to a group already identified, so I would want the surrounding context before interpreting its scope.',
        {
          state: 'model-reviewed',
          record: 'study-review.md: ask-teacher.B2.contrast',
        },
      ],
      [
        'apply',
        'apply-example',
        'How would you report a fictional result in which six of ten students chose pictures?',
        '数据完全给出，不编造研究来源。',
        'numbers',
        'Six of the ten students chose pictures.',
        'majority',
        'A majority of this small group chose pictures.',
        {
          state: 'model-reviewed',
          record: 'study-review.md: ask-teacher.B2.apply',
        },
      ],
      [
        'scope',
        'check-rule-scope',
        'What should you avoid concluding from that six-out-of-ten result?',
        '限定结论的对象或程度。',
        'all',
        'I should not say that all students prefer pictures.',
        'cause',
        'I should not claim the pictures caused better learning; the result only describes a choice.',
        {
          state: 'model-reviewed',
          record: 'study-review.md: ask-teacher.B2.scope',
        },
      ],
      [
        'next',
        'choose-next-step',
        'How could you test your understanding without simply repeating the teacher’s wording?',
        '提出新检验步骤。',
        'contrast',
        'I could create two contrasting examples and explain the difference.',
        'classify',
        'I could classify a new example and explain which detail guided my choice.',
        {
          state: 'model-reviewed',
          record: 'study-review.md: ask-teacher.B2.next',
        },
      ],
      [
        'repeat',
        'request-repeat',
        'What would be a precise request for another hearing of the original instruction?',
        '仅请求已说过的部分。',
        'link',
        'Could you repeat the wording linking the circling step to the writing step?',
        'last',
        'Could you repeat the final clause? I heard the first action clearly.',
        {
          state: 'model-reviewed',
          record: 'study-review.md: ask-teacher.B2.repeat',
        },
      ],
      [
        'format',
        'choose-demonstration',
        'Which explanation format would let you check your own reasoning?',
        '关注可检验的解释方式。',
        'side',
        'Two examples side by side would let me identify the difference before you explain it.',
        'steps',
        'A worked example with pauses would let me predict the next step and compare my reasoning.',
        {
          state: 'model-reviewed',
          record: 'study-review.md: ask-teacher.B2.format',
        },
      ],
    ],
    variantRead.B2,
  ),
  C1: studyPack(
    scene,
    'C1',
    {
      canDoZh: '区分表述歧义与概念缺口，探查解释和证据边界。',
      complexityZh: '用具体反例限定规则，协商可迁移反馈并重述论点。',
      scaffoldingZh: '完整自足的原创例句、数据与反馈样例支持复杂问答。',
      registerZh: '精确且不对抗的师生讨论；可质疑假设而不冒充课程专家。',
    },
    [
      [
        'focus',
        'identify-gap',
        'How would you distinguish a problem with the task wording from a gap in your own understanding?',
        '区分两种不确定来源。',
        'wording',
        'I can explain the two actions separately, but the wording leaves their relationship open; that is what I would clarify first.',
        'concept',
        'The instruction itself is clear to me; what I lack is a way of deciding which structure expresses my intended meaning.',
        {
          state: 'model-reviewed',
          record: 'study-review.md: ask-teacher.C1.focus',
        },
      ],
      [
        'instruction',
        'check-instruction',
        'What unstated requirement might you need to check in “circle one word, then write a sentence”?',
        '不假设已经明确关联。',
        'reuse',
        'Should the sentence demonstrate how the selected word is used, or is the selection merely a warm-up?',
        'form',
        'Are we expected to preserve the printed form of the word, even if the sentence calls for a different form?',
        {
          state: 'model-reviewed',
          record: 'study-review.md: ask-teacher.C1.instruction',
        },
      ],
      [
        'example',
        'request-example',
        'What would make a demonstration useful beyond this particular answer?',
        '请求可迁移的判断过程。',
        'decision',
        'Could you make the decision points explicit, including where another choice would also be defensible?',
        'boundary',
        'Could you include a near-miss example so we can see where the explanation stops applying?',
        {
          state: 'model-reviewed',
          record: 'study-review.md: ask-teacher.C1.example',
        },
      ],
      [
        'meaning',
        'check-word-meaning',
        'A separate sample receives the comment “the argument is thin”. How would you seek usable clarification?',
        '引用独立反馈，不虚构给你的评语。',
        'support',
        'Do you mean the claim needs stronger support, or that the link between the support and the claim is missing?',
        'scope',
        'Would narrowing the claim address the problem, or is the available support inadequate even for a narrower claim?',
        {
          state: 'model-reviewed',
          record: 'study-review.md: ask-teacher.C1.meaning',
        },
      ],
      [
        'attempt',
        'choose-attempt',
        'How would you proceed if two formulations seem accurate but place the emphasis differently?',
        '处理均可成立的措辞选择。',
        'reader',
        'I would choose according to what the reader needs to notice first, then check that the shift in emphasis is intentional.',
        'compare',
        'I would keep both versions briefly and compare what each implies before committing to one.',
        {
          state: 'model-reviewed',
          record: 'study-review.md: ask-teacher.C1.attempt',
        },
      ],
      [
        'check',
        'request-check',
        'What kind of feedback would help you recognise the same issue in unfamiliar material?',
        '寻求可迁移而非仅局部订正的反馈。',
        'diagnostic',
        'Could you explain the question you ask yourself when diagnosing this issue, rather than only giving me the preferred wording?',
        'limits',
        'Could you point out which part of the feedback is a general principle and which depends on this particular context?',
        {
          state: 'model-reviewed',
          record: 'study-review.md: ask-teacher.C1.check',
        },
      ],
      [
        'contrast',
        'compare-examples',
        'How do “The exercise improved recall” and “Recall was higher after the exercise” differ as claims?',
        '两句都已给出，比较因果与时间先后。',
        'causal',
        'The first attributes the improvement to the exercise, whereas the second reports a sequence without establishing the cause.',
        'design',
        'The first needs a design that supports a causal inference; a before-and-after observation alone would only support the second.',
        {
          state: 'model-reviewed',
          record: 'study-review.md: ask-teacher.C1.contrast',
        },
      ],
      [
        'apply',
        'apply-example',
        'In a fictional class, scores rose after practice, but there was no comparison group. How would you report that?',
        '只根据题内虚构条件表述。',
        'observed',
        'Scores rose after the practice session, although this observation does not isolate the effect of practice.',
        'cautious',
        'I would report the before-and-after scores separately and leave the causal explanation open for a better-controlled comparison.',
        {
          state: 'model-reviewed',
          record: 'study-review.md: ask-teacher.C1.apply',
        },
      ],
      [
        'scope',
        'check-rule-scope',
        'What further question would you ask before treating that improvement as a lasting learning gain?',
        '提出新的证据缺口。',
        'delay',
        'Were the students tested again after a delay, or only immediately after practice?',
        'transfer',
        'Did the later task require using the knowledge in a new context, or repeating the same items?',
        {
          state: 'model-reviewed',
          record: 'study-review.md: ask-teacher.C1.scope',
        },
      ],
      [
        'next',
        'choose-next-step',
        'How would you summarise the difference between observing higher scores after practice and proving that practice caused the rise?',
        '题内完整给出对比，短练不依赖未经过的样例。',
        'claim',
        'The strength of the claim needs to match what the design can establish, not just the size of the observed change.',
        'distinguish',
        'I need to separate what happened after an activity from what can reasonably be attributed to that activity.',
        {
          state: 'model-reviewed',
          record: 'study-review.md: ask-teacher.C1.next',
        },
      ],
      [
        'repeat',
        'request-repeat',
        'How would you request a repeat while making clear which part of the spoken instruction you did catch?',
        '听说历史来自情境的真实给句。',
        'ending',
        'I caught the instruction to circle a word; could you repeat exactly what followed it?',
        'opening',
        'I heard the sentence-writing part, but could you repeat the opening action so I do not fill it in from memory?',
        {
          state: 'model-reviewed',
          record: 'study-review.md: ask-teacher.C1.repeat',
        },
      ],
      [
        'format',
        'choose-demonstration',
        'How could an explanation expose the reasoning without overwhelming you with every possible exception?',
        '协商解释的信息层级。',
        'core',
        'Please establish the main distinction with one contrast first, then introduce an exception that genuinely tests it.',
        'questions',
        'A short sequence of diagnostic questions would help me follow the reasoning; we could leave rare edge cases until afterwards.',
        {
          state: 'model-reviewed',
          record: 'study-review.md: ask-teacher.C1.format',
        },
      ],
    ],
    variantRead.C1,
  ),
}
