import { studyPack, type StudyScene, type Review } from './authoring'
const variantRead = {
  A1: {
    state: 'model-reviewed',
    record: 'study-review.md: class-introduction.A1 variants',
  },
  A2: {
    state: 'model-reviewed',
    record: 'study-review.md: class-introduction.A2 variants',
  },
  B1: {
    state: 'model-reviewed',
    record: 'study-review.md: class-introduction.B1 variants',
  },
  B2: {
    state: 'model-reviewed',
    record: 'study-review.md: class-introduction.B2 variants',
  },
  C1: {
    state: 'model-reviewed',
    record: 'study-review.md: class-introduction.C1 variants',
  },
} satisfies Record<string, Review>
const scene: StudyScene = {
  sceneId: 'study-01',
  slug: 'class-introduction',
  situations: [
    '虚构新班见面。老师 Lee 正在认识你，桌上有姓名卡、地图、图画和故事卡。可使用参考答案的虚构姓名与经历，不必透露真实身份。Lee 已说：“Welcome. You can use a picture or a story today. First choose a card. Next think about your idea. Then speak.” 尚未分配同伴或活动，短练只记录实际说出的选择。',
    '虚构新班的小组体验环节。老师 Lee 正在安排首次结伴练习，桌上有姓名卡、地图、图画和故事卡。Lee 已说：“Welcome. You can use a picture or a story today. First choose a card. Next think about your idea. Then speak.” 小组里有不同经验的同学，需要先说明听说支持和合作方式；尚未分组，不要求真实个人资料。',
  ],
  paths: [
    {
      short: ['name', 'interest', 'next'],
      standard: ['name', 'experience', 'interest', 'goal', 'partner', 'next'],
      extended: [
        'name',
        'experience',
        'interest',
        'goal',
        'support',
        'partner',
        'resource',
        'contribute',
        'privacy',
        'next',
      ],
    },
    {
      short: ['name', 'pace', 'next'],
      standard: ['name', 'interest', 'pace', 'question', 'partner', 'next'],
      extended: [
        'name',
        'experience',
        'interest',
        'goal',
        'pace',
        'question',
        'partner',
        'contribute',
        'privacy',
        'next',
      ],
    },
  ],
  closing:
    'The introduction practice is complete. Only your stated choices are recorded; no partner or activity has been assigned.',
  partial:
    'We will stop the introduction here. Some choices are still unconfirmed, and no class arrangement is assumed.',
  repairs: {
    clarify: 'You can ask about this introduction question.',
    struggle: 'A name or a short phrase is enough to start.',
    offTopic: 'We can return to getting to know you as a class member.',
    unknown:
      'This wording is not covered locally, so I have not confirmed an introduction detail.',
    changed: 'Your new introduction detail replaces the earlier one.',
    refusedClosing:
      'We will stop here. You do not have to share personal details.',
  },
}
export const classIntroduction = {
  A1: studyPack(
    scene,
    'A1',
    {
      canDoZh: '借助姓名卡和图画介绍自己，表达简单课堂需要。',
      complexityZh: '每次处理姓名、物件或一个偏好；合作只要求具体选择。',
      scaffoldingZh: '已展示材料、短问句与可直接使用的双选回答。',
      registerZh: '友好的基础课堂口语；可以求助或保留隐私。',
    },
    [
      [
        'name',
        'give-name',
        'What is your name?',
        '可以使用虚构姓名。',
        'mei',
        'My name is Mei.',
        'leo',
        'Please call me Leo.',
        {
          state: 'model-reviewed',
          record: 'study-review.md: class-introduction.A1.name',
        },
      ],
      [
        'experience',
        'describe-experience',
        'Is this your first English class?',
        '说是否第一次上英语课。',
        'first',
        'Yes, this is my first class.',
        'before',
        'No, I had a class last year.',
        {
          state: 'model-reviewed',
          record: 'study-review.md: class-introduction.A1.experience',
        },
      ],
      [
        'interest',
        'choose-material',
        'Do you like pictures or stories?',
        '选择感兴趣的材料。',
        'pictures',
        'I like pictures.',
        'stories',
        'I like stories.',
        {
          state: 'model-reviewed',
          record: 'study-review.md: class-introduction.A1.interest',
        },
      ],
      [
        'goal',
        'state-goal',
        'What do you want to learn to say?',
        '选择一个具体学习目标。',
        'name',
        'I want to say my name.',
        'food',
        'I want to talk about food.',
        {
          state: 'model-reviewed',
          record: 'study-review.md: class-introduction.A1.goal',
        },
      ],
      [
        'support',
        'request-support',
        'Do you need a pen?',
        '可以要笔，也可以说明已有笔。',
        'need',
        'Yes, a pen, please.',
        'have',
        'No, I have a pen.',
        {
          state: 'model-reviewed',
          record: 'study-review.md: class-introduction.A1.support',
        },
      ],
      [
        'partner',
        'choose-partner-format',
        'Do you want to work with one person or two?',
        '只选择人数，还没有分组。',
        'one',
        'One person, please.',
        'two',
        'Two people, please.',
        {
          state: 'model-reviewed',
          record: 'study-review.md: class-introduction.A1.partner',
        },
      ],
      [
        'resource',
        'choose-resource',
        'Would you like the map or a blank card?',
        '选择桌上的辅助材料。',
        'map',
        'The map, please.',
        'card',
        'A blank card, please.',
        {
          state: 'model-reviewed',
          record: 'study-review.md: class-introduction.A1.resource',
        },
      ],
      [
        'contribute',
        'offer-contribution',
        'Can you draw or read a word for the group?',
        '说能做的具体事情。',
        'draw',
        'I can draw a cat.',
        'read',
        'I can read a word.',
        {
          state: 'model-reviewed',
          record: 'study-review.md: class-introduction.A1.contribute',
        },
      ],
      [
        'privacy',
        'set-privacy',
        'Do you want to say your age?',
        '不说年龄也完全可以。',
        'say',
        'Yes. I am twenty.',
        'private',
        'No, I do not want to say.',
        {
          state: 'model-reviewed',
          record: 'study-review.md: class-introduction.A1.privacy',
        },
      ],
      [
        'next',
        'choose-next-step',
        'Are you ready to start, or do you need a minute?',
        '说明准备情况。',
        'ready',
        'I am ready.',
        'minute',
        'One minute, please.',
        {
          state: 'model-reviewed',
          record: 'study-review.md: class-introduction.A1.next',
        },
      ],
      [
        'pace',
        'request-pace',
        'Am I speaking too fast?',
        '老师正在讲话，可以请求放慢。',
        'slow',
        'Yes, please speak slowly.',
        'fine',
        'No, this is OK.',
        {
          state: 'model-reviewed',
          record: 'study-review.md: class-introduction.A1.pace',
        },
      ],
      [
        'question',
        'ask-class-information',
        'What do you want to ask about this room?',
        '提出尚不知道的房间信息。',
        'books',
        'Where are the books?',
        'seat',
        'Can I sit here?',
        {
          state: 'model-reviewed',
          record: 'study-review.md: class-introduction.A1.question',
        },
      ],
    ],
    variantRead.A1,
  ),
  A2: studyPack(
    scene,
    'A2',
    {
      canDoZh: '在新班说明学习经历、兴趣和可预测的合作偏好。',
      complexityZh: '连接一个背景与简单需要，安排参与方式而非论证观点。',
      scaffoldingZh: '熟悉教室物件、两种明确答案和中文意图提示。',
      registerZh: '简短礼貌的师生交流，可说明不愿公开的信息。',
    },
    [
      [
        'name',
        'give-name',
        'What name would you like us to use in class?',
        '给出课堂称呼。',
        'mei',
        'Please use Mei; it is easy to say.',
        'leo',
        'You can call me Leo in class.',
        {
          state: 'model-reviewed',
          record: 'study-review.md: class-introduction.A2.name',
        },
      ],
      [
        'experience',
        'describe-experience',
        'Where have you practised English before?',
        '采用虚构学习经历即可。',
        'school',
        'I practised English at school.',
        'home',
        'I have only practised at home.',
        {
          state: 'model-reviewed',
          record: 'study-review.md: class-introduction.A2.experience',
        },
      ],
      [
        'interest',
        'choose-material',
        'Which class activity sounds enjoyable to you?',
        '选择具体活动。',
        'pictures',
        'Talking about pictures sounds fun.',
        'stories',
        'I would enjoy reading a short story.',
        {
          state: 'model-reviewed',
          record: 'study-review.md: class-introduction.A2.interest',
        },
      ],
      [
        'goal',
        'state-goal',
        'What would you like to do more easily in English?',
        '说明日常口语目标。',
        'travel',
        'I want to ask for directions when I travel.',
        'friends',
        'I want to talk to new friends.',
        {
          state: 'model-reviewed',
          record: 'study-review.md: class-introduction.A2.goal',
        },
      ],
      [
        'support',
        'request-support',
        'Would a written example help you get started?',
        '说是否需要文字范例。',
        'example',
        'Yes, I would like to see an example.',
        'try',
        'No, I would like to try first.',
        {
          state: 'model-reviewed',
          record: 'study-review.md: class-introduction.A2.support',
        },
      ],
      [
        'partner',
        'choose-partner-format',
        'Would you prefer the same partner or a new partner each time?',
        '选择合作安排，不代表已安排。',
        'same',
        'The same partner, please. I feel more comfortable.',
        'new',
        'A new partner each time would be interesting.',
        {
          state: 'model-reviewed',
          record: 'study-review.md: class-introduction.A2.partner',
        },
      ],
      [
        'resource',
        'choose-resource',
        'Which would help you speak: the map or some picture cards?',
        '选择说话支架。',
        'map',
        'The map would help me talk about places.',
        'cards',
        'Picture cards would give me more ideas.',
        {
          state: 'model-reviewed',
          record: 'study-review.md: class-introduction.A2.resource',
        },
      ],
      [
        'contribute',
        'offer-contribution',
        'What could you bring to a group activity?',
        '说明能贡献的小技能。',
        'drawing',
        'I could draw pictures for a group story.',
        'reading',
        'I could read the instructions aloud.',
        {
          state: 'model-reviewed',
          record: 'study-review.md: class-introduction.A2.contribute',
        },
      ],
      [
        'privacy',
        'set-privacy',
        'Is there anything you would rather not talk about in introductions?',
        '可以设置话题边界。',
        'address',
        'I would rather not give my address.',
        'open',
        'No, I am happy to answer the introduction questions.',
        {
          state: 'model-reviewed',
          record: 'study-review.md: class-introduction.A2.privacy',
        },
      ],
      [
        'next',
        'choose-next-step',
        'Would you like to introduce yourself to a partner now or practise quietly first?',
        '选择接下来的准备方式。',
        'partner',
        'I would like to try with a partner now.',
        'quiet',
        'I would like to practise quietly first.',
        {
          state: 'model-reviewed',
          record: 'study-review.md: class-introduction.A2.next',
        },
      ],
      [
        'pace',
        'request-pace',
        'How is the speed of my introduction for you?',
        '回应已开始的介绍速度。',
        'slow',
        'It is a little fast. Could you slow down?',
        'fine',
        'The speed is fine for me.',
        {
          state: 'model-reviewed',
          record: 'study-review.md: class-introduction.A2.pace',
        },
      ],
      [
        'question',
        'ask-class-information',
        'What would you like to know before the first activity?',
        '提出新的课堂信息需求。',
        'length',
        'How long is the activity?',
        'notes',
        'Can we use our notes?',
        {
          state: 'model-reviewed',
          record: 'study-review.md: class-introduction.A2.question',
        },
      ],
    ],
    variantRead.A2,
  ),
  B1: studyPack(
    scene,
    'B1',
    {
      canDoZh: '说明学习经验与实际困难，协商首次课堂参与方式。',
      complexityZh: '把过去经验与今后目标联系起来，给出简短原因。',
      scaffoldingZh: '具体课堂材料和情境；回答提供连词但不要求个人真实经历。',
      registerZh: '自然、合作的师生口语，允许不同准备速度。',
    },
    [
      [
        'name',
        'give-name',
        'How would you introduce your preferred name to the class?',
        '给出称呼及必要说明。',
        'mei',
        'My name is Mei, and that is the name I use every day.',
        'leo',
        'Please call me Leo; I use that name in English classes.',
        {
          state: 'model-reviewed',
          record: 'study-review.md: class-introduction.B1.name',
        },
      ],
      [
        'experience',
        'describe-experience',
        'What has your experience of speaking English been like?',
        '选择一种学习经历并说明困难或收益。',
        'reading',
        'I read quite often, but I have had little speaking practice.',
        'club',
        'I joined a conversation club, which helped me feel less nervous.',
        {
          state: 'model-reviewed',
          record: 'study-review.md: class-introduction.B1.experience',
        },
      ],
      [
        'interest',
        'choose-material',
        'What kind of material would make you want to join a discussion?',
        '把材料与参与兴趣联系起来。',
        'pictures',
        'A picture of a place would help because I enjoy describing things.',
        'stories',
        'A short story would interest me because people can read it differently.',
        {
          state: 'model-reviewed',
          record: 'study-review.md: class-introduction.B1.interest',
        },
      ],
      [
        'goal',
        'state-goal',
        'What change would you like to notice in your speaking this term?',
        '提出可观察的目标。',
        'followup',
        'I would like to ask follow-up questions instead of ending a chat quickly.',
        'explain',
        'I want to explain a problem without immediately switching languages.',
        {
          state: 'model-reviewed',
          record: 'study-review.md: class-introduction.B1.goal',
        },
      ],
      [
        'support',
        'request-support',
        'What would help when you know an idea but cannot find the words?',
        '提出具体支架。',
        'keywords',
        'A few key words on the board would help me continue.',
        'time',
        'I would prefer a little thinking time before anyone helps.',
        {
          state: 'model-reviewed',
          record: 'study-review.md: class-introduction.B1.support',
        },
      ],
      [
        'partner',
        'choose-partner-format',
        'How would you like partners to support each other during a first attempt?',
        '协商尝试时的帮助方式。',
        'wait',
        'I would like us to wait until the other person finishes.',
        'prompt',
        'We could offer a word if the speaker asks for help.',
        {
          state: 'model-reviewed',
          record: 'study-review.md: class-introduction.B1.partner',
        },
      ],
      [
        'resource',
        'choose-resource',
        'How could you use the table materials without reading a whole answer?',
        '说明材料的辅助用法。',
        'map',
        'I could point to the map and describe a route in my own words.',
        'card',
        'I could write three key words on a card as a reminder.',
        {
          state: 'model-reviewed',
          record: 'study-review.md: class-introduction.B1.resource',
        },
      ],
      [
        'contribute',
        'offer-contribution',
        'What could your classmates learn from working with you?',
        '说可贡献的经验或技能。',
        'drawing',
        'I enjoy drawing, so I could show ideas that are hard to explain.',
        'listening',
        'I am a careful listener and could help a partner organise a story.',
        {
          state: 'model-reviewed',
          record: 'study-review.md: class-introduction.B1.contribute',
        },
      ],
      [
        'privacy',
        'set-privacy',
        'How would you handle a class question that feels too personal?',
        '给出自然的边界表达。',
        'fiction',
        'I would ask whether I could use an invented example.',
        'skip',
        'I would politely say I prefer to skip that question.',
        {
          state: 'model-reviewed',
          record: 'study-review.md: class-introduction.B1.privacy',
        },
      ],
      [
        'next',
        'choose-next-step',
        'What would be a useful first step after this introduction?',
        '选择尚未发生的行动。',
        'pair',
        'I would like to try a short conversation with a partner.',
        'plan',
        'I would like to write down one speaking goal first.',
        {
          state: 'model-reviewed',
          record: 'study-review.md: class-introduction.B1.next',
        },
      ],
      [
        'pace',
        'request-pace',
        'What should I change about the way I am giving these instructions?',
        '可指出具体支持，也可说无需改变。',
        'pause',
        'Could you pause between the steps so I can make a note?',
        'fine',
        'The pace works for me; I can follow the steps.',
        {
          state: 'model-reviewed',
          record: 'study-review.md: class-introduction.B1.pace',
        },
      ],
      [
        'question',
        'ask-class-information',
        'What would you like to check about feedback in this class?',
        '提出关于反馈的新问题。',
        'when',
        'Will we get feedback during the activity or afterwards?',
        'who',
        'Can we ask a partner for feedback as well as the teacher?',
        {
          state: 'model-reviewed',
          record: 'study-review.md: class-introduction.B1.question',
        },
      ],
    ],
    variantRead.B1,
  ),
  B2: studyPack(
    scene,
    'B2',
    {
      canDoZh: '比较参与方式，解释学习策略与合作反馈的取舍。',
      complexityZh: '面对不同经验同学协商支持，不把流利度等同理解。',
      scaffoldingZh: '固定材料和明确首次活动，答案展示理由及条件。',
      registerZh: '坦诚而有分寸的课堂协商，尊重他人的发言空间。',
    },
    [
      [
        'name',
        'give-name',
        'How would you like to introduce yourself without making the introduction too formal?',
        '用适合新班的方式给出称呼。',
        'mei',
        'I am Mei. Please use my first name; there is no need for anything formal.',
        'leo',
        'I go by Leo in class, though you may see a different name on the register.',
        {
          state: 'model-reviewed',
          record: 'study-review.md: class-introduction.B2.name',
        },
      ],
      [
        'experience',
        'describe-experience',
        'Which part of your previous learning has prepared you for this class, and which part has not?',
        '比较已有能力与经验缺口。',
        'reading',
        'Reading has given me a useful vocabulary, but I have rarely had to respond on the spot.',
        'practice',
        'Conversation practice has made me confident, although I sometimes miss details in longer explanations.',
        {
          state: 'model-reviewed',
          record: 'study-review.md: class-introduction.B2.experience',
        },
      ],
      [
        'interest',
        'choose-material',
        'Which of the available materials would encourage more than a description from you?',
        '说明材料怎样引发进一步交流。',
        'picture',
        'A picture could lead us to compare interpretations instead of just naming objects.',
        'story',
        'A story could prompt a discussion about why a character made a particular choice.',
        {
          state: 'model-reviewed',
          record: 'study-review.md: class-introduction.B2.interest',
        },
      ],
      [
        'goal',
        'state-goal',
        'What speaking goal would be challenging but realistic for you?',
        '提出有边界的进步目标。',
        'disagree',
        'I would like to disagree clearly while still showing that I have understood the other view.',
        'summarise',
        'I want to summarise a discussion accurately without trying to repeat every sentence.',
        {
          state: 'model-reviewed',
          record: 'study-review.md: class-introduction.B2.goal',
        },
      ],
      [
        'support',
        'request-support',
        'How could I support your first attempt without taking over?',
        '区分辅助与替代发言。',
        'prompt',
        'A brief prompt would be useful, provided I still get to finish the explanation myself.',
        'later',
        'I would rather finish with imperfect wording and discuss alternatives afterwards.',
        {
          state: 'model-reviewed',
          record: 'study-review.md: class-introduction.B2.support',
        },
      ],
      [
        'partner',
        'choose-partner-format',
        'How could a pair with different speaking experience share the time fairly?',
        '提出具体合作安排。',
        'turns',
        'We could take timed turns so the more confident speaker does not fill every silence.',
        'roles',
        'We could alternate between explaining and asking questions, rather than letting one person lead throughout.',
        {
          state: 'model-reviewed',
          record: 'study-review.md: class-introduction.B2.partner',
        },
      ],
      [
        'resource',
        'choose-resource',
        'How would you keep a support card from becoming a script?',
        '说明准备材料的使用边界。',
        'outline',
        'I would keep only a rough outline on it, leaving the wording open.',
        'prompts',
        'I would use questions as prompts rather than writing complete answers.',
        {
          state: 'model-reviewed',
          record: 'study-review.md: class-introduction.B2.resource',
        },
      ],
      [
        'contribute',
        'offer-contribution',
        'What can you contribute while leaving room for classmates to solve problems themselves?',
        '提出帮助但不包办。',
        'visual',
        'I could sketch a difficult idea, then let the group decide how to explain it.',
        'questions',
        'I could ask focused questions instead of immediately supplying my own answer.',
        {
          state: 'model-reviewed',
          record: 'study-review.md: class-introduction.B2.contribute',
        },
      ],
      [
        'privacy',
        'set-privacy',
        'How could you participate fully without using personal experiences?',
        '不把隐私披露作为参与条件。',
        'invent',
        'I could use an invented example and make that clear at the start.',
        'public',
        'I could discuss a familiar public situation rather than my own circumstances.',
        {
          state: 'model-reviewed',
          record: 'study-review.md: class-introduction.B2.privacy',
        },
      ],
      [
        'next',
        'choose-next-step',
        'What would you suggest trying first so we can see how the class works for you?',
        '提议试行而不是断言已有效。',
        'trial',
        'A short pair task would let me try the approach before asking for changes.',
        'observe',
        'I would like to watch one example first, then take part in the next round.',
        {
          state: 'model-reviewed',
          record: 'study-review.md: class-introduction.B2.next',
        },
      ],
      [
        'pace',
        'request-pace',
        'How could I make these spoken instructions easier to retain without slowing every sentence?',
        '提供具体听说支持。',
        'signposts',
        'Could you signal each new step clearly and pause before the final one?',
        'written',
        'A short written list would help; the speaking speed itself is comfortable.',
        {
          state: 'model-reviewed',
          record: 'study-review.md: class-introduction.B2.pace',
        },
      ],
      [
        'question',
        'ask-class-information',
        'What would you want to know about how speaking progress will be discussed?',
        '核查反馈依据。',
        'criteria',
        'Which features will feedback focus on: clarity, interaction, or accuracy?',
        'choice',
        'Will we be able to choose a particular feature for feedback on a given task?',
        {
          state: 'model-reviewed',
          record: 'study-review.md: class-introduction.B2.question',
        },
      ],
    ],
    variantRead.B2,
  ),
  C1: studyPack(
    scene,
    'C1',
    {
      canDoZh: '精确界定学习需求，协调不同经验的参与者与反馈边界。',
      complexityZh: '区分可观察行为和模糊自我评价，限定干预与试行条件。',
      scaffoldingZh: '具体新班材料与角色支持复杂协商，不依赖专业课程知识。',
      registerZh:
        '自然、合作且能委婉挑战假设的师生口语；依据 CEFR 而非 BC C1。',
    },
    [
      [
        'name',
        'give-name',
        'How would you like us to address you, particularly if the register is unfamiliar?',
        '处理正式名册与日常称呼差异。',
        'mei',
        'Mei is the name I use, so please stick with that even if the register gives my full name.',
        'leo',
        'I use Leo for classes; I would be grateful if that could be the name on my card too.',
        {
          state: 'model-reviewed',
          record: 'study-review.md: class-introduction.C1.name',
        },
      ],
      [
        'experience',
        'describe-experience',
        'What might your previous experience lead us to overestimate or underestimate about your speaking?',
        '说明表现与实际经验的不一致。',
        'fluent',
        'I can sound fluent on familiar topics, but that should not be taken to mean I can follow a dense explanation without support.',
        'quiet',
        'I may be quiet at first, though that is usually because I am organising my response rather than failing to understand.',
        {
          state: 'model-reviewed',
          record: 'study-review.md: class-introduction.C1.experience',
        },
      ],
      [
        'interest',
        'choose-material',
        'Which material could open up a discussion without requiring everyone to share the same background knowledge?',
        '权衡共同入口与解释空间。',
        'picture',
        'The picture gives everyone a common starting point, while still leaving room for contrasting interpretations.',
        'story',
        'A self-contained story would work, provided the discussion stays grounded in details available to everyone.',
        {
          state: 'model-reviewed',
          record: 'study-review.md: class-introduction.C1.interest',
        },
      ],
      [
        'goal',
        'state-goal',
        'How would you turn a broad wish to sound more natural into an observable classroom goal?',
        '把笼统目标变成可观察行为。',
        'reformulate',
        'I would focus on reformulating an explanation when a listener looks uncertain, rather than simply speaking faster.',
        'respond',
        'I would aim to respond to the substance of an objection before moving on to my own point.',
        {
          state: 'model-reviewed',
          record: 'study-review.md: class-introduction.C1.goal',
        },
      ],
      [
        'support',
        'request-support',
        'Where would you draw the line between a useful prompt and an interruption that breaks your train of thought?',
        '给出具体干预边界。',
        'signal',
        'I would welcome a prompt after I signal that I am stuck, but prefer not to be supplied with words mid-sentence.',
        'meaning',
        'An interruption is worthwhile if my meaning is unclear; minor wording issues could wait until the end.',
        {
          state: 'model-reviewed',
          record: 'study-review.md: class-introduction.C1.support',
        },
      ],
      [
        'partner',
        'choose-partner-format',
        'How could we avoid treating the most fluent partner as the person responsible for every explanation?',
        '挑战流利者包办的默认安排。',
        'rotate',
        'We could rotate responsibility for explaining, with the listener checking meaning rather than taking over.',
        'prepare',
        'A minute of individual preparation would give both partners something to contribute before either starts leading.',
        {
          state: 'model-reviewed',
          record: 'study-review.md: class-introduction.C1.partner',
        },
      ],
      [
        'resource',
        'choose-resource',
        'How would you use a preparation card while remaining responsive to an unexpected question?',
        '兼顾准备与现场回应。',
        'anchors',
        'I would note the main ideas as anchors, not a sequence of sentences I feel obliged to deliver.',
        'separate',
        'I would separate essential points from optional examples, so I could drop an example when the conversation takes another direction.',
        {
          state: 'model-reviewed',
          record: 'study-review.md: class-introduction.C1.resource',
        },
      ],
      [
        'contribute',
        'offer-contribution',
        'How could your strengths benefit the group without becoming the default way everyone has to work?',
        '限定优势的使用，不替全组作决定。',
        'offer',
        'I could offer to visualise a difficult point, while leaving the group free to choose a different approach.',
        'invite',
        'I could help structure the discussion, but explicitly invite someone else to suggest a better order.',
        {
          state: 'model-reviewed',
          record: 'study-review.md: class-introduction.C1.contribute',
        },
      ],
      [
        'privacy',
        'set-privacy',
        'How would you question an activity that seems to require more personal disclosure than its language goal needs?',
        '以学习目标为依据提出隐私替代。',
        'alternative',
        'Could we use a fictional case? It would practise the same language without requiring us to disclose personal experiences.',
        'boundary',
        'I am happy to explore the topic, but I would prefer to set aside the part that asks for private family details.',
        {
          state: 'model-reviewed',
          record: 'study-review.md: class-introduction.C1.privacy',
        },
      ],
      [
        'next',
        'choose-next-step',
        'What initial trial would give us useful information without locking us into a learning arrangement?',
        '提出有边界的试行。',
        'compare',
        'We could try one short pair task and compare what each of us found helpful before settling on a routine.',
        'observe',
        'I would like to observe a demonstration, then try the same format myself before suggesting adjustments.',
        {
          state: 'model-reviewed',
          record: 'study-review.md: class-introduction.C1.next',
        },
      ],
      [
        'pace',
        'request-pace',
        'What adjustment would help you follow the structure of these instructions rather than merely hear every word?',
        '区分结构支架与逐词重复。',
        'overview',
        'A brief overview before the details would help me see how the steps fit together.',
        'transition',
        'Could you make the transition from preparation to speaking more explicit? The individual sentences are clear.',
        {
          state: 'model-reviewed',
          record: 'study-review.md: class-introduction.C1.pace',
        },
      ],
      [
        'question',
        'ask-class-information',
        'What would you ask to establish how feedback will account for the demands of different tasks?',
        '澄清反馈标准与任务条件。',
        'interaction',
        'Will a discussion be judged partly on how we respond to others, rather than only on the accuracy of our own sentences?',
        'preparation',
        'How will feedback distinguish a prepared contribution from an answer formulated under time pressure?',
        {
          state: 'model-reviewed',
          record: 'study-review.md: class-introduction.C1.question',
        },
      ],
    ],
    variantRead.C1,
  ),
}
