import { studyPack, type StudyScene, type Review } from './authoring'
const variantRead = {
  A1: {
    state: 'model-reviewed',
    record: 'study-review.md: group-project.A1 variants',
  },
  A2: {
    state: 'model-reviewed',
    record: 'study-review.md: group-project.A2 variants',
  },
  B1: {
    state: 'model-reviewed',
    record: 'study-review.md: group-project.B1 variants',
  },
  B2: {
    state: 'model-reviewed',
    record: 'study-review.md: group-project.B2 variants',
  },
  C1: {
    state: 'model-reviewed',
    record: 'study-review.md: group-project.C1 variants',
  },
} satisfies Record<string, Review>
const scene: StudyScene = {
  sceneId: 'study-03',
  slug: 'group-project',
  situations: [
    '虚构小组要做一张“班级植物角”海报，你和同学 Jo 正在准备。桌上有绿色、黄色纸、两幅植物图和空白标签。尚未选角色、写文字、调查或核查资料。A1/A2 做具体图文分工；较高级别遇到的样本数字和主张都在问题内给出，均为虚构教学材料，不是真实研究。',
    '虚构“班级植物角”小组工作坊，你和 Jo 可以先做纸上草案，另一位同学还未到。桌上有绿色、黄色纸、两幅植物图和空白标签。需要保留缺席者的参与机会并商量版本合并，尚未实际完成任何分工或检查。题内样本数据只是原创练习材料。',
  ],
  paths: [
    {
      short: ['role', 'product', 'next'],
      standard: ['role', 'product', 'share', 'resource', 'combine', 'next'],
      extended: [
        'role',
        'product',
        'share',
        'resource',
        'evidence',
        'disagree',
        'combine',
        'check',
        'credit',
        'next',
      ],
    },
    {
      short: ['role', 'absent', 'next'],
      standard: ['role', 'product', 'absent', 'version', 'combine', 'next'],
      extended: [
        'role',
        'product',
        'share',
        'absent',
        'version',
        'disagree',
        'combine',
        'check',
        'credit',
        'next',
      ],
    },
  ],
  closing:
    'The project-planning practice is complete. These are proposals, not completed work or an agreement from absent classmates.',
  partial:
    'We will stop with part of the project plan still unconfirmed. No research, checking or submission has taken place.',
  repairs: {
    clarify: 'You can ask about this part of the poster plan.',
    struggle: 'A short choice or a request for help is fine.',
    offTopic: 'We can return to planning the plant-corner poster.',
    unknown:
      'That proposal is not covered by this local answer set, so it remains unconfirmed.',
    changed: 'Your revised proposal replaces the earlier one.',
    refusedClosing:
      'We will stop planning here. No work has been assigned to you.',
  },
}
export const groupProject = {
  A1: studyPack(
    scene,
    'A1',
    {
      canDoZh: '选择海报中的具体小工作与材料，并请求简单协作。',
      complexityZh: '看图、写词、摆放、分材料；不承担证据论证或抽象管理。',
      scaffoldingZh: '实际给出的纸、图片和标签，两种可见选择。',
      registerZh: '同学之间简单合作口语，可选需要帮助的工作。',
    },
    [
      [
        'role',
        'choose-role',
        'Do you want to draw or write?',
        '选择具体分工。',
        'draw',
        'I want to draw.',
        'write',
        'I want to write.',
        {
          state: 'model-reviewed',
          record: 'study-review.md: group-project.A1.role',
        },
      ],
      [
        'product',
        'choose-product',
        'Shall we use green or yellow paper for the poster?',
        '选择桌上的海报纸。',
        'green',
        'Let us use green paper.',
        'yellow',
        'I like the yellow paper.',
        {
          state: 'model-reviewed',
          record: 'study-review.md: group-project.A1.product',
        },
      ],
      [
        'share',
        'share-materials',
        'Can we share the pictures?',
        '同意分享或说明需要先看。',
        'share',
        'Yes, we can share them.',
        'first',
        'I want to look first, please.',
        {
          state: 'model-reviewed',
          record: 'study-review.md: group-project.A1.share',
        },
      ],
      [
        'resource',
        'request-resource',
        'Do you need a blank label?',
        '选择是否需要标签。',
        'need',
        'Yes, one label, please.',
        'no',
        'No, thank you.',
        {
          state: 'model-reviewed',
          record: 'study-review.md: group-project.A1.resource',
        },
      ],
      [
        'evidence',
        'identify-source',
        'Where can we find the plant name: on a card or in a book?',
        '只选可查找的来源，不称已经查证。',
        'card',
        'We can look on a card.',
        'book',
        'We can look in a book.',
        {
          state: 'model-reviewed',
          record: 'study-review.md: group-project.A1.evidence',
        },
      ],
      [
        'disagree',
        'express-layout-preference',
        'I want the big picture at the top. Is that OK?',
        'Jo 的布局提议在此明确给出。',
        'agree',
        'Yes, the top is good.',
        'bottom',
        'I want it at the bottom.',
        {
          state: 'model-reviewed',
          record: 'study-review.md: group-project.A1.disagree',
        },
      ],
      [
        'combine',
        'combine-parts',
        'Where shall we put the words?',
        '选择文字摆放位置。',
        'under',
        'Under the pictures.',
        'next',
        'Next to the pictures.',
        {
          state: 'model-reviewed',
          record: 'study-review.md: group-project.A1.combine',
        },
      ],
      [
        'check',
        'plan-check',
        'What shall we look at before we finish?',
        '未来查看，不假设已检查过。',
        'names',
        'Let us look at the names.',
        'pictures',
        'Let us look at the pictures.',
        {
          state: 'model-reviewed',
          record: 'study-review.md: group-project.A1.check',
        },
      ],
      [
        'credit',
        'name-contributors',
        'Where shall we write our names?',
        '选择署名位置。',
        'back',
        'On the back.',
        'front',
        'At the bottom on the front.',
        {
          state: 'model-reviewed',
          record: 'study-review.md: group-project.A1.credit',
        },
      ],
      [
        'next',
        'choose-next-step',
        'Shall we start now or get the paper first?',
        '选择下一步。',
        'start',
        'Let us start now.',
        'paper',
        'Let us get the paper first.',
        {
          state: 'model-reviewed',
          record: 'study-review.md: group-project.A1.next',
        },
      ],
      [
        'absent',
        'include-absent-member',
        'Our other classmate is not here yet. Shall we leave some labels for them?',
        '给未到的同学留材料或另一个参与入口。',
        'labels',
        'Yes, leave two labels.',
        'picture',
        'Let us leave a picture for them instead.',
        {
          state: 'model-reviewed',
          record: 'study-review.md: group-project.A1.absent',
        },
      ],
      [
        'version',
        'choose-draft-place',
        'Shall we try the layout on the table or on blank paper?',
        '选择试摆位置，不算完成海报。',
        'table',
        'On the table, please.',
        'paper',
        'On blank paper, please.',
        {
          state: 'model-reviewed',
          record: 'study-review.md: group-project.A1.version',
        },
      ],
    ],
    variantRead.A1,
  ),
  A2: studyPack(
    scene,
    'A2',
    {
      canDoZh: '安排图文小任务，说明材料需要并为未到同学留位置。',
      complexityZh: '熟悉海报制作中的两三步安排和简单意见差异。',
      scaffoldingZh: '已有具体图纸材料，答案给出简短理由。',
      registerZh: '平等礼貌地提议与不同意，不默认他人同意。',
    },
    [
      [
        'role',
        'choose-role',
        'Which part of the poster would you like to do?',
        '选择可做的一项。',
        'pictures',
        'I would like to draw the plant pictures.',
        'labels',
        'I would like to write the labels.',
        {
          state: 'model-reviewed',
          record: 'study-review.md: group-project.A2.role',
        },
      ],
      [
        'product',
        'choose-product',
        'Would you prefer a poster with large pictures or more small pictures?',
        '选择信息呈现形式。',
        'large',
        'Large pictures would be easy to see.',
        'small',
        'More small pictures would show different plants.',
        {
          state: 'model-reviewed',
          record: 'study-review.md: group-project.A2.product',
        },
      ],
      [
        'share',
        'share-materials',
        'How can we use the two plant pictures fairly?',
        '提出材料共享方案。',
        'each',
        'We can take one picture each.',
        'together',
        'We can look at both pictures together.',
        {
          state: 'model-reviewed',
          record: 'study-review.md: group-project.A2.share',
        },
      ],
      [
        'resource',
        'request-resource',
        'What else do you need before working on your part?',
        '说明准备缺口。',
        'pencil',
        'I need a pencil to make a rough plan.',
        'nothing',
        'I have what I need and can begin.',
        {
          state: 'model-reviewed',
          record: 'study-review.md: group-project.A2.resource',
        },
      ],
      [
        'evidence',
        'identify-source',
        'How could we check a plant name we do not know?',
        '提出查询，不虚构结果。',
        'book',
        'We could look for it in a plant book.',
        'teacher',
        'We could ask the teacher to help us find it.',
        {
          state: 'model-reviewed',
          record: 'study-review.md: group-project.A2.evidence',
        },
      ],
      [
        'disagree',
        'express-layout-preference',
        'Jo suggests putting every picture close together. What do you think?',
        '针对新给出的布局提议。',
        'space',
        'I would leave some space so the poster is easier to read.',
        'together',
        'I like that idea because the pictures will look like a garden.',
        {
          state: 'model-reviewed',
          record: 'study-review.md: group-project.A2.disagree',
        },
      ],
      [
        'combine',
        'combine-parts',
        'How shall we put our separate parts together?',
        '安排合并流程。',
        'lay',
        'Let us lay everything on the table before we stick it down.',
        'outline',
        'We could draw boxes first and put each part in a box.',
        {
          state: 'model-reviewed',
          record: 'study-review.md: group-project.A2.combine',
        },
      ],
      [
        'check',
        'plan-check',
        'What should we check before showing the poster to the class?',
        '计划尚未发生的检查。',
        'spelling',
        'We should check the spelling of the plant names.',
        'view',
        'We should see if the words are big enough to read.',
        {
          state: 'model-reviewed',
          record: 'study-review.md: group-project.A2.check',
        },
      ],
      [
        'credit',
        'name-contributors',
        'How would you like to show who contributes to the poster?',
        '选择未来署名形式，不声称已经制作。',
        'names',
        'We could put all our names along the bottom.',
        'parts',
        'We could write our names beside the parts we make.',
        {
          state: 'model-reviewed',
          record: 'study-review.md: group-project.A2.credit',
        },
      ],
      [
        'next',
        'choose-next-step',
        'What should we do as soon as this planning chat ends?',
        '下一步只为提议，不假定还缺材料。',
        'materials',
        'Let us check that we have all the materials.',
        'rough',
        'Let us make a rough version first.',
        {
          state: 'model-reviewed',
          record: 'study-review.md: group-project.A2.next',
        },
      ],
      [
        'absent',
        'include-absent-member',
        'How can the classmate who arrives later still join in?',
        '不替缺席者确定角色。',
        'choose',
        'We can leave two small jobs for them to choose from.',
        'ask',
        'We can ask what they would like to add when they arrive.',
        {
          state: 'model-reviewed',
          record: 'study-review.md: group-project.A2.absent',
        },
      ],
      [
        'version',
        'choose-draft-place',
        'How can we remember a layout before moving the pieces?',
        '选择版本记录方式。',
        'draw',
        'We can draw a quick copy on spare paper.',
        'numbers',
        'We can number the pieces and write down their places.',
        {
          state: 'model-reviewed',
          record: 'study-review.md: group-project.A2.version',
        },
      ],
    ],
    variantRead.A2,
  ),
  B1: studyPack(
    scene,
    'B1',
    {
      canDoZh: '协商职责、合并方式与信息检查，照顾未到成员。',
      complexityZh: '说明简单因果，预防文字与图画冲突，不声称已完成调查。',
      scaffoldingZh: '小海报任务及完整给出的虚构意见。',
      registerZh: '合作、可调整的同伴交流；角色不是不可更改的承诺。',
    },
    [
      [
        'role',
        'choose-role',
        'Which responsibility would suit you, and why?',
        '把任务和能力联系起来。',
        'visual',
        'I could organise the pictures because I enjoy working on layouts.',
        'text',
        'I could draft the labels because I am comfortable explaining things briefly.',
        {
          state: 'model-reviewed',
          record: 'study-review.md: group-project.B1.role',
        },
      ],
      [
        'product',
        'choose-product',
        'Who should the plant-corner poster mainly help?',
        '选择目标读者，后文不假定已选特定人群。',
        'new',
        'It should help new students find their way around the plant corner.',
        'carers',
        'It should help classmates remember the jobs involved in looking after it.',
        {
          state: 'model-reviewed',
          record: 'study-review.md: group-project.B1.product',
        },
      ],
      [
        'share',
        'share-work',
        'How could we divide the work without losing track of the whole poster?',
        '提出协作而非孤立分工。',
        'outline',
        'We could agree on a rough outline before working on separate parts.',
        'checkin',
        'We could work separately at first and have a short check-in before combining anything.',
        {
          state: 'model-reviewed',
          record: 'study-review.md: group-project.B1.share',
        },
      ],
      [
        'resource',
        'request-resource',
        'What information is missing before we can write reliable labels?',
        '定位信息缺口。',
        'names',
        'We need to confirm the names of the plants rather than guess from the pictures.',
        'care',
        'We need a reliable source for the care instructions before adding them.',
        {
          state: 'model-reviewed',
          record: 'study-review.md: group-project.B1.resource',
        },
      ],
      [
        'evidence',
        'identify-source',
        'Jo has written “All plants need the same amount of water”. How should we handle that line?',
        '具体不可靠主张已给出，不提供植物护理建议。',
        'check',
        'We should check that claim in a suitable source before using it.',
        'remove',
        'We should leave it out for now because we have not established that it is true.',
        {
          state: 'model-reviewed',
          record: 'study-review.md: group-project.B1.evidence',
        },
      ],
      [
        'disagree',
        'express-layout-preference',
        'Jo wants to fill every empty space with text. How would you respond?',
        '友好不同意或有条件支持。',
        'less',
        'I think fewer words would make the main information easier to find.',
        'sections',
        'We could include more text if we divide it into clearly labelled sections.',
        {
          state: 'model-reviewed',
          record: 'study-review.md: group-project.B1.disagree',
        },
      ],
      [
        'combine',
        'combine-parts',
        'How would you combine the text and pictures if they do not fit?',
        '未来假设，未声称已做完。',
        'shorten',
        'I would shorten repeated wording before making the text smaller.',
        'move',
        'I would try a different arrangement before cutting useful information.',
        {
          state: 'model-reviewed',
          record: 'study-review.md: group-project.B1.combine',
        },
      ],
      [
        'check',
        'plan-check',
        'How could we find out whether a classmate can use the poster easily?',
        '提出尚未发生的检查。',
        'find',
        'We could ask someone to find one piece of information and watch where they look.',
        'explain',
        'We could ask someone to explain the poster’s main point in their own words.',
        {
          state: 'model-reviewed',
          record: 'study-review.md: group-project.B1.check',
        },
      ],
      [
        'credit',
        'name-contributors',
        'How should we describe each person’s contribution fairly?',
        '可署名，不虚构真实贡献已经发生。',
        'record',
        'We could keep a short note of who does each part as we work.',
        'review',
        'We could review the contributions together before adding names.',
        {
          state: 'model-reviewed',
          record: 'study-review.md: group-project.B1.credit',
        },
      ],
      [
        'next',
        'choose-next-step',
        'What would move the project forward after this discussion?',
        '具体可执行的下一步。',
        'outline',
        'We could sketch the overall layout before making a final version.',
        'information',
        'We could find information about the plants and keep the sources with our notes.',
        {
          state: 'model-reviewed',
          record: 'study-review.md: group-project.B1.next',
        },
      ],
      [
        'absent',
        'include-absent-member',
        'What should remain open until our absent classmate can contribute?',
        '保留真实参与空间。',
        'role',
        'We should leave their role open instead of assigning one without asking.',
        'content',
        'We could leave room for an additional idea rather than finalising every section.',
        {
          state: 'model-reviewed',
          record: 'study-review.md: group-project.B1.absent',
        },
      ],
      [
        'version',
        'manage-version',
        'How could we prevent two different drafts from being mistaken for the final poster?',
        '提出版本管理。',
        'label',
        'We could label each draft clearly and keep the final version in one place.',
        'owner',
        'We could ask one person to combine changes after everyone has seen them.',
        {
          state: 'model-reviewed',
          record: 'study-review.md: group-project.B1.version',
        },
      ],
    ],
    variantRead.B1,
  ),
  B2: studyPack(
    scene,
    'B2',
    {
      canDoZh: '协调角色与质量标准，质疑未经支持的海报主张。',
      complexityZh: '权衡读者需要、证据范围与合并成本，安排可核查流程。',
      scaffoldingZh: '完整小组设定和题内数据，不需外部课程或真实调查。',
      registerZh: '有依据的同伴协商和建设性异议。',
    },
    [
      [
        'role',
        'choose-role',
        'Which responsibility would you take on without becoming the person who has to fix everything?',
        '明确责任边界。',
        'layout',
        'I can coordinate the layout, but each contributor should check the accuracy of their own text.',
        'sources',
        'I can keep track of sources, provided the group helps locate the information rather than leaving all the research to me.',
        {
          state: 'model-reviewed',
          record: 'study-review.md: group-project.B2.role',
        },
      ],
      [
        'product',
        'choose-product',
        'What should determine which information earns space on the poster?',
        '提出选择标准。',
        'use',
        'I would prioritise information a visitor can act on over background details that are merely interesting.',
        'purpose',
        'I would keep information that serves the agreed purpose and move optional detail to a separate note.',
        {
          state: 'model-reviewed',
          record: 'study-review.md: group-project.B2.product',
        },
      ],
      [
        'share',
        'share-work',
        'How could we divide tasks of different sizes fairly?',
        '处理工作量而非只数任务。',
        'estimate',
        'We could estimate the effort involved and rebalance the tasks once we see what each requires.',
        'support',
        'We could pair a large task with help from another member instead of pretending all tasks are equal.',
        {
          state: 'model-reviewed',
          record: 'study-review.md: group-project.B2.share',
        },
      ],
      [
        'resource',
        'request-resource',
        'What would you check before using a source suggested by a teammate?',
        '定位资料质量判断。',
        'relevance',
        'I would check whether it actually addresses the plants and conditions shown on our poster.',
        'origin',
        'I would check where the information comes from and whether we can trace the original source.',
        {
          state: 'model-reviewed',
          record: 'study-review.md: group-project.B2.resource',
        },
      ],
      [
        'evidence',
        'evaluate-evidence',
        'In a fictional class poll, eight of twelve respondents want more plants. What could the poster fairly say?',
        '数字为虚构，只表达有限范围。',
        'count',
        'It could state that eight of the twelve respondents supported adding plants.',
        'question',
        'It could present the result as a reason to ask the rest of the class, rather than claim a class-wide decision.',
        {
          state: 'model-reviewed',
          record: 'study-review.md: group-project.B2.evidence',
        },
      ],
      [
        'disagree',
        'express-content-disagreement',
        'Jo proposes the heading “Everyone wants a greener classroom”. How would you respond?',
        '独立给出主张，无论是否经过民调题都可答。',
        'qualify',
        '“Everyone” is too strong unless every classmate has agreed; I would use a heading that invites views instead.',
        'separate',
        'We can argue for a greener classroom, but we should not present our preference as everyone else’s position.',
        {
          state: 'model-reviewed',
          record: 'study-review.md: group-project.B2.disagree',
        },
      ],
      [
        'combine',
        'combine-parts',
        'How should we handle two sections that make the same point in different words?',
        '合并时保护信息和成员意见。',
        'merge',
        'We could merge them and retain the clearest example from each.',
        'purpose',
        'We should first check whether they serve different readers; if so, repetition may have a purpose.',
        {
          state: 'model-reviewed',
          record: 'study-review.md: group-project.B2.combine',
        },
      ],
      [
        'check',
        'plan-check',
        'What would make a trial reading of the poster informative rather than just a request for praise?',
        '规划真实可观察的检查。',
        'task',
        'We could give the reader a specific information-finding task and note where they hesitate.',
        'misread',
        'We could ask what the poster seems to promise, so we can spot unintended claims.',
        {
          state: 'model-reviewed',
          record: 'study-review.md: group-project.B2.check',
        },
      ],
      [
        'credit',
        'name-contributors',
        'How could we acknowledge contributions that are less visible than the final drawing or text?',
        '考虑资料整理等实际参与。',
        'log',
        'We could record checking and organising work alongside the visible sections.',
        'discussion',
        'We could discuss contributions together rather than infer them from whose name appears on a file.',
        {
          state: 'model-reviewed',
          record: 'study-review.md: group-project.B2.credit',
        },
      ],
      [
        'next',
        'choose-next-step',
        'Which next step would reduce the greatest uncertainty in the project?',
        '选择有理由的下一步，不预设已经发现错误资料。',
        'sources',
        'I would check whether the source material is reliable before spending time polishing the design.',
        'mockup',
        'I would build a rough mock-up to see whether the proposed content can actually fit.',
        {
          state: 'model-reviewed',
          record: 'study-review.md: group-project.B2.next',
        },
      ],
      [
        'absent',
        'include-absent-member',
        'What can we reasonably decide while a group member is absent?',
        '限定临时决定。',
        'reversible',
        'We can make reversible layout choices, but should leave their role and contribution open.',
        'options',
        'We can prepare options for discussion without presenting one as an agreement already reached.',
        {
          state: 'model-reviewed',
          record: 'study-review.md: group-project.B2.absent',
        },
      ],
      [
        'version',
        'manage-version',
        'How should changes be handled once the separate sections have been combined?',
        '提出后续修改流程。',
        'log',
        'We could note each proposed change and its reason before updating the shared version.',
        'review',
        'We could have another member review changes that affect a factual claim, while leaving minor layout edits to the coordinator.',
        {
          state: 'model-reviewed',
          record: 'study-review.md: group-project.B2.version',
        },
      ],
    ],
    variantRead.B2,
  ),
  C1: studyPack(
    scene,
    'C1',
    {
      canDoZh: '界定协作责任与证据边界，调和贡献、公平与决策权限。',
      complexityZh: '区分提案、调查和共同决定，处理贡献不可见及反例。',
      scaffoldingZh: '题内完整主张和有限虚构数据；可推理而无需专业植物知识。',
      registerZh: '有分寸地质疑集体假设并提出可修订方案。',
    },
    [
      [
        'role',
        'choose-role',
        'How would you define a coordinating role so it carries responsibility without giving one person control of everyone’s work?',
        '区分协调与单方定稿。',
        'process',
        'I could coordinate the process and flag inconsistencies, but substantive changes should go back to the person responsible for that section.',
        'integration',
        'I could integrate the sections, provided the group agrees which decisions I can make and which need joint review.',
        {
          state: 'model-reviewed',
          record: 'study-review.md: group-project.C1.role',
        },
      ],
      [
        'product',
        'choose-product',
        'How would you resolve tension between making the poster persuasive and keeping its claims proportionate?',
        '处理说服力与证据强度。',
        'distinguish',
        'I would distinguish our proposal from the evidence supporting it, so a strong invitation does not turn into an overstated finding.',
        'narrow',
        'I would rather make a narrower claim convincingly than use an eye-catching heading we cannot defend.',
        {
          state: 'model-reviewed',
          record: 'study-review.md: group-project.C1.product',
        },
      ],
      [
        'share',
        'share-work',
        'What would a fair division of work need to recognise beyond the number of assigned tasks?',
        '考虑难度与不可见协调。',
        'effort',
        'It should account for uncertainty and revision effort; a short section can require more investigation than a large illustration.',
        'invisible',
        'It should recognise coordination and checking, which can consume time without producing a separate visible section.',
        {
          state: 'model-reviewed',
          record: 'study-review.md: group-project.C1.share',
        },
      ],
      [
        'resource',
        'request-resource',
        'Two proposed sources give conflicting plant-care statements. What would you investigate before choosing one?',
        '不自行给护理结论，提出核查因素。',
        'conditions',
        'I would check whether the statements concern different species or conditions before treating them as a direct contradiction.',
        'basis',
        'I would trace the basis of each statement rather than favour the source with the more confident wording.',
        {
          state: 'model-reviewed',
          record: 'study-review.md: group-project.C1.resource',
        },
      ],
      [
        'evidence',
        'evaluate-evidence',
        'A fictional poll has eight supporters among twelve volunteers, with twenty classmates not responding. How would you frame the finding?',
        '题内样本与未答者已给出。',
        'respondents',
        'Support was common among the volunteers who responded, but the non-response prevents us from treating that as the class’s settled view.',
        'distribution',
        'I would report the response numbers explicitly and leave the preferences of the twenty non-respondents undetermined.',
        {
          state: 'model-reviewed',
          record: 'study-review.md: group-project.C1.evidence',
        },
      ],
      [
        'disagree',
        'express-content-disagreement',
        'Jo argues that “a confident headline matters more than a caveat”. How would you challenge that assumption?',
        '引用具体同伴观点并回应其核心。',
        'trust',
        'A headline may attract attention, but if it overstates the case, a caveat below it is unlikely to repair the loss of trust.',
        'alternative',
        'We do not have to choose between confidence and precision; we can state the proposal firmly without presenting uncertain support as fact.',
        {
          state: 'model-reviewed',
          record: 'study-review.md: group-project.C1.disagree',
        },
      ],
      [
        'combine',
        'combine-parts',
        'How would you handle a conflict between two sections without quietly rewriting one contributor’s argument?',
        '维护作者参与的合并方案。',
        'surface',
        'I would make the conflict explicit and ask the contributors to agree on the distinction they intended.',
        'options',
        'I would propose alternative ways of integrating the sections and explain what each would preserve or lose.',
        {
          state: 'model-reviewed',
          record: 'study-review.md: group-project.C1.combine',
        },
      ],
      [
        'check',
        'plan-check',
        'How could a trial reader reveal a weakness that the authors are likely to overlook?',
        '规划未发生的读者检查。',
        'assumptions',
        'We could ask the reader to identify what background knowledge the poster assumes, without supplying that knowledge ourselves.',
        'inference',
        'We could ask what conclusion they draw from the headline before they read the small print, then compare it with our intended claim.',
        {
          state: 'model-reviewed',
          record: 'study-review.md: group-project.C1.check',
        },
      ],
      [
        'credit',
        'name-contributors',
        'How would you make the contribution record fair without turning every small action into a competition?',
        '兼顾可见性与合作气氛。',
        'categories',
        'I would record broad responsibilities and substantial support, then let members correct omissions together.',
        'purpose',
        'I would agree that the record is for acknowledging work, not ranking people, and include shared contributions where individual attribution would be artificial.',
        {
          state: 'model-reviewed',
          record: 'study-review.md: group-project.C1.credit',
        },
      ],
      [
        'next',
        'choose-next-step',
        'What would you make provisional at this stage, and what would you resolve before polishing the poster?',
        '选择需先解决的关键不确定性。',
        'claims',
        'I would keep the layout provisional and settle the scope of the claims first, since that may change how much explanation we need.',
        'audience',
        'I would resolve the intended audience before refining the wording, while leaving colour and placement open to revision.',
        {
          state: 'model-reviewed',
          record: 'study-review.md: group-project.C1.next',
        },
      ],
      [
        'absent',
        'include-absent-member',
        'How can we make progress without later treating an absent member’s silence as consent?',
        '不把未回应算共同同意。',
        'label',
        'We can label the decisions as provisional and explicitly invite objections when the member returns.',
        'reserve',
        'We can work on agreed preparation while reserving any decision that would commit the absent member to a role or position.',
        {
          state: 'model-reviewed',
          record: 'study-review.md: group-project.C1.absent',
        },
      ],
      [
        'version',
        'manage-version',
        'How would you preserve a clear final version without erasing the reasoning behind important changes?',
        '版本管理兼顾可读性与可追溯性。',
        'summary',
        'I would keep one working version with a brief decision log for changes to claims, rather than retain every formatting experiment.',
        'archive',
        'I would archive a reviewed draft at each substantive milestone and record why the next version departs from it.',
        {
          state: 'model-reviewed',
          record: 'study-review.md: group-project.C1.version',
        },
      ],
    ],
    variantRead.C1,
  ),
}
