import { studyPack, type StudyScene, type Review } from './authoring'
const variantRead = {
  A1: {
    state: 'model-reviewed',
    record: 'study-review.md: office-hours.A1 variants',
  },
  A2: {
    state: 'model-reviewed',
    record: 'study-review.md: office-hours.A2 variants',
  },
  B1: {
    state: 'model-reviewed',
    record: 'study-review.md: office-hours.B1 variants',
  },
  B2: {
    state: 'model-reviewed',
    record: 'study-review.md: office-hours.B2 variants',
  },
  C1: {
    state: 'model-reviewed',
    record: 'study-review.md: office-hours.C1 variants',
  },
} satisfies Record<string, Review>
const scene: StudyScene = {
  sceneId: 'study-06',
  slug: 'office-hours',
  situations: [
    '虚构课后咨询，老师 Lee 和你看一张写作练习纸。纸上两句：“The garden is small. It has two trees.” 另有一幅花园图。你尚未收到任何批改或额外辅导承诺，咨询用于确定学习重点和准备后续尝试。更高级问题会当场给出独立样例或虚构反馈，不要求真实论文、成绩或外部资料。',
    '虚构课后咨询的自主练习安排环节。老师 Lee 和你有练习纸与花园图，纸上全文：“The garden is small. It has two trees.” 老师希望了解你需要怎样的反馈，以及没有即时帮助时如何继续；没有假设你已完成修改或老师已答应后续联系。新增例子均为题内原创材料。',
  ],
  paths: [
    {
      short: ['aim', 'priority', 'next'],
      standard: ['aim', 'sample', 'priority', 'feedback', 'practice', 'next'],
      extended: [
        'aim',
        'sample',
        'priority',
        'feedback',
        'diagnose',
        'strategy',
        'practice',
        'check',
        'support',
        'next',
      ],
    },
    {
      short: ['aim', 'access', 'next'],
      standard: ['aim', 'sample', 'access', 'record', 'practice', 'next'],
      extended: [
        'aim',
        'sample',
        'access',
        'record',
        'diagnose',
        'strategy',
        'practice',
        'check',
        'support',
        'next',
      ],
    },
  ],
  closing:
    'The office-hours practice is complete. A learning plan is not a completed revision, a grade or a promise of further tutoring.',
  partial:
    'We will stop with some learning priorities unconfirmed. No revision or follow-up appointment has been completed.',
  repairs: {
    clarify: 'You can ask about this part of the learning plan.',
    struggle: 'You can name one difficulty or use a short example answer.',
    offTopic:
      'We can return to your writing practice and the support you need.',
    unknown:
      'I have not matched that wording or inferred a learning diagnosis.',
    changed: 'Your new learning-plan choice replaces the earlier one.',
    refusedClosing:
      'We will end the consultation practice here. No additional work or appointment is assumed.',
  },
}
export const officeHours = {
  A1: studyPack(
    scene,
    'A1',
    {
      canDoZh: '指出练习纸上的具体困难，选择阅读或写作小目标。',
      complexityZh: '一词一句的查看、工具选择和未来练习，不要求诊断抽象弱点。',
      scaffoldingZh: '短文和图画全部给出，短问句与直接双选答。',
      registerZh: '简单礼貌的老师咨询，可以请求帮助或独立尝试。',
    },
    [
      [
        'aim',
        'state-consultation-aim',
        'Do you want help with reading or writing today?',
        '选择咨询重点。',
        'reading',
        'Reading, please.',
        'writing',
        'I want help with writing.',
        {
          state: 'model-reviewed',
          record: 'study-review.md: office-hours.A1.aim',
        },
      ],
      [
        'sample',
        'choose-sample',
        'Shall we look at the words or the garden picture first?',
        '选择已给材料。',
        'words',
        'The words first, please.',
        'picture',
        'Let us look at the picture.',
        {
          state: 'model-reviewed',
          record: 'study-review.md: office-hours.A1.sample',
        },
      ],
      [
        'priority',
        'set-priority',
        'Which word is hard: garden or trees?',
        '指出具体词。',
        'garden',
        'Garden is hard for me.',
        'trees',
        'I need help with trees.',
        {
          state: 'model-reviewed',
          record: 'study-review.md: office-hours.A1.priority',
        },
      ],
      [
        'feedback',
        'request-feedback',
        'Do you want me to read a sentence or point to a word?',
        '选择支持形式。',
        'read',
        'Please read a sentence.',
        'point',
        'Please point to a word.',
        {
          state: 'model-reviewed',
          record: 'study-review.md: office-hours.A1.feedback',
        },
      ],
      [
        'diagnose',
        'locate-difficulty',
        'Can you see the words clearly?',
        '具体可见问题，不自动诊断能力。',
        'yes',
        'Yes, I can see them.',
        'bigger',
        'No. Bigger words, please.',
        {
          state: 'model-reviewed',
          record: 'study-review.md: office-hours.A1.diagnose',
        },
      ],
      [
        'strategy',
        'choose-strategy',
        'Do you want to say a word or write it first?',
        '选择学习步骤。',
        'say',
        'I want to say it first.',
        'write',
        'I want to write it first.',
        {
          state: 'model-reviewed',
          record: 'study-review.md: office-hours.A1.strategy',
        },
      ],
      [
        'practice',
        'choose-practice',
        'What can you practise after this chat?',
        '未来活动与已完成区分。',
        'read',
        'I can read the two sentences.',
        'draw',
        'I can draw a garden and write a word.',
        {
          state: 'model-reviewed',
          record: 'study-review.md: office-hours.A1.practice',
        },
      ],
      [
        'check',
        'plan-self-check',
        'How can you check a word later?',
        '尚未检查，使用已给练习纸或询问。',
        'sheet',
        'I can look at this sheet.',
        'ask',
        'I can ask my teacher.',
        {
          state: 'model-reviewed',
          record: 'study-review.md: office-hours.A1.check',
        },
      ],
      [
        'support',
        'request-support',
        'Do you want to take a copy of the picture?',
        '可接受也可拒绝辅助物。',
        'yes',
        'Yes, a copy, please.',
        'no',
        'No, thank you. I have my notes.',
        {
          state: 'model-reviewed',
          record: 'study-review.md: office-hours.A1.support',
        },
      ],
      [
        'next',
        'choose-next-step',
        'Will you put the sheet in your bag or keep it on the desk?',
        '具体结束后动作。',
        'bag',
        'I will put it in my bag.',
        'desk',
        'I will keep it on the desk.',
        {
          state: 'model-reviewed',
          record: 'study-review.md: office-hours.A1.next',
        },
      ],
      [
        'access',
        'choose-independent-access',
        'Do you have paper for practice at home?',
        '可说明没有资源。',
        'have',
        'Yes, I have paper.',
        'need',
        'No, I need some paper.',
        {
          state: 'model-reviewed',
          record: 'study-review.md: office-hours.A1.access',
        },
      ],
      [
        'record',
        'choose-record',
        'Will you write a word or draw a picture in your notes?',
        '简单记录选择。',
        'word',
        'I will write a word.',
        'picture',
        'I will draw a picture.',
        {
          state: 'model-reviewed',
          record: 'study-review.md: office-hours.A1.record',
        },
      ],
    ],
    variantRead.A1,
  ),
  A2: studyPack(
    scene,
    'A2',
    {
      canDoZh: '说明写作困难，安排短练习并选择可用支持。',
      complexityZh: '围绕现有两句短文做可预测的咨询，给一个简单理由。',
      scaffoldingZh: '完整例文、熟悉图画和明确提示，不靠未给反馈。',
      registerZh: '直接礼貌的咨询，承认资源缺口和未知。',
    },
    [
      [
        'aim',
        'state-consultation-aim',
        'What would you like to work on in this short meeting?',
        '选择实质学习重点。',
        'understand',
        'I would like to understand the sentences on this sheet.',
        'own',
        'I want to write a short description of my own.',
        {
          state: 'model-reviewed',
          record: 'study-review.md: office-hours.A2.aim',
        },
      ],
      [
        'sample',
        'choose-sample',
        'Which part of the sample should we start with?',
        '用已给短文明确指向。',
        'first',
        'Let us start with “The garden is small.”',
        'second',
        'I would like to look at the sentence about the trees.',
        {
          state: 'model-reviewed',
          record: 'study-review.md: office-hours.A2.sample',
        },
      ],
      [
        'priority',
        'set-priority',
        'What is most difficult when you describe a picture?',
        '指出具体困难。',
        'words',
        'Finding the right words is difficult for me.',
        'order',
        'I know some words, but I need help putting them in order.',
        {
          state: 'model-reviewed',
          record: 'study-review.md: office-hours.A2.priority',
        },
      ],
      [
        'feedback',
        'request-feedback',
        'How would you like me to help with a first attempt?',
        '只提出帮助请求，不称已纠正。',
        'example',
        'Please show me one example before I try.',
        'after',
        'I would like to try first and ask you afterwards.',
        {
          state: 'model-reviewed',
          record: 'study-review.md: office-hours.A2.feedback',
        },
      ],
      [
        'diagnose',
        'locate-difficulty',
        'Look at “It has two trees.” Which part would you like explained?',
        '定位题内例句的问题。',
        'it',
        'What does “it” mean here?',
        'has',
        'Why do we use “has” in this sentence?',
        {
          state: 'model-reviewed',
          record: 'study-review.md: office-hours.A2.diagnose',
        },
      ],
      [
        'strategy',
        'choose-strategy',
        'What could help you find words for a new picture?',
        '具体词汇策略。',
        'list',
        'I could make a small list of things I can see.',
        'labels',
        'I could put simple labels around the picture.',
        {
          state: 'model-reviewed',
          record: 'study-review.md: office-hours.A2.strategy',
        },
      ],
      [
        'practice',
        'choose-practice',
        'Which short practice would you like to do on your own?',
        '自主练习是计划。',
        'sentence',
        'I would like to write two sentences about my room.',
        'read',
        'I would like to read the garden text aloud.',
        {
          state: 'model-reviewed',
          record: 'study-review.md: office-hours.A2.practice',
        },
      ],
      [
        'check',
        'plan-self-check',
        'What could you check in your writing before asking for help?',
        '计划自查项目。',
        'spelling',
        'I could check the spelling with my word list.',
        'fullstop',
        'I could look for a full stop at the end of each sentence.',
        {
          state: 'model-reviewed',
          record: 'study-review.md: office-hours.A2.check',
        },
      ],
      [
        'support',
        'request-support',
        'What would be useful to take away from this meeting?',
        '选择支持而非成绩承诺。',
        'example',
        'A copy of the example would be useful.',
        'words',
        'I would like a short list of useful words.',
        {
          state: 'model-reviewed',
          record: 'study-review.md: office-hours.A2.support',
        },
      ],
      [
        'next',
        'choose-next-step',
        'When would you like to try your short practice?',
        '非统一截止日期，选择个人安排。',
        'today',
        'I would like to try it later today.',
        'tomorrow',
        'Tomorrow would be better for me.',
        {
          state: 'model-reviewed',
          record: 'study-review.md: office-hours.A2.next',
        },
      ],
      [
        'access',
        'choose-independent-access',
        'Can you use a computer for your practice, or would paper be easier?',
        '允许没有电脑，不影响后续练习。',
        'computer',
        'I can use a computer at home.',
        'paper',
        'Paper would be easier because I do not have a computer.',
        {
          state: 'model-reviewed',
          record: 'study-review.md: office-hours.A2.access',
        },
      ],
      [
        'record',
        'choose-record',
        'How will you remember the main point you want to practise?',
        '记录未来重点，不假设反馈已收到。',
        'note',
        'I will write a short note on the sheet.',
        'mark',
        'I will put a star beside the part I want to practise.',
        {
          state: 'model-reviewed',
          record: 'study-review.md: office-hours.A2.record',
        },
      ],
    ],
    variantRead.A2,
  ),
  B1: studyPack(
    scene,
    'B1',
    {
      canDoZh: '描述学习困难，选择反馈并制定可自查的小练习。',
      complexityZh: '连结原因、策略与未来观察，不把咨询当诊断或修改已完成。',
      scaffoldingZh: '短文与独立例句全给出，保留没有设备的分支。',
      registerZh: '主动但不过度承诺的课后咨询口语。',
    },
    [
      [
        'aim',
        'state-consultation-aim',
        'What would make this meeting useful for you?',
        '明确咨询成果。',
        'focus',
        'I would like to leave with one clear writing priority rather than a long list of corrections.',
        'method',
        'I would like to find a way to practise describing things when I am studying alone.',
        {
          state: 'model-reviewed',
          record: 'study-review.md: office-hours.B1.aim',
        },
      ],
      [
        'sample',
        'choose-sample',
        'How would you use the garden sample to explain what you need?',
        '材料辅助定位，不声称自己的作品已被看过。',
        'compare',
        'I would compare the short sample with the kind of description I want to write.',
        'point',
        'I would point to a sentence whose structure I do not yet know how to use myself.',
        {
          state: 'model-reviewed',
          record: 'study-review.md: office-hours.B1.sample',
        },
      ],
      [
        'priority',
        'set-priority',
        'Which difficulty most often stops you from continuing a description?',
        '说明具体卡点。',
        'vocabulary',
        'I often stop because I cannot find a word, even when I know what I want to describe.',
        'linking',
        'I can write separate sentences, but connecting them into a description is harder.',
        {
          state: 'model-reviewed',
          record: 'study-review.md: office-hours.B1.priority',
        },
      ],
      [
        'feedback',
        'request-feedback',
        'What would you like feedback to focus on first?',
        '选择不同反馈标准。',
        'meaning',
        'Please focus on whether a reader can understand my description.',
        'pattern',
        'I would like to know if I keep making the same sentence-structure mistake.',
        {
          state: 'model-reviewed',
          record: 'study-review.md: office-hours.B1.feedback',
        },
      ],
      [
        'diagnose',
        'locate-difficulty',
        'In the sample, how do you know what “it” refers to?',
        '先行词已给出，也可承认缺口。',
        'garden',
        'The previous sentence names the garden, so “it” refers back to the garden.',
        'explain',
        'I know “it” refers to something earlier, but I would like help finding the exact reference.',
        {
          state: 'model-reviewed',
          record: 'study-review.md: office-hours.B1.diagnose',
        },
      ],
      [
        'strategy',
        'choose-strategy',
        'How could you keep writing when a precise word is missing?',
        '处理信息缺口。',
        'describe',
        'I could describe the object with words I already know and check the precise word later.',
        'mark',
        'I could leave a clear mark and finish the rest before returning to that word.',
        {
          state: 'model-reviewed',
          record: 'study-review.md: office-hours.B1.strategy',
        },
      ],
      [
        'practice',
        'choose-practice',
        'What small task would let you practise without copying the whole sample?',
        '提出原创迁移练习。',
        'newpicture',
        'I could describe a different picture using two or three sentences of my own.',
        'memory',
        'I could study the pattern, put the sample away and describe a familiar place from memory.',
        {
          state: 'model-reviewed',
          record: 'study-review.md: office-hours.B1.practice',
        },
      ],
      [
        'check',
        'plan-self-check',
        'How would you tell whether a first draft communicates what you intended?',
        '未来检查，不假设已完成稿件。',
        'reader',
        'I could ask a classmate to say what they picture from the description.',
        'aloud',
        'I could read it aloud and check whether each sentence adds clear information.',
        {
          state: 'model-reviewed',
          record: 'study-review.md: office-hours.B1.check',
        },
      ],
      [
        'support',
        'request-support',
        'What help would be useful if you got stuck during independent practice?',
        '提出可控支持，不默认老师随时可用。',
        'guide',
        'A short checklist would help me decide what to try before asking someone.',
        'question',
        'I could keep a specific question for the next chance to speak with a teacher.',
        {
          state: 'model-reviewed',
          record: 'study-review.md: office-hours.B1.support',
        },
      ],
      [
        'next',
        'choose-next-step',
        'What will you do first after leaving this meeting?',
        '具体下一步。',
        'choose',
        'I will choose a new picture and write a few key words.',
        'organise',
        'I will organise my notes around one practice goal.',
        {
          state: 'model-reviewed',
          record: 'study-review.md: office-hours.B1.next',
        },
      ],
      [
        'access',
        'choose-independent-access',
        'What would you do if the online exercise were unavailable?',
        '资源不可用的真实替代。',
        'paper',
        'I could use the paper sample and make a new description.',
        'offline',
        'I could read my existing notes and practise saying the sentences aloud.',
        {
          state: 'model-reviewed',
          record: 'study-review.md: office-hours.B1.access',
        },
      ],
      [
        'record',
        'choose-record',
        'How could you record a useful correction without saving only the corrected sentence?',
        '未来反馈可怎样记录，不假设本轮已给。',
        'reason',
        'I could add a short note explaining why the change is needed.',
        'own',
        'I could write a new example using the same pattern.',
        {
          state: 'model-reviewed',
          record: 'study-review.md: office-hours.B1.record',
        },
      ],
    ],
    variantRead.B1,
  ),
  B2: studyPack(
    scene,
    'B2',
    {
      canDoZh: '选择高价值反馈，分析独立样例并设计可迁移练习。',
      complexityZh: '区分局部订正与重复问题，安排缺资源情况下的自查。',
      scaffoldingZh: '完整给出样例与假设反馈，不要求真实成绩或论文。',
      registerZh: '目标明确的课后协商，对自己和老师的承诺均有限定。',
    },
    [
      [
        'aim',
        'state-consultation-aim',
        'How would you keep this consultation focused enough to be useful?',
        '界定咨询成果与范围。',
        'oneissue',
        'I would choose one recurring difficulty and leave with a way to practise it, rather than ask for every sentence to be corrected.',
        'decision',
        'I would use the time to decide which issue has the greatest effect on clarity before choosing a practice task.',
        {
          state: 'model-reviewed',
          record: 'study-review.md: office-hours.B2.aim',
        },
      ],
      [
        'sample',
        'choose-sample',
        'What would you bring to show a difficulty accurately rather than simply say your writing is weak?',
        '提出未来材料，不声称已带来或批改。',
        'versions',
        'I would bring an initial sentence and my attempted revision so the point of uncertainty is visible.',
        'contrast',
        'I would bring two examples where I made different choices and explain why I was unsure.',
        {
          state: 'model-reviewed',
          record: 'study-review.md: office-hours.B2.sample',
        },
      ],
      [
        'priority',
        'set-priority',
        'How would you choose between improving precision and making the overall description easier to follow?',
        '区分不同学习优先级。',
        'structure',
        'I would start with organisation if readers lose the main point, even when individual sentences are accurate.',
        'precision',
        'I would prioritise precision if a key word changes the meaning of an otherwise clear description.',
        {
          state: 'model-reviewed',
          record: 'study-review.md: office-hours.B2.priority',
        },
      ],
      [
        'feedback',
        'request-feedback',
        'How could feedback help you revise without making the teacher the editor of every draft?',
        '请求有边界的反馈。',
        'pattern',
        'Please explain one recurring pattern and let me look for the remaining examples myself.',
        'questions',
        'Could you give me questions to ask while revising, rather than rewrite the paragraph for me?',
        {
          state: 'model-reviewed',
          record: 'study-review.md: office-hours.B2.feedback',
        },
      ],
      [
        'diagnose',
        'locate-difficulty',
        'A separate sample says “The garden is beside the classroom. It is noisy.” What needs checking?',
        '独立新例句真正存在指代歧义。',
        'reference',
        'We need to check whether “it” refers to the garden or the classroom.',
        'intention',
        'I would ask the writer which place is noisy before choosing a revision.',
        {
          state: 'model-reviewed',
          record: 'study-review.md: office-hours.B2.diagnose',
        },
      ],
      [
        'strategy',
        'choose-strategy',
        'How would you revise that ambiguous sample once the intended place was known?',
        '条件式，不假定已确定是哪个地点。',
        'name',
        'I would repeat the intended place name if that is the clearest way to remove doubt.',
        'combine',
        'I would combine the ideas so the description of noise is attached directly to the intended place.',
        {
          state: 'model-reviewed',
          record: 'study-review.md: office-hours.B2.strategy',
        },
      ],
      [
        'practice',
        'choose-practice',
        'What practice would test whether you can make references clear in a new description?',
        '新任务而非仅抄答案。',
        'twoobjects',
        'I could describe a picture with two objects and check every pronoun against its intended reference.',
        'reader',
        'I could give a new description to someone and ask which object each sentence refers to.',
        {
          state: 'model-reviewed',
          record: 'study-review.md: office-hours.B2.practice',
        },
      ],
      [
        'check',
        'plan-self-check',
        'How would you evaluate a revision without assuming that every change improves it?',
        '未来检查与真实完成区分。',
        'compare',
        'I would compare the old and new versions against the intended meaning, not just their length.',
        'reader',
        'I would ask a reader to explain the revised meaning without first telling them what I meant.',
        {
          state: 'model-reviewed',
          record: 'study-review.md: office-hours.B2.check',
        },
      ],
      [
        'support',
        'request-support',
        'What follow-up request would be reasonable if the teacher has limited time?',
        '请求范围有边界，未获得同意。',
        'one',
        'Could you look at one example of the pattern at our next available meeting?',
        'resource',
        'Could you suggest a suitable resource for this specific issue so I can continue independently?',
        {
          state: 'model-reviewed',
          record: 'study-review.md: office-hours.B2.support',
        },
      ],
      [
        'next',
        'choose-next-step',
        'How would you turn the consultation into an achievable first action?',
        '不承诺立即解决全部问题。',
        'shorttask',
        'I would set aside a short session to try one new example and note what remains unclear.',
        'materials',
        'I would gather a few contrasting examples before choosing the one I want feedback on.',
        {
          state: 'model-reviewed',
          record: 'study-review.md: office-hours.B2.next',
        },
      ],
      [
        'access',
        'choose-independent-access',
        'How would you keep practising if you could not access the recommended digital resource?',
        '没有资源分支仍有可行动作。',
        'local',
        'I would use the local examples and make my own variations instead of waiting for access.',
        'alternative',
        'I would look for an available alternative that practises the same skill, not just any writing exercise.',
        {
          state: 'model-reviewed',
          record: 'study-review.md: office-hours.B2.access',
        },
      ],
      [
        'record',
        'choose-record',
        'What should a learning note preserve besides the final wording?',
        '记录规则或适用条件。',
        'reason',
        'It should preserve the reason for the change and the misunderstanding it prevents.',
        'limits',
        'It should note when the advice applies, so I do not turn one useful correction into a rule for every sentence.',
        {
          state: 'model-reviewed',
          record: 'study-review.md: office-hours.B2.record',
        },
      ],
    ],
    variantRead.B2,
  ),
  C1: studyPack(
    scene,
    'C1',
    {
      canDoZh:
        '协商反馈责任，区分表述问题与论证缺口，并设计验证迁移的学习步骤。',
      complexityZh: '处理模糊评价、条件与反例，不用承诺或修改动作充当成果。',
      scaffoldingZh: '独立样例和反馈原文全给出；具体咨询支持复杂话语。',
      registerZh: '精确、自主而尊重辅导边界的交流，CEFR 设计对齐而非认证。',
    },
    [
      [
        'aim',
        'state-consultation-aim',
        'What would you want this consultation to resolve that you cannot readily resolve by polishing the wording yourself?',
        '界定需要讨论的深层问题。',
        'reasoning',
        'I would like to establish whether the difficulty lies in the reasoning or only in how I have expressed it; polishing alone could conceal that distinction.',
        'priority',
        'I need help deciding which recurring issue is worth concentrating on, rather than another set of isolated sentence corrections.',
        {
          state: 'model-reviewed',
          record: 'study-review.md: office-hours.C1.aim',
        },
      ],
      [
        'sample',
        'choose-sample',
        'What material would make your uncertainty visible without asking the teacher to reconstruct your whole writing process?',
        '选择有信息量且有边界的样例。',
        'annotated',
        'I would bring a short passage with the decision point marked and explain the two options I am considering.',
        'pair',
        'I would bring an original and revised version, together with one sentence explaining what I intended the revision to achieve.',
        {
          state: 'model-reviewed',
          record: 'study-review.md: office-hours.C1.sample',
        },
      ],
      [
        'priority',
        'set-priority',
        'How would you decide whether a problem deserves immediate attention or can wait?',
        '限定优先级依据。',
        'meaning',
        'I would prioritise anything that distorts the intended claim, even if a more noticeable stylistic issue remains.',
        'recurrence',
        'I would prioritise a pattern that recurs across tasks, provided doing so does not leave the current text misleading.',
        {
          state: 'model-reviewed',
          record: 'study-review.md: office-hours.C1.priority',
        },
      ],
      [
        'feedback',
        'request-feedback',
        'How would you ask for critical feedback while retaining responsibility for the final decision?',
        '区分理解反馈与机械接受修改。',
        'effect',
        'Please explain the likely effect on a reader; I can then decide which revision best serves the purpose of the passage.',
        'options',
        'I would value a comparison of the trade-offs between the two versions rather than a replacement sentence to adopt automatically.',
        {
          state: 'model-reviewed',
          record: 'study-review.md: office-hours.C1.feedback',
        },
      ],
      [
        'diagnose',
        'locate-difficulty',
        'A separate draft says books were added to welcome visitors, then claims “Adding books made the corner welcoming” without describing reactions. What issue would you raise?',
        '已给意图但未给效果依据，独立新主张存在真实缺口。',
        'support',
        'The draft moves from an action to an effect without showing how the effect was established.',
        'definition',
        'I would ask what “welcoming” is intended to mean here before deciding what evidence would be relevant.',
        {
          state: 'model-reviewed',
          record: 'study-review.md: office-hours.C1.diagnose',
        },
      ],
      [
        'strategy',
        'choose-strategy',
        'How could that separate draft be revised without inventing the missing reactions?',
        '仅处理题内样例，不指当前已明确答案。',
        'narrow',
        'It could state that books were added with the aim of making the corner more welcoming, separating intention from demonstrated effect.',
        'remove',
        'It could remove the claim about welcoming and describe the physical change until there is a basis for evaluating the effect.',
        {
          state: 'model-reviewed',
          record: 'study-review.md: office-hours.C1.strategy',
        },
      ],
      [
        'practice',
        'choose-practice',
        'What exercise would help you distinguish observations, intentions and inferred effects in unfamiliar writing?',
        '题中明确三个类别，标准练也不依赖未给的样例。',
        'classify',
        'I could classify claims in a new paragraph as observations, intentions or inferred effects, then justify the difficult cases.',
        'rewrite',
        'I could rewrite an overclaimed result in two defensible ways and explain what evidence each version would require.',
        {
          state: 'model-reviewed',
          record: 'study-review.md: office-hours.C1.practice',
        },
      ],
      [
        'check',
        'plan-self-check',
        'How would you avoid mistaking a smoother revision for a better-supported argument?',
        '具体自查标准。',
        'trace',
        'I would trace each claim back to the information that supports it, independently of how fluent the paragraph sounds.',
        'challenge',
        'I would ask what a sceptical reader could reasonably object to in the revised version and whether the revision addresses that objection.',
        {
          state: 'model-reviewed',
          record: 'study-review.md: office-hours.C1.check',
        },
      ],
      [
        'support',
        'request-support',
        'What bounded follow-up would let the teacher see your reasoning rather than simply check another finished page?',
        '明确可控的反馈请求。',
        'decision',
        'I could bring one difficult decision with my reasons and ask whether I have identified the relevant trade-off.',
        'transfer',
        'I could bring a new example of the same issue and ask whether the principle still applies in that context.',
        {
          state: 'model-reviewed',
          record: 'study-review.md: office-hours.C1.support',
        },
      ],
      [
        'next',
        'choose-next-step',
        'What would count as a useful next action even if no further meeting were available?',
        '没有后续辅导也可自主继续，短练不依赖未给的概念对比。',
        'test',
        'I would compare a claim with its supporting information in a new passage and record the cases I cannot yet resolve.',
        'framework',
        'I would turn the questions from this discussion into a short revision checklist, keeping uncertain points clearly marked.',
        {
          state: 'model-reviewed',
          record: 'study-review.md: office-hours.C1.next',
        },
      ],
      [
        'access',
        'choose-independent-access',
        'How would you proceed if a suggested resource were unavailable and no immediate substitute had been recommended?',
        '承认资源缺失，不假装已使用。',
        'examples',
        'I would work with the examples already available and note which questions genuinely depend on additional material.',
        'request',
        'I would make a specific request for an accessible alternative while continuing the parts of the practice that do not require it.',
        {
          state: 'model-reviewed',
          record: 'study-review.md: office-hours.C1.access',
        },
      ],
      [
        'record',
        'choose-record',
        'How could your notes preserve useful uncertainty instead of turning qualified feedback into an absolute rule?',
        '记录适用边界或保留争议案例。',
        'conditions',
        'I would record the conditions under which the advice was given, alongside a case where I am unsure it applies.',
        'separate',
        'I would separate the principle I understand from the unresolved question, rather than write down a confident rule that the discussion never established.',
        {
          state: 'model-reviewed',
          record: 'study-review.md: office-hours.C1.record',
        },
      ],
    ],
    variantRead.C1,
  ),
}
