import { studyPack, type StudyScene, type Review } from './authoring'
const variantRead = {
  A1: {
    state: 'model-reviewed',
    record: 'study-review.md: presentation-qa.A1 variants',
  },
  A2: {
    state: 'model-reviewed',
    record: 'study-review.md: presentation-qa.A2 variants',
  },
  B1: {
    state: 'model-reviewed',
    record: 'study-review.md: presentation-qa.B1 variants',
  },
  B2: {
    state: 'model-reviewed',
    record: 'study-review.md: presentation-qa.B2 variants',
  },
  C1: {
    state: 'model-reviewed',
    record: 'study-review.md: presentation-qa.C1 variants',
  },
} satisfies Record<string, Review>
const scene: StudyScene = {
  sceneId: 'study-04',
  slug: 'presentation-qa',
  situations: [
    '虚构课上你刚展示一张步行上学图表，同学 Jo 正在提问。图表明确显示十名虚构学生：六人步行、四人乘公交。每个小人图形代表一名学生，分组标签为 Walk / Bus，时间标签为 One day。只有一天的出行方式，无原因、路程、前后变化或其他班级资料；这些数字不是实际调查或真实引用。题内如给新材料，会明确引入。图表副本可以保留或指给同学看，问答不表示已发送资料。',
    '同一虚构步行上学图表展示后的工作坊。Jo 希望先弄清问题范围，再讨论观众提出的应用问题。图表只记录十名虚构学生某一天的方式：六人步行、四人乘公交。每个小人图形代表一名学生，分组标签为 Walk / Bus，时间标签为 One day。没有原因、路程或因果数据。可以承认不知道，不需要重复一个已经清楚的问题；高级题会明确给出新的质疑。',
  ],
  paths: [
    {
      short: ['topic', 'number', 'next'],
      standard: ['topic', 'number', 'meaning', 'reason', 'limit', 'next'],
      extended: [
        'topic',
        'number',
        'meaning',
        'reason',
        'compare',
        'limit',
        'challenge',
        'application',
        'followup',
        'next',
      ],
    },
    {
      short: ['topic', 'scope', 'next'],
      standard: ['topic', 'scope', 'visual', 'reason', 'limit', 'next'],
      extended: [
        'topic',
        'number',
        'scope',
        'visual',
        'reason',
        'limit',
        'challenge',
        'application',
        'followup',
        'next',
      ],
    },
  ],
  closing:
    'The presentation question practice is complete. The chart remains a fictional one-day example; no missing data or follow-up answer has been supplied.',
  partial:
    'We will stop here. Some audience questions remain unconfirmed, and the fictional chart does not establish more than its stated data.',
  repairs: {
    clarify: 'You can ask about the current audience question.',
    struggle: 'A brief answer or an honest “I do not know” is fine.',
    offTopic: 'We can return to questions about the walking-to-school chart.',
    unknown:
      'I have not matched that wording or inferred an answer from the chart.',
    changed: 'Your revised answer replaces the earlier one.',
    refusedClosing:
      'We will end the question practice here. No further explanation is required.',
  },
}
export const presentationQa = {
  A1: studyPack(
    scene,
    'A1',
    {
      canDoZh: '用已给图表回答主题、人数和简单指示问题。',
      complexityZh: '具体数字与一个日期范围；缺少原因时直接说不知道。',
      scaffoldingZh: '十人、六人步行、四人公交均已给出；短答支架充分。',
      registerZh: '简单清楚的课堂问答，不把不知道视为失败。',
    },
    [
      [
        'topic',
        'identify-topic',
        'Will you talk about walking or bus travel first?',
        '选择实质不同的介绍入口。',
        'walking',
        'Walking first, please.',
        'bus',
        'I will talk about bus travel first.',
        {
          state: 'model-reviewed',
          record: 'study-review.md: presentation-qa.A1.topic',
        },
      ],
      [
        'number',
        'report-number',
        'How many students walk, or do you need to look at the chart?',
        '可以给已知数字或请求查看。',
        'six',
        'Six students walk.',
        'look',
        'I need to look at the chart.',
        {
          state: 'model-reviewed',
          record: 'study-review.md: presentation-qa.A1.number',
        },
      ],
      [
        'meaning',
        'explain-chart',
        'What do the pictures show: people or days?',
        '图表图形对应人数。',
        'people',
        'They show people.',
        'help',
        'Please help me read the pictures.',
        {
          state: 'model-reviewed',
          record: 'study-review.md: presentation-qa.A1.meaning',
        },
      ],
      [
        'reason',
        'acknowledge-gap',
        'Why do those students walk?',
        '图中没有原因，可诚实说明。',
        'unknown',
        'I do not know why.',
        'ask',
        'We can ask them.',
        {
          state: 'model-reviewed',
          record: 'study-review.md: presentation-qa.A1.reason',
        },
      ],
      [
        'compare',
        'compare-numbers',
        'Are there more walkers or bus riders?',
        '比较已给六与四。',
        'walkers',
        'There are more walkers.',
        'help',
        'Please help me count them.',
        {
          state: 'model-reviewed',
          record: 'study-review.md: presentation-qa.A1.compare',
        },
      ],
      [
        'limit',
        'state-time-scope',
        'Does the chart show one day or every day?',
        '不能把一天说成每天。',
        'one',
        'It shows one day.',
        'point',
        'Can you show me the day on the chart?',
        {
          state: 'model-reviewed',
          record: 'study-review.md: presentation-qa.A1.limit',
        },
      ],
      [
        'challenge',
        'correct-misreading',
        'I said “ten students walk”. Is that right?',
        '明确引入观众的数字错误。',
        'correct',
        'No, six students walk.',
        'show',
        'No. Let us look at the chart together.',
        {
          state: 'model-reviewed',
          record: 'study-review.md: presentation-qa.A1.challenge',
        },
      ],
      [
        'application',
        'offer-personal-example',
        'Do you walk or take a bus to school?',
        '可使用虚构个人方式，与图中群体数据分开。',
        'walk',
        'I walk to school.',
        'bus',
        'I take a bus.',
        {
          state: 'model-reviewed',
          record: 'study-review.md: presentation-qa.A1.application',
        },
      ],
      [
        'followup',
        'offer-material',
        'Can I look at the chart after this chat?',
        '选择展示方式，不声称已发送。',
        'yes',
        'Yes, you can look at this copy.',
        'point',
        'I can show it to you here.',
        {
          state: 'model-reviewed',
          record: 'study-review.md: presentation-qa.A1.followup',
        },
      ],
      [
        'next',
        'choose-next-step',
        'Will you write the numbers or draw a small chart in your notes?',
        '不撤回前面可能已提出的查看图表安排。',
        'numbers',
        'I will write the numbers.',
        'draw',
        'I will draw a small chart.',
        {
          state: 'model-reviewed',
          record: 'study-review.md: presentation-qa.A1.next',
        },
      ],
      [
        'scope',
        'clarify-referent',
        'When I ask “How many?”, what do you want to check?',
        '真实模糊问题在此给出。',
        'walk',
        'Do you mean the students who walk?',
        'all',
        'Do you mean all the students?',
        {
          state: 'model-reviewed',
          record: 'study-review.md: presentation-qa.A1.scope',
        },
      ],
      [
        'visual',
        'provide-visual-support',
        'Can you show me the bus part of the chart?',
        '指示或请求共同查找。',
        'show',
        'Yes, here is the bus part.',
        'together',
        'Let us find it together.',
        {
          state: 'model-reviewed',
          record: 'study-review.md: presentation-qa.A1.visual',
        },
      ],
    ],
    variantRead.A1,
  ),
  A2: studyPack(
    scene,
    'A2',
    {
      canDoZh: '说明图表数字、纠正简单误读并提出后续查看方式。',
      complexityZh: '简短比较与范围说明，未知原因保持未知。',
      scaffoldingZh: '完整虚构数字、独立给出的模糊问题与误读。',
      registerZh: '友好直接的演示后问答，可查表再答。',
    },
    [
      [
        'topic',
        'identify-topic',
        'What part of your chart would you like to introduce first?',
        '选择主题入口。',
        'walking',
        'I would like to start with the students who walk to school.',
        'bus',
        'I will start with the students who take the bus.',
        {
          state: 'model-reviewed',
          record: 'study-review.md: presentation-qa.A2.topic',
        },
      ],
      [
        'number',
        'report-number',
        'Can you tell us how many of the ten students take the bus?',
        '直接给数字或要求查看。',
        'four',
        'Four of the ten students take the bus.',
        'check',
        'Please give me a moment to check the number.',
        {
          state: 'model-reviewed',
          record: 'study-review.md: presentation-qa.A2.number',
        },
      ],
      [
        'meaning',
        'explain-chart',
        'What does one person-shaped picture stand for?',
        '明确图形读法或诚实求助。',
        'one',
        'It stands for one student.',
        'uncertain',
        'I am not sure how to read that part.',
        {
          state: 'model-reviewed',
          record: 'study-review.md: presentation-qa.A2.meaning',
        },
      ],
      [
        'reason',
        'acknowledge-gap',
        'Can the chart tell us why some students take the bus?',
        '没有原因数据。',
        'no',
        'No, it only shows how they travel.',
        'ask',
        'We would need to ask the students about their reasons.',
        {
          state: 'model-reviewed',
          record: 'study-review.md: presentation-qa.A2.reason',
        },
      ],
      [
        'compare',
        'compare-numbers',
        'How would you compare the two groups?',
        '用数量或差值进行比较。',
        'counts',
        'Six students walk and four take the bus.',
        'difference',
        'There are two more walkers than bus riders.',
        {
          state: 'model-reviewed',
          record: 'study-review.md: presentation-qa.A2.compare',
        },
      ],
      [
        'limit',
        'state-time-scope',
        'Can we use this chart to describe the students’ travel every week?',
        '限制一天观察的范围。',
        'one',
        'No, the chart only shows one day.',
        'more',
        'We would need information from more days.',
        {
          state: 'model-reviewed',
          record: 'study-review.md: presentation-qa.A2.limit',
        },
      ],
      [
        'challenge',
        'correct-misreading',
        'I think the chart shows six bus riders. What would you say?',
        '纠正新给的误读。',
        'four',
        'It shows four bus riders; six is the number who walk.',
        'point',
        'Let me point to the bus group so we can count it together.',
        {
          state: 'model-reviewed',
          record: 'study-review.md: presentation-qa.A2.challenge',
        },
      ],
      [
        'application',
        'offer-personal-example',
        'What would you like to ask a student about their journey?',
        '不猜原因，提出具体问题。',
        'time',
        'How long does your journey take?',
        'company',
        'Do you travel alone or with someone?',
        {
          state: 'model-reviewed',
          record: 'study-review.md: presentation-qa.A2.application',
        },
      ],
      [
        'followup',
        'offer-material',
        'How can a classmate see the numbers more clearly afterwards?',
        '建议后续查看，不假设已复制发送。',
        'copy',
        'They can look at this copy after the question session.',
        'write',
        'I can write the two numbers on the board.',
        {
          state: 'model-reviewed',
          record: 'study-review.md: presentation-qa.A2.followup',
        },
      ],
      [
        'next',
        'choose-next-step',
        'What will you do with the chart after these questions?',
        '下一步选项仍为未来。',
        'keep',
        'I will keep it for the next class activity.',
        'notes',
        'I will use it to make a short set of notes.',
        {
          state: 'model-reviewed',
          record: 'study-review.md: presentation-qa.A2.next',
        },
      ],
      [
        'scope',
        'clarify-referent',
        'An audience member asks “Is it a big number?” What would you check?',
        '仅澄清新出现的真实歧义。',
        'which',
        'Do you mean the total number or the number who walk?',
        'compare',
        'What would you like me to compare it with?',
        {
          state: 'model-reviewed',
          record: 'study-review.md: presentation-qa.A2.scope',
        },
      ],
      [
        'visual',
        'provide-visual-support',
        'The labels look small from the back. How could you help?',
        '引入实际可处理的展示障碍。',
        'read',
        'I can read the labels aloud.',
        'closer',
        'I can bring the chart closer.',
        {
          state: 'model-reviewed',
          record: 'study-review.md: presentation-qa.A2.visual',
        },
      ],
    ],
    variantRead.A2,
  ),
  B1: studyPack(
    scene,
    'B1',
    {
      canDoZh: '组织图表解释、处理观众误解并承认信息不足。',
      complexityZh: '连接数字、范围与新问题，区分图表和个人推测。',
      scaffoldingZh: '自足十人图表及明确引入的观众提问。',
      registerZh: '清楚耐心的课堂说明，不反复要求重问清楚问题。',
    },
    [
      [
        'topic',
        'identify-topic',
        'What is the main point you want the audience to take from this small chart?',
        '选择真实可见的重点。',
        'split',
        'It shows how these ten students were divided between walking and taking the bus that day.',
        'majority',
        'It shows that walking was the more common of the two choices in this group.',
        {
          state: 'model-reviewed',
          record: 'study-review.md: presentation-qa.B1.topic',
        },
      ],
      [
        'number',
        'report-number',
        'How could you express the number of walkers so the audience understands the size of the group?',
        '明确分母或说明查表需要。',
        'ratio',
        'Six out of ten students walked that day.',
        'check',
        'I would like to check the total on the chart before giving the proportion.',
        {
          state: 'model-reviewed',
          record: 'study-review.md: presentation-qa.B1.number',
        },
      ],
      [
        'meaning',
        'explain-chart',
        'What should the audience understand about the two groups shown here?',
        '说明类别或防止过度推断。',
        'categories',
        'They are categories of travel on that day, not different classes of students.',
        'choice',
        'The chart records a way of travelling; it does not tell us whether students liked that way.',
        {
          state: 'model-reviewed',
          record: 'study-review.md: presentation-qa.B1.meaning',
        },
      ],
      [
        'reason',
        'acknowledge-gap',
        'A classmate asks why walking is more common. How would you answer from the available information?',
        '回答清楚问题，不假设原因。',
        'unknown',
        'The chart does not give reasons, so I cannot explain the difference from these figures alone.',
        'investigate',
        'I would ask about distance and other possible reasons before suggesting an explanation.',
        {
          state: 'model-reviewed',
          record: 'study-review.md: presentation-qa.B1.reason',
        },
      ],
      [
        'compare',
        'compare-numbers',
        'Which comparison could you make without introducing new information?',
        '选择合法比较或比例。',
        'difference',
        'There were two more walkers than bus riders in the group.',
        'fraction',
        'Walkers made up more than half of the ten students.',
        {
          state: 'model-reviewed',
          record: 'study-review.md: presentation-qa.B1.compare',
        },
      ],
      [
        'limit',
        'state-time-scope',
        'What would you say if someone asked whether this pattern is typical of the whole school?',
        '限定代表范围。',
        'small',
        'We cannot tell from a group of ten students observed on one day.',
        'broader',
        'We would need information from other classes and days to answer that.',
        {
          state: 'model-reviewed',
          record: 'study-review.md: presentation-qa.B1.limit',
        },
      ],
      [
        'challenge',
        'correct-misreading',
        'Someone says “The chart proves walking is faster”. How would you respond?',
        '具体新主张，无需外部事实。',
        'no-time',
        'It does not show journey times, so it cannot establish that walking is faster.',
        'measure',
        'We would need to compare journey times before making that claim.',
        {
          state: 'model-reviewed',
          record: 'study-review.md: presentation-qa.B1.challenge',
        },
      ],
      [
        'application',
        'propose-application',
        'How might the chart be useful even with its limits?',
        '有限应用，不转成普遍结论。',
        'questions',
        'It could help us plan questions for a larger class survey.',
        'practice',
        'It could be used to practise comparing groups and describing numbers.',
        {
          state: 'model-reviewed',
          record: 'study-review.md: presentation-qa.B1.application',
        },
      ],
      [
        'followup',
        'plan-followup',
        'What would you offer if someone wanted information that is not on your chart?',
        '不承诺尚未获取的答案。',
        'record',
        'I could note the question and identify what extra information we would need.',
        'source',
        'I could help look for a suitable source, without promising that it will contain the answer.',
        {
          state: 'model-reviewed',
          record: 'study-review.md: presentation-qa.B1.followup',
        },
      ],
      [
        'next',
        'choose-next-step',
        'How would you close your part of the question session?',
        '自然非问题式结束，不预设每条路径都留下未回答问题。',
        'limits',
        'That is what this chart can tell us. I will keep any unanswered questions with my notes.',
        'thanks',
        'Thank you for the questions. I will leave the chart here for anyone who wants to look more closely.',
        {
          state: 'model-reviewed',
          record: 'study-review.md: presentation-qa.B1.next',
        },
      ],
      [
        'scope',
        'clarify-referent',
        'Someone asks “Did it change?” without naming what changed. What would you clarify?',
        '歧义是新引入的独立问题。',
        'mode',
        'Do you mean whether the students changed their travel method?',
        'numbers',
        'Are you asking whether the numbers were different on another day?',
        {
          state: 'model-reviewed',
          record: 'study-review.md: presentation-qa.B1.scope',
        },
      ],
      [
        'visual',
        'provide-visual-support',
        'How would you explain the chart to someone who cannot see the small figures?',
        '保持数字准确的替代形式。',
        'verbal',
        'There are ten students in total: six walked and four took the bus.',
        'write',
        'I can write a large six beside walking and a large four beside bus travel.',
        {
          state: 'model-reviewed',
          record: 'study-review.md: presentation-qa.B1.visual',
        },
      ],
    ],
    variantRead.B1,
  ),
  B2: studyPack(
    scene,
    'B2',
    {
      canDoZh: '在问答中限定结论、处理质疑并提出适当后续调查。',
      complexityZh: '区分描述、解释和政策应用，能应对错误推断。',
      scaffoldingZh: '完整小样本数据与明确观众主张，无外部研究依赖。',
      registerZh: '有依据、不防御性地回应课堂质疑。',
    },
    [
      [
        'topic',
        'identify-topic',
        'How would you frame your presentation so the audience knows what it does and does not attempt?',
        '选择清楚的展示范围。',
        'snapshot',
        'It is a one-day snapshot of travel in a group of ten, not an explanation of school-wide habits.',
        'description',
        'I am describing a simple distribution and using it to identify questions that would require further information.',
        {
          state: 'model-reviewed',
          record: 'study-review.md: presentation-qa.B2.topic',
        },
      ],
      [
        'number',
        'report-number',
        'How would you report the walking figure without making the sample sound larger than it is?',
        '避免只给百分数掩盖人数。',
        'count',
        'Six of the ten students walked, so I would keep the count alongside any percentage.',
        'avoid',
        'I would avoid leading with a percentage and show the ten individual observations instead.',
        {
          state: 'model-reviewed',
          record: 'study-review.md: presentation-qa.B2.number',
        },
      ],
      [
        'meaning',
        'explain-chart',
        'What distinction should we make between the recorded travel method and a student’s preference?',
        '说明观察与心理偏好差异。',
        'constraint',
        'A recorded method may reflect practical constraints rather than what the student would prefer.',
        'question',
        'To discuss preference, we would need to ask a separate question rather than infer it from the journey.',
        {
          state: 'model-reviewed',
          record: 'study-review.md: presentation-qa.B2.meaning',
        },
      ],
      [
        'reason',
        'acknowledge-gap',
        'Could distance explain the difference between the groups?',
        '可提出假说，不当作已知原因。',
        'possible',
        'It could, but the chart contains no distance information with which to test that explanation.',
        'alternatives',
        'Distance is one possibility; I would also want to consider other factors before choosing an explanation.',
        {
          state: 'model-reviewed',
          record: 'study-review.md: presentation-qa.B2.reason',
        },
      ],
      [
        'compare',
        'compare-numbers',
        'What is the most useful way to describe the gap between the groups here?',
        '比较表达的作用。',
        'absolute',
        'An absolute difference of two students makes the size of the gap easy to judge.',
        'distribution',
        'I would show both counts, because a single statement about the gap can hide how small the group is.',
        {
          state: 'model-reviewed',
          record: 'study-review.md: presentation-qa.B2.compare',
        },
      ],
      [
        'limit',
        'state-time-scope',
        'How would you respond to a request for a conclusion about the whole school?',
        '拒绝过度外推，同时提供下一步。',
        'boundary',
        'I can describe this group, but I would not generalise to the school without a broader sample.',
        'design',
        'That is a different question; we would need to plan sampling across classes and days to address it.',
        {
          state: 'model-reviewed',
          record: 'study-review.md: presentation-qa.B2.limit',
        },
      ],
      [
        'challenge',
        'respond-challenge',
        'An audience member says “With only ten students, your chart is useless”. How would you respond?',
        '真正新质疑，平衡接受与反驳。',
        'purpose',
        'It is too limited for a school-wide conclusion, but still useful for demonstrating how to describe a small dataset.',
        'pilot',
        'The size limits what we can infer; it does not stop the example from revealing what a fuller survey should ask.',
        {
          state: 'model-reviewed',
          record: 'study-review.md: presentation-qa.B2.challenge',
        },
      ],
      [
        'application',
        'propose-application',
        'Would this chart justify changing school transport arrangements?',
        '不把小样本用于直接决策。',
        'no',
        'No. We would need much broader information about journeys and needs before proposing changes.',
        'discussion',
        'It could start a discussion about what information to collect, but it would not justify a transport decision on its own.',
        {
          state: 'model-reviewed',
          record: 'study-review.md: presentation-qa.B2.application',
        },
      ],
      [
        'followup',
        'plan-followup',
        'How would you handle an unanswered question without promising a result you may not be able to obtain?',
        '具体规划而非空泛承诺。',
        'needs',
        'I would record the question and explain which missing information would be needed to answer it.',
        'feasibility',
        'I would offer to check whether a suitable source exists, then report whether the question is answerable from it.',
        {
          state: 'model-reviewed',
          record: 'study-review.md: presentation-qa.B2.followup',
        },
      ],
      [
        'next',
        'choose-next-step',
        'How would you bring the discussion to a close while preserving the main qualification?',
        '总结有限成果，不假设短练经历过质疑。',
        'summary',
        'The chart gives us a small descriptive snapshot; explanations and wider conclusions remain open.',
        'handoff',
        'Thank you for the questions. I will keep the distinction between observed numbers and possible explanations clear in my notes.',
        {
          state: 'model-reviewed',
          record: 'study-review.md: presentation-qa.B2.next',
        },
      ],
      [
        'scope',
        'clarify-referent',
        'A new question is “Is the difference significant?” What would you clarify before answering?',
        'significant 的具体歧义在题内真实给出。',
        'practical',
        'Do you mean large enough to matter in practice, or statistically significant?',
        'comparison',
        'Are you asking about the difference between six and four, or a change compared with another group?',
        {
          state: 'model-reviewed',
          record: 'study-review.md: presentation-qa.B2.scope',
        },
      ],
      [
        'visual',
        'provide-visual-support',
        'How could you improve the display for an audience that is struggling to judge the counts?',
        '提供可执行呈现调整。',
        'labels',
        'I would label each category with its count so the audience does not have to estimate from the drawing.',
        'table',
        'I would add a small table showing the two counts and the total alongside the graphic.',
        {
          state: 'model-reviewed',
          record: 'study-review.md: presentation-qa.B2.visual',
        },
      ],
    ],
    variantRead.B2,
  ),
  C1: studyPack(
    scene,
    'C1',
    {
      canDoZh: '精确回应推断、概念歧义与方法质疑，同时维护有限示例的价值。',
      complexityZh: '区分样本描述、外推与决策，重构过强或过弱的评价。',
      scaffoldingZh: '所有数字与质疑题内提供，不虚构外部研究或统计检验。',
      registerZh: '审慎而不僵硬的学术口头问答，承认边界但不反复空泛免责声明。',
    },
    [
      [
        'topic',
        'identify-topic',
        'What would be a defensible central claim for this presentation?',
        '确定能支持的核心命题。',
        'distribution',
        'Within this fictional group on the day shown, walking was more common than bus travel; that is the descriptive claim the chart supports.',
        'method',
        'The example illustrates how easily a simple count can be turned into a stronger claim than the available information warrants.',
        {
          state: 'model-reviewed',
          record: 'study-review.md: presentation-qa.C1.topic',
        },
      ],
      [
        'number',
        'report-number',
        'What is at risk of being lost if you report only “sixty per cent walked”?',
        '说明分母和个体变动敏感性。',
        'size',
        'The audience may overlook that the figure represents just six people, not a large survey.',
        'sensitivity',
        'It conceals how much the percentage would shift if even one person in this very small group travelled differently.',
        {
          state: 'model-reviewed',
          record: 'study-review.md: presentation-qa.C1.number',
        },
      ],
      [
        'meaning',
        'explain-chart',
        'How would you respond to a listener who treats “travel choice” as evidence of a freely expressed preference?',
        '对实际出现的假设作限定。',
        'constraint',
        '“Choice” is being used descriptively here; the chart does not establish what alternatives were available to each student.',
        'reword',
        'I would call it the recorded travel method to avoid implying a preference that we have not measured.',
        {
          state: 'model-reviewed',
          record: 'study-review.md: presentation-qa.C1.meaning',
        },
      ],
      [
        'reason',
        'acknowledge-gap',
        'How could you discuss plausible explanations without allowing them to become the apparent findings of the presentation?',
        '把假说与结果在话语中分开。',
        'separate',
        'I would label distance as a possible explanation and immediately distinguish it from the variables actually recorded.',
        'questions',
        'I would turn the explanations into research questions, so their untested status remains explicit.',
        {
          state: 'model-reviewed',
          record: 'study-review.md: presentation-qa.C1.reason',
        },
      ],
      [
        'compare',
        'compare-numbers',
        'How would you respond if someone described the two-person gap as both “a clear majority” and “almost no difference”?',
        '两种读法在题内同时给出。',
        'frame',
        'Those descriptions emphasise different features: six exceeds half, but the absolute gap is only two people. I would show the counts rather than settle the issue through adjectives.',
        'purpose',
        'The useful description depends on the question being asked; neither phrase alone tells us whether the gap matters beyond this group.',
        {
          state: 'model-reviewed',
          record: 'study-review.md: presentation-qa.C1.compare',
        },
      ],
      [
        'limit',
        'state-time-scope',
        'Which missing feature most directly blocks a claim about usual school-wide behaviour?',
        '定位不同外推条件。',
        'sampling',
        'We have no basis for treating these ten students as representative of the school.',
        'time',
        'We have only one day of observations, so we cannot establish what is usual even for these students.',
        {
          state: 'model-reviewed',
          record: 'study-review.md: presentation-qa.C1.limit',
        },
      ],
      [
        'challenge',
        'respond-challenge',
        'A critic says “If you cannot explain the pattern, you have nothing worth presenting”. How would you answer?',
        '回应具体价值质疑。',
        'distinction',
        'Description and explanation are different contributions. The chart can establish the former within its stated scope without pretending to establish the latter.',
        'reframe',
        'I would accept that the presentation cannot answer a causal question, but reframe its value around identifying exactly what an explanatory study would need to measure.',
        {
          state: 'model-reviewed',
          record: 'study-review.md: presentation-qa.C1.challenge',
        },
      ],
      [
        'application',
        'propose-application',
        'How could the example inform a future enquiry without becoming a premature case for a preferred transport policy?',
        '保持调查开放性。',
        'design',
        'It could help us refine the categories and questions, provided the next enquiry does not assume which travel method students ought to use.',
        'needs',
        'I would use it to ask what needs and constraints are missing, rather than treat the larger category as a policy recommendation.',
        {
          state: 'model-reviewed',
          record: 'study-review.md: presentation-qa.C1.application',
        },
      ],
      [
        'followup',
        'plan-followup',
        'What would a responsible follow-up commitment sound like when the requested comparison may not exist?',
        '承诺范围具体可控。',
        'availability',
        'I can check whether comparable data are available and report the outcome of that search, but I cannot promise the comparison itself.',
        'requirements',
        'I can set out the conditions a valid comparison would need to meet, even if no existing dataset meets them.',
        {
          state: 'model-reviewed',
          record: 'study-review.md: presentation-qa.C1.followup',
        },
      ],
      [
        'next',
        'choose-next-step',
        'How would you close without allowing a speculative explanation to become the takeaway?',
        '结束强调有限事实或开放问题。',
        'boundary',
        'The observed counts are clear; the reasons behind them remain questions for a different kind of enquiry.',
        'questions',
        'I will leave the discussion with the questions the chart raises, rather than an explanation it cannot substantiate.',
        {
          state: 'model-reviewed',
          record: 'study-review.md: presentation-qa.C1.next',
        },
      ],
      [
        'scope',
        'clarify-referent',
        'A listener asks “Is it representative?” without specifying a population. How would you narrow the question?',
        '只澄清真实未指定的总体。',
        'population',
        'Representative of this class, the whole school, or students more generally? Those would require different sampling claims.',
        'time',
        'Are you asking about the people included or whether that single day reflects their usual behaviour?',
        {
          state: 'model-reviewed',
          record: 'study-review.md: presentation-qa.C1.scope',
        },
      ],
      [
        'visual',
        'provide-visual-support',
        'What display choice would communicate the small scale of the example more honestly?',
        '图示选择与解释边界关联。',
        'individuals',
        'I would retain individual student symbols with the counts, so the small number of observations stays visible.',
        'annotation',
        'I would put the one-day scope and total beside the figures rather than burying them in a footnote.',
        {
          state: 'model-reviewed',
          record: 'study-review.md: presentation-qa.C1.visual',
        },
      ],
    ],
    variantRead.C1,
  ),
}
