import { studyPack, type StudyScene, type Review } from './authoring'
const variantRead = {
  A1: {
    state: 'model-reviewed',
    record: 'study-review.md: seminar-discussion.A1 variants',
  },
  A2: {
    state: 'model-reviewed',
    record: 'study-review.md: seminar-discussion.A2 variants',
  },
  B1: {
    state: 'model-reviewed',
    record: 'study-review.md: seminar-discussion.B1 variants',
  },
  B2: {
    state: 'model-reviewed',
    record: 'study-review.md: seminar-discussion.B2 variants',
  },
  C1: {
    state: 'model-reviewed',
    record: 'study-review.md: seminar-discussion.C1 variants',
  },
} satisfies Record<string, Review>
const scene: StudyScene = {
  sceneId: 'study-05',
  slug: 'seminar-discussion',
  situations: [
    '虚构读书讨论，和同学 Jo 一起看一幅课堂安静角图画：两把椅子、两本书、一只蓝包，包在一把椅子上。配文是：“A quiet corner has two chairs. Students may sit and read.” 图画和文字均为原创教学设定。简单等级只说图中物件和阅读偏好，高级讨论的观察和论点均在问题内给出，不当作真实研究。',
    '虚构读书小组围绕同一安静角图画和短文讨论，Jo 邀请你先说明自己的理解，再为其他读者留发言空间。两把椅子、两本书、一只放在椅子上的蓝包；全文：“A quiet corner has two chairs. Students may sit and read.” 除题内明确新增的观点外，不假设同学讲过经历或达成一致。',
  ],
  paths: [
    {
      short: ['notice', 'view', 'next'],
      standard: ['notice', 'meaning', 'view', 'detail', 'response', 'next'],
      extended: [
        'notice',
        'meaning',
        'view',
        'detail',
        'evidence',
        'alternative',
        'response',
        'synthesis',
        'open',
        'next',
      ],
    },
    {
      short: ['notice', 'turn', 'next'],
      standard: ['notice', 'view', 'turn', 'term', 'response', 'next'],
      extended: [
        'notice',
        'meaning',
        'view',
        'turn',
        'term',
        'alternative',
        'response',
        'synthesis',
        'open',
        'next',
      ],
    },
  ],
  closing:
    'The discussion practice is complete. Different views may remain; no class decision or real research finding has been established.',
  partial:
    'We will stop with part of the discussion still open. An unanswered question is not an agreed conclusion.',
  repairs: {
    clarify: 'You can ask about this sentence, picture or discussion question.',
    struggle: 'You may point out one detail or use a short answer.',
    offTopic: 'We can return to the quiet-corner material.',
    unknown:
      'That wording has not been matched to a covered contribution; I have not inferred your position.',
    changed: 'Your new contribution replaces the earlier recorded one.',
    refusedClosing:
      'We will stop the discussion here. You may choose not to take a position.',
  },
}
export const seminarDiscussion = {
  A1: studyPack(
    scene,
    'A1',
    {
      canDoZh: '在有图画支持的小组中指出物件、说明喜好并轮流发言。',
      complexityZh: '图画中的单步信息与具体读书选择，不要求论证或综合证据。',
      scaffoldingZh: '两椅两书与蓝包已给出；短文可直接引用，也可求助。',
      registerZh: '简单友好的读书小组交流，保留不懂和暂不发言。',
    },
    [
      [
        'notice',
        'choose-detail',
        'What do you want to talk about in the picture?',
        '选择可见物件作为话题。',
        'chairs',
        'The chairs.',
        'books',
        'The books.',
        {
          state: 'model-reviewed',
          record: 'study-review.md: seminar-discussion.A1.notice',
        },
      ],
      [
        'meaning',
        'check-simple-meaning',
        'What can students do in this corner?',
        '依据短文或表示需要帮助。',
        'read',
        'They can sit and read.',
        'help',
        'Please help me read the sentence.',
        {
          state: 'model-reviewed',
          record: 'study-review.md: seminar-discussion.A1.meaning',
        },
      ],
      [
        'view',
        'state-preference',
        'Would you like to read here?',
        '表达自己的喜好。',
        'yes',
        'Yes, I like quiet places.',
        'no',
        'No, I like reading at home.',
        {
          state: 'model-reviewed',
          record: 'study-review.md: seminar-discussion.A1.view',
        },
      ],
      [
        'detail',
        'locate-detail',
        'Where is the blue bag?',
        '图中信息已给出。',
        'chair',
        'It is on a chair.',
        'show',
        'Please show me the bag.',
        {
          state: 'model-reviewed',
          record: 'study-review.md: seminar-discussion.A1.detail',
        },
      ],
      [
        'evidence',
        'refer-to-material',
        'Shall we look at the picture or read the words together?',
        '选择理解材料的方法，不要求证据论证。',
        'picture',
        'Let us look at the picture.',
        'words',
        'Let us read the words.',
        {
          state: 'model-reviewed',
          record: 'study-review.md: seminar-discussion.A1.evidence',
        },
      ],
      [
        'alternative',
        'suggest-item',
        'What else would you like in this corner?',
        '提议新增物件，不称图中已有。',
        'table',
        'I would like a small table.',
        'lamp',
        'A lamp, please.',
        {
          state: 'model-reviewed',
          record: 'study-review.md: seminar-discussion.A1.alternative',
        },
      ],
      [
        'response',
        'respond-to-proposal',
        'Jo says, “I want a red chair.” Do you like that idea?',
        '同伴观点此处明确给出。',
        'red',
        'Yes, I like red.',
        'blue',
        'I like blue chairs.',
        {
          state: 'model-reviewed',
          record: 'study-review.md: seminar-discussion.A1.response',
        },
      ],
      [
        'synthesis',
        'choose-shared-action',
        'Shall we draw a new corner or read the text aloud?',
        '选择具体共同活动，不假设前面的朗读请求已经执行。',
        'draw',
        'Let us draw a new corner.',
        'read',
        'Let us read the text aloud.',
        {
          state: 'model-reviewed',
          record: 'study-review.md: seminar-discussion.A1.synthesis',
        },
      ],
      [
        'open',
        'ask-missing-detail',
        'What do you want to ask about the corner?',
        '提出尚未给的信息问题。',
        'where',
        'Where is this corner?',
        'time',
        'When can we go there?',
        {
          state: 'model-reviewed',
          record: 'study-review.md: seminar-discussion.A1.open',
        },
      ],
      [
        'next',
        'choose-next-step',
        'Would you like to speak next time or listen first?',
        '安排以后参与，不假设已经讨论完具体观点。',
        'speak',
        'I would like to speak.',
        'listen',
        'I want to listen first.',
        {
          state: 'model-reviewed',
          record: 'study-review.md: seminar-discussion.A1.next',
        },
      ],
      [
        'turn',
        'manage-turn',
        'Do you want a turn now?',
        '可发言也可等。',
        'now',
        'Yes, my turn, please.',
        'wait',
        'Not yet. I want to wait.',
        {
          state: 'model-reviewed',
          record: 'study-review.md: seminar-discussion.A1.turn',
        },
      ],
      [
        'term',
        'ask-word-meaning',
        'Do you know the word “quiet”?',
        '可以给基础含义或请求解释。',
        'yes',
        'Yes. Not noisy.',
        'explain',
        'No. Please explain it.',
        {
          state: 'model-reviewed',
          record: 'study-review.md: seminar-discussion.A1.term',
        },
      ],
    ],
    variantRead.A1,
  ),
  A2: studyPack(
    scene,
    'A2',
    {
      canDoZh: '借助短文说喜好、给简单理由并回应同伴建议。',
      complexityZh: '围绕具体读书角安排一两步交流，能问材料未给的信息。',
      scaffoldingZh: '短文、图示和新给出的同伴话语，回答可直接使用。',
      registerZh: '友好且尊重发言顺序，不必同意别人的偏好。',
    },
    [
      [
        'notice',
        'choose-detail',
        'Which part of the reading corner interests you most?',
        '选一个讨论焦点。',
        'chairs',
        'I am interested in the two chairs and where people can sit.',
        'books',
        'The books interest me because I enjoy reading.',
        {
          state: 'model-reviewed',
          record: 'study-review.md: seminar-discussion.A2.notice',
        },
      ],
      [
        'meaning',
        'check-simple-meaning',
        'What does the short text tell us students can do?',
        '引用具体活动或请求更慢阅读。',
        'read',
        'It says students may sit and read in the corner.',
        'slow',
        'Could we read that sentence slowly together?',
        {
          state: 'model-reviewed',
          record: 'study-review.md: seminar-discussion.A2.meaning',
        },
      ],
      [
        'view',
        'state-preference',
        'Would this be a comfortable place for you to read?',
        '喜好加简单理由。',
        'quiet',
        'Yes, because it is a quiet place.',
        'home',
        'I would prefer home because I like my own chair.',
        {
          state: 'model-reviewed',
          record: 'study-review.md: seminar-discussion.A2.view',
        },
      ],
      [
        'detail',
        'locate-detail',
        'Does the picture show both chairs ready for someone to sit on?',
        '依据蓝包细节判断，不猜真实占座者。',
        'bag',
        'No, there is a bag on one chair.',
        'look',
        'I need to look at the picture more closely.',
        {
          state: 'model-reviewed',
          record: 'study-review.md: seminar-discussion.A2.detail',
        },
      ],
      [
        'evidence',
        'refer-to-material',
        'How could we show a classmate what the text says about reading?',
        '引用材料，不虚构额外内容。',
        'point',
        'We could point to the words “sit and read”.',
        'aloud',
        'We could read the second sentence aloud.',
        {
          state: 'model-reviewed',
          record: 'study-review.md: seminar-discussion.A2.evidence',
        },
      ],
      [
        'alternative',
        'suggest-item',
        'What could make the corner nicer for you?',
        '提出个人选择。',
        'light',
        'A reading lamp would make it nicer for me.',
        'shelf',
        'I would like a small shelf for the books.',
        {
          state: 'model-reviewed',
          record: 'study-review.md: seminar-discussion.A2.alternative',
        },
      ],
      [
        'response',
        'respond-to-proposal',
        'Jo says, “Let us put music in the corner.” What do you think?',
        '新给出的具体意见。',
        'no',
        'I would rather keep it quiet so I can read.',
        'soft',
        'Soft music would be nice, but not loud music.',
        {
          state: 'model-reviewed',
          record: 'study-review.md: seminar-discussion.A2.response',
        },
      ],
      [
        'synthesis',
        'choose-shared-action',
        'How could our group show its ideas for the corner?',
        '选择具体展示成果。',
        'drawing',
        'We could draw a picture with our ideas on it.',
        'list',
        'We could make a short list of things to add.',
        {
          state: 'model-reviewed',
          record: 'study-review.md: seminar-discussion.A2.synthesis',
        },
      ],
      [
        'open',
        'ask-missing-detail',
        'What is one thing the text does not tell us that you would like to know?',
        '提出实质信息缺口。',
        'books',
        'What kinds of books are there?',
        'hours',
        'When can students use the corner?',
        {
          state: 'model-reviewed',
          record: 'study-review.md: seminar-discussion.A2.open',
        },
      ],
      [
        'next',
        'choose-next-step',
        'What would you like to prepare for our next reading discussion?',
        '安排真实未来准备。',
        'words',
        'I would like to write down useful words.',
        'question',
        'I would like to prepare one question about the text.',
        {
          state: 'model-reviewed',
          record: 'study-review.md: seminar-discussion.A2.next',
        },
      ],
      [
        'turn',
        'manage-turn',
        'Would you like to add something now or hear another person first?',
        '选择参与顺序。',
        'add',
        'I would like to add one idea now.',
        'listen',
        'I would like to hear another person first.',
        {
          state: 'model-reviewed',
          record: 'study-review.md: seminar-discussion.A2.turn',
        },
      ],
      [
        'term',
        'ask-word-meaning',
        'In “Students may sit and read”, is “may” clear to you?',
        '按当前短文理解允许含义或请求解释。',
        'can',
        'I think it means students can sit and read there.',
        'ask',
        'Could you explain “may” in this sentence?',
        {
          state: 'model-reviewed',
          record: 'study-review.md: seminar-discussion.A2.term',
        },
      ],
    ],
    variantRead.A2,
  ),
  B1: studyPack(
    scene,
    'B1',
    {
      canDoZh: '从短文细节提出观点与问题，回应不同意见并组织共同探索。',
      complexityZh: '区分材料明示与个人推断，给出理由和可行替代。',
      scaffoldingZh: '原创短文完全给出，题中新增观点有明确发言者。',
      registerZh: '合作讨论，可不同意也可保持未决定。',
    },
    [
      [
        'notice',
        'choose-detail',
        'What detail would be a useful starting point for discussing this corner?',
        '选择具体讨论入口。',
        'chairs',
        'The two chairs make me wonder how many students could use the corner at once.',
        'permission',
        'The word “may” interests me because the text offers students a choice.',
        {
          state: 'model-reviewed',
          record: 'study-review.md: seminar-discussion.B1.notice',
        },
      ],
      [
        'meaning',
        'interpret-text',
        'Does the text require students to read in the corner?',
        '区分允许和义务。',
        'choice',
        'No, it says they may read there, so it seems to be an option.',
        'check',
        'I would like to check whether there are other instructions before deciding that.',
        {
          state: 'model-reviewed',
          record: 'study-review.md: seminar-discussion.B1.meaning',
        },
      ],
      [
        'view',
        'state-preference',
        'What value could a quiet corner have in a busy classroom?',
        '提出理由，不冒充观察结果。',
        'focus',
        'It could give students a place to concentrate for a short time.',
        'rest',
        'It might offer a calm break, even for someone who does not want a long reading session.',
        {
          state: 'model-reviewed',
          record: 'study-review.md: seminar-discussion.B1.view',
        },
      ],
      [
        'detail',
        'interpret-detail',
        'What can we reasonably say about the bag on the chair?',
        '区分可见事实和推测。',
        'visible',
        'We can say a bag is on the chair, but we do not know whose it is.',
        'possible',
        'It may make that chair harder to use, although the picture does not show anyone trying to sit there.',
        {
          state: 'model-reviewed',
          record: 'study-review.md: seminar-discussion.B1.detail',
        },
      ],
      [
        'evidence',
        'refer-to-material',
        'Which part of the text supports calling this a reading space?',
        '可引用句子或明示词语。',
        'sentence',
        'The second sentence says students may sit and read.',
        'limit',
        'The word “read” supports that, but it does not say reading is the only activity allowed.',
        {
          state: 'model-reviewed',
          record: 'study-review.md: seminar-discussion.B1.evidence',
        },
      ],
      [
        'alternative',
        'suggest-alternative',
        'How could the corner serve more students without making it crowded?',
        '提出不同可行方案。',
        'turns',
        'Students could take turns using it for short periods.',
        'another',
        'The class could consider a second small quiet area elsewhere.',
        {
          state: 'model-reviewed',
          record: 'study-review.md: seminar-discussion.B1.alternative',
        },
      ],
      [
        'response',
        'respond-to-proposal',
        'Jo says, “Only keen readers will use it.” How would you respond?',
        '具体他人主张。',
        'broader',
        'Perhaps, but students who need a quiet moment might use it too.',
        'ask',
        'That is possible, but we could ask classmates rather than assume who would be interested.',
        {
          state: 'model-reviewed',
          record: 'study-review.md: seminar-discussion.B1.response',
        },
      ],
      [
        'synthesis',
        'identify-shared-question',
        'What shared question could organise different ideas about the corner?',
        '不虚构大家已经表达过的立场。',
        'users',
        'We could ask who the corner should serve and what those students need.',
        'use',
        'We could ask how the corner would fit into an ordinary class day.',
        {
          state: 'model-reviewed',
          record: 'study-review.md: seminar-discussion.B1.synthesis',
        },
      ],
      [
        'open',
        'ask-missing-detail',
        'What important question does the short text leave open?',
        '提出新信息缺口。',
        'access',
        'How would students know when the corner is available?',
        'rules',
        'What would happen if more than two students wanted to use it?',
        {
          state: 'model-reviewed',
          record: 'study-review.md: seminar-discussion.B1.open',
        },
      ],
      [
        'next',
        'choose-next-step',
        'What could our group do next without pretending these ideas are already agreed?',
        '下一步是探索而非决定。',
        'options',
        'We could write down the options and ask the class for comments.',
        'questions',
        'We could collect the unanswered questions before choosing an arrangement.',
        {
          state: 'model-reviewed',
          record: 'study-review.md: seminar-discussion.B1.next',
        },
      ],
      [
        'turn',
        'manage-turn',
        'How would you make space for someone who has not spoken yet?',
        '选择包容的邀请或留白。',
        'invite',
        'I would invite them to add something, while making it clear they can pass.',
        'pause',
        'I would leave a short pause rather than fill every gap myself.',
        {
          state: 'model-reviewed',
          record: 'study-review.md: seminar-discussion.B1.turn',
        },
      ],
      [
        'term',
        'ask-word-meaning',
        'How would you check what Jo means by “accessible” in this discussion?',
        '词在问题内明确引入，含义未定义。',
        'physical',
        'Do you mean physically easy to reach and use?',
        'available',
        'Are you talking about when students are allowed to use it?',
        {
          state: 'model-reviewed',
          record: 'study-review.md: seminar-discussion.B1.term',
        },
      ],
    ],
    variantRead.B1,
  ),
  B2: studyPack(
    scene,
    'B2',
    {
      canDoZh: '区别文本依据与推测，比较安静角方案并提出可检验问题。',
      complexityZh: '对群体概括、使用条件与潜在冲突提出限定。',
      scaffoldingZh: '自足短文和题内新例子，不需要外部教育学知识。',
      registerZh: '有理由的探讨、支持和反驳，给未发言者退出空间。',
    },
    [
      [
        'notice',
        'choose-detail',
        'Which feature of the short description is worth examining rather than taking for granted?',
        '选择值得追问的文本特点。',
        'capacity',
        'The two-seat capacity is worth examining because it may shape who can actually benefit.',
        'optional',
        'The optional wording is important because offering a space is different from requiring everyone to use it.',
        {
          state: 'model-reviewed',
          record: 'study-review.md: seminar-discussion.B2.notice',
        },
      ],
      [
        'meaning',
        'interpret-text',
        'What is the difference between the space being available and its being usable?',
        '区分名义提供与实际使用。',
        'barriers',
        'A space can exist while practical barriers prevent some students from using it.',
        'conditions',
        'Usability depends on conditions such as access and timing, which the text does not specify.',
        {
          state: 'model-reviewed',
          record: 'study-review.md: seminar-discussion.B2.meaning',
        },
      ],
      [
        'view',
        'state-position',
        'How strongly would you support introducing a corner like this?',
        '立场有实质差别。',
        'trial',
        'I would support a small trial, provided students can comment on how it works.',
        'reserve',
        'I would reserve judgement until we know whether students need this more than other uses of the space.',
        {
          state: 'model-reviewed',
          record: 'study-review.md: seminar-discussion.B2.view',
        },
      ],
      [
        'detail',
        'interpret-detail',
        'What does the bag detail allow us to discuss, and what would go beyond the picture?',
        '区分有限细节与人物归因。',
        'access',
        'It allows us to discuss a possible obstacle to seating, but not to accuse a particular student of excluding others.',
        'routine',
        'It raises a question about where belongings go; it does not show that the chair is always blocked.',
        {
          state: 'model-reviewed',
          record: 'study-review.md: seminar-discussion.B2.detail',
        },
      ],
      [
        'evidence',
        'evaluate-evidence',
        'A fictional note says “Three visitors read quietly on Tuesday”. Does it show the corner improves concentration?',
        '明确新给观察，避免真实引用。',
        'no',
        'No. It describes activity on one day, not a comparison that shows an improvement.',
        'suggests',
        'It suggests the corner can support quiet reading on that occasion, but it does not establish a general effect on concentration.',
        {
          state: 'model-reviewed',
          record: 'study-review.md: seminar-discussion.B2.evidence',
        },
      ],
      [
        'alternative',
        'suggest-alternative',
        'What alternative could address quiet study needs without permanently reserving this space?',
        '提出不同资源配置。',
        'times',
        'We could set aside quiet periods in the existing classroom.',
        'portable',
        'We could use movable seating so a quiet area can be created when needed.',
        {
          state: 'model-reviewed',
          record: 'study-review.md: seminar-discussion.B2.alternative',
        },
      ],
      [
        'response',
        'respond-to-proposal',
        'Jo argues that “equal access means exactly the same time for everyone”. How would you respond?',
        '回应明确假设。',
        'needs',
        'Equal time may look fair, but different needs could justify some flexibility.',
        'practical',
        'That rule might be simple to administer, though we should consider whether everyone wants the same amount of time.',
        {
          state: 'model-reviewed',
          record: 'study-review.md: seminar-discussion.B2.response',
        },
      ],
      [
        'synthesis',
        'identify-shared-question',
        'How could we connect the access question with the question of usefulness?',
        '整合问题而非假装各方已同意。',
        'users',
        'We could ask whether the students who would benefit are actually able to use the space.',
        'conditions',
        'We could compare the conditions under which the corner is useful with the conditions under which access is restricted.',
        {
          state: 'model-reviewed',
          record: 'study-review.md: seminar-discussion.B2.synthesis',
        },
      ],
      [
        'open',
        'ask-missing-detail',
        'Which unresolved question would matter most before choosing a permanent arrangement?',
        '确定进一步调查焦点。',
        'demand',
        'I would want to know when demand is highest and whether two seats are enough.',
        'alternatives',
        'I would want to compare the corner with other ways of meeting the same need.',
        {
          state: 'model-reviewed',
          record: 'study-review.md: seminar-discussion.B2.open',
        },
      ],
      [
        'next',
        'choose-next-step',
        'What would be a proportionate next step for this discussion?',
        '有限探索，不宣布真实实施。',
        'trialplan',
        'We could outline a short trial with clear questions for feedback.',
        'views',
        'We could seek views from students who are less likely to volunteer them in a group discussion.',
        {
          state: 'model-reviewed',
          record: 'study-review.md: seminar-discussion.B2.next',
        },
      ],
      [
        'turn',
        'manage-turn',
        'How would you invite another view without putting a quiet participant on the spot?',
        '非强迫性的轮流发言。',
        'open',
        'I would offer an open invitation and explicitly allow people to pass.',
        'written',
        'I would suggest a moment for written ideas before asking anyone to speak.',
        {
          state: 'model-reviewed',
          record: 'study-review.md: seminar-discussion.B2.turn',
        },
      ],
      [
        'term',
        'ask-word-meaning',
        'The group starts using “successful” without defining it. What would you ask?',
        '术语真实未界定。',
        'measure',
        'What would count as success: frequent use, better concentration, or students feeling more comfortable?',
        'whose',
        'Successful for whom: the users, the rest of the class, or the teacher managing the room?',
        {
          state: 'model-reviewed',
          record: 'study-review.md: seminar-discussion.B2.term',
        },
      ],
    ],
    variantRead.B2,
  ),
  C1: studyPack(
    scene,
    'C1',
    {
      canDoZh: '剖析概念与评价假设，综合不同问题而不抹平分歧。',
      complexityZh: '将价值主张与描述证据分开，分析公平、代表性与可逆试行。',
      scaffoldingZh: '完整原创短文及有限观察，所有论点在题内出现。',
      registerZh: '精确、开放的研讨语域，温和挑战推论而不使用空泛复杂句。',
    },
    [
      [
        'notice',
        'choose-detail',
        'What assumption in the description would you make explicit before evaluating the proposal?',
        '选择不同隐含前提。',
        'quiet',
        'I would examine the assumption that a visibly quiet space necessarily meets the needs of the students who find the classroom difficult.',
        'permission',
        'I would ask whether permission to use the corner translates into a realistic opportunity to do so during class.',
        {
          state: 'model-reviewed',
          record: 'study-review.md: seminar-discussion.C1.notice',
        },
      ],
      [
        'meaning',
        'interpret-text',
        'How would you distinguish an inclusive invitation from an inclusive arrangement?',
        '概念区分落到具体条件。',
        'conditions',
        'The invitation can be open to everyone while the arrangement still favours those who can reach the seats or choose the available times.',
        'enquiry',
        'I would look beyond who is nominally allowed in and ask whose participation the practical conditions make easy or difficult.',
        {
          state: 'model-reviewed',
          record: 'study-review.md: seminar-discussion.C1.meaning',
        },
      ],
      [
        'view',
        'state-position',
        'What position could you defend at this point without resolving every practical question?',
        '不同力度的立场均合法。',
        'conditional',
        'I could defend a reversible trial, but not a permanent allocation before the competing needs for the space are understood.',
        'withhold',
        'I would withhold support for even a trial until the class has a say in which problem it is intended to address.',
        {
          state: 'model-reviewed',
          record: 'study-review.md: seminar-discussion.C1.view',
        },
      ],
      [
        'detail',
        'interpret-detail',
        'How would you keep the bag on the chair from becoming an anecdote that does too much argumentative work?',
        '限制图画细节的证明作用。',
        'illustration',
        'I would use it to illustrate a possible access issue, not as evidence that exclusion is a recurring feature of the corner.',
        'question',
        'I would turn it into a question about storage arrangements rather than infer either the owner’s intention or a wider pattern.',
        {
          state: 'model-reviewed',
          record: 'study-review.md: seminar-discussion.C1.detail',
        },
      ],
      [
        'evidence',
        'evaluate-evidence',
        'A fictional note reports three quiet readers on Tuesday but no observations elsewhere. How would you weigh it?',
        '自足有限证据，不假装真实研究。',
        'feasibility',
        'It offers a small indication that quiet reading occurred there, but cannot tell us whether the corner made a difference compared with another space.',
        'selection',
        'We also do not know how those three visitors were selected, so even the pattern of use may be less typical than the note suggests.',
        {
          state: 'model-reviewed',
          record: 'study-review.md: seminar-discussion.C1.evidence',
        },
      ],
      [
        'alternative',
        'suggest-alternative',
        'How could an alternative arrangement test whether the important feature is quietness rather than the corner itself?',
        '提出比较思路，不冒充因果实验已进行。',
        'period',
        'We could compare experiences during a quiet period elsewhere, while noting the other conditions that differ.',
        'portable',
        'We could try a movable quiet area and ask whether users value its location or the conditions it creates.',
        {
          state: 'model-reviewed',
          record: 'study-review.md: seminar-discussion.C1.alternative',
        },
      ],
      [
        'response',
        'respond-to-proposal',
        'Jo claims that “any exception to equal time is unfair”. How would you challenge or qualify that claim?',
        '具体原则冲突。',
        'distinction',
        'That treats identical treatment as the only form of fairness; I would ask whether justified differences in need should count for anything.',
        'rule',
        'I can see the value of a clear rule, but an exception with transparent reasons need not amount to arbitrary favouritism.',
        {
          state: 'model-reviewed',
          record: 'study-review.md: seminar-discussion.C1.response',
        },
      ],
      [
        'synthesis',
        'identify-shared-question',
        'How could you bring the fairness and usefulness questions together without pretending they are the same question?',
        '整合但保留不同判断标准。',
        'separate',
        'We could assess who benefits and who has access separately, then examine where the two assessments pull in different directions.',
        'tradeoff',
        'I would identify which access rule supports which benefit, making the trade-off visible rather than calling one arrangement simply “best”.',
        {
          state: 'model-reviewed',
          record: 'study-review.md: seminar-discussion.C1.synthesis',
        },
      ],
      [
        'open',
        'ask-missing-detail',
        'What would you still need to know before calling the arrangement inclusive?',
        '追问未被代表的人群或机会。',
        'nonusers',
        'I would want to hear from students who do not use it, especially whether that reflects preference or an obstacle.',
        'opportunity',
        'I would need to know whether the students most likely to benefit have a genuine opportunity to use it at the times that matter.',
        {
          state: 'model-reviewed',
          record: 'study-review.md: seminar-discussion.C1.open',
        },
      ],
      [
        'next',
        'choose-next-step',
        'How would you close without implying that everyone has agreed on the corner?',
        '短练未必出现异议，也不虚构共同结论。',
        'questions',
        'I would keep questions about access and benefit open until we have a basis for choosing an arrangement.',
        'criteria',
        'The next useful step is to agree how competing arrangements would be judged, rather than force agreement on the corner itself.',
        {
          state: 'model-reviewed',
          record: 'study-review.md: seminar-discussion.C1.next',
        },
      ],
      [
        'turn',
        'manage-turn',
        'How could you prevent an invitation to dissent from becoming a demand that one quiet person represent an entire group?',
        '具体互动管理风险。',
        'individual',
        'I would invite individual perspectives without assigning anyone the role of speaking for others who share a characteristic.',
        'channels',
        'I would offer several ways to contribute and avoid treating silence in the room as either consent or absence of a view.',
        {
          state: 'model-reviewed',
          record: 'study-review.md: seminar-discussion.C1.turn',
        },
      ],
      [
        'term',
        'ask-word-meaning',
        'What would you clarify when someone calls the corner “effective” but names no intended outcome?',
        '术语未给目标，真实澄清必要。',
        'outcome',
        'Effective at enabling quiet reading, improving concentration, or making students feel welcome? Those are distinct outcomes.',
        'comparison',
        'Effective compared with what alternative, and under which classroom conditions? The term needs a reference point.',
        {
          state: 'model-reviewed',
          record: 'study-review.md: seminar-discussion.C1.term',
        },
      ],
    ],
    variantRead.C1,
  ),
}
