import { emergencyPack, type EmergencyScene } from './authoring'
const scene: EmergencyScene = {
  sceneId: 'emergency-02',
  slug: 'describe-symptoms',
  situations: [
    '症状描述英语模拟，不是真实问诊。练习搭档只记录你选用的虚构症状、时间及感受，不诊断或判断轻重。虚构时间为下午，角色已坐在椅子上；桌上有身体图和空白时间卡。所有参考答案都是可选择的虚构角色事实，不需要说自己的真实健康状况；角色可不知道日期或原因。先口头描述，再考虑如何整理信息。本练习不会联系真实医疗或紧急服务，也不提供治疗或急救。',
    '症状信息留言模拟。练习搭档帮你拟一段尚未发送的描述，虚构时间为下午，角色已坐在椅子上；桌上有身体图、空白时间卡和纸笔。你只需采用参考答案中的虚构情况，重点是区分观察到的变化、个人感受与不知道的部分。没有医生在此作答，不填写真实身份或联系方式。本练习不会发送信息、联系真实医疗或紧急服务，也不提供诊断或处理建议。',
  ],
  paths: [
    {
      short: ['feeling', 'onset', 'next'],
      standard: ['feeling', 'onset', 'pattern', 'activity', 'format', 'next'],
      extended: [
        'feeling',
        'onset',
        'pattern',
        'activity',
        'duration',
        'change',
        'record',
        'format',
        'uncertain',
        'next',
      ],
    },
    {
      short: ['feeling', 'location', 'next'],
      standard: ['feeling', 'location', 'onset', 'support', 'format', 'next'],
      extended: [
        'feeling',
        'location',
        'onset',
        'pattern',
        'activity',
        'support',
        'change',
        'format',
        'uncertain',
        'next',
      ],
    },
  ],
  closing:
    'The symptom-description practice is complete, without a diagnosis or assessment of severity. No real medical or emergency service was contacted.',
  partial:
    'We will stop with some symptom details unconfirmed. No real medical or emergency service was contacted, and this was not an assessment.',
  repairs: {
    clarify: 'You can ask which detail this description question needs.',
    struggle: 'A short phrase about the fictional person is enough.',
    offTopic: 'Let us return to describing the fictional experience.',
    unknown:
      'That wording is not covered locally; no symptom meaning or severity has been inferred.',
    changed: 'Your new description replaces the earlier practice detail.',
    refusedClosing:
      'The symptom practice has stopped. No real service was contacted; you do not need to share personal health information.',
  },
}
export const describeSymptoms = {
  A1: emergencyPack(
    scene,
    'A1',
    {
      canDoZh: '用短句说虚构人物哪里不舒服、什么时候开始。',
      complexityZh: '具体身体词、时间词与一个简单感受，不需分析原因或轻重。',
      scaffoldingZh: '身体图、时间卡和完整简短答句支架；不知道也是可用回答。',
      registerZh: '简单直接的描述口语，不作诊断。',
    },
    [
      [
        'feeling',
        'describe-feeling',
        'How do you feel in this practice?',
        '选择虚构感受。',
        'head',
        'My head hurts.',
        'tired',
        'I feel tired.',
        {
          state: 'model-reviewed',
          record: 'emergency-review.md: describe-symptoms.A1.feeling',
        },
      ],
      [
        'onset',
        'give-onset',
        'When did you start to feel this way?',
        '选择虚构开始时间。',
        'today',
        'It started today.',
        'yesterday',
        'It started yesterday.',
        {
          state: 'model-reviewed',
          record: 'emergency-review.md: describe-symptoms.A1.onset',
        },
      ],
      [
        'pattern',
        'describe-pattern',
        'Do you feel this way all the time?',
        '说持续或反复。',
        'constant',
        'Yes, all the time.',
        'sometimes',
        'No, only sometimes.',
        {
          state: 'model-reviewed',
          record: 'emergency-review.md: describe-symptoms.A1.pattern',
        },
      ],
      [
        'activity',
        'describe-impact',
        'Is reading easy for you today?',
        '描述活动，不评价病情。',
        'hard',
        'No, reading is hard today.',
        'easy',
        'Yes, I can read easily.',
        {
          state: 'model-reviewed',
          record: 'emergency-review.md: describe-symptoms.A1.activity',
        },
      ],
      [
        'duration',
        'give-observation-period',
        'How long have you been sitting here?',
        '只问独立的观察时间。',
        'ten',
        'For ten minutes.',
        'five',
        'For five minutes.',
        {
          state: 'model-reviewed',
          record: 'emergency-review.md: describe-symptoms.A1.duration',
        },
      ],
      [
        'change',
        'report-change',
        'Do you feel the same as before?',
        '陈述主观变化。',
        'same',
        'Yes, I feel the same.',
        'different',
        'No, I feel different now.',
        {
          state: 'model-reviewed',
          record: 'emergency-review.md: describe-symptoms.A1.change',
        },
      ],
      [
        'record',
        'offer-notes',
        'Do you have notes about how you feel?',
        '说明记录状态。',
        'notes',
        'Yes, I have notes.',
        'none',
        'No, I have no notes.',
        {
          state: 'model-reviewed',
          record: 'emergency-review.md: describe-symptoms.A1.record',
        },
      ],
      [
        'format',
        'choose-description-format',
        'Do you want to speak or write your description?',
        '选择表达方式。',
        'speak',
        'I want to speak.',
        'write',
        'I want to write it.',
        {
          state: 'model-reviewed',
          record: 'emergency-review.md: describe-symptoms.A1.format',
        },
      ],
      [
        'uncertain',
        'state-unknown',
        'Do you know why you feel this way?',
        '原因可以不知道。',
        'unknown',
        'No, I do not know why.',
        'unsure',
        'I have an idea, but I am not sure.',
        {
          state: 'model-reviewed',
          record: 'emergency-review.md: describe-symptoms.A1.uncertain',
        },
      ],
      [
        'location',
        'add-discomfort-detail',
        'Is there anything else you want to describe?',
        '询问其他不适，不假定疲倦必然伴有疼痛。',
        'neck',
        'Yes, my neck hurts.',
        'none',
        'No, nothing else.',
        {
          state: 'model-reviewed',
          record: 'emergency-review.md: describe-symptoms.A1.location',
        },
      ],
      [
        'support',
        'request-description-support',
        'Would a body picture help you explain?',
        '不假定表达困难已解决。',
        'picture',
        'Yes, a picture would help.',
        'words',
        'No, I want to use words.',
        {
          state: 'model-reviewed',
          record: 'emergency-review.md: describe-symptoms.A1.support',
        },
      ],
      [
        'next',
        'plan-description-check',
        'What would you like to do with your description?',
        '练习后续，不联系服务。',
        'read',
        'I would like to read it.',
        'add',
        'I would like to add a detail.',
        {
          state: 'model-reviewed',
          record: 'emergency-review.md: describe-symptoms.A1.next',
        },
      ],
    ],
    {
      state: 'model-reviewed',
      record: 'emergency-review.md: describe-symptoms.A1 variants',
    },
  ),
  A2: emergencyPack(
    scene,
    'A2',
    {
      canDoZh: '按时间顺序交代简单症状经历并请求描述帮助。',
      complexityZh: '说持续或间歇及对活动的影响，区分知道和不确定。',
      scaffoldingZh: '明确的时间与身体图支持简短两句表达。',
      registerZh: '日常清楚的健康沟通语言，无病情推断。',
    },
    [
      [
        'feeling',
        'describe-feeling',
        'What would you like to tell someone about how you feel?',
        '使用虚构描述。',
        'ache',
        'I have an ache in my shoulder.',
        'tired',
        'I feel tired, even after sitting down.',
        {
          state: 'model-reviewed',
          record: 'emergency-review.md: describe-symptoms.A2.feeling',
        },
      ],
      [
        'onset',
        'give-onset',
        'Did this feeling begin this morning or earlier?',
        '给开始时间。',
        'morning',
        'It began this morning after breakfast.',
        'earlier',
        'It began yesterday afternoon.',
        {
          state: 'model-reviewed',
          record: 'emergency-review.md: describe-symptoms.A2.onset',
        },
      ],
      [
        'pattern',
        'describe-pattern',
        'Is the feeling always there, or does it come and go?',
        '区分时间模式。',
        'constant',
        'It is there all the time.',
        'intermittent',
        'It comes and goes during the day.',
        {
          state: 'model-reviewed',
          record: 'emergency-review.md: describe-symptoms.A2.pattern',
        },
      ],
      [
        'activity',
        'describe-impact',
        'Has this made your usual reading difficult?',
        '影响可有可无。',
        'difficult',
        'Yes, I find it difficult to read for long.',
        'unchanged',
        'No, I can read as usual.',
        {
          state: 'model-reviewed',
          record: 'emergency-review.md: describe-symptoms.A2.activity',
        },
      ],
      [
        'duration',
        'give-observation-period',
        'How much time have you spent resting in this chair?',
        '不是再次问症状开始时间。',
        'half',
        'I have been here for half an hour.',
        'brief',
        'I sat down about five minutes ago.',
        {
          state: 'model-reviewed',
          record: 'emergency-review.md: describe-symptoms.A2.duration',
        },
      ],
      [
        'change',
        'report-change',
        'Compared with an hour ago, how do you feel now?',
        '按虚构比较描述，不评轻重。',
        'same',
        'I feel about the same as an hour ago.',
        'changed',
        'The feeling is different, but it is hard to describe.',
        {
          state: 'model-reviewed',
          record: 'emergency-review.md: describe-symptoms.A2.change',
        },
      ],
      [
        'record',
        'offer-notes',
        'Did you write down the time or keep it in your memory?',
        '只说明记录来源。',
        'written',
        'I wrote it down on a piece of paper.',
        'memory',
        'I remember it, but I did not write it down.',
        {
          state: 'model-reviewed',
          record: 'emergency-review.md: describe-symptoms.A2.record',
        },
      ],
      [
        'format',
        'choose-description-format',
        'Would you rather give a short spoken description or write a few lines?',
        '形式偏好。',
        'spoken',
        'I would rather say it in a few short sentences.',
        'written',
        'I would rather write a few lines first.',
        {
          state: 'model-reviewed',
          record: 'emergency-review.md: describe-symptoms.A2.format',
        },
      ],
      [
        'uncertain',
        'state-unknown',
        'Which detail would you need to check before giving a clear answer?',
        '承认未确认的信息。',
        'time',
        'I need to check the exact time.',
        'previous',
        'I need to check whether this happened before.',
        {
          state: 'model-reviewed',
          record: 'emergency-review.md: describe-symptoms.A2.uncertain',
        },
      ],
      [
        'location',
        'add-discomfort-detail',
        'Is there discomfort in any other area?',
        '只补充其他部位，不改写主要感受。',
        'area',
        'Yes, there is also discomfort in my lower back.',
        'none',
        'No, there is no other area to describe.',
        {
          state: 'model-reviewed',
          record: 'emergency-review.md: describe-symptoms.A2.location',
        },
      ],
      [
        'support',
        'request-description-support',
        'How could the practice partner help you find the words?',
        '提出具体语言帮助。',
        'picture',
        'Please let me use the body picture.',
        'time',
        'Please give me a moment to think of the words.',
        {
          state: 'model-reviewed',
          record: 'emergency-review.md: describe-symptoms.A2.support',
        },
      ],
      [
        'next',
        'plan-description-check',
        'How would you like to check your symptom message before keeping it?',
        '计划核对，不声称已执行。',
        'listen',
        'I would like to hear the message read aloud.',
        'reread',
        'I would like to read it myself and check the details.',
        {
          state: 'model-reviewed',
          record: 'emergency-review.md: describe-symptoms.A2.next',
        },
      ],
    ],
    {
      state: 'model-reviewed',
      record: 'emergency-review.md: describe-symptoms.A2 variants',
    },
  ),
  B1: emergencyPack(
    scene,
    'B1',
    {
      canDoZh: '连贯描述症状出现及变化，并说明记忆和表达的局限。',
      complexityZh: '处理非例行感受、活动影响和资料来源，不把同时发生当因果。',
      scaffoldingZh: '问题把时间、模式、影响分开，允许不能确定的完整回答。',
      registerZh: '中性描述口语，以具体观察代替病名判断。',
    },
    [
      [
        'feeling',
        'describe-feeling',
        'How would you describe the feeling without trying to name its cause?',
        '说明体验，不诊断。',
        'tight',
        'There is a tight feeling across my shoulders.',
        'drained',
        'I feel unusually tired and find it hard to concentrate.',
        {
          state: 'model-reviewed',
          record: 'emergency-review.md: describe-symptoms.B1.feeling',
        },
      ],
      [
        'onset',
        'give-onset',
        'What were you doing when you first noticed the feeling?',
        '时间背景不等于原因。',
        'reading',
        'I first noticed it while I was reading yesterday evening.',
        'waking',
        'I noticed it when I woke up this morning.',
        {
          state: 'model-reviewed',
          record: 'emergency-review.md: describe-symptoms.B1.onset',
        },
      ],
      [
        'pattern',
        'describe-pattern',
        'What have you noticed about whether the feeling continues or returns?',
        '描述持续模式。',
        'continuous',
        'It has been present whenever I have paid attention to it.',
        'returns',
        'It disappears for a while and then comes back.',
        {
          state: 'model-reviewed',
          record: 'emergency-review.md: describe-symptoms.B1.pattern',
        },
      ],
      [
        'activity',
        'describe-impact',
        'What difference has the feeling made to an ordinary activity?',
        '选择具体影响或无影响。',
        'breaks',
        'I have needed more breaks while reading than I normally do.',
        'normal',
        'It has not changed how long I can read so far.',
        {
          state: 'model-reviewed',
          record: 'emergency-review.md: describe-symptoms.B1.activity',
        },
      ],
      [
        'duration',
        'give-observation-period',
        'Over what period have you been paying close attention to changes?',
        '观察区间和起病时间分开。',
        'hour',
        'I have been paying close attention for the past hour.',
        'brief',
        'Only since I sat down a few minutes ago.',
        {
          state: 'model-reviewed',
          record: 'emergency-review.md: describe-symptoms.B1.duration',
        },
      ],
      [
        'change',
        'report-change',
        'What can you say about any change since you began paying attention?',
        '可报告没有变化。',
        'same',
        'I have not noticed a clear change during that time.',
        'different',
        'The feeling is less noticeable now than when I first paid attention.',
        {
          state: 'model-reviewed',
          record: 'emergency-review.md: describe-symptoms.B1.change',
        },
      ],
      [
        'record',
        'offer-notes',
        'What is your account based on: notes or memory?',
        '说明证据来源。',
        'notes',
        'I made short notes at the time, so I can refer to them.',
        'memory',
        'It is based on memory, and the timings may not be exact.',
        {
          state: 'model-reviewed',
          record: 'emergency-review.md: describe-symptoms.B1.record',
        },
      ],
      [
        'format',
        'choose-description-format',
        'How would you organise the description so someone could follow it?',
        '选择叙述结构。',
        'time',
        'I would start with when I noticed it and describe the changes in order.',
        'impact',
        'I would describe the feeling first, then explain its effect on my day.',
        {
          state: 'model-reviewed',
          record: 'emergency-review.md: describe-symptoms.B1.format',
        },
      ],
      [
        'uncertain',
        'state-unknown',
        'How would you answer if someone asked whether an activity caused the feeling?',
        '不从相关性推断原因。',
        'unknown',
        'I noticed both at about the same time, but I do not know whether they are connected.',
        'check',
        'I cannot say what caused it; I would need to discuss that question with a professional.',
        {
          state: 'model-reviewed',
          record: 'emergency-review.md: describe-symptoms.B1.uncertain',
        },
      ],
      [
        'location',
        'add-discomfort-detail',
        'Is there any discomfort you have not yet mentioned?',
        '可补充也可明确没有其他部位。',
        'specific',
        'There is also a small uncomfortable area just below my right shoulder.',
        'none',
        'There is no other area of discomfort that I need to add.',
        {
          state: 'model-reviewed',
          record: 'emergency-review.md: describe-symptoms.B1.location',
        },
      ],
      [
        'support',
        'request-description-support',
        'What would help if you could describe the feeling in your own language but not in English?',
        '语言障碍可以求助。',
        'compare',
        'I would try a comparison, such as saying it feels like pressure.',
        'picture',
        'I would use the picture and ask for help finding the English words.',
        {
          state: 'model-reviewed',
          record: 'emergency-review.md: describe-symptoms.B1.support',
        },
      ],
      [
        'next',
        'plan-description-check',
        'What would you want to check before treating the wording as a finished description?',
        '描述完成不等于问诊完成。',
        'facts',
        'I would check that the times and changes match what I meant to say.',
        'uncertainty',
        'I would check that uncertain details still sound uncertain.',
        {
          state: 'model-reviewed',
          record: 'emergency-review.md: describe-symptoms.B1.next',
        },
      ],
    ],
    {
      state: 'model-reviewed',
      record: 'emergency-review.md: describe-symptoms.B1 variants',
    },
  ),
  B2: emergencyPack(
    scene,
    'B2',
    {
      canDoZh: '区分主观体验、可观察变化及推测，组织可追问的详细描述。',
      complexityZh: '比较资料可靠度，避免时间重合与因果混淆，并协商表达结构。',
      scaffoldingZh: '有明确的独立记录样例及观察区间，双选句保留不同确定程度。',
      registerZh: '准确但不临床化的描述语域，解释表达选择的理由。',
    },
    [
      [
        'feeling',
        'describe-feeling',
        'Which description best captures the experience you want to communicate?',
        '精确描述体验而非评估风险。',
        'pressure',
        'It feels like pressure rather than a sharp pain, although I find that distinction difficult to express.',
        'fatigue',
        'The main issue is a sense of exhaustion that makes sustained concentration difficult.',
        {
          state: 'model-reviewed',
          record: 'emergency-review.md: describe-symptoms.B2.feeling',
        },
      ],
      [
        'onset',
        'give-onset',
        'How would you distinguish when the feeling began from when you first noticed it?',
        '不把首次注意等同起始。',
        'noticed',
        'I first noticed it during breakfast, but I cannot say whether it had started earlier.',
        'witnessed',
        'I was paying attention when the feeling began, so I can give an approximate starting time.',
        {
          state: 'model-reviewed',
          record: 'emergency-review.md: describe-symptoms.B2.onset',
        },
      ],
      [
        'pattern',
        'describe-pattern',
        'How would you describe the pattern without suggesting you monitored it continuously?',
        '反复观察不是全天监测。',
        'checks',
        'It was present each time I checked, though I was not watching for it every minute.',
        'intervals',
        'I noticed several separate episodes, with periods when I did not feel it.',
        {
          state: 'model-reviewed',
          record: 'emergency-review.md: describe-symptoms.B2.pattern',
        },
      ],
      [
        'activity',
        'describe-impact',
        'Which everyday effect would give a listener a concrete picture of the difficulty?',
        '以活动为描述例子，不给分诊标准。',
        'reading',
        'I usually read for half an hour, but today I stopped after a few pages because concentrating was difficult.',
        'none',
        'My reading routine has not changed; the unusual feeling is what I want to describe.',
        {
          state: 'model-reviewed',
          record: 'emergency-review.md: describe-symptoms.B2.activity',
        },
      ],
      [
        'duration',
        'give-observation-period',
        'What limit should be placed on the period covered by your observations?',
        '指出观察范围。',
        'recent',
        'My account of changes covers the past hour, not the whole day.',
        'occasional',
        'I only checked occasionally this afternoon, so I cannot describe the gaps confidently.',
        {
          state: 'model-reviewed',
          record: 'emergency-review.md: describe-symptoms.B2.duration',
        },
      ],
      [
        'change',
        'report-change',
        'What comparison can you make without turning a personal impression into a measurement?',
        '主观比较有其限度。',
        'impression',
        'It seems less noticeable now, but that is my impression rather than a measured change.',
        'stable',
        'I have not detected a difference, though my description may miss small changes.',
        {
          state: 'model-reviewed',
          record: 'emergency-review.md: describe-symptoms.B2.change',
        },
      ],
      [
        'record',
        'offer-notes',
        'How would you handle a discrepancy between a written time and your recollection?',
        '假设差异，不捏造已核对。',
        'both',
        'I would report both and explain that I am unsure which is accurate.',
        'check',
        'I would check the original note before presenting either time as settled.',
        {
          state: 'model-reviewed',
          record: 'emergency-review.md: describe-symptoms.B2.record',
        },
      ],
      [
        'format',
        'choose-description-format',
        'Would a timeline or a description organised by activity make your account clearer?',
        '组织方式有不同用途。',
        'timeline',
        'A timeline would help distinguish the first observation from the later changes.',
        'activity',
        'An activity-based account would make the practical effect clearer, with times added where I know them.',
        {
          state: 'model-reviewed',
          record: 'emergency-review.md: describe-symptoms.B2.format',
        },
      ],
      [
        'uncertain',
        'state-unknown',
        'If two events happened together, how would you avoid presenting their connection as established?',
        '明确区分观察与解释。',
        'sequence',
        'I would describe the sequence and say that I do not know whether one affected the other.',
        'question',
        'I would raise the possible connection as a question rather than build it into the description as a fact.',
        {
          state: 'model-reviewed',
          record: 'emergency-review.md: describe-symptoms.B2.uncertain',
        },
      ],
      [
        'location',
        'locate-discomfort',
        'How precisely could you describe the location of any discomfort?',
        '用范围限定具体位置。',
        'approximate',
        'It is roughly around the upper back, but I cannot draw a precise boundary.',
        'specific',
        'I can identify one clear spot; I would point to it rather than use a broader term.',
        {
          state: 'model-reviewed',
          record: 'emergency-review.md: describe-symptoms.B2.location',
        },
      ],
      [
        'support',
        'request-description-support',
        'What would you ask for if a suggested word did not quite match the experience?',
        '假设词汇不合适，不承诺翻译能力。',
        'contrast',
        'Could I explain how it differs from that word before we choose another one?',
        'own',
        'Could we keep my own description for now rather than force it into a single term?',
        {
          state: 'model-reviewed',
          record: 'emergency-review.md: describe-symptoms.B2.support',
        },
      ],
      [
        'next',
        'plan-description-check',
        'What would make the final wording a faithful account rather than a polished guess?',
        '语言清晰不应新增事实。',
        'limits',
        'It should preserve the gaps in my knowledge even if that makes the account less tidy.',
        'comparison',
        'I would compare it with my notes and remove any detail that I cannot support.',
        {
          state: 'model-reviewed',
          record: 'emergency-review.md: describe-symptoms.B2.next',
        },
      ],
    ],
    {
      state: 'model-reviewed',
      record: 'emergency-review.md: describe-symptoms.B2 variants',
    },
  ),
  C1: emergencyPack(
    scene,
    'C1',
    {
      canDoZh:
        '自然限定观察、回忆及措辞近似值，把复杂体验整理得清楚且不过度断言。',
      complexityZh:
        '协调叙事顺序、信息出处及表达不充分之处，保留可供后续专业人员追问的空间。',
      scaffoldingZh:
        '给出明确的语词选择和记录差异问题；不要求学习者扮演临床评估者。',
      registerZh: 'CEFR C1 的精确限定与修复，避免堆叠诊断免责声明。',
    },
    [
      [
        'feeling',
        'describe-feeling',
        'How would you convey the character of the sensation when no single familiar term seems adequate?',
        '允许描述比喻，不将其变成诊断。',
        'contrast',
        'Pressure comes closest, although that misses the intermittent pulling sensation I also notice.',
        'plain',
        'I would describe what it feels like in ordinary words rather than choose a technical term that might be misleading.',
        {
          state: 'model-reviewed',
          record: 'emergency-review.md: fix1 describe-symptoms.C1.feeling',
        },
      ],
      [
        'onset',
        'give-onset',
        'How would you preserve the distinction between the onset of the experience and the first point you can reliably place in time?',
        '时间精确度不能超过记忆。',
        'anchor',
        'The first point I can place reliably is breakfast; that anchors my account without establishing when the feeling actually began.',
        'approximate',
        'I recall the feeling beginning during the morning, but giving a precise minute would overstate my recollection.',
        {
          state: 'model-reviewed',
          record: 'emergency-review.md: fix1 describe-symptoms.C1.onset',
        },
      ],
      [
        'pattern',
        'describe-pattern',
        'What qualification would keep a description of recurrence accurate despite gaps in your attention?',
        '留意的间隙不等于无症状。',
        'gaps',
        'I noticed it returning several times, but I cannot tell whether it disappeared completely during the gaps in my attention.',
        'episodes',
        'There were distinct periods when I felt it and periods when I did not; I would describe those rather than imply uninterrupted monitoring.',
        {
          state: 'model-reviewed',
          record: 'emergency-review.md: fix1 describe-symptoms.C1.pattern',
        },
      ],
      [
        'activity',
        'describe-impact',
        'How could a comparison with your ordinary routine clarify the impact without implying a clinical judgement?',
        '具体生活比较，不设严重程度阈值。',
        'routine',
        'I normally finish a chapter in one sitting; today I kept losing my place, which conveys the difficulty more clearly than simply saying I felt bad.',
        'unchanged',
        'My routine has remained unchanged, so I would not invent a functional limitation just to make the account sound more substantial.',
        {
          state: 'model-reviewed',
          record: 'emergency-review.md: fix1 describe-symptoms.C1.activity',
        },
      ],
      [
        'duration',
        'give-observation-period',
        'How would you make the coverage of your observations transparent to the listener?',
        '说明实际观察范围与空白。',
        'bounded',
        'The detailed observations cover only the last hour; anything before that is a less precise recollection.',
        'uneven',
        'My notes cover a few moments across the afternoon, not a continuous record of everything between them.',
        {
          state: 'model-reviewed',
          record: 'emergency-review.md: fix1 describe-symptoms.C1.duration',
        },
      ],
      [
        'change',
        'report-change',
        'How would you express a perceived change while separating its direction from the confidence you have in it?',
        '变化描述与可信程度分开。',
        'tentative',
        'It seems to have become less noticeable, but I am not confident enough to describe a steady improvement.',
        'none',
        'I cannot identify a consistent change; the variation in my descriptions may reflect how difficult the sensation is to put into words.',
        {
          state: 'model-reviewed',
          record: 'emergency-review.md: fix1 describe-symptoms.C1.change',
        },
      ],
      [
        'record',
        'offer-notes',
        'If your notes and recollection differed, how would you present the discrepancy without silently resolving it?',
        '明确的假设，不冒充已检查。',
        'preserve',
        'I would preserve both versions, identify their sources and flag the time as unresolved.',
        'defer',
        'I would leave the exact time open until I could examine the original note, rather than choose the version that sounds more plausible.',
        {
          state: 'model-reviewed',
          record: 'emergency-review.md: fix1 describe-symptoms.C1.record',
        },
      ],
      [
        'format',
        'choose-description-format',
        'How would you organise the timeline alongside an account of whether your routine changed?',
        '组织时间线，并保留日常活动可能未受影响的情况。',
        'chronology',
        'I would use chronology as the main thread, stating at the relevant point whether there was any effect on my routine.',
        'summary',
        'I would begin by saying whether my routine changed, then give a separate timeline so the two kinds of information remain distinguishable.',
        {
          state: 'model-reviewed',
          record: 'emergency-review.md: fix1 describe-symptoms.C1.format',
        },
      ],
      [
        'uncertain',
        'state-unknown',
        'How would you raise a possible connection that matters to you without embedding it as an explanation?',
        '推测以问题形式提出。',
        'question',
        'I would explain why the timing caught my attention and ask whether the two events might be connected.',
        'separate',
        'I would report the two events separately, then identify the possible link as my question rather than part of the observed account.',
        {
          state: 'model-reviewed',
          record: 'emergency-review.md: fix1 describe-symptoms.C1.uncertain',
        },
      ],
      [
        'location',
        'locate-discomfort',
        'How could you convey an imprecise location without making the whole description vague?',
        '在精确和不确定之间划界。',
        'anchor',
        'I can identify the general area around my left shoulder, while making clear that the sensation does not have a sharply defined edge.',
        'contrast',
        'I would distinguish the spot I can point to from the wider area that only sometimes feels uncomfortable.',
        {
          state: 'model-reviewed',
          record: 'emergency-review.md: fix1 describe-symptoms.C1.location',
        },
      ],
      [
        'support',
        'request-description-support',
        'In a separate example, a speaker describes “pressure and pulling” but a listener repeats only “pressure”; how could the speaker clarify?',
        '独立样例明确提供两种感受，不把前面未说的细节当事实。',
        'partial',
        'That captures the pressure, but not the pulling feeling; could we retain both descriptions for now?',
        'qualify',
        'I could use that word as an approximation, provided the rest of my description is not lost.',
        {
          state: 'model-reviewed',
          record: 'emergency-review.md: fix1 describe-symptoms.C1.support',
        },
      ],
      [
        'next',
        'plan-description-check',
        'What would you preserve in the final account even if removing it made the narrative sound smoother?',
        '保留有意义的限制而非追求虚假完整。',
        'gaps',
        'I would preserve the uncertain timings and gaps in observation, since a seamless account would imply knowledge I do not have.',
        'wording',
        'I would preserve the distinction between my own words and any suggested terminology, so the listener can see where the wording is approximate.',
        {
          state: 'model-reviewed',
          record: 'emergency-review.md: fix1 describe-symptoms.C1.next',
        },
      ],
    ],
    {
      state: 'model-reviewed',
      record: 'emergency-review.md: fix1 describe-symptoms.C1 variants',
    },
  ),
}
