import { emergencyPack, type EmergencyScene } from './authoring'
const scene: EmergencyScene = {
  sceneId: 'emergency-03',
  slug: 'doctor-appointment',
  situations: [
    '虚构诊所预约英语演练；练习搭档扮演接待员。纸卡仅展示供练习选择的周二上午、周四下午以及电话或当面咨询形式，不是真实空位或临床推荐。示例卡写有 arrival time 和 appointment time 两个栏位，但没有默认时间。你可以使用参考答案的虚构偏好，不提供真实姓名、证件、联系方式或病历。本轮仅准备预约请求，不做分诊、不确认真实预约、不联系医疗或紧急服务。',
    '虚构诊所留言练习。接待员角色帮助整理尚未发送的预约请求，纸上有周二上午与周四下午两项示例时段，以及电话和当面形式。arrival time 与 appointment time 是示例表的不同栏位。重点在于时间限制、需询问事项及回信形式；所有选项只是练习素材，不代表可用名额。不填写真实身份或联系方式，不发送留言，不作分诊或联系真实医疗和紧急服务。',
  ],
  paths: [
    {
      short: ['purpose', 'time', 'next'],
      standard: ['purpose', 'time', 'format', 'constraint', 'reply', 'next'],
      extended: [
        'purpose',
        'time',
        'format',
        'constraint',
        'access',
        'privacy',
        'reply',
        'notice',
        'question',
        'next',
      ],
    },
    {
      short: ['purpose', 'clarify', 'next'],
      standard: ['purpose', 'time', 'clarify', 'record', 'reply', 'next'],
      extended: [
        'purpose',
        'time',
        'format',
        'constraint',
        'clarify',
        'record',
        'reply',
        'notice',
        'question',
        'next',
      ],
    },
  ],
  closing:
    'The appointment-request practice is complete. Preferred times and formats are requests only. No real appointment was booked or medical or emergency service contacted.',
  partial:
    'Some appointment-request details remain unconfirmed in this practice. No real appointment was booked or service contacted.',
  repairs: {
    clarify: 'You can ask which appointment detail this question is about.',
    struggle: 'You can use one of the fictional time or request examples.',
    offTopic: 'We can return to preparing the appointment request.',
    unknown:
      'That wording is not covered locally, so no appointment detail has been confirmed.',
    changed: 'Your new request replaces the previous choice in this practice.',
    refusedClosing:
      'The appointment practice has stopped. No real appointment was booked or service contacted.',
  },
}
export const doctorAppointment = {
  A1: emergencyPack(
    scene,
    'A1',
    {
      canDoZh: '借助时段卡提出简单预约需要。',
      complexityZh: '逐次选目的、时间和形式，不判断医疗需求等级。',
      scaffoldingZh: '虚构选项可见，短问短答和中文提示支持。',
      registerZh: '基础礼貌接待口语，可说不能或不知道。',
    },
    [
      [
        'purpose',
        'state-booking-purpose',
        'What do you want to ask the clinic for?',
        '只是提出请求。',
        'visit',
        'I want an appointment.',
        'information',
        'I want information about appointments.',
        {
          state: 'model-reviewed',
          record: 'emergency-review.md: doctor-appointment.A1.purpose',
        },
      ],
      [
        'time',
        'request-time',
        'Which time on the card do you prefer?',
        '虚构时段不是预约确认。',
        'tuesday',
        'Tuesday morning, please.',
        'thursday',
        'Thursday afternoon, please.',
        {
          state: 'model-reviewed',
          record: 'emergency-review.md: doctor-appointment.A1.time',
        },
      ],
      [
        'format',
        'request-format',
        'Do you prefer a phone call or a visit?',
        '表达形式偏好。',
        'phone',
        'A phone call, please.',
        'visit',
        'A visit, please.',
        {
          state: 'model-reviewed',
          record: 'emergency-review.md: doctor-appointment.A1.format',
        },
      ],
      [
        'constraint',
        'state-availability',
        'Can you come before nine?',
        '独立说明时间限制。',
        'yes',
        'Yes, I can come before nine.',
        'no',
        'No, I cannot come before nine.',
        {
          state: 'model-reviewed',
          record: 'emergency-review.md: doctor-appointment.A1.constraint',
        },
      ],
      [
        'access',
        'request-access-information',
        'Do you need information about the clinic entrance?',
        '不要求真实位置。',
        'yes',
        'Yes, I need a picture.',
        'no',
        'No, I have a picture.',
        {
          state: 'model-reviewed',
          record: 'emergency-review.md: doctor-appointment.A1.access',
        },
      ],
      [
        'privacy',
        'set-information-boundary',
        'Do you want to share personal details in this practice?',
        '可以保留隐私。',
        'fiction',
        'I want to use made-up details.',
        'none',
        'No personal details, please.',
        {
          state: 'model-reviewed',
          record: 'emergency-review.md: doctor-appointment.A1.privacy',
        },
      ],
      [
        'reply',
        'choose-reply-style',
        'Would you like a short reply or a detailed reply?',
        '模拟回信形式。',
        'short',
        'A short reply, please.',
        'detailed',
        'A detailed reply, please.',
        {
          state: 'model-reviewed',
          record: 'emergency-review.md: doctor-appointment.A1.reply',
        },
      ],
      [
        'notice',
        'ask-change-information',
        'Do you want to ask about changing a time?',
        '未预约也可以先询问变更方式。',
        'yes',
        'Yes, I want to ask about changes.',
        'no',
        'No, not now.',
        {
          state: 'model-reviewed',
          record: 'emergency-review.md: doctor-appointment.A1.notice',
        },
      ],
      [
        'question',
        'ask-arrival-information',
        'For a possible visit, what would you like to ask about arriving?',
        '只问，不捏造诊所流程。',
        'where',
        'Where should I go?',
        'when',
        'When should I arrive?',
        {
          state: 'model-reviewed',
          record: 'emergency-review.md: doctor-appointment.A1.question',
        },
      ],
      [
        'clarify',
        'clarify-time-label',
        'Which word on the card is unclear?',
        '明确示例词已呈现。',
        'arrival',
        'I do not know “arrival”.',
        'appointment',
        'I do not know “appointment”.',
        {
          state: 'model-reviewed',
          record: 'emergency-review.md: doctor-appointment.A1.clarify',
        },
      ],
      [
        'record',
        'prepare-request-notes',
        'Do you have paper for your request?',
        '只说明物件是否在手。',
        'paper',
        'Yes, I have paper.',
        'none',
        'No, I need some paper.',
        {
          state: 'model-reviewed',
          record: 'emergency-review.md: doctor-appointment.A1.record',
        },
      ],
      [
        'next',
        'finish-request',
        'Do you want to write or say an appointment request?',
        '计划表达，不假定已有书面请求。',
        'write',
        'I want to write one.',
        'say',
        'I want to say one.',
        {
          state: 'model-reviewed',
          record: 'emergency-review.md: doctor-appointment.A1.next',
        },
      ],
    ],
    {
      state: 'model-reviewed',
      record: 'emergency-review.md: doctor-appointment.A1 variants',
    },
  ),
  A2: emergencyPack(
    scene,
    'A2',
    {
      canDoZh: '安排可预测的预约请求，说明时间限制并提出到达问题。',
      complexityZh: '用简短理由联系选择与限制，区别偏好和确认。',
      scaffoldingZh: '两项时间与形式固定可见；每题只推进一个信息点。',
      registerZh: '日常礼貌请求，不将纸卡当真实诊所规则。',
    },
    [
      [
        'purpose',
        'state-booking-purpose',
        'Are you requesting an appointment or asking for information before choosing?',
        '说此次请求目的。',
        'appointment',
        'I would like to request an appointment.',
        'information',
        'I would like more information before I choose.',
        {
          state: 'model-reviewed',
          record: 'emergency-review.md: fix1 doctor-appointment.A2.purpose',
        },
      ],
      [
        'time',
        'request-time',
        'Would Tuesday morning or Thursday afternoon be better for you?',
        '表达时段偏好，不确定空位。',
        'tuesday',
        'Tuesday morning would be better for me.',
        'thursday',
        'I would prefer Thursday afternoon.',
        {
          state: 'model-reviewed',
          record: 'emergency-review.md: fix1 doctor-appointment.A2.time',
        },
      ],
      [
        'format',
        'request-format',
        'Which appointment format would you like to ask about?',
        '形式仍须询问。',
        'phone',
        'I would like to ask about a phone appointment.',
        'person',
        'I would like to ask about seeing someone in person.',
        {
          state: 'model-reviewed',
          record: 'emergency-review.md: fix1 doctor-appointment.A2.format',
        },
      ],
      [
        'constraint',
        'state-availability',
        'Is there a time of day when you are not available?',
        '不与两项偏好冲突。',
        'early',
        'I am not available before nine in the morning.',
        'flexible',
        'I am available throughout the day.',
        {
          state: 'model-reviewed',
          record: 'emergency-review.md: fix1 doctor-appointment.A2.constraint',
        },
      ],
      [
        'access',
        'request-access-information',
        'Would you like directions to the entrance in your reply?',
        '可以已有或需要信息。',
        'directions',
        'Yes, please include a simple map.',
        'known',
        'No, I already have a map of the entrance.',
        {
          state: 'model-reviewed',
          record: 'emergency-review.md: fix1 doctor-appointment.A2.access',
        },
      ],
      [
        'privacy',
        'set-information-boundary',
        'How would you like to handle personal information in this rehearsal?',
        '不使用真实数据。',
        'invented',
        'I would like to use an invented name.',
        'blank',
        'I would like to leave that part blank.',
        {
          state: 'model-reviewed',
          record: 'emergency-review.md: fix1 doctor-appointment.A2.privacy',
        },
      ],
      [
        'reply',
        'choose-reply-style',
        'What should a helpful reply look like for you?',
        '形式偏好不是已收到回信。',
        'list',
        'A short list would be easy for me to read.',
        'paragraph',
        'A short paragraph would help me understand the details.',
        {
          state: 'model-reviewed',
          record: 'emergency-review.md: fix1 doctor-appointment.A2.reply',
        },
      ],
      [
        'notice',
        'ask-change-information',
        'Would you like to include a question about changing a future appointment?',
        '前瞻，不声称已有预约。',
        'ask',
        'Yes, I would like to know how to ask for a change.',
        'omit',
        'No, I do not want to include that question now.',
        {
          state: 'model-reviewed',
          record: 'emergency-review.md: fix1 doctor-appointment.A2.notice',
        },
      ],
      [
        'question',
        'ask-arrival-information',
        'For a possible visit, which arrival detail would you like the clinic to explain?',
        '不默认提前到达时间。',
        'time',
        'I would like to know what time to arrive.',
        'place',
        'I would like to know where to report when I arrive.',
        {
          state: 'model-reviewed',
          record: 'emergency-review.md: fix1 doctor-appointment.A2.question',
        },
      ],
      [
        'clarify',
        'clarify-time-label',
        'Would you like help with “arrival time” or “appointment time”?',
        '明确练习卡标签。',
        'arrival',
        'Please explain the words “arrival time”.',
        'appointment',
        'Please explain the words “appointment time”.',
        {
          state: 'model-reviewed',
          record: 'emergency-review.md: fix1 doctor-appointment.A2.clarify',
        },
      ],
      [
        'record',
        'prepare-request-notes',
        'Have you made notes, or would you prefer to start a new list?',
        '准备状态不代表已发送。',
        'notes',
        'I have some notes that I can use.',
        'new',
        'I would prefer to start a new list.',
        {
          state: 'model-reviewed',
          record: 'emergency-review.md: fix1 doctor-appointment.A2.record',
        },
      ],
      [
        'next',
        'finish-request',
        'What would you like to do before finishing this appointment rehearsal?',
        '完成的是演练。',
        'check',
        'I would like to check the wording of my request.',
        'practise',
        'I would like to practise saying the request aloud.',
        {
          state: 'model-reviewed',
          record: 'emergency-review.md: fix1 doctor-appointment.A2.next',
        },
      ],
    ],
    {
      state: 'model-reviewed',
      record: 'emergency-review.md: fix1 doctor-appointment.A2 variants',
    },
  ),
  B1: emergencyPack(
    scene,
    'B1',
    {
      canDoZh: '解释预约偏好与限制，并为不明确的行政信息设计追问。',
      complexityZh: '协调多个请求项目，避免把未回复的偏好误认为预约。',
      scaffoldingZh: '明确纸卡及两种形式，具体问题分步引导理由表达。',
      registerZh: '自然日常接待语言，可保留选择和提出替代需求。',
    },
    [
      [
        'purpose',
        'state-booking-purpose',
        'What would you like the clinic to do with your enquiry?',
        '询问或请求均不预设服务可用。',
        'request',
        'I would like to ask whether an appointment could be arranged.',
        'options',
        'I would like an explanation of the appointment options before making a request.',
        {
          state: 'model-reviewed',
          record: 'emergency-review.md: doctor-appointment.B1.purpose',
        },
      ],
      [
        'time',
        'request-time',
        'Which sample time would suit you, and what makes it convenient?',
        '可选虚构原因。',
        'tuesday',
        'Tuesday morning would suit me because I have no class then.',
        'thursday',
        'Thursday afternoon would be easier because my work finishes at noon.',
        {
          state: 'model-reviewed',
          record: 'emergency-review.md: doctor-appointment.B1.time',
        },
      ],
      [
        'format',
        'request-format',
        'How would you state a preference without assuming that format is available?',
        '明确请求不是确认。',
        'phone',
        'I would prefer a phone appointment, if that is an option.',
        'person',
        'I would like to ask whether an in-person visit is possible.',
        {
          state: 'model-reviewed',
          record: 'emergency-review.md: doctor-appointment.B1.format',
        },
      ],
      [
        'constraint',
        'state-availability',
        'What availability detail should accompany your preferred time?',
        '不推翻前面的偏好。',
        'early',
        'I can be flexible after nine, but I cannot manage an earlier time.',
        'notice',
        'For any proposed time, I would like advance notice.',
        {
          state: 'model-reviewed',
          record: 'emergency-review.md: doctor-appointment.B1.constraint',
        },
      ],
      [
        'access',
        'request-access-information',
        'What practical information would help you plan a possible visit?',
        '只规划，不提供入口事实。',
        'entrance',
        'A description of the entrance would help me recognise it.',
        'desk',
        'I would like to know which desk handles arrivals.',
        {
          state: 'model-reviewed',
          record: 'emergency-review.md: doctor-appointment.B1.access',
        },
      ],
      [
        'privacy',
        'set-information-boundary',
        'How would you keep unnecessary personal information out of this practice?',
        '真实个人信息不在范围。',
        'invent',
        'I would use an invented name and keep the request general.',
        'omit',
        'I would leave personal details out and practise only the appointment questions.',
        {
          state: 'model-reviewed',
          record: 'emergency-review.md: doctor-appointment.B1.privacy',
        },
      ],
      [
        'reply',
        'choose-reply-style',
        'How could the reply separate confirmed arrangements from unanswered questions?',
        '希望的答复结构，不假称已获确认。',
        'headings',
        'I would ask for separate headings for confirmed details and points still to discuss.',
        'list',
        'I would ask for a list that clearly marks anything not yet agreed.',
        {
          state: 'model-reviewed',
          record: 'emergency-review.md: doctor-appointment.B1.reply',
        },
      ],
      [
        'notice',
        'ask-change-information',
        'Do you want to ask how changes are handled, even before a time is agreed?',
        '可以不问，不留虚构待办。',
        'ask',
        'Yes, knowing how to request a change would help me plan.',
        'later',
        'No, I would rather ask that after discussing the available options.',
        {
          state: 'model-reviewed',
          record: 'emergency-review.md: doctor-appointment.B1.notice',
        },
      ],
      [
        'question',
        'ask-arrival-information',
        'What would you ask to avoid confusing arrival time with appointment time?',
        '不要自行设定提前多久。',
        'difference',
        'For a possible visit, would the arrival time and appointment time be different?',
        'which',
        'Which time should I use when planning when to reach the clinic?',
        {
          state: 'model-reviewed',
          record: 'emergency-review.md: doctor-appointment.B1.question',
        },
      ],
      [
        'clarify',
        'clarify-time-label',
        'What clarification would help with the two time headings on the sample card?',
        '问题本身给出有意义差别。',
        'meaning',
        'Could you explain what each heading means in this form?',
        'example',
        'Could you show an example of how the two boxes would be filled in?',
        {
          state: 'model-reviewed',
          record: 'emergency-review.md: doctor-appointment.B1.clarify',
        },
      ],
      [
        'record',
        'prepare-request-notes',
        'How will you keep track of the details you still need to ask about?',
        '只是计划，不声称已完成。',
        'list',
        'I will make a short question list before the conversation.',
        'notes',
        'I will add a question mark beside unclear points in my existing notes.',
        {
          state: 'model-reviewed',
          record: 'emergency-review.md: doctor-appointment.B1.record',
        },
      ],
      [
        'next',
        'finish-request',
        'How would you describe the status of your request at the end of this rehearsal?',
        '保持模拟边界。',
        'ready',
        'It is ready for me to check, but it has not been sent.',
        'draft',
        'It is still a draft because I want to add a question.',
        {
          state: 'model-reviewed',
          record: 'emergency-review.md: doctor-appointment.B1.next',
        },
      ],
    ],
    {
      state: 'model-reviewed',
      record: 'emergency-review.md: doctor-appointment.B1 variants',
    },
  ),
  B2: emergencyPack(
    scene,
    'B2',
    {
      canDoZh: '协商预约请求中灵活性与限制的表达，区分行政确认与信息咨询。',
      complexityZh: '处理时间标签歧义和回信结构，给出具体权衡理由。',
      scaffoldingZh: '纸卡提供可追问标签；不要求判断就诊形式是否医学适宜。',
      registerZh: '清晰有分寸的行政沟通，避免生硬的制度或权利断言。',
    },
    [
      [
        'purpose',
        'state-booking-purpose',
        'What outcome are you seeking from the initial appointment enquiry?',
        '询问范围不代替分诊。',
        'possibility',
        'I want to find out whether an appointment can be arranged, without treating the example times as available slots.',
        'process',
        'I mainly need to understand the booking process before deciding what to request.',
        {
          state: 'model-reviewed',
          record: 'emergency-review.md: doctor-appointment.B2.purpose',
        },
      ],
      [
        'time',
        'request-time',
        'How would you express a preferred sample time while allowing room for discussion?',
        '偏好和替代空间。',
        'tuesday',
        'Tuesday morning is my first choice, but I would welcome a discussion of alternatives.',
        'thursday',
        'Thursday afternoon would be easiest; if that is unavailable, I would like to compare other options.',
        {
          state: 'model-reviewed',
          record: 'emergency-review.md: doctor-appointment.B2.time',
        },
      ],
      [
        'format',
        'request-format',
        'How would you ask about appointment format without presenting your preference as a decision?',
        '不提供医学适宜性判断。',
        'phone',
        'Could we discuss whether a phone appointment is an available option for this request?',
        'person',
        'I would prefer to attend in person, but I would first like to understand what the clinic offers.',
        {
          state: 'model-reviewed',
          record: 'emergency-review.md: doctor-appointment.B2.format',
        },
      ],
      [
        'constraint',
        'state-availability',
        'What distinction should your request make between a preference and a firm availability limit?',
        '各分支不与时段卡矛盾。',
        'limit',
        'The day is negotiable, but I cannot arrive before nine.',
        'flexible',
        'I have no firm time limit; my preference is about convenience rather than availability.',
        {
          state: 'model-reviewed',
          record: 'emergency-review.md: doctor-appointment.B2.constraint',
        },
      ],
      [
        'access',
        'request-access-information',
        'Which practical uncertainty about a possible visit would you ask the clinic to resolve?',
        '请求具体信息，不虚构流程。',
        'route',
        'I would ask which entrance and reception desk I should use.',
        'support',
        'I would ask whom to contact about access information before planning the visit.',
        {
          state: 'model-reviewed',
          record: 'emergency-review.md: doctor-appointment.B2.access',
        },
      ],
      [
        'privacy',
        'set-information-boundary',
        'How could you practise the administrative exchange without including a real health history?',
        '遵守虚构最少资料。',
        'fiction',
        'I would keep the details fictional and focus on how the request is organised.',
        'separate',
        'I would leave the personal section empty and rehearse only the administrative questions.',
        {
          state: 'model-reviewed',
          record: 'emergency-review.md: doctor-appointment.B2.privacy',
        },
      ],
      [
        'reply',
        'choose-reply-style',
        'What structure would make an eventual reply less likely to be mistaken for a booking confirmation?',
        '未来回信结构。',
        'status',
        'I would ask for the status of each point to be stated explicitly, especially whether a time has actually been agreed.',
        'separate',
        'I would ask for the available options to be listed separately from any confirmed arrangement.',
        {
          state: 'model-reviewed',
          record: 'emergency-review.md: doctor-appointment.B2.reply',
        },
      ],
      [
        'notice',
        'ask-change-information',
        'Would including a question about future changes make this enquiry more useful or unnecessarily long?',
        '明确可不纳入。',
        'include',
        'I would include one concise question so I know how to request a change later.',
        'defer',
        'I would leave that out for now to keep the first enquiry focused.',
        {
          state: 'model-reviewed',
          record: 'emergency-review.md: doctor-appointment.B2.notice',
        },
      ],
      [
        'question',
        'ask-arrival-information',
        'What question would resolve the relationship between the two time fields without guessing a local rule?',
        '询问而非普遍流程。',
        'relation',
        'Could you explain how the arrival time relates to the appointment time on this form?',
        'planning',
        'If both fields are completed, which one should guide my travel planning?',
        {
          state: 'model-reviewed',
          record: 'emergency-review.md: doctor-appointment.B2.question',
        },
      ],
      [
        'clarify',
        'clarify-time-label',
        'Suppose a reply gives only one time without a heading; what clarification would you request?',
        '明确的假设回复才触发澄清。',
        'label',
        'Does that time refer to arrival or to the start of the appointment?',
        'both',
        'Could you label the time and say whether there is a separate arrival time?',
        {
          state: 'model-reviewed',
          record: 'emergency-review.md: doctor-appointment.B2.clarify',
        },
      ],
      [
        'record',
        'prepare-request-notes',
        'How would you record a proposed time without later remembering it as agreed?',
        '提出记录策略，不假装已写。',
        'label',
        'I would label it “proposed” and keep the confirmation field blank.',
        'separate',
        'I would keep proposals in a separate section until the status is explicitly clarified.',
        {
          state: 'model-reviewed',
          record: 'emergency-review.md: doctor-appointment.B2.record',
        },
      ],
      [
        'next',
        'finish-request',
        'What would be an accurate closing statement for this unsent appointment enquiry?',
        '未发送与未确认保持准确。',
        'complete',
        'The wording is complete enough to review, but no arrangement has been made.',
        'incomplete',
        'The draft still needs a check of the time questions before I regard it as ready.',
        {
          state: 'model-reviewed',
          record: 'emergency-review.md: doctor-appointment.B2.next',
        },
      ],
    ],
    {
      state: 'model-reviewed',
      record: 'emergency-review.md: doctor-appointment.B2 variants',
    },
  ),
  C1: emergencyPack(
    scene,
    'C1',
    {
      canDoZh: '以自然专业语域管理预约请求的范围、条件、歧义及确认状态。',
      complexityZh:
        '区分程序问题、偏好、硬性限制与未决信息，并协商简洁但不丢条件的表述。',
      scaffoldingZh: '示例时段和明确假设回信承载复杂信息，不新增真实服务规则。',
      registerZh: 'CEFR C1 信息交换和澄清取向；用精细限定表达实际行政需求。',
    },
    [
      [
        'purpose',
        'state-booking-purpose',
        'How would you frame the enquiry so the recipient can distinguish your immediate aim from a later booking decision?',
        '区分先问和后决定。',
        'explore',
        'At this stage I am exploring how an appointment could be arranged; I am not asking you to treat any of the sample times as agreed.',
        'request',
        'I would like to initiate an appointment request, while leaving the practical details open for discussion.',
        {
          state: 'model-reviewed',
          record: 'emergency-review.md: doctor-appointment.C1.purpose',
        },
      ],
      [
        'time',
        'request-time',
        'How would you signal the strength of your time preference without closing off a workable alternative?',
        '具体时段和灵活性。',
        'tuesday',
        'Tuesday morning would fit particularly well, although I would rather discuss a workable alternative than imply that it is my only option.',
        'thursday',
        'Thursday afternoon is preferable, but the preference should not prevent us from considering another suitable time.',
        {
          state: 'model-reviewed',
          record: 'emergency-review.md: doctor-appointment.C1.time',
        },
      ],
      [
        'format',
        'request-format',
        'How could you raise a format preference while leaving the available options for the clinic to clarify?',
        '不擅自认定服务或适宜性。',
        'phone',
        'I would welcome a phone appointment if that is among the options you can offer; could you clarify the position before I plan around it?',
        'visit',
        'My preference is for an in-person discussion, but I would like to understand the available arrangements before settling on a format.',
        {
          state: 'model-reviewed',
          record: 'emergency-review.md: doctor-appointment.C1.format',
        },
      ],
      [
        'constraint',
        'state-availability',
        'What wording would prevent flexibility about the day from being mistaken for unrestricted availability?',
        '明确限制的范围。',
        'bounded',
        'I can consider different days, but the earliest I could attend is nine; those are separate points in my availability.',
        'unrestricted',
        'In my case there is no firm time restriction, so I would describe the proposed day as a preference rather than a condition.',
        {
          state: 'model-reviewed',
          record: 'emergency-review.md: doctor-appointment.C1.constraint',
        },
      ],
      [
        'access',
        'request-access-information',
        'How would you make an access enquiry concrete without assuming the clinic follows a particular procedure?',
        '询问具体细节而非规则。',
        'identify',
        'Could you identify the entrance and arrival point for the arrangement we eventually discuss, rather than rely on a general description of the building?',
        'contact',
        'Could you indicate who can clarify access arrangements, so I can put any practical questions to the appropriate person?',
        {
          state: 'model-reviewed',
          record: 'emergency-review.md: doctor-appointment.C1.access',
        },
      ],
      [
        'privacy',
        'set-information-boundary',
        'How would you keep this rehearsal useful while declining to supply real identifying or health information?',
        '隐私边界明确且自然。',
        'substitute',
        'I would substitute clearly invented details and concentrate on whether the request communicates its purpose and constraints.',
        'omit',
        'I would omit that section altogether; practising the administrative wording does not require a personal account.',
        {
          state: 'model-reviewed',
          record: 'emergency-review.md: doctor-appointment.C1.privacy',
        },
      ],
      [
        'reply',
        'choose-reply-style',
        'Which distinction would you most want an eventual reply to preserve between discussion and agreement?',
        '未来而非已收到回复。',
        'status',
        'I would want each proposed arrangement labelled with its current status, so an option under discussion cannot be read as a confirmed booking.',
        'conditions',
        'I would want any outstanding condition stated beside the proposal, rather than separated from it in a way that invites misunderstanding.',
        {
          state: 'model-reviewed',
          record: 'emergency-review.md: doctor-appointment.C1.reply',
        },
      ],
      [
        'notice',
        'ask-change-information',
        'How would you decide whether a question about later changes belongs in the opening enquiry?',
        '给出纳入或不纳入的具体理由。',
        'include',
        'I would include it briefly, since knowing the process would help me assess how to manage an uncertain schedule.',
        'omit',
        'I would omit it until the basic options are clear; introducing every possible later issue could obscure the immediate request.',
        {
          state: 'model-reviewed',
          record: 'emergency-review.md: doctor-appointment.C1.notice',
        },
      ],
      [
        'question',
        'ask-arrival-information',
        'How would you ask about arrival expectations while avoiding an unsupported assumption about how early to attend?',
        '无真实提前时间规则。',
        'direct',
        'Could you specify the arrival time separately from the appointment time and explain any distinction relevant to the arrangement?',
        'clarify',
        'Before I make travel plans, could you clarify whether the two time fields serve different purposes in this case?',
        {
          state: 'model-reviewed',
          record: 'emergency-review.md: doctor-appointment.C1.question',
        },
      ],
      [
        'clarify',
        'clarify-time-label',
        'A hypothetical reply says “Thursday at two” but labels neither time field; how would you resolve that ambiguity efficiently?',
        '提供独立假设才提出歧义修复。',
        'label',
        'Could you confirm whether two is the arrival time or the appointment time, and supply the other time if it differs?',
        'restate',
        'May I check how “Thursday at two” should be entered on the form, given that arrival and appointment have separate fields?',
        {
          state: 'model-reviewed',
          record: 'emergency-review.md: doctor-appointment.C1.clarify',
        },
      ],
      [
        'record',
        'prepare-request-notes',
        'How would you design your notes to prevent a tentative proposal acquiring the appearance of a settled arrangement?',
        '记录计划不是完成记录。',
        'status',
        'I would keep a status beside each proposal and record confirmation only when it is explicitly given.',
        'history',
        'I would retain a short record of what was proposed and what remains open, rather than overwrite the proposal as though it had been accepted.',
        {
          state: 'model-reviewed',
          record: 'emergency-review.md: doctor-appointment.C1.record',
        },
      ],
      [
        'next',
        'finish-request',
        'How would you conclude this drafting exercise without overstating what the exchange has achieved?',
        '只总结拟稿，不联系服务。',
        'ready',
        'The enquiry is ready for review as wording, while every practical arrangement remains subject to an actual response.',
        'revise',
        'I have a usable draft, but I would revise the unresolved time question before treating the wording as final.',
        {
          state: 'model-reviewed',
          record: 'emergency-review.md: doctor-appointment.C1.next',
        },
      ],
    ],
    {
      state: 'model-reviewed',
      record: 'emergency-review.md: doctor-appointment.C1 variants',
    },
  ),
}
