import { emergencyPack, type EmergencyScene } from './authoring'
const scene: EmergencyScene = {
  sceneId: 'emergency-04',
  slug: 'emergency-call',
  situations: [
    '紧急通话语言模拟，接线员由练习搭档扮演，绝不拨号。地图为虚构的 Example Hall，标有 east door、west door、fountain 和 garden；喷泉和花园画在大厅附近，未标距离；这里不是你的真实位置。事件可从答案选择为有人摔倒或走廊有烟，只描述明确看见或不知道的情况，不判断原因、伤势或处置。无线电能力、自动定位、回拨和口译均不预设；不用真实电话、姓名或地址。练习不联系真实医疗或紧急服务，不派遣救援，不提供急救指令。真实紧急情况请使用所在地适用的紧急渠道。',
    '紧急信息转述模拟，搭档扮演接线员帮你区分亲见事实与不清楚的部分，但没有实际通话或信息转发。虚构地图 Example Hall 有 east door、west door、fountain 与 garden，喷泉和花园画在大厅附近但未标距离，答案中的地点不是现实位置；事件可选有人摔倒或走廊有烟。此轮优先确认可见标志和听说支持，不假设已收到位置信息、可回拨或有翻译。仅用虚构最少资料，绝不要求真实地址或号码。本练习不会联系真实医疗或紧急服务，不派遣救援或提供急救操作；真实紧急情况使用所在地适用的紧急渠道。',
  ],
  paths: [
    {
      short: ['event', 'place', 'next'],
      standard: ['event', 'place', 'time', 'source', 'uncertain', 'next'],
      extended: [
        'event',
        'place',
        'time',
        'source',
        'people',
        'view',
        'contact',
        'pace',
        'uncertain',
        'next',
      ],
    },
    {
      short: ['event', 'landmark', 'next'],
      standard: ['event', 'place', 'landmark', 'language', 'uncertain', 'next'],
      extended: [
        'event',
        'place',
        'time',
        'source',
        'landmark',
        'language',
        'view',
        'pace',
        'uncertain',
        'next',
      ],
    },
  ],
  closing:
    'The simulated emergency communication practice is complete; it is not a real call ending instruction. No real medical or emergency service was contacted and no help was dispatched.',
  partial:
    'This simulation stops with some details unconfirmed, not with a real incident resolved. No real service was contacted or help dispatched.',
  repairs: {
    clarify: 'You can ask which fictional detail the practice question needs.',
    struggle: 'You can use a short statement from the fictional facts.',
    offTopic:
      'We can return to the simulated report without guessing missing details.',
    unknown:
      'That wording is not covered locally. No event, location or condition has been inferred.',
    changed:
      'The corrected fictional detail replaces the earlier one in this practice.',
    refusedClosing:
      'The simulation has stopped; this is not advice about ending a real emergency call. No real service was contacted or help dispatched.',
  },
}
export const emergencyCall = {
  A1: emergencyPack(
    scene,
    'A1',
    {
      canDoZh: '在明确虚构的通话中用短句说事件、地点并表示不知道。',
      complexityZh: '只处理具体可见对象与单一事实，不推断伤情或原因。',
      scaffoldingZh:
        '场景地图与虚构事实可见；短问句、地点词和两个完整回答提供强支架。',
      registerZh: '简短直接的求助信息语言，不教授实际接线流程。',
    },
    [
      [
        'event',
        'report-event',
        'What is happening in the practice scene?',
        '选择虚构观察。',
        'fall',
        'A person has fallen.',
        'smoke',
        'There is smoke in the hall.',
        {
          state: 'model-reviewed',
          record: 'emergency-review.md: emergency-call.A1.event',
        },
      ],
      [
        'place',
        'give-fictional-location',
        'Where is this on the practice map?',
        '不提供真实地址。',
        'east',
        'At the east door of Example Hall.',
        'west',
        'At the west door of Example Hall.',
        {
          state: 'model-reviewed',
          record: 'emergency-review.md: emergency-call.A1.place',
        },
      ],
      [
        'time',
        'give-observation-time',
        'When did you learn about this?',
        '选择得知消息的虚构时间；可亲见或听说。',
        'now',
        'Just now.',
        'minutes',
        'Two minutes ago.',
        {
          state: 'model-reviewed',
          record: 'emergency-review.md: emergency-call.A1.time',
        },
      ],
      [
        'source',
        'identify-information-source',
        'Did you see it yourself?',
        '区分亲见和他人说。',
        'saw',
        'Yes, I saw it.',
        'told',
        'No, someone told me.',
        {
          state: 'model-reviewed',
          record: 'emergency-review.md: emergency-call.A1.source',
        },
      ],
      [
        'people',
        'report-visible-people',
        'Can you see people now?',
        '不推断伤情。',
        'two',
        'Yes, I can see two people.',
        'none',
        'No, I cannot see anyone.',
        {
          state: 'model-reviewed',
          record: 'emergency-review.md: emergency-call.A1.people',
        },
      ],
      [
        'view',
        'state-view-limit',
        'Can you see the entrance?',
        '只报告视线，不要求移动。',
        'yes',
        'Yes, I can see the entrance.',
        'no',
        'I cannot see the entrance.',
        {
          state: 'model-reviewed',
          record: 'emergency-review.md: emergency-call.A1.view',
        },
      ],
      [
        'contact',
        'state-contact-uncertainty',
        'Do you know if this practice phone can receive calls?',
        '模拟能力不能假定。',
        'unknown',
        'No, I do not know.',
        'card',
        'The practice card says it can.',
        {
          state: 'model-reviewed',
          record: 'emergency-review.md: emergency-call.A1.contact',
        },
      ],
      [
        'pace',
        'request-clear-speech',
        'Do you want one short question at a time?',
        '沟通节奏需求。',
        'yes',
        'Yes, one short question, please.',
        'no',
        'No, this is okay.',
        {
          state: 'model-reviewed',
          record: 'emergency-review.md: emergency-call.A1.pace',
        },
      ],
      [
        'uncertain',
        'avoid-guessing',
        'Do you know the cause of the event?',
        '不知道就直说。',
        'unknown',
        'No, I do not know the cause.',
        'unsure',
        'I am not sure.',
        {
          state: 'model-reviewed',
          record: 'emergency-review.md: emergency-call.A1.uncertain',
        },
      ],
      [
        'landmark',
        'identify-map-landmark',
        'What other place can you name on the map?',
        '已提供虚构地标。',
        'fountain',
        'There is a fountain.',
        'garden',
        'There is a garden.',
        {
          state: 'model-reviewed',
          record: 'emergency-review.md: emergency-call.A1.landmark',
        },
      ],
      [
        'language',
        'request-language-support',
        'Do you want help with English words?',
        '提出需要，不保证口译。',
        'help',
        'Yes, I need help with English.',
        'simple',
        'I can use simple English.',
        {
          state: 'model-reviewed',
          record: 'emergency-review.md: emergency-call.A1.language',
        },
      ],
      [
        'next',
        'prepare-report-check',
        'What do you want to check in your practice report?',
        '只做语言核对。',
        'place',
        'I want to check the place name.',
        'words',
        'I want to check my words.',
        {
          state: 'model-reviewed',
          record: 'emergency-review.md: emergency-call.A1.next',
        },
      ],
    ],
    {
      state: 'model-reviewed',
      record: 'emergency-review.md: emergency-call.A1 variants',
    },
  ),
  A2: emergencyPack(
    scene,
    'A2',
    {
      canDoZh: '在模拟信息交换中交代地点和消息来源，并请求简短问题。',
      complexityZh: '把观察时间与来源分开，允许不知能力或视线受限。',
      scaffoldingZh: '给出虚构地图和可用事实；两句回答解释有限观察。',
      registerZh: '清楚直接而礼貌，未引入全球号码或救援承诺。',
    },
    [
      [
        'event',
        'report-event',
        'What would you like to report in this simulation?',
        '只选虚构事件。',
        'fall',
        'Someone has fallen near the hall.',
        'smoke',
        'I want to report smoke in the hall.',
        {
          state: 'model-reviewed',
          record: 'emergency-review.md: emergency-call.A2.event',
        },
      ],
      [
        'place',
        'give-fictional-location',
        'Which entrance on the fictional map is the report about?',
        '定位对象明确为地图。',
        'east',
        'The report is about the east entrance of Example Hall.',
        'west',
        'It is about the west entrance of Example Hall.',
        {
          state: 'model-reviewed',
          record: 'emergency-review.md: emergency-call.A2.place',
        },
      ],
      [
        'time',
        'give-observation-time',
        'Was the event noticed now or a few minutes ago?',
        '描述虚构发现时间。',
        'now',
        'It was noticed just now.',
        'earlier',
        'It was noticed about five minutes ago.',
        {
          state: 'model-reviewed',
          record: 'emergency-review.md: emergency-call.A2.time',
        },
      ],
      [
        'source',
        'identify-information-source',
        'Is this something you saw or something you were told?',
        '两种来源不混淆。',
        'direct',
        'I saw it myself a short time ago.',
        'reported',
        'Another person told me about it.',
        {
          state: 'model-reviewed',
          record: 'emergency-review.md: emergency-call.A2.source',
        },
      ],
      [
        'people',
        'report-visible-people',
        'How many people can you actually see from where you are?',
        '不要求改变位置。',
        'two',
        'I can see two people from here.',
        'unknown',
        'I cannot see the people from here.',
        {
          state: 'model-reviewed',
          record: 'emergency-review.md: emergency-call.A2.people',
        },
      ],
      [
        'view',
        'state-view-limit',
        'Is the entrance visible from your present position?',
        '当前视线不同于事件来源。',
        'clear',
        'Yes, I can see the entrance clearly.',
        'blocked',
        'No, a wall is blocking my view.',
        {
          state: 'model-reviewed',
          record: 'emergency-review.md: emergency-call.A2.view',
        },
      ],
      [
        'contact',
        'state-contact-uncertainty',
        'What can you say about receiving a call on the fictional phone?',
        '不使用真实号码或保证能力。',
        'unknown',
        'I do not know whether this phone can receive a call.',
        'card',
        'In this exercise, the phone card says it can receive calls.',
        {
          state: 'model-reviewed',
          record: 'emergency-review.md: emergency-call.A2.contact',
        },
      ],
      [
        'pace',
        'request-clear-speech',
        'Would shorter questions help you give the details clearly?',
        '支持请求可有可无。',
        'shorter',
        'Yes, please ask shorter questions.',
        'fine',
        'No, I can follow the questions as they are.',
        {
          state: 'model-reviewed',
          record: 'emergency-review.md: emergency-call.A2.pace',
        },
      ],
      [
        'uncertain',
        'avoid-guessing',
        'Can you explain the cause, or is that something you do not know?',
        '不猜原因。',
        'unknown',
        'I do not know what caused it.',
        'notseen',
        'I did not see how it started.',
        {
          state: 'model-reviewed',
          record: 'emergency-review.md: emergency-call.A2.uncertain',
        },
      ],
      [
        'landmark',
        'identify-map-landmark',
        'Which named feature on the practice map could help describe the area?',
        '指地图，不猜现场相对距离。',
        'fountain',
        'The map shows a fountain near the hall.',
        'garden',
        'A garden is marked beside Example Hall.',
        {
          state: 'model-reviewed',
          record: 'emergency-review.md: emergency-call.A2.landmark',
        },
      ],
      [
        'language',
        'request-language-support',
        'How would you explain the language help you need?',
        '请求不等于提供翻译。',
        'simple',
        'Please use simple English words.',
        'help',
        'I need language help; is any available?',
        {
          state: 'model-reviewed',
          record: 'emergency-review.md: emergency-call.A2.language',
        },
      ],
      [
        'next',
        'prepare-report-check',
        'Which part of the simulated report would you like to practise next?',
        '不会真实通话。',
        'location',
        'I would like to read back the location on the map.',
        'source',
        'I would like to practise saying where the information came from.',
        {
          state: 'model-reviewed',
          record: 'emergency-review.md: emergency-call.A2.next',
        },
      ],
    ],
    {
      state: 'model-reviewed',
      record: 'emergency-review.md: emergency-call.A2 variants',
    },
  ),
  B1: emergencyPack(
    scene,
    'B1',
    {
      canDoZh: '区分看到和听说的事件信息，并准确表达位置与观察限制。',
      complexityZh: '处理转述、可见范围和未确认能力，不补写未知事实。',
      scaffoldingZh:
        '明确虚构地图及回拨条件只可来自假设卡；提供短理由支持信息修复。',
      registerZh: '直接有条理的模拟信息交换，不承担接线或急救权威。',
    },
    [
      [
        'event',
        'report-event',
        'How would you describe the event briefly before adding details?',
        '不判断原因或伤势。',
        'fall',
        'The report concerns a person who has fallen near the hall.',
        'smoke',
        'The report concerns smoke inside the hall; I do not know its source.',
        {
          state: 'model-reviewed',
          record: 'emergency-review.md: emergency-call.B1.event',
        },
      ],
      [
        'place',
        'give-fictional-location',
        'How would you give the fictional location without assuming it is already known?',
        '不假定自动定位。',
        'east',
        'The location on my practice map is the east entrance of Example Hall.',
        'west',
        'Please use the west entrance of Example Hall as the location in this exercise.',
        {
          state: 'model-reviewed',
          record: 'emergency-review.md: emergency-call.B1.place',
        },
      ],
      [
        'time',
        'give-observation-time',
        'How exact can you be about when the event was first noticed?',
        '未知时间可坦白。',
        'approximate',
        'It was noticed about five minutes ago, although I cannot give an exact minute.',
        'unknown',
        'I do not know when it was first noticed.',
        {
          state: 'model-reviewed',
          record: 'emergency-review.md: emergency-call.B1.time',
        },
      ],
      [
        'source',
        'identify-information-source',
        'How would you make clear whether you witnessed the event?',
        '转述不得升级亲眼看到。',
        'witness',
        'I saw the event myself, so that part comes from my own observation.',
        'secondhand',
        'I am passing on what someone told me; I did not witness the event.',
        {
          state: 'model-reviewed',
          record: 'emergency-review.md: emergency-call.B1.source',
        },
      ],
      [
        'people',
        'report-visible-people',
        'What can you report about the people within your current view?',
        '不对看不到的人做推断。',
        'two',
        'I can see two people, but I do not know whether anyone else is nearby.',
        'blocked',
        'I cannot see the people, so I cannot give a reliable number.',
        {
          state: 'model-reviewed',
          record: 'emergency-review.md: emergency-call.B1.people',
        },
      ],
      [
        'view',
        'state-view-limit',
        'What can you see of the entrance from your current position?',
        '不提供移动或检查指令。',
        'partial',
        'I can see part of the entrance, but not the area inside it.',
        'none',
        'The entrance is out of view from where I am.',
        {
          state: 'model-reviewed',
          record: 'emergency-review.md: emergency-call.B1.view',
        },
      ],
      [
        'contact',
        'state-contact-uncertainty',
        'How would you answer a question about callback capability without guessing?',
        '不提供实际联系方式。',
        'unknown',
        'I cannot confirm whether this fictional phone can receive a callback.',
        'specified',
        'The exercise card explicitly says this phone can receive calls.',
        {
          state: 'model-reviewed',
          record: 'emergency-review.md: emergency-call.B1.contact',
        },
      ],
      [
        'pace',
        'request-clear-speech',
        'What would help you avoid missing part of a long practice question?',
        '语言支持，不实际操作流程。',
        'split',
        'Please ask one part at a time so I can answer each detail.',
        'repeat',
        'Please repeat the key words before I answer.',
        {
          state: 'model-reviewed',
          record: 'emergency-review.md: emergency-call.B1.pace',
        },
      ],
      [
        'uncertain',
        'avoid-guessing',
        'How would you respond if asked for details outside your view?',
        '不推测任何条件。',
        'limited',
        'I cannot see that area, so I cannot describe what is happening there.',
        'unknown',
        'I do not have that information, and I do not want to guess.',
        {
          state: 'model-reviewed',
          record: 'emergency-review.md: emergency-call.B1.uncertain',
        },
      ],
      [
        'landmark',
        'identify-map-landmark',
        'How could you use the map to add an identifying feature without inventing a distance?',
        '地图有地标但没有测距。',
        'fountain',
        'The map names a fountain near Example Hall, but it does not give the distance.',
        'garden',
        'The map marks a garden beside the hall, without showing a measured distance.',
        {
          state: 'model-reviewed',
          record: 'emergency-review.md: emergency-call.B1.landmark',
        },
      ],
      [
        'language',
        'request-language-support',
        'How would you ask about language support without assuming it is available?',
        '不保证口译。',
        'availability',
        'Is language support available for someone who finds English difficult?',
        'simpler',
        'If possible, please use shorter sentences and everyday words.',
        {
          state: 'model-reviewed',
          record: 'emergency-review.md: emergency-call.B1.language',
        },
      ],
      [
        'next',
        'prepare-report-check',
        'What would you check to make your practice report more accurate?',
        '核对计划不变成已验证。',
        'source',
        'I would check that any second-hand information is clearly labelled.',
        'location',
        'I would compare the place names in my report with the practice map.',
        {
          state: 'model-reviewed',
          record: 'emergency-review.md: emergency-call.B1.next',
        },
      ],
    ],
    {
      state: 'model-reviewed',
      record: 'emergency-review.md: emergency-call.B1 variants',
    },
  ),
  B2: emergencyPack(
    scene,
    'B2',
    {
      canDoZh: '有条理地报告有限信息并修复来源、位置和能力方面可能的误解。',
      complexityZh:
        '管理可见范围与转述的不同证据，处理假设歧义，拒绝不可靠推断。',
      scaffoldingZh: '固定虚构地图保证位置词有出处，所有反事实问题明确为假设。',
      registerZh: '简洁准确而不戏剧化，避免替真实接线员做决策。',
    },
    [
      [
        'event',
        'report-event',
        'How would you introduce the report while separating the event from assumptions about its cause?',
        '只陈述事件，不断言风险。',
        'fall',
        'A person has fallen near the hall; the report does not establish why it happened.',
        'smoke',
        'There is a report of smoke inside the hall, but I cannot identify the source.',
        {
          state: 'model-reviewed',
          record: 'emergency-review.md: emergency-call.B2.event',
        },
      ],
      [
        'place',
        'give-fictional-location',
        'How would you identify the relevant entrance when the listener has not received your location?',
        '明确不预设定位能力。',
        'east',
        'For this exercise, the relevant location is Example Hall’s east entrance; I am not assuming the location has been transmitted.',
        'west',
        'The practice map identifies the west entrance of Example Hall as the location I want to report.',
        {
          state: 'model-reviewed',
          record: 'emergency-review.md: emergency-call.B2.place',
        },
      ],
      [
        'time',
        'give-observation-time',
        'How would you distinguish the time of the report from the time the event began?',
        '未观察起始时不虚构起始。',
        'noticed',
        'It was noticed roughly five minutes ago; that does not tell me exactly when it began.',
        'unknown',
        'I can describe the report now, but I have no reliable information about the starting time.',
        {
          state: 'model-reviewed',
          record: 'emergency-review.md: emergency-call.B2.time',
        },
      ],
      [
        'source',
        'identify-information-source',
        'What wording would prevent second-hand information from sounding like eyewitness evidence?',
        '对应来源，避免抹平差别。',
        'reported',
        'I was told about the event and am relaying that account, not claiming to have witnessed it.',
        'direct',
        'In this version I did witness the event, so I can distinguish that observation from anything I am later told.',
        {
          state: 'model-reviewed',
          record: 'emergency-review.md: emergency-call.B2.source',
        },
      ],
      [
        'people',
        'report-visible-people',
        'How would you qualify a headcount when only part of the area is visible?',
        '看见两人不等于现场仅两人。',
        'bounded',
        'Two people are within my view, but I cannot account for anyone outside it.',
        'none',
        'I have no view of the people, so giving a number would be speculation.',
        {
          state: 'model-reviewed',
          record: 'emergency-review.md: emergency-call.B2.people',
        },
      ],
      [
        'view',
        'state-view-limit',
        'How could you describe the limits of your view without implying you will move to check?',
        '不提供冒险检查指令。',
        'partial',
        'I can see the doorway but not the interior; that is the limit of my current view.',
        'blocked',
        'The entrance is obscured from my present position, so I cannot provide an observation of it.',
        {
          state: 'model-reviewed',
          record: 'emergency-review.md: emergency-call.B2.view',
        },
      ],
      [
        'contact',
        'state-contact-uncertainty',
        'How would you distinguish a stated callback capability from one you have simply assumed?',
        '练习资料依据明确。',
        'specified',
        'The fictional device card specifically says calls can be received; I am relying on that stated detail.',
        'unknown',
        'No callback capability is specified, so I would say that I cannot confirm it.',
        {
          state: 'model-reviewed',
          record: 'emergency-review.md: emergency-call.B2.contact',
        },
      ],
      [
        'pace',
        'request-clear-speech',
        'How would you request a manageable question pace while keeping the exchange focused?',
        '具体沟通需要。',
        'single',
        'Please give me one factual question at a time so I do not combine separate details.',
        'pause',
        'Please leave a brief pause after each question so I can distinguish what I know from what I need to leave open.',
        {
          state: 'model-reviewed',
          record: 'emergency-review.md: emergency-call.B2.pace',
        },
      ],
      [
        'uncertain',
        'avoid-guessing',
        'If a question asks about conditions you cannot observe, what distinction should your answer preserve?',
        '未知不等于否定。',
        'unknown',
        'I would say that the condition is unknown to me, not that it is absent.',
        'limited',
        'I would explain what lies outside my view and avoid filling the gap with an assumption.',
        {
          state: 'model-reviewed',
          record: 'emergency-review.md: emergency-call.B2.uncertain',
        },
      ],
      [
        'landmark',
        'identify-map-landmark',
        'How would you add a map landmark while making clear what the map does not establish?',
        '地图事实与现实位置分开。',
        'fountain',
        'The practice map shows a fountain near the hall, but it gives no measured distance between them.',
        'garden',
        'A garden is marked beside the hall; its exact distance from the entrance is not supplied.',
        {
          state: 'model-reviewed',
          record: 'emergency-review.md: emergency-call.B2.landmark',
        },
      ],
      [
        'language',
        'request-language-support',
        'What request would communicate a language difficulty without promising an interpreter will be provided?',
        '提出请求不保证能力。',
        'ask',
        'Could you tell me whether language assistance is available in this setting?',
        'plain',
        'Could we use shorter sentences while the availability of language help remains unclear?',
        {
          state: 'model-reviewed',
          record: 'emergency-review.md: emergency-call.B2.language',
        },
      ],
      [
        'next',
        'prepare-report-check',
        'What would you review before calling the simulated report internally consistent?',
        '不等于真实事件解决。',
        'attribution',
        'I would check that each detail is labelled as observed, reported or unknown as appropriate.',
        'map',
        'I would check the location wording against the fictional map and remove any unsupported extra detail.',
        {
          state: 'model-reviewed',
          record: 'emergency-review.md: emergency-call.B2.next',
        },
      ],
    ],
    {
      state: 'model-reviewed',
      record: 'emergency-review.md: emergency-call.B2 variants',
    },
  ),
  C1: emergencyPack(
    scene,
    'C1',
    {
      canDoZh: '以准确简洁语言传递信息，主动限定来源、观察范围与未知能力。',
      complexityZh:
        '处理来源转换、未观察与不存在之间的逻辑差别及地标信息精度。',
      scaffoldingZh:
        '模拟有确定地图和设备卡的条件式问题，不要求临场处置或医疗判断。',
      registerZh: 'CEFR C1 精确信息交换；紧凑明确，不堆砌法律或医疗声明。',
    },
    [
      [
        'event',
        'report-event',
        'How would you give a concise initial account without letting an explanation become part of the reported event?',
        '表达边界针对原因这一具体缺口。',
        'fall',
        'The report is that a person has fallen near the hall; I would keep any explanation of the fall separate from that initial account.',
        'smoke',
        'Smoke has been reported inside the hall, but attributing it to a particular source would go beyond the information available.',
        {
          state: 'model-reviewed',
          record: 'emergency-review.md: emergency-call.C1.event',
        },
      ],
      [
        'place',
        'give-fictional-location',
        'How would you establish the fictional location explicitly rather than rely on an unstated assumption that it has been conveyed?',
        '无自动定位假设。',
        'east',
        'The location I am referring to is the east entrance of Example Hall, as labelled on the practice map.',
        'west',
        'Please identify the location in this exercise as Example Hall’s west entrance; no other location information should be inferred.',
        {
          state: 'model-reviewed',
          record: 'emergency-review.md: emergency-call.C1.place',
        },
      ],
      [
        'time',
        'give-observation-time',
        'How would you convey the time information while preserving the gap between detection and onset?',
        '发现不等于发生。',
        'detection',
        'The event was noticed approximately five minutes ago; I cannot infer its starting time from that observation.',
        'unavailable',
        'I have no reliable onset time, and would leave it unspecified rather than let the time of this report stand in for it.',
        {
          state: 'model-reviewed',
          record: 'emergency-review.md: emergency-call.C1.time',
        },
      ],
      [
        'source',
        'identify-information-source',
        'How would you make the evidential status of the account clear before the listener relies on its details?',
        '来源区分清晰。',
        'relayed',
        'I am relaying another person’s account and cannot independently confirm the event from my own observation.',
        'witnessed',
        'I witnessed the event myself; I would identify any subsequent information from others separately rather than merge the two sources.',
        {
          state: 'model-reviewed',
          record: 'emergency-review.md: emergency-call.C1.source',
        },
      ],
      [
        'people',
        'report-visible-people',
        'How would you avoid allowing a limited observation of people to be read as a complete account of who is present?',
        '观察范围限制人数陈述。',
        'two',
        'I can account for two people within my view, but that is not a complete count of everyone who may be in the area.',
        'unseen',
        'The people are outside my view, so I cannot support either a number or a claim that nobody is there.',
        {
          state: 'model-reviewed',
          record: 'emergency-review.md: emergency-call.C1.people',
        },
      ],
      [
        'view',
        'state-view-limit',
        'What distinction would help the listener understand exactly where your visual account ends?',
        '不建议行动，只报告可见范围。',
        'boundary',
        'The doorway is visible, whereas the interior beyond it is not; observations about one should not be extended to the other.',
        'none',
        'I cannot see the entrance from my present position, so I would keep that part of the account explicitly unobserved.',
        {
          state: 'model-reviewed',
          record: 'emergency-review.md: emergency-call.C1.view',
        },
      ],
      [
        'contact',
        'state-contact-uncertainty',
        'How would you handle a question about callback capability when the exercise materials may or may not specify it?',
        '条件式问题与两分支匹配。',
        'specified',
        'If the device card explicitly states that calls can be received, I can report that as a supplied fact of the exercise.',
        'unspecified',
        'If the materials do not specify it, I would leave the capability unconfirmed rather than infer it from the presence of a phone.',
        {
          state: 'model-reviewed',
          record: 'emergency-review.md: emergency-call.C1.contact',
        },
      ],
      [
        'pace',
        'request-clear-speech',
        'How could you negotiate the pace without losing the distinctions the report depends on?',
        '沟通深度来自信息区分而非冗长。',
        'separate',
        'Could we separate questions about what I observed from questions about what I was told, so I can attribute each answer accurately?',
        'sequence',
        'Could we take one detail at a time, allowing me to state explicitly when the information is unavailable?',
        {
          state: 'model-reviewed',
          record: 'emergency-review.md: emergency-call.C1.pace',
        },
      ],
      [
        'uncertain',
        'avoid-guessing',
        'How would you prevent a lack of observation from being interpreted as evidence that a condition is absent?',
        '关键逻辑区分。',
        'explicit',
        'I cannot observe that condition; my inability to report it should not be taken to mean it is not present.',
        'scope',
        'That lies outside what I can see, so I would leave the question open rather than answer it negatively.',
        {
          state: 'model-reviewed',
          record: 'emergency-review.md: emergency-call.C1.uncertain',
        },
      ],
      [
        'landmark',
        'identify-map-landmark',
        'How would you use the fictional landmark without adding spatial precision that the map does not support?',
        '不给具体虚构距离。',
        'bounded',
        'I can name the fountain shown near Example Hall, but I would not attach a distance that the map does not provide.',
        'garden',
        'I can name the garden marked beside the hall, while leaving its unmeasured distance from the entrance unspecified.',
        {
          state: 'model-reviewed',
          record: 'emergency-review.md: emergency-call.C1.landmark',
        },
      ],
      [
        'language',
        'request-language-support',
        'How would you raise a language-support need while leaving local capabilities for the recipient to clarify?',
        '无普遍口译承诺。',
        'availability',
        'Could you clarify what language support is available here, so I do not assume a service you may not be able to provide?',
        'interim',
        'While that is being clarified, could we keep to short, concrete questions that I can answer accurately?',
        {
          state: 'model-reviewed',
          record: 'emergency-review.md: emergency-call.C1.language',
        },
      ],
      [
        'next',
        'prepare-report-check',
        'What would count as a sound endpoint for reviewing this fictional report, as distinct from resolving an actual event?',
        '闭环只限描述审阅。',
        'consistent',
        'The account would be ready for review once its locations, sources and uncertainties are expressed consistently.',
        'open',
        'I would retain any unresolved detail as unresolved, even if that leaves the practice report less complete than I had hoped.',
        {
          state: 'model-reviewed',
          record: 'emergency-review.md: emergency-call.C1.next',
        },
      ],
    ],
    {
      state: 'model-reviewed',
      record: 'emergency-review.md: emergency-call.C1 variants',
    },
  ),
}
