import { emergencyPack, type EmergencyScene } from './authoring'
const scene: EmergencyScene = {
  sceneId: 'emergency-05',
  slug: 'lost-property',
  situations: [
    '虚构失物柜台英语模拟。练习搭档帮你描述遗失物，可能是蓝色手提袋或绿色笔记本；答案选定前没有默认物品。虚构场所为 Example Gallery，内有 cafe 和 reading room。遗失时间、特征和证明资料从参考答案选择，不索要真实姓名、地址、证件或联系方式。尚未搜寻、找到、核实物主或递交报告；不提供法律建议或保证找回。本轮不会联系真实柜台、警方或其他服务。',
    '虚构失物信息留言演练。搭档帮你准备一份尚未提交的说明，地点 Example Gallery 内有 cafe 和 reading room，可选物品为蓝色手提袋或绿色笔记本。此轮更重视辨识特征和候选物比对问题，所有时间、物件与证明信息均为虚构。没有检索结果，候选物仅会作为题目中的明确假设。不提供真实身份或联系方式，不作所有权法律判断，不实际报失、联系柜台或保证找回。',
  ],
  paths: [
    {
      short: ['item', 'last', 'next'],
      standard: ['item', 'last', 'time', 'feature', 'contact', 'next'],
      extended: [
        'item',
        'last',
        'time',
        'feature',
        'contents',
        'proof',
        'contact',
        'privacy',
        'followup',
        'next',
      ],
    },
    {
      short: ['item', 'feature', 'next'],
      standard: ['item', 'last', 'feature', 'candidate', 'contact', 'next'],
      extended: [
        'item',
        'last',
        'time',
        'feature',
        'candidate',
        'uncertain',
        'contact',
        'privacy',
        'followup',
        'next',
      ],
    },
  ],
  closing:
    'The lost-property description practice is complete. No real report was filed or service contacted; no item was found or ownership verified.',
  partial:
    'Some details of the fictional lost item remain unconfirmed. No real report was filed, service contacted or item recovered.',
  repairs: {
    clarify: 'You can ask which detail of the fictional lost item is needed.',
    struggle:
      'A short colour, place or feature description can help you start.',
    offTopic: 'We can return to describing the fictional lost property.',
    unknown:
      'That wording is not covered locally, so no ownership or item detail has been inferred.',
    changed:
      'The new detail replaces the earlier one in this practice description.',
    refusedClosing:
      'The lost-property practice has stopped. No real report was filed or service contacted; no personal details are required.',
  },
}
export const lostProperty = {
  A1: emergencyPack(
    scene,
    'A1',
    {
      canDoZh: '描述一个虚构失物及最后看见的位置。',
      complexityZh: '单一物件、地点、时间和可见特征，尚未证明归属或找回。',
      scaffoldingZh: '固定两类物品和场所，短句可以直接应答。',
      registerZh: '基础失物求助口语，保留隐私。',
    },
    [
      [
        'item',
        'identify-lost-item',
        'What have you lost in the practice story?',
        '选择虚构物品。',
        'bag',
        'I have lost a blue bag.',
        'book',
        'I have lost a green notebook.',
        {
          state: 'model-reviewed',
          record: 'emergency-review.md: lost-property.A1.item',
        },
      ],
      [
        'last',
        'give-last-seen-place',
        'Where did you last see your item?',
        '虚构地点，不是确定遗落处。',
        'cafe',
        'I last saw it in the cafe.',
        'reading',
        'I last saw it in the reading room.',
        {
          state: 'model-reviewed',
          record: 'emergency-review.md: lost-property.A1.last',
        },
      ],
      [
        'time',
        'give-last-seen-time',
        'When did you last see it?',
        '选择虚构时间。',
        'morning',
        'This morning.',
        'yesterday',
        'Yesterday afternoon.',
        {
          state: 'model-reviewed',
          record: 'emergency-review.md: lost-property.A1.time',
        },
      ],
      [
        'feature',
        'describe-mark',
        'Does your item have a mark?',
        '两种物品都能有此特征。',
        'star',
        'Yes, it has a white star.',
        'none',
        'No, it has no mark.',
        {
          state: 'model-reviewed',
          record: 'emergency-review.md: lost-property.A1.feature',
        },
      ],
      [
        'contents',
        'describe-associated-object',
        'Was there a card with your item?',
        '不透露真实卡片信息。',
        'card',
        'Yes, a blank card.',
        'none',
        'No, there was no card.',
        {
          state: 'model-reviewed',
          record: 'emergency-review.md: lost-property.A1.contents',
        },
      ],
      [
        'proof',
        'offer-identifying-material',
        'Do you have a picture of your item?',
        '图片不是所有权结论。',
        'yes',
        'Yes, I have a picture.',
        'no',
        'No, I have no picture.',
        {
          state: 'model-reviewed',
          record: 'emergency-review.md: lost-property.A1.proof',
        },
      ],
      [
        'contact',
        'choose-practice-followup',
        'Do you want a written note or a spoken reply for this exercise?',
        '不填写实际联系方式。',
        'note',
        'A written note, please.',
        'spoken',
        'A spoken reply, please.',
        {
          state: 'model-reviewed',
          record: 'emergency-review.md: lost-property.A1.contact',
        },
      ],
      [
        'privacy',
        'protect-private-details',
        'Do you want a made-up name on the practice note?',
        '仅虚构或不填。',
        'madeup',
        'Yes, please use Sam.',
        'blank',
        'No, please leave it blank.',
        {
          state: 'model-reviewed',
          record: 'emergency-review.md: lost-property.A1.privacy',
        },
      ],
      [
        'followup',
        'request-process-information',
        'What do you want to ask the lost-property desk?',
        '只拟问题。',
        'how',
        'How can I ask again later?',
        'where',
        'Where is the lost-property desk?',
        {
          state: 'model-reviewed',
          record: 'emergency-review.md: lost-property.A1.followup',
        },
      ],
      [
        'candidate',
        'avoid-premature-identification',
        'If someone shows you a similar item, what do you want to do?',
        '明确假设候选物，不表示已找到。',
        'look',
        'I want to look at it.',
        'size',
        'I want to ask about its size.',
        {
          state: 'model-reviewed',
          record: 'emergency-review.md: lost-property.A1.candidate',
        },
      ],
      [
        'uncertain',
        'acknowledge-memory-gap',
        'Do you remember the exact place where you left it?',
        '最后看见不等于遗落位置。',
        'unknown',
        'No, I do not remember.',
        'unsure',
        'I think I do, but I am not sure.',
        {
          state: 'model-reviewed',
          record: 'emergency-review.md: lost-property.A1.uncertain',
        },
      ],
      [
        'next',
        'plan-report-review',
        'What do you want to do with your lost-item description?',
        '只是演练。',
        'read',
        'I want to read it aloud.',
        'keep',
        'I want to keep a copy.',
        {
          state: 'model-reviewed',
          record: 'emergency-review.md: lost-property.A1.next',
        },
      ],
    ],
    {
      state: 'model-reviewed',
      record: 'emergency-review.md: lost-property.A1 variants',
    },
  ),
  A2: emergencyPack(
    scene,
    'A2',
    {
      canDoZh: '简短报失，描述可辨认特征并询问后续流程。',
      complexityZh: '连接最后看到的地点与时间，明确相似不等于自己的。',
      scaffoldingZh: '给定地点及两类物品；问题逐项引导不要求真实身份。',
      registerZh: '清楚日常柜台请求，可以不确定或不提供资料。',
    },
    [
      [
        'item',
        'identify-lost-item',
        'Which item would you like to describe to the lost-property desk?',
        '选择虚构物品。',
        'bag',
        'I would like to describe a blue shopping bag.',
        'book',
        'I would like to describe a green notebook.',
        {
          state: 'model-reviewed',
          record: 'emergency-review.md: lost-property.A2.item',
        },
      ],
      [
        'last',
        'give-last-seen-place',
        'Was the cafe or the reading room the last place you saw it?',
        '最后看见不是断言遗落。',
        'cafe',
        'I last saw it at a table in the cafe.',
        'reading',
        'I last saw it on a chair in the reading room.',
        {
          state: 'model-reviewed',
          record: 'emergency-review.md: lost-property.A2.last',
        },
      ],
      [
        'time',
        'give-last-seen-time',
        'Can you give a day and part of the day?',
        '选择虚构时间。',
        'today',
        'I last saw it this morning.',
        'yesterday',
        'I saw it yesterday, in the afternoon.',
        {
          state: 'model-reviewed',
          record: 'emergency-review.md: lost-property.A2.time',
        },
      ],
      [
        'feature',
        'describe-mark',
        'What could help someone recognise your item?',
        '各物品都可有贴纸或普通表面。',
        'sticker',
        'It has a yellow sticker on one side.',
        'plain',
        'It is plain, with no sticker or writing.',
        {
          state: 'model-reviewed',
          record: 'emergency-review.md: lost-property.A2.feature',
        },
      ],
      [
        'contents',
        'describe-associated-object',
        'Was a paper ticket kept with the item?',
        '两物件都可夹或装纸票。',
        'ticket',
        'Yes, I kept a paper ticket with it.',
        'none',
        'No, there was no ticket with it.',
        {
          state: 'model-reviewed',
          record: 'emergency-review.md: lost-property.A2.contents',
        },
      ],
      [
        'proof',
        'offer-identifying-material',
        'Would you be able to show a photo of it?',
        '不把照片当必然证明。',
        'yes',
        'Yes, I have a photo I could show.',
        'no',
        'No, but I can describe it in words.',
        {
          state: 'model-reviewed',
          record: 'emergency-review.md: lost-property.A2.proof',
        },
      ],
      [
        'contact',
        'choose-practice-followup',
        'How would you prefer to receive a reply in this rehearsal?',
        '虚构回复，无真实渠道。',
        'written',
        'I would prefer a written reply.',
        'spoken',
        'I would prefer someone to say the reply aloud.',
        {
          state: 'model-reviewed',
          record: 'emergency-review.md: lost-property.A2.contact',
        },
      ],
      [
        'privacy',
        'protect-private-details',
        'Would you like to use a fictional name or no name at all?',
        '不使用真实身份。',
        'fiction',
        'I would like to use the name Robin.',
        'none',
        'I would rather leave the name out.',
        {
          state: 'model-reviewed',
          record: 'emergency-review.md: lost-property.A2.privacy',
        },
      ],
      [
        'followup',
        'request-process-information',
        'Which follow-up question would be useful to include?',
        '只询问流程。',
        'when',
        'When could I ask for an update?',
        'how',
        'How should I refer to this report if I ask again?',
        {
          state: 'model-reviewed',
          record: 'emergency-review.md: lost-property.A2.followup',
        },
      ],
      [
        'candidate',
        'avoid-premature-identification',
        'If a similar object is shown, how would you check it before saying it is yours?',
        '不假定已有候选物。',
        'details',
        'I would look carefully at the small details.',
        'compare',
        'I would compare it with what I remember.',
        {
          state: 'model-reviewed',
          record: 'emergency-review.md: lost-property.A2.candidate',
        },
      ],
      [
        'uncertain',
        'acknowledge-memory-gap',
        'Are you sure where the item was actually left?',
        '区分记忆和确定。',
        'notcertain',
        'No, I only know where I last saw it.',
        'rough',
        'I have an idea, but I cannot be sure.',
        {
          state: 'model-reviewed',
          record: 'emergency-review.md: lost-property.A2.uncertain',
        },
      ],
      [
        'next',
        'plan-report-review',
        'What would you like to check before keeping the practice report?',
        '计划核对。',
        'description',
        'I would like to check the item description.',
        'wording',
        'I would like to check that the words are clear.',
        {
          state: 'model-reviewed',
          record: 'emergency-review.md: lost-property.A2.next',
        },
      ],
    ],
    {
      state: 'model-reviewed',
      record: 'emergency-review.md: lost-property.A2 variants',
    },
  ),
  B1: emergencyPack(
    scene,
    'B1',
    {
      canDoZh: '有条理地描述遗失物并解释记忆范围、比对材料和后续请求。',
      complexityZh:
        '处理不能确定遗落地点与没有照片的情况，避免搜索结果或归属假设。',
      scaffoldingZh:
        '两种物品均支持贴纸、夹带票和照片等问题，假设候选物单独介绍。',
      registerZh: '自然求助与核对语域，不承诺柜台制度或法律权利。',
    },
    [
      [
        'item',
        'identify-lost-item',
        'What item are you trying to trace, and how would you describe it briefly?',
        '选择具体虚构对象。',
        'bag',
        'I am looking for a blue cloth shopping bag.',
        'book',
        'I am trying to find a green notebook with a hard cover.',
        {
          state: 'model-reviewed',
          record: 'emergency-review.md: lost-property.B1.item',
        },
      ],
      [
        'last',
        'give-last-seen-place',
        'What is the last location you can associate with the item from memory?',
        '可靠最后看见位置。',
        'cafe',
        'I remember having it at a table in the cafe.',
        'reading',
        'I remember putting it beside me in the reading room.',
        {
          state: 'model-reviewed',
          record: 'emergency-review.md: lost-property.B1.last',
        },
      ],
      [
        'time',
        'give-last-seen-time',
        'How closely can you place the last sighting in time?',
        '可精确也可粗略。',
        'morning',
        'It was around ten this morning, although I did not check the clock.',
        'afternoon',
        'I can only say it was yesterday afternoon.',
        {
          state: 'model-reviewed',
          record: 'emergency-review.md: lost-property.B1.time',
        },
      ],
      [
        'feature',
        'describe-mark',
        'Which detail might distinguish it from other items of the same colour?',
        '特征不得依赖另一分支。',
        'sticker',
        'There is a small round sticker with a red dot on one side.',
        'plain',
        'There are no labels or marks, which may make it harder to distinguish.',
        {
          state: 'model-reviewed',
          record: 'emergency-review.md: lost-property.B1.feature',
        },
      ],
      [
        'contents',
        'describe-associated-object',
        'Was anything small kept with it that you could describe?',
        '最少虚构物件，无私密内容。',
        'ticket',
        'There was a blank sample ticket tucked inside.',
        'nothing',
        'Nothing else was kept with it.',
        {
          state: 'model-reviewed',
          record: 'emergency-review.md: lost-property.B1.contents',
        },
      ],
      [
        'proof',
        'offer-identifying-material',
        'What material could you offer to help compare a possible match?',
        '比较材料不证明拥有权。',
        'photo',
        'I have a photo that shows the colour and shape.',
        'description',
        'I do not have a photo, but I can give a more detailed description.',
        {
          state: 'model-reviewed',
          record: 'emergency-review.md: lost-property.B1.proof',
        },
      ],
      [
        'contact',
        'choose-practice-followup',
        'What reply format would help you keep track of this fictional enquiry?',
        '只模拟形式。',
        'written',
        'A written reply would let me refer back to the details.',
        'spoken',
        'A spoken reply would give me a chance to ask about anything unclear.',
        {
          state: 'model-reviewed',
          record: 'emergency-review.md: lost-property.B1.contact',
        },
      ],
      [
        'privacy',
        'protect-private-details',
        'How would you avoid putting real personal information into the practice report?',
        '资料最小化。',
        'alias',
        'I would use a made-up name and leave contact details blank.',
        'omit',
        'I would leave the name section blank and focus on the item itself.',
        {
          state: 'model-reviewed',
          record: 'emergency-review.md: lost-property.B1.privacy',
        },
      ],
      [
        'followup',
        'request-process-information',
        'What would you ask about following up without assuming a search has begun?',
        '流程问题不等于已启动搜索。',
        'process',
        'If I make a report, how would I ask about its progress later?',
        'reference',
        'Would a report reference be provided, and how would I use it?',
        {
          state: 'model-reviewed',
          record: 'emergency-review.md: lost-property.B1.followup',
        },
      ],
      [
        'candidate',
        'avoid-premature-identification',
        'Suppose an item with the same colour is offered as a possible match; what would you say?',
        '相同颜色不够确认。',
        'compare',
        'It might be mine, but I would like to compare the details first.',
        'caution',
        'The colour matches, though I would need more information before identifying it.',
        {
          state: 'model-reviewed',
          record: 'emergency-review.md: lost-property.B1.candidate',
        },
      ],
      [
        'uncertain',
        'acknowledge-memory-gap',
        'How would you explain that the last place you saw it may not be where it was lost?',
        '明确非相邻前提差别。',
        'distinguish',
        'That is where I last remember seeing it, but I may have carried it somewhere else afterwards.',
        'unknown',
        'I can give the last sighting, but I do not know exactly where I left it.',
        {
          state: 'model-reviewed',
          record: 'emergency-review.md: lost-property.B1.uncertain',
        },
      ],
      [
        'next',
        'plan-report-review',
        'What should remain clear when you review this practice description?',
        '没有真实已报失。',
        'memory',
        'It should be clear which details I remember and which are uncertain.',
        'request',
        'It should describe what I am looking for without suggesting the item has already been found.',
        {
          state: 'model-reviewed',
          record: 'emergency-review.md: lost-property.B1.next',
        },
      ],
    ],
    {
      state: 'model-reviewed',
      record: 'emergency-review.md: lost-property.B1 variants',
    },
  ),
  B2: emergencyPack(
    scene,
    'B2',
    {
      canDoZh: '区分最后看见、遗落推测与候选物比对，提出有依据的后续信息请求。',
      complexityZh:
        '管理低辨识度外观、不完整记忆及证明材料缺口；避免过早断言。',
      scaffoldingZh: '具体场所、物品和明确假设支撑权衡，不用真实证件。',
      registerZh: '有分寸且清晰的服务沟通，不推论真实报失程序。',
    },
    [
      [
        'item',
        'identify-lost-item',
        'How would you identify the missing object without starting with details that could apply to almost anything?',
        '具体类别及材质。',
        'bag',
        'It is a blue cloth shopping bag with short handles, rather than a backpack or suitcase.',
        'book',
        'It is a green hardback notebook, not a printed book.',
        {
          state: 'model-reviewed',
          record: 'emergency-review.md: lost-property.B2.item',
        },
      ],
      [
        'last',
        'give-last-seen-place',
        'What location can you report as a remembered sighting rather than a guess about where the loss occurred?',
        '不虚构最终遗落位置。',
        'cafe',
        'I can place it at the cafe table from memory; I cannot establish where it went after that.',
        'reading',
        'My last clear memory is of it beside my chair in the reading room.',
        {
          state: 'model-reviewed',
          record: 'emergency-review.md: lost-property.B2.last',
        },
      ],
      [
        'time',
        'give-last-seen-time',
        'How would you express a useful time window without inventing an exact time?',
        '时间范围来自选定虚构事实。',
        'morning',
        'It was between breakfast and midday today, but I cannot narrow it down further.',
        'afternoon',
        'It was sometime yesterday afternoon; a precise time would be a guess.',
        {
          state: 'model-reviewed',
          record: 'emergency-review.md: lost-property.B2.time',
        },
      ],
      [
        'feature',
        'describe-mark',
        'How would you describe a distinguishing feature, or its absence, accurately?',
        '无特殊标记也如实说。',
        'mark',
        'There is a faded circular sticker on one side, which may be more useful than the colour alone.',
        'plain',
        'There are no distinctive markings, so the description may fit several similar objects.',
        {
          state: 'model-reviewed',
          record: 'emergency-review.md: lost-property.B2.feature',
        },
      ],
      [
        'contents',
        'describe-associated-object',
        'What additional object, if any, could be relevant when comparing a candidate?',
        '关联物是虚构，不索要敏感内容。',
        'ticket',
        'A blank sample ticket was tucked inside; I could describe its size if that became useful.',
        'none',
        'There was nothing else with it, so I cannot offer an identifying detail of that kind.',
        {
          state: 'model-reviewed',
          record: 'emergency-review.md: lost-property.B2.contents',
        },
      ],
      [
        'proof',
        'offer-identifying-material',
        'How would you present supporting material without treating it as conclusive identification?',
        '图片材料有限。',
        'image',
        'I have an image that may help with comparison, although it does not show every side.',
        'none',
        'I have no image, so I would rely on a careful description and keep any identification tentative.',
        {
          state: 'model-reviewed',
          record: 'emergency-review.md: lost-property.B2.proof',
        },
      ],
      [
        'contact',
        'choose-practice-followup',
        'What would make the format of a practice reply useful for checking details later?',
        '形式取舍。',
        'written',
        'A written reply would let me compare details without relying on my memory of a conversation.',
        'spoken',
        'A spoken reply would let me clarify unfamiliar descriptions, provided I could take notes.',
        {
          state: 'model-reviewed',
          record: 'emergency-review.md: lost-property.B2.contact',
        },
      ],
      [
        'privacy',
        'protect-private-details',
        'How would you keep a rehearsal of identification questions separate from real personal data?',
        '无需真实身份证明。',
        'fiction',
        'I would use clearly fictional examples and leave every real identifier out.',
        'omit',
        'I would omit the identity section and practise only how to ask what information would be needed.',
        {
          state: 'model-reviewed',
          record: 'emergency-review.md: lost-property.B2.privacy',
        },
      ],
      [
        'followup',
        'request-process-information',
        'How would you enquire about next steps without implying the desk has already searched?',
        '未行动，不假定。',
        'process',
        'Could you explain what happens after a report is submitted and how an update could be requested?',
        'reference',
        'If a reference is issued, could you explain when and how it should be quoted?',
        {
          state: 'model-reviewed',
          record: 'emergency-review.md: lost-property.B2.followup',
        },
      ],
      [
        'candidate',
        'avoid-premature-identification',
        'If a candidate matches the colour but its identifying details have not been compared, how would you respond?',
        '保持候选未确认。',
        'compare',
        'The colour is consistent with my description, but I would need to compare the less general features.',
        'unconfirmed',
        'It remains a possible match rather than an identified item until those details are checked.',
        {
          state: 'model-reviewed',
          record: 'emergency-review.md: lost-property.B2.candidate',
        },
      ],
      [
        'uncertain',
        'acknowledge-memory-gap',
        'How would you correct a listener who equates your last sighting with the place where you definitely left the item?',
        '假设误解，明确校正。',
        'correct',
        'I am certain only about the last sighting; I have not established that I left it there.',
        'qualify',
        'That location is a starting point for my account, not a confirmed location of the loss.',
        {
          state: 'model-reviewed',
          record: 'emergency-review.md: lost-property.B2.uncertain',
        },
      ],
      [
        'next',
        'plan-report-review',
        'What would you check before considering the wording of this report ready?',
        '不冒充已找到或报告已交。',
        'specificity',
        'I would check that the useful identifying details are prominent and the uncertain details remain qualified.',
        'status',
        'I would check that the report asks for help tracing the item rather than implying a search result.',
        {
          state: 'model-reviewed',
          record: 'emergency-review.md: lost-property.B2.next',
        },
      ],
    ],
    {
      state: 'model-reviewed',
      record: 'emergency-review.md: lost-property.B2 variants',
    },
  ),
  C1: emergencyPack(
    scene,
    'C1',
    {
      canDoZh: '精准管理报失叙述的记忆依据、识别特征及候选物确认状态。',
      complexityZh:
        '权衡低辨识度特征和有限比较资料，修复最后看见被当作确定遗落的推论。',
      scaffoldingZh:
        '具象虚构物品和明确候选物假设提供语境；不引入法律证明规则。',
      registerZh: 'CEFR C1 服务沟通与澄清取向，礼貌审慎而不官样。',
    },
    [
      [
        'item',
        'identify-lost-item',
        'What description would establish the type of object before moving on to the details needed to distinguish it?',
        '具体物件先于细节。',
        'bag',
        'It is a blue cloth shopping bag with short handles; I would distinguish that from a travel bag before adding smaller details.',
        'book',
        'It is a green hardback notebook with unprinted pages, which should prevent it being confused with a published book.',
        {
          state: 'model-reviewed',
          record: 'emergency-review.md: lost-property.C1.item',
        },
      ],
      [
        'last',
        'give-last-seen-place',
        'How would you anchor the account in a reliable memory without extending that memory into an unsupported account of the loss?',
        '可靠锚点与未观察后续分开。',
        'cafe',
        'My clearest recollection places it at a cafe table; I cannot reconstruct its movements after that with confidence.',
        'reading',
        'I distinctly remember it beside my chair in the reading room, but that is the limit of what I can locate reliably.',
        {
          state: 'model-reviewed',
          record: 'emergency-review.md: lost-property.C1.last',
        },
      ],
      [
        'time',
        'give-last-seen-time',
        'How would you give the most useful time information your recollection genuinely supports?',
        '准确不等于假精确。',
        'window',
        'I can narrow the sighting to the period between breakfast and midday today, but not to a particular minute.',
        'broad',
        'Yesterday afternoon is the narrowest period I can support; a more precise time would create a false impression of certainty.',
        {
          state: 'model-reviewed',
          record: 'emergency-review.md: lost-property.C1.time',
        },
      ],
      [
        'feature',
        'describe-mark',
        'How would you assess the descriptive value of a feature without overselling how distinctive it is?',
        '区分有特征与唯一特征。',
        'sticker',
        'There is a faded circular sticker that may help narrow the comparison, although I would not assume it is unique to my item.',
        'plain',
        'Its plain surface offers little to distinguish it, so I would be explicit that the description could fit more than one object.',
        {
          state: 'model-reviewed',
          record: 'emergency-review.md: lost-property.C1.feature',
        },
      ],
      [
        'contents',
        'describe-associated-object',
        'How would you introduce an associated object only to the extent that it could assist a comparison?',
        '最少相关资料。',
        'ticket',
        'A blank sample ticket was tucked inside; I would mention that as an additional detail, not as proof by itself.',
        'none',
        'There was no associated object, so I would not pad the account with a detail I cannot provide.',
        {
          state: 'model-reviewed',
          record: 'emergency-review.md: lost-property.C1.contents',
        },
      ],
      [
        'proof',
        'offer-identifying-material',
        'How would you explain both the usefulness and the limits of the material you can provide?',
        '照片不构成自动认证。',
        'photo',
        'I have a partial photograph that may support a comparison, but it does not show enough to settle every identifying detail.',
        'memory',
        'I have no photograph, which means the comparison would depend on a description whose less certain parts I should identify explicitly.',
        {
          state: 'model-reviewed',
          record: 'emergency-review.md: lost-property.C1.proof',
        },
      ],
      [
        'contact',
        'choose-practice-followup',
        'Which reply format would best support careful comparison rather than a hurried identification?',
        '形式偏好有理由。',
        'written',
        'A written reply would allow me to compare each feature systematically and flag discrepancies before drawing a conclusion.',
        'discussion',
        'A spoken discussion would let me explore a discrepancy immediately, although I would want notes of the details afterwards.',
        {
          state: 'model-reviewed',
          record: 'emergency-review.md: lost-property.C1.contact',
        },
      ],
      [
        'privacy',
        'protect-private-details',
        'How would you respond if this rehearsal appeared to require real identifying material?',
        '明确不需要真实材料。',
        'fiction',
        'I would ask to substitute a fictional example; the language of the exchange can be practised without exposing real identifiers.',
        'boundary',
        'I would decline to supply identifying material and keep the exercise to how such a request could be clarified.',
        {
          state: 'model-reviewed',
          record: 'emergency-review.md: lost-property.C1.privacy',
        },
      ],
      [
        'followup',
        'request-process-information',
        'How could a follow-up enquiry remain useful without presupposing that any report or search is already under way?',
        '真实服务未启动。',
        'conditional',
        'Could you explain how a submitted report would be followed up, including whether a reference would be available?',
        'sequence',
        'Could you outline the steps after submission, so I can distinguish making a report from receiving a search update?',
        {
          state: 'model-reviewed',
          record: 'emergency-review.md: lost-property.C1.followup',
        },
      ],
      [
        'candidate',
        'avoid-premature-identification',
        'How would you respond to a hypothetical candidate that matches the general description but has not undergone a detailed comparison?',
        '假设候选不升级确认。',
        'provisional',
        'It is a plausible candidate, but I would reserve identification until the less general details have been compared.',
        'discrepancies',
        'I would ask to examine any discrepancies before allowing a broad similarity to stand in for a positive identification.',
        {
          state: 'model-reviewed',
          record: 'emergency-review.md: lost-property.C1.candidate',
        },
      ],
      [
        'uncertain',
        'acknowledge-memory-gap',
        'What clarification would you offer if “last seen there” were restated as “definitely left there”?',
        '修复明确假设错误归纳。',
        'distinguish',
        'Those are different claims: I can support the sighting, but I cannot establish where the item was ultimately left.',
        'limit',
        'I would ask that the record retain “last seen”, because the stronger wording goes beyond my recollection.',
        {
          state: 'model-reviewed',
          record: 'emergency-review.md: lost-property.C1.uncertain',
        },
      ],
      [
        'next',
        'plan-report-review',
        'What would you regard as complete at the end of this description exercise, and what would remain open?',
        '只达成描述目标。',
        'wording',
        'The wording may be ready for review, while the item’s location and any possible identification remain entirely open.',
        'draft',
        'I would retain it as a draft if the uncertain details still sound definite; a polished report is not necessarily an accurate one.',
        {
          state: 'model-reviewed',
          record: 'emergency-review.md: lost-property.C1.next',
        },
      ],
    ],
    {
      state: 'model-reviewed',
      record: 'emergency-review.md: lost-property.C1 variants',
    },
  ),
}
