import { emergencyPack, type EmergencyScene } from './authoring'

const scene: EmergencyScene = {
  sceneId: 'emergency-01',
  slug: 'pharmacy-medicine',
  situations: [
    '纯虚构药房英语模拟。对方是练习搭档扮演的柜台人员，只帮助整理给药师的问题。道具有空药盒、写有 expiry date 的示例标签及印有示例问题的卡片（“What does this word mean?”、“Who can answer my question?”），另有空白纸。不含药品名称或用法。可以从参考答案选择虚构经历，不提供真实健康资料。柜台可讨论标签文字、隐私和提问顺序，不能解答治疗问题；没有咨询、购买或联系真实药师。短练只处理实际问到的事项。',
    '纯虚构药房留言演练。练习搭档帮你准备尚未发送的问题卡，药师不在本轮中。空药盒上有 expiry date 示例文字，另有印着 “What does this word mean?” 和 “Who can answer my question?” 的问题卡及空白纸。重点是把疑问、资料缺口和希望的答复形式写清，不默认任何药物适合使用。所有经历可用答案中的虚构事实；不填写真实姓名、药品清单或联系方式。本练习不会发送留言或联系真实服务。',
  ],
  paths: [
    {
      short: ['need', 'label', 'next'],
      standard: ['need', 'label', 'history', 'other', 'format', 'next'],
      extended: [
        'need',
        'label',
        'history',
        'other',
        'record',
        'privacy',
        'format',
        'priority',
        'uncertain',
        'next',
      ],
    },
    {
      short: ['need', 'question', 'next'],
      standard: ['need', 'question', 'record', 'pace', 'format', 'next'],
      extended: [
        'need',
        'label',
        'history',
        'other',
        'question',
        'pace',
        'format',
        'priority',
        'uncertain',
        'next',
      ],
    },
  ],
  closing:
    'The pharmacy language practice is complete. Questions remain questions, not advice to use a medicine. No real pharmacist was contacted or purchase made.',
  partial:
    'This pharmacy practice stops with some details unconfirmed. No real pharmacist was contacted and no medicine advice was given.',
  repairs: {
    clarify: 'You can ask which part of the pharmacy question to answer.',
    struggle: 'You can use a short phrase from the fictional examples.',
    offTopic: 'Let us return to preparing a question for a pharmacist.',
    unknown:
      'That wording is not covered locally; no health detail has been inferred.',
    changed: 'The new stated detail replaces the earlier one in this practice.',
    refusedClosing:
      'The pharmacy practice has stopped. No real pharmacist was contacted; no personal health details are required.',
  },
}
export const pharmacyMedicine = {
  A1: emergencyPack(
    scene,
    'A1',
    {
      canDoZh: '借助道具指出看不懂的标签，并提出一个简短药房沟通需要。',
      complexityZh: '一次说一个具体物件、经历或选择；不解释药效。',
      scaffoldingZh: '中文情境、可见标签词、短问句与完整双选句支持直接应答。',
      registerZh: '基础礼貌柜台口语；隐私和不知道均可直接表达。',
    },
    [
      [
        'need',
        'state-need',
        'What do you need help with at the pharmacy?',
        '选择虚构需求。',
        'label',
        'I need help with this label.',
        'question',
        'I have a question for the pharmacist.',
        {
          state: 'model-reviewed',
          record: 'emergency-review.md: fix1 pharmacy-medicine.A1.need',
        },
      ],
      [
        'label',
        'identify-label-gap',
        'Can you read the words on the box?',
        '说能否看清示例字。',
        'small',
        'The words are too small.',
        'word',
        'I can read them, but I do not know “expiry”.',
        {
          state: 'model-reviewed',
          record: 'emergency-review.md: fix1 pharmacy-medicine.A1.label',
        },
      ],
      [
        'history',
        'report-past-experience',
        'Have you used medicine before?',
        '选择虚构经历，不提供真实资料。',
        'yes',
        'Yes, I have used medicine before.',
        'unsure',
        'I do not remember.',
        {
          state: 'model-reviewed',
          record: 'emergency-review.md: fix1 pharmacy-medicine.A1.history',
        },
      ],
      [
        'other',
        'disclose-other-products',
        'Do you take any vitamins?',
        '仅选择虚构情况。',
        'yes',
        'Yes, I take a vitamin.',
        'no',
        'No, I do not take vitamins.',
        {
          state: 'model-reviewed',
          record: 'emergency-review.md: fix1 pharmacy-medicine.A1.other',
        },
      ],
      [
        'record',
        'offer-written-information',
        'Do you have a list with you?',
        '说明虚构清单是否在手。',
        'list',
        'Yes, I have a list.',
        'none',
        'No, I do not have a list.',
        {
          state: 'model-reviewed',
          record: 'emergency-review.md: fix1 pharmacy-medicine.A1.record',
        },
      ],
      [
        'privacy',
        'request-privacy',
        'Do you want to talk here or somewhere quiet?',
        '选择交谈位置偏好，不表示已安排。',
        'here',
        'Here is fine.',
        'quiet',
        'Somewhere quiet, please.',
        {
          state: 'model-reviewed',
          record: 'emergency-review.md: fix1 pharmacy-medicine.A1.privacy',
        },
      ],
      [
        'format',
        'choose-response-format',
        'Would you like words or a picture on your question card?',
        '选择问题卡形式。',
        'words',
        'Words, please.',
        'picture',
        'A picture, please.',
        {
          state: 'model-reviewed',
          record: 'emergency-review.md: fix1 pharmacy-medicine.A1.format',
        },
      ],
      [
        'priority',
        'set-question-priority',
        'Which topic comes first: the box or medicine names?',
        '选择话题，不要求已有清单。',
        'box',
        'The box comes first.',
        'names',
        'Medicine names come first.',
        {
          state: 'model-reviewed',
          record: 'emergency-review.md: fix1 pharmacy-medicine.A1.priority',
        },
      ],
      [
        'uncertain',
        'acknowledge-uncertainty',
        'Do you know the medicine name?',
        '只说明是否知道；不说真实药品名。',
        'known',
        'Yes, I know the name.',
        'unknown',
        'No, I do not know the name.',
        {
          state: 'model-reviewed',
          record: 'emergency-review.md: fix1 pharmacy-medicine.A1.uncertain',
        },
      ],
      [
        'question',
        'formulate-professional-question',
        'What would you like to ask the pharmacist?',
        '只提出问题，不回答医疗问题。',
        'meaning',
        'What does this word mean?',
        'who',
        'Who can answer my question?',
        {
          state: 'model-reviewed',
          record: 'emergency-review.md: fix1 pharmacy-medicine.A1.question',
        },
      ],
      [
        'pace',
        'request-speaking-support',
        'How should we practise your pharmacy question?',
        '选择练习支架。',
        'slow',
        'Please speak slowly.',
        'read',
        'Please let me read my card.',
        {
          state: 'model-reviewed',
          record: 'emergency-review.md: fix1 pharmacy-medicine.A1.pace',
        },
      ],
      [
        'next',
        'choose-next-language-step',
        'What do you want to do with your question card now?',
        '选择练习下一步。',
        'keep',
        'I want to keep the card.',
        'read',
        'I want to read it aloud.',
        {
          state: 'model-reviewed',
          record: 'emergency-review.md: fix1 pharmacy-medicine.A1.next',
        },
      ],
    ],
    {
      state: 'model-reviewed',
      record: 'emergency-review.md: fix1 pharmacy-medicine.A1 variants',
    },
  ),
  A2: emergencyPack(
    scene,
    'A2',
    {
      canDoZh: '在可预测药房对话中交代资料缺口并准备给药师的具体问题。',
      complexityZh: '连结一个事实与一个简短原因，区分已有清单和稍后补充。',
      scaffoldingZh: '标签和留言卡明确在场，提供可直接采用的句型与替代请求。',
      registerZh: '清楚礼貌的日常咨询准备语言，不作医疗判断。',
    },
    [
      [
        'need',
        'state-need',
        'Are you here to ask about the label or to prepare a question?',
        '选择本次目的。',
        'label',
        'I would like someone to explain the label words.',
        'question',
        'I want to prepare a question before I speak to the pharmacist.',
        {
          state: 'model-reviewed',
          record: 'emergency-review.md: pharmacy-medicine.A2.need',
        },
      ],
      [
        'label',
        'identify-label-gap',
        'What is difficult about the sample label?',
        '指出具体阅读障碍。',
        'print',
        'The print is small, so I cannot read it easily.',
        'expiry',
        'I can see “expiry date”, but I do not understand it.',
        {
          state: 'model-reviewed',
          record: 'emergency-review.md: pharmacy-medicine.A2.label',
        },
      ],
      [
        'history',
        'report-past-experience',
        'What can you say about your earlier medicine use?',
        '使用虚构记忆，不推断反应。',
        'used',
        'I used a medicine last year, but I cannot remember its name.',
        'none',
        'I have no earlier medicine use to describe.',
        {
          state: 'model-reviewed',
          record: 'emergency-review.md: pharmacy-medicine.A2.history',
        },
      ],
      [
        'other',
        'disclose-other-products',
        'What could you tell the pharmacist about other products you use?',
        '选虚构信息或不确定。',
        'vitamin',
        'I use a vitamin, and I can show the box later.',
        'unsure',
        'I am not sure which products to include on the list.',
        {
          state: 'model-reviewed',
          record: 'emergency-review.md: pharmacy-medicine.A2.other',
        },
      ],
      [
        'record',
        'offer-written-information',
        'Is your information written down or do you need a blank card?',
        '说明资料状态。',
        'written',
        'It is written down on this card.',
        'blank',
        'I need a blank card to write it down.',
        {
          state: 'model-reviewed',
          record: 'emergency-review.md: pharmacy-medicine.A2.record',
        },
      ],
      [
        'privacy',
        'request-privacy',
        'Would you prefer to discuss your questions away from the counter?',
        '可请求也可不请求。',
        'quiet',
        'Yes, I would prefer a quieter place.',
        'here',
        'No, I can discuss my questions here.',
        {
          state: 'model-reviewed',
          record: 'emergency-review.md: pharmacy-medicine.A2.privacy',
        },
      ],
      [
        'format',
        'choose-response-format',
        'What kind of reply would be easier for you to understand?',
        '期望形式仍是请求。',
        'written',
        'A short written reply would help me.',
        'spoken',
        'A spoken reply with simple words would be easier.',
        {
          state: 'model-reviewed',
          record: 'emergency-review.md: pharmacy-medicine.A2.format',
        },
      ],
      [
        'priority',
        'set-question-priority',
        'Should the pharmacist hear the label question or your background first?',
        '排列两个不同主题。',
        'label',
        'Please put the label question first.',
        'background',
        'Please put my background information first.',
        {
          state: 'model-reviewed',
          record: 'emergency-review.md: pharmacy-medicine.A2.priority',
        },
      ],
      [
        'uncertain',
        'acknowledge-uncertainty',
        'What will you say if you cannot remember a product name?',
        '练习如实表达缺口。',
        'unknown',
        'I cannot remember the name, but I can bring the box later.',
        'check',
        'I need to check the name before I tell you.',
        {
          state: 'model-reviewed',
          record: 'emergency-review.md: pharmacy-medicine.A2.uncertain',
        },
      ],
      [
        'question',
        'formulate-professional-question',
        'Which question belongs on your card for the pharmacist?',
        '不由模拟柜台提供用药结论。',
        'list',
        'Which information do you need from me?',
        'label',
        'Could you explain these label words to me?',
        {
          state: 'model-reviewed',
          record: 'emergency-review.md: pharmacy-medicine.A2.question',
        },
      ],
      [
        'pace',
        'request-speaking-support',
        'Would reading the pharmacy question together help, or do you want time alone?',
        '选择语言练习方式。',
        'together',
        'Please read it with me, one line at a time.',
        'alone',
        'I would like a minute to read it myself.',
        {
          state: 'model-reviewed',
          record: 'emergency-review.md: pharmacy-medicine.A2.pace',
        },
      ],
      [
        'next',
        'choose-next-language-step',
        'How would you like to finish preparing your pharmacy message?',
        '只安排练习，不发送。',
        'rehearse',
        'I would like to practise saying it once.',
        'save',
        'I would like to keep it and add details later.',
        {
          state: 'model-reviewed',
          record: 'emergency-review.md: pharmacy-medicine.A2.next',
        },
      ],
    ],
    {
      state: 'model-reviewed',
      record: 'emergency-review.md: pharmacy-medicine.A2 variants',
    },
  ),
  B1: emergencyPack(
    scene,
    'B1',
    {
      canDoZh: '说明记忆或记录不完整的情况，把药房疑问整理为可追问的信息。',
      complexityZh: '处理非例行资料缺口，连接经历、理由及后续核对计划。',
      scaffoldingZh:
        '明确模拟角色不提供医疗解答；可借双选句组织信息但需维持前后限制。',
      registerZh: '自然中性咨询语域，既能求助也能保留不确定性。',
    },
    [
      [
        'need',
        'state-need',
        'What would you like the pharmacist to help you understand?',
        '提出信息需求而非要求模拟角色判断安全。',
        'wording',
        'I want to understand the wording on a label before asking further questions.',
        'list',
        'I want to check what information to include in a medicine list.',
        {
          state: 'model-reviewed',
          record: 'emergency-review.md: pharmacy-medicine.B1.need',
        },
      ],
      [
        'label',
        'identify-label-gap',
        'Can you explain where your difficulty with the label begins?',
        '区分读不清和词义不明。',
        'print',
        'I cannot make out the small print, so I cannot quote the whole line.',
        'meaning',
        'I can read the line with “expiry date”, but I need someone to explain the term.',
        {
          state: 'model-reviewed',
          record: 'emergency-review.md: pharmacy-medicine.B1.label',
        },
      ],
      [
        'history',
        'report-past-experience',
        'How much of your earlier medicine use can you describe confidently?',
        '不把记忆当完整记录。',
        'part',
        'I remember using a medicine last winter, but not its name.',
        'record',
        'I would rather refer to a written record than rely on my memory.',
        {
          state: 'model-reviewed',
          record: 'emergency-review.md: pharmacy-medicine.B1.history',
        },
      ],
      [
        'other',
        'disclose-other-products',
        'How could you introduce other products without claiming the list is complete?',
        '练习不完整信息的表达。',
        'vitamin',
        'I use a vitamin, although I still need to check its name.',
        'incomplete',
        'This is the information I remember; there may be something missing.',
        {
          state: 'model-reviewed',
          record: 'emergency-review.md: pharmacy-medicine.B1.other',
        },
      ],
      [
        'record',
        'offer-written-information',
        'What could you provide if the pharmacist needs more detail?',
        '资源可以是已有或未来准备。',
        'photo',
        'I have a picture of the packaging that I could show.',
        'later',
        'I could bring the packaging later; I do not have it with me.',
        {
          state: 'model-reviewed',
          record: 'emergency-review.md: pharmacy-medicine.B1.record',
        },
      ],
      [
        'privacy',
        'request-privacy',
        'How would you handle a question you do not want to discuss at an open counter?',
        '隐私选择不等于中止整轮。',
        'private',
        'I would ask whether there is a more private place to speak.',
        'limited',
        'I would explain that I prefer to leave that detail out here.',
        {
          state: 'model-reviewed',
          record: 'emergency-review.md: pharmacy-medicine.B1.privacy',
        },
      ],
      [
        'format',
        'choose-response-format',
        'How should your request describe the kind of explanation you need?',
        '提出答复形式需求。',
        'plain',
        'Please use everyday words and explain one point at a time.',
        'written',
        'Please write the main points so I can ask about anything unclear.',
        {
          state: 'model-reviewed',
          record: 'emergency-review.md: pharmacy-medicine.B1.format',
        },
      ],
      [
        'priority',
        'set-question-priority',
        'With limited time for a conversation, what would you raise first?',
        '根据具体沟通困难排序。',
        'read',
        'I would mention that I cannot understand the label wording.',
        'missing',
        'I would explain that some information is missing from my notes.',
        {
          state: 'model-reviewed',
          record: 'emergency-review.md: pharmacy-medicine.B1.priority',
        },
      ],
      [
        'uncertain',
        'acknowledge-uncertainty',
        'How would you stop an uncertain memory from sounding like a confirmed detail?',
        '准确限定知道什么。',
        'qualify',
        'I think that was last winter, but I would need to check the date.',
        'withhold',
        'I cannot confirm that detail, so please leave it blank for now.',
        {
          state: 'model-reviewed',
          record: 'emergency-review.md: pharmacy-medicine.B1.uncertain',
        },
      ],
      [
        'question',
        'formulate-professional-question',
        'What question could help you prepare for an actual pharmacist conversation?',
        '只拟问题，模拟中不实际咨询。',
        'bring',
        'What would you like me to bring so you can answer my questions?',
        'contact',
        'How can I ask a follow-up question if I forget something?',
        {
          state: 'model-reviewed',
          record: 'emergency-review.md: pharmacy-medicine.B1.question',
        },
      ],
      [
        'pace',
        'request-speaking-support',
        'If the practice question feels too long, what support would you ask for?',
        '假设困难，不虚构已听过的说明。',
        'split',
        'Could we break my question into two shorter sentences?',
        'rehearse',
        'Could I try reading it slowly before we change the wording?',
        {
          state: 'model-reviewed',
          record: 'emergency-review.md: pharmacy-medicine.B1.pace',
        },
      ],
      [
        'next',
        'choose-next-language-step',
        'What remains to be done with your prepared pharmacy questions?',
        '不暗示问题已经解答。',
        'check',
        'I want to check that each question says what I mean.',
        'pause',
        'I will keep the questions and fill in the missing details later.',
        {
          state: 'model-reviewed',
          record: 'emergency-review.md: pharmacy-medicine.B1.next',
        },
      ],
    ],
    {
      state: 'model-reviewed',
      record: 'emergency-review.md: pharmacy-medicine.B1 variants',
    },
  ),
  B2: emergencyPack(
    scene,
    'B2',
    {
      canDoZh: '对比资料来源与答复形式，协商让药师更易处理的提问顺序。',
      complexityZh: '权衡可读性、完整性和隐私；说明理由而不推演医学结论。',
      scaffoldingZh: '限定为拟问及信息整理，给出具体标签和记录差异作支点。',
      registerZh: '专业场合可用但不过度正式；限定语服务于真实资料缺口。',
    },
    [
      [
        'need',
        'state-need',
        'What is the main communication problem you want to resolve before speaking to a pharmacist?',
        '聚焦交流障碍。',
        'terms',
        'The label terminology makes it hard for me to frame a precise question.',
        'organise',
        'My notes mix several concerns together, and I want to separate them before the conversation.',
        {
          state: 'model-reviewed',
          record: 'emergency-review.md: pharmacy-medicine.B2.need',
        },
      ],
      [
        'label',
        'identify-label-gap',
        'How would you distinguish a legibility problem from a question about the label meaning?',
        '明确障碍类型，避免对方误解。',
        'legibility',
        'I need a readable copy first; I cannot reliably quote the smaller text.',
        'meaning',
        'The text is legible, so a larger copy would not solve my difficulty with the meaning.',
        {
          state: 'model-reviewed',
          record: 'emergency-review.md: pharmacy-medicine.B2.label',
        },
      ],
      [
        'history',
        'report-past-experience',
        'How would you present a past experience when your recollection is incomplete?',
        '经历和确定程度一起表达。',
        'memory',
        'I remember using something last winter, but I cannot identify it accurately from memory.',
        'record',
        'I would prefer to check my records before describing that experience in detail.',
        {
          state: 'model-reviewed',
          record: 'emergency-review.md: pharmacy-medicine.B2.history',
        },
      ],
      [
        'other',
        'disclose-other-products',
        'What wording would help distinguish a partial product list from a complete one?',
        '说明列举范围。',
        'partial',
        'These are the products I can currently recall; I have not checked whether the list is complete.',
        'pending',
        'I have not prepared the list yet, so I would like to ask what should be included.',
        {
          state: 'model-reviewed',
          record: 'emergency-review.md: pharmacy-medicine.B2.other',
        },
      ],
      [
        'record',
        'offer-written-information',
        'Would a packaging photo be available, or should the message explain that supporting material is missing?',
        '两种资源状态均成立。',
        'photo',
        'I have a clear photo of the packaging and could refer to it during the conversation.',
        'missing',
        'The packaging is elsewhere, so the message should say that I cannot provide it yet.',
        {
          state: 'model-reviewed',
          record: 'emergency-review.md: pharmacy-medicine.B2.record',
        },
      ],
      [
        'privacy',
        'request-privacy',
        'How could you protect your privacy without making your communication needs unclear?',
        '提出有分寸的边界。',
        'space',
        'I can explain the general question here, but I would prefer a private space for personal details.',
        'later',
        'I would rather postpone the personal details and focus on how to prepare for the conversation.',
        {
          state: 'model-reviewed',
          record: 'emergency-review.md: pharmacy-medicine.B2.privacy',
        },
      ],
      [
        'format',
        'choose-response-format',
        'Would a concise written explanation or a slower spoken discussion suit your needs better?',
        '选择并给理由，仍未发生答复。',
        'written',
        'A concise written explanation would let me revisit unfamiliar terms at my own pace.',
        'spoken',
        'A slower discussion would let me flag the exact point where I stop following.',
        {
          state: 'model-reviewed',
          record: 'emergency-review.md: pharmacy-medicine.B2.format',
        },
      ],
      [
        'priority',
        'set-question-priority',
        'How would you keep the first question focused without losing the other concerns?',
        '处理信息组织而非医疗优先级。',
        'one',
        'I would ask about the unclear label term first and keep the remaining questions on a separate list.',
        'overview',
        'I would briefly name the concerns, then ask the pharmacist which information is needed to discuss them.',
        {
          state: 'model-reviewed',
          record: 'emergency-review.md: pharmacy-medicine.B2.priority',
        },
      ],
      [
        'uncertain',
        'acknowledge-uncertainty',
        'Suppose a draft note says “all products”, but you have not checked the list; how would you qualify it?',
        '这是明确提供的假设草稿，不改写已经清楚的回答。',
        'replace',
        'I would replace “all products” with “the products I currently remember”.',
        'flag',
        'I would add that the list is provisional and still needs checking.',
        {
          state: 'model-reviewed',
          record: 'emergency-review.md: pharmacy-medicine.B2.uncertain',
        },
      ],
      [
        'question',
        'formulate-professional-question',
        'How would you ask who can address a concern that the counter assistant cannot answer?',
        '询问责任人，不要求虚构柜台越权。',
        'person',
        'Could you tell me who I should speak to about this question?',
        'route',
        'Could you explain how I can arrange a conversation with the pharmacist?',
        {
          state: 'model-reviewed',
          record: 'emergency-review.md: pharmacy-medicine.B2.question',
        },
      ],
      [
        'pace',
        'request-speaking-support',
        'What would help you rehearse a detailed question without hiding the important uncertainty?',
        '控制句式而不删事实边界。',
        'split',
        'Let us separate what I know from what I still need to check.',
        'mark',
        'I would keep the uncertainty in the sentence and mark a pause before it.',
        {
          state: 'model-reviewed',
          record: 'emergency-review.md: pharmacy-medicine.B2.pace',
        },
      ],
      [
        'next',
        'choose-next-language-step',
        'How would you close the preparation stage while leaving substantive questions open?',
        '总结的是准备，不是已获得医疗建议。',
        'ready',
        'The questions are ready for a pharmacist, but they have not been answered.',
        'revise',
        'I need to revise my notes before deciding that the questions are ready.',
        {
          state: 'model-reviewed',
          record: 'emergency-review.md: pharmacy-medicine.B2.next',
        },
      ],
    ],
    {
      state: 'model-reviewed',
      record: 'emergency-review.md: pharmacy-medicine.B2 variants',
    },
  ),
  C1: emergencyPack(
    scene,
    'C1',
    {
      canDoZh:
        '在药房咨询准备中精确区分原文、回忆和待核实资料，并自然协商沟通方式。',
      complexityZh:
        '管理资料依据、信息排序和对方职责，处理具体草稿中范围过宽的措辞。',
      scaffoldingZh:
        '有明确道具和假设草稿；高级表达来自资料冲突与隐私选择，不来自反复口述安全免责声明。',
      registerZh: '审慎而自然的专业咨询口语；采用 CEFR C1 互动和澄清设计依据。',
    },
    [
      [
        'need',
        'state-need',
        'What would make your eventual conversation with the pharmacist more productive?',
        '明确准备需求及其原因。',
        'separate',
        'I need to separate the wording I cannot interpret from the background information the pharmacist may need.',
        'focus',
        'I would like to turn a rather scattered set of concerns into a few questions that can be addressed individually.',
        {
          state: 'model-reviewed',
          record: 'emergency-review.md: pharmacy-medicine.C1.need',
        },
      ],
      [
        'label',
        'identify-label-gap',
        'Where should the distinction between the printed wording and your interpretation be made explicit?',
        '原文与解读分开，不自作药品解释。',
        'quote',
        'I can quote the visible term “expiry date”, but I do not want my interpretation to be mistaken for the wording on the box.',
        'unreadable',
        'Part of the print is unreadable, so I would leave a gap rather than reconstruct the sentence from memory.',
        {
          state: 'model-reviewed',
          record: 'emergency-review.md: pharmacy-medicine.C1.label',
        },
      ],
      [
        'history',
        'report-past-experience',
        'How would you communicate a relevant recollection without giving it more precision than it warrants?',
        '保留记忆的不确定程度。',
        'approximate',
        'I recall using a product around last winter, although I would need the record to identify it or give a reliable date.',
        'defer',
        'I would prefer to defer the details until I can consult my notes; an approximate account might create more confusion than it resolves.',
        {
          state: 'model-reviewed',
          record: 'emergency-review.md: pharmacy-medicine.C1.history',
        },
      ],
      [
        'other',
        'disclose-other-products',
        'How could your message make the limits of the product information immediately apparent?',
        '明确范围，避免完整性误读。',
        'heading',
        'I would head the section “Products recalled so far” and make clear that it has not been checked against the packaging.',
        'absent',
        'I would say that a product list has not yet been assembled and ask what information would make it useful.',
        {
          state: 'model-reviewed',
          record: 'emergency-review.md: pharmacy-medicine.C1.other',
        },
      ],
      [
        'record',
        'offer-written-information',
        'How would you describe the material available for checking details, as distinct from the details themselves?',
        '有资料不等于已经核对过。',
        'image',
        'I have a packaging image available, but I have not yet checked my written notes against it.',
        'later',
        'The relevant packaging is not with me; I can offer to bring it, but not claim that its details have been verified.',
        {
          state: 'model-reviewed',
          record: 'emergency-review.md: pharmacy-medicine.C1.record',
        },
      ],
      [
        'privacy',
        'request-privacy',
        'How would you negotiate the setting if a useful explanation required more personal detail than you wished to share openly?',
        '具体原因支撑隐私请求。',
        'move',
        'I am happy to outline the communication problem here, but I would want a more private setting before discussing personal details.',
        'limit',
        'For now, I would keep the conversation to what information is needed and reserve the personal account for another setting.',
        {
          state: 'model-reviewed',
          record: 'emergency-review.md: pharmacy-medicine.C1.privacy',
        },
      ],
      [
        'format',
        'choose-response-format',
        'Which response format would address your difficulty most directly, and why?',
        '比较答复形式，不声称已理解。',
        'annotated',
        'A short written explanation linked to the label terms would help me see exactly which part each point addresses.',
        'dialogue',
        'A paced conversation would suit me better, because I could distinguish an unfamiliar word from a point I had simply misheard.',
        {
          state: 'model-reviewed',
          record: 'emergency-review.md: pharmacy-medicine.C1.format',
        },
      ],
      [
        'priority',
        'set-question-priority',
        'How would you prevent a brief opening summary from burying the question you most want to ask?',
        '自然管理话语顺序。',
        'lead',
        'I would lead with the label question, then offer the background only where it helps the pharmacist understand what I am asking.',
        'signpost',
        'I would signal that there are two separate issues and ask to deal with the wording before the incomplete notes.',
        {
          state: 'model-reviewed',
          record: 'emergency-review.md: pharmacy-medicine.C1.priority',
        },
      ],
      [
        'uncertain',
        'acknowledge-uncertainty',
        'A separate sample draft says “I have included everything” although its author has not checked; what revision would preserve the useful information?',
        '独立编辑样例，不虚构用户曾这样说。',
        'scope',
        '“I have included everything I can currently recall” preserves the contribution while making its limit explicit.',
        'process',
        '“This is my initial list; I still need to check it” makes the unfinished checking process clear.',
        {
          state: 'model-reviewed',
          record: 'emergency-review.md: pharmacy-medicine.C1.uncertain',
        },
      ],
      [
        'question',
        'formulate-professional-question',
        'How would you redirect a question politely when the person helping with the message is not the person who can answer it?',
        '职责边界以实际请求表达。',
        'route',
        'Could you tell me how to put the substantive question to the pharmacist once we have settled the wording?',
        'separate',
        'Could we keep the wording question here and leave the medicine-related question for a conversation with the pharmacist?',
        {
          state: 'model-reviewed',
          record: 'emergency-review.md: pharmacy-medicine.C1.question',
        },
      ],
      [
        'pace',
        'request-speaking-support',
        'What revision would make a complex pharmacy question easier to follow without flattening its distinctions?',
        '保留已知与未知之间的关系。',
        'order',
        'I would put the concrete question first and move the qualification into a second sentence, where it is less likely to be missed.',
        'retain',
        'I would retain the qualification but shorten the background, so the listener has fewer details to hold in mind.',
        {
          state: 'model-reviewed',
          record: 'emergency-review.md: pharmacy-medicine.C1.pace',
        },
      ],
      [
        'next',
        'choose-next-language-step',
        'What is a proportionate endpoint for this preparation, given that no pharmacist has answered the questions?',
        '准确区分准备完成与问题解决。',
        'ready',
        'I can regard the questions as ready to raise, while leaving their answers entirely open.',
        'pending',
        'I would stop with a working draft rather than call it ready, because the missing details could change how I frame the questions.',
        {
          state: 'model-reviewed',
          record: 'emergency-review.md: pharmacy-medicine.C1.next',
        },
      ],
    ],
    {
      state: 'model-reviewed',
      record: 'emergency-review.md: pharmacy-medicine.C1 variants',
    },
  ),
}
