import { workPack, type WorkScene, type Review } from './authoring'
const a1: Review = {
  state: 'model-reviewed',
  record:
    'work-review.md#daily-standup: A1 all 12 Q/24 A, rationale, both variants and paths read and corrected by Codex implementation agent, 2026-09-10; model-assisted, not teacher certification',
}
const a2: Review = {
  state: 'model-reviewed',
  record:
    'work-review.md#fix1: A2 all 12 Q/24 A, rationale, both variants and paths reread after I1 correction by Codex implementation agent, 2026-09-10; independent re-review pending',
}
const b1: Review = {
  state: 'model-reviewed',
  record:
    'work-review.md#fix1: B1 all 12 Q/24 A, rationale, both variants and paths reread after I1 correction by Codex implementation agent, 2026-09-10; independent re-review pending',
}
const b2: Review = {
  state: 'model-reviewed',
  record:
    'work-review.md#daily-standup: B2 all 12 Q/24 A, rationale, both variants and paths read and corrected by Codex implementation agent, 2026-09-10; model-assisted, not teacher certification',
}
const c1: Review = {
  state: 'model-reviewed',
  record:
    'work-review.md#daily-standup: C1 all 12 Q/24 A, rationale, both variants and paths read and corrected by Codex implementation agent, 2026-09-10; model-assisted, not teacher certification',
}
const scene: WorkScene = {
  sceneId: 'work-02',
  slug: 'daily-standup',
  situations: [
    '虚构Atlas网站团队晨会。你在准备网站检查；样例工作板有测试清单、按钮文字、待处理图片和以前项目的参考清单。今天的表单与图片检查均需登录测试环境，因此缺测试账号可能阻碍任一种计划；准备材料仍可离线做。昨天可报告写完测试清单或审阅按钮文字，两者都不是跑完功能测试。团队与个人负责的范围要单独说明。主持人只收集更新，不自动接受求助、安排同事或批准发布。短练只报已做事项、今日计划和阻碍。',
    '虚构Atlas团队异地交接晨会，接班同事需要知道哪些准备资料可用。工作板有测试清单、按钮文字、样例图片和以前项目的参考清单；表单与图片检查都需登录测试环境，缺账号会阻碍任一种检查，但仍可离线准备。昨天的测试清单编写或按钮文字审阅都不代表已运行功能测试。角色可独自负责联系表单，也可只承担团队中的检查；两者均可选择。交接版增加可交付材料与接班提醒，预计时间不等于已交付。',
  ],
  paths: [
    {
      short: ['done', 'plan', 'blocker'],
      standard: ['done', 'plan', 'blocker', 'owner', 'help', 'time'],
      extended: [
        'done',
        'plan',
        'blocker',
        'owner',
        'help',
        'time',
        'evidence',
        'priority',
        'detail',
        'followup',
      ],
    },
    {
      short: ['done', 'plan', 'blocker'],
      standard: ['done', 'plan', 'blocker', 'owner', 'evidence', 'help'],
      extended: [
        'done',
        'plan',
        'blocker',
        'owner',
        'evidence',
        'help',
        'time',
        'priority',
        'handover',
        'warning',
      ],
    },
  ],
  closing:
    'Your standup update is recorded for practice. Plans, estimates and requests remain distinct from completed work and accepted assignments.',
  partial:
    'This standup rehearsal is partly complete. Missing updates have not been inferred.',
  repairs: {
    clarify: 'I can restate this standup question.',
    struggle: 'Try one completed task or one next step.',
    offTopic: 'Let us return to the current work update.',
    unknown:
      'That update is not a covered answer; no progress has been confirmed from it.',
    changed: 'Your earlier update has been replaced in this rehearsal.',
    refusedClosing:
      'The standup rehearsal stops here without further commitments.',
  },
}
export const standupPacks = {
  A1: workPack(
    scene,
    'A1',
    {
      canDoZh: '能用简单过去时与计划短句报告晨会三要点。',
      complexityZh: '区分做完、要做和受阻，拓展增加负责人和证据。',
      scaffoldingZh: '固定表单与工作板提供具体指代，可分步回答。',
      registerZh: '清楚简短，不需解释复杂技术原因。',
    },
    [
      [
        'done',
        'report-completed',
        'What did you finish yesterday?',
        '只说已完成的具体事项。',
        'list',
        'I finished the test list.',
        'labels',
        'I checked the button words.',
        a1,
      ],
      [
        'plan',
        'state-today-plan',
        'What will you work on today?',
        '计划不是完成。',
        'form',
        'I will test the contact form.',
        'pictures',
        'I will check the pictures.',
        a1,
      ],
      [
        'blocker',
        'report-blocker',
        'Is anything stopping your work now?',
        '可有阻碍，也可没有。',
        'account',
        'Yes, I need a test account.',
        'none',
        'No, I can start now.',
        a1,
      ],
      [
        'owner',
        'identify-ownership',
        'Is the contact form your job or a team job?',
        '个人和团队不同。',
        'mine',
        'The contact form is my job.',
        'team',
        'It is a team job. I do the checks.',
        a1,
      ],
      [
        'help',
        'request-support',
        'Would you like help reading the test list?',
        '求助未被接受。',
        'ask',
        'Yes, please read it with me.',
        'no',
        'No, I can read it myself.',
        a1,
      ],
      [
        'time',
        'give-estimate',
        'When do you think your next update will be ready?',
        '只是预计时间。',
        'morning',
        'I think it will be ready this morning.',
        'afternoon',
        'I think it will be ready this afternoon.',
        a1,
      ],
      [
        'evidence',
        'locate-evidence',
        'Where are yesterday’s work notes?',
        '工作资料位置。',
        'board',
        'They are on the work board.',
        'folder',
        'They are in the team folder.',
        a1,
      ],
      [
        'priority',
        'choose-priority',
        'Which should come first, broken links or picture sizes?',
        '只选优先次序。',
        'links',
        'Broken links should come first.',
        'sizes',
        'Picture sizes should come first.',
        a1,
      ],
      [
        'detail',
        'park-detail',
        'Do you want to discuss the button colours in this short meeting?',
        '可以留到会后。',
        'later',
        'No, let us discuss them later.',
        'brief',
        'Yes, just one quick point.',
        a1,
      ],
      [
        'followup',
        'arrange-followup',
        'How will you share your next update?',
        '个人下一步。',
        'board',
        'I will add it to the board.',
        'chat',
        'I will send a team message.',
        a1,
      ],
      [
        'handover',
        'prepare-handover',
        'What can the next person read first?',
        '交接可用材料。',
        'list',
        'They can read the test list.',
        'notes',
        'They can read yesterday’s notes.',
        a1,
      ],
      [
        'warning',
        'flag-limit',
        'Is the whole website ready to use?',
        '避免把小项完成当全部完成。',
        'not-tested',
        'No, we still need to test it.',
        'unknown',
        'I do not know yet.',
        a1,
      ],
    ],
    a1,
  ),
  A2: workPack(
    scene,
    'A2',
    {
      canDoZh: '能把晨会工作、阻碍和求助连成简短更新。',
      complexityZh: '增加完成证据与交接限制，避免把预计当事实。',
      scaffoldingZh: '样例工作板和具体任务支撑简单因果表达。',
      registerZh: '简洁礼貌，能说不需要帮助或留待会后。',
    },
    [
      [
        'done',
        'report-completed',
        'Which small task did you complete before this meeting?',
        '完整事项，不是整体项目。',
        'list',
        'I completed the list of things we need to test.',
        'labels',
        'I checked the button text and wrote down two spelling mistakes.',
        a2,
      ],
      [
        'plan',
        'state-today-plan',
        'What is your first task after the standup?',
        '接下来要做什么。',
        'form',
        'I am going to test the contact form with sample details.',
        'pictures',
        'I am going to check how the pictures look on a small screen.',
        a2,
      ],
      [
        'blocker',
        'report-blocker',
        'Do you have what you need to begin that task?',
        '两种现状都成立。',
        'account',
        'Not yet. I am waiting for a test account.',
        'none',
        'Yes, everything I need is ready.',
        a2,
      ],
      [
        'owner',
        'identify-ownership',
        'Who is doing the contact-form work?',
        '准确说明个人份额。',
        'mine',
        'I am doing that work on my own.',
        'team',
        'The team is doing it together, and I am checking the results.',
        a2,
      ],
      [
        'help',
        'request-support',
        'Would a second person checking your test list help today?',
        '请求或不请求。',
        'ask',
        'Yes, could someone look for anything I have missed?',
        'no',
        'No, thanks. I can compare it with the sample list first.',
        a2,
      ],
      [
        'time',
        'give-estimate',
        'Can you give us a rough time for another update?',
        '粗略预计而非保证。',
        'today',
        'I expect to have an update by four today.',
        'tomorrow',
        'I think tomorrow morning is more likely.',
        a2,
      ],
      [
        'evidence',
        'locate-evidence',
        'Where can the team see your work from yesterday?',
        '询问昨天工作资料的位置，不假设已经跑过测试。',
        'board',
        'I added my notes to the card on the work board.',
        'folder',
        'I saved a short checklist in the team folder.',
        a2,
      ],
      [
        'priority',
        'choose-priority',
        'Would you check links or picture sizes first, and why?',
        '简单优先理由。',
        'links',
        'Links first, because people need to reach the right page.',
        'sizes',
        'Picture sizes first, because large pictures load slowly.',
        a2,
      ],
      [
        'detail',
        'park-detail',
        'Is the button-colour discussion useful for everyone here?',
        '会议内外分流。',
        'later',
        'Probably not. We can talk about it after the standup.',
        'brief',
        'One point is useful for everyone, but the rest can wait.',
        a2,
      ],
      [
        'followup',
        'arrange-followup',
        'What will you do if your work plan changes this afternoon?',
        '变化时更新而非静默承诺。',
        'board',
        'I will update the card and add a short reason.',
        'message',
        'I will tell the team in our chat.',
        a2,
      ],
      [
        'handover',
        'prepare-handover',
        'How can you help the next person find the useful notes?',
        '可执行交接。',
        'link',
        'I can send a link to the checklist.',
        'label',
        'I can mark the latest notes with today’s date.',
        a2,
      ],
      [
        'warning',
        'flag-limit',
        'Does yesterday’s completed task mean the website is finished?',
        '完成范围有限。',
        'remaining',
        'No, there are still other tests to do.',
        'own-only',
        'No, I only know about the small task I completed.',
        a2,
      ],
    ],
    a2,
  ),
  B1: workPack(
    scene,
    'B1',
    {
      canDoZh: '能报告可验证进展、解释阻碍，并给出下一步与粗略预估。',
      complexityZh: '把任务状态、责任和需要他人参与的请求分开。',
      scaffoldingZh: '固定项目减少技术知识要求，需连接理由和后续动作。',
      registerZh: '短会中的清楚工作交流，既不推责也不过度保证。',
    },
    [
      [
        'done',
        'report-completed',
        'What useful result came out of your work yesterday?',
        '说结果而非忙碌时长。',
        'list',
        'I finished a test list, so we now have a clear way to check the form.',
        'labels',
        'I reviewed the button wording and recorded the corrections, ready for someone to apply.',
        b1,
      ],
      [
        'plan',
        'state-today-plan',
        'What do you intend to move forward today?',
        '计划推动的具体事项。',
        'form',
        'I intend to test the form with sample data and record any failures.',
        'pictures',
        'I plan to check the images on smaller screens and identify the ones that need resizing.',
        b1,
      ],
      [
        'blocker',
        'report-blocker',
        'What is preventing progress, if anything?',
        '障碍与无障碍都可说明。',
        'account',
        'The test account is not ready, so I cannot run the planned checks yet.',
        'none',
        'Nothing is blocking me now; the next step is simply to carry out the checks.',
        b1,
      ],
      [
        'owner',
        'identify-ownership',
        'How is responsibility for the contact form divided?',
        '个人独立或团队中的检查角色。',
        'mine',
        'I am responsible for the contact form myself, including its checks.',
        'team',
        'The team shares the contact-form work; my responsibility is checking the results.',
        b1,
      ],
      [
        'help',
        'request-support',
        'Is there a specific contribution you would like from someone else?',
        '指清单审阅协助，不取消此前账号依赖。',
        'ask',
        'Could someone review the test list for missing cases before I use it?',
        'no',
        'I do not need a reviewer yet; I will compare the list with our previous example first.',
        b1,
      ],
      [
        'time',
        'give-estimate',
        'How confident are you about when you can report again?',
        '预估带具体不确定性。',
        'today-estimate',
        'I expect to report this afternoon, though the checks could uncover more work.',
        'unknown',
        'I cannot give a useful time until I have tried the first check.',
        b1,
      ],
      [
        'evidence',
        'locate-evidence',
        'How can a colleague check the work you described from yesterday?',
        '检查的是准备或文字审阅，非功能测试结果。',
        'board',
        'The work card links to my notes and the document I worked on.',
        'folder',
        'The dated files in the team folder show yesterday’s work and the questions I left open.',
        b1,
      ],
      [
        'priority',
        'choose-priority',
        'Which deserves attention first, broken links or oversized pictures?',
        '优先序与原因。',
        'links',
        'I would fix broken links first because they can stop people reaching the form at all.',
        'sizes',
        'I would examine picture sizes first because slow loading may affect every page.',
        b1,
      ],
      [
        'detail',
        'park-detail',
        'How should we handle a detailed question about button colours during this standup?',
        '将深入讨论留给相关人员。',
        'later',
        'We should note the question and discuss it afterwards with the people involved.',
        'brief',
        'We could clarify the one decision needed now and leave the design discussion for later.',
        b1,
      ],
      [
        'followup',
        'arrange-followup',
        'What will you do if the checks reveal a larger problem than expected?',
        '主动更新或补充证据。',
        'notify',
        'I will tell the team what changed and revise my next-step estimate.',
        'record',
        'I will record a clear example of the failure before asking the team to review it.',
        b1,
      ],
      [
        'handover',
        'prepare-handover',
        'What would make your notes useful to a colleague picking up the work?',
        '提供计划检查步骤并区分准备材料与待解问题，不假设已检查。',
        'steps',
        'I can include the steps and sample data needed to run the planned check.',
        'open',
        'I can separate prepared material from open questions so they know where to start.',
        b1,
      ],
      [
        'warning',
        'flag-limit',
        'What should the team avoid assuming from your update?',
        '不要扩大完成范围。',
        'whole',
        'They should not assume the whole website is ready just because one task is complete.',
        'others',
        'They should not treat my update as confirmation that everyone else has finished.',
        b1,
      ],
    ],
    b1,
  ),
  B2: workPack(
    scene,
    'B2',
    {
      canDoZh: '能在短会中突出有用变化、协商协助并解释风险。',
      complexityZh: '权衡即时讨论和异步细节，限定团队成果与个人责任。',
      scaffoldingZh: '项目背景固定，回答需给出证据类型与行动依据。',
      registerZh: '直接而协作，避免把依赖说成借口。',
    },
    [
      [
        'done',
        'report-completed',
        'What changed yesterday that the rest of the team can now use?',
        '成果可使用但未夸大。',
        'list',
        'The test list is complete, giving us a common set of checks rather than separate personal lists.',
        'labels',
        'The wording review is complete, with suggested corrections recorded; those corrections have not been applied yet.',
        b2,
      ],
      [
        'plan',
        'state-today-plan',
        'What outcome are you aiming for before your next update?',
        '预期成果不是已实现。',
        'form',
        'I am aiming for a clear account of which form submissions pass and which fail.',
        'pictures',
        'I want a prioritised list of image problems, rather than a collection of unrelated screenshots.',
        b2,
      ],
      [
        'blocker',
        'report-blocker',
        'Is there an external dependency we should distinguish from work you can do yourself?',
        '无阻碍不排除之后请求可选审阅。',
        'account',
        'Access to a test account is the dependency; I can still prepare the sample cases while that is being arranged.',
        'none',
        'No external dependency prevents me from starting the checks; a second opinion on the list could still be useful.',
        b2,
      ],
      [
        'owner',
        'identify-ownership',
        'Should we read the contact-form update as your own delivery or a shared team effort?',
        '明确个人和团队。',
        'mine',
        'The contact-form delivery is mine, so I will provide the combined update on that piece.',
        'team',
        'It is a shared effort; I can speak for the checks, but the others need to report their own work.',
        b2,
      ],
      [
        'help',
        'request-support',
        'Would a review from a colleague remove uncertainty, or just duplicate your current work?',
        '支持或拒绝请求均有原因。',
        'ask',
        'A second view would help with missing cases; could someone review that part of the list?',
        'no',
        'It would duplicate the first pass at the moment; I will ask once I have identified a specific uncertainty.',
        b2,
      ],
      [
        'time',
        'give-estimate',
        'What can you usefully say about timing without making a premature commitment?',
        '具体估计或暂不估计。',
        'today-estimate',
        'A first set of findings looks achievable this afternoon, provided the initial checks do not reveal a wider issue.',
        'unknown',
        'I would rather time the first few checks before offering a date, as we have not tested this workflow before.',
        b2,
      ],
      [
        'evidence',
        'locate-evidence',
        'What evidence should someone look at before challenging yesterday’s result?',
        '证据可以是测试清单编写或按钮文字审阅。',
        'board',
        'The work card links to yesterday’s document and the notes explaining its scope.',
        'folder',
        'The dated files in the shared folder show the work itself, so the team need not rely on my summary.',
        b2,
      ],
      [
        'priority',
        'choose-priority',
        'How would you choose between link failures and image performance with limited checking time?',
        '权衡影响和成本。',
        'links',
        'I would trace the main user journey first; a broken link on that route matters more than a minor delay elsewhere.',
        'sizes',
        'I would measure the largest images first, since one quick reduction could improve several pages at once.',
        b2,
      ],
      [
        'detail',
        'park-detail',
        'A colour discussion is expanding. How would you keep this update useful to the whole team?',
        '具体会议管理。',
        'park',
        'I would note who needs to be involved and move the detailed discussion out of the standup.',
        'decision',
        'I would ask whether a decision is needed now; if so, we should state that decision without reopening the entire design.',
        b2,
      ],
      [
        'followup',
        'arrange-followup',
        'What would trigger an update before the next scheduled standup?',
        '明确提前沟通条件。',
        'risk',
        'A finding that affects someone else’s plan would trigger a short message with the likely impact.',
        'estimate',
        'A substantial change to my estimate would be worth flagging immediately, even before I know the final answer.',
        b2,
      ],
      [
        'handover',
        'prepare-handover',
        'How would you hand over checks that another person may run differently?',
        '保留可复现性或允许差异。',
        'repeatable',
        'I would specify the setup and expected result, so a different outcome can be investigated.',
        'limits',
        'I would separate essential steps from personal shortcuts, so the next person knows what can safely vary.',
        b2,
      ],
      [
        'warning',
        'flag-limit',
        'Which boundary would you make explicit when your update is passed to the wider project?',
        '防止扩大完成和代表范围。',
        'scope',
        'I would make clear that completing the checklist is not the same as passing all of its checks.',
        'ownership',
        'I would distinguish my verified findings from the status of work owned by other people.',
        b2,
      ],
    ],
    b2,
  ),
  C1: workPack(
    scene,
    'C1',
    {
      canDoZh: '能筛选晨会关键信息，精确表达依赖、置信度和交接边界。',
      complexityZh: '处理资源重复、范围漂移和他人可能误读的状态。',
      scaffoldingZh: '固定样例任务为背景，需自行组织限定与建议。',
      registerZh: '自然简练的高级职业交流，限定来自真实任务条件。',
    },
    [
      [
        'done',
        'report-completed',
        'Which part of yesterday’s work is now firm enough for others to build on?',
        '可依赖的已完成事项。',
        'list',
        'The test list is now settled, so colleagues can use a common baseline; the actual pass-or-fail results are still to come.',
        'labels',
        'The wording review is finished and the corrections are documented, but implementation remains a separate step.',
        c1,
      ],
      [
        'plan',
        'state-today-plan',
        'What is the most useful uncertainty you intend to reduce today?',
        '从忙碌转向信息价值。',
        'form',
        'I want to establish whether failed submissions follow a pattern, so any fix can address a cause rather than individual examples.',
        'pictures',
        'I intend to find out whether image size is the main loading constraint before recommending changes across the site.',
        c1,
      ],
      [
        'blocker',
        'report-blocker',
        'What, if anything, needs another person’s action before your planned work can move?',
        '依赖并提出仍可做的事。',
        'account',
        'The account setup needs to be completed by its owner; in the meantime, I can prepare cases but cannot honestly report test results.',
        'none',
        'Nothing currently needs someone else’s action; the uncertainty is in the work itself, and the next checks should narrow it.',
        c1,
      ],
      [
        'owner',
        'identify-ownership',
        'Where should the team draw the line around what you are accountable for on the contact form?',
        '准确划分责任。',
        'mine',
        'The contact-form work is my responsibility end to end, so questions about that piece should come to me.',
        'team',
        'The delivery belongs to the team; I am accountable for the checks, not for certifying the other contributions.',
        c1,
      ],
      [
        'help',
        'request-support',
        'What would make another pair of eyes worth the interruption today?',
        '有界求助或暂不请求。',
        'ask',
        'A colleague who knows the unusual customer cases could challenge the gaps in my list; could we seek that specific input?',
        'no',
        'I have not yet narrowed the problem enough to use someone’s time well; I will do that first rather than request an open-ended review.',
        c1,
      ],
      [
        'time',
        'give-estimate',
        'How would you communicate timing while the first results could still change the amount of work?',
        '具体预估条件。',
        'today-estimate',
        'I expect an initial readout this afternoon; whether that supports a completion date depends on how consistent the results are.',
        'unknown',
        'There is not yet a sound basis for a completion date, but the first checks should let me offer a range in the next update.',
        c1,
      ],
      [
        'evidence',
        'locate-evidence',
        'If someone needs to pick apart your summary, where should they start?',
        '已完成准备工作的证据，不暗示已运行测试。',
        'board',
        'Start with yesterday’s document linked from the work card; its scope and open questions are recorded alongside it.',
        'folder',
        'The dated folder files preserve the draft and my revisions, so a colleague can examine the changes rather than reconstruct them from the summary.',
        c1,
      ],
      [
        'priority',
        'choose-priority',
        'How would you challenge a request to check every link and image equally thoroughly?',
        '有限资源与风险重点。',
        'journey',
        'I would propose deeper checks on the main customer route and lighter checks elsewhere, making the residual risk visible.',
        'sample',
        'I would suggest an initial sample to identify the dominant issue, then direct the remaining time towards it rather than spread effort evenly.',
        c1,
      ],
      [
        'detail',
        'park-detail',
        'The button-colour issue matters to two people but is holding everyone up. How would you intervene?',
        '有实际原因的委婉打断。',
        'separate',
        'Could we capture the unresolved point and let those two continue afterwards, so the rest of the team can give their updates?',
        'dependency',
        'Before we go further, is there a decision here that blocks anyone else? If not, I suggest we take the detail offline.',
        c1,
      ],
      [
        'followup',
        'arrange-followup',
        'What would justify breaking the usual update rhythm rather than waiting until tomorrow?',
        '影响范围驱动沟通。',
        'dependency',
        'If a finding invalidates another person’s assumption, I would flag it promptly with the smallest useful example.',
        'scope',
        'If the work expands beyond the current scope, I would raise the choice about priorities before quietly absorbing the extra work.',
        c1,
      ],
      [
        'handover',
        'prepare-handover',
        'What would you leave a colleague who must continue before you are next available?',
        '异步交接细节。',
        'reproduce',
        'I would leave a reproducible starting point and the next unanswered question, rather than ask them to infer my reasoning from screenshots.',
        'boundaries',
        'I would mark the conclusions they can rely on and the provisional notes they should treat as leads, not instructions.',
        c1,
      ],
      [
        'warning',
        'flag-limit',
        'How would you prevent this short update becoming an overly confident status line further up the chain?',
        '两种昨日成果均不等于功能测试通过。',
        'checklist',
        'I would keep preparation and wording review distinct from functional testing, rather than let completed work be shortened to tests passed.',
        'scope',
        'I would attach the scope of yesterday’s work to the update, so completion of a small task cannot easily be retold as a site-wide sign-off.',
        c1,
      ],
    ],
    c1,
  ),
}
