import { workPack, type WorkScene, type Review } from './authoring'
const a1: Review = {
  state: 'model-reviewed',
  record:
    'work-review.md#deadline-negotiation: A1 all 12 Q/24 A, rationale, both variants and paths read and corrected by Codex implementation agent, 2026-09-10; model-assisted, not teacher certification',
}
const a2: Review = {
  state: 'model-reviewed',
  record:
    'work-review.md#deadline-negotiation: A2 all 12 Q/24 A, rationale, both variants and paths read and corrected by Codex implementation agent, 2026-09-10; model-assisted, not teacher certification',
}
const b1: Review = {
  state: 'model-reviewed',
  record:
    'work-review.md#deadline-negotiation: B1 all 12 Q/24 A, rationale, both variants and paths read and corrected by Codex implementation agent, 2026-09-10; model-assisted, not teacher certification',
}
const b2: Review = {
  state: 'model-reviewed',
  record:
    'work-review.md#deadline-negotiation: B2 all 12 Q/24 A, rationale, both variants and paths read and corrected by Codex implementation agent, 2026-09-10; model-assisted, not teacher certification',
}
const c1: Review = {
  state: 'model-reviewed',
  record:
    'work-review.md#deadline-negotiation: C1 all 12 Q/24 A, rationale, both variants and paths read and corrected by Codex implementation agent, 2026-09-10; model-assisted, not teacher certification',
}
const scene: WorkScene = {
  sceneId: 'work-04',
  slug: 'deadline-negotiation',
  situations: [
    '虚构项目协商：原计划周五交付客户使用的培训包，包含说明页与练习示例，内容核对需要时间。你向项目负责人提出延长时间或缩减范围，两者都尚未获准。可以讨论保留核心说明、延后部分示例、分批交付和增加协助，但主持问题不代表同意任何提案。你并无替同事承诺加班或替客户接受取舍的权限。短练提出需求、原因和必须保留的质量底线。',
    '同一虚构培训包，今天项目负责人把协商资料交给另一位审批人。原周五计划未改；你需要把请求、取舍和待决定事项说清，交接版加入书面确认及分歧处理。两种初始请求都未被接受，不能在后续将任一提议当作新合同或已约定日期。所有时间均是练习设定，不是现实雇佣或法律建议。',
  ],
  paths: [
    {
      short: ['need', 'reason', 'quality'],
      standard: ['need', 'reason', 'quality', 'core', 'tradeoff', 'checkpoint'],
      extended: [
        'need',
        'reason',
        'quality',
        'core',
        'tradeoff',
        'checkpoint',
        'help',
        'fallback',
        'impact',
        'next',
      ],
    },
    {
      short: ['need', 'reason', 'quality'],
      standard: ['need', 'reason', 'quality', 'core', 'tradeoff', 'checkpoint'],
      extended: [
        'need',
        'reason',
        'quality',
        'core',
        'tradeoff',
        'checkpoint',
        'help',
        'fallback',
        'confirm',
        'dispute',
      ],
    },
  ],
  closing:
    'Your deadline proposal has been rehearsed. The original plan has not been changed here; any new scope, support or date still needs explicit agreement.',
  partial:
    'The negotiation rehearsal is partly complete. No agreement has been inferred from unanswered points.',
  repairs: {
    clarify: 'I can restate this question about your proposal.',
    struggle: 'Try saying what you need and one reason.',
    offTopic: 'Let us return to the training-package proposal.',
    unknown:
      'That proposal is not covered by this pair, so I have not recorded an agreed change.',
    changed:
      'Your earlier proposal detail has been replaced, not accepted on the other party’s behalf.',
    refusedClosing:
      'We will stop this negotiation rehearsal without recording a new agreement.',
  },
}
export const deadlinePacks = {
  A1: workPack(
    scene,
    'A1',
    {
      canDoZh: '能提出更多时间或较少任务，并说简单原因与底线。',
      complexityZh: '每问只处理一项提议，后续明确没有获准新日期。',
      scaffoldingZh: '周五培训包与说明、示例提供可见具体选项。',
      registerZh: 'please和can构成基本协商，不要求复杂谈判表达。',
    },
    [
      [
        'need',
        'request-change',
        'What change do you need for the training package?',
        '请求不等于同意。',
        'extension-request',
        'Can I have more time, please?',
        'scope-request',
        'Can we make the package smaller, please?',
        a1,
      ],
      [
        'reason',
        'explain-constraint',
        'Why is Friday difficult for you?',
        '具体原因。',
        'checks',
        'The checks need more time.',
        'new-pages',
        'There are extra pages to write.',
        a1,
      ],
      [
        'quality',
        'protect-quality',
        'What must we check before people use the package?',
        '质量底线。',
        'instructions',
        'We must check the instructions.',
        'examples',
        'We must check the examples.',
        a1,
      ],
      [
        'core',
        'identify-core',
        'Which part is most important for the first training session?',
        '优先内容。',
        'steps',
        'The main instruction steps.',
        'sample',
        'One clear practice example.',
        a1,
      ],
      [
        'tradeoff',
        'offer-tradeoff',
        'What could wait until a later version?',
        '可以建议延后。',
        'extra-examples',
        'The extra examples could wait.',
        'pictures',
        'Some pictures could wait.',
        a1,
      ],
      [
        'checkpoint',
        'propose-checkpoint',
        'When could you show a work sample?',
        '展示样稿不是完成承诺。',
        'thursday',
        'I could show a sample on Thursday.',
        'friday',
        'I could show a sample on Friday.',
        a1,
      ],
      [
        'help',
        'request-resource',
        'Do you want help checking page numbers?',
        '允许不请求帮助。',
        'ask',
        'Yes, could someone help me?',
        'no',
        'No, I can check the numbers.',
        a1,
      ],
      [
        'fallback',
        'offer-fallback',
        'What can you do if your first idea is not accepted?',
        '没有隐含同意。',
        'ask-priority',
        'I can ask which part comes first.',
        'show-work',
        'I can show the work so far.',
        a1,
      ],
      [
        'impact',
        'explain-impact',
        'Who needs to know about a possible change?',
        '只是可能变化。',
        'trainer',
        'The trainer needs to know.',
        'customer',
        'The customer contact needs to know.',
        a1,
      ],
      [
        'next',
        'name-next-step',
        'What will you do after this discussion?',
        '可自主下一步。',
        'summary',
        'I will write a short summary.',
        'list',
        'I will list the open questions.',
        a1,
      ],
      [
        'confirm',
        'seek-confirmation',
        'How would you like the manager to send the final decision?',
        '选择将来确认渠道，当前仍未同意。',
        'email-request',
        'Please send the decision by email.',
        'board-request',
        'Please put the decision on the project board.',
        a1,
      ],
      [
        'dispute',
        'handle-disagreement',
        'What can you ask if the reply is not clear?',
        '未引入已收到回复，使用假设。',
        'date',
        'I can ask which date they mean.',
        'scope',
        'I can ask which pages they need.',
        a1,
      ],
    ],
    a1,
  ),
  A2: workPack(
    scene,
    'A2',
    {
      canDoZh: '能说明时间压力，提出简单范围取舍与检查点。',
      complexityZh: '连接请求与理由，识别哪些需要双方进一步同意。',
      scaffoldingZh: '固定交付包和原日期支撑两三步交换。',
      registerZh: '礼貌、直接、可拒绝，不替别人作安排。',
    },
    [
      [
        'need',
        'request-change',
        'Would you like to ask for more time or fewer pages?',
        '两种都只是申请。',
        'extension-request',
        'Could we move the deadline to give me more time?',
        'scope-request',
        'Could we keep Friday but include fewer pages?',
        a2,
      ],
      [
        'reason',
        'explain-constraint',
        'What is making the current plan hard to complete?',
        '具体受限原因。',
        'checks',
        'The content checks are taking longer than I expected.',
        'new-pages',
        'Some extra pages were added after I made the plan.',
        a2,
      ],
      [
        'quality',
        'protect-quality',
        'Which check should we keep even if time is short?',
        '不能默许无检查交付。',
        'instructions',
        'We should still check that the instructions are clear.',
        'examples',
        'We should still check that the practice examples work.',
        a2,
      ],
      [
        'core',
        'identify-core',
        'What would you put first in a smaller training package?',
        '设想缩减版，不假设已采纳。',
        'steps',
        'I would put the main instructions first.',
        'sample',
        'I would include one complete example first.',
        a2,
      ],
      [
        'tradeoff',
        'offer-tradeoff',
        'What could you suggest leaving for the second version?',
        '建议推后非核心项。',
        'examples',
        'We could leave the extra examples for later.',
        'design',
        'We could leave some decorative pictures for later.',
        a2,
      ],
      [
        'checkpoint',
        'propose-checkpoint',
        'Could you offer a time to show progress before the final version?',
        '进展展示与完成不同。',
        'thursday',
        'I could show a few pages on Thursday afternoon.',
        'friday',
        'I could show a sample on Friday morning.',
        a2,
      ],
      [
        'help',
        'request-resource',
        'Would another person checking the page numbers be useful?',
        '求助尚未安排。',
        'ask',
        'Yes, could someone do that while I check the content?',
        'no',
        'No, thanks. I can check them after the content.',
        a2,
      ],
      [
        'fallback',
        'offer-fallback',
        'If the first request is refused, what could you discuss next?',
        '未假设拒绝已经发生。',
        'priority',
        'We could discuss which parts are most important.',
        'stages',
        'We could discuss sending the work in two parts.',
        a2,
      ],
      [
        'impact',
        'explain-impact',
        'How could a change affect the trainer?',
        '影响不同而非仅日期。',
        'prepare',
        'The trainer might have less time to prepare.',
        'examples',
        'The trainer might need a different practice activity.',
        a2,
      ],
      [
        'next',
        'name-next-step',
        'How will you help the manager consider your proposal?',
        '主动准备而非宣告同意。',
        'options',
        'I will write down the options and what each one changes.',
        'sample',
        'I will share a sample so the manager can see the work left.',
        a2,
      ],
      [
        'confirm',
        'seek-confirmation',
        'How would you ask for a record once the manager has made a decision?',
        '未来决定的记录方式，不假设已发生。',
        'email-request',
        'Could you confirm the decision in an email?',
        'note-request',
        'Could we write the decision in the meeting notes?',
        a2,
      ],
      [
        'dispute',
        'handle-disagreement',
        'If the manager says Friday without saying which version, what would you ask?',
        '具体虚构条件，不当已发生。',
        'pages',
        'Do you mean all the pages or the smaller version?',
        'checks',
        'Which checks do you expect us to finish by Friday?',
        a2,
      ],
    ],
    a2,
  ),
  B1: workPack(
    scene,
    'B1',
    {
      canDoZh: '能解释原计划为何困难，提出取舍和替代而不自动确认结果。',
      complexityZh: '因果说明与后续安排并行，保持对质量和接收者影响的关注。',
      scaffoldingZh: '熟悉培训包减少专业知识门槛，需组织请求理由。',
      registerZh: '合作解决问题，避免推责或无条件承诺。',
    },
    [
      [
        'need',
        'request-change',
        'What adjustment would you like the project lead to consider?',
        '表达请求。',
        'extension-request',
        'I would like to request an extension so the full package can be checked properly.',
        'scope-request',
        'I would like to reduce the first version so Friday remains a realistic target.',
        b1,
      ],
      [
        'reason',
        'explain-constraint',
        'What evidence explains why the original plan is no longer straightforward?',
        '具体约束而非泛泛忙碌。',
        'checks',
        'The first checks took longer than planned because several instructions needed clarification.',
        'new-pages',
        'The added pages increase the writing and checking work beyond the original estimate.',
        b1,
      ],
      [
        'quality',
        'protect-quality',
        'Which part of quality would you be unwilling to trade for speed?',
        '不能牺牲的检查。',
        'instructions',
        'I would keep the check that a new user can follow the main instructions.',
        'examples',
        'I would keep testing the examples, because a broken exercise would interrupt the session.',
        b1,
      ],
      [
        'core',
        'identify-core',
        'If we considered a smaller first version, what would it need to contain?',
        '条件式范围协商。',
        'steps',
        'It would need the main steps, so people can complete the basic task.',
        'example',
        'It would need one complete worked example, so the trainer has something reliable to demonstrate.',
        b1,
      ],
      [
        'tradeoff',
        'offer-tradeoff',
        'What could be delayed with the least effect on the first session?',
        '支持范围建议。',
        'examples',
        'The extra practice examples could follow later if the trainer has enough for the first activity.',
        'decoration',
        'Decorative images could wait because they do not explain any essential step.',
        b1,
      ],
      [
        'checkpoint',
        'propose-checkpoint',
        'What progress checkpoint could help the manager judge the remaining work?',
        '样稿不是交付验收。',
        'thursday',
        'I could show a checked sample on Thursday and explain what remains different in the other pages.',
        'friday',
        'I could bring a sample on Friday morning with a list of unresolved content questions.',
        b1,
      ],
      [
        'help',
        'request-resource',
        'Is there a task you could ask someone else to take without handing over the whole package?',
        '有界资源请求。',
        'ask',
        'Could someone check the numbering and links while I handle the content questions?',
        'no',
        'I would keep this pass myself, because splitting it now could create conflicting versions.',
        b1,
      ],
      [
        'fallback',
        'offer-fallback',
        'How would you respond if the manager could not accept your preferred change?',
        '替代不代表已被拒绝。',
        'priority',
        'I would ask which outcome matters most and use that to suggest another option.',
        'staged',
        'I would ask whether a staged delivery could meet the trainer’s immediate needs.',
        b1,
      ],
      [
        'impact',
        'explain-impact',
        'What effect on other people would you raise during the negotiation?',
        '显露取舍成本。',
        'trainer',
        'A later package could reduce the trainer’s preparation time, so we should discuss that with them.',
        'customer',
        'A smaller version could change what the customer expects, so their contact needs to understand the difference.',
        b1,
      ],
      [
        'next',
        'name-next-step',
        'What will you record while the proposal is still awaiting a decision?',
        '保留请求状态。',
        'options',
        'I will record the options, their consequences and the decision we still need.',
        'questions',
        'I will list the unanswered questions, rather than put a new date into the plan as if it were agreed.',
        b1,
      ],
      [
        'confirm',
        'seek-confirmation',
        'What would you need before changing the official plan?',
        '书面确认或负责人明确宣告，均尚未发生。',
        'written',
        'I would need written confirmation of both the date and the content to be delivered.',
        'decision',
        'I would need the project lead to state which option has been accepted in the decision meeting.',
        b1,
      ],
      [
        'dispute',
        'handle-disagreement',
        'If the reply says do your best for Friday, what remains unclear?',
        '具体含糊回复的澄清。',
        'scope',
        'It is unclear whether Friday still means the whole package or a smaller version.',
        'priority',
        'It is unclear which work to protect if there is not enough time for everything.',
        b1,
      ],
    ],
    b1,
  ),
  B2: workPack(
    scene,
    'B2',
    {
      canDoZh: '能把期限谈判组织为有证据的选项，协商范围、质量和资源。',
      complexityZh: '明确受益和代价，面对含糊承诺时寻求可执行确认。',
      scaffoldingZh: '已知交付物与原日期，需支持建议并评估他人影响。',
      registerZh: '坚定而合作，拒绝把额外工作静默转嫁给同事。',
    },
    [
      [
        'need',
        'request-change',
        'Which change would best address the pressure on the current delivery plan?',
        '建议而非单方面改计划。',
        'extension-request',
        'I would propose moving the deadline so we can retain the full scope without compressing the essential checks.',
        'scope-request',
        'I would propose narrowing the initial scope, keeping Friday as the target while moving nonessential material to a later version.',
        b2,
      ],
      [
        'reason',
        'explain-constraint',
        'How would you justify reopening the plan rather than simply promising to work faster?',
        '证据支撑协商。',
        'checks',
        'The first review exposed unclear steps that need rewriting, so the remaining work is not just a matter of typing faster.',
        'new-pages',
        'The scope has grown since the estimate; we should account for that explicitly rather than absorb it in an unchanged deadline.',
        b2,
      ],
      [
        'quality',
        'protect-quality',
        'What minimum check would you defend if the manager asked for a shortcut?',
        '说明底线价值。',
        'instructions',
        'I would retain a first-time-user check of the core instructions, since internal familiarity can hide missing steps.',
        'examples',
        'I would retain a complete run-through of each included exercise; an untested example could undermine the training itself.',
        b2,
      ],
      [
        'core',
        'identify-core',
        'What would make a reduced package genuinely useful rather than merely shorter?',
        '缩减仍有完整价值。',
        'journey',
        'It should support one complete basic task, even if it covers fewer variations.',
        'example',
        'It should give the trainer one reliable demonstration with enough explanation for participants to follow.',
        b2,
      ],
      [
        'tradeoff',
        'offer-tradeoff',
        'How would you present the cost of delaying the optional material?',
        '取舍透明。',
        'examples',
        'Participants would have fewer practice variations initially, so we should check whether that fits the trainer’s session plan.',
        'visuals',
        'The package would be less polished visually, but delaying decorative work would protect time for content checks.',
        b2,
      ],
      [
        'checkpoint',
        'propose-checkpoint',
        'What checkpoint would reduce uncertainty without creating a second full deadline?',
        '有界检查点。',
        'sample',
        'I would propose a small checked sample on Thursday, with a clear list of what it does and does not represent.',
        'review',
        'I would propose reviewing the unresolved questions on Friday morning, so the manager can judge whether the current options remain viable.',
        b2,
      ],
      [
        'help',
        'request-resource',
        'Would additional help actually relieve the constraint?',
        '资源有成本，不替别人接受。',
        'ask',
        'A bounded check of links and numbering could run in parallel; could the lead ask whether someone has capacity for that?',
        'no',
        'Not immediately: the content decisions are too interconnected, and explaining them could take longer than resolving this pass myself.',
        b2,
      ],
      [
        'fallback',
        'offer-fallback',
        'If neither extra time nor reduced scope is acceptable, how would you keep the discussion constructive?',
        '第三种讨论策略，不承诺不可能完成。',
        'priority',
        'I would ask the lead to rank the constraints and identify which outcome must take precedence.',
        'stages',
        'I would explore a staged handover with the trainer, while making clear that it would need their agreement.',
        b2,
      ],
      [
        'impact',
        'explain-impact',
        'Whose downstream work should be part of the trade-off discussion?',
        '外部成本。',
        'trainer',
        'The trainer’s preparation matters; a later package may move the pressure onto them rather than remove it.',
        'contact',
        'The customer contact needs to assess whether a smaller first version still meets the purpose of the session.',
        b2,
      ],
      [
        'next',
        'name-next-step',
        'How would you summarise the discussion before any option has been accepted?',
        '忠实区分提案和决定。',
        'table',
        'I would set out the options with their costs and mark the decision as pending.',
        'note',
        'I would record the unresolved date and scope questions, then ask who will make the decision and when.',
        b2,
      ],
      [
        'confirm',
        'seek-confirmation',
        'What would count as sufficient confirmation to revise the delivery plan?',
        '明确授权内容。',
        'scope-date',
        'An explicit decision covering the date, included material and required checks would let us update the plan.',
        'authority',
        'Confirmation from the responsible lead, with the trainer’s dependencies addressed, would be enough to record the chosen option.',
        b2,
      ],
      [
        'dispute',
        'handle-disagreement',
        'How would you respond to “Keep Friday, but do not compromise anything”?',
        '实际冲突，需要选择。',
        'constraint',
        'I would explain that the current work estimate does not support both demands and ask which constraint can change.',
        'options',
        'I would return to the concrete options and their consequences, rather than agree to a promise I cannot support.',
        b2,
      ],
    ],
    b2,
  ),
  C1: workPack(
    scene,
    'C1',
    {
      canDoZh: '能识别谈判中的隐含取舍，限定承诺并推动有授权的明确决定。',
      complexityZh: '处理零取舍要求、资源协调成本与下游约束，避免防御性推责。',
      scaffoldingZh: '具体原计划为支架，需自主组织有分寸的异议与方案。',
      registerZh: '自然的高级协商语气，限定直接源于真实工作条件。',
    },
    [
      [
        'need',
        'request-change',
        'What would you ask the lead to reconsider before the current plan becomes an unsupported promise?',
        '清楚请求改变什么。',
        'extension-request',
        'I would ask for a later deadline to preserve the full training package and its checks, rather than leave an unrealistic date in place.',
        'scope-request',
        'I would ask us to redefine the first release around the session’s essential needs, keeping Friday as the target but reducing what it is expected to contain.',
        c1,
      ],
      [
        'reason',
        'explain-constraint',
        'How would you make the case for a change without sounding as though you are merely defending your estimate?',
        '从实际证据解释约束。',
        'checks',
        'I would show the unclear steps the review uncovered and the work needed to resolve them, so the discussion is about the task rather than whether I estimated well.',
        'new-pages',
        'I would distinguish the original work from the additions and invite the lead to choose where the extra effort should come from.',
        c1,
      ],
      [
        'quality',
        'protect-quality',
        'Which shortcut would save time on paper while putting the purpose of the training at risk?',
        '具体底线。',
        'instructions',
        'Skipping a first-time-user check could leave a critical step unstated; that would save review time only by moving the confusion into the session.',
        'examples',
        'Using examples that have not been run through could leave the trainer demonstrating a failure, so I would protect that check even in a smaller version.',
        c1,
      ],
      [
        'core',
        'identify-core',
        'How would you define a credible minimum version rather than an arbitrary cut in page count?',
        '以用途定义最小范围。',
        'task',
        'I would define it around one complete participant task, retaining everything needed to finish that task without relying on missing later pages.',
        'trainer',
        'I would work backwards from what the trainer must demonstrate, preserving one coherent explanation and example rather than fragments of every topic.',
        c1,
      ],
      [
        'tradeoff',
        'offer-tradeoff',
        'What cost of deferring optional material should not be hidden by calling it a quick win?',
        '揭示取舍成本。',
        'practice',
        'Fewer exercises mean less room to adapt to different participants, so the trainer should judge whether that loss is acceptable.',
        'polish',
        'Deferring visual polish may be sensible, but the contact needs to know the first version will look less finished than originally expected.',
        c1,
      ],
      [
        'checkpoint',
        'propose-checkpoint',
        'How could you offer visibility without creating a checkpoint that consumes the time it is meant to protect?',
        '避免检查点过重。',
        'sample',
        'I would offer one checked sample on Thursday with a short account of the remaining differences, not a polished preview of the entire package.',
        'questions',
        'I would propose a brief decision-focused review on Friday morning, using the open-question list rather than preparing another presentation.',
        c1,
      ],
      [
        'help',
        'request-resource',
        'How would you respond to the suggestion that adding a colleague will automatically recover the lost time?',
        '不替同事承诺资源。',
        'ask',
        'A colleague could help with the separable link and numbering checks, but the lead would need to confirm their capacity; I would ask for that specific contribution.',
        'no',
        'The remaining content choices share too much context for an immediate handoff; adding someone now could slow the first pass, so I would not request it yet.',
        c1,
      ],
      [
        'fallback',
        'offer-fallback',
        'What would you do if the lead rejected your preferred option but still expected a workable route forward?',
        '将分歧变成授权选择。',
        'priority',
        'I would ask which consequence they are prepared to accept, since preserving every constraint would leave us without a credible plan.',
        'staged',
        'I would explore whether the trainer could use a staged handover, while treating their preparation needs as a constraint to confirm rather than an inconvenience to assume away.',
        c1,
      ],
      [
        'impact',
        'explain-impact',
        'Where might an apparently successful deadline negotiation simply displace the problem?',
        '下游影响。',
        'trainer',
        'A later delivery could leave the trainer absorbing the lost preparation time, so their capacity needs to be part of the decision.',
        'customer',
        'A reduced version could leave the customer expecting material that is no longer included, unless the scope change is explained and accepted.',
        c1,
      ],
      [
        'next',
        'name-next-step',
        'What would you put in the follow-up note while the lead is still considering the options?',
        '记录待决定而非假装同意。',
        'pending',
        'I would separate the proposed changes from the unchanged baseline and identify the decision still required.',
        'consequences',
        'I would summarise the consequences of each option and ask for a decision by the point at which those options start to close.',
        c1,
      ],
      [
        'confirm',
        'seek-confirmation',
        'What ambiguity would you remove before treating a positive response as permission to proceed?',
        '正面语气不一定批准。',
        'scope',
        'I would confirm exactly which material the response covers; agreement to a date does not by itself settle the scope.',
        'authority',
        'I would establish whether the person responding is authorising the change or merely expressing support for taking it to the lead.',
        c1,
      ],
      [
        'dispute',
        'handle-disagreement',
        'If the lead says they understand the pressure but the original expectations stand, how would you reply?',
        '尊重立场但不接受无依据承诺。',
        'decision',
        'I appreciate that the expectations matter; the remaining work still exceeds the plan, so we need an explicit choice about time, scope or support.',
        'risk',
        'I would acknowledge the position and set out what is realistically achievable, making the residual risk visible rather than quietly promising the gap away.',
        c1,
      ],
    ],
    c1,
  ),
}
