import { workPack, type WorkScene, type Review } from './authoring'
const a1: Review = {
  state: 'model-reviewed',
  record:
    'work-review.md#job-interview: A1 all 12 Q/24 A, rationale, both variants and paths read and corrected by Codex implementation agent, 2026-09-10; model-assisted, not teacher certification',
}
const a2: Review = {
  state: 'model-reviewed',
  record:
    'work-review.md#job-interview: A2 all 12 Q/24 A, rationale, both variants and paths read and corrected by Codex implementation agent, 2026-09-10; model-assisted, not teacher certification',
}
const b1: Review = {
  state: 'model-reviewed',
  record:
    'work-review.md#job-interview: B1 all 12 Q/24 A, rationale, both variants and paths read and corrected by Codex implementation agent, 2026-09-10; model-assisted, not teacher certification',
}
const b2: Review = {
  state: 'model-reviewed',
  record:
    'work-review.md#job-interview: B2 all 12 Q/24 A, rationale, both variants and paths read and corrected by Codex implementation agent, 2026-09-10; model-assisted, not teacher certification',
}
const c1: Review = {
  state: 'model-reviewed',
  record:
    'work-review.md#job-interview: C1 all 12 Q/24 A, rationale, both variants and paths read and corrected by Codex implementation agent, 2026-09-10; model-assisted, not teacher certification',
}
const scene: WorkScene = {
  sceneId: 'work-06',
  slug: 'job-interview',
  situations: [
    '虚构招聘练习，面试的是社区展览的项目助理，工作包括访客安排、资料整理和团队协作。答案中的学生项目、志愿活动、技能与成绩都是练习角色素材，不是用户实际经历；真实求职须换成真实且可核对的内容，不应捏造资历、角色或结果。面试官未提供录用承诺。短练谈兴趣、相关经历与本人贡献；拓展涉及困难、学习和反馈。',
    '同一虚构项目助理的后续面谈，由另一位面试官接手。不假设前一场面试已经认可候选人或验证经历；本轮仍重新介绍兴趣与实例。交接版着重可核实证据与向面试方提问，不要求真实个人联系方式、薪资、证件或敏感资料。所有样例经历仅作语言练习，不能拿来虚构实际资格。',
  ],
  paths: [
    {
      short: ['interest', 'experience', 'contribution'],
      standard: [
        'interest',
        'experience',
        'contribution',
        'strength',
        'difficulty',
        'learning',
      ],
      extended: [
        'interest',
        'experience',
        'contribution',
        'strength',
        'difficulty',
        'learning',
        'feedback',
        'priority',
        'gap',
        'question',
      ],
    },
    {
      short: ['interest', 'experience', 'contribution'],
      standard: [
        'interest',
        'experience',
        'contribution',
        'strength',
        'difficulty',
        'learning',
      ],
      extended: [
        'interest',
        'experience',
        'contribution',
        'strength',
        'difficulty',
        'learning',
        'feedback',
        'priority',
        'evidence',
        'clarify',
      ],
    },
  ],
  closing:
    'Your fictional interview practice is complete. No credentials have been verified and no hiring decision has been made; use only your real experience in an actual application.',
  partial:
    'This fictional interview is partly rehearsed. Unanswered areas have not been filled with invented qualifications.',
  repairs: {
    clarify: 'I can restate this interview question.',
    struggle:
      'Try one truthful detail from your own experience when you adapt the fictional example.',
    offTopic: 'Let us return to the project-assistant interview.',
    unknown:
      'That answer is not covered here; I have not evaluated your suitability or verified any qualification.',
    changed: 'Your earlier fictional interview answer has been replaced.',
    refusedClosing:
      'We will stop the interview rehearsal here without a hiring judgment.',
  },
}
export const interviewPacks = {
  A1: workPack(
    scene,
    'A1',
    {
      canDoZh: '能在虚构角色卡支持下说兴趣、经历与本人做过的简单任务。',
      complexityZh: '每次一句具体信息，明确个人贡献不是整个团队成果。',
      scaffoldingZh: '固定项目助理岗位与样例经历降低表达负担。',
      registerZh: '礼貌直白，可承认不会，真实面试须使用真实经历。',
    },
    [
      [
        'interest',
        'explain-interest',
        'Why do you want this project-assistant job?',
        '选择岗位相关兴趣。',
        'people',
        'I like helping visitors.',
        'organise',
        'I like organising information.',
        a1,
      ],
      [
        'experience',
        'describe-experience',
        'What kind of project have you helped with?',
        '只用虚构角色练习。',
        'school',
        'I helped with a school exhibition.',
        'volunteer',
        'I helped with a local volunteer event.',
        a1,
      ],
      [
        'contribution',
        'separate-contribution',
        'What was your own job on that project?',
        '两类项目都可做的个人任务。',
        'list',
        'I made the visitor list.',
        'signs',
        'I put up the signs.',
        a1,
      ],
      [
        'strength',
        'name-strength',
        'What do you do well?',
        '具体工作能力。',
        'careful',
        'I check details carefully.',
        'friendly',
        'I talk to new people easily.',
        a1,
      ],
      [
        'difficulty',
        'describe-difficulty',
        'What was difficult on the project?',
        '两类项目共有可能困难。',
        'change',
        'The room changed at the last minute.',
        'busy',
        'Many visitors arrived at once.',
        a1,
      ],
      [
        'learning',
        'reflect-learning',
        'What did the project teach you?',
        '独立反思，无前文冲突。',
        'check',
        'It taught me to check the plan.',
        'ask',
        'It taught me to ask for help early.',
        a1,
      ],
      [
        'feedback',
        'respond-feedback',
        'What do you do when someone gives you a useful tip?',
        '回应建议策略。',
        'try',
        'I try it on the next task.',
        'write',
        'I write it down.',
        a1,
      ],
      [
        'priority',
        'set-priority',
        'Two visitors need help. What do you do first?',
        '简单处理方法。',
        'ask',
        'I ask what they need.',
        'urgent',
        'I check who needs urgent help.',
        a1,
      ],
      [
        'gap',
        'acknowledge-gap',
        'What computer task do you need help with?',
        '承认具体学习缺口。',
        'spreadsheets',
        'I need help with spreadsheets.',
        'calendar',
        'I need help with the work calendar.',
        a1,
      ],
      [
        'question',
        'ask-employer',
        'What would you like to ask about this job?',
        '真实岗位问题。',
        'day',
        'What is a normal workday like?',
        'team',
        'How many people are on the team?',
        a1,
      ],
      [
        'evidence',
        'offer-evidence',
        'What could you show to explain your project work?',
        '样例证据而非已验证。',
        'sample',
        'I could show a sample of my work.',
        'notes',
        'I could show my project notes.',
        a1,
      ],
      [
        'clarify',
        'clarify-role',
        'Which job detail would you like me to explain?',
        '向面试官核实。',
        'hours',
        'Please explain the working hours.',
        'training',
        'Please explain the training.',
        a1,
      ],
    ],
    a1,
  ),
  A2: workPack(
    scene,
    'A2',
    {
      canDoZh: '能描述相关经历、具体贡献并回答简单行为问题。',
      complexityZh: '增加简短例子与学习结果，不把角色卡当真实履历。',
      scaffoldingZh: '展览与活动均支持同一后续个人任务，可用简单过去时。',
      registerZh: '友好职业语气，允许承认缺乏工具经验。',
    },
    [
      [
        'interest',
        'explain-interest',
        'What interests you about helping with community exhibitions?',
        '岗位兴趣。',
        'visitors',
        'I enjoy helping people find what they need at an event.',
        'planning',
        'I enjoy making clear plans and keeping information organised.',
        a2,
      ],
      [
        'experience',
        'describe-experience',
        'Can you tell me about an event you helped organise?',
        '角色卡事例。',
        'school',
        'I helped our class prepare a small exhibition at school.',
        'volunteer',
        'I volunteered at a local event with a small organising team.',
        a2,
      ],
      [
        'contribution',
        'separate-contribution',
        'Which task did you do yourself for that event?',
        '个人具体任务。',
        'list',
        'I prepared the visitor list and checked the names.',
        'signs',
        'I made the direction signs and put them near the entrance.',
        a2,
      ],
      [
        'strength',
        'name-strength',
        'Which skill would be useful in this assistant role?',
        '能力与岗位相连。',
        'details',
        'I am good at checking small details, such as names and times.',
        'welcome',
        'I am good at welcoming people who do not know the place.',
        a2,
      ],
      [
        'difficulty',
        'describe-difficulty',
        'Can you describe one problem your event team faced?',
        '团队问题不声称全由自己解决。',
        'room',
        'The room changed late, so the team had to update the directions.',
        'crowd',
        'A large group arrived together, so the entrance became very busy.',
        a2,
      ],
      [
        'learning',
        'reflect-learning',
        'What would you do better at your next event?',
        '反思兼容两种困难。',
        'check',
        'I would check the final plan with the team before visitors arrive.',
        'backup',
        'I would ask who can help if things become busy.',
        a2,
      ],
      [
        'feedback',
        'respond-feedback',
        'How do you make use of feedback on a task?',
        '可采取不同方法。',
        'try',
        'I try the suggestion and check whether the task becomes easier.',
        'clarify',
        'I ask for an example if I do not understand the suggestion.',
        a2,
      ],
      [
        'priority',
        'set-priority',
        'How would you choose what to do when two visitors ask for help at the same time?',
        '实际判断步骤。',
        'needs',
        'I would ask both what they need and deal with the quick question first.',
        'urgent',
        'I would check for an urgent problem and ask a colleague to help if needed.',
        a2,
      ],
      [
        'gap',
        'acknowledge-gap',
        'What would you do if this job used a computer tool you had never seen?',
        '学习方法不造资历。',
        'training',
        'I would ask for training and practise with sample information.',
        'guide',
        'I would read the guide and ask someone to check my first try.',
        a2,
      ],
      [
        'question',
        'ask-employer',
        'What would help you understand whether the role suits you?',
        '向面试方提问。',
        'day',
        'Could you describe a typical day during an exhibition?',
        'support',
        'What support is available for someone new to the team?',
        a2,
      ],
      [
        'evidence',
        'offer-evidence',
        'How could you help the interviewer understand the work you actually did?',
        '区分自己证据。',
        'sample',
        'I could explain a sample that I made myself.',
        'notes',
        'I could show my task notes and say which parts were mine.',
        a2,
      ],
      [
        'clarify',
        'clarify-role',
        'Which part of the job description would you like more detail about?',
        '具体岗位澄清。',
        'weekend',
        'I would like to know how often the work includes weekends.',
        'training',
        'I would like to know how new assistants learn the event system.',
        a2,
      ],
    ],
    a2,
  ),
  B1: workPack(
    scene,
    'B1',
    {
      canDoZh: '能以经历说明技能，区分团队与本人行动并反思学习。',
      complexityZh: '说明问题原因、回应反馈、安排优先级，诚实面对技能缺口。',
      scaffoldingZh: '两个原创事件均支持后续贡献和困难，需简短因果组织。',
      registerZh: '可信面试表达，不要求完美经历或虚构成果。',
    },
    [
      [
        'interest',
        'explain-interest',
        'Why does this assistant role appeal to you rather than just any event job?',
        '岗位相关动机。',
        'visitors',
        'I like the mix of practical organisation and helping visitors feel comfortable in an unfamiliar place.',
        'information',
        'I am interested in work where clear information makes a visible difference to how an event runs.',
        b1,
      ],
      [
        'experience',
        'describe-experience',
        'Which previous experience gives you a useful example for this role?',
        '虚构经历。',
        'school',
        'A student exhibition gave me experience of preparing information for people who had not seen the project before.',
        'volunteer',
        'A volunteer event taught me how a small team coordinates tasks while visitors are arriving.',
        b1,
      ],
      [
        'contribution',
        'separate-contribution',
        'What exactly did you contribute, as distinct from what the whole team achieved?',
        '明确个人贡献。',
        'list',
        'I prepared and checked the visitor list; the team handled the wider event plan.',
        'signs',
        'I was responsible for the direction signs, while other people managed bookings and activities.',
        b1,
      ],
      [
        'strength',
        'name-strength',
        'What strength could you bring to a busy exhibition day?',
        '能力联系具体工作。',
        'accuracy',
        'I stay careful with details when things are busy, which helps prevent small information errors.',
        'communication',
        'I can explain practical information calmly to people who are unsure where to go.',
        b1,
      ],
      [
        'difficulty',
        'describe-difficulty',
        'What challenge from the event shows why teamwork mattered?',
        '团队协作不据为己有。',
        'change',
        'A late room change affected several tasks, so the team needed to share one updated plan.',
        'crowd',
        'An unexpected group made the entrance busy, and one person could not both answer questions and keep people moving.',
        b1,
      ],
      [
        'learning',
        'reflect-learning',
        'What lesson from that experience would you apply here?',
        '不依赖特定前答。',
        'shared',
        'I would check that everyone is using the same current information before the event starts.',
        'help',
        'I would agree a way to call for help early, rather than wait until a small problem grows.',
        b1,
      ],
      [
        'feedback',
        'respond-feedback',
        'How would you respond if a colleague said your explanation was too detailed?',
        '具体虚构反馈条件。',
        'shorten',
        'I would ask which information the visitor needs first and shorten the explanation around that.',
        'example',
        'I would ask for an example of a clearer explanation and try it on the next similar question.',
        b1,
      ],
      [
        'priority',
        'set-priority',
        'How would you manage two competing requests when you could not finish both immediately?',
        '优先与沟通。',
        'urgency',
        'I would check which has the more urgent consequence, then tell the other person when I can help.',
        'delegate',
        'I would identify any request a colleague could handle and ask for help rather than make both people wait silently.',
        b1,
      ],
      [
        'gap',
        'acknowledge-gap',
        'How would you answer a question about software you have not used?',
        '诚实，不把学习意愿说成熟练。',
        'related',
        'I would say I have not used it, explain any related experience and describe how I would learn it.',
        'practice',
        'I would be clear about the gap and ask whether there is a sample task I could use to understand the tool.',
        b1,
      ],
      [
        'question',
        'ask-employer',
        'What would you ask to understand the team’s expectations of a new assistant?',
        '有效反向提问。',
        'success',
        'What would successful progress look like in the first month?',
        'support',
        'Which decisions can an assistant make independently, and when should they ask for help?',
        b1,
      ],
      [
        'evidence',
        'offer-evidence',
        'What could you offer if the interviewer wanted to understand your contribution more clearly?',
        '可展示而非已证明资格。',
        'sample',
        'I could walk through a sample of my own work and explain the choices I made.',
        'record',
        'I could describe the task record and distinguish my responsibilities from the team’s shared results.',
        b1,
      ],
      [
        'clarify',
        'clarify-role',
        'What would you clarify before assuming the job fits the way you can work?',
        '岗位细节不替面试方回答。',
        'schedule',
        'I would ask how exhibition schedules affect evening or weekend work.',
        'training',
        'I would ask what training is available before an assistant works with visitors independently.',
        b1,
      ],
    ],
    b1,
  ),
  B2: workPack(
    scene,
    'B2',
    {
      canDoZh: '能以有限真实类型的经历支持适岗论点，反思取舍并澄清雇主期待。',
      complexityZh: '连接证据、个人贡献与团队效果，处理技能缺口不夸大。',
      scaffoldingZh: '固定虚构背景，不要求特定证书；需自述有依据的能力。',
      registerZh: '自信但可信，面试为双向了解而非背诵理想答案。',
    },
    [
      [
        'interest',
        'explain-interest',
        'What makes this particular combination of visitor support and organisation attractive to you?',
        '有针对性兴趣。',
        'service',
        'I enjoy solving practical problems in direct contact with people, and this role combines that with preparation that can prevent those problems.',
        'information',
        'I like turning scattered information into something people can use, especially when the effect is visible during a live event.',
        b2,
      ],
      [
        'experience',
        'describe-experience',
        'Which experience best demonstrates the kind of work you could bring to this team?',
        '具体但明确虚构的样例。',
        'exhibition',
        'A student exhibition gave me a useful example of preparing information for an audience with very different levels of background knowledge.',
        'volunteer',
        'A local volunteer event showed me how coordination and clear responsibilities affect the visitor experience under pressure.',
        b2,
      ],
      [
        'contribution',
        'separate-contribution',
        'How would you separate your personal input from the project’s overall success?',
        '贡献证据而非包揽成果。',
        'list',
        'My part was preparing and checking the visitor list; I would not attribute the smooth running of the whole event to that task alone.',
        'signs',
        'I owned the direction signs, including their placement, while the rest of the team handled the programme and visitor flow.',
        b2,
      ],
      [
        'strength',
        'name-strength',
        'Which strength is useful here, and where could it become a weakness if overused?',
        '能力与取舍。',
        'detail',
        'My attention to detail is useful for accurate information, but I need to avoid polishing a minor point when an urgent visitor issue needs attention.',
        'explain',
        'I explain things thoroughly, which helps new visitors, though I need to judge when a short answer would serve them better.',
        b2,
      ],
      [
        'difficulty',
        'describe-difficulty',
        'What challenge illustrates the need to adapt rather than simply follow the original plan?',
        '问题不因个人贡献选择而矛盾。',
        'room',
        'A late room change meant the team had to update several pieces of information consistently, not just move one sign.',
        'arrival',
        'An unexpected group arrived together, so the team had to adjust how it welcomed people instead of relying on the planned arrival pattern.',
        b2,
      ],
      [
        'learning',
        'reflect-learning',
        'What would you change next time based on that experience?',
        '具体改进。',
        'source',
        'I would establish one clear source for last-minute changes and check that everyone knows where to find it.',
        'backup',
        'I would agree backup responsibilities before the event, so asking for help does not require a new discussion during a busy moment.',
        b2,
      ],
      [
        'feedback',
        'respond-feedback',
        'Suppose a supervisor says visitors found your explanations hard to follow. How would you use that feedback?',
        '具体假设反馈，不预设历史。',
        'observe',
        'I would ask to see where visitors became confused, then test a shorter explanation on a similar task.',
        'compare',
        'I would compare my explanation with a clearer example and check whether the issue was order, vocabulary or unnecessary detail.',
        b2,
      ],
      [
        'priority',
        'set-priority',
        'How would you balance a quick request against a more important task that cannot be interrupted easily?',
        '权衡而非简单永远先急事。',
        'consequence',
        'I would judge the consequence of delay, acknowledge the request and give a realistic time rather than automatically interrupt the larger task.',
        'handoff',
        'If the quick request can be handled safely by someone else, I would seek a handoff while keeping responsibility clear.',
        b2,
      ],
      [
        'gap',
        'acknowledge-gap',
        'How would you discuss a required tool you have not used without overstating your readiness?',
        '诚实缺口和可迁移经验。',
        'transfer',
        'I would distinguish relevant experience from direct experience with that tool, then explain a practical learning plan.',
        'limits',
        'I would state what I could do immediately and what I would need supervised practice for, rather than describe myself as proficient.',
        b2,
      ],
      [
        'question',
        'ask-employer',
        'What question would help you judge how this team supports good work?',
        '深入岗位提问。',
        'priorities',
        'How does the team resolve conflicting priorities during a busy exhibition day?',
        'feedback',
        'How is feedback given to new assistants, particularly after a difficult visitor interaction?',
        b2,
      ],
      [
        'evidence',
        'offer-evidence',
        'How could you make your account of a contribution credible without relying on a dramatic success story?',
        '可信有限证据。',
        'sample',
        'I could explain a modest work sample in detail, including what I changed and why.',
        'limits',
        'I could be specific about my task and the limits of what I observed, instead of claiming a team result I cannot personally establish.',
        b2,
      ],
      [
        'clarify',
        'clarify-role',
        'Which ambiguity in the role would you want settled before accepting an offer, if one were made?',
        '没有虚构录用。',
        'authority',
        'I would clarify which visitor issues the assistant can resolve independently and which need a supervisor.',
        'schedule',
        'I would clarify how much notice is normally given for evening or weekend event work.',
        b2,
      ],
    ],
    b2,
  ),
  C1: workPack(
    scene,
    'C1',
    {
      canDoZh: '能精细说明可迁移能力、证据限制和发展需求，进行双向岗位评估。',
      complexityZh: '处理归因、取舍与隐含工作期待，不把叙述流畅当资历真实。',
      scaffoldingZh: '仍有明确虚构素材，但需独立组织连贯反思与有分寸的限定。',
      registerZh: '自然可信的高阶面试互动；不教编造证书或夸大团队成果。',
    },
    [
      [
        'interest',
        'explain-interest',
        'What draws you to this role beyond a general interest in working with people?',
        '具体工作吸引点。',
        'prevention',
        'I am drawn to the link between preparation and service: getting the information right beforehand can prevent a visitor’s small uncertainty becoming a difficult experience.',
        'translation',
        'I like work that turns an organiser’s internal plan into something a first-time visitor can actually use; that practical translation is what interests me here.',
        c1,
      ],
      [
        'experience',
        'describe-experience',
        'Which experience would you use to show how you think, rather than simply to list tasks you have done?',
        '选择思考方式的实例。',
        'exhibition',
        'I would use a student exhibition, where preparing information for people unfamiliar with the subject made me question what we were taking for granted.',
        'volunteer',
        'I would use a local volunteer event, where a small team had to make its division of responsibilities workable as well as clear on paper.',
        c1,
      ],
      [
        'contribution',
        'separate-contribution',
        'Which part of the event can you discuss from direct involvement rather than the team’s overall account?',
        '不假定学员前文声称活动成功。',
        'list',
        'I contributed to the preparation by checking the visitor list; I can explain that work directly, but I would not claim it accounts for the event’s overall success.',
        'signs',
        'I was responsible for the direction signs and their placement; the wider visitor experience depended on colleagues’ work that I would not present as my own.',
        c1,
      ],
      [
        'strength',
        'name-strength',
        'What strength would colleagues value, and what judgment do you need to apply when using it?',
        '优点伴随情境判断。',
        'precision',
        'They could rely on my care with information, provided I judge which details affect the visitor and which refinements can wait.',
        'explanation',
        'They could rely on me to explain an unfamiliar process, though I need to notice when someone wants one immediate answer rather than a full account.',
        c1,
      ],
      [
        'difficulty',
        'describe-difficulty',
        'Which difficulty from the event would you discuss without turning the account into a story about saving everyone else?',
        '团队问题而非英雄叙事。',
        'room',
        'I would discuss the late room change and how it exposed the need for a shared update process, recognising that several people had to adjust their work.',
        'crowd',
        'I would describe the unexpected group arrival as a coordination problem, focusing on how responsibilities needed to adapt rather than claiming I solved it single-handedly.',
        c1,
      ],
      [
        'learning',
        'reflect-learning',
        'What did the experience change about how you would prepare for another event?',
        '反思有具体改变。',
        'assumptions',
        'I would make the shared assumptions visible before opening, especially where different tasks rely on the same piece of information being current.',
        'backup',
        'I would establish how cover is requested and handed over, so willingness to help does not leave two people assuming the other has taken responsibility.',
        c1,
      ],
      [
        'feedback',
        'respond-feedback',
        'How would you respond to feedback that seemed fair in its outcome but did not match your intention?',
        '意图与效果区别。',
        'impact',
        'I would start with the effect on the visitor, ask for a concrete example and adjust the explanation before defending what I meant to convey.',
        'test',
        'I would acknowledge the gap and try an alternative in a comparable situation, so the discussion leads to a change we can examine.',
        c1,
      ],
      [
        'priority',
        'set-priority',
        'How would you handle competing requests when the person asking most insistently does not necessarily have the greatest need?',
        '隐含社会压力与优先级。',
        'criteria',
        'I would make the basis for prioritising clear, considering urgency and consequence rather than allowing insistence alone to determine the order.',
        'communicate',
        'I would acknowledge the persistent request and explain when it can be handled, while seeking support if the more consequential need requires my attention.',
        c1,
      ],
      [
        'gap',
        'acknowledge-gap',
        'How would you present a gap in direct experience when you believe your skills are transferable?',
        '不能以可迁移代替真实资历。',
        'distinguish',
        'I would specify which skills transfer and where I still need practice, giving a concrete learning approach rather than letting confidence stand in for experience.',
        'demonstrate',
        'I would offer to demonstrate a related task and discuss the difference, without implying that success there proves proficiency in a tool I have not used.',
        c1,
      ],
      [
        'question',
        'ask-employer',
        'What would you ask to uncover expectations that may not appear in the job description?',
        '隐含要求的双向澄清。',
        'judgment',
        'When assistants face a situation the procedure does not cover, how do you expect them to balance initiative with seeking approval?',
        'pressure',
        'What tends to put the team under the most pressure during exhibitions, and how is that pressure shared in practice?',
        c1,
      ],
      [
        'evidence',
        'offer-evidence',
        'What could you provide if the interviewer wanted to distinguish a well-told answer from a well-supported one?',
        '可核实证据而非背书。',
        'sample',
        'I could walk through an appropriate sample of my own work, including the choices and revisions behind it, rather than rely on the polish of the story.',
        'record',
        'I could point to a suitable task record and be clear about what it demonstrates, separating documented responsibility from my interpretation of the result.',
        c1,
      ],
      [
        'clarify',
        'clarify-role',
        'What would you want to understand before interpreting an invitation to take ownership as unlimited responsibility?',
        '岗位边界和授权。',
        'authority',
        'I would ask what decision-making authority accompanies that ownership and which situations still require a supervisor’s involvement.',
        'cover',
        'I would clarify how cover and competing priorities are handled, so ownership does not quietly become an expectation of constant availability.',
        c1,
      ],
    ],
    c1,
  ),
}
