import { workPack, type WorkScene, type Review } from './authoring'
const a1: Review = {
  state: 'model-reviewed',
  record:
    'work-review.md#meeting-disagreement: A1 all 12 Q/24 A, rationale, both variants and paths read and corrected by Codex implementation agent, 2026-09-10; model-assisted, not teacher certification',
}
const a2: Review = {
  state: 'model-reviewed',
  record:
    'work-review.md#meeting-disagreement: A2 all 12 Q/24 A, rationale, both variants and paths read and corrected by Codex implementation agent, 2026-09-10; model-assisted, not teacher certification',
}
const b1: Review = {
  state: 'model-reviewed',
  record:
    'work-review.md#meeting-disagreement: B1 all 12 Q/24 A, rationale, both variants and paths read and corrected by Codex implementation agent, 2026-09-10; model-assisted, not teacher certification',
}
const b2: Review = {
  state: 'model-reviewed',
  record:
    'work-review.md#meeting-disagreement: B2 all 12 Q/24 A, rationale, both variants and paths read and corrected by Codex implementation agent, 2026-09-10; model-assisted, not teacher certification',
}
const c1: Review = {
  state: 'model-reviewed',
  record:
    'work-review.md#meeting-disagreement: C1 all 12 Q/24 A, rationale, both variants and paths read and corrected by Codex implementation agent, 2026-09-10; model-assisted, not teacher certification',
}
const scene: WorkScene = {
  sceneId: 'work-05',
  slug: 'meeting-disagreement',
  situations: [
    '虚构团队会议讨论是否用共享看板替代每周的进度邮件。主持人在开场前明确说过：“One board will mean less work for everyone.”这是待检验的观点，不是事实；纸上有看板样图，但没有试用结果。你可支持或质疑方案，双方目标都是让信息容易找到。经理负责最终决定，尚未批准试点或全面更换。短练表达立场、共同目标和理由，拓展讨论假设、取舍及试点提议。',
    '虚构会议结论交接：经理需要一份公平呈现不同意见的记录。讨论仍是共享看板与每周邮件，主持人已说“One board will mean less work for everyone.”；没有真实试点数据或决定。交接版增加少数意见记录与重新讨论条件。提议试点与不提议试点两种回答都可成立；后续不能假定试点获批，不能把沉默或礼貌理解当作同意。',
  ],
  paths: [
    {
      short: ['position', 'goal', 'reason'],
      standard: [
        'position',
        'goal',
        'reason',
        'evidence',
        'assumption',
        'alternative',
      ],
      extended: [
        'position',
        'goal',
        'reason',
        'evidence',
        'assumption',
        'alternative',
        'trial',
        'measure',
        'tone',
        'decision',
      ],
    },
    {
      short: ['position', 'goal', 'reason'],
      standard: [
        'position',
        'goal',
        'reason',
        'evidence',
        'assumption',
        'alternative',
      ],
      extended: [
        'position',
        'goal',
        'reason',
        'evidence',
        'assumption',
        'alternative',
        'trial',
        'measure',
        'record',
        'revisit',
      ],
    },
  ],
  closing:
    'Your contribution to the disagreement has been rehearsed. Neither a pilot nor a permanent change has been approved in this exchange.',
  partial:
    'The discussion is partly rehearsed. Unanswered concerns and decisions remain open.',
  repairs: {
    clarify: 'I can restate this question about the proposal.',
    struggle: 'Start with your view and one practical reason.',
    offTopic: 'Let us return to how the team shares updates.',
    unknown:
      'That view is not a covered answer; I have not inferred agreement from it.',
    changed: 'Your earlier contribution is replaced in this rehearsal.',
    refusedClosing:
      'We will end this meeting rehearsal without assuming agreement.',
  },
}
export const disagreementPacks = {
  A1: workPack(
    scene,
    'A1',
    {
      canDoZh: '能礼貌表达赞成或不同意见并给出简单理由。',
      complexityZh: '共同目标、证据请求和方案选择分别处理。',
      scaffoldingZh: '看板和邮件为具体选项，已提供待讨论的一句话。',
      registerZh: '简短不攻击人，允许说不知道或不想试点。',
    },
    [
      [
        'position',
        'state-position',
        'Do you like the idea of one shared board?',
        '可以赞成或保留。',
        'support',
        'Yes, I like the idea.',
        'concern',
        'I am not sure about it.',
        a1,
      ],
      [
        'goal',
        'find-common-goal',
        'What should a good update system help us do?',
        '选共同目标。',
        'find',
        'Find information quickly.',
        'miss',
        'See important changes.',
        a1,
      ],
      [
        'reason',
        'give-reason',
        'What matters most to you about the change?',
        '任何立场都能有此关心。',
        'time',
        'The time it takes matters most.',
        'access',
        'Easy access matters most.',
        a1,
      ],
      [
        'evidence',
        'ask-evidence',
        'What would help you decide about the board?',
        '看实例或听意见均直接回应。',
        'example',
        'I would like to see a real example.',
        'feedback',
        'I would like to hear from the team.',
        a1,
      ],
      [
        'assumption',
        'question-assumption',
        'Is the board easier for everyone?',
        '主持人的话尚未证实。',
        'unknown',
        'We do not know yet.',
        'different',
        'It may be easy for some people, but not all.',
        a1,
      ],
      [
        'alternative',
        'offer-alternative',
        'What other idea could we discuss?',
        '提出选项而非已选。',
        'short-email',
        'We could try a shorter email.',
        'summary',
        'We could add a short weekly summary.',
        a1,
      ],
      [
        'trial',
        'propose-pilot',
        'Would you like to suggest a small test of the board?',
        '提议或不提议。',
        'pilot-proposal',
        'Yes, could one group test it?',
        'no-pilot',
        'No, I want more information first.',
        a1,
      ],
      [
        'measure',
        'choose-criterion',
        'How could we compare the board and email?',
        '无论是否提试点均可谈标准。',
        'time',
        'We could compare the time they take.',
        'find',
        'We could compare how easy they are to search.',
        a1,
      ],
      [
        'tone',
        'repair-tone',
        'How can you ask for a different view politely?',
        '合作交流。',
        'invite',
        'Please tell me what you think.',
        'reason',
        'Can you explain your reason?',
        a1,
      ],
      [
        'decision',
        'clarify-decision',
        'How should the manager get our views before choosing?',
        '选择收集意见的方法，不重复已知权限。',
        'talk',
        'The manager should talk to us.',
        'notes',
        'The manager should read our notes.',
        a1,
      ],
      [
        'record',
        'record-concern',
        'What should the meeting note include?',
        '不抹去分歧。',
        'questions',
        'The open questions.',
        'views',
        'The different views.',
        a1,
      ],
      [
        'revisit',
        'set-revisit',
        'When should we look at this idea again?',
        '设定重新讨论条件。',
        'information',
        'When we have more information.',
        'team',
        'When the team has read the proposal.',
        a1,
      ],
    ],
    a1,
  ),
  A2: workPack(
    scene,
    'A2',
    {
      canDoZh: '能表达意见、问证据并提出简单替代方案。',
      complexityZh: '从个人偏好进到团队使用差异，区分建议与决定。',
      scaffoldingZh: '已命名工具和主持人观点支撑简短反应。',
      registerZh: '礼貌异议与邀请别人说明，避免人身评价。',
    },
    [
      [
        'position',
        'state-position',
        'How do you feel about replacing the weekly email with a board?',
        '直接但礼貌表达。',
        'support',
        'I think a shared board could be useful.',
        'concern',
        'I have some doubts about replacing the email.',
        a2,
      ],
      [
        'goal',
        'find-common-goal',
        'What result should we all want from the new system?',
        '共通目的不等于方案同意。',
        'find',
        'We should be able to find the latest information easily.',
        'miss',
        'We should not miss important changes.',
        a2,
      ],
      [
        'reason',
        'give-reason',
        'Which practical point is most important to your view?',
        '选择关键考虑。',
        'time',
        'I want to know how much time it takes to keep the board up to date.',
        'access',
        'I want to know whether everyone can open it easily.',
        a2,
      ],
      [
        'evidence',
        'ask-evidence',
        'What information would help you judge the proposal?',
        '实际所需证据。',
        'example',
        'A complete example of a weekly update would help.',
        'feedback',
        'Comments from people in different roles would help.',
        a2,
      ],
      [
        'assumption',
        'question-assumption',
        'Can we be sure that one board means less work for every person?',
        '检验已提供观点。',
        'unknown',
        'No, we need to check how each person would use it.',
        'different',
        'Not necessarily. Some people may need to enter the same information twice.',
        a2,
      ],
      [
        'alternative',
        'offer-alternative',
        'What simpler option could we put beside the board idea?',
        '有不同实质的替代。',
        'short-email',
        'We could keep email but make the weekly message shorter.',
        'summary',
        'We could use the board and send a short summary as well.',
        a2,
      ],
      [
        'trial',
        'propose-pilot',
        'Would you suggest testing the board with a small group first?',
        '可暂不建议试点。',
        'pilot-proposal',
        'Yes, I would suggest a one-week test with one group.',
        'no-pilot',
        'Not yet. I would like to see a clearer example first.',
        a2,
      ],
      [
        'measure',
        'choose-criterion',
        'What could tell us whether one option works better than another?',
        '仅讨论比较标准。',
        'time',
        'We could count the time needed to write an update.',
        'find',
        'We could check how quickly people find a recent change.',
        a2,
      ],
      [
        'tone',
        'repair-tone',
        'What could you say when a colleague has a different opinion?',
        '保持好奇。',
        'ask',
        'Could you tell me what makes that option better for you?',
        'understand',
        'I see it differently, but I would like to understand your point.',
        a2,
      ],
      [
        'decision',
        'clarify-decision',
        'What should happen before the manager makes the final choice?',
        '程序而非结果。',
        'hear',
        'The manager should hear the team’s main concerns.',
        'compare',
        'The manager should compare the options clearly.',
        a2,
      ],
      [
        'record',
        'record-concern',
        'How can the notes show that people still have different views?',
        '记录异议。',
        'separate',
        'We can write the different views in separate points.',
        'open',
        'We can mark the questions that do not have an answer yet.',
        a2,
      ],
      [
        'revisit',
        'set-revisit',
        'What would be a useful reason to discuss the proposal again?',
        '重启讨论的条件。',
        'example',
        'A clearer example could help us discuss it again.',
        'feedback',
        'New feedback from the team would be a useful reason.',
        a2,
      ],
    ],
    a2,
  ),
  B1: workPack(
    scene,
    'B1',
    {
      canDoZh: '能用理由支持意见，质疑假设并协商比较方法。',
      complexityZh: '区分共同目的与具体工具，提出证据需求和后续条件。',
      scaffoldingZh: '单一明确工具争议，需解释因果而非套礼貌句。',
      registerZh: '尊重不同经历，聚焦工作而非对人的评价。',
    },
    [
      [
        'position',
        'state-position',
        'What is your initial view of moving weekly updates to a shared board?',
        '立场可以保留。',
        'support',
        'I support exploring it, because a single place for updates could be easier to follow.',
        'concern',
        'I am cautious about replacing email before we know how people will notice changes.',
        b1,
      ],
      [
        'goal',
        'find-common-goal',
        'What common aim could keep this discussion from becoming a debate about favourite tools?',
        '先找到共同目标。',
        'find',
        'We all need a reliable way to find the latest information without searching several places.',
        'miss',
        'We all want important changes to reach the people who need to act on them.',
        b1,
      ],
      [
        'reason',
        'give-reason',
        'Which concern would you use to explain your position?',
        '中立因素兼容两立场。',
        'time',
        'I would focus on the work required to maintain the system, not just how neat it looks.',
        'access',
        'I would focus on whether people can reach the information during their normal working day.',
        b1,
      ],
      [
        'evidence',
        'ask-evidence',
        'What evidence is missing from the discussion so far?',
        '不假造数据。',
        'example',
        'We have not seen a full week’s update, including changes made after the first post.',
        'feedback',
        'We have not heard from colleagues whose work does not keep them at a computer.',
        b1,
      ],
      [
        'assumption',
        'question-assumption',
        'How would you question the claim that the board means less work for everyone?',
        '针对给定观点。',
        'duplication',
        'I would ask whether anyone would still have to copy the same update into another system.',
        'notifications',
        'I would ask how people would know to check the board without someone sending reminders.',
        b1,
      ],
      [
        'alternative',
        'offer-alternative',
        'What alternative could meet the same goal without a complete switch?',
        '实质替代。',
        'short-email',
        'We could use a shorter email with a consistent layout, making changes easier to scan.',
        'hybrid',
        'We could keep detailed updates on the board and use a short email to flag important changes.',
        b1,
      ],
      [
        'trial',
        'propose-pilot',
        'Would you put forward a pilot now, or wait for more information?',
        '提案不等于批准。',
        'pilot-proposal',
        'I would propose a small pilot to see how the board fits real work.',
        'no-pilot',
        'I would wait until we understand who would maintain it, rather than start a pilot with unclear responsibilities.',
        b1,
      ],
      [
        'measure',
        'choose-criterion',
        'What would make a comparison fair, whether we run a pilot or review examples?',
        '标准兼容无试点路径。',
        'time',
        'We should count both writing and reading time, because saving one person time may cost another more.',
        'find',
        'We should ask people to find the same kind of update in each option.',
        b1,
      ],
      [
        'tone',
        'repair-tone',
        'Suppose a colleague gives an example of the board working well in their role. How could you respond with a concern?',
        '明确提供假设中的对方实例，再回应。',
        'context',
        'I can see why that works in your role; my concern is how it would work for people away from their desks.',
        'question',
        'Your example is useful, though I wonder whether it covers the cases where an update changes during the week.',
        b1,
      ],
      [
        'decision',
        'clarify-decision',
        'What decision process would you ask the manager to make clear?',
        '权限与程序。',
        'criteria',
        'I would ask which criteria the manager will use to choose between the options.',
        'input',
        'I would ask how the team’s feedback will be considered before the final decision.',
        b1,
      ],
      [
        'record',
        'record-concern',
        'How should the meeting notes handle an objection that has not been resolved?',
        '记录并保留未解决状态。',
        'reason',
        'They should record the concern and its reason, not just say that someone disagreed.',
        'question',
        'They should turn it into an open question with the information needed to answer it.',
        b1,
      ],
      [
        'revisit',
        'set-revisit',
        'What new information would make it worth reopening the discussion?',
        '不同重新评估条件。',
        'cost',
        'Evidence that the maintenance work is much lower or higher than expected would matter.',
        'access',
        'Feedback showing that some colleagues cannot reliably access updates would justify another discussion.',
        b1,
      ],
    ],
    b1,
  ),
  B2: workPack(
    scene,
    'B2',
    {
      canDoZh: '能支持并限定观点，比较证据、权衡方案并维护决策公平性。',
      complexityZh: '识别时间成本转移、试点偏差和少数意见，避免虚假共识。',
      scaffoldingZh: '具体会议问题和既有发言作支架，回答需论证。',
      registerZh: '有分寸地挑战观点，保持共同目的。',
    },
    [
      [
        'position',
        'state-position',
        'Where do you stand on replacing the weekly email, and how firm is that view?',
        '程度限定不是机械免责声明。',
        'support',
        'I am broadly in favour of exploring the board, though I would want to see how it handles urgent changes.',
        'concern',
        'I am not persuaded that replacement is the right move yet; the proposal says more about storing updates than getting them noticed.',
        b2,
      ],
      [
        'goal',
        'find-common-goal',
        'How would you frame a shared objective that both supporters and sceptics could accept?',
        '不将共同目标当方案一致。',
        'reliability',
        'The objective should be reliable access to current information, regardless of which tool provides it.',
        'action',
        'We should aim for changes reaching the right people in time to act, not simply for fewer emails.',
        b2,
      ],
      [
        'reason',
        'give-reason',
        'Which practical issue would you put at the centre of your argument?',
        '依据兼容正反立场。',
        'effort',
        'I would examine the total effort across the team, since a simpler view may conceal extra maintenance.',
        'access',
        'I would examine access during real work, particularly for colleagues who do not monitor a board throughout the day.',
        b2,
      ],
      [
        'evidence',
        'ask-evidence',
        'What would you ask for before treating the proposal’s benefits as established?',
        '实际证据需求。',
        'workflow',
        'I would ask for a complete example from initial update to later correction, rather than a polished static screen.',
        'roles',
        'I would ask for input from a range of roles, not only the people who helped choose the tool.',
        b2,
      ],
      [
        'assumption',
        'question-assumption',
        'How would you challenge “less work for everyone” without rejecting the proposal outright?',
        '针对假设并允许方案有价值。',
        'distribution',
        'I would ask whose work is reduced and whose increases; the board may still be worthwhile, but that balance should be visible.',
        'attention',
        'I would question the assumption that people will check it regularly without reminders, since that affects the claimed saving.',
        b2,
      ],
      [
        'alternative',
        'offer-alternative',
        'What middle option could address the main concern without adding unnecessary complexity?',
        '实质权衡。',
        'email-structure',
        'A standardised email with clear action headings could improve scanning without introducing another place to maintain.',
        'hybrid',
        'A board for detail plus a brief change alert could work, provided the alert links to the source rather than duplicates it.',
        b2,
      ],
      [
        'trial',
        'propose-pilot',
        'Is there enough clarity to recommend a pilot at this point?',
        '不假装已运行。',
        'pilot-proposal',
        'I would recommend a bounded pilot with a named maintainer and a clear point for deciding whether to continue.',
        'no-pilot',
        'I would hold off until maintenance responsibility is clear; otherwise the pilot may test enthusiasm rather than a workable process.',
        b2,
      ],
      [
        'measure',
        'choose-criterion',
        'Which criterion would help us compare options without favouring the tool we already like?',
        '不依赖试点已同意。',
        'effort',
        'We should measure total time spent producing, finding and correcting updates, not just the time to post them.',
        'reliability',
        'We should compare whether people can find the current answer to a realistic question, including a recent change.',
        b2,
      ],
      [
        'tone',
        'repair-tone',
        'A colleague hears your concern as resistance to change. How would you respond?',
        '具体语用修复。',
        'goal',
        'I am open to changing the process; I am asking how this option meets the shared goal for people in different roles.',
        'evidence',
        'My concern is about the evidence for this particular switch, not about keeping email at any cost.',
        b2,
      ],
      [
        'decision',
        'clarify-decision',
        'How would you ask for clarity when the meeting seems to be drifting towards a decision?',
        '防止沉默当同意。',
        'authority',
        'Could we clarify whether the manager is deciding today or gathering input for a later decision?',
        'criteria',
        'Could we state the criteria and the unresolved concerns before treating the discussion as a decision?',
        b2,
      ],
      [
        'record',
        'record-concern',
        'How would you keep the minutes fair when most people favour the proposal but one concern remains?',
        '保留少数意见。',
        'minority',
        'I would record the majority preference alongside the unresolved concern and what evidence could address it.',
        'status',
        'I would distinguish support for exploring the idea from support for a permanent switch.',
        b2,
      ],
      [
        'revisit',
        'set-revisit',
        'What would be a sensible trigger for reviewing a future decision?',
        '未来有条件检查。',
        'burden',
        'A sustained increase in duplicate work would justify review, rather than one difficult first day.',
        'missed',
        'Repeated missed updates affecting decisions would be a stronger trigger than personal dislike of the interface.',
        b2,
      ],
    ],
    b2,
  ),
  C1: workPack(
    scene,
    'C1',
    {
      canDoZh: '能揭示提案隐含假设、处理被误解的异议并推动可追溯决定。',
      complexityZh:
        '兼顾证据质量、成本分配和权力语用，区分探索支持与正式接受。',
      scaffoldingZh: '已提供具体主张，不制造不存在的试用数据或前文。',
      registerZh: '坚定且不敌对，复杂限定由实际争议驱动。',
    },
    [
      [
        'position',
        'state-position',
        'How would you position yourself without making the discussion a choice between enthusiasm and obstruction?',
        '保持有分寸的立场。',
        'support',
        'I see a worthwhile direction in the board, and I would support exploring it while leaving the case for replacing email open.',
        'concern',
        'I remain unconvinced by replacement, but I am willing to examine a design that addresses how people notice changes rather than merely where updates sit.',
        c1,
      ],
      [
        'goal',
        'find-common-goal',
        'What shared outcome would you bring the group back to when preferences start dominating?',
        '工具偏好之外的目标。',
        'trust',
        'People should be able to trust that they have found the current information without reconstructing it from several versions.',
        'reach',
        'The people affected by a change need to notice it in time; reducing message volume is useful only if it serves that outcome.',
        c1,
      ],
      [
        'reason',
        'give-reason',
        'What underlying concern would you make explicit before arguing about the interface?',
        '揭示实际约束。',
        'distribution',
        'I would surface how the maintenance burden is distributed, because apparent simplicity for readers may depend on invisible work elsewhere.',
        'attention',
        'I would focus on attention: a well-organised board is of limited value if checking it is not part of people’s working routine.',
        c1,
      ],
      [
        'evidence',
        'ask-evidence',
        'What would persuade you that the proposal works beyond a carefully chosen demonstration?',
        '证据选择偏差。',
        'awkward-case',
        'I would want to see an awkward midweek correction handled from posting through to someone acting on it, not just a clean initial update.',
        'less-visible',
        'I would want feedback from the less visible users who rarely attend these meetings, since the keenest users may not reveal the access problems.',
        c1,
      ],
      [
        'assumption',
        'question-assumption',
        'How would you unpack the chair’s claim that one board will mean less work for everyone?',
        '已有具体发言，不发明历史。',
        'test',
        'Could we test that assumption? The saving may depend on someone doing extra consolidation work that the proposal has not yet assigned.',
        'separate',
        'I would separate fewer messages from less work; searching, updating and prompting people still take time even when the inbox is quieter.',
        c1,
      ],
      [
        'alternative',
        'offer-alternative',
        'What alternative would expose whether the problem is the tool or the way updates are organised?',
        '更深方案辨析。',
        'email-test',
        'A consistently structured email could show whether clearer ownership and action headings solve much of the problem without a new tool.',
        'single-source',
        'A single board with nonduplicating change alerts could isolate the value of one source while preserving a route to people’s attention.',
        c1,
      ],
      [
        'trial',
        'propose-pilot',
        'Would a pilot clarify the disagreement, or risk turning a provisional idea into the default?',
        '提议试点或暂不提议均成立。',
        'pilot-proposal',
        'I would propose a pilot only with an explicit stopping point and a named decision-maker, so starting it does not quietly settle the permanent choice.',
        'no-pilot',
        'I would not propose a pilot yet; unless the unresolved ownership is settled, temporary extra effort could make the approach look more sustainable than it is.',
        c1,
      ],
      [
        'measure',
        'choose-criterion',
        'How could the comparison distinguish a genuine improvement from effort merely moving between colleagues?',
        '标准并不暗示试点已发生。',
        'whole-cost',
        'We should include the work of maintaining, finding and correcting information across roles, rather than hide an increased burden on some colleagues in a team average.',
        'failure',
        'We should examine realistic missed-change cases and the recovery work they create, not rely solely on how quickly a routine update is posted.',
        c1,
      ],
      [
        'tone',
        'repair-tone',
        'Someone says you are overcomplicating a simple improvement. How would you keep the concern on the table?',
        '回应具体误解，不把待核实可达性当已证实缺陷。',
        'boundary',
        'I am not asking us to solve every edge case; I am asking who will do the recurring work the improvement depends on.',
        'purpose',
        'I would like the change to succeed, which is why I want to check how colleagues outside this room would access updates before we rely on it.',
        c1,
      ],
      [
        'decision',
        'clarify-decision',
        'How would you intervene if the chair took a quiet room as consent to switch permanently?',
        '沉默不是同意。',
        'distinguish',
        'Before we record that, could we distinguish agreement to explore the board from agreement to replace email permanently?',
        'explicit',
        'I would ask for an explicit statement of the decision and how the outstanding concern has been treated, rather than let silence carry that meaning.',
        c1,
      ],
      [
        'record',
        'record-concern',
        'What should the record preserve if the manager eventually chooses an option despite a reasonable objection?',
        '未来决定中的异议记录。',
        'rationale',
        'It should preserve the objection, the reason for proceeding and the condition under which the decision would be reviewed.',
        'scope',
        'It should make the extent of the decision clear, so acceptance of a limited change is not later cited as support for a broader one.',
        c1,
      ],
      [
        'revisit',
        'set-revisit',
        'How would you define a review trigger that does not invite the same argument to restart every week?',
        '稳定又可纠错的条件。',
        'threshold',
        'I would agree a concrete pattern of missed updates or duplicated work that warrants review, rather than reopen the choice after every complaint.',
        'assumption',
        'I would tie review to a central assumption proving false, such as the promised reduction in maintenance, and name the evidence that would demonstrate that.',
        c1,
      ],
    ],
    c1,
  ),
}
