import { workPack, type WorkScene, type Review } from './authoring'
const a1: Review = {
  state: 'model-reviewed',
  record:
    'work-review.md#progress-update: A1 all 12 Q/24 A, rationale, both variants and paths read and corrected by Codex implementation agent, 2026-09-10; model-assisted, not teacher certification',
}
const a2: Review = {
  state: 'model-reviewed',
  record:
    'work-review.md#progress-update: A2 all 12 Q/24 A, rationale, both variants and paths read and corrected by Codex implementation agent, 2026-09-10; model-assisted, not teacher certification',
}
const b1: Review = {
  state: 'model-reviewed',
  record:
    'work-review.md#progress-update: B1 all 12 Q/24 A, rationale, both variants and paths read and corrected by Codex implementation agent, 2026-09-10; model-assisted, not teacher certification',
}
const b2: Review = {
  state: 'model-reviewed',
  record:
    'work-review.md#progress-update: B2 all 12 Q/24 A, rationale, both variants and paths read and corrected by Codex implementation agent, 2026-09-10; model-assisted, not teacher certification',
}
const c1: Review = {
  state: 'model-reviewed',
  record:
    'work-review.md#progress-update: C1 all 12 Q/24 A, rationale, both variants and paths read and corrected by Codex implementation agent, 2026-09-10; model-assisted, not teacher certification',
}
const scene: WorkScene = {
  sceneId: 'work-03',
  slug: 'progress-update',
  situations: [
    '虚构展会项目周报。你报告访客指南状态；草稿、旧版与新版地图、图片和使用记录都在样例文件夹中。本周新地图和新图片均已收到，回答可突出其中一项；新地图入口与旧版不同，部分新图片缺匹配记录，两类问题均待核实。设计团队负责版式，活动团队确认入口，图片协调员核对记录。可说草稿完成或仍在写，两者均不表示批准。工作板链接指向当前文件。短练说明状态、证据位置和预计，所有回答仅为角色卡练习。',
    '虚构展会项目交接更新，联系人明天由另一人接替。文件夹有草稿、旧新地图、图片和记录，工作板链接指向当前文件。本周新地图和新图片均已收到；入口改动及缺匹配的图片记录均待核实，回答只选择报告重点。活动团队确认入口，图片协调员核对记录，设计团队负责版式；尚无整份指南批准。交接版增加接收者需求和升级条件，不替设计团队确认状态，不把预测改成完成。',
  ],
  paths: [
    {
      short: ['status', 'evidence', 'forecast'],
      standard: [
        'status',
        'evidence',
        'forecast',
        'change',
        'dependency',
        'next',
      ],
      extended: [
        'status',
        'evidence',
        'forecast',
        'change',
        'dependency',
        'next',
        'risk',
        'support',
        'scope',
        'update',
      ],
    },
    {
      short: ['status', 'evidence', 'forecast'],
      standard: [
        'status',
        'evidence',
        'forecast',
        'dependency',
        'change',
        'next',
      ],
      extended: [
        'status',
        'evidence',
        'forecast',
        'dependency',
        'change',
        'next',
        'risk',
        'support',
        'audience',
        'escalate',
      ],
    },
  ],
  closing:
    'Your progress report has been rehearsed. Reported facts, outstanding checks and forecasts remain separate; no guide has been approved or delivered here.',
  partial:
    'This progress report is only partly rehearsed. Unconfirmed status and dates remain open.',
  repairs: {
    clarify: 'I can ask about this part of the progress report more simply.',
    struggle: 'Start with what is finished or what still needs checking.',
    offTopic: 'Let us return to the guide’s progress.',
    unknown:
      'That wording is outside the covered report, so I have not confirmed a status from it.',
    changed: 'Your earlier report detail has been replaced.',
    refusedClosing: 'We will stop the progress-report rehearsal here.',
  },
}
export const progressPacks = {
  A1: workPack(
    scene,
    'A1',
    {
      canDoZh: '能说草稿现状、资料位置与简单预计。',
      complexityZh: '把草稿和整份指南分开，增加待核实事项。',
      scaffoldingZh: '文件夹、地图和图片构成固定支架，一次只问一项。',
      registerZh: '简单事实短句，能直接说不知道。',
    },
    [
      [
        'status',
        'report-status',
        'Is the guide draft finished?',
        '草稿完成不等于批准。',
        'draft-done',
        'Yes, the draft is finished.',
        'draft-writing',
        'No, I am still writing the draft.',
        a1,
      ],
      [
        'evidence',
        'show-evidence',
        'Where can I see your latest work?',
        '选择可查看的资料位置。',
        'folder',
        'It is in the shared folder.',
        'link',
        'It is at the link on the project board.',
        a1,
      ],
      [
        'forecast',
        'qualify-forecast',
        'When do you think the guide will be ready?',
        '估计或未知。',
        'estimate',
        'I think it will be ready next week.',
        'unknown',
        'I do not know yet.',
        a1,
      ],
      [
        'change',
        'explain-change',
        'What new information arrived this week?',
        '新资料不等于已核实。',
        'map',
        'A new map arrived.',
        'photos',
        'Some new photos arrived.',
        a1,
      ],
      [
        'dependency',
        'identify-dependency',
        'What do you still need to check for the guide?',
        '选择具体核实需求。',
        'map',
        'I need to check the map.',
        'photos',
        'I need to check the photo records.',
        a1,
      ],
      [
        'next',
        'state-next-step',
        'What is your next step on this project?',
        '可独立采取的行动。',
        'list',
        'I will list the open questions.',
        'compare',
        'I will compare the files.',
        a1,
      ],
      [
        'risk',
        'flag-risk',
        'What could cause a problem with the printed guide?',
        '表达可能的风险。',
        'map-error',
        'The map could be wrong.',
        'photo-record',
        'A photo record could be missing.',
        a1,
      ],
      [
        'support',
        'request-support',
        'Do you want help checking the file names?',
        '求助或不求助。',
        'ask',
        'Yes, please check them with me.',
        'no',
        'No, I can check them.',
        a1,
      ],
      [
        'scope',
        'limit-report',
        'Can you give an update for the design team too?',
        '不能把个人报告扩大。',
        'ask-team',
        'No, please ask the design team.',
        'not-yet',
        'Not yet. I need their update.',
        a1,
      ],
      [
        'update',
        'set-update',
        'When can you send another progress note?',
        '承诺自己能发的更新，而非交付。',
        'tomorrow',
        'I can send a note tomorrow.',
        'friday',
        'I can send a note on Friday.',
        a1,
      ],
      [
        'audience',
        'adapt-report',
        'What does the new project contact need first?',
        '选择交接信息重点。',
        'open-list',
        'The list of open questions.',
        'files',
        'The links to the latest files.',
        a1,
      ],
      [
        'escalate',
        'raise-issue',
        'Who can you tell if a guide problem gets bigger?',
        '渠道而非已通知。',
        'lead',
        'I can tell the project lead.',
        'contact',
        'I can tell the project contact.',
        a1,
      ],
    ],
    a1,
  ),
  A2: workPack(
    scene,
    'A2',
    {
      canDoZh: '能作简短状态报告，指出资料变化和需要核实的地方。',
      complexityZh: '串联状态、证据与后续，明确预计不是确定日期。',
      scaffoldingZh: '熟悉文档情境提供支架，可选择两种合理状态。',
      registerZh: '清晰普通工作英语，用简单原因和时间表达。',
    },
    [
      [
        'status',
        'report-status',
        'How far have you got with the visitor-guide draft?',
        '报告写作进度。',
        'draft-done',
        'I have finished the draft, but the guide still needs checks.',
        'draft-writing',
        'I am still writing the draft, and the guide needs checks too.',
        a2,
      ],
      [
        'evidence',
        'show-evidence',
        'How can the project contact find the current draft?',
        '资料获取方式。',
        'folder',
        'They can open the dated file in the shared folder.',
        'link',
        'They can use the latest link on the project board.',
        a2,
      ],
      [
        'forecast',
        'qualify-forecast',
        'Can you give a possible finish time for the guide?',
        '保留不确定性。',
        'estimate',
        'Next week is my estimate, but it is not a fixed date.',
        'unknown',
        'I cannot give a finish time until I know more.',
        a2,
      ],
      [
        'change',
        'explain-change',
        'What has changed in the information for the guide?',
        '新信息内容。',
        'map',
        'We received a new map with a different entrance.',
        'photos',
        'We received photos that were not in the first folder.',
        a2,
      ],
      [
        'dependency',
        'identify-dependency',
        'Which information still needs confirmation?',
        '待确认资料。',
        'map',
        'The entrance on the map still needs confirmation.',
        'photos',
        'The records for using the photos still need confirmation.',
        a2,
      ],
      [
        'next',
        'state-next-step',
        'What can you do next while some information is still open?',
        '有依赖时继续可控工作。',
        'list',
        'I can write down the questions we need answered.',
        'compare',
        'I can compare the new files with the older ones.',
        a2,
      ],
      [
        'risk',
        'flag-risk',
        'What might happen if we print without checking the details?',
        '风险而非确定后果。',
        'map-error',
        'Visitors might go to the wrong entrance.',
        'photo-record',
        'We might use a photo without a complete record.',
        a2,
      ],
      [
        'support',
        'request-support',
        'Would it help to have someone check the file names with you?',
        '有界求助。',
        'ask',
        'Yes, could someone check for old copies with me?',
        'no',
        'No, thanks. I can use the dates to check them myself.',
        a2,
      ],
      [
        'scope',
        'limit-report',
        'Does your update also tell us whether the layout is finished?',
        '区分他人工作。',
        'ask-team',
        'No, the design team needs to give that update.',
        'not-yet',
        'Not yet. I have not checked with the design team.',
        a2,
      ],
      [
        'update',
        'set-update',
        'When will you send a note about the remaining questions?',
        '下一次报告而非完成日期。',
        'tomorrow',
        'I will send a short note tomorrow afternoon.',
        'friday',
        'I will send the question list on Friday morning.',
        a2,
      ],
      [
        'audience',
        'adapt-report',
        'How could you make this update easier for the new contact to use?',
        '交接格式。',
        'summary',
        'I could put the open questions at the top.',
        'links',
        'I could add clear links to the latest files.',
        a2,
      ],
      [
        'escalate',
        'raise-issue',
        'What will you do if a new problem could affect the exhibition?',
        '及时升级。',
        'lead',
        'I will tell the project lead and explain the problem.',
        'contact',
        'I will ask the project contact for a quick discussion.',
        a2,
      ],
    ],
    a2,
  ),
  B1: workPack(
    scene,
    'B1',
    {
      canDoZh: '能解释进度变化、说明信息依赖并给出有条件的预估。',
      complexityZh: '区分实际完成与可能完成，提出合理下一步而不把依赖当借口。',
      scaffoldingZh: '明确的地图和图片核实任务支撑因果组织。',
      registerZh: '平实可信的项目报告，承认未知并说明如何补齐。',
    },
    [
      [
        'status',
        'report-status',
        'What is the current state of the draft, separate from final approval?',
        '明确草稿与批准不同。',
        'draft-done',
        'The draft is complete, but the map and photo information still need to be checked.',
        'draft-writing',
        'The draft is still being written, and the map and photo checks are also outstanding.',
        b1,
      ],
      [
        'evidence',
        'show-evidence',
        'What can the contact look at to verify your description of progress?',
        '证据入口。',
        'folder',
        'The dated draft in the shared folder shows exactly what is there now.',
        'link',
        'The project-board link opens the current draft rather than an older email attachment.',
        b1,
      ],
      [
        'forecast',
        'qualify-forecast',
        'How would you describe the likely completion time at this stage?',
        '预估或不足以预估。',
        'estimate',
        'My estimate is next week, assuming the outstanding information arrives in time.',
        'unknown',
        'I cannot make a useful forecast until we know how much the remaining checks will change.',
        b1,
      ],
      [
        'change',
        'explain-change',
        'What new information explains why the guide needs another look?',
        '变化的具体原因。',
        'map',
        'The new map shows a different entrance, so we need to check which one visitors should use.',
        'photos',
        'The new photos do not all have matching records, so we need to check the file list.',
        b1,
      ],
      [
        'dependency',
        'identify-dependency',
        'Which outside confirmation would help you move the guide forward?',
        '需要谁提供什么，而非已获得。',
        'map',
        'We need the event team to confirm the correct entrance on the map.',
        'photos',
        'We need the image coordinator to confirm that the photo records are complete.',
        b1,
      ],
      [
        'next',
        'state-next-step',
        'What will you do to keep the work moving rather than simply wait?',
        '自己能采取行动。',
        'questions',
        'I will group the open questions so the relevant people can answer them efficiently.',
        'compare',
        'I will compare the files and highlight the exact differences that need a decision.',
        b1,
      ],
      [
        'risk',
        'flag-risk',
        'Which risk would you bring to the contact’s attention now?',
        '风险和后果相连。',
        'entrance',
        'An incorrect entrance could confuse visitors, so that detail needs attention before printing.',
        'records',
        'Incomplete image records could force a late photo change and create more layout work.',
        b1,
      ],
      [
        'support',
        'request-support',
        'Is there a small task someone else could help with, or can you handle the checks yourself?',
        '请求与拒绝均可。',
        'ask',
        'Could someone cross-check the file names while I compare the content?',
        'no',
        'I can handle this pass myself; I will ask for help if I find conflicting versions.',
        b1,
      ],
      [
        'scope',
        'limit-report',
        'How should we describe the design team’s progress in this report?',
        '别人的状态不能从本报告推断。',
        'separate',
        'We should leave it as awaiting their update, because I cannot confirm their progress.',
        'request',
        'We should ask them for a short status note before adding a claim about layout.',
        b1,
      ],
      [
        'update',
        'set-update',
        'What will your next report tell the contact even if the guide is not finished?',
        '更新应提供真实信息。',
        'resolved',
        'It will show which questions have been resolved and which still need an answer.',
        'changes',
        'It will explain whether the new information changes the amount of work left.',
        b1,
      ],
      [
        'audience',
        'adapt-report',
        'What would you emphasise for a contact who is joining the project tomorrow?',
        '根据接收者调整。',
        'decisions',
        'I would explain the decisions still needed before giving the detailed work history.',
        'current',
        'I would point to the current files and explain why earlier copies may be misleading.',
        b1,
      ],
      [
        'escalate',
        'raise-issue',
        'When would you raise a concern rather than wait for the regular update?',
        '沟通触发条件。',
        'print',
        'I would raise it if an unresolved detail could affect the printing plan.',
        'conflict',
        'I would raise it if two teams gave conflicting answers that I could not resolve.',
        b1,
      ],
    ],
    b1,
  ),
  B2: workPack(
    scene,
    'B2',
    {
      canDoZh: '能用证据支撑状态，解释变化对计划的影响并向不同读者报告。',
      complexityZh: '识别关键依赖、风险与非关键细节，给出有根据的条件预测。',
      scaffoldingZh: '固定文档项目背景，需较独立地组织论据和建议。',
      registerZh: '可信而不防御，避免把状态报告变为泛泛免责。',
    },
    [
      [
        'status',
        'report-status',
        'How would you summarise the draft without implying that the guide is ready for release?',
        '完成范围与待核实事项。',
        'draft-done',
        'The writing is complete; the outstanding work is to verify the map and image information before approval.',
        'draft-writing',
        'The writing is still in progress, alongside the map and image checks that approval will require.',
        b2,
      ],
      [
        'evidence',
        'show-evidence',
        'Which version should someone use to assess your update independently?',
        '明确当前版本证据。',
        'folder',
        'Use the dated draft in the shared folder, where the open points are marked beside the relevant content.',
        'link',
        'Use the live project-board link; exported copies may not include the latest annotations.',
        b2,
      ],
      [
        'forecast',
        'qualify-forecast',
        'What forecast is defensible given the outstanding checks?',
        '有条件预测或证据不足。',
        'estimate',
        'Next week is a reasonable estimate if the checks confirm the current content rather than require substantial replacement.',
        'unknown',
        'A finish date would be premature until we know whether the unresolved details change the content or only confirm it.',
        b2,
      ],
      [
        'change',
        'explain-change',
        'Which change has the greatest bearing on the remaining work?',
        '变化影响。',
        'map',
        'The revised entrance on the map may affect several references, so confirming it is more important than a cosmetic edit.',
        'photos',
        'The additional photos introduce record-matching work that was not included in the original estimate.',
        b2,
      ],
      [
        'dependency',
        'identify-dependency',
        'Where is another team’s input essential rather than merely helpful?',
        '权限或知识依赖。',
        'map',
        'Only the event team can confirm the intended visitor entrance; comparing maps alone cannot settle that.',
        'photos',
        'The image coordinator needs to confirm the records; a plausible file name is not enough to establish that they are complete.',
        b2,
      ],
      [
        'next',
        'state-next-step',
        'What can you prepare now to make the outstanding decision easier?',
        '准备能促进决策的材料。',
        'options',
        'I can present the conflicting details side by side and ask a focused question about each.',
        'impact',
        'I can show which pages would change under each answer, so the contact can see the practical impact.',
        b2,
      ],
      [
        'risk',
        'flag-risk',
        'Which risk needs visibility at project level, rather than just in your personal notes?',
        '项目层面影响。',
        'entrance',
        'A late entrance change could affect both the guide and signs, so the project needs a coordinated answer.',
        'images',
        'Replacing images after layout could create avoidable rework, especially if several pages use the same photo.',
        b2,
      ],
      [
        'support',
        'request-support',
        'Would extra help shorten the work, or add coordination overhead at this point?',
        '权衡帮助的价值。',
        'ask',
        'A separate file-name check could run in parallel; could someone take that bounded task?',
        'no',
        'At this stage I would spend longer explaining the inconsistencies than checking them, so I will finish the first pass myself.',
        b2,
      ],
      [
        'scope',
        'limit-report',
        'How would you handle a request to report one overall percentage for writing and layout?',
        '不凭个人数据声称团队状态。',
        'separate',
        'I would report writing separately and ask the design team for their status, since combining them now would conceal missing information.',
        'milestones',
        'I would suggest named milestones instead; without the design team’s input, a single percentage would look more precise than it is.',
        b2,
      ],
      [
        'update',
        'set-update',
        'What should the next update contain to help the contact make a decision?',
        '行动相关报告。',
        'impact',
        'It should show which open questions affect printing and which can be resolved without changing the plan.',
        'options',
        'It should set out the remaining options and the information needed to choose between them.',
        b2,
      ],
      [
        'audience',
        'adapt-report',
        'How would you adapt the update for a new contact who has little time?',
        '信息排序。',
        'decisions-first',
        'I would lead with the decisions needed, then link the evidence rather than repeat the full project history.',
        'exceptions',
        'I would highlight what has changed from the last agreed plan and leave unchanged background in an attachment.',
        b2,
      ],
      [
        'escalate',
        'raise-issue',
        'What would make an unresolved detail worth escalating immediately?',
        '有界升级条件。',
        'cross-team',
        'I would escalate conflicting instructions that affect more than one team and cannot be settled at working level.',
        'window',
        'I would escalate when the time left to make a choice is about to disappear, even if the final outcome is still uncertain.',
        b2,
      ],
    ],
    b2,
  ),
  C1: workPack(
    scene,
    'C1',
    {
      canDoZh: '能管理报告中证据、推断与决策的界限，回应过度简化的状态要求。',
      complexityZh:
        '考虑跨团队影响、信息时效及隐含批准，提出具体而有分寸的澄清。',
      scaffoldingZh: '已知项目约束，无统一句式延长；需独立组织信息优先序。',
      registerZh:
        '面向项目负责人的自然专业表达，具体限定而非空泛报告方法声明。',
    },
    [
      [
        'status',
        'report-status',
        'What is the clearest distinction between the work completed and the work that still stands between us and approval?',
        '写作现状和批准障碍。',
        'draft-done',
        'The draft itself is complete; what still stands in the way is confirmation of the map and image information, not further drafting.',
        'draft-writing',
        'Drafting is still under way, and approval also depends on the map and image checks; those are separate pieces of unfinished work.',
        c1,
      ],
      [
        'evidence',
        'show-evidence',
        'Where can the incoming contact trace a conclusion back to the detail that supports it?',
        '证据链入口。',
        'folder',
        'The dated folder draft keeps the open annotations beside the relevant passages, so the contact can see precisely what each conclusion rests on.',
        'link',
        'The project-board link points to the working copy with its revision history, which is more informative than a detached version sent by email.',
        c1,
      ],
      [
        'forecast',
        'qualify-forecast',
        'How would you respond if the contact wanted to put next week’s completion in a briefing as a firm date?',
        '防止把预测升级为确认。',
        'estimate',
        'Next week is my current estimate, but I would keep it conditional on the checks; a firm date would imply the remaining content is already settled.',
        'unknown',
        'I would leave the completion date open for now and explain what the checks need to establish before we can give a credible range.',
        c1,
      ],
      [
        'change',
        'explain-change',
        'What recent change could look minor in a summary while creating substantial work downstream?',
        '隐含跨文档影响。',
        'map',
        'The entrance moved on the latest map; that single detail could leave the guide and signs directing visitors to different places.',
        'photos',
        'The new image set looks like a simple swap, but incomplete matching records could force replacements after the layout has been built around it.',
        c1,
      ],
      [
        'dependency',
        'identify-dependency',
        'Which unresolved point cannot responsibly be settled by your own best guess?',
        '明确知识边界。',
        'map',
        'The intended entrance needs the event team’s confirmation; the newest map is evidence of a change, not proof that the change is final.',
        'photos',
        'The image records need confirmation from their coordinator; visual similarity between files cannot resolve a missing record.',
        c1,
      ],
      [
        'next',
        'state-next-step',
        'How could you reduce the burden on the people whose confirmation you need?',
        '具体降低协作成本。',
        'decision-note',
        'I can send a short decision note with the two conflicting details and the pages affected, rather than ask them to inspect the whole folder.',
        'targeted',
        'I can separate questions only they can answer from checks I can do myself, keeping the request focused on their expertise.',
        c1,
      ],
      [
        'risk',
        'flag-risk',
        'What would you want the project lead to see before the remaining issue becomes urgent?',
        '提前呈现风险传播。',
        'coordination',
        'An entrance change could trigger separate corrections in the guide and signage; we need one confirmed reference before those versions drift apart.',
        'rework',
        'If images are replaced after layout, a small information gap becomes coordinated rework, so the timing of confirmation matters as much as the answer.',
        c1,
      ],
      [
        'support',
        'request-support',
        'Where could a colleague add value without having to reconstruct the whole history?',
        '限定可委派的工作或不请求。',
        'ask',
        'A colleague could check the file inventory against the record list without judging the content; could we ask for help on that clearly bounded pass?',
        'no',
        'The remaining inconsistencies are tightly connected, so I would finish tracing them myself before inviting someone into a half-formed account of the problem.',
        c1,
      ],
      [
        'scope',
        'limit-report',
        'The contact wants a single green status for the guide and layout. How would you handle that?',
        '不同责任状态不能合并为批准。',
        'separate',
        'I would keep the layout status open until the design team responds; a single green label would hide exactly the gap the contact needs to see.',
        'criteria',
        'I would ask what green is intended to mean and report against that criterion once the design team has supplied their part.',
        c1,
      ],
      [
        'update',
        'set-update',
        'How would you make the next report useful if none of the outstanding confirmations has arrived?',
        '未解决时仍有信息价值。',
        'impact',
        'I would show which decisions are becoming time-sensitive and what choices remain, instead of repeating that we are still waiting.',
        'workaround',
        'I would set out the work that can continue safely and the changes that should wait, so the contact can direct effort without assuming the unknowns away.',
        c1,
      ],
      [
        'audience',
        'adapt-report',
        'What context is easy to omit but important for the person taking over tomorrow?',
        '交接隐含背景。',
        'assumptions',
        'They need to know which earlier assumptions the new material has called into question, otherwise a familiar summary could steer them towards an outdated decision.',
        'authority',
        'They need to know who can settle each open point, so a helpful opinion from the wrong person is not treated as confirmation.',
        c1,
      ],
      [
        'escalate',
        'raise-issue',
        'How would you escalate the issue without making it sound as though another team is simply failing you?',
        '陈述影响与所需决策，不推责。',
        'choice',
        'I would describe the decision now needed and the consequence of leaving it open, while keeping the history of requests brief and factual.',
        'constraints',
        'I would explain the competing constraints and ask the lead to resolve the priority, rather than attribute the delay to someone’s lack of effort.',
        c1,
      ],
    ],
    c1,
  ),
}
