import { workPack, type WorkScene, type Review } from './authoring'
const a1: Review = {
  state: 'model-reviewed',
  record:
    'work-review.md#work-introduction: A1 all 12 Q/24 A, rationale, both variants and paths read and corrected by Codex implementation agent, 2026-09-10; model-assisted, not teacher certification',
}
const a2: Review = {
  state: 'model-reviewed',
  record:
    'work-review.md#work-introduction: A2 all 12 Q/24 A, rationale, both variants and paths read and corrected by Codex implementation agent, 2026-09-10; model-assisted, not teacher certification',
}
const b1: Review = {
  state: 'model-reviewed',
  record:
    'work-review.md#work-introduction: B1 all 12 Q/24 A, rationale, both variants and paths read and corrected by Codex implementation agent, 2026-09-10; model-assisted, not teacher certification',
}
const b2: Review = {
  state: 'model-reviewed',
  record:
    'work-review.md#work-introduction: B2 all 12 Q/24 A, rationale, both variants and paths read and corrected by Codex implementation agent, 2026-09-10; model-assisted, not teacher certification',
}
const c1: Review = {
  state: 'model-reviewed',
  record:
    'work-review.md#work-introduction: C1 all 12 Q/24 A, rationale, both variants and paths read and corrected by Codex implementation agent, 2026-09-10; model-assisted, not teacher certification',
}
const scene: WorkScene = {
  sceneId: 'work-01',
  slug: 'work-introduction',
  situations: [
    '虚构公司Juniper的新同事见面。你与接待同事介绍工作方式；练习角色在客户支持团队，团队还负责入职指南，负责人为Maya。你可选择描述自己的具体分工与已有经验，不代表用户真实履历。纸上列有chat、guide和queue三个工作词，尚无人读出或解释。短练只完成角色、当前关注点与联系偏好；拓展讨论协作边界和学习安排，所有求助与约谈仍是提议。',
    '虚构Juniper支持团队交接见面：一位跨团队同事希望知道该把什么问题交给你。背景同为支持团队、入职指南和负责人Maya；你尚未接下额外任务。交接版着重权限边界、请教对象和下次联系，避免把介绍说成对整个团队的承诺。提供的经历仅是角色卡素材，不要用于捏造个人资历。',
  ],
  paths: [
    {
      short: ['role', 'focus', 'contact'],
      standard: ['role', 'focus', 'contact', 'experience', 'learn', 'help'],
      extended: [
        'role',
        'focus',
        'contact',
        'experience',
        'learn',
        'help',
        'boundary',
        'name',
        'feedback',
        'meet',
      ],
    },
    {
      short: ['role', 'focus', 'contact'],
      standard: ['role', 'focus', 'contact', 'experience', 'boundary', 'help'],
      extended: [
        'role',
        'focus',
        'contact',
        'experience',
        'boundary',
        'help',
        'learn',
        'name',
        'handoff',
        'check',
      ],
    },
  ],
  closing:
    'Your introduction and collaboration preferences are recorded for this rehearsal. No colleague has accepted a new assignment or meeting.',
  partial:
    'The introduction is partly rehearsed. Unanswered details about your role remain open.',
  repairs: {
    clarify: 'I can put this introduction question another way.',
    struggle: 'Start with one task you do or one thing you need.',
    offTopic: 'Let us return to getting to know your work.',
    unknown:
      'That introduction is not in the covered pair, so I have not confirmed a role from it.',
    changed:
      'Your earlier introduction detail has been replaced in this rehearsal.',
    refusedClosing: 'We will end the introduction rehearsal here.',
  },
}
export const introductionPacks = {
  A1: workPack(
    scene,
    'A1',
    {
      canDoZh: '能在固定团队背景下说简单职责并提出具体帮助需求。',
      complexityZh: '一次处理一件工作或一种偏好，拓展增加边界与会面提议。',
      scaffoldingZh: '角色卡和二选一支架支持短话轮，可请求换一种问法。',
      registerZh: '友好而具体的短句，不要求商务术语。',
    },
    [
      [
        'role',
        'introduce-role',
        'What do you do on the support team?',
        '说出具体工作。',
        'chat',
        'I answer customer chats.',
        'guide',
        'I work on the welcome guide.',
        a1,
      ],
      [
        'focus',
        'name-focus',
        'What are you learning today?',
        '选今天学习的内容。',
        'names',
        'I am learning my colleagues’ names.',
        'tools',
        'I am learning how to use our work tools.',
        a1,
      ],
      [
        'contact',
        'choose-contact',
        'How can I contact you at work?',
        '选择工作联系方式。',
        'chat',
        'Please message me in the team chat.',
        'email',
        'Please email me.',
        a1,
      ],
      [
        'experience',
        'share-experience',
        'Have you worked in a shop before?',
        '使用虚构角色的经历。',
        'yes',
        'Yes, I worked in a bookshop.',
        'no',
        'No, this is my first job.',
        a1,
      ],
      [
        'learn',
        'identify-learning',
        'What would you like to see first?',
        '选想了解的工作资料。',
        'guide',
        'The welcome guide, please.',
        'queue',
        'The customer chat list, please.',
        a1,
      ],
      [
        'help',
        'request-help',
        'Do you need help with your desk?',
        '可以求助或不需要。',
        'chair-request',
        'Yes, please help me with the chair.',
        'no',
        'No, my desk is ready.',
        a1,
      ],
      [
        'boundary',
        'state-boundary',
        'Can you answer price questions yet?',
        '区分能处理与仍需帮助。',
        'basic',
        'I can answer simple price questions.',
        'help',
        'Not yet. I need help with prices.',
        a1,
      ],
      [
        'name',
        'clarify-term',
        'Is the word queue clear to you?',
        '词在纸上，不假设已听过。',
        'clear',
        'Yes, it means the waiting list here.',
        'explain-request',
        'No, please explain it.',
        a1,
      ],
      [
        'feedback',
        'invite-feedback',
        'How do you want tips on your work?',
        '选接收建议的方式。',
        'show',
        'Please show me one example.',
        'write',
        'Please write a short note.',
        a1,
      ],
      [
        'meet',
        'propose-meeting',
        'When would you like a short team tour?',
        '提出时间，不代表获同意。',
        'today-request',
        'This afternoon, please.',
        'tomorrow-request',
        'Tomorrow morning, please.',
        a1,
      ],
      [
        'handoff',
        'route-question',
        'Who can you ask about a difficult customer question?',
        '选择请教对象。',
        'maya',
        'I can ask Maya.',
        'team',
        'I can ask in the team chat.',
        a1,
      ],
      [
        'check',
        'confirm-next-action',
        'What can you do after this introduction?',
        '自己能采取的下一步。',
        'read',
        'I can read the welcome guide.',
        'list',
        'I can write my questions down.',
        a1,
      ],
    ],
    a1,
  ),
  A2: workPack(
    scene,
    'A2',
    {
      canDoZh: '能说明固定职责、入职需要和方便协作的方式。',
      complexityZh:
        '从任务介绍连到学习资源与简单范围限制，区分个人安排和邀约。',
      scaffoldingZh: '已命名的团队资料与负责人支撑两三步交换。',
      registerZh: '常用礼貌请求与简短理由适用于初次同事交谈。',
    },
    [
      [
        'role',
        'introduce-role',
        'Which part of customer support do you handle?',
        '具体职责而非整个团队。',
        'chat',
        'I handle chats about new accounts.',
        'guide',
        'I update the instructions for new customers.',
        a2,
      ],
      [
        'focus',
        'name-focus',
        'What is your main aim for your first week?',
        '选入职目标。',
        'system',
        'I want to use the support system on my own.',
        'people',
        'I want to learn who handles each kind of question.',
        a2,
      ],
      [
        'contact',
        'choose-contact',
        'Which is easier for you, a chat message or an email?',
        '说出联系方式和用途。',
        'chat',
        'A chat message is easier for a quick question.',
        'email',
        'Email is better when there are several details.',
        a2,
      ],
      [
        'experience',
        'share-experience',
        'What experience are you bringing to this team?',
        '角色卡经历，不是用户履历。',
        'shop',
        'I helped customers in a small shop last year.',
        'project',
        'I wrote instructions for a college project.',
        a2,
      ],
      [
        'learn',
        'identify-learning',
        'Which part of the support process would you like someone to show you?',
        '提出想看的具体步骤。',
        'routing',
        'Could someone show me how to send a chat to another team?',
        'editing',
        'Could someone show me how to change a page in the guide?',
        a2,
      ],
      [
        'help',
        'request-help',
        'Would some help setting up your work calendar be useful?',
        '可以要求协助或自己处理。',
        'help-request',
        'Yes, could you help me add the team calendar?',
        'no',
        'No, thanks. I have already added it.',
        a2,
      ],
      [
        'boundary',
        'state-boundary',
        'Are you ready to deal with complaints alone?',
        '说明当前能力边界。',
        'simple',
        'I can handle simple complaints, but I need help with refunds.',
        'observe',
        'Not yet. I would like to watch a colleague first.',
        a2,
      ],
      [
        'name',
        'clarify-term',
        'What would help you understand the word queue on this sheet?',
        '围绕看到的词提需求。',
        'example',
        'An example of a chat queue would help.',
        'meaning',
        'Please tell me what the word means here.',
        a2,
      ],
      [
        'feedback',
        'invite-feedback',
        'Would you prefer feedback straight away or at the end of a task?',
        '选择反馈时机。',
        'now',
        'Straight away, so I can correct the next step.',
        'end',
        'At the end, so I can try the whole task first.',
        a2,
      ],
      [
        'meet',
        'propose-meeting',
        'Would you like to suggest a time for a short team introduction?',
        '邀约尚待对方接受。',
        'today-request',
        'Could we do it after lunch today?',
        'later-request',
        'Could we arrange it for tomorrow morning?',
        a2,
      ],
      [
        'handoff',
        'route-question',
        'If a customer asks about something outside your role, what can you do?',
        '选择转介方法。',
        'maya',
        'I can ask Maya who should answer.',
        'channel',
        'I can put the question in the team help channel.',
        a2,
      ],
      [
        'check',
        'confirm-next-action',
        'What would you like to prepare before your next team chat?',
        '准备材料不需别人先同意。',
        'questions',
        'I would like to make a short list of questions.',
        'summary',
        'I would like to write a short description of my tasks.',
        a2,
      ],
    ],
    a2,
  ),
  B1: workPack(
    scene,
    'B1',
    {
      canDoZh: '能联系经历与新职责，说明学习缺口及可执行的求助方式。',
      complexityZh: '解释原因并安排下一步，同时不替他人承诺。',
      scaffoldingZh: '固定团队与资料背景降低信息负担，需自述简短因果。',
      registerZh: '平实职业语气，允许坦承尚未掌握的内容。',
    },
    [
      [
        'role',
        'introduce-role',
        'How would you describe your contribution to the support team?',
        '说明自己做什么。',
        'chat',
        'I help new customers get started when they contact us by chat.',
        'guide',
        'I turn common customer questions into clearer guide pages.',
        b1,
      ],
      [
        'focus',
        'name-focus',
        'What would make your first month here feel successful?',
        '选择可观察的学习结果。',
        'independent',
        'I would like to handle routine cases without needing someone beside me.',
        'patterns',
        'I would like to spot the questions that our guide does not answer well.',
        b1,
      ],
      [
        'contact',
        'choose-contact',
        'How should a colleague reach you when a question needs some background?',
        '沟通方式配合信息量。',
        'email',
        'Email works well because I can read the history before replying.',
        'chat-link',
        'Send me a chat message with a link to the case, so I can see the context.',
        b1,
      ],
      [
        'experience',
        'share-experience',
        'Which earlier experience could help you settle into this role?',
        '提供虚构相关经历。',
        'shop',
        'Working in a busy shop taught me to ask what a customer actually needed.',
        'project',
        'Writing a student project guide taught me to test instructions with a new reader.',
        b1,
      ],
      [
        'learn',
        'identify-learning',
        'Where do you expect to need the most guidance at first?',
        '指出明确知识缺口。',
        'policy',
        'I will need guidance on exceptions because the standard instructions do not cover every case.',
        'tools',
        'I will need help finding older cases because the search tool is new to me.',
        b1,
      ],
      [
        'help',
        'request-help',
        'Would you like a colleague to sit with you for your first practice case?',
        '是否请求同伴协助。',
        'pair-request',
        'Yes, I would like someone to explain their choices as we go.',
        'no',
        'I would rather try a sample case first and bring back any questions.',
        b1,
      ],
      [
        'boundary',
        'state-boundary',
        'How will you handle a request that you do not have permission to approve?',
        '区分收集信息与批准。',
        'refer',
        'I will collect the details and refer the decision to Maya.',
        'check',
        'I will check the approval process before giving the customer an answer.',
        b1,
      ],
      [
        'name',
        'clarify-term',
        'The sheet calls some cases escalations. What would you like to clarify?',
        '词已在纸上，询问工作用法。',
        'criteria',
        'I would like to know when an ordinary case becomes an escalation.',
        'owner',
        'I would like to know who takes responsibility after a case is escalated.',
        b1,
      ],
      [
        'feedback',
        'invite-feedback',
        'What kind of feedback helps you improve without losing track of a task?',
        '说明反馈形式的理由。',
        'one-point',
        'One specific point at a time helps me make a change and see the result.',
        'review',
        'A short review at the end helps me connect the feedback to the whole task.',
        b1,
      ],
      [
        'meet',
        'propose-meeting',
        'How could you get to know colleagues without interrupting their busiest period?',
        '提议可协商而未确定的安排。',
        'invite',
        'I could suggest a short call after the morning chat rush.',
        'ask',
        'I could ask everyone to suggest a quiet time for an introduction.',
        b1,
      ],
      [
        'handoff',
        'route-question',
        'What information would you include when passing a question to another team?',
        '转交有用内容。',
        'history',
        'I would include what the customer needs and what we have already tried.',
        'decision',
        'I would explain which decision is needed and why our team cannot make it.',
        b1,
      ],
      [
        'check',
        'confirm-next-action',
        'How will you keep track of what you still need to learn?',
        '个人跟进行动。',
        'log',
        'I will keep a question log and group similar issues before asking for help.',
        'checklist',
        'I will use a checklist and mark the tasks I have only watched, not done myself.',
        b1,
      ],
    ],
    b1,
  ),
  B2: workPack(
    scene,
    'B2',
    {
      canDoZh: '能界定跨团队贡献与权限，商量反馈及交接方式。',
      complexityZh: '比较协作成本与信息完整性，说明经验的可迁移性。',
      scaffoldingZh: '仍有明确角色卡，但回答需支持立场并处理例外。',
      registerZh: '专业而开放，避免夸大个人影响或代表全组作承诺。',
    },
    [
      [
        'role',
        'introduce-role',
        'Where does your role fit between customer conversations and the welcome guide?',
        '说明贡献范围，不独占团队成果。',
        'frontline',
        'I work on the conversation side, identifying questions that the guide may need to address.',
        'documentation',
        'I focus on the guide, using the support team’s examples to make the instructions more useful.',
        b2,
      ],
      [
        'focus',
        'name-focus',
        'Which improvement would you prioritise while you are still learning how the team works?',
        '权衡早期贡献。',
        'small-fix',
        'I would start with a small, well-evidenced correction rather than redesigning the whole process.',
        'observe',
        'I would first compare several cases, because one frustrating exchange may not represent a wider problem.',
        b2,
      ],
      [
        'contact',
        'choose-contact',
        'How can colleagues give you enough context without creating another long meeting?',
        '协商异步沟通。',
        'brief',
        'A brief written summary with the decision needed would usually be enough.',
        'voice-note',
        'A short voice note could work, provided the case link and key names are also written down.',
        b2,
      ],
      [
        'experience',
        'share-experience',
        'What from your previous work transfers here, and what will you need to relearn?',
        '承认经验的适用限制。',
        'service',
        'I can bring experience of handling upset customers, but I need to learn this company’s approval limits.',
        'writing',
        'I know how to test instructions with readers, although I am still learning the product itself.',
        b2,
      ],
      [
        'learn',
        'identify-learning',
        'Which uncertainty about the team’s workflow would you resolve before taking on more work?',
        '识别承担工作前需澄清的点。',
        'priority',
        'I would clarify who sets priorities when a customer case and a guide update compete for time.',
        'review',
        'I would find out which changes require review, so I do not accidentally publish an unapproved edit.',
        b2,
      ],
      [
        'help',
        'request-help',
        'Would shadowing a colleague be the best use of your next training session?',
        '比较学习安排并可不请求。',
        'shadow-request',
        'Yes, especially if we can pause afterwards to discuss cases that were not straightforward.',
        'no',
        'I would get more from reviewing a recorded sample case, since I could stop and check the reasoning.',
        b2,
      ],
      [
        'boundary',
        'state-boundary',
        'How would you respond if someone introduced you as the owner of the entire support process?',
        '纠正职责扩大，可自己解释或请负责人说明。',
        'scope',
        'I would clarify that I contribute to support, while Maya remains responsible for the overall process.',
        'decision',
        'I would ask Maya to introduce the decision-makers, so colleagues know which requests need her approval.',
        b2,
      ],
      [
        'name',
        'clarify-term',
        'The role note uses the term case owner. Which distinction would you ask about?',
        '纸面术语的两种边界。',
        'followup',
        'Does ownership mean following the case through, even when another team provides the answer?',
        'authority',
        'Does the owner have authority to approve a solution, or only to coordinate it?',
        b2,
      ],
      [
        'feedback',
        'invite-feedback',
        'How would you invite candid feedback while keeping the discussion manageable?',
        '兼顾坦诚和可操作性。',
        'evidence',
        'I would ask for one example of where my wording caused confusion and work through that first.',
        'pattern',
        'I would ask which pattern matters most, rather than trying to correct every minor detail at once.',
        b2,
      ],
      [
        'meet',
        'propose-meeting',
        'What would make an introductory meeting worth taking colleagues away from customer work?',
        '用具体目的支持约谈提议。',
        'overlap',
        'I would propose a short session on where our responsibilities overlap, with general updates sent in advance.',
        'optional',
        'I would offer a few optional slots and focus each conversation on how we can help each other.',
        b2,
      ],
      [
        'handoff',
        'route-question',
        'How would you avoid a customer having to repeat their story after a handoff?',
        '提出交接策略而非已完成。',
        'summary',
        'I would attach a concise history and flag any details that still need confirmation.',
        'check',
        'I would ask the receiving colleague what information they need before transferring the case.',
        b2,
      ],
      [
        'check',
        'confirm-next-action',
        'What would you check with Maya before describing your role to the wider company?',
        '校准公开职责描述。',
        'limits',
        'I would check that my description makes the approval limits clear.',
        'routing',
        'I would check which requests should come directly to me and which belong in the shared queue.',
        b2,
      ],
    ],
    b2,
  ),
  C1: workPack(
    scene,
    'C1',
    {
      canDoZh: '能精确定位专业贡献、纠正过度归责，并处理跨团队隐含期待。',
      complexityZh:
        '把授权、协调和执行分开；通过具体情境处理信息负担与学习策略。',
      scaffoldingZh: '角色和任务固定，较少句型支架，需组织限定与委婉纠偏。',
      registerZh:
        '同事间自然且有分寸，不靠重复自我免责制造难度；依据CEFR而非BC的C1材料。',
    },
    [
      [
        'role',
        'introduce-role',
        'What should colleagues think of you as their first point of contact for?',
        '界定对口工作与转介价值。',
        'customer-patterns',
        'Bring me recurring difficulties from customer chats; I can help turn them into a clear problem for the right team to tackle.',
        'guide-clarity',
        'Come to me when the welcome guide is technically accurate but still hard to follow; that gap is where I can contribute most.',
        c1,
      ],
      [
        'focus',
        'name-focus',
        'Where would you look for an early contribution that does not depend on knowing the whole organisation?',
        '选择有限而有价值的切入点。',
        'friction',
        'I would trace one recurring point of confusion from the original chat to the guide, then propose a narrowly scoped improvement.',
        'handoffs',
        'I would look at cases that bounce between teams, since unclear handoffs may be easier to address than the underlying product issue.',
        c1,
      ],
      [
        'contact',
        'choose-contact',
        'How would you like people to approach you when urgency and complexity pull in different directions?',
        '按真实信息条件限定联系方式。',
        'alert-context',
        'A brief chat alert can flag the urgency, with the background in a linked note so we do not lose the detail.',
        'decision-first',
        'Lead with the decision that is needed and when; I can then judge whether a call will help more than a written exchange.',
        c1,
      ],
      [
        'experience',
        'share-experience',
        'Which part of your background is useful here without assuming this team works the same way?',
        '迁移经验而不套用旧流程。',
        'complaints',
        'Handling complaints taught me to separate the immediate frustration from the underlying need; I would still learn this team’s escalation practice before applying a familiar solution.',
        'testing',
        'Testing instructions with first-time users gave me a useful method, though I would want colleagues to challenge any assumptions I bring from the previous product.',
        c1,
      ],
      [
        'learn',
        'identify-learning',
        'What unwritten part of the workflow would you want to understand early on?',
        '处理隐含协作规则。',
        'exceptions',
        'I would ask how exceptions are discussed in practice, especially when the written process leaves two teams expecting the other to act.',
        'consultation',
        'I would want to know when a quick consultation is welcome and when people expect a fully worked-through proposal.',
        c1,
      ],
      [
        'help',
        'request-help',
        'How much support would be useful without turning your first assignment into someone else’s extra job?',
        '明确有界求助或独立尝试。',
        'checkpoint-request',
        'Could I agree a single checkpoint with a colleague after I have worked through a sample, rather than asking them to sit through every step?',
        'no',
        'I can start from a completed example and collect my questions; there is no need to reserve someone’s time before I know where I am stuck.',
        c1,
      ],
      [
        'boundary',
        'state-boundary',
        'A colleague says, “Great, you can sort out all our support bottlenecks.” How would you reset that expectation?',
        '已有具体虚构话语，可说明权限或缩小初始任务。',
        'scope',
        'I can certainly help identify where cases get stuck; changing responsibilities across teams would need Maya and the other leads involved.',
        'contribution',
        'Could we start with one recurring bottleneck? I can investigate it with the team, rather than promise to take on the whole process at once.',
        c1,
      ],
      [
        'name',
        'clarify-term',
        'The handover note says you will own a case end to end. What ambiguity would you clear up?',
        '把协调责任与权限区分。',
        'coordination',
        'I would check whether that means coordinating the response throughout, including stages where another team holds the decision.',
        'availability',
        'I would ask how cover works when I am unavailable, so end-to-end ownership does not quietly become an expectation of constant availability.',
        c1,
      ],
      [
        'feedback',
        'invite-feedback',
        'How would you make it easy for an experienced colleague to challenge your approach?',
        '降低对方提出异议的成本。',
        'assumptions',
        'I would explain the assumption behind my approach and ask where their experience suggests it might break down.',
        'alternative',
        'I would bring a concrete alternative alongside my preferred approach, so the conversation is about the work rather than defending my first idea.',
        c1,
      ],
      [
        'meet',
        'propose-meeting',
        'How would you introduce yourself to another team without making a vague request to pick their brains?',
        '提出范围明确的交流。',
        'case-request',
        'I would ask for fifteen minutes on a specific handoff that involves both teams and send the example beforehand.',
        'questions-first',
        'I would send two focused questions first and offer a call only if the answers would be easier to discuss.',
        c1,
      ],
      [
        'handoff',
        'route-question',
        'What would a good handoff preserve besides the factual history of a case?',
        '增加交接中的关系信息。',
        'expectations',
        'It should preserve what the customer has been led to expect, including any wording that could sound like a promise.',
        'uncertainty',
        'It should make unresolved points visible, so the next colleague does not mistake a working assumption for something the customer confirmed.',
        c1,
      ],
      [
        'check',
        'confirm-next-action',
        'How would you check that your introduction has not created a misleading picture of your remit?',
        '主动验证边界是否被理解。',
        'examples',
        'I would ask Maya to test the description against a couple of likely requests and identify anything that should be routed elsewhere.',
        'summary',
        'I would send a brief scope summary for correction, making the boundary between my contribution and the team’s authority explicit.',
        c1,
      ],
    ],
    c1,
  ),
}
