import { defineScenes, type SceneSeed } from '../factory'

const scenes = [
  {
    slug: 'airport-check-in',
    titleZh: '机场值机',
    titleEn: 'Airport check-in',
    summaryZh: '确认航班、托运行李，并选择合适座位。',
    learnerRole: '即将出发的旅客',
    aiRole: '耐心但需要核对信息的航空公司值机员',
    goalsZh: ['提供护照与目的地信息', '说明托运行李数量', '确认座位和登机口'],
    keywords: ['passport', 'flight', 'bag', 'aisle', 'boarding pass', 'connection'],
    expressions: {
      basic: ['Here is my passport.', 'I have one bag.'],
      standard: ['Could I have an aisle seat?', 'Is my bag checked through to London?'],
      advanced: ['Would it be possible to seat us together despite the late check-in?', 'Could you clarify whether the connection time is still realistic?'],
    },
    openings: {
      basic: 'Hello. Passport, please.',
      standard: 'Good morning. Where are you flying today?',
      advanced: 'I can check you in, though the flight is nearly full. How flexible are you about seating?',
    },
    imageAltZh: '明亮机场值机柜台与行李传送带',
  },
  {
    slug: 'security-screening',
    titleZh: '安检沟通',
    titleEn: 'Security screening',
    summaryZh: '理解安检指令，并解释随身物品。',
    learnerRole: '正在通过安检的旅客',
    aiRole: '简洁、程序化的机场安检员',
    goalsZh: ['确认需要取出的物品', '解释液体或电子设备', '理解二次检查安排'],
    keywords: ['laptop', 'liquid', 'tray', 'remove', 'screening', 'inspection'],
    expressions: {
      basic: ['Should I take this out?', 'This is my medicine.'],
      standard: ['Do I need to remove my shoes?', 'The bottle is under one hundred milliliters.'],
      advanced: ['Could you explain what triggered the additional screening?', 'I am happy to cooperate; I just need the medication handled carefully.'],
    },
    openings: {
      basic: 'Laptop out, please.',
      standard: 'Please place electronics and liquids in separate trays.',
      advanced: 'Your bag needs a secondary inspection. Is there anything fragile or medically necessary inside?',
    },
    imageAltZh: '机场安检通道和托盘',
  },
  {
    slug: 'flight-connection',
    titleZh: '转机问询',
    titleEn: 'Flight connection',
    summaryZh: '在时间紧张时确认登机口与转机方案。',
    learnerRole: '担心错过下一程航班的旅客',
    aiRole: '机场转机服务台工作人员',
    goalsZh: ['说明下一程航班', '确认最快路线', '讨论错过航班的替代方案'],
    keywords: ['connection', 'gate', 'delay', 'terminal', 'rebook', 'transfer'],
    expressions: {
      basic: ['Where is gate B12?', 'My flight is delayed.'],
      standard: ['Can I still make my connection?', 'What is the fastest way to Terminal Two?'],
      advanced: ['If the connection becomes impossible, what rebooking options would minimize the delay?', 'Could you note that the inbound delay was caused by the airline?'],
    },
    openings: {
      basic: 'Which gate do you need?',
      standard: 'Let me check your connection time and terminal.',
      advanced: 'You have a tight connection and a terminal change. What is your onward flight number?',
    },
    imageAltZh: '机场航班信息屏与转机指示牌',
  },
  {
    slug: 'immigration-interview',
    titleZh: '入境问答',
    titleEn: 'Immigration questions',
    summaryZh: '清晰说明旅行目的、停留时间和住宿安排。',
    learnerRole: '抵达目的地并接受入境问询的旅客',
    aiRole: '正式、直接的入境官员',
    goalsZh: ['说明来访目的', '确认停留时长', '提供住宿与返程信息'],
    keywords: ['purpose', 'stay', 'hotel', 'return ticket', 'address', 'business'],
    expressions: {
      basic: ['I am here for a holiday.', 'I will stay for seven days.'],
      standard: ['I am attending a three-day conference.', 'I have a return flight next Friday.'],
      advanced: ['The primary purpose is business, with two personal days added afterward.', 'I can provide the invitation letter and the full accommodation itinerary.'],
    },
    openings: {
      basic: 'Why are you visiting?',
      standard: 'What is the purpose and length of your stay?',
      advanced: 'Your itinerary combines business and leisure. Please explain the arrangements and who is covering the expenses.',
    },
    imageAltZh: '国际入境检查柜台',
  },
  {
    slug: 'hotel-check-in',
    titleZh: '酒店入住',
    titleEn: 'Hotel check-in',
    summaryZh: '核对预订、提出房间偏好，并确认早餐信息。',
    learnerRole: '办理入住的酒店客人',
    aiRole: '专业、友好的酒店前台接待员',
    goalsZh: ['报出预订姓名', '确认房型与入住时长', '询问早餐和退房时间'],
    keywords: ['reservation', 'passport', 'room', 'breakfast', 'checkout', 'deposit'],
    expressions: {
      basic: ['I have a reservation.', 'The name is Li.'],
      standard: ['I have a reservation under the name Li.', 'Could you tell me when breakfast is served?'],
      advanced: ['The booking notes a quiet room; could you confirm whether that request was accommodated?', 'Before I authorize the deposit, could you clarify the incidental-hold policy?'],
    },
    openings: {
      basic: 'Welcome. Your name, please?',
      standard: 'Good evening. Do you have a reservation with us?',
      advanced: 'Welcome. I found the reservation, though the requested room type is limited tonight. How would you like to proceed?',
    },
    imageAltZh: '温暖灯光下的精品酒店前台',
  },
  {
    slug: 'hotel-room-problem',
    titleZh: '房间问题',
    titleEn: 'Hotel room problem',
    summaryZh: '礼貌描述设施问题并协商解决方案。',
    learnerRole: '遇到房间问题的酒店客人',
    aiRole: '需要核实情况的酒店值班经理',
    goalsZh: ['准确描述问题', '说明问题造成的影响', '协商维修或换房方案'],
    keywords: ['air conditioning', 'noise', 'repair', 'change rooms', 'inconvenience', 'resolve'],
    expressions: {
      basic: ['The room is too noisy.', 'The air conditioning is broken.'],
      standard: ['Could someone take a look at it?', 'Would another room be available tonight?'],
      advanced: ['The ongoing noise makes the room unusable for work; what comparable alternatives can you offer?', 'I appreciate the constraints, but a repair tomorrow would not address tonight’s disruption.'],
    },
    openings: {
      basic: 'How can I help?',
      standard: 'I am sorry to hear there is a problem. What seems to be wrong?',
      advanced: 'I understand you have raised a room concern. Could you describe both the issue and the outcome you are seeking?',
    },
    imageAltZh: '酒店客房与服务电话',
  },
] satisfies readonly SceneSeed[]

export const TRAVEL_SCENES = defineScenes('travel', 'travel', scenes)
