import { dailyPack, type DailyScene, type Review } from './authoring'

const a1: Review = {
  state: 'model-reviewed',
  record:
    'daily-review.md#fix1: directions A1 all 12 Q/24 A and both corrected variants reread by Codex implementation agent, 2026-09-10',
}
const a2: Review = {
  state: 'model-reviewed',
  record:
    'daily-review.md#fix1: directions A2 all 12 Q/24 A and both corrected variants reread by Codex implementation agent, 2026-09-10',
}
const b1: Review = {
  state: 'model-reviewed',
  record:
    'daily-review.md#fix1: directions B1 all 12 Q/24 A and both corrected variants reread by Codex implementation agent, 2026-09-10',
}
const b2: Review = {
  state: 'model-reviewed',
  record:
    'daily-review.md#fix1: directions B2 all 12 Q/24 A and both corrected variants reread by Codex implementation agent, 2026-09-10',
}
const c1: Review = {
  state: 'model-reviewed',
  record:
    'daily-review.md#fix1: directions C1 all 12 Q/24 A and both corrected variants reread by Codex implementation agent, 2026-09-10',
}
const scene: DailyScene = {
  sceneId: 'daily-01',
  slug: 'ask-directions',
  situations: [
    '虚构Oak Square游客咨询点。你步行去图书馆或博物馆；两者均在河对岸，地图上经过面包店与桥。楼梯捷径和沿河无台阶路线都在讨论中，尚未选定。你有纸质地图，可选择拍照或抄写路线。开场前，工作人员已指着地图上的两条街名，连着读过一遍：“Mill Road, Hill Road.”你听到了这两个相近的名字，但连读时不容易区分；这只是读出图上标签，还没有说明该走哪条路。工作人员接下来先了解你的需要；短练只确定目的地、路线条件和指引方式，不假装已给出完整导航。',
    '虚构Oak Square信息台，你在提前规划明天去河对岸图书馆或博物馆的步行路线；桥与面包店已在纸图上标出。开场前，工作人员已指着地图上的两条街名，连着读过一遍：“Mill Road, Hill Road.”你听到了这两个相近的名字，但连读时不容易区分；这只是读出图上标签，还没有说明该走哪条路。你特别需要核对过桥之后的走法和问路备选方式。楼梯捷径与沿河无台阶路线均未选定；时间和天气都未保证。不是实时地图或真实通行建议。',
  ],
  paths: [
    {
      short: ['destination', 'access', 'format'],
      standard: [
        'destination',
        'access',
        'format',
        'landmark',
        'pace',
        'crossing',
      ],
      extended: [
        'destination',
        'access',
        'format',
        'landmark',
        'pace',
        'crossing',
        'repeat',
        'time',
        'record',
        'weather',
      ],
    },
    {
      short: ['destination', 'format', 'access'],
      standard: [
        'destination',
        'format',
        'access',
        'landmark',
        'pace',
        'crossing',
      ],
      extended: [
        'destination',
        'format',
        'access',
        'landmark',
        'pace',
        'crossing',
        'repeat',
        'time',
        'after-bridge',
        'backup',
      ],
    },
  ],
  closing:
    'Your route questions and preferences are recorded for this practice. No complete route or current street conditions have been verified.',
  partial:
    'This route-planning practice is partly complete. Details you have not confirmed remain open.',
  repairs: {
    clarify: 'I can repeat this route question.',
    struggle: 'You can name one place or one preference.',
    offTopic: 'Let us return to the route detail on screen.',
    unknown:
      'That wording is not covered here; I have not confirmed a route from it.',
    changed: 'Your earlier route preference is replaced in this practice.',
    refusedClosing:
      'We will stop the directions practice here. No journey has been made.',
  },
}
export const directionsPacks = {
  A1: dailyPack(
    scene,
    'A1',
    {
      canDoZh: '在图示和二选一帮助下说目的地、台阶需求和指路方式。',
      complexityZh: '每次只处理一个地点或动作，拓展增加时间和记录。',
      scaffoldingZh: '固定广场、桥、面包店与纸图提供具体支架，可重复。',
      registerZh: '短句与please构成友好的问路交流。',
    },
    [
      [
        'destination',
        'name-place',
        'Where do you want to go?',
        '选图书馆或博物馆。',
        'library',
        'The library, please.',
        'museum',
        'The museum, please.',
        a1,
      ],
      [
        'access',
        'set-access',
        'Are steps OK for you?',
        '说明能否走台阶。',
        'step-free',
        'No steps, please.',
        'steps-ok',
        'Steps are OK.',
        a1,
      ],
      [
        'format',
        'request-format',
        'Would you like a map or spoken directions?',
        '选纸图或口头指路。',
        'map',
        'A map, please.',
        'spoken',
        'Please tell me the way.',
        a1,
      ],
      [
        'landmark',
        'locate-landmark',
        'Can you see the bakery on this map?',
        '面包店已在图上。',
        'seen',
        'Yes, I can see it.',
        'help',
        'No. Please point to it.',
        a1,
      ],
      [
        'pace',
        'control-pace',
        'Shall I speak slowly?',
        '选择讲解速度。',
        'slow',
        'Yes, slowly, please.',
        'normal',
        'No, normal speed is fine.',
        a1,
      ],
      [
        'crossing',
        'ask-crossing',
        'Do you need help finding the crossing?',
        '需要人行过街点信息吗。',
        'help',
        'Yes. Where can I cross?',
        'no-help',
        'No, thank you.',
        a1,
      ],
      [
        'repeat',
        'repair-hearing',
        'Should I repeat the street names?',
        '选择重复或拼写。',
        'repeat',
        'Yes, please repeat them.',
        'spell',
        'Please spell them.',
        a1,
      ],
      [
        'time',
        'ask-duration',
        'Do you want to know the walking time?',
        '可询问时间或暂不需要。',
        'ask',
        'Yes. How long is the walk?',
        'no',
        'No, thank you.',
        a1,
      ],
      [
        'record',
        'keep-directions',
        'Would you like to photograph the map or copy the route?',
        '选记录方法。',
        'photo',
        'A photo, please.',
        'copy',
        'I will copy the route.',
        a1,
      ],
      [
        'weather',
        'consider-weather',
        'Would you like to ask about places to shelter?',
        '不保证天气。',
        'ask',
        'Yes. Is there a place to shelter?',
        'no',
        'No, thanks. I have a coat.',
        a1,
      ],
      [
        'after-bridge',
        'clarify-section',
        'Which part after the bridge needs explaining?',
        '两处都在尚待说明的路线内。',
        'turn',
        'The first turn, please.',
        'entrance',
        'The entrance, please.',
        a1,
      ],
      [
        'backup',
        'plan-help',
        'If you get lost, would you ask someone or look at the map?',
        '表达备用方法。',
        'ask',
        'I would ask someone.',
        'map',
        'I would look at the map.',
        a1,
      ],
    ],
    a1,
  ),
  A2: dailyPack(
    scene,
    'A2',
    {
      canDoZh: '说明步行限制并安排几步可预测的问路交换。',
      complexityZh: '联系路线方式与简单理由，核对地标和后半段路线。',
      scaffoldingZh: '地图与明确选项支持先后步骤，回答可用because。',
      registerZh: '日常礼貌请求，允许说不懂或不需要。',
    },
    [
      [
        'destination',
        'name-place',
        'Which building are you looking for across the river?',
        '河对岸两个候选建筑。',
        'library',
        'I am looking for the library.',
        'museum',
        'I want to find the museum.',
        a2,
      ],
      [
        'access',
        'set-access',
        'Do you need a route without steps?',
        '路线未选；说明限制。',
        'step-free',
        'Yes, because I have a heavy bag.',
        'steps-ok',
        'No, I can use the steps.',
        a2,
      ],
      [
        'format',
        'request-format',
        'How would you like me to explain the way?',
        '选择讲解形式。',
        'map',
        'Could you mark it on the map?',
        'spoken',
        'Could you explain it aloud?',
        a2,
      ],
      [
        'landmark',
        'locate-landmark',
        'Is the bakery easy to find on the paper map?',
        '可直接表示识别困难。',
        'seen',
        'Yes, it is next to the bridge on the map.',
        'help',
        'Not for me. Could you show me the symbol?',
        a2,
      ],
      [
        'pace',
        'control-pace',
        'Would a slower explanation help?',
        '独立于是否用纸图。',
        'slow',
        'Yes, please leave a pause between steps.',
        'normal',
        'No, that speed is comfortable.',
        a2,
      ],
      [
        'crossing',
        'ask-crossing',
        'Would you like information about crossing the road?',
        '不预设实际过街许可。',
        'help',
        'Yes, please show me the crossing point.',
        'no-help',
        'No, I can find the crossing on the map.',
        a2,
      ],
      [
        'repeat',
        'repair-hearing',
        'How can I help with the street names?',
        '重复或写出来。',
        'repeat',
        'Please say each name twice.',
        'spell',
        'Please spell the names for me.',
        a2,
      ],
      [
        'time',
        'ask-duration',
        'Is an approximate walking time useful?',
        '时间只是待询问估计。',
        'ask',
        'Yes, I want to know how long to allow.',
        'no',
        'No, I do not need a time estimate.',
        a2,
      ],
      [
        'record',
        'keep-directions',
        'How will you keep the route details?',
        '不声称路线已讲完。',
        'photo',
        'I would like to take a photo of the map.',
        'copy',
        'I will copy the route into my notebook.',
        a2,
      ],
      [
        'weather',
        'consider-weather',
        'Do you want to check where you could shelter from rain?',
        '新增沿途需要。',
        'ask',
        'Yes, I would like to know about a covered place.',
        'no',
        'No, I have a raincoat with me.',
        a2,
      ],
      [
        'after-bridge',
        'clarify-section',
        'What would you like explained after the bridge?',
        '指定尚未清楚的部分。',
        'turn',
        'Please explain the first turn after the bridge.',
        'entrance',
        'Please explain how to find the entrance.',
        a2,
      ],
      [
        'backup',
        'plan-help',
        'What would you do if you could not find the next street?',
        '用would表达备用行动。',
        'ask',
        'I would ask someone nearby for help.',
        'map',
        'I would stop and check the paper map.',
        a2,
      ],
    ],
    a2,
  ),
  B1: dailyPack(
    scene,
    'B1',
    {
      canDoZh: '处理不熟悉路线，说明负担并定位信息缺口。',
      complexityZh: '以原因连接路线限制、理解方式和备用安排。',
      scaffoldingZh: '地点固定但不提供整条答案路线；允许具体澄清。',
      registerZh: '自然咨询语气，用could和would协商协助。',
    },
    [
      [
        'destination',
        'name-place',
        'Which place across the river would you like directions to?',
        '说明目的地和目的。',
        'library',
        'The library; I need somewhere to read quietly.',
        'museum',
        'The museum; I would like to see the local exhibition.',
        b1,
      ],
      [
        'access',
        'set-access',
        'Should I rule out routes with steps?',
        '不暗示已选具体路线。',
        'step-free',
        'Yes, carrying my bag up steps would be difficult.',
        'steps-ok',
        'No, steps are fine if they make the walk shorter.',
        b1,
      ],
      [
        'format',
        'request-format',
        'What sort of directions would be easiest for you to follow?',
        '选择具体支架。',
        'map',
        'Please mark the turns on the paper map so I can check them.',
        'spoken',
        'Please explain the turns aloud; I remember spoken directions better.',
        b1,
      ],
      [
        'landmark',
        'locate-landmark',
        'Can you identify the bakery as a reference point?',
        '只核对地图识别。',
        'seen',
        'Yes, I can find it beside the bridge symbol.',
        'help',
        'Not yet; I am not sure which symbol is the bakery.',
        b1,
      ],
      [
        'pace',
        'control-pace',
        'How should I pace the explanation?',
        '安排讲解节奏。',
        'slow',
        'Please pause after each stage so I can follow it.',
        'normal',
        'Your usual pace is fine; I will ask if I miss anything.',
        b1,
      ],
      [
        'crossing',
        'ask-crossing',
        'Is there anything you need to check about crossing the road?',
        '可询问或不另提请求。',
        'help',
        'Yes, I would like the location of the pedestrian crossing.',
        'no-help',
        'No, I can identify the crossing on this map.',
        b1,
      ],
      [
        'repeat',
        'repair-hearing',
        'What would help you distinguish the street names?',
        '区分重听与拼写。',
        'repeat',
        'Hearing the names separately would help me remember them.',
        'spell',
        'Please spell them, as two of the names sound similar to me.',
        b1,
      ],
      [
        'time',
        'ask-duration',
        'Would an estimate of the walking time help you plan?',
        '不与速度选择冲突。',
        'ask',
        'Yes, I want to allow enough time without rushing.',
        'no',
        'No, my schedule is open, so the route itself matters more.',
        b1,
      ],
      [
        'record',
        'keep-directions',
        'How would you prefer to save the route information?',
        '路线说明仍可未完成。',
        'photo',
        'I would photograph the marked map so I have it with me.',
        'copy',
        'I would copy the key turns into my notebook.',
        b1,
      ],
      [
        'weather',
        'consider-weather',
        'Would you like to include a question about shelter along the way?',
        '不假设真的下雨。',
        'ask',
        'Yes, I would like to know where I could stop if it rains.',
        'no',
        'No, I have suitable clothing and do not need that information.',
        b1,
      ],
      [
        'after-bridge',
        'clarify-section',
        'Which part of the route beyond the bridge needs more detail?',
        '聚焦信息缺口。',
        'turn',
        'The first turn after the bridge, because the roads look close together.',
        'entrance',
        'The final entrance, because the building seems to cover a large area.',
        b1,
      ],
      [
        'backup',
        'plan-help',
        'How would you recover if you lost track of the route?',
        '不要假称当前迷路。',
        'ask',
        'I would ask a local person to point out my location.',
        'map',
        'I would stop somewhere safe and work out my position on the map.',
        b1,
      ],
    ],
    b1,
  ),
  B2: dailyPack(
    scene,
    'B2',
    {
      canDoZh: '权衡可达性、信息负担与时间，并提出针对性澄清。',
      complexityZh: '说明优先级而不假定更改已被接受，规划不确定情况。',
      scaffoldingZh: '共享地图提供事实；学习者组织限制及具体理由。',
      registerZh: '有分寸的公共服务交流，清楚表达条件而不过分正式。',
    },
    [
      [
        'destination',
        'name-place',
        'Which destination should we use as the endpoint of your route enquiry?',
        '保持终点唯一。',
        'library',
        'The library; access to its reading room is the main purpose of the visit.',
        'museum',
        'The museum; I want to reach the exhibition entrance rather than just the grounds.',
        b2,
      ],
      [
        'access',
        'set-access',
        'How should we balance a shorter walk against avoiding steps?',
        '说明优先级。',
        'step-free',
        'Avoiding steps comes first; I would accept a longer walk to keep the route step-free.',
        'steps-ok',
        'A shorter walk would suit me, and I have no difficulty using steps.',
        b2,
      ],
      [
        'format',
        'request-format',
        'What would make the directions practical to use once you leave here?',
        '选择信息呈现。',
        'map',
        'A clearly marked map would let me check each turn without relying on memory.',
        'spoken',
        'A spoken explanation would work best if the turns were grouped into a few clear stages.',
        b2,
      ],
      [
        'landmark',
        'locate-landmark',
        'Is the bakery a clear enough reference point on your copy of the map?',
        '不编造街上视野。',
        'seen',
        'Yes, the label and bridge symbol make its position clear.',
        'help',
        'Not quite; the print is small, so please point out the exact building.',
        b2,
      ],
      [
        'pace',
        'control-pace',
        'Would you prefer a continuous explanation or pauses between sections?',
        '控制互动节奏。',
        'slow',
        'Pauses would help me check each section before you move on.',
        'normal',
        'A continuous explanation is fine; I can raise specific questions at the end.',
        b2,
      ],
      [
        'crossing',
        'ask-crossing',
        'Do you need any crossing information beyond what the map shows?',
        '有请求和无请求都成立。',
        'help',
        'Yes, I would like you to identify the pedestrian crossing, as the junction looks complicated.',
        'no-help',
        'No, the marked crossing is clear enough for this planning exercise.',
        b2,
      ],
      [
        'repeat',
        'repair-hearing',
        'How could we make the street names less easy to confuse?',
        '选择声音或字形。',
        'repeat',
        'Please repeat each name with a brief pause; hearing them together makes them harder to distinguish.',
        'spell',
        'Please spell them so I can match each one to the printed label.',
        b2,
      ],
      [
        'time',
        'ask-duration',
        'How much detail about walking time would be useful?',
        '可拒绝非必需估计。',
        'ask',
        'An approximate range would help; a single precise number might give me the wrong expectation.',
        'no',
        'I do not need a time estimate; I would rather focus on navigating the junctions.',
        b2,
      ],
      [
        'record',
        'keep-directions',
        'Which record of the route would be most useful to you?',
        '保存方式不承诺已经完成。',
        'photo',
        'A photograph of the marked map would preserve the relationship between the landmarks.',
        'copy',
        'My own notes would be easier to scan, provided I include the main turns.',
        b2,
      ],
      [
        'weather',
        'consider-weather',
        'Should we also discuss options for shelter along the route?',
        '独立可选需求。',
        'ask',
        'Yes, a possible sheltered stop would help me plan for a change in the weather.',
        'no',
        'No, weather protection is not part of my enquiry; I have what I need with me.',
        b2,
      ],
      [
        'after-bridge',
        'clarify-section',
        'Where would a more detailed explanation be most valuable beyond the bridge?',
        '避免再次询问终点。',
        'turn',
        'At the first junction, where the close spacing of the roads could make the turn ambiguous.',
        'entrance',
        'At the destination entrance, since reaching the building may not mean finding the right way in.',
        b2,
      ],
      [
        'backup',
        'plan-help',
        'What would be your preferred fallback if the route became unclear?',
        '未来条件安排。',
        'ask',
        'I would ask someone to identify a nearby landmark before trying to continue.',
        'map',
        'I would retrace my position on the paper map rather than guess at the next turn.',
        b2,
      ],
    ],
    b2,
  ),
  C1: dailyPack(
    scene,
    'C1',
    {
      canDoZh: '精确界定路线咨询范围，调节信息密度并处理地标歧义。',
      complexityZh: '权衡可操作性和不确定性；能纠正隐含假设而保持合作。',
      scaffoldingZh: '共享虚构地图，不给套用长句；需要解释具体信息优先级。',
      registerZh:
        '自然细致的咨询语域，使用条件、对比和适当限定；据CEFR而非BC Speaking。',
    },
    [
      [
        'destination',
        'name-place',
        'To avoid planning towards the wrong endpoint, which building do you mean?',
        '明确终点，不沿用含混there。',
        'library',
        'The library, specifically its public entrance; I am going there to use the reading room.',
        'museum',
        'The museum, specifically the exhibition entrance rather than the service entrance.',
        c1,
      ],
      [
        'access',
        'set-access',
        'What should take priority if the step-free route is noticeably longer?',
        '明确可达性与距离的取舍。',
        'step-free',
        'Keep it step-free, even if that adds some distance; negotiating steps with my bag is the greater difficulty.',
        'steps-ok',
        'I would favour the shorter route; steps themselves are not a restriction for me.',
        c1,
      ],
      [
        'format',
        'request-format',
        'How could I present the route so that the important details are easy to recover later?',
        '信息组织有真实原因。',
        'map',
        'Mark the decisive turns on the map; too many minor landmarks would make the useful ones harder to pick out.',
        'spoken',
        'Talk me through a few distinct stages, using a clear landmark to signal the end of each one.',
        c1,
      ],
      [
        'landmark',
        'locate-landmark',
        'Does the bakery label identify one building clearly enough on your map?',
        '识别歧义来自地图而非编造路线。',
        'seen',
        'Yes, its position beside the bridge is distinct enough for me to use it as a reference.',
        'help',
        'Not quite; the label overlaps another symbol, so I would appreciate you indicating the building itself.',
        c1,
      ],
      [
        'pace',
        'control-pace',
        'Would you rather check each section as we go, or hear the overall explanation first?',
        '选择互动深度和时机。',
        'slow',
        'Let us check each section as we go; that would prevent a small misunderstanding carrying through the rest.',
        'normal',
        'Please give me the overall explanation first, and I will come back to any points that need unpacking.',
        c1,
      ],
      [
        'crossing',
        'ask-crossing',
        'Is there a particular uncertainty about road crossings that you would like to address?',
        '可具体询问，也可明确无额外请求。',
        'help',
        'Yes, please distinguish the pedestrian crossing from the nearby junction; the two markings are close together.',
        'no-help',
        'No, the crossing symbols are clear to me; I do not need further detail on that part.',
        c1,
      ],
      [
        'repeat',
        'repair-hearing',
        'What would resolve the potential confusion between the street names?',
        '说明修复策略。',
        'repeat',
        'Say them separately, with a pause between them; it is the way they run together that I find confusing.',
        'spell',
        'Spelling them would be more useful than repeating them, because I need to match them to the labels.',
        c1,
      ],
      [
        'time',
        'ask-duration',
        'Would a rough walking-time range inform your planning, or distract from the route details?',
        '不反复防御性声明。',
        'ask',
        'A range would be useful, particularly if you could say whether it allows for a leisurely pace.',
        'no',
        'I can leave the timing open; I would rather use our time to clarify the less obvious turns.',
        c1,
      ],
      [
        'record',
        'keep-directions',
        'What would be the most reliable way for you to retain the directions?',
        '解释选择的使用场景。',
        'photo',
        'I would photograph the marked map, making sure the labels remain legible when I enlarge it.',
        'copy',
        'I would make concise notes, keeping the order of the turns explicit rather than recording every detail.',
        c1,
      ],
      [
        'weather',
        'consider-weather',
        'Would identifying potential shelter add anything useful to your route enquiry?',
        '不将拒绝当待办。',
        'ask',
        'Yes, knowing where I might pause under cover would help if the weather changes while I am walking.',
        'no',
        'No, I am prepared for rain and would prefer to keep the enquiry focused on finding my way.',
        c1,
      ],
      [
        'after-bridge',
        'clarify-section',
        'Which detail beyond the bridge is most likely to cause uncertainty?',
        '聚焦复杂节点。',
        'turn',
        'The first junction: I need to distinguish the intended turn from the road immediately before it.',
        'entrance',
        'The final approach: I would like a feature that distinguishes the public entrance from the other doors.',
        c1,
      ],
      [
        'backup',
        'plan-help',
        'If the landmarks stopped matching your expectations, how would you re-establish your position?',
        '条件性而非已迷路。',
        'ask',
        'I would ask someone to identify the street I was on before requesting any further directions.',
        'map',
        'I would stop and compare the last unmistakable landmark with the map instead of pressing on uncertainly.',
        c1,
      ],
    ],
    c1,
  ),
}
