import { dailyPack, type DailyScene, type Review } from './authoring'
const a1: Review = {
  state: 'model-reviewed',
  record:
    'daily-review.md#bank-a1: all 12 named Q/A pairs and both variants read and contact/privacy corrections reread by Codex implementation agent, 2026-09-10',
}
const a2: Review = {
  state: 'model-reviewed',
  record:
    'daily-review.md#bank-a2: all 12 named Q/A pairs and both variants read and contact/privacy corrections reread by Codex implementation agent, 2026-09-10',
}
const b1: Review = {
  state: 'model-reviewed',
  record:
    'daily-review.md#bank-b1: all 12 named Q/A pairs and both variants read and contact/privacy corrections reread by Codex implementation agent, 2026-09-10',
}
const b2: Review = {
  state: 'model-reviewed',
  record:
    'daily-review.md#bank-b2: all 12 named Q/A pairs and both variants read and contact/privacy corrections reread by Codex implementation agent, 2026-09-10',
}
const c1: Review = {
  state: 'model-reviewed',
  record:
    'daily-review.md#bank-c1: all 12 named Q/A pairs and both variants read and contact/privacy corrections reread by Codex implementation agent, 2026-09-10',
}
const scene: DailyScene = {
  sceneId: 'daily-03',
  slug: 'bank-card-problem',
  situations: [
    '虚构银行服务柜台沟通演练，使用标为SAMPLE的道具卡和不含任何个人资料的练习说明页。可选昨天下午商店刷卡被拒或ATM未退卡；两种情况都未确定原因，尚未安排后续帮助。本练习不办理挂失、转账或解锁，不提供金融建议。禁止提供真实姓名、账号、卡号、密码、验证码或证件；所有标识、金额和联系人均不需要。短练只说明问题、地点类型和是否曾发生类似问题。',
    '虚构银行电话服务演练，使用SAMPLE道具卡和不含个人资料的练习说明页，没有真实账户。候选问题为商店支付被拒或ATM未退卡，都发生在昨天下午，原因未知，尚未安排后续帮助。你需要先问安全沟通方式和可用帮助渠道，再考虑后续询问。任何电话或窗口仅作为练习中的渠道名称，不能要求真实电话号码、证件、卡号、密码或验证码；没有真实银行操作。',
  ],
  paths: [
    {
      short: ['problem', 'place', 'time'],
      standard: ['problem', 'place', 'time', 'message', 'attempts', 'priority'],
      extended: [
        'problem',
        'place',
        'time',
        'message',
        'attempts',
        'priority',
        'privacy',
        'explanation',
        'summary',
        'followup',
      ],
    },
    {
      short: ['problem', 'place', 'time'],
      standard: ['problem', 'place', 'time', 'privacy', 'channel', 'priority'],
      extended: [
        'problem',
        'place',
        'time',
        'privacy',
        'channel',
        'priority',
        'message',
        'attempts',
        'access',
        'followup',
      ],
    },
  ],
  closing:
    'This banking conversation practice is complete. No account has been accessed, no card action has been taken, and the cause remains undetermined.',
  partial:
    'We have practised only part of the card enquiry. Unconfirmed details remain open; no banking action has occurred.',
  repairs: {
    clarify:
      'I can repeat this fictional card-service question. No real identifiers are needed.',
    struggle: 'A short description of the practice problem is enough.',
    offTopic: 'Let us return to the fictional card enquiry.',
    unknown:
      'That wording is not covered. No account detail or cause has been inferred.',
    changed:
      'Your earlier description has been replaced within this fictional practice.',
    refusedClosing:
      'The banking practice has stopped. No account or card has been changed.',
  },
}
export const bankPacks = {
  A1: dailyPack(
    scene,
    'A1',
    {
      canDoZh: '用简单句说卡片问题、地点类型与时间。',
      complexityZh: '逐项描述观察，不推断原因；拓展选择帮助形式。',
      scaffoldingZh: '道具卡与虚构事件支持安全回答，不用真实标识。',
      registerZh: '基础柜台语言，允许拒绝提供信息或说不懂。',
    },
    [
      [
        'problem',
        'describe-problem',
        'What is the problem with the sample card?',
        '两种虚构问题选一。',
        'declined',
        'The payment was declined.',
        'retained',
        'The ATM kept the card.',
        a1,
      ],
      [
        'place',
        'locate-event',
        'Was this indoors or outside?',
        '只问地点类型，不问地址。',
        'inside',
        'It was indoors.',
        'outside',
        'It was outside.',
        a1,
      ],
      [
        'time',
        'state-time',
        'Was yesterday afternoon the first time?',
        '虚构事件时间固定。',
        'first',
        'Yes, the first time.',
        'before',
        'No, it happened before.',
        a1,
      ],
      [
        'message',
        'report-message',
        'Was there a message on the screen?',
        '观察而非原因。',
        'message',
        'Yes, there was a message.',
        'none',
        'No, there was no message.',
        a1,
      ],
      [
        'attempts',
        'report-contact',
        'Did you ask a staff member for help then?',
        '此前是否求助；不假设能再使用被留卡片。',
        'no',
        'No, I did not ask.',
        'unsure',
        'I am not sure.',
        a1,
      ],
      [
        'priority',
        'set-priority',
        'What help do you want first?',
        '两种后续询问。',
        'explain',
        'Please explain the problem.',
        'options',
        'Please explain my options.',
        a1,
      ],
      [
        'privacy',
        'protect-information',
        'Do you need the privacy rule explained again?',
        '所有情况只用道具资料。',
        'sample',
        'No, sample details only. I understand.',
        'explain',
        'Yes, please explain it again.',
        a1,
      ],
      [
        'explanation',
        'request-clarity',
        'Would you like simple words or a written explanation?',
        '理解方式不同。',
        'simple',
        'Simple words, please.',
        'written',
        'A written explanation, please.',
        a1,
      ],
      [
        'summary',
        'request-summary',
        'Would a short summary help?',
        '不假装问题已处理。',
        'yes',
        'Yes, a short summary, please.',
        'no',
        'No summary, thanks.',
        a1,
      ],
      [
        'followup',
        'plan-next-step',
        'What would you like to ask about next?',
        '只提出下一步询问。',
        'time',
        'How long might this take?',
        'contact',
        'Where can I ask for more help?',
        a1,
      ],
      [
        'channel',
        'choose-channel',
        'Would you prefer help at a desk or by phone?',
        '不用真实联系方式。',
        'desk',
        'At a desk, please.',
        'phone',
        'By phone, please.',
        a1,
      ],
      [
        'access',
        'request-access',
        'Would you like more time to read the information?',
        '可拒绝额外时间。',
        'time',
        'Yes, more time, please.',
        'ready',
        'No, I can read it now.',
        a1,
      ],
    ],
    a1,
  ),
  A2: dailyPack(
    scene,
    'A2',
    {
      canDoZh: '顺序描述卡片事件，并提出直接的解释请求。',
      complexityZh: '区分观察、重复发生和后续渠道，不判断账户状态。',
      scaffoldingZh: '虚构时间和道具卡固定，给短句支架。',
      registerZh: '简洁服务语域，可要求易懂解释及隐私边界。',
    },
    [
      [
        'problem',
        'describe-problem',
        'What happened when the sample card was used?',
        '无需真实卡资料。',
        'declined',
        'The shop payment was declined.',
        'retained',
        'The cash machine did not return the card.',
        a2,
      ],
      [
        'place',
        'locate-event',
        'Was the payment point or machine inside a building?',
        '两问题都可在室内外。',
        'inside',
        'Yes, it was inside a building.',
        'outside',
        'No, it was outside.',
        a2,
      ],
      [
        'time',
        'state-time',
        'Had this happened before yesterday afternoon?',
        '区分首次和重复。',
        'first',
        'No, yesterday was the first time.',
        'before',
        'Yes, it had happened once before.',
        a2,
      ],
      [
        'message',
        'report-message',
        'Did the screen show any message when the problem happened?',
        '不补造错误原因。',
        'message',
        'Yes, but I did not write the message down.',
        'none',
        'No, I did not see any message.',
        a2,
      ],
      [
        'attempts',
        'report-contact',
        'Did you speak to any staff about it at the time?',
        '报告先前联系，不要求具体人名。',
        'no',
        'No, I did not speak to anyone about it.',
        'unsure',
        'I cannot remember whether I asked anyone.',
        a2,
      ],
      [
        'priority',
        'set-priority',
        'What would you like the service adviser to explain first?',
        '请求解释，不自动解决。',
        'explain',
        'I would like to understand what may have happened.',
        'options',
        'I would like to know what help is available.',
        a2,
      ],
      [
        'privacy',
        'protect-information',
        'Would you like a reminder of what information this exercise uses?',
        '只用虚构资料，可要求提醒。',
        'sample',
        'No, I understand that we use only the sample details.',
        'explain',
        'Yes, please remind me what information we can use.',
        a2,
      ],
      [
        'explanation',
        'request-clarity',
        'How would you like the information explained?',
        '说明易用形式。',
        'simple',
        'Please use simple words and short steps.',
        'written',
        'Please write the explanation so I can read it.',
        a2,
      ],
      [
        'summary',
        'request-summary',
        'Would you like a short summary of the discussion?',
        '讨论与操作区分。',
        'yes',
        'Yes, that would help me remember it.',
        'no',
        'No, thank you. I do not need a summary.',
        a2,
      ],
      [
        'followup',
        'plan-next-step',
        'Which follow-up question would you like to practise?',
        '练习问题而非接受操作。',
        'time',
        'Could you tell me how long a check might take?',
        'contact',
        'Could you tell me where to ask for further help?',
        a2,
      ],
      [
        'channel',
        'choose-channel',
        'Which way of speaking to an adviser would suit you?',
        '只是渠道偏好。',
        'desk',
        'I would prefer to speak to someone at a desk.',
        'phone',
        'I would prefer to speak to someone by phone.',
        a2,
      ],
      [
        'access',
        'request-access',
        'Do you need more time to read the sample information?',
        '虚构材料无需个人信息。',
        'time',
        'Yes, please give me a little more time.',
        'ready',
        'No, I can read the information at this pace.',
        a2,
      ],
    ],
    a2,
  ),
  B1: dailyPack(
    scene,
    'B1',
    {
      canDoZh: '描述非例行服务问题、证据缺口和帮助优先级。',
      complexityZh: '区分看到的现象与不确定记忆，安排进一步询问。',
      scaffoldingZh: '不用具体错误码或账户数据，提供观察型问题。',
      registerZh: '清楚诚实的服务叙述，能说无法确认。',
    },
    [
      [
        'problem',
        'describe-problem',
        'How would you describe the difficulty with the sample card?',
        '只描述结果。',
        'declined',
        'A payment at a shop was declined, and I do not know why.',
        'retained',
        'The ATM kept the card instead of returning it.',
        b1,
      ],
      [
        'place',
        'locate-event',
        'What sort of setting was the payment point or machine in?',
        '地点类型足够。',
        'inside',
        'It was inside a building, rather than on the street.',
        'outside',
        'It was outside, in an open area.',
        b1,
      ],
      [
        'time',
        'state-time',
        'Was the incident yesterday afternoon a new problem or a repeat?',
        '虚构历史可选。',
        'first',
        'It was a new problem; I had not experienced it before.',
        'before',
        'It was a repeat of something that had happened earlier.',
        b1,
      ],
      [
        'message',
        'report-message',
        'What can you say about any message that appeared?',
        '不要猜消息内容。',
        'message',
        'There was a message, but I cannot recall the wording accurately.',
        'none',
        'I did not see a message, so I cannot report one.',
        b1,
      ],
      [
        'attempts',
        'report-contact',
        'Can you say whether you asked staff for help at the time?',
        '承认联系历史的记忆空缺。',
        'no',
        'I did not speak to any staff about the problem then.',
        'unsure',
        'I am not certain whether I asked anyone, and I would rather not guess.',
        b1,
      ],
      [
        'priority',
        'set-priority',
        'What would make this discussion most useful to you at the start?',
        '选择理解原因或了解帮助。',
        'explain',
        'I would like an explanation of possible causes, without assuming one has been identified.',
        'options',
        'I would like to hear which kinds of assistance could be available.',
        b1,
      ],
      [
        'privacy',
        'protect-information',
        'Is the sample-only information rule clear, or would you like it explained?',
        '解释请求不改变隐私规则。',
        'sample',
        'It is clear; I will use only the fictional details supplied.',
        'explain',
        'I would like the rule explained so I know what to leave out.',
        b1,
      ],
      [
        'explanation',
        'request-clarity',
        'What form of explanation would help you understand the discussion?',
        '选择具体支架。',
        'simple',
        'Please use plain language, because banking terms are unfamiliar to me.',
        'written',
        'A written explanation would help me review the points at my own pace.',
        b1,
      ],
      [
        'summary',
        'request-summary',
        'Would a brief summary of the points discussed be useful?',
        '不声称已完成服务。',
        'yes',
        'Yes, it would help me separate what is known from what still needs checking.',
        'no',
        'No, I can keep track of the discussion without a summary.',
        b1,
      ],
      [
        'followup',
        'plan-next-step',
        'What would you want clarified before considering a next step?',
        '仍是咨询问题。',
        'time',
        'I would want to know how long any proposed check might take.',
        'contact',
        'I would want to know which support channel could handle a further enquiry.',
        b1,
      ],
      [
        'channel',
        'choose-channel',
        'Which support channel would make it easier for you to explain the issue?',
        '不指定真实银行渠道。',
        'desk',
        'A face-to-face conversation would let me ask questions as they arise.',
        'phone',
        'A phone conversation would be more convenient for me.',
        b1,
      ],
      [
        'access',
        'request-access',
        'Would extra reading time help with the sample information?',
        '不因无额外请求而保留待办。',
        'time',
        'Yes, I need a little more time to take in the unfamiliar terms.',
        'ready',
        'No, the pace is comfortable and I do not need extra time.',
        b1,
      ],
    ],
    b1,
  ),
  B2: dailyPack(
    scene,
    'B2',
    {
      canDoZh: '结构化报告服务故障，限定证据与解释范围。',
      complexityZh: '处理记忆不确定性，协调信息形式和可执行的询问。',
      scaffoldingZh: '给定虚构事件，不依赖真实银行规则或身份信息。',
      registerZh: '明确而合作的投诉咨询语气。',
    },
    [
      [
        'problem',
        'describe-problem',
        'Which outcome are you asking the adviser to help you understand?',
        '不推断故障原因。',
        'declined',
        'The shop payment was declined; I would like the refusal investigated rather than assume the reason.',
        'retained',
        'The ATM did not return the card; I need to discuss that specific outcome.',
        b2,
      ],
      [
        'place',
        'locate-event',
        'How would you describe the setting without providing an identifying location?',
        '隐私边界来自任务。',
        'inside',
        'The payment point or machine was indoors, within a building.',
        'outside',
        'It was outdoors, rather than inside a branch or shop.',
        b2,
      ],
      [
        'time',
        'state-time',
        'Does yesterday afternoon mark the first occurrence or the latest one?',
        '先后顺序。',
        'first',
        'It was the first occurrence, so I do not have a pattern to compare it with.',
        'before',
        'It was the latest occurrence; the same type of problem had arisen before.',
        b2,
      ],
      [
        'message',
        'report-message',
        'How much reliable information do you have about a screen message?',
        '不虚构原话。',
        'message',
        'I remember a message appearing, but quoting its wording now would be unreliable.',
        'none',
        'I did not see a message, so I have no wording to pass on.',
        b2,
      ],
      [
        'attempts',
        'report-contact',
        'How certain are you about whether you contacted staff immediately afterwards?',
        '未联系或不确定都适用两种问题。',
        'no',
        'I am certain I did not approach any staff about the incident at the time.',
        'unsure',
        'I cannot reliably say whether I spoke to anyone; that detail is unclear in my memory.',
        b2,
      ],
      [
        'priority',
        'set-priority',
        'Which issue would you like the adviser to address before moving into detail?',
        '服务沟通而非建议。',
        'explain',
        'I would like the possible explanations outlined, with a clear distinction between possibilities and findings.',
        'options',
        'I would like an overview of the available assistance before discussing any particular option.',
        b2,
      ],
      [
        'privacy',
        'protect-information',
        'Do you need the limits on information use clarified?',
        '不允许真实信息；可询问解释。',
        'sample',
        'No, I understand that only the fictional sample information belongs in this exercise.',
        'explain',
        'Yes, I would like a clear explanation of which kinds of details must be left out.',
        b2,
      ],
      [
        'explanation',
        'request-clarity',
        'How could the explanation be made easier for you to use?',
        '形式选择。',
        'simple',
        'Please translate any specialist terminology into plain language as it comes up.',
        'written',
        'Please provide the explanation in writing so I can check the sequence carefully.',
        b2,
      ],
      [
        'summary',
        'request-summary',
        'Would you benefit from a brief recap of the discussion?',
        '不声称采取行动。',
        'yes',
        'Yes, particularly a recap distinguishing the reported facts from matters that remain uncertain.',
        'no',
        'No, I have followed the distinctions and do not need a recap at this stage.',
        b2,
      ],
      [
        'followup',
        'plan-next-step',
        'What practical uncertainty would you want resolved before considering further help?',
        '不保证时间。',
        'time',
        'I would ask for a realistic time range for any proposed check, rather than an open-ended assurance.',
        'contact',
        'I would ask which support channel is responsible for a follow-up enquiry.',
        b2,
      ],
      [
        'channel',
        'choose-channel',
        'Which form of contact would best support a clear explanation of the issue?',
        '具体权衡。',
        'desk',
        'A desk conversation would suit me, because I could clarify misunderstandings as they occur.',
        'phone',
        'A phone conversation would be more practical, provided the explanation is not rushed.',
        b2,
      ],
      [
        'access',
        'request-access',
        'Is the pace at which you can read the sample information sufficient?',
        '仅阅读需要。',
        'time',
        'Not quite; I would appreciate more time to work through the unfamiliar wording.',
        'ready',
        'Yes, the pace is manageable and no additional reading time is needed.',
        b2,
      ],
    ],
    b2,
  ),
  C1: dailyPack(
    scene,
    'C1',
    {
      canDoZh: '精确组织事件陈述，区分已知、记忆缺口与解释假设。',
      complexityZh: '协商服务沟通范围、责任渠道与时间预期，不变成金融指导。',
      scaffoldingZh: '共享道具事件支撑细致陈述，未提供原因或真实操作流程。',
      registerZh: '冷静、精确而不生硬；CEFR信息交换及服务沟通。',
    },
    [
      [
        'problem',
        'describe-problem',
        'What is the specific outcome you want this enquiry to address?',
        '范围限定具体。',
        'declined',
        'The payment at the shop was declined; I would like to establish what can be checked before drawing conclusions about the cause.',
        'retained',
        'The ATM retained the card; the immediate point of the enquiry is that it was not returned.',
        c1,
      ],
      [
        'place',
        'locate-event',
        'What can you say about the setting while keeping identifying details out of the exercise?',
        '不索取地址或证件。',
        'inside',
        'It took place indoors, at a payment point or machine within a building.',
        'outside',
        'It took place outdoors; there was no need to enter a building to use the payment point or machine.',
        c1,
      ],
      [
        'time',
        'state-time',
        'How does yesterday afternoon fit into the history of the problem?',
        '区分首次与再次。',
        'first',
        'It was the first instance I had encountered, so I cannot say whether it forms part of a recurring pattern.',
        'before',
        'It was a recurrence of the same type of difficulty, although I cannot assume the underlying cause was the same.',
        c1,
      ],
      [
        'message',
        'report-message',
        'What distinction should the adviser make between what you recall and what you can quote?',
        '明确证据边界有情境必要。',
        'message',
        'I recall a message appearing, but not its exact wording; I would not want an approximate memory treated as a quotation.',
        'none',
        'I did not see a message, so there is no text that I can quote or paraphrase from the screen.',
        c1,
      ],
      [
        'attempts',
        'report-contact',
        'Can you give a firm account of whether you raised the issue with staff at the time?',
        '明确先前沟通证据，不指导操作。',
        'no',
        'Yes: I did not raise the issue with any staff at the time.',
        'unsure',
        'No; I cannot clearly recall whether I spoke to anyone, and would prefer to leave that point unconfirmed.',
        c1,
      ],
      [
        'priority',
        'set-priority',
        'What would you like established before the enquiry becomes more detailed?',
        '明确讨论优先级。',
        'explain',
        'I would like the possible explanations set out, with an indication of what evidence would distinguish them.',
        'options',
        'I would like to understand the scope of the assistance available before focusing on a particular course of action.',
        c1,
      ],
      [
        'privacy',
        'protect-information',
        'Would a further explanation of the information boundary be useful to you?',
        '澄清需要不要求真实信息。',
        'sample',
        'No, the boundary is clear: the fictional details supplied are enough, and real identifiers have no place here.',
        'explain',
        'Yes, I would appreciate the exclusions being made explicit, so I can keep my account of the event within them.',
        c1,
      ],
      [
        'explanation',
        'request-clarity',
        'What would make the explanation easier to assess rather than merely hear?',
        '提高互动深度。',
        'simple',
        'Please unpack the specialist terms as you use them, so I can follow the reasoning rather than just the labels.',
        'written',
        'A written explanation would let me examine the sequence and identify any points I still needed clarified.',
        c1,
      ],
      [
        'summary',
        'request-summary',
        'Would a concise recap add value at this stage of the conversation?',
        '拒绝无待办。',
        'yes',
        'Yes, especially if it separates what I have reported from what has yet to be established.',
        'no',
        'No, I have followed the distinction between the report and the unresolved points, so a recap is unnecessary.',
        c1,
      ],
      [
        'followup',
        'plan-next-step',
        'What would you want clarified before deciding whether to pursue further assistance?',
        '只询问时限或责任渠道。',
        'time',
        'I would ask what a realistic timescale depends on, rather than accept a vague suggestion that it will be quick.',
        'contact',
        'I would ask which team handles follow-up enquiries, so that a later question would not simply be passed around.',
        c1,
      ],
      [
        'channel',
        'choose-channel',
        'Which contact arrangement would give you the best chance of resolving misunderstandings?',
        '不冒充真实银行途径。',
        'desk',
        'I would favour a desk conversation, where I could stop and clarify a point before the discussion moved on.',
        'phone',
        'I would favour a phone conversation, provided there was enough time to work through the issue without being rushed.',
        c1,
      ],
      [
        'access',
        'request-access',
        'Would the reading time available let you make sense of the sample information?',
        '细致表达阅读需求。',
        'time',
        'I would need longer; I can read the words, but the unfamiliar terminology takes more time to absorb.',
        'ready',
        'Yes, the pace gives me enough time to understand the material, so no extension is needed.',
        c1,
      ],
    ],
    c1,
  ),
}
