import { dailyPack, type DailyScene, type Review } from './authoring'
const a1: Review = {
  state: 'model-reviewed',
  record:
    'daily-review.md#parcel-a1: all 12 named Q/A pairs and both variants read; conditional return reread by Codex implementation agent, 2026-09-10',
}
const a2: Review = {
  state: 'model-reviewed',
  record:
    'daily-review.md#parcel-a2: all 12 named Q/A pairs and both variants read by Codex implementation agent, 2026-09-10',
}
const b1: Review = {
  state: 'model-reviewed',
  record:
    'daily-review.md#parcel-b1: all 12 named Q/A pairs and both variants read by Codex implementation agent, 2026-09-10',
}
const b2: Review = {
  state: 'model-reviewed',
  record:
    'daily-review.md#parcel-b2: all 12 named Q/A pairs and both variants read by Codex implementation agent, 2026-09-10',
}
const c1: Review = {
  state: 'model-reviewed',
  record:
    'daily-review.md#parcel-c1: all 12 named Q/A pairs and both variants read by Codex implementation agent, 2026-09-10',
}
const scene: DailyScene = {
  sceneId: 'daily-04',
  slug: 'collect-parcel',
  situations: [
    '虚构包裹领取柜台。只有两件道具包裹：贴绿色贴纸的纸箱、贴蓝色贴纸的软包装，均为你的演练候选物，尚未选定或交付。你持有无姓名、地址、号码或条码的SAMPLE纸质通知。柜台可讨论核对物件、等候和搬运，但不要求真实身份证件、收件人信息、验证码或运单号。若请求改天再来或先检查，仍未获确认；短练仅说明物件、通知形式和核对重点。',
    '虚构包裹领取信息台，尚未排队或完成领取。候选道具是绿色贴纸纸箱与蓝色贴纸软包装；有一张只写SAMPLE的纸通知，没有个人信息。你先规划再来时间与携带方式，再考虑包裹外观及通知遗失时的询问。两件物品都是虚构，不提供真实证明、代码或联系方式，不保证保管、交付或退件服务。',
  ],
  paths: [
    {
      short: ['object', 'notice', 'check'],
      standard: ['object', 'notice', 'check', 'condition', 'wait', 'carry'],
      extended: [
        'object',
        'notice',
        'check',
        'condition',
        'wait',
        'carry',
        'inspect',
        'receipt',
        'packaging',
        'next',
      ],
    },
    {
      short: ['object', 'notice', 'check'],
      standard: ['object', 'notice', 'check', 'return', 'carry', 'wait'],
      extended: [
        'object',
        'notice',
        'check',
        'return',
        'carry',
        'wait',
        'condition',
        'inspect',
        'missing-notice',
        'next',
      ],
    },
  ],
  closing:
    'Your parcel-collection requests are recorded for the exercise. No identity has been verified and no parcel, storage request or later visit has been confirmed.',
  partial:
    'This parcel enquiry is partly complete. Unanswered choices remain open; no parcel has been handed over.',
  repairs: {
    clarify: 'I can repeat the current question about the sample parcel.',
    struggle:
      'You can use the colour or package description from the situation.',
    offTopic: 'Let us return to this fictional parcel enquiry.',
    unknown:
      'That wording is not covered; no parcel identity or collection is confirmed.',
    changed: 'The earlier parcel preference is replaced in this practice.',
    refusedClosing:
      'We will stop the parcel practice here. No real collection or storage arrangement has been made.',
  },
}
export const parcelPacks = {
  A1: dailyPack(
    scene,
    'A1',
    {
      canDoZh: '用颜色和包装形态识别虚构包裹并提出基本领取问题。',
      complexityZh: '逐项处理物件、外观和携带，增加等待及后续询问。',
      scaffoldingZh: '两件道具和无标识通知提供清晰支架，不用真实证件。',
      registerZh: '简单柜台请求与明确拒绝附加服务。',
    },
    [
      [
        'object',
        'identify-object',
        'Which sample parcel are you asking about?',
        '颜色与包装绑定。',
        'box',
        'The box with the green sticker.',
        'soft',
        'The soft package with the blue sticker.',
        a1,
      ],
      [
        'notice',
        'present-notice',
        'Would you like to show the sample notice or describe it?',
        '通知不含个人信息。',
        'show',
        'I would like to show it.',
        'describe',
        'I would like to describe it.',
        a1,
      ],
      [
        'check',
        'verify-object',
        'What would you like checked first?',
        '不核对真人身份。',
        'colour',
        'The sticker colour, please.',
        'shape',
        'The package shape, please.',
        a1,
      ],
      [
        'condition',
        'report-condition',
        'Does the outside look damaged?',
        '虚构观察可选。',
        'damaged',
        'Yes, I can see a tear.',
        'clear',
        'No, it looks fine.',
        a1,
      ],
      [
        'wait',
        'negotiate-wait',
        'Would you wait here or ask to come back?',
        '再来仅为请求。',
        'wait',
        'I can wait here.',
        'return-request',
        'Can I come back later?',
        a1,
      ],
      [
        'carry',
        'request-carrying',
        'Do you need help carrying the parcel?',
        '未交付。',
        'help',
        'Yes, help, please.',
        'self',
        'No, I can carry it.',
        a1,
      ],
      [
        'inspect',
        'request-inspection',
        'Would you like to ask for a closer look?',
        '检查未自动批准。',
        'ask',
        'Yes. Can I look more closely?',
        'no',
        'No, thank you.',
        a1,
      ],
      [
        'receipt',
        'request-record',
        'Would you like a collection record?',
        '未生成领取凭证。',
        'yes',
        'Yes, a record, please.',
        'no',
        'No record, thanks.',
        a1,
      ],
      [
        'packaging',
        'ask-packaging',
        'Would you like to ask about an extra bag?',
        '包装请求可拒绝。',
        'ask',
        'Yes. Is a bag available?',
        'no',
        'No, I have a bag.',
        a1,
      ],
      [
        'next',
        'clarify-next',
        'What would you like to ask before leaving?',
        '不假定已领取。',
        'steps',
        'What is the next step?',
        'hours',
        'When does this desk close?',
        a1,
      ],
      [
        'return',
        'plan-visit',
        'If you came back, would today or tomorrow suit you?',
        '只问假设偏好，后续可选择等候。',
        'today',
        'Later today would suit me.',
        'tomorrow',
        'Tomorrow would suit me.',
        a1,
      ],
      [
        'missing-notice',
        'plan-contingency',
        'If the sample notice were lost, what would you ask?',
        '不要求真实身份证明。',
        'process',
        'What is the process?',
        'help',
        'Who can explain the options?',
        a1,
      ],
    ],
    a1,
  ),
  A2: dailyPack(
    scene,
    'A2',
    {
      canDoZh: '描述包裹特征和外观问题，安排简短服务咨询。',
      complexityZh: '连接等候、携带和再来询问，不预设保管获准。',
      scaffoldingZh: '给定包装颜色与通知，可选择具体检查点。',
      registerZh: '日常礼貌请求，清楚说不需要附加选择。',
    },
    [
      [
        'object',
        'identify-object',
        'Which of the two sample packages do you mean?',
        '选择具体物件。',
        'box',
        'I mean the box with a green sticker.',
        'soft',
        'I mean the soft package with a blue sticker.',
        a2,
      ],
      [
        'notice',
        'present-notice',
        'How would you like to refer to the sample notice?',
        '只用SAMPLE道具。',
        'show',
        'I would like to show you the paper notice.',
        'describe',
        'I would prefer to describe what the paper notice says.',
        a2,
      ],
      [
        'check',
        'verify-object',
        'Which feature should we compare first?',
        '不问姓名地址。',
        'colour',
        'Please compare the sticker colour first.',
        'shape',
        'Please compare the shape of the package first.',
        a2,
      ],
      [
        'condition',
        'report-condition',
        'What can you see on the outside of the package?',
        '外观非内容物保证。',
        'damaged',
        'There is a small tear in the outside wrapping.',
        'clear',
        'I cannot see any damage on the outside.',
        a2,
      ],
      [
        'wait',
        'negotiate-wait',
        'Would you prefer to wait or ask about returning later?',
        '等待与请求分开。',
        'wait',
        'I can wait here for now.',
        'return-request',
        'Could I return later instead of waiting?',
        a2,
      ],
      [
        'carry',
        'request-carrying',
        'Will you need any help carrying the package?',
        '不假定已领到。',
        'help',
        'Yes, could someone help me carry it?',
        'self',
        'No, I can carry it on my own.',
        a2,
      ],
      [
        'inspect',
        'request-inspection',
        'Do you want to ask whether you can inspect the outside more closely?',
        '不承诺检查权限。',
        'ask',
        'Yes, could I have a closer look at the outside?',
        'no',
        'No, I do not need a closer look.',
        a2,
      ],
      [
        'receipt',
        'request-record',
        'Would you like to request a record of collection?',
        '请求未等于领取。',
        'yes',
        'Yes, I would like a record for my notes.',
        'no',
        'No, thank you. I do not need a record.',
        a2,
      ],
      [
        'packaging',
        'ask-packaging',
        'Would an extra carrying bag be worth asking about?',
        '可不提请求。',
        'ask',
        'Yes, could you tell me if a bag is available?',
        'no',
        'No, I have brought a bag with me.',
        a2,
      ],
      [
        'next',
        'clarify-next',
        'Which final question would be useful before you leave?',
        '中性后续，无已完成假设。',
        'steps',
        'Could you explain what I should ask about next?',
        'hours',
        'Could you tell me the desk opening hours?',
        a2,
      ],
      [
        'return',
        'plan-visit',
        'When would you prefer to return if a later visit were possible?',
        '时间均未确认。',
        'today',
        'I would prefer to return later today.',
        'tomorrow',
        'I would prefer to come back tomorrow.',
        a2,
      ],
      [
        'missing-notice',
        'plan-contingency',
        'If you lost the sample notice, what would you want explained?',
        '只练流程询问。',
        'process',
        'I would ask how to continue without the notice.',
        'help',
        'I would ask who could explain the available options.',
        a2,
      ],
    ],
    a2,
  ),
  B1: dailyPack(
    scene,
    'B1',
    {
      canDoZh: '解释包裹识别线索、外观疑点和领取限制。',
      complexityZh: '处理等待替代与缺失通知的假设，不把请求当批准。',
      scaffoldingZh: '固定道具说明使问答聚焦，无私人资料输入。',
      registerZh: '合作的柜台咨询，提出原因和澄清。',
    },
    [
      [
        'object',
        'identify-object',
        'How would you distinguish the parcel you are enquiring about?',
        '描述足以对应道具。',
        'box',
        'It is the cardboard box with the green sticker.',
        'soft',
        'It is the soft package with the blue sticker.',
        b1,
      ],
      [
        'notice',
        'present-notice',
        'Would you rather show the sample notice or explain what is on it?',
        '仅无标识纸通知。',
        'show',
        'I would rather show it so we can look at the same information.',
        'describe',
        'I would rather describe it, since the only wording is SAMPLE.',
        b1,
      ],
      [
        'check',
        'verify-object',
        'Which identifying feature would you like compared first?',
        '物件特征与真人身份分离。',
        'colour',
        'The sticker colour would be the clearest first check.',
        'shape',
        'The shape of the package would be the easiest feature to compare.',
        b1,
      ],
      [
        'condition',
        'report-condition',
        'How would you describe the visible condition of the package?',
        '不给内部损坏结论。',
        'damaged',
        'There is a tear in the outer wrapping, which I would like to point out.',
        'clear',
        'I cannot see any damage to the outside of the package.',
        b1,
      ],
      [
        'wait',
        'negotiate-wait',
        'Would waiting here work for you, or would you like to ask about another visit?',
        '拒绝改期不产生待定请求。',
        'wait',
        'Waiting here would work for me; I do not need to arrange another visit.',
        'return-request',
        'I would like to ask whether I could return later, because I have another errand.',
        b1,
      ],
      [
        'carry',
        'request-carrying',
        'What help would you need to carry the parcel away?',
        '携带仍是假设需求。',
        'help',
        'I would need some help carrying it, as I have another bag with me.',
        'self',
        'I could carry it myself and would not need assistance.',
        b1,
      ],
      [
        'inspect',
        'request-inspection',
        'Would you like to request a closer check of the outside?',
        '与是否看到损坏均兼容。',
        'ask',
        'Yes, I would like to look more closely before making any decision about collection.',
        'no',
        'No, I do not want to request any further inspection.',
        b1,
      ],
      [
        'receipt',
        'request-record',
        'Would a collection record be useful to you?',
        '未实际创建。',
        'yes',
        'Yes, I would like to request one so I can keep track of the collection.',
        'no',
        'No, I do not need a separate record for this exercise.',
        b1,
      ],
      [
        'packaging',
        'ask-packaging',
        'Do you want to enquire about a carrying bag?',
        '独立包装需要。',
        'ask',
        'Yes, I would like to know whether a suitable bag is available.',
        'no',
        'No, I have a bag with me, so there is no need to ask.',
        b1,
      ],
      [
        'next',
        'clarify-next',
        'What would you want clarified before ending the enquiry?',
        '无论等待或再来都自然。',
        'steps',
        'I would like the next part of the collection process explained.',
        'hours',
        'I would like to know when the collection desk is open.',
        b1,
      ],
      [
        'return',
        'plan-visit',
        'If a return visit were possible, when would it suit you?',
        '条件明确不保证保管。',
        'today',
        'Later today would suit me, after I have finished my other errands.',
        'tomorrow',
        'Tomorrow would be more convenient, because I could allow more time.',
        b1,
      ],
      [
        'missing-notice',
        'plan-contingency',
        'What would you ask if the sample notice were no longer available?',
        '不索取真实文件。',
        'process',
        'I would ask what process applies when the notice is missing.',
        'help',
        'I would ask which member of staff could explain the alternatives.',
        b1,
      ],
    ],
    b1,
  ),
  B2: dailyPack(
    scene,
    'B2',
    {
      canDoZh: '精确比较物件线索，报告外观并协商等候替代。',
      complexityZh: '区分条件性计划、服务请求与事实，澄清缺通知的流程。',
      scaffoldingZh: '道具共享事实固定，学习者自行组织理由和重点。',
      registerZh: '冷静明确的服务咨询，避免指责或未经证实的损坏结论。',
    },
    [
      [
        'object',
        'identify-object',
        'Which combination of features identifies the sample parcel you mean?',
        '颜色和形态共同支持物件。',
        'box',
        'The cardboard box with the green sticker, rather than the soft blue-labelled package.',
        'soft',
        'The soft package with the blue sticker, rather than the green-labelled box.',
        b2,
      ],
      [
        'notice',
        'present-notice',
        'How would you prefer to use the fictional collection notice in this discussion?',
        '道具不含个人资料。',
        'show',
        'I would show the paper notice so that we could refer to it together.',
        'describe',
        'I would describe its SAMPLE wording rather than hand over the paper.',
        b2,
      ],
      [
        'check',
        'verify-object',
        'Which feature should receive attention before the others?',
        '特征核对不是身份确认。',
        'colour',
        'The sticker colour is the most distinctive feature, so I would compare that first.',
        'shape',
        'The package shape gives the clearest contrast, so I would start there.',
        b2,
      ],
      [
        'condition',
        'report-condition',
        'What observation about the exterior would you want recorded?',
        '观察限定可见范围。',
        'damaged',
        'I would want the visible tear in the outer wrapping noted, without assuming what is inside.',
        'clear',
        'I would report that I can see no external damage, without making a claim about the contents.',
        b2,
      ],
      [
        'wait',
        'negotiate-wait',
        'How would you prefer to handle the possibility of a wait?',
        '请求不能当作已改期。',
        'wait',
        'I can wait here and do not need to explore a return visit.',
        'return-request',
        'I would like to ask about returning later, rather than assume I can leave the parcel here indefinitely.',
        b2,
      ],
      [
        'carry',
        'request-carrying',
        'Would carrying the parcel present a practical difficulty?',
        '两件均可有此需求。',
        'help',
        'Yes, with my other bag it would be awkward; I would appreciate assistance carrying it.',
        'self',
        'No, I can manage it myself and do not need carrying assistance.',
        b2,
      ],
      [
        'inspect',
        'request-inspection',
        'Would a closer inspection of the exterior be worth requesting?',
        '已拒绝则不留待办。',
        'ask',
        'Yes, I would like to request a closer look before deciding how to proceed.',
        'no',
        'No, I do not wish to request any additional inspection.',
        b2,
      ],
      [
        'receipt',
        'request-record',
        'Do you want to include a collection record among your requests?',
        '未假装领取。',
        'yes',
        'Yes, a written record would help me keep the collection separate from my other errands.',
        'no',
        'No, I do not need a separate collection record.',
        b2,
      ],
      [
        'packaging',
        'ask-packaging',
        'Would you like to check whether additional carrying packaging is available?',
        '不暗示包装破损必定要换。',
        'ask',
        'Yes, please explain whether a suitable carrying bag is available and whether it costs extra.',
        'no',
        'No, I have suitable carrying packaging with me, so no enquiry is needed.',
        b2,
      ],
      [
        'next',
        'clarify-next',
        'What would be most useful to clarify before closing this conversation?',
        '中性，不预设某请求待定。',
        'steps',
        'The remaining collection process, so I know what would be expected before a handover.',
        'hours',
        'The desk opening hours, so I can plan without assuming continuous access.',
        b2,
      ],
      [
        'return',
        'plan-visit',
        'What timing would you propose if a later visit could be arranged?',
        '假设条件服务。',
        'today',
        'I would propose later today, provided the desk would still be open.',
        'tomorrow',
        'I would propose tomorrow, when I could give the collection more time.',
        b2,
      ],
      [
        'missing-notice',
        'plan-contingency',
        'What would you ask to avoid guessing the procedure if the sample notice were missing?',
        '只询问流程。',
        'process',
        'I would ask for the missing-notice procedure to be explained before considering any next step.',
        'help',
        'I would ask who was able to explain the available options for that situation.',
        b2,
      ],
    ],
    b2,
  ),
  C1: dailyPack(
    scene,
    'C1',
    {
      canDoZh: '用准确特征消除包裹歧义，并审慎协商可行后续安排。',
      complexityZh: '处理外观与内容物的证据差别、条件性再访和流程缺口。',
      scaffoldingZh: '共享无身份数据的道具，要求具体澄清与自然权衡。',
      registerZh: '周到明确的柜台互动；CEFR服务和澄清量表，不宣称实际规则。',
    },
    [
      [
        'object',
        'identify-object',
        'Which parcel should this enquiry concern, so that we do not confuse the two samples?',
        '识别始终绑定配色。',
        'box',
        'The cardboard box bearing the green sticker; the soft package with the blue sticker is not the one I mean.',
        'soft',
        'The soft package bearing the blue sticker; I am not referring to the green-labelled cardboard box.',
        c1,
      ],
      [
        'notice',
        'present-notice',
        'How would you like to bring the sample notice into the discussion?',
        '无真实文件。',
        'show',
        'I would show the paper itself, so we could both refer to the same sample rather than rely on a description.',
        'describe',
        'I would describe the SAMPLE wording; there are no other details on the notice that need to be supplied.',
        c1,
      ],
      [
        'check',
        'verify-object',
        'Which visible feature offers the clearest starting point for comparison?',
        '比较焦点有实质区别。',
        'colour',
        'The sticker colour; it provides an immediate distinction that is less dependent on how the package is positioned.',
        'shape',
        'The overall shape; I would establish that first and use the label only as a secondary check.',
        c1,
      ],
      [
        'condition',
        'report-condition',
        'How would you characterise the exterior without overstating what you can establish?',
        '特定损坏场景才需限定。',
        'damaged',
        'There is a visible tear in the outer wrapping; I would want that noted before anyone draws conclusions about the contents.',
        'clear',
        'The exterior appears intact to me; that is an observation about the packaging, not an assessment of what is inside.',
        c1,
      ],
      [
        'wait',
        'negotiate-wait',
        'Would you rather wait here, or explore whether a return visit could be accommodated?',
        '不自动承认保管或改期。',
        'wait',
        'I can wait here, so there is no need to pursue an arrangement for a return visit.',
        'return-request',
        'I would prefer to explore a return visit, but would need the timing and storage conditions clarified before relying on it.',
        c1,
      ],
      [
        'carry',
        'request-carrying',
        'What carrying assistance would make the collection manageable for you?',
        '需求与已经交付分开。',
        'help',
        'Some assistance would help, since managing the parcel alongside my other bag would be awkward on my own.',
        'self',
        'I can manage it without assistance; I would prefer to carry it myself so I can position it comfortably.',
        c1,
      ],
      [
        'inspect',
        'request-inspection',
        'Would you like to pursue a closer inspection of the outside before considering collection?',
        '否定分支没有悬而未决的检查请求。',
        'ask',
        'Yes, I would like to request a closer look, particularly at the edges where the wrapping is folded.',
        'no',
        'No, I do not wish to pursue a further inspection of the exterior.',
        c1,
      ],
      [
        'receipt',
        'request-record',
        'Would a separate record of collection serve a useful purpose for you?',
        '具体用途而非抽象免责声明。',
        'yes',
        'Yes, I would like to request one so that I can distinguish this collection from the other items I am tracking.',
        'no',
        'No, I have no need for a separate record, so please leave that out of my requests.',
        c1,
      ],
      [
        'packaging',
        'ask-packaging',
        'Is there any value in enquiring about additional carrying packaging?',
        '独立请求及价格条件。',
        'ask',
        'Yes, I would like to know what is available and whether there is a charge before requesting a bag.',
        'no',
        'No, I have suitable packaging with me and do not need to pursue that option.',
        c1,
      ],
      [
        'next',
        'clarify-next',
        'Which remaining piece of information would make the enquiry useful beyond this conversation?',
        '所有选择后均自然，无虚构待办。',
        'steps',
        'A clear account of the collection process, especially anything that would need to happen before a parcel could be handed over.',
        'hours',
        'The collection desk hours, including any interruption in service, so that I can plan a visit realistically.',
        c1,
      ],
      [
        'return',
        'plan-visit',
        'If a later visit were possible, what timing would you put forward?',
        '无已批准假设。',
        'today',
        'Later today would be my preference, provided there would be enough time before the desk closed.',
        'tomorrow',
        'Tomorrow would be more practical; I could allow time for the collection instead of fitting it between other errands.',
        c1,
      ],
      [
        'missing-notice',
        'plan-contingency',
        'If the sample notice were unavailable, what would you want clarified rather than assumed?',
        '不索要替代真实证件。',
        'process',
        'I would want the procedure for a missing notice explained, rather than presume that the usual sequence still applied.',
        'help',
        'I would want to know who could explain the alternatives, so the enquiry reached someone able to deal with that situation.',
        c1,
      ],
    ],
    c1,
  ),
}
