import { dailyPack, type DailyScene, type Review } from './authoring'
const a1: Review = {
  state: 'model-reviewed',
  record:
    'daily-review.md#hair-a1: all 12 named Q/A pairs and both variants read; wash/finish/product pairs reread by Codex implementation agent, 2026-09-10',
}
const a2: Review = {
  state: 'model-reviewed',
  record:
    'daily-review.md#hair-a2: all 12 named Q/A pairs and both variants read; wash/finish/product pairs reread by Codex implementation agent, 2026-09-10',
}
const b1: Review = {
  state: 'model-reviewed',
  record:
    'daily-review.md#hair-b1: all 12 named Q/A pairs and both variants read; wash/finish/product pairs reread by Codex implementation agent, 2026-09-10',
}
const b2: Review = {
  state: 'model-reviewed',
  record:
    'daily-review.md#hair-b2: all 12 named Q/A pairs and both variants read; wash/finish/product pairs reread by Codex implementation agent, 2026-09-10',
}
const c1: Review = {
  state: 'model-reviewed',
  record:
    'daily-review.md#hair-c1: all 12 named Q/A pairs and both variants read; wash/finish/product pairs reread by Codex implementation agent, 2026-09-10',
}
const scene: DailyScene = {
  sceneId: 'daily-05',
  slug: 'haircut-request',
  situations: [
    '虚构理发店咨询，尚未开始剪发。你的头发到肩部，额前部分可选剪刘海或向两侧梳；没有既定发型。主长度可选只修发尾或明显剪短，两种都适合讨论图示、洗发、干发和日常打理。店内有两张虚构参考图及镜子，服务内容和价格未确定。改变长度后不得继续说保留原长度；短练只说明主长度、刘海偏好及参考方式。',
    '虚构理发预约前的风格咨询。你的头发到肩部，可选只修发尾或明显剪短，额前可剪刘海或梳到两边。店内有两张虚构参考图及镜子。你侧重日常打理时间和产品偏好，并询问时间及预算限制；未预约或授权剪发，效果不保证。所有偏好待理发师讨论，没有染烫或医疗建议。',
  ],
  paths: [
    {
      short: ['length', 'fringe', 'reference'],
      standard: ['length', 'fringe', 'reference', 'wash', 'dry', 'check'],
      extended: [
        'length',
        'fringe',
        'reference',
        'wash',
        'dry',
        'check',
        'parting',
        'products',
        'time',
        'price',
      ],
    },
    {
      short: ['length', 'fringe', 'reference'],
      standard: [
        'length',
        'fringe',
        'reference',
        'routine',
        'products',
        'check',
      ],
      extended: [
        'length',
        'fringe',
        'reference',
        'routine',
        'products',
        'check',
        'parting',
        'growth',
        'time',
        'price',
      ],
    },
  ],
  closing:
    'Your haircut preferences have been practised, including any revisions. No haircut, price or appointment has been agreed or carried out.',
  partial:
    'This haircut consultation is partly complete. Unconfirmed preferences remain open, and no cutting has started.',
  repairs: {
    clarify: 'I can repeat the current haircut question.',
    struggle: 'A short preference about this detail is enough.',
    offTopic: 'Let us return to the haircut consultation.',
    unknown:
      'That wording is not covered, so no style instruction has been confirmed from it.',
    changed:
      'Your earlier style preference has been replaced for this practice.',
    refusedClosing:
      'We will stop the haircut consultation practice here. No haircut has started.',
  },
}
export const haircutPacks = {
  A1: dailyPack(
    scene,
    'A1',
    {
      canDoZh: '用具体短句说明长度、刘海和基本服务偏好。',
      complexityZh: '每次一项，额外话轮加入打理及费用询问。',
      scaffoldingZh: '肩部头发、镜子和图示支持词汇理解，可要求先展示。',
      registerZh: '简单礼貌的理发咨询，可拒绝产品或洗发。',
    },
    [
      [
        'length',
        'choose-length',
        'How much would you like cut off?',
        '只修发尾或明显剪短。',
        'trim',
        'Just a trim, please.',
        'shorter',
        'Much shorter, please.',
        a1,
      ],
      [
        'fringe',
        'choose-fringe',
        'Would you like a fringe?',
        '额前独立偏好。',
        'fringe',
        'Yes, a fringe, please.',
        'sides',
        'No, keep the front to the sides.',
        a1,
      ],
      [
        'reference',
        'use-reference',
        'Would you like to use a picture or describe the style?',
        '可用参考图或言语。',
        'picture',
        'A picture, please.',
        'describe',
        'I will describe it.',
        a1,
      ],
      [
        'wash',
        'choose-wash',
        'Would you like a wash?',
        '可拒绝附加服务。',
        'yes',
        'Yes, a wash, please.',
        'no',
        'No wash, thanks.',
        a1,
      ],
      [
        'dry',
        'choose-finish',
        'Would you like a styled finish or a natural finish?',
        '不依赖是否洗发。',
        'styled',
        'A styled finish, please.',
        'natural',
        'A natural finish, please.',
        a1,
      ],
      [
        'check',
        'set-checkpoint',
        'How should we check the length before cutting?',
        '不重问已选长度。',
        'show',
        'Please show me with your fingers.',
        'mirror',
        'Please show me in the mirror.',
        a1,
      ],
      [
        'parting',
        'choose-parting',
        'Do you prefer a middle or side parting?',
        '主长度与刘海都可兼容分缝。',
        'middle',
        'A middle parting, please.',
        'side',
        'A side parting, please.',
        a1,
      ],
      [
        'products',
        'set-products',
        'Would you like styling products?',
        '可以明确不需要。',
        'yes',
        'Yes, a little, please.',
        'no',
        'No products, please.',
        a1,
      ],
      [
        'time',
        'state-time',
        'Do you have a time limit today?',
        '不承诺服务可按时结束。',
        'limit',
        'Yes, I have thirty minutes.',
        'flexible',
        'No, I have plenty of time.',
        a1,
      ],
      [
        'price',
        'ask-price',
        'What would you like to ask about the price?',
        '仍是询问。',
        'total',
        'How much is it altogether?',
        'extras',
        'Do extras cost more?',
        a1,
      ],
      [
        'routine',
        'describe-routine',
        'How long do you spend on your hair in the morning?',
        '生活习惯。',
        'quick',
        'About five minutes.',
        'longer',
        'About twenty minutes.',
        a1,
      ],
      [
        'growth',
        'ask-upkeep',
        'What would you like to know about looking after the cut?',
        '新结果非重问长度。',
        'visits',
        'When would I need another trim?',
        'home',
        'How could I style it at home?',
        a1,
      ],
    ],
    a1,
  ),
  A2: dailyPack(
    scene,
    'A2',
    {
      canDoZh: '说明发型偏好与简单打理习惯，并要求剪前核对。',
      complexityZh: '区分剪发主体、附加服务和日常限制。',
      scaffoldingZh: '图示和镜子支持具体描述；使用简单原因。',
      registerZh: '日常咨询短句，友好但清楚表达不要。',
    },
    [
      [
        'length',
        'choose-length',
        'Are you looking for a small trim or a shorter cut?',
        '长度主指令只由本题负责。',
        'trim',
        'A small trim, please. Just tidy the ends.',
        'shorter',
        'I would like it much shorter than it is now.',
        a2,
      ],
      [
        'fringe',
        'choose-fringe',
        'What would you like done with the front?',
        '不锁定主长度。',
        'fringe',
        'I would like a fringe at the front.',
        'sides',
        'I would like the front brushed to the sides, without a fringe.',
        a2,
      ],
      [
        'reference',
        'use-reference',
        'How would you like to explain the style you want?',
        '参考方式。',
        'picture',
        'I would like to use one of the pictures.',
        'describe',
        'I would prefer to describe it in words.',
        a2,
      ],
      [
        'wash',
        'choose-wash',
        'Would you like a hair wash as part of the service?',
        '服务未确认。',
        'yes',
        'Yes, please include a wash in my request.',
        'no',
        'No, thank you. I do not want a wash.',
        a2,
      ],
      [
        'dry',
        'choose-finish',
        'How would you like your hair finished?',
        '不假定已洗发或头发湿。',
        'styled',
        'I would like it styled at the end.',
        'natural',
        'I would like to leave it looking natural.',
        a2,
      ],
      [
        'check',
        'set-checkpoint',
        'How would you like the proposed length shown before any cutting?',
        '改变长度后仍适用。',
        'show',
        'Please show the amount with your fingers first.',
        'mirror',
        'Please use the mirror to show where the ends would be.',
        a2,
      ],
      [
        'parting',
        'choose-parting',
        'Where do you like the parting in your hair?',
        '可与刘海并存。',
        'middle',
        'I like a parting in the middle.',
        'side',
        'I prefer a parting at the side.',
        a2,
      ],
      [
        'products',
        'set-products',
        'Do you want any products used for styling?',
        '产品不等于保证效果。',
        'yes',
        'Yes, but only a small amount, please.',
        'no',
        'No, I would rather not use any products.',
        a2,
      ],
      [
        'time',
        'state-time',
        'Is there a latest time you need to leave?',
        '具体限制不等于接受。',
        'limit',
        'Yes, I need to leave in thirty minutes.',
        'flexible',
        'No, I do not have a fixed leaving time.',
        a2,
      ],
      [
        'price',
        'ask-price',
        'Which price information do you need first?',
        '新增费用核对。',
        'total',
        'Please tell me the total price for what I request.',
        'extras',
        'Please tell me which extra services cost more.',
        a2,
      ],
      [
        'routine',
        'describe-routine',
        'How much time do you usually spend styling your hair?',
        '真实习惯可由虚构选择表达。',
        'quick',
        'Only about five minutes in the morning.',
        'longer',
        'About twenty minutes; I enjoy styling it.',
        a2,
      ],
      [
        'growth',
        'ask-upkeep',
        'What would you like explained about keeping the style tidy?',
        '周期或居家打理。',
        'visits',
        'I would like to know when another trim might be needed.',
        'home',
        'I would like to know how to style it at home.',
        a2,
      ],
    ],
    a2,
  ),
  B1: dailyPack(
    scene,
    'B1',
    {
      canDoZh: '结合习惯解释剪发要求，并安排可见的剪前核对。',
      complexityZh: '明确各项偏好，讨论时间、价格及维护信息。',
      scaffoldingZh: '不生成真实造型建议；参考图与镜子帮助澄清。',
      registerZh: '合作且具体的咨询语气，可以礼貌坚持边界。',
    },
    [
      [
        'length',
        'choose-length',
        'What sort of change in length are you hoping for?',
        '不要与后续固定厘米矛盾。',
        'trim',
        'Only a trim; I want the ends tidied without a major change in length.',
        'shorter',
        'I want a noticeably shorter cut, rather than just tidying the ends.',
        b1,
      ],
      [
        'fringe',
        'choose-fringe',
        'How would you like the hair at the front to sit?',
        '额前偏好。',
        'fringe',
        'I would like a fringe across the front.',
        'sides',
        'I would like it swept to the sides, with no fringe.',
        b1,
      ],
      [
        'reference',
        'use-reference',
        'What would help you communicate the style most clearly?',
        '选择表达支架。',
        'picture',
        'Using a picture would help me point out the features I like.',
        'describe',
        'I would rather describe the style, because I do not want to copy a picture exactly.',
        b1,
      ],
      [
        'wash',
        'choose-wash',
        'Would you like washing included in the service you are requesting?',
        '可拒绝而无悬而未决。',
        'yes',
        'Yes, I would like to request a wash as well.',
        'no',
        'No, I would prefer the service without a wash.',
        b1,
      ],
      [
        'dry',
        'choose-finish',
        'What kind of finish would suit you after the cut?',
        '无论是否洗发都可选。',
        'styled',
        'I would like it styled so I can see one way of wearing the cut.',
        'natural',
        'I would prefer a natural finish rather than a carefully shaped look.',
        b1,
      ],
      [
        'check',
        'set-checkpoint',
        'How should the stylist check the intended length with you before starting?',
        '核对方法不重问长度。',
        'show',
        'Please show me the amount to be removed between your fingers.',
        'mirror',
        'Please use the mirror to show where the hair would end.',
        b1,
      ],
      [
        'parting',
        'choose-parting',
        'Which parting would feel natural to you?',
        '与主指令独立。',
        'middle',
        'A middle parting would feel natural; that is how I usually wear it.',
        'side',
        'A side parting would be more comfortable for me.',
        b1,
      ],
      [
        'products',
        'set-products',
        'What is your preference about styling products?',
        '明确有无。',
        'yes',
        'A small amount would be fine, as long as it does not feel heavy.',
        'no',
        'I would prefer no styling products, because I dislike the feeling.',
        b1,
      ],
      [
        'time',
        'state-time',
        'How much time can you allow for the appointment?',
        '未预约未保证。',
        'limit',
        'I can allow thirty minutes, so I need to know whether that is realistic.',
        'flexible',
        'I can be flexible; there is no fixed time I need to leave.',
        b1,
      ],
      [
        'price',
        'ask-price',
        'What would you like clarified about the cost before agreeing?',
        '不把咨询当授权。',
        'total',
        'I would like the total cost of the requested service explained first.',
        'extras',
        'I would like to know which optional services would add to the price.',
        b1,
      ],
      [
        'routine',
        'describe-routine',
        'What does your usual morning hair routine look like?',
        '两种投入。',
        'quick',
        'I spend about five minutes on it, so I need a quick routine.',
        'longer',
        'I usually spend about twenty minutes styling it and do not mind the effort.',
        b1,
      ],
      [
        'growth',
        'ask-upkeep',
        'Which aspect of maintaining the cut would you like to discuss?',
        '独立维护话题。',
        'visits',
        'How often I might need to return for a trim as it grows.',
        'home',
        'How I could style it at home without relying on a salon finish.',
        b1,
      ],
    ],
    b1,
  ),
  B2: dailyPack(
    scene,
    'B2',
    {
      canDoZh: '协商造型变化与日常打理、服务范围及时间成本。',
      complexityZh: '明确主长度与其他偏好分开，改变指令后无陈旧长度。',
      scaffoldingZh: '共享头发状态但不给固定效果承诺，要求解释偏好。',
      registerZh: '自信而礼貌，区分咨询、授权和服务预期。',
    },
    [
      [
        'length',
        'choose-length',
        'How far do you want the cut to depart from your current length?',
        '主要长度决策。',
        'trim',
        'I only want the ends tidied; preserving most of the current length is important to me.',
        'shorter',
        'I am looking for a clear reduction in length, not merely a tidier version of the same cut.',
        b2,
      ],
      [
        'fringe',
        'choose-fringe',
        'What would you like to happen to the front section?',
        '与总体剪短幅度分开。',
        'fringe',
        'I would like a fringe, with its precise shape discussed before cutting.',
        'sides',
        'I would prefer the front swept to the sides rather than cut into a fringe.',
        b2,
      ],
      [
        'reference',
        'use-reference',
        'Would an image or a verbal description communicate your preferences better?',
        '参考不等于复制保证。',
        'picture',
        'An image would help me identify the elements I like without expecting an exact copy.',
        'describe',
        'A verbal description would work better, because my preferences combine features from different styles.',
        b2,
      ],
      [
        'wash',
        'choose-wash',
        'Should washing form part of the service you are considering?',
        '附加服务独立。',
        'yes',
        'Yes, I would like a wash included in the service request.',
        'no',
        'No, I would prefer to leave washing out of the service.',
        b2,
      ],
      [
        'dry',
        'choose-finish',
        'Which finishing approach would best suit what you want from the visit?',
        '任何洗发、长度选项都兼容。',
        'styled',
        'A styled finish would help me see one way of presenting the result.',
        'natural',
        'A natural finish would suit me better, as I prefer a less sculpted look.',
        b2,
      ],
      [
        'check',
        'set-checkpoint',
        'What visual check would prevent a misunderstanding about the amount to be cut?',
        '方法不固定原长度。',
        'show',
        'Show the intended amount between your fingers before the scissors are used.',
        'mirror',
        'Use the mirror to indicate where the new ends would sit, so I can judge the overall effect.',
        b2,
      ],
      [
        'parting',
        'choose-parting',
        'Which parting would fit the way you prefer to wear your hair?',
        '不依赖已给刘海回答。',
        'middle',
        'A middle parting would fit my usual look and feel balanced to me.',
        'side',
        'A side parting would fit my preferences better than a central one.',
        b2,
      ],
      [
        'products',
        'set-products',
        'How much styling product, if any, would you be comfortable with?',
        '可明确零。',
        'yes',
        'A small amount would be fine, provided it does not leave the hair feeling stiff.',
        'no',
        'None, please; I would rather assess the cut without styling product in it.',
        b2,
      ],
      [
        'time',
        'state-time',
        'What time constraint should be considered before any service is agreed?',
        '咨询尚无服务。',
        'limit',
        'I need to leave in thirty minutes; please tell me if that makes the requested service impractical.',
        'flexible',
        'There is no fixed deadline, so I can allow a reasonable amount of time.',
        b2,
      ],
      [
        'price',
        'ask-price',
        'What cost information would help you make an informed choice about the service?',
        '非财务指导，普通报价咨询。',
        'total',
        'A total for the service as requested would help me decide whether to proceed.',
        'extras',
        'A breakdown of optional extras would help me decide which parts I actually want.',
        b2,
      ],
      [
        'routine',
        'describe-routine',
        'How much effort do you normally put into styling your hair each morning?',
        '现实使用限制。',
        'quick',
        'About five minutes; I would struggle with a style that required a lengthy daily routine.',
        'longer',
        'Around twenty minutes; I am comfortable spending time on styling rather than expecting it to happen by itself.',
        b2,
      ],
      [
        'growth',
        'ask-upkeep',
        'Which maintenance question matters more to you at this stage?',
        '两条新询问。',
        'visits',
        'How often the shape might need refreshing, so I can consider the commitment of repeat visits.',
        'home',
        'What home styling would involve, so I can compare it with my normal routine.',
        b2,
      ],
    ],
    b2,
  ),
  C1: dailyPack(
    scene,
    'C1',
    {
      canDoZh: '精确说明变化程度并协商可视核对、服务范围和维护投入。',
      complexityZh: '在审美偏好与时间成本之间解释取舍，避免误将参考当保证。',
      scaffoldingZh: '固定起始头发状态与工具，学习者组织具体限定和理由。',
      registerZh: '自然细腻且不含糊的咨询语域；CEFR商品服务和澄清。',
    },
    [
      [
        'length',
        'choose-length',
        'What degree of change in length would feel right to you?',
        '主长度事实可随change替换。',
        'trim',
        'A conservative trim is what I have in mind; I want the ends refreshed while keeping the overall length substantially as it is.',
        'shorter',
        'I am looking for a visibly shorter cut; simply tidying the ends would not give me the change I want.',
        c1,
      ],
      [
        'fringe',
        'choose-fringe',
        'How would you like the front section to frame your face?',
        '具体选择而不生成专业建议。',
        'fringe',
        'I would like a fringe, but would want to discuss its outline before committing to a particular shape.',
        'sides',
        'I would prefer the front swept to the sides; a fringe is not part of what I am requesting.',
        c1,
      ],
      [
        'reference',
        'use-reference',
        'What reference would help us distinguish the features you want from those you do not?',
        '图示与口述策略。',
        'picture',
        'A picture would be useful if I could point out the particular features I like, rather than treat the whole image as an instruction.',
        'describe',
        'I would rather describe the features individually, since no single picture captures the combination I have in mind.',
        c1,
      ],
      [
        'wash',
        'choose-wash',
        'Would you like washing to be included in the scope of the service under discussion?',
        '自然范围说明。',
        'yes',
        'Yes, please include a wash in what we are discussing, so I can consider the service as a whole.',
        'no',
        'No, I would prefer to exclude washing and keep the service focused on the other elements.',
        c1,
      ],
      [
        'dry',
        'choose-finish',
        'What would you want the finishing stage to show you about the result?',
        '不依赖未确认的洗发。',
        'styled',
        'I would choose a styled finish to see how the cut could look with deliberate shaping.',
        'natural',
        'I would choose a natural finish; I am more interested in how the cut falls on its own than in a polished salon effect.',
        c1,
      ],
      [
        'check',
        'set-checkpoint',
        'How could we make the intended length unambiguous before any cutting begins?',
        '支持变更后的最新长度。',
        'show',
        'Show me the amount you intend to remove between your fingers, and give me a moment to check it before starting.',
        'mirror',
        'Use the mirror to indicate where the ends would sit; that would make the overall change easier for me to judge.',
        c1,
      ],
      [
        'parting',
        'choose-parting',
        'Which parting would sit most comfortably with your personal preferences?',
        '不改变前部既定选择。',
        'middle',
        'I would favour a middle parting; the symmetry feels more natural to the way I usually wear my hair.',
        'side',
        'I would favour a side parting; a central one tends to feel too severe for my taste.',
        c1,
      ],
      [
        'products',
        'set-products',
        'What limits would you like to set on styling products?',
        '真实情境内的限定。',
        'yes',
        'A small amount is fine, but I would prefer a light finish rather than anything that leaves the hair rigid.',
        'no',
        'No styling products, please; I want to see how the cut behaves without them.',
        c1,
      ],
      [
        'time',
        'state-time',
        'Is there a time constraint that could affect what is realistic today?',
        '不能默认为准时服务。',
        'limit',
        'I need to leave in thirty minutes; if that is too restrictive, I would rather know before agreeing to the service.',
        'flexible',
        'I have no firm deadline, so the appointment does not need to be organised around a fixed departure time.',
        c1,
      ],
      [
        'price',
        'ask-price',
        'What would you need clarified about the quotation before making a decision?',
        '询问不构成付款授权。',
        'total',
        'I would want a clear total for the service we are discussing, so that there is no uncertainty about what it covers.',
        'extras',
        'I would want the optional elements priced separately, so I could judge which additions were worthwhile to me.',
        c1,
      ],
      [
        'routine',
        'describe-routine',
        'How much daily styling effort should the consultation take into account?',
        '高阶具体生活取舍。',
        'quick',
        'I usually allow about five minutes, so a cut that depended on elaborate daily styling would not be practical for me.',
        'longer',
        'I normally spend around twenty minutes styling my hair and am happy to make that effort for a look I enjoy.',
        c1,
      ],
      [
        'growth',
        'ask-upkeep',
        'Which longer-term aspect of the cut would you like to understand before deciding?',
        '不保证造型寿命。',
        'visits',
        'How frequently its shape might need refreshing; I would like to factor the return visits into my decision.',
        'home',
        'What reproducing the style at home would involve, particularly which parts of the salon finish are difficult to recreate.',
        c1,
      ],
    ],
    c1,
  ),
}
