import { dailyPack, type DailyScene, type Review } from './authoring'
const a1: Review = {
  state: 'model-reviewed',
  record:
    'daily-review.md#taxi-a1: all 12 named Q/A pairs and both variants read by Codex implementation agent, 2026-09-10',
}
const a2: Review = {
  state: 'model-reviewed',
  record:
    'daily-review.md#taxi-a2: all 12 named Q/A pairs and both variants read by Codex implementation agent, 2026-09-10',
}
const b1: Review = {
  state: 'model-reviewed',
  record:
    'daily-review.md#taxi-b1: all 12 named Q/A pairs and both variants read by Codex implementation agent, 2026-09-10',
}
const b2: Review = {
  state: 'model-reviewed',
  record:
    'daily-review.md#taxi-b2: all 12 named Q/A pairs and both variants read by Codex implementation agent, 2026-09-10',
}
const c1: Review = {
  state: 'model-reviewed',
  record:
    'daily-review.md#taxi-c1: all 12 named Q/A pairs and both variants read by Codex implementation agent, 2026-09-10',
}
const scene: DailyScene = {
  sceneId: 'daily-02',
  slug: 'taxi-ride',
  situations: [
    '虚构出租车发车前咨询。你坐在Oak Square停靠的车内，行李箱仍在车外，尚未装车。可去Central Station或Riverside Hotel，两处都有正门和侧门。广场的出租车标志与蓝色长椅是候选接车点。司机提到收费桥路线和免费绕行路线，未确定时间或价格。你可选择是否询问绕路，询问并不等于改道成功；练习中始终未发车、付款或保证可停车。短练只表达终点、行李协助和路线询问。',
    '虚构电话预约咨询，尚未预订。你计划从Oak Square前往Central Station或Riverside Hotel，带一只箱子。两处都有正门和侧门。广场的出租车标志与蓝色长椅是候选接车点。你先核对接车点和无法准时到场时的处理方式，再讨论行程细节。收费桥与免费绕行只是候选方案；所有要求均待司机确认，不能提供真实地址或付款资料。',
  ],
  paths: [
    {
      short: ['destination', 'bag', 'route'],
      standard: [
        'destination',
        'bag',
        'route',
        'urgency',
        'dropoff',
        'payment',
      ],
      extended: [
        'destination',
        'bag',
        'route',
        'urgency',
        'dropoff',
        'payment',
        'temperature',
        'quiet',
        'receipt',
        'fare',
      ],
    },
    {
      short: ['destination', 'bag', 'route'],
      standard: ['destination', 'bag', 'route', 'pickup', 'urgency', 'late'],
      extended: [
        'destination',
        'bag',
        'route',
        'pickup',
        'urgency',
        'late',
        'dropoff',
        'payment',
        'quiet',
        'fare',
      ],
    },
  ],
  closing:
    'Your taxi preferences have been practised. No ride, route change, stopping place, fare or payment has been confirmed.',
  partial:
    'We have practised part of the taxi enquiry. Unanswered details remain open, and no booking has been made.',
  repairs: {
    clarify: 'I can repeat the current taxi question.',
    struggle: 'A short answer about this ride detail is enough.',
    offTopic: 'Let us return to the taxi enquiry.',
    unknown:
      'That wording is not covered; it has not confirmed a destination or service.',
    changed:
      'Your earlier preference has been replaced in the practice; no real ride has changed.',
    refusedClosing:
      'This taxi practice has stopped. No booking or payment has been made.',
  },
}
export const taxiPacks = {
  A1: dailyPack(
    scene,
    'A1',
    {
      canDoZh: '用短句表达目的地、箱子协助和路线问题。',
      complexityZh: '一步一项；长练增加车内偏好与费用询问。',
      scaffoldingZh: '给定两个终点及虚构接车点，允许重复。',
      registerZh: '简单友好的乘车请求，不替司机确认服务。',
    },
    [
      [
        'destination',
        'state-destination',
        'Where would you like to go?',
        '选车站或酒店。',
        'station',
        'Central Station, please.',
        'hotel',
        'Riverside Hotel, please.',
        a1,
      ],
      [
        'bag',
        'request-loading',
        'Do you need help with your suitcase?',
        '箱子未装车。',
        'help',
        'Yes, please help me.',
        'self',
        'No, I can lift it.',
        a1,
      ],
      [
        'route',
        'discuss-route',
        'Would you like to ask about the free route?',
        '询问不是接受或完成改道。',
        'ask-free',
        'Yes. Is the free route possible?',
        'no-request',
        'No, thank you.',
        a1,
      ],
      [
        'urgency',
        'state-urgency',
        'Are you in a hurry?',
        '不保证准时。',
        'urgent',
        'Yes, I am in a hurry.',
        'flexible',
        'No, I have time.',
        a1,
      ],
      [
        'dropoff',
        'request-dropoff',
        'Which entrance would you prefer?',
        '只是下车偏好。',
        'main',
        'The main entrance, please.',
        'side',
        'The side entrance, please.',
        a1,
      ],
      [
        'payment',
        'ask-payment',
        'Which payment method would you like to ask about?',
        '不输入卡号。',
        'cash',
        'Can I pay cash?',
        'card',
        'Can I pay by card?',
        a1,
      ],
      [
        'temperature',
        'adjust-comfort',
        'Would you like the car warmer or cooler?',
        '表达偏好。',
        'warmer',
        'Warmer, please.',
        'cooler',
        'Cooler, please.',
        a1,
      ],
      [
        'quiet',
        'set-boundary',
        'Would you like a quiet ride?',
        '可以拒绝闲聊。',
        'quiet',
        'Yes, quiet, please.',
        'chat',
        'No, I would like to chat.',
        a1,
      ],
      [
        'receipt',
        'request-receipt',
        'Would you like to request a receipt?',
        '未开具收据。',
        'yes',
        'Yes, a receipt, please.',
        'no',
        'No receipt, thanks.',
        a1,
      ],
      [
        'fare',
        'clarify-fare',
        'What would you like to know about the price?',
        '费用尚未给出。',
        'estimate',
        'How much is the ride?',
        'extras',
        'Are there extra charges?',
        a1,
      ],
      [
        'pickup',
        'locate-pickup',
        'Where at Oak Square would you like to wait?',
        '两个虚构候选接车点。',
        'sign',
        'By the taxi sign, please.',
        'bench',
        'By the blue bench, please.',
        a1,
      ],
      [
        'late',
        'plan-delay',
        'If you are late, would you call or cancel the request?',
        '假设未来情况。',
        'call',
        'I would call.',
        'cancel',
        'I would cancel the request.',
        a1,
      ],
    ],
    a1,
  ),
  A2: dailyPack(
    scene,
    'A2',
    {
      canDoZh: '安排日常乘车所需细节，提出简单服务询问。',
      complexityZh: '联系时间压力、付款方式及接车备选。',
      scaffoldingZh: '虚构地点固定，问题给可预测选择；可用if。',
      registerZh: '简明礼貌请求，清楚区分想询问和已安排。',
    },
    [
      [
        'destination',
        'state-destination',
        'Which destination do you need today?',
        '选择唯一终点。',
        'station',
        'I need to go to Central Station.',
        'hotel',
        'I would like to go to Riverside Hotel.',
        a2,
      ],
      [
        'bag',
        'request-loading',
        'Would you like help putting the suitcase in the car?',
        '尚未装行李。',
        'help',
        'Yes, it is heavy. Could you help me?',
        'self',
        'No, thanks. I can put it in myself.',
        a2,
      ],
      [
        'route',
        'discuss-route',
        'Do you want to ask whether we could avoid the toll bridge?',
        '提问不等于线路确认。',
        'ask-free',
        'Yes, could we use the free route instead?',
        'no-request',
        'No, I do not need to ask about another route.',
        a2,
      ],
      [
        'urgency',
        'state-urgency',
        'How much of a hurry are you in?',
        '时间需求与路线讨论分开。',
        'urgent',
        'I am in a hurry, so please tell me the likely travel time.',
        'flexible',
        'I am not in a hurry; I have plenty of time.',
        a2,
      ],
      [
        'dropoff',
        'request-dropoff',
        'Where would you prefer to get out at the destination?',
        '下车位置需另确认。',
        'main',
        'I would prefer the main entrance.',
        'side',
        'The side entrance would suit me better.',
        a2,
      ],
      [
        'payment',
        'ask-payment',
        'What would you like to check about paying?',
        '只问方式。',
        'cash',
        'Could you tell me if cash is accepted?',
        'card',
        'Could you tell me if I can pay by card?',
        a2,
      ],
      [
        'temperature',
        'adjust-comfort',
        'What temperature would be comfortable for you?',
        '用比较级表达调整。',
        'warmer',
        'Could you make it a little warmer?',
        'cooler',
        'Could you make it a little cooler?',
        a2,
      ],
      [
        'quiet',
        'set-boundary',
        'Would you prefer to chat or have a quiet journey?',
        '尊重安静需求。',
        'quiet',
        'I would prefer a quiet journey, please.',
        'chat',
        'I would enjoy a little conversation.',
        a2,
      ],
      [
        'receipt',
        'request-receipt',
        'Do you need to ask for a receipt at the end?',
        '未完成行程。',
        'yes',
        'Yes, please. I need one for my records.',
        'no',
        'No, thank you. I do not need one.',
        a2,
      ],
      [
        'fare',
        'clarify-fare',
        'Which price detail should we check first?',
        '费用询问不依赖是否改道。',
        'estimate',
        'Please give me an estimate for the journey.',
        'extras',
        'Please explain any extra charges first.',
        a2,
      ],
      [
        'pickup',
        'locate-pickup',
        'Which meeting point at Oak Square would you prefer?',
        '提出接车点偏好。',
        'sign',
        'I would like to wait beside the taxi sign.',
        'bench',
        'I would prefer to wait beside the blue bench.',
        a2,
      ],
      [
        'late',
        'plan-delay',
        'What would you do if you could not reach the meeting point on time?',
        '表达条件行动。',
        'call',
        'I would call to explain that I was late.',
        'cancel',
        'I would cancel the request if I could not get there.',
        a2,
      ],
    ],
    a2,
  ),
  B1: dailyPack(
    scene,
    'B1',
    {
      canDoZh: '解释行程优先级并核对非例行安排。',
      complexityZh: '提出替代路线、理由和迟到处理，不虚构接受。',
      scaffoldingZh: '共享地点与候选路线支持原因表达，允许请求澄清。',
      registerZh: '自然乘客与司机协商，费用和偏好分项表达。',
    },
    [
      [
        'destination',
        'state-destination',
        'Where should the journey end?',
        '目的与地点绑定。',
        'station',
        'At Central Station, where I need to meet a friend.',
        'hotel',
        'At Riverside Hotel, where I will be staying.',
        b1,
      ],
      [
        'bag',
        'request-loading',
        'How would you like to handle the suitcase?',
        '区分需要帮助与自理。',
        'help',
        'I would appreciate help lifting it because it is awkward to carry.',
        'self',
        'I can lift it myself; please just leave space for it.',
        b1,
      ],
      [
        'route',
        'discuss-route',
        'Would you like to explore avoiding the toll bridge?',
        '更改仍只是询问。',
        'ask-free',
        'Yes, could you explain the free alternative before we settle the route?',
        'no-request',
        'No, I do not want to request a different route.',
        b1,
      ],
      [
        'urgency',
        'state-urgency',
        'Is arrival time a concern for you?',
        '不假定更改已确认。',
        'urgent',
        'Yes, I am short of time and need a realistic journey estimate.',
        'flexible',
        'No, I can be flexible about arrival time.',
        b1,
      ],
      [
        'dropoff',
        'request-dropoff',
        'Which entrance would make the arrival easier for you?',
        '两终点均有这些入口。',
        'main',
        'The main entrance would be easier to recognise.',
        'side',
        'I would prefer the side entrance because it is likely to be quieter.',
        b1,
      ],
      [
        'payment',
        'ask-payment',
        'Which payment option would you like clarified?',
        '不提供付款凭据。',
        'cash',
        'I would like to check whether I can pay the fare in cash.',
        'card',
        'I need to know whether card payment is available.',
        b1,
      ],
      [
        'temperature',
        'adjust-comfort',
        'Would you like any adjustment to the temperature?',
        '不编造已调整。',
        'warmer',
        'Yes, I feel cold; could you make it warmer?',
        'cooler',
        'Yes, the car feels warm to me; could you cool it slightly?',
        b1,
      ],
      [
        'quiet',
        'set-boundary',
        'Would conversation be welcome during the ride?',
        '礼貌边界。',
        'quiet',
        'I would rather have some quiet time, if that is all right.',
        'chat',
        'Yes, I would enjoy hearing a little about the area.',
        b1,
      ],
      [
        'receipt',
        'request-receipt',
        'Will you need to request a receipt?',
        '真实收据未生成。',
        'yes',
        'Yes, I would like a receipt so I can keep track of the cost.',
        'no',
        'No, I do not need a receipt for this journey.',
        b1,
      ],
      [
        'fare',
        'clarify-fare',
        'What fare information would help you decide whether to proceed?',
        '不说路线待定或已定，兼容两分支。',
        'estimate',
        'An estimated total would help me decide whether the ride fits my budget.',
        'extras',
        'Please explain any charges that might be added to the basic fare.',
        b1,
      ],
      [
        'pickup',
        'locate-pickup',
        'Where would you prefer to meet the driver at Oak Square?',
        '都是候选而非已预约。',
        'sign',
        'Beside the taxi sign, because it should be easy for us both to identify.',
        'bench',
        'Beside the blue bench, where I could sit while waiting.',
        b1,
      ],
      [
        'late',
        'plan-delay',
        'How would you handle being delayed on the way to the pickup point?',
        '仅未来假设。',
        'call',
        'I would call with an updated arrival time and ask whether the driver could wait.',
        'cancel',
        'I would cancel the request rather than leave the driver waiting.',
        b1,
      ],
    ],
    b1,
  ),
  B2: dailyPack(
    scene,
    'B2',
    {
      canDoZh: '协商路线、时间、费用的不确定因素与服务边界。',
      complexityZh: '通过理由和条件表达优先级，保持请求与确认分离。',
      scaffoldingZh: '场景提供选项，学习者承担权衡与准确限定。',
      registerZh: '直接但体谅对方的服务沟通，不滥用免责声明。',
    },
    [
      [
        'destination',
        'state-destination',
        'Which destination should the driver plan around?',
        '明确终点及用途。',
        'station',
        'Central Station; I am meeting someone there, so a recognisable entrance matters.',
        'hotel',
        'Riverside Hotel; I will have my suitcase with me when I arrive.',
        b2,
      ],
      [
        'bag',
        'request-loading',
        'What assistance, if any, would you like with loading the suitcase?',
        '可拒绝帮助而非暂停请求。',
        'help',
        'Help with lifting would be useful; I can manage the smaller movements myself.',
        'self',
        'I can load it myself, provided there is enough space to reach the luggage area.',
        b2,
      ],
      [
        'route',
        'discuss-route',
        'Would you like to compare the free alternative with the toll-bridge route?',
        '只是提出比较。',
        'ask-free',
        'Yes, please explain the difference in travel time before I decide whether to request the free route.',
        'no-request',
        'No, I do not need a comparison and am not requesting an alternative route.',
        b2,
      ],
      [
        'urgency',
        'state-urgency',
        'How important is keeping the journey time down?',
        '不确定时长可沟通。',
        'urgent',
        'It is important, but I would rather hear a realistic estimate than rely on an optimistic arrival time.',
        'flexible',
        'I have some flexibility, so a modest delay would not be a problem.',
        b2,
      ],
      [
        'dropoff',
        'request-dropoff',
        'Which entrance would you like us to consider for dropping you off?',
        '可停车仍待确认。',
        'main',
        'The main entrance would make it easier to orient myself when I get out.',
        'side',
        'The side entrance would suit me better, provided stopping there is permitted.',
        b2,
      ],
      [
        'payment',
        'ask-payment',
        'What payment information do you need before agreeing to the ride?',
        '不实施支付。',
        'cash',
        'Please confirm whether cash is accepted so I can decide whether this ride is practical.',
        'card',
        'Please confirm whether card payment is available before I agree to proceed.',
        b2,
      ],
      [
        'temperature',
        'adjust-comfort',
        'How could we make the temperature more comfortable?',
        '真实体感作为理由。',
        'warmer',
        'Could you raise it a little? The cool air is blowing directly towards me.',
        'cooler',
        'Could you lower it slightly? I find the current warmth rather uncomfortable.',
        b2,
      ],
      [
        'quiet',
        'set-boundary',
        'Would you welcome conversation, or prefer some space during the journey?',
        '不贬低司机。',
        'quiet',
        'I would appreciate a quiet journey; I need a little time to gather my thoughts.',
        'chat',
        'I would welcome conversation, especially a few suggestions about places nearby.',
        b2,
      ],
      [
        'receipt',
        'request-receipt',
        'Would you like a receipt included in your requests for the ride?',
        '请求未等于开具。',
        'yes',
        'Yes, please; having the fare documented would help me organise my expenses.',
        'no',
        'No, I have no need for a receipt and would prefer not to request one.',
        b2,
      ],
      [
        'fare',
        'clarify-fare',
        'Which aspect of the fare would you like explained before making a decision?',
        '不保留已拒绝的改道请求。',
        'estimate',
        'Please give me an estimated total, including the assumptions that could make it change.',
        'extras',
        'Please identify possible extras so that I can distinguish them from the basic fare.',
        b2,
      ],
      [
        'pickup',
        'locate-pickup',
        'Which proposed meeting point would be more practical for you?',
        '不擅自保证停车。',
        'sign',
        'The taxi sign would minimise confusion, provided the driver can stop there.',
        'bench',
        'The blue bench would let me wait with my suitcase without standing the whole time.',
        b2,
      ],
      [
        'late',
        'plan-delay',
        'What would you propose if you realised you would miss the pickup time?',
        '协商而非保证等待。',
        'call',
        'I would call promptly, explain the likely delay and ask whether waiting would still be practical.',
        'cancel',
        'I would cancel promptly so that the driver was not kept waiting for an uncertain arrival.',
        b2,
      ],
    ],
    b2,
  ),
  C1: dailyPack(
    scene,
    'C1',
    {
      canDoZh: '在行程选择中澄清隐含成本、优先级和可接受条件。',
      complexityZh: '以自然精确措辞处理不同利益与未确认安排，管理服务互动。',
      scaffoldingZh: '仅共享地点及路线候选，要求清楚限定请求范围。',
      registerZh: '灵活、体贴又明确的乘客语域；CEFR互动与服务量表。',
    },
    [
      [
        'destination',
        'state-destination',
        'Which destination should I take as the basis for this enquiry?',
        '明确而不假定已预订。',
        'station',
        'Central Station; I am meeting someone there, so I would value a clearly identifiable arrival point.',
        'hotel',
        'Riverside Hotel; I need to reach the building with my suitcase rather than be left some distance away.',
        c1,
      ],
      [
        'bag',
        'request-loading',
        'How much help would you like with getting the suitcase into the car?',
        '细分帮助范围。',
        'help',
        'I would appreciate help with the initial lift; once it is level with the luggage area, I can guide it into place.',
        'self',
        'I would prefer to handle it myself, as I know how to position it without putting pressure on the handle.',
        c1,
      ],
      [
        'route',
        'discuss-route',
        'Would it be worth examining the free route before discussing the rest of the ride?',
        '不把比较当选择。',
        'ask-free',
        'Yes; I would like to understand the time difference before weighing the saving against the inconvenience.',
        'no-request',
        'No; I am not asking for an alternative route, so there is no need to pursue that comparison.',
        c1,
      ],
      [
        'urgency',
        'state-urgency',
        'How should the driver understand your time constraints?',
        '现实地限定迫切性。',
        'urgent',
        'I am pressed for time, although an honest estimate would be more useful than reassurance that cannot be relied on.',
        'flexible',
        'My arrival time is flexible; a reasonable delay would be manageable if I knew what to expect.',
        c1,
      ],
      [
        'dropoff',
        'request-dropoff',
        'What would make a drop-off point suitable for you at the destination?',
        '入口偏好不锁定目的地。',
        'main',
        'I would favour the main entrance, where I could orient myself without carrying the suitcase around the building.',
        'side',
        'The side entrance would be preferable if stopping there is permitted; I would like to avoid the busier main approach.',
        c1,
      ],
      [
        'payment',
        'ask-payment',
        'Is there a payment arrangement you need clarified before you commit?',
        '只交流方式不输入凭据。',
        'cash',
        'Please establish whether cash is accepted; I would not want to discover a payment restriction at the end.',
        'card',
        'Please establish whether card payment is available, as that would determine whether I could proceed.',
        c1,
      ],
      [
        'temperature',
        'adjust-comfort',
        'What temperature adjustment would make the journey more comfortable?',
        '具体请求而非抽象限定。',
        'warmer',
        'Could you make it slightly warmer? The cold air is reaching my seat directly, and I am feeling chilly.',
        'cooler',
        'Could you lower the temperature a little? A small reduction would be enough; it need not be cold.',
        c1,
      ],
      [
        'quiet',
        'set-boundary',
        'Would you prefer conversation or a quieter journey?',
        '边界不需要防御性说明。',
        'quiet',
        'A quiet journey would be welcome; I have a few things to think through, so please do not take my silence personally.',
        'chat',
        'I would be happy to chat, especially if you have a local perspective on the area we are travelling through.',
        c1,
      ],
      [
        'receipt',
        'request-receipt',
        'Would a receipt be useful for your records?',
        '明确有无请求。',
        'yes',
        'Yes, please include a receipt among my requests; I would like a clear record of the amount charged.',
        'no',
        'No, I do not need one for my records, so there is no need to request a receipt.',
        c1,
      ],
      [
        'fare',
        'clarify-fare',
        'What distinction about the fare would you most like made clear?',
        '与路线请求的两种状态兼容。',
        'estimate',
        'I would like the estimated total distinguished from a fixed quotation, so I know how much variation to allow for.',
        'extras',
        'I would like any possible extras separated from the basic fare, particularly charges that depend on the route or waiting time.',
        c1,
      ],
      [
        'pickup',
        'locate-pickup',
        'Which meeting point would reduce the practical difficulty of finding each other?',
        '选择理由不同。',
        'sign',
        'The taxi sign seems the clearest reference, assuming the driver can stop there without obstructing access.',
        'bench',
        'The blue bench would suit me better with the suitcase; its distinctive colour should also make it easy to describe.',
        c1,
      ],
      [
        'late',
        'plan-delay',
        'How would you handle a delay without leaving the driver uncertain about your intentions?',
        '未来行动与对方权益。',
        'call',
        'I would call as soon as the delay became clear, give a realistic update and ask whether waiting was still workable.',
        'cancel',
        'If my arrival time became too uncertain, I would cancel promptly rather than repeatedly ask the driver to wait.',
        c1,
      ],
    ],
    c1,
  ),
}
